PSCF: Pscf::Rpg::AmIteratorBasis< D > Class Template Reference
Pscf::Rpg::AmIteratorBasis< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Self-Consistent Field Theory (SCFT) » Iterators
Anderson Mixing iterator with imposed space-group symmetry.
#include <AmIteratorBasis.h>
Public Types
using AmTmpl = AmIteratorTmpl<Iterator<D>, DArray<double> >
Alias for indirect base (grandparent) class.
Public Types inherited from Pscf::AmIteratorDArray< Iterator< D > >
using AmTmpl
Alias for base class template.
Public Member Functions
AmIteratorBasis (System< D > &system)
Constructor.
~AmIteratorBasis ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
void outputTimers (std::ostream &out) const
Output timing results to log file.
int solve (bool isContinuation=false)
Iterate to a solution.
void clearTimers ()
Clear timers.
Public Member Functions inherited from Pscf::AmIteratorDArray< Iterator< D > >
AmIteratorDArray ()=default
Constructor.
~AmIteratorDArray ()=default
Destructor.
Public Member Functions inherited from Pscf::AmIteratorTmpl< Iterator, DArray< double > >
AmIteratorTmpl ()
Constructor.
~AmIteratorTmpl ()
Destructor.
int solve (bool isContinuation=false)
Iterate to a solution.
void outputTimers (std::ostream &out) const
Log output timing results.
void clearTimers ()
Clear timers.
Protected Member Functions
void setup (bool isContinuation)
Setup iterator just before entering iteration loop.
int verbose () const
Verbosity level, allowed values 0, 1, or 2.
DArray< double > const & residual () const
Get the current residual vector by const reference.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
Protected Member Functions inherited from Pscf::AmIteratorTmpl< Iterator, DArray< double > >
void readErrorType (std::istream &in)
Read and validate the optional errorType string parameter.
virtual bool isValidErrorType ()
Checks if a string is a valid error type.
void readMixingParameters (std::istream &in, bool useLambdaRamp=true)
Read optional parameters used in default correction algorithm.
void allocateAM ()
Allocate memory required by AM algorithm, if necessary.
bool isAllocatedAM () const
Have data structures required by the AM algorithm been allocated?
virtual void clear ()
Clear information about history.
virtual double computeError (DArray< double > &residTrial, DArray< double > &stateTrial, std::string errorType, int verbose)
Compute and return error used to test for convergence.
double computeError (int verbose)
Compute and return error used to test for convergence.
double lambdaRampFactor ()
Compute ramped prefactor of mixing parameter lambda.
virtual double computeLambda ()
Compute mixing parameter for correction step of Anderson mixing.
int verbose () const
Verbosity level, allowed values 0, 1, or 2.
std::string errorType () const
Get error type string.
DArray< double > const & residual () const
Get the current residual vector by const reference.
DArray< double > const & state () const
Return the current state vector by const reference.
int totalItr ()
Return the total number of iterations needed to converge.
double timerTotal ()
Get total time.
double timerMDE ()
Get time spent solving the modified diffusion equation (MDE).
double timerAM ()
Get total time for AM algorithm, excluding MDE solution.
double timerResid ()
Get time spent computing residual.
double timerError ()
Get time evaluating scalar error.
double timerCoeff ()
Get time spent evaluating Anderson mixing coefficients.
double timerOmega ()
Get time spent updating w states.
Additional Inherited Members
Protected Attributes inherited from Pscf::AmIteratorTmpl< Iterator, DArray< double > >
double epsilon_
Error tolerance.
int maxItr_
Maximum number of iterations to attempt.
int maxHist_
Maximum number of basis vectors in AM algorithm.
int verbose_
Verbosity level.
std::string errorType_
Type of error criterion used to test convergence.
Detailed Description
template<int D>
class Pscf::Rpg::AmIteratorBasis< D >
Anderson Mixing iterator with imposed space-group symmetry.
See also
AmIteratorBasis
Definition at line 33 of file rpg/scft/iterator/AmIteratorBasis.h.
Member Typedef Documentation
AmTmpl
template<int D> using Pscf::Rpg::AmIteratorBasis< D >::AmTmpl = AmIteratorTmpl<Iterator<D>, DArray<double> >
Alias for indirect base (grandparent) class.
Definition at line 65 of file rpg/scft/iterator/AmIteratorBasis.h.
Constructor & Destructor Documentation
AmIteratorBasis()
template<int D> Pscf::Rpg::AmIteratorBasis< D >::AmIteratorBasis (System< D > & system)
Constructor.
Parameters
system parent system object
Definition at line 32 of file rpg/scft/iterator/AmIteratorBasis.tpp.
References Util::ParamComposite::setClassName().
~AmIteratorBasis()
template<int D> Pscf::Rpg::AmIteratorBasis< D >::~AmIteratorBasis ()
Destructor.
Definition at line 43 of file rpg/scft/iterator/AmIteratorBasis.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::AmIteratorBasis< D >::readParameters (std::istream & in) virtual
Read all parameters and initialize.
Parameters
in input filestream
Reimplemented from Pscf::AmIteratorTmpl< Iterator, DArray< double > >.
Definition at line 50 of file rpg/scft/iterator/AmIteratorBasis.tpp.
References Pscf::AmIteratorTmpl< Iterator< D >, DArray< double > >::readErrorType(), Pscf::AmIteratorTmpl< Iterator< D >, DArray< double > >::readMixingParameters(), readOptional(), readOptionalFSArray(), Pscf::AmIteratorTmpl< Iterator< D >, DArray< double > >::readParameters(), and UTIL_CHECK.
outputTimers()
template<int D> void Pscf::Rpg::AmIteratorBasis< D >::outputTimers (std::ostream & out) const
Output timing results to log file.
Parameters
out output stream for timer report
Definition at line 102 of file rpg/scft/iterator/AmIteratorBasis.tpp.
References Pscf::AmIteratorTmpl< Iterator< D >, DArray< double > >::outputTimers().
setup()
template<int D> void Pscf::Rpg::AmIteratorBasis< D >::setup (bool isContinuation) protected virtual
Setup iterator just before entering iteration loop.
Parameters
isContinuation Is this a continuation within a sweep?
Reimplemented from Pscf::AmIteratorTmpl< Iterator, DArray< double > >.
Definition at line 114 of file rpg/scft/iterator/AmIteratorBasis.tpp.
References Pscf::AmIteratorTmpl< Iterator< D >, DArray< double > >::setup().
solve()
template<int D> int Pscf::AmIteratorTmpl< Iterator, DArray< double > >::solve (bool isContinuation = false)
Iterate to a solution.
Parameters
isContinuation true iff continuation within a sweep
Returns
0 for convergence, 1 for failure
clearTimers()
template<int D> void Pscf::AmIteratorTmpl< Iterator, DArray< double > >::clearTimers ()
Clear timers.
verbose()
template<int D> int Pscf::AmIteratorTmpl< Iterator, DArray< double > >::verbose () const protected
Verbosity level, allowed values 0, 1, or 2.
residual()
template<int D> DArray< double > const & Pscf::AmIteratorTmpl< Iterator, DArray< double > >::residual () const protected
Get the current residual vector by const reference.
readOptional()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
Referenced by readParameters().
readParamCompositeOptional()
template<int D> void Util::ParamComposite::readParamCompositeOptional (std::istream & in, ParamComposite & child, bool next = true) protected
Add and attempt to read an optional child ParamComposite.
Parameters
in input stream for reading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 292 of file ParamComposite.cpp.
readOptionalFSArray()
template<int D> template<typename Type, int N> FSArrayParam< Type, N > & Util::ParamComposite::readOptionalFSArray (std::istream & in, const char * label, FSArray< Type, N > & array, int size) inline protected
Add and read an optional FSArray < Type, N > array parameter.
Parameters
in input stream for reading
label Label string for new array
array FSArray object
size logical size of array
Returns
reference to the new FSArrayParam<Type, N> object
Definition at line 427 of file ParamComposite.h.
Referenced by readParameters().
The documentation for this class was generated from the following files:
rpg/scft/iterator/AmIteratorBasis.h
rpg/scft/iterator/AmIteratorBasis.tpp