PSCF: Pscf::R1d::FieldIo Class Reference
Pscf::R1d::FieldIo Class Reference
Pscf namespace » Pscf::R1d - Real 1D fields
Read and write fields to file.
#include <FieldIo.h>
Public Member Functions
FieldIo ()
Constructor.
~FieldIo ()
Destructor.
void associate (Domain const &domain, FileMaster const &fileMaster)
Get and store addresses of associated objects.
void readFields (DArray< Field > &fields, std::istream &in)
Read a set of fields, one per monomer type.
void readFields (DArray< Field > &fields, std::string const &filename)
Read a set of fields, one per monomer type.
void writeField (Field const &field, std::ostream &out, bool writeHeader=true) const
Write a single field to an output stream.
void writeField (Field const &field, std::string const &filename, bool writeHeader=true) const
Write a single field to a file.
void writeFields (DArray< Field > const &fields, std::ostream &out, bool writeHeader=true) const
Write a set of fields, one per monomer type, to an output stream.
void writeFields (DArray< Field > const &fields, std::string const &filename, bool writeHeader=true) const
Write a set of fields, one per monomer type, to a named file.
void writeBlockCFields (Mixture const &mixture, std::ostream &out) const
Write block concentration fields for all blocks to an output stream.
void writeBlockCFields (Mixture const &mixture, std::string const &filename) const
Write block concentration fields for all blocks to a named file.
void writeVertexQ (Mixture const &mixture, int polymerId, int vertexId, std::ostream &out) const
Write product of incoming q fields for one vertex to stream.
void writeVertexQ (Mixture const &mixture, int polymerId, int vertexId, std::string const &filename) const
Write incoming q fields for a specified vertex.
void remesh (DArray< Field > const &fields, int nx, std::ostream &out)
Interpolate an array of fields onto a new mesh and write to stream.
void remesh (DArray< Field > const &fields, int nx, std::string const &filename)
Interpolate an array of fields onto a new mesh and write to file.
void extend (DArray< Field > const &fields, int m, std::ostream &out)
Add points to the end of a field mesh and write to stream.
void extend (DArray< Field > const &fields, int m, std::string const &filename)
Add points to the end of a field mesh and write to a file.
Detailed Description
Read and write fields to file.
Definition at line 27 of file r1d/misc/FieldIo.h.
Constructor & Destructor Documentation
FieldIo()
Pscf::R1d::FieldIo::FieldIo ()
Constructor.
Definition at line 34 of file r1d/misc/FieldIo.cpp.
~FieldIo()
Pscf::R1d::FieldIo::~FieldIo ()
Destructor.
Definition at line 40 of file r1d/misc/FieldIo.cpp.
Member Function Documentation
associate()
void Pscf::R1d::FieldIo::associate (Domain const & domain, FileMaster const & fileMaster)
Get and store addresses of associated objects.
Parameters
domain associated spatial domain
fileMaster associated FileMaster (for file paths)
Definition at line 44 of file r1d/misc/FieldIo.cpp.
Referenced by Pscf::R1d::Sweep::Sweep(), and Pscf::R1d::System::System().
readFields() [1/2]
void Pscf::R1d::FieldIo::readFields (DArray< Field > & fields, std::istream & in)
Read a set of fields, one per monomer type.
Precondition
File in must be open for reading.
Parameters
fields array of fields to read, indexed by monomer id
in input stream, open for reading.
Definition at line 60 of file r1d/misc/FieldIo.cpp.
References Util::Array< Data >::capacity(), and UTIL_CHECK.
Referenced by Pscf::R1d::System::readCommands(), and readFields().
readFields() [2/2]
void Pscf::R1d::FieldIo::readFields (DArray< Field > & fields, std::string const & filename)
Read a set of fields, one per monomer type.
This function uses the associated FileMaster to open an input file named filename before reading, and closes the file after reading.
Parameters
fields array of fields to read, indexed by monomer id.
filename name of input file
Definition at line 51 of file r1d/misc/FieldIo.cpp.
References Util::FileMaster::openInputFile(), and readFields().
writeField() [1/2]
void Pscf::R1d::FieldIo::writeField (Field const & field, std::ostream & out, bool writeHeader = true) const
Write a single field to an output stream.
Precondition
Stream out must be open for writing.
Parameters
field field defined on r-space grid (input)
out output stream
writeHeader write file header iff this bool is true
Definition at line 102 of file r1d/misc/FieldIo.cpp.
References Util::Array< Data >::capacity(), and UTIL_CHECK.
Referenced by Pscf::R1d::System::writeQ(), Pscf::R1d::System::writeQSlice(), and Pscf::R1d::System::writeQTail().
writeField() [2/2]
void Pscf::R1d::FieldIo::writeField (Field const & field, std::string const & filename, bool writeHeader = true) const
Write a single field to a file.
This function uses the associated FileMaster to open an output file named filename before writing, and closes the file after writing.
Parameters
field field defined on r-space grid (input)
filename output filename
writeHeader write file header iff this bool is true
Definition at line 93 of file r1d/misc/FieldIo.cpp.
References Util::FileMaster::openOutputFile(), and writeField().
Referenced by writeField().
writeFields() [1/2]
void Pscf::R1d::FieldIo::writeFields (DArray< Field > const & fields, std::ostream & out, bool writeHeader = true) const
Write a set of fields, one per monomer type, to an output stream.
Precondition
Stream out must be open for writing.
Parameters
fields set of fields to written.
out output stream
writeHeader write file header iff this bool is true
Definition at line 128 of file r1d/misc/FieldIo.cpp.
References Util::Array< Data >::capacity(), and UTIL_CHECK.
Referenced by Pscf::R1d::Sweep::outputSolution(), Pscf::R1d::System::readCommands(), Pscf::R1d::System::writeC(), and Pscf::R1d::System::writeW().
writeFields() [2/2]
void Pscf::R1d::FieldIo::writeFields (DArray< Field > const & fields, std::string const & filename, bool writeHeader = true) const
Write a set of fields, one per monomer type, to a named file.
This function uses the associated FileMaster to open an output file named filename before writing, and closes the file after writing.
Parameters
fields array of fields to read, indexed by monomer id
filename output filename
writeHeader write header iff this bool is true
Definition at line 118 of file r1d/misc/FieldIo.cpp.
References Util::FileMaster::openOutputFile(), and writeFields().
Referenced by writeFields().
writeBlockCFields() [1/2]
void Pscf::R1d::FieldIo::writeBlockCFields (Mixture const & mixture, std::ostream & out) const
Write block concentration fields for all blocks to an output stream.
Precondition
Stream out must be open for writing.
Parameters
mixture associated Mixture MDE solver object
out output stream
Definition at line 168 of file r1d/misc/FieldIo.cpp.
References Pscf::MixtureTmpl< TP, TS >::nBlock(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::MixtureTmpl< TP, TS >::nSolvent(), Pscf::R1d::Domain::nx(), Pscf::MixtureTmpl< TP, TS >::polymer(), and Pscf::MixtureTmpl< TP, TS >::solvent().
Referenced by Pscf::R1d::System::readCommands(), Pscf::R1d::System::writeBlockC(), and writeBlockCFields().
writeBlockCFields() [2/2]
void Pscf::R1d::FieldIo::writeBlockCFields (Mixture const & mixture, std::string const & filename) const
Write block concentration fields for all blocks to a named file.
This function uses the associated FileMaster to open an output file named filename before writing, and closes the file after writing.
Parameters
mixture associated Mixture MDE solver object
filename name of output file
Definition at line 156 of file r1d/misc/FieldIo.cpp.
References Util::FileMaster::openOutputFile(), and writeBlockCFields().
writeVertexQ() [1/2]
void Pscf::R1d::FieldIo::writeVertexQ (Mixture const & mixture, int polymerId, int vertexId, std::ostream & out) const
Write product of incoming q fields for one vertex to stream.
Precondition
Stream out must be open for writing.
Parameters
mixture associated Mixture MDE solver object
polymerId integer id of polymer species
vertexId integer id of vertex (end or junction)
out output stream
Definition at line 216 of file r1d/misc/FieldIo.cpp.
References Pscf::Vertex::inPropagatorId(), Pscf::PolymerTmpl< Block >::nBlock(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::R1d::Domain::nx(), Pscf::MixtureTmpl< TP, TS >::polymer(), Util::product(), Pscf::PolymerTmpl< Block >::propagator(), Pscf::Vertex::size(), UTIL_CHECK, and Pscf::PolymerTmpl< Block >::vertex().
Referenced by Pscf::R1d::System::readCommands(), and writeVertexQ().
writeVertexQ() [2/2]
void Pscf::R1d::FieldIo::writeVertexQ (Mixture const & mixture, int polymerId, int vertexId, std::string const & filename) const
Write incoming q fields for a specified vertex.
Parameters
mixture associated Mixture MDE solver object
polymerId integer id of polymer species
vertexId integer id of vertex (end or junction)
filename name of output file
Definition at line 203 of file r1d/misc/FieldIo.cpp.
References Util::FileMaster::openOutputFile(), and writeVertexQ().
remesh() [1/2]
void Pscf::R1d::FieldIo::remesh (DArray< Field > const & fields, int nx, std::ostream & out)
Interpolate an array of fields onto a new mesh and write to stream.
Parameters
fields field to be remeshed
nx number of grid points in new mesh
out output stream for remeshed field
Definition at line 269 of file r1d/misc/FieldIo.cpp.
References Util::Array< Data >::capacity(), Pscf::R1d::Domain::dx(), Pscf::R1d::Domain::nx(), UTIL_CHECK, Pscf::R1d::Domain::xMax(), and Pscf::R1d::Domain::xMin().
Referenced by Pscf::R1d::System::readCommands(), and remesh().
remesh() [2/2]
void Pscf::R1d::FieldIo::remesh (DArray< Field > const & fields, int nx, std::string const & filename)
Interpolate an array of fields onto a new mesh and write to file.
Parameters
fields field to be remeshed
nx number of grid points in new mesh
filename name of output file for remeshed field
Definition at line 256 of file r1d/misc/FieldIo.cpp.
References Util::FileMaster::openOutputFile(), and remesh().
extend() [1/2]
void Pscf::R1d::FieldIo::extend (DArray< Field > const & fields, int m, std::ostream & out)
Add points to the end of a field mesh and write to stream.
Values at the added mesh points are taken to be the same as those at the last mesh point of the original mesh.
Parameters
fields array of fields to be extended
m number of added grid points
out output stream for extended field
Definition at line 342 of file r1d/misc/FieldIo.cpp.
References Util::Array< Data >::capacity(), and UTIL_CHECK.
Referenced by extend(), and Pscf::R1d::System::readCommands().
extend() [2/2]
void Pscf::R1d::FieldIo::extend (DArray< Field > const & fields, int m, std::string const & filename)
Add points to the end of a field mesh and write to a file.
Values at the added mesh points are taken to be the same as those at the last mesh point of the original mesh.
Parameters
fields field to be remeshed
m number of added grid points
filename name of output file for remeshed field
Definition at line 329 of file r1d/misc/FieldIo.cpp.
References extend(), and Util::FileMaster::openOutputFile().
The documentation for this class was generated from the following files:
r1d/misc/FieldIo.h
r1d/misc/FieldIo.cpp