PSCF: Pscf::Rpg::Polymer< D > Class Template Reference
Pscf::Rpg::Polymer< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Solvers
Descriptor and solver for one polymer species.
#include <Polymer.h>
Public Types
using Base = PolymerTmpl< Block<D> >
Base class, partial template specialization.
using BlockT = Block<D>
Block type, for a block within a block polymer.
using PropagatorT = typename BlockT::PropagatorT
Propagator type, for one direction within a block.
Public Types inherited from Pscf::PolymerTmpl< Block< D > >
using BlockT
Block of a block polymer.
using PropagatorT
Modified diffusion equation solver for one block, in one direction.
Public Types inherited from Pscf::Species
enum Ensemble
Statistical ensemble for number of molecules.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Polymer ()
Constructor.
~Polymer ()
Destructor.
void setNParams (int nParams)
Set the number of unit cell parameters.
void clearUnitCellData ()
Clear all data that depends on unit cell parameters.
void compute (DArray< RField< D > > const &wFields, double phiTot=1.0)
Compute MDE solutions and block concentrations.
void computeStress ()
Compute SCFT stress contribution from this polymer species.
double stress (int n)
Get derivative of free energy w/ respect to a unit cell parameter.
Edge & edge (int id) final
Get a specified Edge (block descriptor) by non-const reference.
Edge const & edge (int id) const final
Get a specified Edge (block descriptor) by const reference.
Block< D > & block (int id)
Get a specified Block (solver and descriptor).
Block< D > const & block (int id) const
Get a specified Block (solver and descriptor) by const reference.
PropagatorT & propagator (int blockId, int directionId)
Get the propagator for a specific block and direction (non-const).
PropagatorT const & propagator (int blockId, int directionId) const
Get the propagator for a specific block and direction (const).
PropagatorT & propagator (int id)
Get a propagator indexed in order of computation (non-const).
const Vertex & vertex (int id) const
Get a specified Vertex by const reference.
Pair< int > const & propagatorId (int id) const
Get a propagator identifier, indexed by order of computation.
Pair< int > const & path (int is, int it) const
Get an id for a propagator from one vertex towards a target.
int nBlock () const
Number of blocks.
int nVertex () const
Number of vertices (junctions and chain ends).
int nPropagator () const
Number of propagators (2*nBlock).
double length () const
Sum of the lengths of all blocks in the polymer (thread model).
int nBead () const
Total number of beads in the polymer (bead model).
PolymerType::Enum type () const
Get Polymer type (Branched or Linear)
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble () const
Get the statistical ensemble for this species (open or closed).
void setPhi (double phi)
Set value of phi (volume fraction), if ensemble is closed.
void setMu (double mu)
Set value of mu (chemical potential), if ensemble is closed.
Public Member Functions inherited from Pscf::PolymerTmpl< Block< D > >
PolymerTmpl ()
Constructor.
~PolymerTmpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read and initialize.
Block< D > & block (int id)
Get a specified Block (solver and descriptor).
Block< D > const & block (int id) const
Get a specified Block (solver and descriptor) by const reference.
PropagatorT & propagator (int blockId, int directionId)
Get the propagator for a specific block and direction (non-const).
PropagatorT const & propagator (int blockId, int directionId) const
Get the propagator for a specific block and direction (const).
PropagatorT & propagator (int id)
Get a propagator indexed in order of computation (non-const).
Public Member Functions inherited from Pscf::PolymerSpecies
PolymerSpecies ()
Constructor.
~PolymerSpecies ()
Destructor.
const Vertex & vertex (int id) const
Get a specified Vertex by const reference.
int nBlock () const
Number of blocks.
int nVertex () const
Number of vertices (junctions and chain ends).
int nPropagator () const
Number of propagators (2*nBlock).
double length () const
Sum of the lengths of all blocks in the polymer (thread model).
int nBead () const
Total number of beads in the polymer (bead model).
PolymerType::Enum type () const
Get Polymer type (Branched or Linear)
Pair< int > const & propagatorId (int id) const
Get a propagator identifier, indexed by order of computation.
Pair< int > const & path (int is, int it) const
Get an id for a propagator from one vertex towards a target.
Public Member Functions inherited from Pscf::Species
Species ()
Default constructor.
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble () const
Get the statistical ensemble for this species (open or closed).
void setPhi (double phi)
Set value of phi (volume fraction), if ensemble is closed.
void setMu (double mu)
Set value of mu (chemical potential), if ensemble is closed.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Pscf::PolymerTmpl< Block< D > >
void allocateBlocks () final
Allocate array of Block objects.
void readBlocks (std::istream &in) final
Read array of data for blocks from parameter file.
Protected Member Functions inherited from Pscf::PolymerSpecies
virtual void makePlan ()
Make a plan for order in which propagators should be computed.
void makePaths ()
Create a matrix of vertex-to-vertex path signposts.
Protected Member Functions inherited from Pscf::Species
void setQ (double q)
Set q and compute phi or mu (depending on the ensemble).
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
template<int D>
class Pscf::Rpg::Polymer< D >
Descriptor and solver for one polymer species.
The phi() and mu() accessor functions, which are inherited from PolymerSpecies, return the value of phi (spatial average volume fraction of a species) or mu (species chemical potential) computed in the last call of the compute function. If the ensemble for this species is closed, phi is read from the parameter file and mu is computed. If the ensemble is open, mu is read from the parameter file and phi is computed.
The block concentrations stored in the constituent Block<D> objects contain the block concentrations (i.e., volume fractions) computed in the most recent call of the compute function. These can be accessed using the Block<D>::cField() function.
Definition at line 57 of file rpg/solvers/Polymer.h.
Member Typedef Documentation
Base
template<int D> using Pscf::Rpg::Polymer< D >::Base = PolymerTmpl< Block<D> >
Base class, partial template specialization.
Definition at line 65 of file rpg/solvers/Polymer.h.
BlockT
template<int D> using Pscf::Rpg::Polymer< D >::BlockT = Block<D>
Block type, for a block within a block polymer.
Definition at line 68 of file rpg/solvers/Polymer.h.
PropagatorT
template<int D> using Pscf::Rpg::Polymer< D >::PropagatorT = typename BlockT::PropagatorT
Propagator type, for one direction within a block.
Definition at line 71 of file rpg/solvers/Polymer.h.
Constructor & Destructor Documentation
Polymer()
template<int D> Pscf::Rpg::Polymer< D >::Polymer ()
Constructor.
Definition at line 23 of file rpg/solvers/Polymer.tpp.
References Util::ParamComposite::setClassName().
~Polymer()
template<int D> Pscf::Rpg::Polymer< D >::~Polymer ()
Destructor.
Definition at line 31 of file rpg/solvers/Polymer.tpp.
Member Function Documentation
setNParams()
template<int D> void Pscf::Rpg::Polymer< D >::setNParams (int nParams)
Set the number of unit cell parameters.
Parameters
nParams the number of unit cell parameters
Definition at line 38 of file rpg/solvers/Polymer.tpp.
clearUnitCellData()
template<int D> void Pscf::Rpg::Polymer< D >::clearUnitCellData ()
Clear all data that depends on unit cell parameters.
This function should be called after each change in the unit cell. It calls Block<D>::clearUnitCellData() for all blocks in this polymer.
Definition at line 45 of file rpg/solvers/Polymer.tpp.
References block(), and nBlock().
compute()
template<int D> void Pscf::Rpg::Polymer< D >::compute (DArray< RField< D > > const & wFields, double phiTot = 1.0)
Compute MDE solutions and block concentrations.
This function sets up w-fields in the MDE solvers for all blocks and then calls the base class PolymerTmpl solve function. This solves the MDE for all propagators and computes the properly scaled volume fraction fields for all blocks. After this function is called, the associated Block objects store pre-computed propagator solutions and block volume fraction fields.
The parameter phiTot is only relevant to problems such as thin films in which the material is excluded from part of the unit cell by imposing an inhogeneous constraint on the sum of the monomer concentrations (i.e., a "mask").
Parameters
wFields array of chemical potential fields.
phiTot volume fraction of unit cell occupied by material
Definition at line 57 of file rpg/solvers/Polymer.tpp.
References block(), Pscf::PolymerModel::isThread(), length(), nBead(), nBlock(), phi(), and q().
computeStress()
template<int D> void Pscf::Rpg::Polymer< D >::computeStress ()
Compute SCFT stress contribution from this polymer species.
This function computes contributions from this species to the derivatives of SCFT free energy per monomer with respect to unit cell parameters and stores the values. It requires that the MDE has been solved for all blocks prior to entry, and so must be called after the compute function.
Definition at line 91 of file rpg/solvers/Polymer.tpp.
References block(), Pscf::PolymerModel::isThread(), length(), nBead(), nBlock(), phi(), q(), and UTIL_CHECK.
stress()
template<int D> double Pscf::Rpg::Polymer< D >::stress (int n) inline
Get derivative of free energy w/ respect to a unit cell parameter.
Get the contribution from this polymer species to the derivative of free energy per monomer with respect to unit cell parameter n, as computed by the most recent call to computeStress.
Parameters
n unit cell parameter index
Definition at line 181 of file rpg/solvers/Polymer.h.
edge() [1/2]
template<int D> Edge & Pscf::PolymerTmpl< Block< D > >::edge (int id) final virtual
Get a specified Edge (block descriptor) by non-const reference.
The edge member functions implements pure virtual functions defined by the PolymerSpecies base class, and provide access to each Block as a reference to an Edge (a block descriptor).
Parameters
id block index, 0 <= id < nBlock
Reimplemented from Pscf::PolymerTmpl< Block< D > >.
edge() [2/2]
template<int D> Edge const & Pscf::PolymerTmpl< Block< D > >::edge (int id) const final virtual
Get a specified Edge (block descriptor) by const reference.
Parameters
id block index, 0 <= id < nBlock
Reimplemented from Pscf::PolymerTmpl< Block< D > >.
block() [1/2]
template<int D> Block< D > & Pscf::PolymerTmpl< Block< D > >::block (int id)
Get a specified Block (solver and descriptor).
Parameters
id block index, 0 <= id < nBlock
Referenced by clearUnitCellData(), compute(), and computeStress().
block() [2/2]
template<int D> Block< D > const & Pscf::PolymerTmpl< Block< D > >::block (int id) const
Get a specified Block (solver and descriptor) by const reference.
Parameters
id block index, 0 <= id < nBlock
propagator() [1/3]
template<int D> PropagatorT & Pscf::PolymerTmpl< Block< D > >::propagator (int blockId, int directionId)
Get the propagator for a specific block and direction (non-const).
For an edge that terminates at vertices with vertex indices given by the return values of Edge::vertexId(0) and Edge::vertexId(1):
direction 0 propagates from vertexId(0) to vertexId(1)
direction 1 propagates from vertexId(1) to vertexId(0)
Parameters
blockId integer index of associated block
directionId integer index for direction (0 or 1)
propagator() [2/3]
template<int D> PropagatorT const & Pscf::PolymerTmpl< Block< D > >::propagator (int blockId, int directionId) const
Get the propagator for a specific block and direction (const).
Parameters
blockId integer index of associated block
directionId integer index for direction (0 or 1)
propagator() [3/3]
template<int D> PropagatorT & Pscf::PolymerTmpl< Block< D > >::propagator (int id)
Get a propagator indexed in order of computation (non-const).
The propagator index argument must satisfy 0 <= id < 2*nBlock.
Parameters
id propagator index, in order of computation plan
vertex()
template<int D> Vertex const & Pscf::PolymerSpecies::vertex (int id) const inline
Get a specified Vertex by const reference.
Chain ends and block junctions are all vertices.
Parameters
id vertex index, 0 <= id < nVertex
Definition at line 124 of file PolymerSpecies.h.
propagatorId()
template<int D> Pair< int > const & Pscf::PolymerSpecies::propagatorId (int id) const inline
Get a propagator identifier, indexed by order of computation.
The return value is a pair of integers that identifies a directed edge, or a propagator. The first integer is a block index between 0 and nBlock - 1, and the second is a propagator direction id, which must be 0 or 1. By convention, direction 0 of Edge i propagates from vertex edge(i).vertexId(0) to vertex edge(i).vertexId(1), while direction 1 propagates in the other direction, from edge(i).vertexId(1) to edge(i).vertexId(0).
The propagators are indexed in an order that is computed by the protected function PolymerSpecies::makePlan. The indexing is chosen such that, if MDEs for different propagators are solved in sequential order by propagator index, then information required to construct the initial condition for the MDE within each propagator (the source slice) is guaranteed to be available from the solution of previous calculations.
Parameters
id propagator index, in order of computation plan
Definition at line 192 of file PolymerSpecies.h.
path()
template<int D> Pair< int > const & Pscf::PolymerSpecies::path (int is, int it) const inline
Get an id for a propagator from one vertex towards a target.
For is != it, the return value is an identifier for an outgoing propagator that begins at the source vertex (vertex index is) and is the first edge of the directed path that leads from the source vertex to the target vertex (vertex id it). The return value is a pair of integers analogous to that returned by the propagatorId(int) member function, for which the first element is a block index and the second element is a direction id (0 or 1) for the propagator direction for that block that is outgoing from from the source vertex along the unique path leading to the target vertex. The requirement that the propagator be outgoing from vertex is implies that if path(is, it) == [ib, id], then edge(ib).vertexId(id) == is.
Parameters
is index of the source vertex
it index of the target vertex
Definition at line 212 of file PolymerSpecies.h.
nBlock()
template<int D> int Pscf::PolymerSpecies::nBlock () const inline
Number of blocks.
Definition at line 133 of file PolymerSpecies.h.
Referenced by clearUnitCellData(), compute(), and computeStress().
nVertex()
template<int D> int Pscf::PolymerSpecies::nVertex () const inline
Number of vertices (junctions and chain ends).
A theorem of graph theory tells us that, for any linear or acyclic branched polymer, nVertex = nBlock + 1.
Definition at line 141 of file PolymerSpecies.h.
nPropagator()
template<int D> int Pscf::PolymerSpecies::nPropagator () const inline
Number of propagators (2*nBlock).
Definition at line 146 of file PolymerSpecies.h.
length()
template<int D> double Pscf::PolymerSpecies::length () const
Sum of the lengths of all blocks in the polymer (thread model).
Precondition: PolymerModel::isThread()
Definition at line 153 of file PolymerSpecies.cpp.
Referenced by compute(), Pscf::Rpg::Simulator< D >::computeHamiltonian(), and computeStress().
nBead()
template<int D> int Pscf::PolymerSpecies::nBead () const
Total number of beads in the polymer (bead model).
Precondition: PolymerModel::isBead()
Definition at line 160 of file PolymerSpecies.cpp.
Referenced by compute(), Pscf::Rpg::Simulator< D >::computeHamiltonian(), and computeStress().
type()
template<int D> PolymerType::Enum Pscf::PolymerSpecies::type () const inline
Get Polymer type (Branched or Linear)
Definition at line 165 of file PolymerSpecies.h.
phi()
template<int D> double Pscf::Species::phi () const inline
Get the overall volume fraction for this species.
Definition at line 62 of file Species.h.
Referenced by compute(), Pscf::Rpg::Simulator< D >::computeHamiltonian(), and computeStress().
mu()
template<int D> double Pscf::Species::mu () const inline
Get the chemical potential for this species (units kT=1).
Definition at line 67 of file Species.h.
Referenced by Pscf::Rpg::Simulator< D >::computeHamiltonian().
q()
template<int D> double Pscf::Species::q () const inline
Get the molecular partition function for this species.
Definition at line 72 of file Species.h.
Referenced by compute(), and computeStress().
ensemble()
template<int D> Species::Ensemble Pscf::Species::ensemble () const inline
Get the statistical ensemble for this species (open or closed).
Definition at line 77 of file Species.h.
setPhi()
template<int D> void Pscf::Species::setPhi (double phi)
Set value of phi (volume fraction), if ensemble is closed.
An initial value for phi or mu is normally read from a parameter file. This function is provided for use by a sweep or other procedure in which phi for a species with a closed enesmble is modified after initialization. It is an error to call setPhi for a polymer species with an open ensemble.
Exceptions
Exception if ensemble is open
Parameters
phi new volume fraction value for this species
Definition at line 91 of file Species.cpp.
setMu()
template<int D> void Pscf::Species::setMu (double mu)
Set value of mu (chemical potential), if ensemble is closed.
An initial value for phi or mu is normally read from a parameter file. This function is provided for use in a sweep or other procedure in which mu for a species with an open enesmble is modified after initialization. It is an error to call setMu for a polymer species with a closed ensemble.
Exceptions
Exception if ensemble is closed
Parameters
mu new chemical potential value for this species
Definition at line 105 of file Species.cpp.
The documentation for this class was generated from the following files:
rpg/solvers/Polymer.h
rpg/solvers/Polymer.tpp