PSCF: Util::TextFileOArchive Class Reference
Util::TextFileOArchive Class Reference
Util namespace » Serialization
Saving archive for character based ostream.
#include <TextFileOArchive.h>
Public Member Functions
TextFileOArchive ()
Constructor.
TextFileOArchive (std::string filename)
Constructor.
TextFileOArchive (std::ofstream &file)
Constructor.
virtual ~TextFileOArchive ()
Destructor.
std::ofstream & file ()
Get the underlying ifstream by reference.
template<typename T>
TextFileOArchive & operator<< (T &data)
Save one T object to this archive via the << (insertion) operator.
template<typename T>
TextFileOArchive & operator& (T &data)
Save one T object to this archive.
template<typename T, size_t N>
TextFileOArchive & operator<< (T(&data)[N])
Save a fixed size array via operator <<.
template<typename T, size_t N>
TextFileOArchive & operator& (T(&data)[N])
Save a fixed size array via operator &.
template<typename T>
void pack (const T &data)
Save one T object to this archive.
template<typename T>
void pack (const T *array, int n)
Save a C-array of T objects to this archive.
template<typename T>
void pack (const T *array, int m, int n, int np)
Save a 2D C array to this archive.
Static Public Member Functions
static bool is_saving ()
Returns true;.
static bool is_loading ()
Returns false;.
Detailed Description
Saving archive for character based ostream.
Definition at line 30 of file TextFileOArchive.h.
Constructor & Destructor Documentation
TextFileOArchive() [1/3]
Util::TextFileOArchive::TextFileOArchive ()
Constructor.
Definition at line 16 of file TextFileOArchive.cpp.
Referenced by operator&(), operator&(), operator<<(), and operator<<().
TextFileOArchive() [2/3]
Util::TextFileOArchive::TextFileOArchive (std::string filename)
Constructor.
Parameters
filename name of file to open for reading.
Definition at line 25 of file TextFileOArchive.cpp.
TextFileOArchive() [3/3]
Util::TextFileOArchive::TextFileOArchive (std::ofstream & file)
Constructor.
Parameters
file output file
Definition at line 35 of file TextFileOArchive.cpp.
References file().
~TextFileOArchive()
Util::TextFileOArchive::~TextFileOArchive () virtual
Destructor.
Definition at line 48 of file TextFileOArchive.cpp.
Member Function Documentation
is_saving()
bool Util::TextFileOArchive::is_saving () inline static
Returns true;.
Definition at line 157 of file TextFileOArchive.h.
is_loading()
bool Util::TextFileOArchive::is_loading () inline static
Returns false;.
Definition at line 160 of file TextFileOArchive.h.
file()
std::ofstream & Util::TextFileOArchive::file ()
Get the underlying ifstream by reference.
Definition at line 58 of file TextFileOArchive.cpp.
Referenced by TextFileOArchive().
operator<<() [1/2]
template<typename T> TextFileOArchive & Util::TextFileOArchive::operator<< (T & data) inline
Save one T object to this archive via the << (insertion) operator.
Implementation calls a global serialize function.
Parameters
data object to be saved to archive
Definition at line 169 of file TextFileOArchive.h.
References TextFileOArchive().
operator&() [1/2]
template<typename T> TextFileOArchive & Util::TextFileOArchive::operator& (T & data) inline
Save one T object to this archive.
Equivalent to operator <<.
Parameters
data object to be saved to archive
Definition at line 179 of file TextFileOArchive.h.
References TextFileOArchive().
operator<<() [2/2]
template<typename T, size_t N> TextFileOArchive & Util::TextFileOArchive::operator<< (T(&) data[N]) inline
Save a fixed size array via operator <<.
Implementation applies the serialize function to each element. The template should thus work for any type T for which a serialize function exists.
Parameters
data array of fixed size N with elements of type T
Definition at line 189 of file TextFileOArchive.h.
References TextFileOArchive().
operator&() [2/2]
template<typename T, size_t N> TextFileOArchive & Util::TextFileOArchive::operator& (T(&) data[N]) inline
Save a fixed size array via operator &.
Equivalent to << operator.
Parameters
data array of fixed size N with elements of type T
Definition at line 201 of file TextFileOArchive.h.
References TextFileOArchive().
pack() [1/3]
template<typename T> void Util::TextFileOArchive::pack (const T & data) inline
Save one T object to this archive.
Parameters
data object to be written to file
Definition at line 215 of file TextFileOArchive.h.
pack() [2/3]
template<typename T> void Util::TextFileOArchive::pack (const T * array, int n) inline
Save a C-array of T objects to this archive.
Parameters
array C array of T objects (pointer to first element)
n number of elements
Definition at line 234 of file TextFileOArchive.h.
pack() [3/3]
template<typename T> void Util::TextFileOArchive::pack (const T * array, int m, int n, int np) inline
Save a 2D C array to this archive.
Parameters
array address of first element array[0][0] of 2D array
m logical number of rows
n logical number of columns
np physical number of columns
Definition at line 246 of file TextFileOArchive.h.
The documentation for this class was generated from the following files:
TextFileOArchive.h
TextFileOArchive.cpp