PSCF: Pscf::Fd1d::Sweep Class Reference
Pscf::Fd1d::Sweep Class Reference
Pscf namespace » Finite-Difference 1D » Sweep
Solve a sequence of problems along a line in parameter space.
#include <Sweep.h>
Public Member Functions
Sweep (System &system)
Constructor.
~Sweep ()
Destructor.
virtual void readParameters (std::istream &in)
Read ns and baseFileName parameters.
virtual void outputSolution (std::string const &stateFileName)
Output information after obtaining a converged solution.
virtual void outputSummary (std::ostream &outFile)
Output data to a running summary.
Public Member Functions inherited from Pscf::SweepTmpl< DArray< System::WField > >
~SweepTmpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read ns and baseFileName parameters.
virtual void sweep ()
Iterate to solution.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void readParam (std::istream &in)=0
Read parameter(s) from file.
virtual void writeParam (std::ostream &out) const =0
Read parameter(s) to file.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
virtual void save (OArchive &ar)=0
Save to an archive.
virtual void load (IArchive &ar)=0
Load from an archive.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from Pscf::Fd1d::SystemAccess
SystemAccess ()
Default constructor.
SystemAccess (System &system)
Constructor.
~SystemAccess ()
Destructor.
virtual void setSystem (System &system)
Set the system after construction.
const System & system () const
Get parent System by reference.
System & system ()
Get parent System by reference.
const Mixture & mixture () const
Get Mixture by reference.
Mixture & mixture ()
Get Mixture by reference.
const Domain & domain () const
Get spatial domain (including grid info) by reference.
Domain & domain ()
Get spatial domain (including grid info) by reference.
const Interaction & interaction () const
Get interaction (i.e., excess free energy model) by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
const Homogeneous::Mixture & homogeneous () const
Get homogeneous mixture (for reference calculations).
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
DArray< System::WField > & wFields ()
Get array of all chemical potential fields.
System::WField & wField (int monomerId)
Get chemical potential field for a specific monomer type.
DArray< System::CField > & cFields ()
Get array of all chemical potential fields.
System::CField & cField (int monomerId)
Get chemical potential field for a specific monomer type.
Protected Member Functions
virtual void checkAllocation (State &state)
Check allocation of w fields in one state, allocate if needed.
virtual void setup ()
Setup operation at beginning sweep.
virtual void setParameters (double s)
Set non-adjustable system parameters to new values.
virtual void extrapolate (double s)
Create initial guess for new w fields by polynomial extrapolation.
virtual int solve (bool isContinuation)
Call the current iterator to solve one SCFT problem.
virtual void reset ()
Reset system to previous solution after iterature failure.
virtual void getSolution ()
Update state(0) and output data after successful convergence.
virtual void cleanup ()
Close log file after end of sweep.
Protected Member Functions inherited from Pscf::SweepTmpl< DArray< System::WField > >
SweepTmpl (int historyCapacity)
Constructor (protected).
DArray< System::WField > & state (int i)
Get reference to a stored state, with i=0 being most recent.
double s (int i) const
Get the value of s for a stored solution, with i = 0 most recent.
double c (int i) const
Get a coefficient of a previous state in a continuation.
int historySize () const
Get the current number of stored previous states.
int historyCapacity () const
Get the maximum number of stored previous states.
int nAccept () const
Get the number of converged solutions accepted thus far.
void initialize ()
Initialize variables that track history of solutions.
virtual void checkAllocation (DArray< System::WField > &state)=0
Check allocation of one state, allocate if necessary.
virtual void setup ()=0
Setup operation at the beginning of a sweep.
virtual void setParameters (double sNew)=0
Set non-adjustable system parameters to new values.
virtual void extrapolate (double sNew)=0
Create initial guess for the next state by extrapolation.
void setCoefficients (double sNew)
Compute coefficients of previous states for continuation.
virtual int solve (bool isContinuation)=0
Call current iterator to solve SCFT problem.
virtual void reset ()=0
Reset system to previous solution after iterature failure.
virtual void getSolution ()=0
Update state(0) and output data after successful solution.
virtual void cleanup ()
Clean up operation at the end of a sweep.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
int homogeneousMode_
Mode for comparison to homogeneous system (none -> -1)
Protected Attributes inherited from Pscf::SweepTmpl< DArray< System::WField > >
int ns_
Number of steps.
std::string baseFileName_
Base name for output files.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
Solve a sequence of problems along a line in parameter space.
Definition at line 30 of file fd1d/sweep/Sweep.h.
Constructor & Destructor Documentation
Sweep()
Pscf::Fd1d::Sweep::Sweep (System & system)
Constructor.
Parameters
system parent System object.
Definition at line 30 of file fd1d/sweep/Sweep.cpp.
References Pscf::Fd1d::FieldIo::associate(), Pscf::Fd1d::System::domain(), Pscf::Fd1d::System::fileMaster(), Util::ParamComposite::setClassName(), and Pscf::Fd1d::SystemAccess::system().
~Sweep()
Pscf::Fd1d::Sweep::~Sweep ()
Destructor.
Definition at line 44 of file fd1d/sweep/Sweep.cpp.
Member Function Documentation
readParameters()
void Pscf::Fd1d::Sweep::readParameters (std::istream & in) virtual
Read ns and baseFileName parameters.
Parameters
in input stream
Reimplemented from Pscf::SweepTmpl< DArray< System::WField > >.
Reimplemented in Pscf::Fd1d::LinearSweep.
Definition at line 50 of file fd1d/sweep/Sweep.cpp.
References homogeneousMode_, and Pscf::SweepTmpl< State >::readParameters().
Referenced by Pscf::Fd1d::LinearSweep::readParameters().
outputSolution()
void Pscf::Fd1d::Sweep::outputSolution (std::string const & stateFileName) virtual
Output information after obtaining a converged solution.
Parameters
stateFileName base name of output files
Definition at line 186 of file fd1d/sweep/Sweep.cpp.
References Pscf::Fd1d::SystemAccess::cFields(), Pscf::Fd1d::SystemAccess::fileMaster(), homogeneousMode_, Util::FileMaster::openOutputFile(), Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::SystemAccess::system(), Pscf::Fd1d::SystemAccess::wFields(), Pscf::Fd1d::FieldIo::writeFields(), Util::ParamComposite::writeParam(), and Pscf::Fd1d::System::writeThermo().
Referenced by getSolution().
outputSummary()
void Pscf::Fd1d::Sweep::outputSummary (std::ostream & outFile) virtual
Output data to a running summary.
Parameters
outFile output log file, open for writing
Reimplemented in Pscf::Fd1d::LinearSweep.
Definition at line 215 of file fd1d/sweep/Sweep.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Fd1d::System::fHelmholtz(), Pscf::Homogeneous::Mixture::fHelmholtz(), Pscf::Fd1d::System::homogeneous(), homogeneousMode_, Pscf::SweepTmpl< DArray< System::WField > >::nAccept(), Pscf::Fd1d::System::pressure(), Pscf::Homogeneous::Mixture::pressure(), Pscf::SweepTmpl< DArray< System::WField > >::s(), Pscf::Fd1d::SystemAccess::system(), and Pscf::Fd1d::Domain::volume().
Referenced by getSolution().
checkAllocation()
void Pscf::Fd1d::Sweep::checkAllocation (Sweep::State & state) protected virtual
Check allocation of w fields in one state, allocate if needed.
Parameters
state one stored state of the system.
Implements Pscf::SweepTmpl< DArray< System::WField > >.
Definition at line 60 of file fd1d/sweep/Sweep.cpp.
References Util::DArray< Data >::allocate(), Util::Array< Data >::capacity(), Pscf::Fd1d::SystemAccess::domain(), Util::DArray< Data >::isAllocated(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::Fd1d::Domain::nx(), Pscf::SweepTmpl< DArray< System::WField > >::state(), and UTIL_CHECK.
setup()
void Pscf::Fd1d::Sweep::setup () protected virtual
Setup operation at beginning sweep.
Implements Pscf::SweepTmpl< DArray< System::WField > >.
Reimplemented in Pscf::Fd1d::LinearSweep.
Definition at line 87 of file fd1d/sweep/Sweep.cpp.
References Pscf::SweepTmpl< DArray< System::WField > >::baseFileName_, Pscf::Fd1d::SystemAccess::fileMaster(), Pscf::SweepTmpl< DArray< System::WField > >::initialize(), and Util::FileMaster::openOutputFile().
Referenced by Pscf::Fd1d::LinearSweep::setup().
setParameters()
void Pscf::Fd1d::Sweep::setParameters (double s) protected virtual
Set non-adjustable system parameters to new values.
Parameters
s new value of contour coordinate, in range [0,1]
Implements Pscf::SweepTmpl< DArray< System::WField > >.
Reimplemented in Pscf::Fd1d::LinearSweep.
Definition at line 104 of file fd1d/sweep/Sweep.cpp.
References UTIL_THROW.
extrapolate()
void Pscf::Fd1d::Sweep::extrapolate (double s) protected virtual
Create initial guess for new w fields by polynomial extrapolation.
Parameters
s new value of contour coordinate, in range [0,1]
Implements Pscf::SweepTmpl< DArray< System::WField > >.
Definition at line 112 of file fd1d/sweep/Sweep.cpp.
References Pscf::SweepTmpl< DArray< System::WField > >::c(), Pscf::Fd1d::SystemAccess::domain(), Pscf::SweepTmpl< DArray< System::WField > >::historySize(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::Fd1d::Domain::nx(), Pscf::SweepTmpl< DArray< System::WField > >::setCoefficients(), Pscf::SweepTmpl< DArray< System::WField > >::state(), UTIL_CHECK, and Pscf::Fd1d::SystemAccess::wField().
solve()
int Pscf::Fd1d::Sweep::solve (bool isContinuation) protected virtual
Call the current iterator to solve one SCFT problem.
Call current iterator to solve SCFT problem.
Return 0 for sucessful solution, 1 on failure to converge.
Implements Pscf::SweepTmpl< DArray< System::WField > >.
Definition at line 148 of file fd1d/sweep/Sweep.cpp.
References Pscf::Fd1d::System::iterate(), and Pscf::Fd1d::SystemAccess::system().
reset()
void Pscf::Fd1d::Sweep::reset () protected virtual
Reset system to previous solution after iterature failure.
The implementation of this function resets the system state to correspond to that stored in state(0).
The implementation of this function should reset the system state to correspond to that stored in state(0).
Implements Pscf::SweepTmpl< DArray< System::WField > >.
Definition at line 157 of file fd1d/sweep/Sweep.cpp.
References Pscf::SweepTmpl< DArray< System::WField > >::state(), and Pscf::Fd1d::SystemAccess::wFields().
getSolution()
void Pscf::Fd1d::Sweep::getSolution () protected virtual
Update state(0) and output data after successful convergence.
The implementation of this function should copy the current system state into state(0) and output any desired information about the current converged solution.
The implementation of this function should copy the current system state into state(0) and output any desired information about the current converged solution.
Implements Pscf::SweepTmpl< DArray< System::WField > >.
Definition at line 167 of file fd1d/sweep/Sweep.cpp.
References Pscf::SweepTmpl< DArray< System::WField > >::baseFileName_, Pscf::Fd1d::HomogeneousComparison::compute(), homogeneousMode_, Pscf::SweepTmpl< DArray< System::WField > >::nAccept(), outputSolution(), outputSummary(), Pscf::SweepTmpl< DArray< System::WField > >::state(), Util::toString(), and Pscf::Fd1d::SystemAccess::wFields().
cleanup()
void Pscf::Fd1d::Sweep::cleanup () protected virtual
Close log file after end of sweep.
Reimplemented from Pscf::SweepTmpl< DArray< System::WField > >.
Definition at line 239 of file fd1d/sweep/Sweep.cpp.
Member Data Documentation
homogeneousMode_
int Pscf::Fd1d::Sweep::homogeneousMode_ protected
Mode for comparison to homogeneous system (none -> -1)
Definition at line 76 of file fd1d/sweep/Sweep.h.
Referenced by getSolution(), outputSolution(), outputSummary(), and readParameters().
The documentation for this class was generated from the following files:
fd1d/sweep/Sweep.h
fd1d/sweep/Sweep.cpp