PSCF: Util::ArrayStack< Data > Class Template Reference
Util::ArrayStack< Data > Class Template Reference
Util namespace » Container Templates » Pointer Arrays
A stack of fixed capacity, which stores pointers to elements.
#include <ArrayStack.h>
Public Member Functions
ArrayStack ()
Default constructor.
virtual ~ArrayStack ()
Destructor.
void allocate (int capacity)
Initialize and allocate required memory.
Mutators
void push (Data &data)
Push an element onto the Stack.
Data & pop ()
Pop an element off the stack.
Accessors
int capacity () const
Return capacity of the underlying array.
int size () const
Get the number of elements in the stack.
Data & peek ()
Return a reference to the top element (don't pop).
const Data & peek () const
Return a const ref to the top element (don't pop).
bool isValid () const
Return true if the ArrayStack is valid, or throw an exception.
bool isAllocated () const
Return true only if the ArrayStack has been allocated.
Detailed Description
template<typename Data>
class Util::ArrayStack< Data >
A stack of fixed capacity, which stores pointers to elements.
Pointers to elements are stored in an allocatable, non-resizable array.
One natural usage is as a stack of pointers to elements of an associated array of Data objects, for which the maximum number of distinct elements is equal to the capacity of the associated array.
Definition at line 29 of file ArrayStack.h.
Constructor & Destructor Documentation
ArrayStack()
template<typename Data > Util::ArrayStack< Data >::ArrayStack ()
Default constructor.
Definition at line 130 of file ArrayStack.h.
~ArrayStack()
template<typename Data > Util::ArrayStack< Data >::~ArrayStack () virtual
Destructor.
Definition at line 140 of file ArrayStack.h.
References Util::Memory::deallocate().
Member Function Documentation
allocate()
template<typename Data > void Util::ArrayStack< Data >::allocate (int capacity)
Initialize and allocate required memory.
Parameters
capacity maximum size of stack
Definition at line 151 of file ArrayStack.h.
References Util::Memory::allocate(), and UTIL_THROW.
push()
template<typename Data > void Util::ArrayStack< Data >::push (Data & data)
Push an element onto the Stack.
Parameters
data element to be added to stack.
Definition at line 187 of file ArrayStack.h.
References UTIL_THROW.
pop()
template<typename Data > Data & Util::ArrayStack< Data >::pop ()
Pop an element off the stack.
Returns
the top element (which is popped off stack).
Definition at line 200 of file ArrayStack.h.
References UTIL_THROW.
capacity()
template<typename Data > int Util::ArrayStack< Data >::capacity () const
Return capacity of the underlying array.
Returns
Number of elements allocated in array.
Definition at line 173 of file ArrayStack.h.
size()
template<typename Data > int Util::ArrayStack< Data >::size () const inline
Get the number of elements in the stack.
Definition at line 180 of file ArrayStack.h.
Referenced by pscfpp.file.File::__eq__(), pscfpp.file.File::__init__(), pscfpp.text.Record::__init__(), pscfpp.file.File::__repr__(), and pscfpp.text.Record::__str__().
peek() [1/2]
template<typename Data > Data & Util::ArrayStack< Data >::peek () inline
Return a reference to the top element (don't pop).
Definition at line 215 of file ArrayStack.h.
peek() [2/2]
template<typename Data > const Data & Util::ArrayStack< Data >::peek () const inline
Return a const ref to the top element (don't pop).
Definition at line 222 of file ArrayStack.h.
isValid()
template<typename Data > bool Util::ArrayStack< Data >::isValid () const
Return true if the ArrayStack is valid, or throw an exception.
Definition at line 229 of file ArrayStack.h.
References UTIL_THROW.
isAllocated()
template<typename Data > bool Util::ArrayStack< Data >::isAllocated () const inline
Return true only if the ArrayStack has been allocated.
Definition at line 265 of file ArrayStack.h.
The documentation for this class was generated from the following file:
ArrayStack.h