PSCF: Pscf::Rpg::AmIteratorGrid< D > Class Template Reference
Pscf::Rpg::AmIteratorGrid< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Self-Consistent Field Theory (SCFT) » Iterators
Rpg implementation of the Anderson Mixing iterator.
#include <AmIteratorGrid.h>
Public Member Functions
AmIteratorGrid (System< D > &system)
Constructor.
~AmIteratorGrid ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
void outputTimers (std::ostream &out) const
Output timing results to log file.
Public Member Functions inherited from Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >
AmIteratorTmpl ()
Constructor.
~AmIteratorTmpl ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
int solve (bool isContinuation=false)
Iterate to a solution.
void outputTimers (std::ostream &out) const
Log output timing results.
void clearTimers ()
Clear timers.
std::string errorType () const
Obtain error type.
Protected Member Functions
void setup (bool isContinuation)
Setup iterator just before entering iteration loop.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >
void setMaxItr (int maxItr)
Set value of maxItr.
void setMaxHist (int maxHist)
Set value of maxHist (number of retained previous states)
void setErrorType (std::string errorType)
Set and validate value of errorType string.
void readErrorType (std::istream &in)
Read and validate the optional errorType string parameter.
virtual bool isValidErrorType ()
Checks if a string is a valid error type.
virtual double norm (FieldCUDA const &hist)
Find the L2 norm of a vector.
void allocateAM ()
Allocate memory required by AM algorithm, if necessary.
virtual void clear ()
Clear information about history.
virtual double computeError (FieldCUDA &residTrial, FieldCUDA &fieldTrial, std::string errorType, int verbose)
Compute and return error used to test for convergence.
virtual double computeLambda (double r)
Compute mixing parameter for correction step of Anderson mixing.
FieldCUDA const & residual () const
Return the current residual vector by const reference.
FieldCUDA const & field () const
Return the current field or state vector by const reference.
int verbose () const
Verbosity level, allowed values 0, 1, or 2.
int totalItr ()
Return the total number of iterations needed to converge.
double timerTotal ()
Get total time.
double timerMDE ()
Get time solving modified diffusion equation (MDE).
double timerAM ()
Get total time for AM algorithm, excluding MDE solution.
double timerResid ()
Get time computing residual.
double timerError ()
Get time evaluating scalar error.
double timerCoeff ()
Get time evaluating Anderson mixing coefficients.
double timerOmega ()
Get time updating w fields.
bool isAllocatedAM () const
Have data structures required by the AM algorithm been allocated?
Additional Inherited Members
Protected Attributes inherited from Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >
std::string errorType_
Type of error criterion used to test convergence.
Detailed Description
template<int D>
class Pscf::Rpg::AmIteratorGrid< D >
Rpg implementation of the Anderson Mixing iterator.
Definition at line 32 of file AmIteratorGrid.h.
Constructor & Destructor Documentation
AmIteratorGrid()
template<int D> Pscf::Rpg::AmIteratorGrid< D >::AmIteratorGrid (System< D > & system)
Constructor.
Parameters
system parent system object
Definition at line 30 of file AmIteratorGrid.tpp.
References setClassName().
~AmIteratorGrid()
template<int D> Pscf::Rpg::AmIteratorGrid< D >::~AmIteratorGrid ()
Destructor.
Definition at line 39 of file AmIteratorGrid.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::AmIteratorGrid< D >::readParameters (std::istream & in)
Read all parameters and initialize.
Parameters
in input filestream
Definition at line 44 of file AmIteratorGrid.tpp.
References Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >::AmIteratorTmpl(), Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >::readErrorType(), readOptional(), readOptionalFSArray(), readParameters(), and UTIL_CHECK.
Referenced by readParameters().
outputTimers()
template<int D> void Pscf::Rpg::AmIteratorGrid< D >::outputTimers (std::ostream & out) const
Output timing results to log file.
Parameters
out output stream for timer report
Definition at line 88 of file AmIteratorGrid.tpp.
References Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >::AmIteratorTmpl(), and outputTimers().
Referenced by outputTimers().
setup()
template<int D> void Pscf::Rpg::AmIteratorGrid< D >::setup (bool isContinuation) protected virtual
Setup iterator just before entering iteration loop.
Parameters
isContinuation Is this a continuation within a sweep?
Reimplemented from Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >.
Definition at line 100 of file AmIteratorGrid.tpp.
References Pscf::AmIteratorTmpl< Iterator< D >, FieldCUDA >::AmIteratorTmpl(), and setup().
Referenced by setup().
readOptional()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
Referenced by readParameters().
readParamCompositeOptional()
template<int D> void Util::ParamComposite::readParamCompositeOptional (std::istream & in, ParamComposite & child, bool next = true) protected
Add and attempt to read an optional child ParamComposite.
Parameters
in input stream for reading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 292 of file ParamComposite.cpp.
readOptionalFSArray()
template<int D> template<typename Type, int N> FSArrayParam< Type, N > & Util::ParamComposite::readOptionalFSArray (std::istream & in, const char * label, FSArray< Type, N > & array, int size) inline protected
Add and read an optional FSArray < Type, N > array parameter.
Parameters
in input stream for reading
label Label string for new array
array FSArray object
size logical size of array
Returns
reference to the new FSArrayParam<Type, N> object
Definition at line 427 of file ParamComposite.h.
Referenced by readParameters().
setClassName()
template<int D> void Util::ParamComposite::setClassName (const char * className) protected
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by AmIteratorGrid().
The documentation for this class was generated from the following files:
AmIteratorGrid.h
AmIteratorGrid.tpp