PSCF: Pscf::MeshIteratorFortran< D > Class Template Reference
Pscf::MeshIteratorFortran< D > Class Template Reference
Pscf namespace » Pscf Common » Spatial Mesh
Iterator over points in a mesh in "Fortran" order.
#include <MeshIteratorFortran.h>
Public Member Functions
MeshIteratorFortran ()
Default constructor.
MeshIteratorFortran (IntVec< D > const &dimensions)
Constructor, set mesh dimensions and initial iterator.
void setDimensions (IntVec< D > const &dimensions)
Set or reset the mesh dimensions, and initialize iterator.
void begin ()
Initialize the iterator to the first grid point.
void operator++ ()
Increment the iterator to the next grid point.
bool atEnd () const
Is this the end (i.e., past the last grid point)?
int rank () const
Return the scalar array rank of the associated grid point.
IntVec< D > const & position () const
Return a vector of coordinates of the associated grid point.
IntVec< D > const & dimensions () const
Return the mesh dimensions as an vector of integers.
int size () const
Return the mesh size (the number of grid points).
IntVec< D > const & offsets () const
Return the vector of offsets.
Detailed Description
template<int D>
class Pscf::MeshIteratorFortran< D >
Iterator over points in a mesh in "Fortran" order.
This mesh iterator iterates over the points of a mesh in "Fortran" order, in which the first array index varies most rapidly. During iteration, the class keeps track of both the IntVec<D> position and the integer rank of the current point in a mesh of specified dimensions. The MeshIterator class instead iterates over points of mesh in "C" order, in which the last index is most rapidly varying.
Ranges of the position vector components and the scalar rank are defined using C/C++ conventions, exactly as in the Mesh and MeshIterator classes: Each component of the position vector is indexed from zero, and the scalar scalar rank of each mesh point is defined using the C convention for the rank of a multi-dimensional array, in which the last index varies most rapidly. Because this iterator visits points of mesh in Fortran order, in which the first index varies most rapidly, the sequence of points visited by this iterator thus do not have sequential values for the rank.
Typical usage:
MeshIteratorFortran<D> iter(meshDimensions);
for (iter.begin(); !iter.atEnd(); ++iter()) {
   (Do something)
   cout << iter.position() << iter.rank();
}
Definition at line 50 of file MeshIteratorFortran.h.
Constructor & Destructor Documentation
MeshIteratorFortran() [1/2]
template<int D> Pscf::MeshIteratorFortran< D >::MeshIteratorFortran ()
Default constructor.
Definition at line 20 of file MeshIteratorFortran.tpp.
MeshIteratorFortran() [2/2]
template<int D> Pscf::MeshIteratorFortran< D >::MeshIteratorFortran (IntVec< D > const & dimensions)
Constructor, set mesh dimensions and initial iterator.
Construction by this function is equivalent to construction by the default constructor followed by a call to the setDimensions function. On return, mesh dimensions are set and the iterator is initialized to the first point in the mesh.
Parameters
dimensions dimensions of the associated mesh
Definition at line 33 of file MeshIteratorFortran.tpp.
References Pscf::MeshIteratorFortran< D >::dimensions(), and Pscf::MeshIteratorFortran< D >::setDimensions().
Member Function Documentation
setDimensions()
template<int D> void Pscf::MeshIteratorFortran< D >::setDimensions (IntVec< D > const & dimensions)
Set or reset the mesh dimensions, and initialize iterator.
This fuction calls begin() internally. Upon return, the iterator thus points to the first grid point, for which all position vector components are equal to zero.
Parameters
dimensions dimensions of the associated mesh
Definition at line 46 of file MeshIteratorFortran.tpp.
References UTIL_CHECK.
Referenced by Pscf::MeshIteratorFortran< D >::MeshIteratorFortran().
begin()
template<int D> void Pscf::MeshIteratorFortran< D >::begin ()
Initialize the iterator to the first grid point.
On return, the rank and all position components are all zero.
Definition at line 74 of file MeshIteratorFortran.tpp.
References UTIL_CHECK.
operator++()
template<int D> void Pscf::MeshIteratorFortran< D >::operator++ ()
Increment the iterator to the next grid point.
Definition at line 88 of file MeshIteratorFortran.tpp.
References UTIL_CHECK.
atEnd()
template<int D> bool Pscf::MeshIteratorFortran< D >::atEnd () const inline
Is this the end (i.e., past the last grid point)?
Definition at line 152 of file MeshIteratorFortran.h.
rank()
template<int D> int Pscf::MeshIteratorFortran< D >::rank () const inline
Return the scalar array rank of the associated grid point.
Definition at line 156 of file MeshIteratorFortran.h.
position()
template<int D> IntVec< D > const & Pscf::MeshIteratorFortran< D >::position () const inline
Return a vector of coordinates of the associated grid point.
Component i of the position varies from 0 to dimension[i] - 1, for i = 0, ..., D - 1, where dimension[i] is the dimension of the mesh in direction i.
Definition at line 160 of file MeshIteratorFortran.h.
dimensions()
template<int D> IntVec< D > const & Pscf::MeshIteratorFortran< D >::dimensions () const inline
Return the mesh dimensions as an vector of integers.
Definition at line 164 of file MeshIteratorFortran.h.
Referenced by Pscf::MeshIteratorFortran< D >::MeshIteratorFortran().
size()
template<int D> int Pscf::MeshIteratorFortran< D >::size () const inline
Return the mesh size (the number of grid points).
Definition at line 168 of file MeshIteratorFortran.h.
Referenced by pscfpp.file.File::__eq__(), pscfpp.file.File::__init__(), pscfpp.text.Record::__init__(), pscfpp.file.File::__repr__(), and pscfpp.text.Record::__str__().
offsets()
template<int D> IntVec< D > const & Pscf::MeshIteratorFortran< D >::offsets () const inline
Return the vector of offsets.
Definition at line 172 of file MeshIteratorFortran.h.
The documentation for this class was generated from the following files:
MeshIteratorFortran.h
MeshIteratorFortran.tpp