PSCF: Pscf::FieldGeneratorBase Class Reference
Pscf::FieldGeneratorBase Class Reference abstract
Pscf namespace » Pscf Common » Environment
Base class for objects that generate fields for a MixAndMatchEnv.
#include <FieldGeneratorBase.h>
Public Types
enum Type
Enum representing the type of field (mask, external field, or none).
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
FieldGeneratorBase ()
Constructor.
~FieldGeneratorBase ()
Destructor.
void generate ()
Checks if fields need to be (re)generated.
virtual bool needsUpdate () const =0
Check whether system has changed such that the field(s) need updating.
virtual void checkCompatibility ()=0
Check that the system is compatible with these fields.
Type type () const
Return Type enumeration value (Mask, External, or None)
bool isDependent () const
Is this object dependent on parameters of another FieldGeneratorBase?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void readParameters (std::istream &in)
Read the body of parameter block, without begin and end lines.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Public Member Functions inherited from Pscf::ParameterModifier
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
virtual GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to the Sweep object.
virtual void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
virtual double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Protected Member Functions
virtual void compute ()=0
Compute the field(s) and store where the System can access.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
Type type_
Type of field (Mask, External, or None).
bool isDependent_
Is this object dependent on parameters of another FieldGeneratorBase?
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
Base class for objects that generate fields for a MixAndMatchEnv.
A subclass of FieldGeneratorBase will contain code to generate a mask (which imposes geometric confinement) or a set of external potential fields (one for each monomer type), based on a set of input parameters defined by the subclass. The interface for the subclass to exchange this information with the System object is contained within the class MixAndMatchEnvTmpl, which owns up to two FieldGeneratorBase objects as members.
This class is a subclass of ParameterModifier so that, if desired, subclasses may declare parameters that can be varied in a Sweep.
In their constructors, subclasses should set the variable type_ to the appropriate value.
Definition at line 37 of file FieldGeneratorBase.h.
Member Enumeration Documentation
Type
enum Pscf::FieldGeneratorBase::Type
Enum representing the type of field (mask, external field, or none).
Definition at line 46 of file FieldGeneratorBase.h.
Constructor & Destructor Documentation
FieldGeneratorBase()
Pscf::FieldGeneratorBase::FieldGeneratorBase ()
Constructor.
Definition at line 14 of file FieldGeneratorBase.cpp.
References isDependent_, and type_.
~FieldGeneratorBase()
Pscf::FieldGeneratorBase::~FieldGeneratorBase ()
Destructor.
Definition at line 20 of file FieldGeneratorBase.cpp.
Member Function Documentation
generate()
void Pscf::FieldGeneratorBase::generate ()
Checks if fields need to be (re)generated.
If so, generates them.
Definition at line 24 of file FieldGeneratorBase.cpp.
References checkCompatibility(), compute(), and needsUpdate().
needsUpdate()
virtual bool Pscf::FieldGeneratorBase::needsUpdate () const pure virtual
Check whether system has changed such that the field(s) need updating.
Implemented in Pscf::Prdc::FilmFieldGenExtBase< D >, and Pscf::Prdc::FilmFieldGenMaskBase< D >.
Referenced by generate().
checkCompatibility()
virtual void Pscf::FieldGeneratorBase::checkCompatibility () pure virtual
Check that the system is compatible with these fields.
This may, for example, involve checking that the fields satisfy the system's symmetry and lattice system, and ensuring that the unit cell is only allowed to adjust its size in ways that agree with the design of the fields.
Implemented in Pscf::Prdc::FilmFieldGenExtBase< D >, and Pscf::Prdc::FilmFieldGenMaskBase< D >.
Referenced by generate().
type()
FieldGeneratorBase::Type Pscf::FieldGeneratorBase::type () const inline
Return Type enumeration value (Mask, External, or None)
This value should be initialized by subclasses during construction.
Definition at line 134 of file FieldGeneratorBase.h.
References type_.
isDependent()
bool Pscf::FieldGeneratorBase::isDependent () const inline
Is this object dependent on parameters of another FieldGeneratorBase?
The parent MixAndMatchEnvTmpl object can contain up to two FieldGeneratorBase objects: a mask generator and an external field generator. In some cases, the properties of one may be dependent on the properties of the other. isDependent allows a FieldGeneratorBase to indicate to the parent MixAndMatchEnvTmpl object that it needs to read the parameters of the other FieldGenerator in addition to its own.
During readParameters, the parent object will first allow the independent FieldGeneratorBase to read its own parameters. It will then rewind the istream to allow the dependent FieldGeneratorBase to read the parameters of the object on which it is dependent, followed by its own parameters.
Therefore, a dependent FieldGeneratorBase must be the second of two FieldGeneratorBases stored in a parent MixAndMatchEnvTmpl, and two FieldGeneratorBases may not be dependent on each other. If the mask and external field are dependent on each other, a different subclass of Environment should be used instead of a MixAndMatchEnvTmpl to generate these imposed fields.
Definition at line 138 of file FieldGeneratorBase.h.
References isDependent_.
compute()
virtual void Pscf::FieldGeneratorBase::compute () protected pure virtual
Compute the field(s) and store where the System can access.
Implemented in Pscf::Prdc::FilmFieldGenExtBase< D >, Pscf::Prdc::FilmFieldGenMaskBase< D >, Pscf::Rpc::FilmFieldGenExt< D >, Pscf::Rpc::FilmFieldGenMask< D >, Pscf::Rpg::FilmFieldGenExt< D >, and Pscf::Rpg::FilmFieldGenMask< D >.
Referenced by generate().
Member Data Documentation
type_
Type Pscf::FieldGeneratorBase::type_ protected
Type of field (Mask, External, or None).
This parameter should be set in the constructor of subclasses and left unchanged for the remainder of the calculation.
Definition at line 124 of file FieldGeneratorBase.h.
Referenced by FieldGeneratorBase(), Pscf::Prdc::FilmFieldGenExtBase< D >::FilmFieldGenExtBase(), Pscf::Prdc::FilmFieldGenMaskBase< D >::FilmFieldGenMaskBase(), and type().
isDependent_
bool Pscf::FieldGeneratorBase::isDependent_ protected
Is this object dependent on parameters of another FieldGeneratorBase?
Definition at line 127 of file FieldGeneratorBase.h.
Referenced by FieldGeneratorBase(), Pscf::Prdc::FilmFieldGenExtBase< D >::FilmFieldGenExtBase(), and isDependent().
The documentation for this class was generated from the following files:
FieldGeneratorBase.h
FieldGeneratorBase.cpp