PSCF: Pscf::Rpc::IntraCorrelation< D > Class Template Reference
Pscf::Rpc::IntraCorrelation< D > Class Template Reference
Pscf namespace » Pscf::Rpc - Real Periodic Fields (CPU) » Field Theoretic Simulation (FTS) » Compressors
Intramolecular correlation analysis for LR compressors.
#include <IntraCorrelation.h>
Public Member Functions
IntraCorrelation (System< D > &system)
Constructor.
~IntraCorrelation ()
Destructor.
void computeIntraCorrelations (RField< D > &correlations)
Compute and modify intramolecular correlations.
Protected Member Functions
System< D > & system ()
Return reference to parent system.
Detailed Description
template<int D>
class Pscf::Rpc::IntraCorrelation< D >
Intramolecular correlation analysis for LR compressors.
Definition at line 37 of file rpc/fts/compressor/IntraCorrelation.h.
Constructor & Destructor Documentation
IntraCorrelation()
template<int D> Pscf::Rpc::IntraCorrelation< D >::IntraCorrelation (System< D > & system)
Constructor.
Parameters
system parent System object
Definition at line 39 of file rpc/fts/compressor/IntraCorrelation.tpp.
References system().
~IntraCorrelation()
template<int D> Pscf::Rpc::IntraCorrelation< D >::~IntraCorrelation ()
Destructor.
Definition at line 48 of file rpc/fts/compressor/IntraCorrelation.tpp.
Member Function Documentation
computeIntraCorrelations()
template<int D> void Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations (RField< D > & correlations)
Compute and modify intramolecular correlations.
Parameters
correlations k-space grid of omega values
Definition at line 56 of file rpc/fts/compressor/IntraCorrelation.tpp.
References Util::DArray< Data >::allocate(), Pscf::MeshIterator< D >::atEnd(), Pscf::EdgeIterator::begin(), Pscf::MeshIterator< D >::begin(), Util::Array< Data >::capacity(), Pscf::Prdc::Cpu::FFT< D >::computeKMesh(), Pscf::EdgeIterator::currentEdgeId(), Pscf::Debye::db(), Pscf::Debye::dt(), Pscf::Debye::eb(), Pscf::PolymerSpecies::edge(), Pscf::Debye::et(), Pscf::PolymerModel::isThread(), Pscf::Prdc::UnitCellBase< D >::ksq(), Pscf::Monomer::kuhn(), Pscf::Edge::length(), Pscf::Rpc::Mixture< D >::monomer(), Pscf::Edge::monomerId(), Pscf::Edge::nBead(), Pscf::PolymerSpecies::nBlock(), Pscf::EdgeIterator::notEnd(), Pscf::Rpc::Mixture< D >::nPolymer(), Pscf::Rpc::Mixture< D >::nSolvent(), Pscf::Rpc::Solvent< D >::phi(), Pscf::Species::phi(), Pscf::Prdc::MixtureReal< D, PT, ST >::polymerSpecies(), Pscf::MeshIterator< D >::position(), Pscf::MeshIterator< D >::rank(), Pscf::MeshIterator< D >::setDimensions(), Pscf::Rpc::Solvent< D >::size(), Pscf::Prdc::MixtureReal< D, PT, ST >::solvent(), system(), UTIL_CHECK, and Pscf::Rpc::Mixture< D >::vMonomer().
system()
template<int D> System< D > & Pscf::Rpc::IntraCorrelation< D >::system () inline protected
Return reference to parent system.
Definition at line 83 of file rpc/fts/compressor/IntraCorrelation.h.
Referenced by computeIntraCorrelations(), and IntraCorrelation().
The documentation for this class was generated from the following files:
rpc/fts/compressor/IntraCorrelation.h
rpc/fts/compressor/IntraCorrelation.tpp