PSCF: Pscf::ParameterModifier Class Reference
Pscf::ParameterModifier Class Reference
Pscf namespace » Pscf Common » Sweep Template
Base class allowing subclasses to define sweepable parameters.
#include <ParameterModifier.h>
Public Member Functions
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
virtual GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to the Sweep object.
virtual void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
virtual double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Detailed Description
Base class allowing subclasses to define sweepable parameters.
This class, along with SweepTmpl, define an interface which allows "specialized" sweepable parameters to be added to the Sweep class at run time. Any object with a specialized sweep parameter must be a subclass of ParameterModifier, and must redefine the three virtual methods getParameterTypes, setParameter, and getParameter. The Sweep object is then responsible for calling the method getParameterTypes for any ParameterModifier in the system and adding the parameters to its list of specialized sweep parameters. This should happen in the Sweep class constructor.
This interface was designed to allow objects whose class is determined at run time (i.e., an object created by a Factory) to have sweepable parameters, which are added to the Sweep object at run time.
Definition at line 40 of file ParameterModifier.h.
Constructor & Destructor Documentation
ParameterModifier()
Pscf::ParameterModifier::ParameterModifier ()
Constructor.
Definition at line 13 of file ParameterModifier.cpp.
~ParameterModifier()
Pscf::ParameterModifier::~ParameterModifier ()
Destructor.
Definition at line 17 of file ParameterModifier.cpp.
Member Function Documentation
getParameterTypes()
GArray< ParameterType > Pscf::ParameterModifier::getParameterTypes () virtual
Return specialized sweep parameter types to add to the Sweep object.
This method should be called by the Sweep object in its constructor. If the ParameterModifier object does not have any specialized sweep parameters, this method can be left as implemented here, returning an empty array.
Reimplemented in Pscf::ImposedFieldsTmpl, and Pscf::Prdc::ExtGenFilmBase< D >.
Definition at line 23 of file ParameterModifier.cpp.
Referenced by Pscf::ImposedFieldsTmpl::getParameterTypes().
setParameter() [1/2]
virtual void Pscf::ParameterModifier::setParameter (std::string name, DArray< int > ids, double value, bool & success) inline virtual
Set the value of a specialized sweep parameter.
Subclass implementations of setParameter should attempt to set the desired parameter, and should not throw an error regardless of whether this attempt succeeded. A boolean input parameter named success should be set to true or false depending on whether the parameter was successfully set. This method should be used when the caller does not know if the specialized sweep parameter belongs to this ParameterModifier or not.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
value the value to which the parameter is set
success boolean flag used to indicate if parameter was set
Reimplemented in Pscf::ImposedFieldsTmpl, and Pscf::Prdc::ExtGenFilmBase< D >.
Definition at line 82 of file ParameterModifier.h.
Referenced by Pscf::ImposedFieldsTmpl::setParameter(), and setParameter().
getParameter() [1/2]
virtual double Pscf::ParameterModifier::getParameter (std::string name, DArray< int > ids, bool & success) const inline virtual
Get the value of a specialized sweep parameter.
Subclass implementations of getParameter should attempt to get the desired parameter, and should not throw an error regardless of whether this attempt succeeded. A boolean input parameter named success should be set to true or false depending on whether the parameter was successfully gotten. This method should be used when the caller does not know if the specialized sweep parameter belongs to this ParameterModifier or not.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
success boolean flag used to indicate if parameter was gotten
Reimplemented in Pscf::ImposedFieldsTmpl, and Pscf::Prdc::ExtGenFilmBase< D >.
Definition at line 102 of file ParameterModifier.h.
Referenced by Pscf::ImposedFieldsTmpl::getParameter(), and getParameter().
setParameter() [2/2]
void Pscf::ParameterModifier::setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
This is an overloaded version of the setParameter method above, which should be used only when the caller is certain that the specialized sweep parameter belongs to this ParameterModifier. An error will be thrown if the specialized parameter is not settable using this class.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
value the value to which the parameter is set
Definition at line 34 of file ParameterModifier.cpp.
References setParameter(), and UTIL_THROW.
getParameter() [2/2]
double Pscf::ParameterModifier::getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
This is an overloaded version of the getParameter method above, which should be used only when the caller is certain that the specialized sweep parameter belongs to this ParameterModifier. An error will be thrown if the specialized parameter is not gettable using this class.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
Definition at line 48 of file ParameterModifier.cpp.
References getParameter(), and UTIL_THROW.
The documentation for this class was generated from the following files:
ParameterModifier.h
ParameterModifier.cpp