PSCF: Pscf::Prdc::MixtureReal< D, PT, ST > Class Template Reference
Pscf::Prdc::MixtureReal< D, PT, ST > Class Template Reference abstract
Solver and descriptor for a mixture of polymers and solvents.
#include <MixtureReal.h>
Public Types
using MixtureTmplT = MixtureTmpl<PT,ST>
MixtureTmplT class.
using FieldT = typename PropagatorT::FieldT
Field type, for data defined on a real-space grid.
using FFTT = typename BlockT::FFTT
WaveList type.
using WaveListT = typename BlockT::WaveListT
WaveList type.
using FieldIoT = typename BlockT::FieldIoT
FieldIo type.
using SolventT
Solvent species solver type.
using PolymerT
Polymer species solver type.
using BlockT
Block polymer block type.
using PropagatorT
Polymer block propagator type.
Public Types inherited from Pscf::MixtureTmpl< PT, ST >
using SolventT = ST
Solvent species solver type.
using PolymerT = PT
Polymer species solver type.
using BlockT = typename PT::BlockT
Block polymer block type.
using PropagatorT = typename BlockT::PropagatorT
Polymer block propagator type.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
PolymerT & polymer (int id)
Get a polymer solver object by non-const reference.
PolymerT const & polymer (int id) const
Get a polymer solver by const reference.
PolymerSpecies const & polymerSpecies (int id) const final
Get a PolymerSpecies descriptor by const reference.
SolventT & solvent (int id)
Get a solvent solver object.
SolventT const & solvent (int id) const
Get a solvent solver object by constant reference.
SolventSpecies const & solventSpecies (int id) const final
Set a SolventSpecies descriptor object by const reference.
int nMonomer () const
Get number of monomer types.
Monomer const & monomer (int id) const
Get a Monomer type descriptor by const reference.
Monomer & monomer (int id)
Get a Monomer type descriptor (non-const reference).
int nPolymer () const
Get number of polymer species.
int nSolvent () const
Get number of solvent (point particle) species.
int nBlock () const
Get total number blocks among all polymer species.
double vMonomer () const
Get monomer reference volume (set to 1.0 by default).
bool isCanonical () const
Is this mixture being treated in canonical ensemble?
Construction, Initialization and Destruction
MixtureReal ()
Constructor.
~MixtureReal ()
Destructor.
virtual void readParameters (std::istream &in)
Read all parameters and initialize.
void associate (Mesh< D > const &mesh, FFTT const &fft, UnitCell< D > const &cell, WaveListT &waveList)
Create associations with Mesh, FFT, UnitCell, and WaveList objects.
void setFieldIo (FieldIoT const &fieldIo)
Create an association with a FieldIoT object.
void allocate ()
Allocate required internal memory for all solvers.
Primary Computations
void compute (DArray< FieldT > const &wFields, DArray< FieldT > &cFields, double phiTot=1.0)
Compute partition functions and concentrations.
void setIsSymmetric (bool isSymmetric)
Set the isSymmetric flag true or false.
void computeStress (double phiTot=1.0)
Compute derivatives of free energy w/ respect to cell parameters.
bool hasStress () const
Has the stress been computed since the last MDE solution?
double stress (int parameterId) const
Get derivative of free energy w/ respect to a unit cell parameter.
Parameter Modification
void setKuhn (int monomerId, double kuhn)
Reset statistical segment length for one monomer type.
void clearUnitCellData ()
Clear all data that depends on the unit cell parameters.
Concentration Field Output
void createBlockCRGrid (DArray< FieldT > &blockCFields) const
Get c-fields for all blocks and solvents as array of r-grid fields.
void writeBlockCRGrid (std::string const &filename) const
Write c fields for all blocks and solvents in r-grid format.
Propagator Output
void writeQSlice (std::string const &filename, int polymerId, int blockId, int directionId, int segmentId) const
Write one slice of a propagator at fixed s in r-grid format.
void writeQTail (std::string const &filename, int polymerId, int blockId, int directionId) const
Write the final slice of a propagator in r-grid format.
void writeQ (std::string const &filename, int polymerId, int blockId, int directionId) const
Write the complete propagator for one block, in r-grid format.
void writeQAll (std::string const &basename)
Write all propagators of all blocks, each to a separate file.
Stress Output
void writeStress (std::ostream &out) const
Write stress values to output stream.
Public Member Functions inherited from Pscf::MixtureTmpl< PT, ST >
MixtureTmpl ()
Constructor.
~MixtureTmpl ()
Destructor.
PolymerT & polymer (int id)
Get a polymer solver object by non-const reference.
PolymerT const & polymer (int id) const
Get a polymer solver by const reference.
SolventT & solvent (int id)
Get a solvent solver object.
SolventT const & solvent (int id) const
Get a solvent solver object by constant reference.
Public Member Functions inherited from Pscf::MixtureBase
MixtureBase ()
Constructor.
~MixtureBase ()
Destructor.
void setVmonomer (double vMonomer)
Set new vMonomer value.
int nMonomer () const
Get number of monomer types.
int nPolymer () const
Get number of polymer species.
int nSolvent () const
Get number of solvent (point particle) species.
int nBlock () const
Get total number blocks among all polymer species.
double vMonomer () const
Get monomer reference volume (set to 1.0 by default).
bool isCanonical () const
Is this mixture being treated in canonical ensemble?
Monomer const & monomer (int id) const
Get a Monomer type descriptor by const reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
Mesh< D > const & mesh () const
Return associated Mesh<D> by const reference.
UnitCell< D > const & unitCell () const
Return associated UnitCell<D> by const reference.
FieldIoT const & fieldIo () const
Return associated FieldIoT by const reference.
double ds () const
Return target value for the contour step size ds.
void setClassName (const char *className)
Set class name string.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Protected Member Functions inherited from Pscf::MixtureBase
Monomer & monomer (int id)
Get a Monomer type descriptor (non-const reference).
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Attributes inherited from Pscf::MixtureBase
DArray< Monomer > monomers_
Array of monomer type descriptors.
int nMonomer_
Number of monomer types.
int nPolymer_
Number of polymer species.
int nSolvent_
Number of solvent species.
int nBlock_
Number of blocks total, across all polymers.
double vMonomer_
Monomer reference volume (set to 1.0 by default).
Detailed Description
template<int D, class PT, class ST>
class Pscf::Prdc::MixtureReal< D, PT, ST >
Solver and descriptor for a mixture of polymers and solvents.
A MixtureReal contains lists of Polymer (PT) and Solvent (ST) objects. Each such object can solve statistical mechanics of a single molecule of the associated species in a set of specified chemical potential fields, and thereby compute concentrations and molecular partition functions for all species in non-interacting reference system.
The compute() member function computes single-molecule partition functions and monomer concentrations all species. This function takes an array of chemical potential fields (w fields) acting on different monomer types an input and yields an array of total monomer concentration fields (c fields) as an output.
Manual Page
Definition at line 50 of file MixtureReal.h.
Member Typedef Documentation
MixtureTmplT
template<int D, class PT, class ST> using Pscf::Prdc::MixtureReal< D, PT, ST >::MixtureTmplT = MixtureTmpl<PT,ST>
MixtureTmplT class.
Definition at line 58 of file MixtureReal.h.
FieldT
template<int D, class PT, class ST> using Pscf::Prdc::MixtureReal< D, PT, ST >::FieldT = typename PropagatorT::FieldT
Field type, for data defined on a real-space grid.
Definition at line 73 of file MixtureReal.h.
FFTT
template<int D, class PT, class ST> using Pscf::Prdc::MixtureReal< D, PT, ST >::FFTT = typename BlockT::FFTT
WaveList type.
Definition at line 76 of file MixtureReal.h.
WaveListT
template<int D, class PT, class ST> using Pscf::Prdc::MixtureReal< D, PT, ST >::WaveListT = typename BlockT::WaveListT
WaveList type.
Definition at line 79 of file MixtureReal.h.
FieldIoT
template<int D, class PT, class ST> using Pscf::Prdc::MixtureReal< D, PT, ST >::FieldIoT = typename BlockT::FieldIoT
FieldIo type.
Definition at line 82 of file MixtureReal.h.
SolventT
template<int D, class PT, class ST> using Pscf::MixtureTmpl< PT, ST >::SolventT
Solvent species solver type.
Definition at line 35 of file MixtureTmpl.h.
PolymerT
template<int D, class PT, class ST> using Pscf::MixtureTmpl< PT, ST >::PolymerT
Polymer species solver type.
Definition at line 40 of file MixtureTmpl.h.
BlockT
template<int D, class PT, class ST> using Pscf::MixtureTmpl< PT, ST >::BlockT
Block polymer block type.
Definition at line 45 of file MixtureTmpl.h.
PropagatorT
template<int D, class PT, class ST> using Pscf::MixtureTmpl< PT, ST >::PropagatorT
Polymer block propagator type.
Definition at line 50 of file MixtureTmpl.h.
Constructor & Destructor Documentation
MixtureReal()
template<int D, class PT, class ST> Pscf::Prdc::MixtureReal< D, PT, ST >::MixtureReal ()
Constructor.
Definition at line 27 of file MixtureReal.tpp.
References setClassName().
~MixtureReal()
template<int D, class PT, class ST> Pscf::Prdc::MixtureReal< D, PT, ST >::~MixtureReal ()
Destructor.
Definition at line 42 of file MixtureReal.tpp.
Member Function Documentation
readParameters()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::readParameters (std::istream & in) virtual
Read all parameters and initialize.
This function reads in a complete description of the structure of all species and the composition of the mixture, plus a few other parameters.
Parameters
in input parameter stream
Reimplemented from Pscf::MixtureTmpl< PT, ST >.
Reimplemented in Pscf::Rpg::Mixture< D >.
Definition at line 49 of file MixtureReal.tpp.
References Pscf::PolymerModel::isThread(), nMonomer(), nPolymer(), nSolvent(), read(), Pscf::MixtureTmpl< PT, ST >::readParameters(), and UTIL_CHECK.
associate()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::associate (Mesh< D > const & mesh, FFTT const & fft, UnitCell< D > const & cell, WaveListT & waveList)
Create associations with Mesh, FFT, UnitCell, and WaveList objects.
The Mesh<D> object must have already been initialized, e.g., by reading the dimensions from a file, so that the mesh dimensions are known on entry. The FFTT object must have been set up with mesh dimensions equal to those of the mesh. The UnitCell<D> must have been assigned a non-null lattice system, but does not need to have initialized lattice parameters.
This function is called within the readParameters function of the parent System, after calls to the readParameters member functions of the Mixture and Domain. The Mesh, FFT, and UnitCell lattice are initialized by the Domain readParameters function prior to entry.
Parameters
mesh associated Mesh<D> object
fft associated FFTT object (Fast Fourier Transform type)
cell associated UnitCell<D> object
waveList associated WaveListT object
Definition at line 70 of file MixtureReal.tpp.
References mesh(), nMonomer(), Pscf::Prdc::UnitCellBase< D >::nParameter(), nPolymer(), nSolvent(), polymer(), and UTIL_CHECK.
setFieldIo()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::setFieldIo (FieldIoT const & fieldIo)
Create an association with a FieldIoT object.
The associated FieldIoT is only used by member functions that write concentration or propagator fields to file.
Parameters
fieldIo associated FieldIoT object
Definition at line 111 of file MixtureReal.tpp.
References fieldIo().
allocate()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::allocate ()
Allocate required internal memory for all solvers.
This function is called within the readParameters of the parent System, after the associate() function.
Definition at line 118 of file MixtureReal.tpp.
References nMonomer(), nPolymer(), nSolvent(), and UTIL_CHECK.
compute()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::compute (DArray< FieldT > const & wFields, DArray< FieldT > & cFields, double phiTot = 1.0)
Compute partition functions and concentrations.
This function calls the compute function of every molecular species, and then adds the resulting block concentration fields for blocks of each type to compute a total monomer concentration (or volume fraction) for each monomer type. Upon return, values are set for volume fraction (phi) and chemical potential (mu) members of each species, and for the concentration fields for each Block and Solvent. The total concentration for each monomer type is returned in the cFields function parameter. Monomer concentration fields are normalized by the inverse steric volume per monomer in an incompressible mixture, and are thus also volume fractions.
The array function parameters wFields and cFields must each have capacity nMonomer(), and contain fields that are indexed by monomer type index.
The optional parameter phiTot is only relevant to problems such as thin films in which the material is excluded from part of the unit cell by imposing an inhomogeneous constraint on the sum of monomer concentrations, (i.e., a "mask"). In such cases, the volume fraction phi for each species is defined as a fraction of the volume that is occupied by material, rather than as a fraction of the entire unit cell volume.
This function does not compute SCFT free energies or stress (i.e., derivatives of free energy with respect to unit cell parameters).
Parameters
wFields array of chemical potential fields (input)
cFields array of monomer concentration fields (output)
phiTot volume fraction of unit cell occupied by material
Definition at line 191 of file MixtureReal.tpp.
References Util::Array< Data >::capacity(), mesh(), nMonomer(), nPolymer(), nSolvent(), and UTIL_CHECK.
setIsSymmetric()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::setIsSymmetric (bool isSymmetric)
Set the isSymmetric flag true or false.
The isSymmetric variable affects whether a space group is written in field file headers by functions that write concentration or propagator fields to file. This variable should be set true after calling compute if the w fields passed to the compute function were known to be symmetric under the space group.
Definition at line 262 of file MixtureReal.tpp.
computeStress()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::computeStress (double phiTot = 1.0)
Compute derivatives of free energy w/ respect to cell parameters.
The optional parameter phiTot is only relevant to problems with a mask, in which the material is excluded from part of the unit cell by imposing an inhomogeneous constrain on the sum of monomer concentrations. In such cases, the stress needs to be scaled by a factor of 1/phiTot.
Parameters
phiTot volume fraction of unit cell occupied by material
Definition at line 269 of file MixtureReal.tpp.
References nPolymer(), and UTIL_CHECK.
hasStress()
template<int D, class PT, class ST> bool Pscf::Prdc::MixtureReal< D, PT, ST >::hasStress () const inline
Has the stress been computed since the last MDE solution?
Definition at line 478 of file MixtureReal.h.
Referenced by Pscf::Prdc::Environment::computeStress().
stress()
template<int D, class PT, class ST> double Pscf::Prdc::MixtureReal< D, PT, ST >::stress (int parameterId) const inline
Get derivative of free energy w/ respect to a unit cell parameter.
Get the pre-computed derivative of the free energy per monomer with respect to a single unit cell parameter.
Parameters
parameterId index of unit cell parameter
Definition at line 467 of file MixtureReal.h.
References UTIL_CHECK.
Referenced by Pscf::Prdc::Environment::computeStress().
setKuhn()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::setKuhn (int monomerId, double kuhn)
Reset statistical segment length for one monomer type.
This function resets the kuhn or statistical segment length value for a monomer type, and updates the associcated value in every block of that monomer type.
Parameters
monomerId monomer type id
kuhn new value for the statistical segment length
Definition at line 168 of file MixtureReal.tpp.
References monomer(), nPolymer(), and polymer().
clearUnitCellData()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::clearUnitCellData ()
Clear all data that depends on the unit cell parameters.
This function marks all private data that depends on the values of the unit cell parameters as invalid, so that it can be recomputed before it is next needed. This function should be called after any change in unit cell parameters.
Definition at line 153 of file MixtureReal.tpp.
References nPolymer(), and polymer().
createBlockCRGrid()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::createBlockCRGrid (DArray< FieldT > & blockCFields) const
Get c-fields for all blocks and solvents as array of r-grid fields.
On return, each element of the blockCFields array contains the monomer concentration field for a single block of a polymer species or a single solvent species. These are indexed with polymer blocks first, followed by solvent species. Polymer blocks are listed with blocks of each polymer placed consecutively in order of block index, with polymers ordered by polymer index. Fields associated with solvents are listed after all polymer blocks, ordered by solvent species index.
This function will allocate the blockCFields array and the FieldT arrays it contains as needed. This array thus does not need to be allocated on entry. If the array or the fields objects it contains are allocated on entry, their capacities must be correct or an error will be thrown.
Parameters
blockCFields DArray of FieldT field objects (output)
Definition at line 315 of file MixtureReal.tpp.
References mesh(), nBlock(), nMonomer(), nSolvent(), and UTIL_CHECK.
Referenced by writeBlockCRGrid().
writeBlockCRGrid()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::writeBlockCRGrid (std::string const & filename) const
Write c fields for all blocks and solvents in r-grid format.
Writes concentrations for all blocks of all polymers and all solvent species in r-grid format. Columns associated with polymer blocks appear first, followed by columns associated with solvent species. Polymer blocks are listed with blocks of each species ordered consecutively in order of block index, with groups of columns associated with polymers ordered by polymer index. Solvents are ordered by solvent species index.
Parameters
filename name of output file
Definition at line 375 of file MixtureReal.tpp.
References Util::DArray< Data >::allocate(), createBlockCRGrid(), fieldIo(), mesh(), nBlock(), nSolvent(), unitCell(), and UTIL_CHECK.
writeQSlice()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::writeQSlice (std::string const & filename, int polymerId, int blockId, int directionId, int segmentId) const
Write one slice of a propagator at fixed s in r-grid format.
Parameters
filename name of output file
polymerId integer id of the polymer
blockId integer id of the block within the polymer
directionId integer id of the direction (0 or 1)
segmentId integer integration step index
Definition at line 402 of file MixtureReal.tpp.
References fieldIo(), nPolymer(), polymer(), unitCell(), and UTIL_CHECK.
writeQTail()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::writeQTail (std::string const & filename, int polymerId, int blockId, int directionId) const
Write the final slice of a propagator in r-grid format.
Parameters
filename name of output file
polymerId integer id of the polymer
blockId integer id of the block within the polymer
directionId integer id of the direction (0 or 1)
Definition at line 428 of file MixtureReal.tpp.
References fieldIo(), nPolymer(), polymer(), unitCell(), and UTIL_CHECK.
writeQ()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::writeQ (std::string const & filename, int polymerId, int blockId, int directionId) const
Write the complete propagator for one block, in r-grid format.
Parameters
filename name of output file
polymerId integer id of the polymer
blockId integer id of the block within the polymer
directionId integer id of the direction (0 or 1)
Definition at line 452 of file MixtureReal.tpp.
References fieldIo(), mesh(), nPolymer(), polymer(), unitCell(), and UTIL_CHECK.
Referenced by writeQAll().
writeQAll()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::writeQAll (std::string const & basename)
Write all propagators of all blocks, each to a separate file.
Write all propagators for both directions for all blocks of all polymers, with each propagator in a separate file. The function writeQ is called internally for each propagator, and is passed an automatically generated file name. The file name for each propagator is given by a string of the form (basename)_(ip)_(ib)_(id), where (basename) denotes the value of the std::string function parameter basename, and where (ip), (ib), and (id) denote the string representations of a polymer indiex ip, a block index ib, and direction index id, with id = 0 or 1. For example, if basename == "out/q", then the file name of the propagator for direction 1 of block 2 of polymer 0 would be "out/q_0_2_1".
Parameters
basename common prefix for output file names
Definition at line 496 of file MixtureReal.tpp.
References nPolymer(), polymer(), Util::toString(), UTIL_CHECK, and writeQ().
writeStress()
template<int D, class PT, class ST> void Pscf::Prdc::MixtureReal< D, PT, ST >::writeStress (std::ostream & out) const
Write stress values to output stream.
Parameters
out output stream
Definition at line 524 of file MixtureReal.tpp.
References UTIL_CHECK.
mesh()
template<int D, class PT, class ST> Mesh< D > const & Pscf::Prdc::MixtureReal< D, PT, ST >::mesh () const inline protected
Return associated Mesh<D> by const reference.
Definition at line 388 of file MixtureReal.h.
Referenced by associate(), compute(), createBlockCRGrid(), writeBlockCRGrid(), and writeQ().
unitCell()
template<int D, class PT, class ST> UnitCell< D > const & Pscf::Prdc::MixtureReal< D, PT, ST >::unitCell () const inline protected
Return associated UnitCell<D> by const reference.
Definition at line 392 of file MixtureReal.h.
Referenced by writeBlockCRGrid(), writeQ(), writeQSlice(), and writeQTail().
fieldIo()
template<int D, class PT, class ST> FieldIoT const & Pscf::Prdc::MixtureReal< D, PT, ST >::fieldIo () const inline protected
Return associated FieldIoT by const reference.
Definition at line 396 of file MixtureReal.h.
Referenced by setFieldIo(), writeBlockCRGrid(), writeQ(), writeQSlice(), and writeQTail().
ds()
template<int D, class PT, class ST> double Pscf::Prdc::MixtureReal< D, PT, ST >::ds () const inline protected
Return target value for the contour step size ds.
Definition at line 400 of file MixtureReal.h.
polymer() [1/2]
template<int D, class PT, class ST> PT & Pscf::MixtureTmpl< PT, ST >::polymer (int id) inline
Get a polymer solver object by non-const reference.
Parameters
id integer polymer species index (0 <= id < nPolymer)
Definition at line 92 of file MixtureTmpl.h.
Referenced by associate(), clearUnitCellData(), Pscf::Rpc::Simulator< D >::computeHamiltonian(), Pscf::Rpg::Simulator< D >::computeHamiltonian(), setKuhn(), writeQ(), writeQAll(), writeQSlice(), and writeQTail().
polymer() [2/2]
template<int D, class PT, class ST> PT const & Pscf::MixtureTmpl< PT, ST >::polymer (int id) const inline
Get a polymer solver by const reference.
Parameters
id integer polymer species index (0 <= id < nPolymer)
Definition at line 99 of file MixtureTmpl.h.
polymerSpecies()
template<int D, class PT, class ST> PolymerSpecies const & Pscf::MixtureTmpl< PT, ST >::polymerSpecies (int id) const final virtual
Get a PolymerSpecies descriptor by const reference.
Defines function declared pure virtual by MixtureBase.
Parameters
id integer polymer species index (0 <= id < nPolymer)
Reimplemented from Pscf::MixtureTmpl< PT, ST >.
Definition at line 108 of file MixtureTmpl.h.
Referenced by Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), and Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations().
solvent() [1/2]
template<int D, class PT, class ST> ST & Pscf::MixtureTmpl< PT, ST >::solvent (int id) inline
Get a solvent solver object.
Parameters
id integer solvent species index (0 <= id < nSolvent)
Definition at line 115 of file MixtureTmpl.h.
Referenced by Pscf::Rpc::Simulator< D >::computeHamiltonian(), Pscf::Rpg::Simulator< D >::computeHamiltonian(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), and Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations().
solvent() [2/2]
template<int D, class PT, class ST> ST const & Pscf::MixtureTmpl< PT, ST >::solvent (int id) const inline
Get a solvent solver object by constant reference.
Parameters
id integer solvent species index (0 <= id < nSolvent)
Definition at line 122 of file MixtureTmpl.h.
solventSpecies()
template<int D, class PT, class ST> SolventSpecies const & Pscf::MixtureTmpl< PT, ST >::solventSpecies (int id) const final virtual
Set a SolventSpecies descriptor object by const reference.
Defines function declared pure virtual by MixtureBase.
Parameters
id integer solvent species index (0 <= id < nSolvent)
Reimplemented from Pscf::MixtureTmpl< PT, ST >.
Definition at line 131 of file MixtureTmpl.h.
References Pscf::MixtureBase::monomers_, Pscf::MixtureBase::nBlock_, Pscf::MixtureBase::nMonomer_, Pscf::MixtureBase::nPolymer_, Pscf::MixtureBase::nSolvent_, and Pscf::MixtureBase::vMonomer_.
nMonomer()
template<int D, class PT, class ST> int Pscf::MixtureBase::nMonomer () const inline
Get number of monomer types.
Definition at line 84 of file MixtureBase.h.
Referenced by allocate(), associate(), compute(), createBlockCRGrid(), and readParameters().
monomer() [1/2]
template<int D, class PT, class ST> Monomer const & Pscf::MixtureBase::monomer (int id) const inline
Get a Monomer type descriptor by const reference.
Parameters
id integer monomer type index (0 <= id < nMonomer)
Definition at line 124 of file MixtureBase.h.
Referenced by setKuhn().
monomer() [2/2]
template<int D, class PT, class ST> Monomer & Pscf::MixtureBase::monomer (int id) inline
Get a Monomer type descriptor (non-const reference).
Parameters
id integer monomer type index (0 <= id < nMonomer)
Definition at line 151 of file MixtureBase.h.
nPolymer()
template<int D, class PT, class ST> int Pscf::MixtureBase::nPolymer () const inline
Get number of polymer species.
Definition at line 89 of file MixtureBase.h.
Referenced by allocate(), associate(), clearUnitCellData(), compute(), computeStress(), readParameters(), setKuhn(), writeQ(), writeQAll(), writeQSlice(), and writeQTail().
nSolvent()
template<int D, class PT, class ST> int Pscf::MixtureBase::nSolvent () const inline
Get number of solvent (point particle) species.
Definition at line 94 of file MixtureBase.h.
Referenced by allocate(), associate(), compute(), createBlockCRGrid(), readParameters(), and writeBlockCRGrid().
nBlock()
template<int D, class PT, class ST> int Pscf::MixtureBase::nBlock () const inline
Get total number blocks among all polymer species.
Definition at line 99 of file MixtureBase.h.
Referenced by createBlockCRGrid(), and writeBlockCRGrid().
vMonomer()
template<int D, class PT, class ST> double Pscf::MixtureBase::vMonomer () const inline
Get monomer reference volume (set to 1.0 by default).
Definition at line 104 of file MixtureBase.h.
isCanonical()
template<int D, class PT, class ST> bool Pscf::MixtureBase::isCanonical () const
Is this mixture being treated in canonical ensemble?
Returns true iff a closed ensemble is used for every polymer and solve species, by specifying a volume fraction phi rather than a chemical potential mu for every species in the mixture.
Definition at line 113 of file MixtureBase.cpp.
setClassName()
template<int D, class PT, class ST> void Util::ParamComposite::setClassName (const char * className) protected
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by MixtureReal().
read()
template<int D, class PT, class ST> template<typename Type> ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value) protected
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 305 of file ParamComposite.h.
Referenced by readParameters().
readOptional()
template<int D, class PT, class ST> template<typename Type> ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
The documentation for this class was generated from the following files:
MixtureReal.h
MixtureReal.tpp