PSCF: TestException Class Reference
TestException Class Reference
An exception thrown by a failed unit test.
#include <TestException.h>
Public Member Functions
TestException ()
Default constructor.
TestException (const char *function, const char *message, const char *file, int line)
Constructor for throwing.
TestException (const char *message, const char *file, int line)
Constructor without function name parameter.
~TestException ()
Destructor.
void write (std::ostream &out)
Write error message to output stream.
const std::string & message ()
Return the error message.
Protected Attributes
std::string message_
Error message.
Detailed Description
An exception thrown by a failed unit test.
Definition at line 19 of file TestException.h.
Constructor & Destructor Documentation
TestException() [1/3]
TestException::TestException ()
Default constructor.
Function Definitions ---------------------------------------—.
Definition at line 87 of file TestException.h.
References message_.
TestException() [2/3]
TestException::TestException (const char * function, const char * message, const char * file, int line)
Constructor for throwing.
Constructs error message that includes file and line number. Values of the file and line parameters should be given by the built-in macros FILE and LINE, respectively, in the calling function. A typical call of the constructor is thus of the form:
throw TestException("MyClass::myFunction", "A terrible thing happened!",
                __FILE__, __LINE__ );
Parameters
function name of the function from which the TestException was thrown
message message describing the nature of the error
file name of the file from which the TestException was thrown
line line number in file
Definition at line 94 of file TestException.h.
References message(), and message_.
TestException() [3/3]
TestException::TestException (const char * message, const char * file, int line)
Constructor without function name parameter.
Parameters
message message describing the nature of the error
file name of the file from which the TestException was thrown
line line number in file
Definition at line 116 of file TestException.h.
References message(), and message_.
~TestException()
TestException::~TestException ()
Destructor.
Definition at line 134 of file TestException.h.
Member Function Documentation
write()
void TestException::write (std::ostream & out) inline
Write error message to output stream.
Parameters
out output stream
Definition at line 142 of file TestException.h.
References message_.
message()
const std::string & TestException::message () inline
Return the error message.
Definition at line 148 of file TestException.h.
References message_.
Referenced by UnitTestRunner< UnitTestClass >::method(), TestException(), and TestException().
Member Data Documentation
message_
std::string TestException::message_ protected
Error message.
Definition at line 78 of file TestException.h.
Referenced by message(), TestException(), TestException(), TestException(), and write().
The documentation for this class was generated from the following file:
TestException.h