PSCF: Util::Array< Data > Class Template Reference
Util::Array< Data > Class Template Reference
Util namespace » Container Templates » Object Arrays
Array container class template.
#include <Array.h>
Public Member Functions
virtual ~Array ()
Destructor.
int capacity () const
Return allocated size.
void begin (ArrayIterator< Data > &iterator)
Set an iterator to begin this Array.
void begin (ConstArrayIterator< Data > &iterator) const
Set a const iterator to begin this Array.
Data & operator[] (int i)
Get an element by non-const reference.
Data const & operator[] (int i) const
Get an element by const reference.
Data * cArray ()
Return a pointer to the underlying C array.
Data const * cArray () const
Return pointer to const to the underlying C array.
Protected Member Functions
Array ()
Default constructor.
Protected Attributes
Data * data_
Pointer to an array of Data elements.
int capacity_
Allocated size of the data_ array.
Detailed Description
template<typename Data>
class Util::Array< Data >
Array container class template.
An Array is a sequence that supports random access via an overloaded operator [], and that wraps a dynamically allocated C array.
Array is a base class for DArray, which is dynamically allocated, and RArray, which acts as a reference to another DArray or FSArray.
When compiled in debug mode (i.e., when NDEBUG is not defined) the subscript operator [] checks the validity of the element index.
Definition at line 33 of file Array.h.
Constructor & Destructor Documentation
~Array()
template<typename Data> Util::Array< Data >::~Array () virtual
Destructor.
Definition at line 152 of file Array.h.
Array()
template<typename Data> Util::Array< Data >::Array () protected
Default constructor.
Protected to prevent direct instantiation.
Definition at line 143 of file Array.h.
References capacity_, and data_.
Referenced by Util::RArray< Data >::associate(), Util::DArray< Data >::DArray(), Util::DArray< Data >::DArray(), Pscf::Prdc::Cpu::FftwDArray< Data >::FftwDArray(), Util::RArray< Data >::RArray(), and Util::RArray< Data >::RArray().
Member Function Documentation
capacity()
template<typename Data> int Util::Array< Data >::capacity () const inline
Return allocated size.
Returns
number of elements allocated in array
Definition at line 159 of file Array.h.
References capacity_.
Referenced by Pscf::Prdc::Cpu::FftwDArray< Data >::allocate(), Util::ArraySet< Data >::allocate(), Util::DArray< Data >::allocate(), Util::DRaggedMatrix< Data >::allocate(), Util::RArray< Data >::associate(), Util::RArray< Data >::associate(), Pscf::Prdc::checkAllocateFields(), Pscf::FieldComparison< FT >::compare(), Pscf::Prdc::Cpu::CFieldComparison< D >::compare(), Pscf::Prdc::Cpu::RFieldDftComparison< D >::compare(), Pscf::Prdc::Cuda::RFieldComparison< D >::compare(), Pscf::Prdc::Cuda::RFieldComparison< D >::compare(), Pscf::R1d::Mixture::compute(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::FieldIo< D >::convertBasisToKGrid(), Pscf::Prdc::FieldIoTmpl< D, RFT, KFT, FFT >::convertBasisToRGrid(), Pscf::Rpg::FieldIo< D >::convertKGridToBasis(), Pscf::Prdc::FieldIoTmpl< D, RFT, KFT, FFT >::convertKGridToRGrid(), Pscf::Prdc::FieldIoTmpl< D, RFT, KFT, FFT >::convertRGridToKGrid(), Util::Distribution::Distribution(), Pscf::R1d::FieldIo::extend(), Pscf::Prdc::Cpu::FFT< D >::forwardTransform(), Pscf::Prdc::Cpu::FFT< D >::forwardTransform(), Pscf::Rpg::FieldIo< D >::hasSymmetry(), Pscf::HostDArray< Data >::HostDArray(), Pscf::HostDArray< Complex >::HostDArray(), Pscf::R1d::Domain::innerProduct(), Pscf::Prdc::inspectArrays(), Pscf::Prdc::inspectFields(), Util::IntDistribution::IntDistribution(), Pscf::Prdc::Cpu::FFT< D >::inverseTransform(), Pscf::Prdc::Cpu::FFT< D >::inverseTransformSafe(), Pscf::Prdc::Cpu::FFT< D >::inverseTransformUnsafe(), Pscf::DeviceArray< Data >::operator=(), Pscf::Prdc::Cuda::CField< D >::operator=(), Pscf::Prdc::Cuda::RField< D >::operator=(), Pscf::Prdc::Cuda::RFieldDft< D >::operator=(), Util::DArray< Data >::operator=(), Util::Distribution::operator=(), Util::IntDistribution::operator=(), Util::Polynomial< T >::Polynomial(), Pscf::Prdc::readBasisData(), Pscf::Prdc::readBasisData(), Pscf::Prdc::FieldIoTmpl< D, RFT, KFT, FFT >::readFieldBasis(), Pscf::R1d::FieldIo::readFields(), Util::DArray< Data >::reallocate(), Pscf::R1d::FieldIo::remesh(), Pscf::Rpc::Mask< D >::rGridAverage(), Pscf::Rpg::Mask< D >::rGridAverage(), Pscf::Prdc::FieldIoTmpl< D, RFT, KFT, FFT >::scaleFieldBasis(), Pscf::Rpc::FieldIo< D >::scaleFieldRGrid(), Pscf::Prdc::FieldIoTmpl< D, RFT, KFT, FFT >::scaleFieldsRGrid(), Pscf::Prdc::Cpu::FftwDArray< Data >::serialize(), Util::DArray< Data >::serialize(), Pscf::Prdc::WFieldsTmpl< D, Prdc::Cpu::RField< D >, Rpc::FieldIo< D > >::setRGrid(), Pscf::Prdc::Cpu::FFT< D >::setup(), Pscf::LuSolver::solve(), Pscf::R1d::Domain::spatialAverage(), Pscf::Rpc::Block< D >::stepBondBead(), Pscf::Rpg::Block< D >::stepBondBead(), Pscf::Rpc::Block< D >::stepFieldBead(), Pscf::Rpg::Block< D >::stepFieldBead(), Pscf::Rpc::Block< D >::stepHalfBondBead(), Pscf::Rpg::Block< D >::stepHalfBondBead(), Pscf::Rpc::Block< D >::stepThread(), Pscf::Rpg::FilmFieldGenExt< D >::stress(), Pscf::Rpg::FilmFieldGenMask< D >::stress(), Pscf::Prdc::writeBasisData(), Pscf::Prdc::writeBasisData(), Pscf::R1d::FieldIo::writeField(), Pscf::Prdc::FieldIoTmpl< D, RFT, KFT, FFT >::writeFieldBasis(), Pscf::Rpg::FieldIo< D >::writeFieldRGrid(), and Pscf::R1d::FieldIo::writeFields().
begin() [1/2]
template<typename Data> void Util::Array< Data >::begin (ArrayIterator< Data > & iterator) inline
Set an iterator to begin this Array.
On return, iterator points to the first element of the array, and the iterator end pointer is set to one past the last element.
Parameters
iterator ArrayIterator, initialized on output
Definition at line 166 of file Array.h.
References capacity_, data_, Util::ArrayIterator< Data >::setCurrent(), and Util::ArrayIterator< Data >::setEnd().
begin() [2/2]
template<typename Data> void Util::Array< Data >::begin (ConstArrayIterator< Data > & iterator) const inline
Set a const iterator to begin this Array.
On return, iterator points to the first element of the array, and the iterator end pointer is set to one past the last element.
Parameters
iterator ConstArrayIterator, initialized on output
Definition at line 178 of file Array.h.
References capacity_, data_, Util::ConstArrayIterator< Data >::setCurrent(), and Util::ConstArrayIterator< Data >::setEnd().
operator[]() [1/2]
template<typename Data> Data & Util::Array< Data >::operator[] (int i) inline
Get an element by non-const reference.
Mimic C-array subscripting.
Parameters
i array index
Returns
non-const reference to element i
Definition at line 190 of file Array.h.
References capacity_, and data_.
operator[]() [2/2]
template<typename Data> Data const & Util::Array< Data >::operator[] (int i) const inline
Get an element by const reference.
Mimics C-array subscripting.
Parameters
i array index
Returns
const reference to element i
Definition at line 202 of file Array.h.
References capacity_, and data_.
cArray() [1/2]
template<typename Data> Data * Util::Array< Data >::cArray () inline
Return a pointer to the underlying C array.
Definition at line 214 of file Array.h.
References data_.
Referenced by Pscf::Prdc::Cuda::VecOp::addVMany(), Pscf::Prdc::Cuda::VecOp::addVMany(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenMask< D >::compute(), Pscf::Prdc::Cuda::VecOp::mulVMany(), Pscf::Prdc::Cuda::VecOp::mulVMany(), Pscf::DeviceArray< Data >::operator=(), Pscf::LuSolver::solve(), Pscf::Rpg::FilmFieldGenExt< D >::stress(), and Pscf::Rpg::FilmFieldGenMask< D >::stress().
cArray() [2/2]
template<typename Data> Data const * Util::Array< Data >::cArray () const inline
Return pointer to const to the underlying C array.
Definition at line 221 of file Array.h.
References data_.
Member Data Documentation
data_
template<typename Data> Data* Util::Array< Data >::data_ protected
Pointer to an array of Data elements.
Definition at line 109 of file Array.h.
Referenced by Util::DArray< Data >::allocate(), Array(), Util::RArray< Data >::associate(), Util::RArray< Data >::associate(), begin(), begin(), cArray(), cArray(), Util::DArray< Data >::DArray(), Pscf::Prdc::Cpu::FftwDArray< Data >::deallocate(), Util::DArray< Data >::deallocate(), Pscf::Prdc::Cpu::FftwDArray< Data >::isAllocated(), Util::DArray< Data >::isAllocated(), Pscf::Prdc::Cpu::CField< D >::operator=(), Pscf::Prdc::Cpu::RFieldDft< D >::operator=(), Util::DArray< Data >::operator=(), operator[](), operator[](), Util::RArray< Data >::RArray(), Util::DArray< Data >::reallocate(), Pscf::Prdc::Cpu::RFieldDft< D >::RFieldDft(), Pscf::Prdc::Cpu::FftwDArray< Data >::serialize(), Util::DArray< Data >::serialize(), Util::DArray< Data >::~DArray(), and Pscf::Prdc::Cpu::FftwDArray< Data >::~FftwDArray().
capacity_
template<typename Data> int Util::Array< Data >::capacity_ protected
Allocated size of the data_ array.
Definition at line 112 of file Array.h.
Referenced by Util::DArray< Data >::allocate(), Array(), Util::RArray< Data >::associate(), Util::RArray< Data >::associate(), begin(), begin(), capacity(), Pscf::Prdc::Cpu::CField< D >::CField(), Util::DArray< Data >::DArray(), Pscf::Prdc::Cpu::FftwDArray< Data >::deallocate(), Util::DArray< Data >::deallocate(), Pscf::Prdc::Cpu::CField< D >::operator=(), Pscf::Prdc::Cpu::RField< D >::operator=(), Pscf::Prdc::Cpu::RFieldDft< D >::operator=(), Util::DArray< Data >::operator=(), operator[](), operator[](), Util::RArray< Data >::RArray(), Util::DArray< Data >::reallocate(), Pscf::Prdc::Cpu::FftwDArray< Data >::serialize(), Util::DArray< Data >::serialize(), Util::DArray< Data >::~DArray(), and Pscf::Prdc::Cpu::FftwDArray< Data >::~FftwDArray().
The documentation for this class was generated from the following files:
AutoCorrArray.h
Array.h