PSCF: Pscf::Rpc::McMove< D > Class Template Reference
Pscf::Rpc::McMove< D > Class Template Reference
Pscf namespace » Pscf::Rpc - Real Periodic Fields (CPU) » Field Theoretic Simulation (FTS) » Monte Carlo
McMove is an abstract base class for Monte Carlo moves.
#include <McMove.h>
Public Member Functions
McMove (McSimulator< D > &simulator)
Constructor.
virtual ~McMove ()
Destructor.
virtual void readParameters (std::istream &in)
Read required parameters from file.
void setProbability (double probability)
Set the probability for this McMove.
virtual void setup ()
Setup before the beginning of each simulation run.
virtual bool move ()
Generate, attempt, and accept or reject a Monte Carlo move.
virtual bool needsCc ()
Decide whether cc fields need to be saved for move The default implementation is false.
virtual bool needsDc ()
Decide whether dc fields need to be saved for move The default implementation is false.
virtual void outputTimers (std::ostream &out)
Log output timing results.
virtual void clearTimers ()
Clear timers.
double probability () const
Return probability for this McMove.
long nAttempt () const
Return number of moves that have been attempted.
long nAccept () const
Return number of moves that have been accepted.
long nFail () const
Return number of moves that fail to converge.
virtual void output ()
Output statistics for this move (at the end of simulation)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
void incrementNAttempt ()
Increment the number of attempted moves.
void incrementNAccept ()
Increment the number of accepted moves.
void incrementNFail ()
Increment the number of failed moves.
System< D > & system ()
Get parent System object.
McSimulator< D > & simulator ()
Get parent McSimulator object.
Random & random ()
Get Random number generator of parent System.
void readProbability (std::istream &in)
Read the probability from file.
virtual void attemptMove ()
Attempt unconstrained move.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
Timer attemptMoveTimer_
Timers for McMove.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<int D>
class Pscf::Rpc::McMove< D >
McMove is an abstract base class for Monte Carlo moves.
The virtual move() method must generate a trial move, decide whether to accept or reject it, and update the associated System fields if it is accepted.
Definition at line 36 of file rpc/fts/montecarlo/McMove.h.
Constructor & Destructor Documentation
McMove()
template<int D> Pscf::Rpc::McMove< D >::McMove (McSimulator< D > & simulator)
Constructor.
Parameters
simulator parent McSimulator object
Definition at line 27 of file rpc/fts/montecarlo/McMove.tpp.
References random(), simulator(), and system().
Referenced by Pscf::Rpc::ForceBiasMove< D >::ForceBiasMove(), and Pscf::Rpc::RealMove< D >::RealMove().
~McMove()
template<int D> Pscf::Rpc::McMove< D >::~McMove () virtual
Destructor.
Empty default implementation.
Definition at line 40 of file rpc/fts/montecarlo/McMove.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpc::McMove< D >::readParameters (std::istream & in) virtual
Read required parameters from file.
Empty default implementation.
Reimplemented from Util::ParamComposite.
Reimplemented in Pscf::Rpc::ForceBiasMove< D >, and Pscf::Rpc::RealMove< D >.
Definition at line 47 of file rpc/fts/montecarlo/McMove.tpp.
setProbability()
template<int D> void Pscf::Rpc::McMove< D >::setProbability (double probability) inline
Set the probability for this McMove.
Parameters
probability Probability of this move being chosen.
Definition at line 316 of file rpc/fts/montecarlo/McMove.h.
References probability().
setup()
template<int D> void Pscf::Rpc::McMove< D >::setup () virtual
Setup before the beginning of each simulation run.
This method zeros the statistical accumulators nAttempt and nAccept. Derived class implementations should complete any other initialization that is required at the beginning of each simulation run within a sequence of several such runs.
Reimplemented in Pscf::Rpc::ForceBiasMove< D >, and Pscf::Rpc::RealMove< D >.
Definition at line 63 of file rpc/fts/montecarlo/McMove.tpp.
References clearTimers(), needsCc(), needsDc(), simulator(), and system().
Referenced by Pscf::Rpc::ForceBiasMove< D >::setup(), and Pscf::Rpc::RealMove< D >::setup().
move()
template<int D> bool Pscf::Rpc::McMove< D >::move () virtual
Generate, attempt, and accept or reject a Monte Carlo move.
Implementations of this by subclasses should:
Generate a proposed move
Decide to accept or reject (use random::metropolis)
Restore the old system state if rejected, and update the system state if accepted.
The default implementation provides a skeleton that calls the virtual attemptMove() function, calls the compressor after attemptMove(), and uses a Metropolis test based on the change of Hamiltonian for acceptance or rejection. MC moves for which this skeleton is appropriate can be implemented by redefining the attemptMove() function and using it in this default implementation of move(). MC moves for which this skeleton is inappropriate or inadequate can be implemented by redefining the move function.
Returns
true if converged, false if failed to converge.
Reimplemented in Pscf::Rpc::ForceBiasMove< D >.
Definition at line 85 of file rpc/fts/montecarlo/McMove.tpp.
References attemptMove(), attemptMoveTimer_, incrementNAccept(), incrementNAttempt(), incrementNFail(), needsCc(), needsDc(), random(), simulator(), system(), and UTIL_CHECK.
needsCc()
template<int D> virtual bool Pscf::Rpc::McMove< D >::needsCc () inline virtual
Decide whether cc fields need to be saved for move The default implementation is false.
Definition at line 108 of file rpc/fts/montecarlo/McMove.h.
Referenced by move(), and setup().
needsDc()
template<int D> virtual bool Pscf::Rpc::McMove< D >::needsDc () inline virtual
Decide whether dc fields need to be saved for move The default implementation is false.
Reimplemented in Pscf::Rpc::ForceBiasMove< D >.
Definition at line 115 of file rpc/fts/montecarlo/McMove.h.
Referenced by move(), and setup().
outputTimers()
template<int D> void Pscf::Rpc::McMove< D >::outputTimers (std::ostream & out) virtual
Log output timing results.
Reimplemented in Pscf::Rpc::ForceBiasMove< D >, and Pscf::Rpc::RealMove< D >.
Definition at line 166 of file rpc/fts/montecarlo/McMove.tpp.
References attemptMoveTimer_.
Referenced by Pscf::Rpc::ForceBiasMove< D >::outputTimers(), and Pscf::Rpc::RealMove< D >::outputTimers().
clearTimers()
template<int D> void Pscf::Rpc::McMove< D >::clearTimers () virtual
Clear timers.
Definition at line 199 of file rpc/fts/montecarlo/McMove.tpp.
References attemptMoveTimer_.
Referenced by setup().
probability()
template<int D> double Pscf::Rpc::McMove< D >::probability () const inline
Return probability for this McMove.
Definition at line 309 of file rpc/fts/montecarlo/McMove.h.
Referenced by setProbability().
nAttempt()
template<int D> long Pscf::Rpc::McMove< D >::nAttempt () const inline
Return number of moves that have been attempted.
Definition at line 244 of file rpc/fts/montecarlo/McMove.h.
nAccept()
template<int D> long Pscf::Rpc::McMove< D >::nAccept () const inline
Return number of moves that have been accepted.
Definition at line 251 of file rpc/fts/montecarlo/McMove.h.
nFail()
template<int D> long Pscf::Rpc::McMove< D >::nFail () const inline
Return number of moves that fail to converge.
Definition at line 258 of file rpc/fts/montecarlo/McMove.h.
output()
template<int D> void Pscf::Rpc::McMove< D >::output () virtual
Output statistics for this move (at the end of simulation)
Reimplemented in Pscf::Rpc::ForceBiasMove< D >, and Pscf::Rpc::RealMove< D >.
Definition at line 162 of file rpc/fts/montecarlo/McMove.tpp.
incrementNAttempt()
template<int D> void Pscf::Rpc::McMove< D >::incrementNAttempt () inline protected
Increment the number of attempted moves.
Definition at line 267 of file rpc/fts/montecarlo/McMove.h.
Referenced by Pscf::Rpc::ForceBiasMove< D >::move(), and move().
incrementNAccept()
template<int D> void Pscf::Rpc::McMove< D >::incrementNAccept () inline protected
Increment the number of accepted moves.
Definition at line 274 of file rpc/fts/montecarlo/McMove.h.
Referenced by Pscf::Rpc::ForceBiasMove< D >::move(), and move().
incrementNFail()
template<int D> void Pscf::Rpc::McMove< D >::incrementNFail () inline protected
Increment the number of failed moves.
Definition at line 281 of file rpc/fts/montecarlo/McMove.h.
Referenced by Pscf::Rpc::ForceBiasMove< D >::move(), and move().
system()
template<int D> System< D > & Pscf::Rpc::McMove< D >::system () inline protected
Get parent System object.
Definition at line 288 of file rpc/fts/montecarlo/McMove.h.
Referenced by Pscf::Rpc::RealMove< D >::attemptMove(), McMove(), Pscf::Rpc::ForceBiasMove< D >::move(), move(), Pscf::Rpc::ForceBiasMove< D >::readParameters(), Pscf::Rpc::ForceBiasMove< D >::setup(), setup(), and Pscf::Rpc::RealMove< D >::setup().
simulator()
template<int D> McSimulator< D > & Pscf::Rpc::McMove< D >::simulator () inline protected
Get parent McSimulator object.
Definition at line 295 of file rpc/fts/montecarlo/McMove.h.
Referenced by Pscf::Rpc::RealMove< D >::attemptMove(), Pscf::Rpc::ForceBiasMove< D >::ForceBiasMove(), McMove(), Pscf::Rpc::ForceBiasMove< D >::move(), move(), Pscf::Rpc::RealMove< D >::RealMove(), and setup().
random()
template<int D> Random & Pscf::Rpc::McMove< D >::random () inline protected
Get Random number generator of parent System.
Definition at line 302 of file rpc/fts/montecarlo/McMove.h.
Referenced by Pscf::Rpc::RealMove< D >::attemptMove(), McMove(), Pscf::Rpc::ForceBiasMove< D >::move(), and move().
readProbability()
template<int D> void Pscf::Rpc::McMove< D >::readProbability (std::istream & in) protected
Read the probability from file.
Definition at line 54 of file rpc/fts/montecarlo/McMove.tpp.
References Util::ParamComposite::read().
Referenced by Pscf::Rpc::ForceBiasMove< D >::readParameters(), and Pscf::Rpc::RealMove< D >::readParameters().
attemptMove()
template<int D> virtual void Pscf::Rpc::McMove< D >::attemptMove () inline protected virtual
Attempt unconstrained move.
This function should modify the system w fields in r-grid format, as returned by system().w().rgrid(), in order apply an unconstrained attempted move. The compressor will then be applied in order to restore the density constraint.
The default implementation is empty.
Reimplemented in Pscf::Rpc::RealMove< D >.
Definition at line 202 of file rpc/fts/montecarlo/McMove.h.
Referenced by move().
Member Data Documentation
attemptMoveTimer_
template<int D> Timer Pscf::Rpc::McMove< D >::attemptMoveTimer_ protected
Timers for McMove.
Definition at line 206 of file rpc/fts/montecarlo/McMove.h.
Referenced by clearTimers(), Pscf::Rpc::ForceBiasMove< D >::move(), move(), and outputTimers().
The documentation for this class was generated from the following files:
rpc/fts/montecarlo/McMove.h
rpc/fts/montecarlo/McMove.tpp