PSCF: Pscf::SolventDescriptor Class Reference
Pscf::SolventDescriptor Class Reference
Pscf namespace » Pscf Common » Chemical Structure
Chemical description of a solvent species.
#include <SolventDescriptor.h>
Public Member Functions
SolventDescriptor ()
Constructor.
~SolventDescriptor ()
Constructor.
void setMonomerId (int monomerId)
Set the monomer id for this solvent.
void setSize (double size)
Set the size or volume of this solvent species.
Accessors (getters)
int monomerId () const
Get the monomer type id.
double size () const
Get the size (number of monomers) in this solvent.
Public Member Functions inherited from Pscf::Species
Species ()
Default constructor.
double phi () const
Get overall volume fraction for this species.
double mu () const
Get chemical potential for this species (units kT=1).
double q () const
Get molecular partition function for this species.
Ensemble ensemble ()
Get statistical ensemble for this species (open or closed).
Additional Inherited Members
Public Types inherited from Pscf::Species
Protected Attributes inherited from Pscf::Species
double phi_
Volume fraction, set by either setPhi or compute function.
double mu_
Chemical potential, set by either setPhi or compute function.
double q_
Partition function, set by compute function.
Ensemble ensemble_
Statistical ensemble for this species (open or closed).
bool isComputed_
Set true by upon return by compute() and set false by clear().
Detailed Description
Chemical description of a solvent species.
Definition at line 23 of file SolventDescriptor.h.
Constructor & Destructor Documentation
Pscf::SolventDescriptor::SolventDescriptor () inline
Constructor.
Definition at line 30 of file SolventDescriptor.h.
Pscf::SolventDescriptor::~SolventDescriptor () inline
Constructor.
Definition at line 36 of file SolventDescriptor.h.
References Pscf::operator<<(), and Pscf::operator>>().
Member Function Documentation
void Pscf::SolventDescriptor::setMonomerId (int monomerId)
Set the monomer id for this solvent.
Parameters
monomerId integer id of monomer type (>=0)
void Pscf::SolventDescriptor::setSize (double size)
Set the size or volume of this solvent species.
The ``size" is steric volume / reference volume.
Parameters
size volume of solvent
int Pscf::SolventDescriptor::monomerId () const inline
Get the monomer type id.
Definition at line 96 of file SolventDescriptor.h.
double Pscf::SolventDescriptor::size () const inline
Get the size (number of monomers) in this solvent.
Definition at line 102 of file SolventDescriptor.h.
References Pscf::operator<<(), Pscf::operator>>(), and Util::serialize().
The documentation for this class was generated from the following file:
SolventDescriptor.h