PSCF: Util::Polynomial< T > Class Template Reference
Util::Polynomial< T > Class Template Reference
Util namespace » Mathematics
A Polynomial (i.e,.
#include <Polynomial.h>
Public Member Functions
Constructors, Destructors, and Assignment
Polynomial (int capacity=10)
Construct a zero polynomial.
Polynomial (T c)
Construct a constant polynomial.
Polynomial (Array< T > const &coeffs)
Construct a polynomial from array of coefficients.
Polynomial (Polynomial< T > const &other)
Copy constructor.
template<typename U>
Polynomial< T > & operator= (Polynomial< U > const &other)
Assignment from another polynomial.
void setToZero ()
Assign this polynomial a value of zero.
Simple Accessors
int degree () const
Return degree of polynomial.
Arithmetic Assignment Operators
Polynomial< T > & operator+= (Polynomial< T > const &a)
Add another polynomial to this one.
Polynomial< T > & operator+= (T a)
Add a constant to this polynomial.
Polynomial< T > & operator-= (Polynomial< T > const &a)
Subtract another polynomial from this one.
Polynomial< T > & operator-= (T a)
Subtract a constant from this polynomial.
Polynomial< T > & operator*= (T a)
Multiply this polynomial by a scalar.
Polynomial< T > & operator/= (T a)
Divide this polynomial by a scalar.
Polynomial< T > & operator*= (Polynomial< T > const &a)
Multiply this polynomial by another.
Mathematical Functions (return polynomials)
Polynomial< T > integrate () const
Compute and return indefinite integral of this polynomial.
Polynomial< T > differentiate () const
Compute and return derivative of this polynomial.
Polynomial< T > reflect () const
Compute and return reflected polynomial f(-x).
Polynomial< T > shift (T a) const
Compute and return shifted polynomial f(x+a).
Polynomial Evaluation Functions
T operator() (T x) const
Evaluate polynomial at specific argument of type T.
double evaluate (double x) const
Evaluate polynomial at specific floating point argument.
static Polynomial< T > monomial (int n)
Return a monomial f(x) = x^{n}.
Detailed Description
template<typename T = Rational>
class Util::Polynomial< T >
A Polynomial (i.e,.
a list of coefficents).
Definition at line 29 of file Polynomial.h.
Constructor & Destructor Documentation
Polynomial() [1/4]
template<typename T> Util::Polynomial< T >::Polynomial (int capacity = 10) inline
Construct a zero polynomial.
Creates a zero polynomial f(x) = 0, with no stored coefficients. The capacity parameter specifies how much physical space to allocate for subsqequent growth in the array of coefficients.
Parameters
capacity initial capacity of coefficient array.
Definition at line 263 of file Polynomial.h.
References Util::GArray< Rational >::capacity(), and Util::GArray< Data >::reserve().
Referenced by differentiate(), integrate(), monomial(), operator*=(), operator*=(), operator+=(), operator+=(), operator-=(), operator-=(), operator/=(), operator=(), Polynomial(), reflect(), and shift().
Polynomial() [2/4]
template<typename T> Util::Polynomial< T >::Polynomial (T c) inline explicit
Construct a constant polynomial.
Creates a polynomial f(x) = c, with degree() = 0.
Parameters
c constant coefficient value
Definition at line 271 of file Polynomial.h.
References Util::GArray< Data >::append(), and Util::GArray< Data >::reserve().
Polynomial() [3/4]
template<typename T> Util::Polynomial< T >::Polynomial (Array< T > const & coeffs) inline
Construct a polynomial from array of coefficients.
Constructs a polynomial in which the coefficient of x^{i} is given by coeffs[i]. The logical and physical size of the coefficient array are both set to the capacity of coeffs.
Parameters
coeffs array of coefficients.
Definition at line 282 of file Polynomial.h.
References Util::GArray< Data >::append(), Util::Array< Data >::capacity(), and Util::GArray< Data >::reserve().
Polynomial() [4/4]
template<typename T> Util::Polynomial< T >::Polynomial (Polynomial< T > const & other) inline
Copy constructor.
Parameters
other Polynomial to be copied
Definition at line 297 of file Polynomial.h.
References Util::GArray< Data >::append(), Polynomial(), and Util::GArray< Data >::reserve().
Member Function Documentation
operator=()
template<typename T> template<typename U> Polynomial< T > & Util::Polynomial< T >::operator= (Polynomial< U > const & other) inline
Assignment from another polynomial.
Parameters
other Polynomial to assign.
Definition at line 313 of file Polynomial.h.
References Util::GArray< Data >::append(), Util::GArray< Rational >::capacity(), Polynomial(), Util::GArray< Data >::reserve(), and Util::setToZero().
setToZero()
template<typename T> void Util::Polynomial< T >::setToZero () inline
Assign this polynomial a value of zero.
Equivalent to GArray::clear(): Clears all coefficients, setting size = 0 and degree = -1.
Definition at line 334 of file Polynomial.h.
References Util::GArray< Data >::clear().
Referenced by differentiate(), and integrate().
degree()
template<typename T> int Util::Polynomial< T >::degree () const inline
Return degree of polynomial.
Returns size() - 1, number of coefficients - 1. By convention, a zero polynomial has degree = -1.
Definition at line 342 of file Polynomial.h.
References Util::GArray< Data >::size().
Referenced by evaluate(), operator()(), and shift().
operator+=() [1/2]
template<typename T> Polynomial< T > & Util::Polynomial< T >::operator+= (Polynomial< T > const & a)
Add another polynomial to this one.
Upon return, *this = this + a.
Parameters
a increment (input)
Definition at line 349 of file Polynomial.h.
References Util::GArray< Data >::append(), Polynomial(), Util::GArray< Rational >::size(), and UTIL_CHECK.
operator+=() [2/2]
template<typename T> Polynomial< T > & Util::Polynomial< T >::operator+= (T a)
Add a constant to this polynomial.
Upon return, *this = this + a.
Parameters
a increment (input)
Definition at line 372 of file Polynomial.h.
References Polynomial(), and Util::GArray< Rational >::size().
operator-=() [1/2]
template<typename T> Polynomial< T > & Util::Polynomial< T >::operator-= (Polynomial< T > const & a)
Subtract another polynomial from this one.
Upon return, *this = this + a.
Parameters
a decrement (input)
Definition at line 386 of file Polynomial.h.
References Util::GArray< Data >::append(), Polynomial(), Util::GArray< Rational >::size(), and UTIL_CHECK.
operator-=() [2/2]
template<typename T> Polynomial< T > & Util::Polynomial< T >::operator-= (T a)
Subtract a constant from this polynomial.
Upon return, *this = this + a.
Parameters
a increment (input)
Definition at line 409 of file Polynomial.h.
References Polynomial(), and Util::GArray< Rational >::size().
operator*=() [1/2]
template<typename T> Polynomial< T > & Util::Polynomial< T >::operator*= (T a) inline
Multiply this polynomial by a scalar.
Upon return, *this = this*a.
Parameters
a scalar factor
Definition at line 424 of file Polynomial.h.
References Polynomial(), and Util::GArray< Rational >::size().
operator/=()
template<typename T> Polynomial< T > & Util::Polynomial< T >::operator/= (T a) inline
Divide this polynomial by a scalar.
Upon return, *this = this*a.
Parameters
a scalar factor (input)
Definition at line 439 of file Polynomial.h.
References Polynomial(), and Util::GArray< Rational >::size().
operator*=() [2/2]
template<typename T> Polynomial< T > & Util::Polynomial< T >::operator*= (Polynomial< T > const & a)
Multiply this polynomial by another.
Upon return, *this = this*a.
Parameters
a increment (input)
Definition at line 453 of file Polynomial.h.
References Util::GArray< Data >::append(), Util::GArray< Rational >::capacity(), Util::GArray< Rational >::GArray(), Polynomial(), Util::GArray< Data >::reserve(), Util::setToZero(), Util::GArray< Data >::size(), Util::GArray< Rational >::size(), and UTIL_ASSERT.
integrate()
template<typename T> Polynomial< T > Util::Polynomial< T >::integrate () const
Compute and return indefinite integral of this polynomial.
Returns an indefinite integral with zero constant term.
Returns
indefinite integral polynomial.
Definition at line 501 of file Polynomial.h.
References Util::DArray< Data >::allocate(), Polynomial(), setToZero(), and Util::GArray< Rational >::size().
differentiate()
template<typename T> Polynomial< T > Util::Polynomial< T >::differentiate () const
Compute and return derivative of this polynomial.
Returns a polynomial of one smaller degree.
Returns
derivative polynomial
Definition at line 527 of file Polynomial.h.
References Util::DArray< Data >::allocate(), Polynomial(), setToZero(), and Util::GArray< Rational >::size().
reflect()
template<typename T> Polynomial< T > Util::Polynomial< T >::reflect () const
Compute and return reflected polynomial f(-x).
If this polynomial is f(x), this returns a polynomial g(x) = f(-x) created by the reflection operation x-> -x. This yields a polynomial in which the sign is reversed for all coefficients of odd powers of x.
Returns
polynomial created by reflection x -> -x.
Definition at line 556 of file Polynomial.h.
References Polynomial().
shift()
template<typename T> Polynomial< T > Util::Polynomial< T >::shift (T a) const
Compute and return shifted polynomial f(x+a).
If this polynomial is f(x), this returns a polynomial g(x) = f(x+a) created by the shift operation x-> x + a.
Returns
polynomial created by shift operation x -> x + a.
Definition at line 575 of file Polynomial.h.
References Util::Binomial::coeff(), degree(), Polynomial(), Util::Binomial::setup(), and Util::GArray< Rational >::size().
operator()()
template<typename T> T Util::Polynomial< T >::operator() (T x) const inline
Evaluate polynomial at specific argument of type T.
Parameters
x value of argument
Returns
Value f(x) of this polynomial at specified x
Definition at line 601 of file Polynomial.h.
References degree(), and Util::GArray< Rational >::size().
evaluate()
template<typename T> double Util::Polynomial< T >::evaluate (double x) const inline
Evaluate polynomial at specific floating point argument.
Parameters
x value of argument x
Returns
Value f(x) of polynomial at specified x
Definition at line 622 of file Polynomial.h.
References degree(), and Util::GArray< Rational >::size().
monomial()
template<typename T> Polynomial< T > Util::Polynomial< T >::monomial (int n) static
Return a monomial f(x) = x^{n}.
Return a monomial.
Parameters
n power of x in monomial.
Definition at line 645 of file Polynomial.h.
References Polynomial(), and UTIL_CHECK.
The documentation for this class was generated from the following file:
Polynomial.h