PSCF: Util::DMatrixParam< Type > Class Template Reference
Util::DMatrixParam< Type > Class Template Reference
Util namespace » Parameter File IO
A Parameter associated with a 2D built-in C array.
#include <DMatrixParam.h>
Public Member Functions
DMatrixParam (const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Constructor.
void writeParam (std::ostream &out) const
Write DMatrix to file.
std::string indent () const
Return indent string for this object (string of spaces).
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::MatrixParam< Type >
MatrixParam (const char *label, int m, int n, bool isRequired=true)
Constructor.
virtual ~MatrixParam ()
Destructor.
int m () const
Get the logical array dimension.
int n () const
Get the logical array dimension.
std::string indent () const
Return indent string for this object (string of spaces).
virtual void readValue (std::istream &in)
Read parameter value from an input stream.
virtual void load (Serializable::IArchive &ar)
Load from an archive.
virtual void save (Serializable::OArchive &ar)
Save to an archive.
std::string label () const
Return label string.
bool isRequired () const
Is this an optional parameter?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::Parameter
Parameter (const char *label, bool isRequired=true)
Constructor.
virtual ~Parameter ()
Destructor.
virtual void readParam (std::istream &in)
Read a label and (if the label matches) a parameter value.
std::string label () const
Return label string.
bool isRequired () const
Is this an optional parameter?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
virtual void readValue (std::istream &in)
Read parameter value from an input stream.
virtual void loadValue (Serializable::IArchive &ar)
Load bare parameter value from an archive.
virtual void saveValue (Serializable::OArchive &ar)
Save parameter value to an archive.
Protected Member Functions inherited from Util::MatrixParam< Type >
virtual void readLabel (std::istream &in)
Read parameter label from an input stream.
void readEndBracket (std::istream &in)
Read the closing delimiter, if any.
void writeEndBracket (std::ostream &out) const
Write the end bracket delimiter, if any.
bool hasBrackets () const
Are brackets being used as delimiters?
void setBrackets (std::string lBracket, std::string rBracket)
Set left and right bracket / delimiter strings.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::Parameter
template<class Type>
static void saveOptional (Serializable::OArchive &ar, Type &value, bool isActive)
Save an optional parameter value to an output archive.
template<class Type>
static void saveOptionalCArray (Serializable::OArchive &ar, Type *ptr, int n, bool isActive)
Save an optional C-array of n values to an output archive.
template<class Type>
static void saveOptionalCArray2D (Serializable::OArchive &ar, Type *ptr, int m, int n, int np, bool isActive)
Save an optional two-dimensional C array to an output archive.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Util::Parameter
static const int Width = 20
Width of output field for a scalar variable.
static const int Precision = 12
Precision for io of floating point data field.
Protected Attributes inherited from Util::MatrixParam< Type >
Label label_
Label object that contains parameter label string.
Protected Attributes inherited from Util::Parameter
Label label_
Label object that contains parameter label string.
bool isActive_
Is this parameter active (always true if isRequired).
Detailed Description
template<class Type>
class Util::DMatrixParam< Type >
A Parameter associated with a 2D built-in C array.
Definition at line 29 of file DMatrixParam.h.
Constructor & Destructor Documentation
DMatrixParam()
template<class Type> Util::DMatrixParam< Type >::DMatrixParam (const char * label, DMatrix< Type > & matrix, int m, int n, bool isRequired = true)
Constructor.
Parameters
label parameter label (a literal C-string)
matrix DMatrix<Type> object
m number of rows
n number of columns
isRequired Is this a required parameter?
Definition at line 99 of file DMatrixParam.h.
References Util::MatrixParam< Type >::isRequired(), Util::MatrixParam< Type >::label(), Util::MatrixParam< Type >::m(), Util::MatrixParam< Type >::MatrixParam(), Util::MatrixParam< Type >::n(), and Util::MatrixParam< Type >::setBrackets().
Member Function Documentation
writeParam()
template<class Type> void Util::DMatrixParam< Type >::writeParam (std::ostream & out) const virtual
Write DMatrix to file.
Implements Util::ParamComponent.
Definition at line 194 of file DMatrixParam.h.
References Util::MatrixParam< Type >::hasBrackets(), indent(), isActive(), Util::Parameter::label_, Util::MatrixParam< Type >::m(), Util::MatrixParam< Type >::n(), Util::Parameter::Precision, UTIL_THROW, Util::Parameter::Width, and Util::MatrixParam< Type >::writeEndBracket().
readValue()
template<class Type> void Util::DMatrixParam< Type >::readValue (std::istream & in) protected virtual
Read parameter value from an input stream.
Parameters
in input stream from which to read
Reimplemented from Util::Parameter.
Definition at line 112 of file DMatrixParam.h.
References Util::MatrixParam< Type >::m(), Util::MatrixParam< Type >::n(), Util::MatrixParam< Type >::readEndBracket(), and UTIL_THROW.
loadValue()
template<class Type> void Util::DMatrixParam< Type >::loadValue (Serializable::IArchive & ar) protected virtual
Load bare parameter value from an archive.
Parameters
ar input archive from which to load
Reimplemented from Util::Parameter.
Definition at line 139 of file DMatrixParam.h.
References Util::MatrixParam< Type >::m(), Util::MatrixParam< Type >::n(), and UTIL_THROW.
saveValue()
template<class Type> void Util::DMatrixParam< Type >::saveValue (Serializable::OArchive & ar) protected virtual
Save parameter value to an archive.
Parameters
ar output archive to which to save
Reimplemented from Util::Parameter.
Definition at line 158 of file DMatrixParam.h.
References Util::MatrixParam< Type >::m(), Util::MatrixParam< Type >::n(), and UTIL_THROW.
indent()
template<class Type> std::string Util::ParamComponent::indent () const
Return indent string for this object (string of spaces).
Definition at line 96 of file ParamComponent.cpp.
Referenced by writeParam().
isActive()
template<class Type> bool Util::Parameter::isActive () const
Is this parameter active?
Definition at line 180 of file Parameter.cpp.
Referenced by writeParam().
The documentation for this class was generated from the following file:
DMatrixParam.h