PSCF: Pscf::Pspg::System< D > Class Template Reference
Pscf::Pspg::System< D > Class Template Reference
Pscf namespace » Periodic Pseudo-Spectral (GPU)
Main class in SCFT simulation of one system.
#include <System.h>
Public Member Functions
Construction and Destruction
System ()
Constructor.
~System ()
Destructor.
Lifetime (Actions)
void setOptions (int argc, char **argv)
Process command line options.
void setGpuResources (int nBlocks, int nThreads)
Explicitly set number of blocks and number of threads.
virtual void readParam (std::istream &in)
Read input parameters (with opening and closing lines).
void readParam ()
Read input parameters from default param file.
virtual void readParameters (std::istream &in)
Read body of parameter file (without opening, closing lines).
void readCommands (std::istream &in)
Read command script.
void readCommands ()
Read commands from default command file.
State Modifiers (Modify W Fields & Unit Cell)
void readWBasis (const std::string &filename)
Read chemical potential fields in symmetry adapted basis format.
void readWRGrid (const std::string &filename)
Read chemical potential fields in real space grid (r-grid) format.
void setWBasis (DArray< DArray< double > > const &fields)
Set new w fields, in symmetrized Fourier format.
void setWRGrid (DArray< RDField< D > > const &fields)
Set new w fields, in real-space (r-grid) format.
void setWRGrid (DField< cudaReal > &fields)
Set new w fields, in unfoled real-space (r-grid) format.
void symmetrizeWFields ()
Symmetrize r-grid w-fields, compute basis components.
void setUnitCell (UnitCell< D > const &unitCell)
Set parameters of the associated unit cell.
void setUnitCell (FSArray< double, 6 > const &parameters)
Set parameters of the associated unit cell.
Primary SCFT Computations
void compute (bool needStress=false)
Solve the modified diffusion equation once, without iteration.
int iterate (bool isContinuation=false)
Iteratively solve a SCFT problem.
void sweep ()
Sweep in parameter space, solving an SCF problem at each point.
Thermodynamic Properties
void computeFreeEnergy ()
Compute free energy density and pressure for current fields.
double fHelmholtz () const
Get precomputed Helmoltz free energy per monomer / kT.
double pressure () const
Get precomputed pressure x monomer volume kT.
Output Operations (correspond to command file commands)
void writeWBasis (const std::string &filename)
Write chemical potential fields in symmetry adapted basis format.
void writeWRGrid (const std::string &filename) const
Write chemical potential fields in real space grid (r-grid) format.
void writeCBasis (const std::string &filename)
Write concentrations in symmetry-adapted basis format.
void writeCRGrid (const std::string &filename) const
Write concentration fields in real space grid (r-grid) format.
void writeBlockCRGrid (const std::string &filename) const
Write c-fields for all blocks and solvents in r-grid format.
void writePropagatorTail (const std::string &filename, int polymerID, int blockID)
Write tail (last slice) of a propagator in r-grid format.
void writeQSlice (std::string const &filename, int polymerId, int blockId, int directionId, int segmentId) const
Write slice of a propagator at fixed s in r-grid format.
void writeQTail (std::string const &filename, int polymerId, int blockId, int directionId) const
Write the final slice of a propagator in r-grid format.
void writeQ (std::string const &filename, int polymerId, int blockId, int directionId) const
Write one propagator for one block, in r-grid format.
void writeQAll (std::string const &basename)
Write all propagators of all blocks, each to a separate file.
void writeParamNoSweep (std::ostream &out) const
Write parameter file to an ostream, omitting the sweep block.
void writeThermo (std::ostream &out)
Write thermodynamic properties to a file.
void writeStars (const std::string &outFileName) const
Output information about stars and symmetrized basis functions.
void writeWaves (const std::string &outFileName) const
Output information about waves.
Field Operations (correspond to command file commands)
void basisToRGrid (const std::string &inFileName, const std::string &outFileName)
Convert a field from symmetry-adapted basis to r-grid format.
void rGridToBasis (const std::string &inFileName, const std::string &outFileName)
Convert a field from real-space grid to symmetrized basis format.
void kGridToRGrid (const std::string &inFileName, const std::string &outFileName) const
Convert fields from Fourier (k-grid) to real-space (r-grid) format.
void rGridToKGrid (const std::string &inFileName, const std::string &outFileName) const
Convert fields from real-space (r-grid) to Fourier (k-grid) format.
void kGridToBasis (const std::string &inFileName, const std::string &outFileName) const
Convert fields from Fourier (k-grid) to symmetrized basis format.
void basisToKGrid (const std::string &inFileName, const std::string &outFileName) const
Convert fields from symmetrized basis to Fourier (k-grid) format.
void guessWfromC (const std::string &inFileName, const std::string &outFileName)
Construct trial w-fields from c-fields.
Chemical Potential Field (W Field) Accessors
DArray< DArray< double > > const & wFieldsBasis () const
Get array of chemical potential fields, in a basis.
DArray< double > const & wFieldBasis (int monomerId) const
Get chemical potential field for one monomer type, in a basis.
DArray< RDField< D > > const & wFieldsRGrid () const
Get array of all w fields, in r-space format, by const ref.
RDField< D > const & wFieldRGrid (int monomerId) const
Get w field for one monomer type in r-space format by const ref.
Concentration / Volume Fraction Field (C Fields) Accessors
DArray< DArray< double > > const & cFieldsBasis () const
Get an array of all monomer concentration fields, in a basis.
DArray< double > const & cFieldBasis (int monomerId) const
Get the concentration field for one monomer type, in a basis.
DArray< RDField< D > > const & cFieldsRGrid () const
Get array of all concentration fields (c fields), on a grid.
RDField< D > const & cFieldRGrid (int monomerId) const
Get the concentration (c field) for one monomer type, on a grid.
Accessors (return sub-objects by reference)
Mixture< D > & mixture ()
Get Mixture by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
Interaction const & interaction () const
Get interaction (i.e., excess free energy model) by const ref.
Domain< D > const & domain () const
Get Domain by const reference.
UnitCell< D > const & unitCell () const
Get crystal UnitCell by const reference.
Mesh< D > const & mesh () const
Get spatial discretization Mesh by const reference.
Basis< D > const & basis () const
Get the Basis by reference.
WaveList< D > & wavelist ()
Get container for wavevector data.
Iterator< D > & iterator ()
Get the iterator by reference.
FieldIo< D > const & fieldIo () const
Get the FieldIo by const reference.
FFT< D > const & fft () const
Get the FFT object by reference.
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
Accessors (return by value)
std::string groupName ()
Get the group name string.
bool hasWFields () const
Have monomer chemical potential fields (w fields) been set?
bool hasCFields () const
Have monomer concentration fields (c fields) been computed?
bool hasSymmetricFields () const
Are w-fields symmetric under all elements of the space group?
bool hasSweep () const
Does this system have an associated Sweep object?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void readParam (std::istream &in)=0
Read parameter(s) from file.
virtual void writeParam (std::ostream &out) const =0
Read parameter(s) to file.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
virtual void save (OArchive &ar)=0
Save to an archive.
virtual void load (IArchive &ar)=0
Load from an archive.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
template<int D>
class Pscf::Pspg::System< D >
Main class in SCFT simulation of one system.
Definition at line 46 of file pspg/System.h.
Constructor & Destructor Documentation
System()
template<int D> Pscf::Pspg::System< D >::System
Constructor.
Definition at line 42 of file pspg/System.tpp.
References Pscf::Pspg::ThreadGrid::init(), and Util::ParamComposite::setClassName().
~System()
template<int D> Pscf::Pspg::System< D >::~System
Destructor.
Definition at line 81 of file pspg/System.tpp.
Member Function Documentation
setOptions()
template<int D> void Pscf::Pspg::System< D >::setOptions (int argc, char ** argv)
Process command line options.
Parameters
argc number of command line arguments
argv array of argument strings
Definition at line 113 of file pspg/System.tpp.
References Util::Log::file(), Util::FileMaster::setCommandFileName(), Util::ParamComponent::setEcho(), Util::FileMaster::setInputPrefix(), Util::FileMaster::setOutputPrefix(), Util::FileMaster::setParamFileName(), Pscf::Pspg::ThreadGrid::setThreadsPerBlock(), and UTIL_THROW.
setGpuResources()
template<int D> void Pscf::Pspg::System< D >::setGpuResources (int nBlocks, int nThreads)
Explicitly set number of blocks and number of threads.
Parameters
nBlocks number of blocks
nThreads number of threads per block
readParam() [1/2]
template<int D> void Pscf::Pspg::System< D >::readParam (std::istream & in) virtual
Read input parameters (with opening and closing lines).
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 253 of file pspg/System.tpp.
readParam() [2/2]
template<int D> void Pscf::Pspg::System< D >::readParam
Read input parameters from default param file.
Definition at line 264 of file pspg/System.tpp.
readParameters()
template<int D> void Pscf::Pspg::System< D >::readParameters (std::istream & in) virtual
Read body of parameter file (without opening, closing lines).
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 197 of file pspg/System.tpp.
References UTIL_THROW.
readCommands() [1/2]
template<int D> void Pscf::Pspg::System< D >::readCommands (std::istream & in)
Read command script.
Parameters
in command script file.
Definition at line 295 of file pspg/System.tpp.
References Util::Log::file(), Util::FileMaster::openOutputFile(), and UTIL_CHECK.
readCommands() [2/2]
template<int D> void Pscf::Pspg::System< D >::readCommands
Read commands from default command file.
Definition at line 479 of file pspg/System.tpp.
References UTIL_THROW.
readWBasis()
template<int D> void Pscf::Pspg::System< D >::readWBasis (const std::string & filename)
Read chemical potential fields in symmetry adapted basis format.
This function opens and reads the file named "filename", which contains chemical potential fields in symmetry-adapted basis format, stores these fields in the system wFieldsBasis array, computes corresponding real-space grid format and stores that in the wFieldsRGrid array. On exit, hasWFields and hasSymmetricFields are set true and hasCFields is false.
Parameters
filename name of input w-field basis file
Definition at line 733 of file pspg/System.tpp.
readWRGrid()
template<int D> void Pscf::Pspg::System< D >::readWRGrid (const std::string & filename)
Read chemical potential fields in real space grid (r-grid) format.
This function opens and reads the file named "filename", which contains chemical potential fields in real space grid format, and copies these fields to the system wFieldsRGrid array. On exit, hasWFields is true, while hasSymmetricFields and hasCFields are false.
Parameters
filename name of input w-field basis file
Definition at line 858 of file pspg/System.tpp.
setWBasis()
template<int D> void Pscf::Pspg::System< D >::setWBasis (DArray< DArray< double > > const & fields)
Set new w fields, in symmetrized Fourier format.
On exit hasWFields and hasSymmetric fields are set true, while hasCFields is set false.
Parameters
fields array of new w (chemical potential) fields
Definition at line 750 of file pspg/System.tpp.
setWRGrid() [1/2]
template<int D> void Pscf::Pspg::System< D >::setWRGrid (DArray< RDField< D > > const & fields)
Set new w fields, in real-space (r-grid) format.
On exit, hasWFields is set true while hasSymmetricFields and hasCFields are both false.
Parameters
fields array of new w (chemical potential) fields
Definition at line 775 of file pspg/System.tpp.
setWRGrid() [2/2]
template<int D> void Pscf::Pspg::System< D >::setWRGrid (DField< cudaReal > & fields)
Set new w fields, in unfoled real-space (r-grid) format.
The array fields is an unfolded array that contains fields for all monomer types, with the field for monomer 0 first, etc.
On exit hasWFields is set true while hasSymmetricFields and hasCFields are both false.
Parameters
fields unfolded array of new w (chemical potential) fields
Definition at line 791 of file pspg/System.tpp.
References Pscf::Pspg::DField< Data >::cDField(), Pscf::Pspg::ThreadGrid::nBlocks(), Pscf::Pspg::ThreadGrid::nThreads(), and Pscf::Pspg::ThreadGrid::setThreadsLogical().
symmetrizeWFields()
template<int D> void Pscf::Pspg::System< D >::symmetrizeWFields
Symmetrize r-grid w-fields, compute basis components.
Use this function after setting or reading w fields in r-grid format that are known to be symmetric under the space group. The function computes corresponding components in symmetrized basis format, which are stored in the wFieldsBasis array, and then recomputes the r-grid format for the fields from the resulting components. This yields fields that are symmetric and that are equal to the original fields only if those field were symmetric. The function assumes that the current wFieldsRGrid fields are known to be symmetric, and does NOT check this.
Precondition: On entry hasWFields must be true. Postcondition: On exit, hasWFields and hasSymmetricFields are true, and hasCFields is false.
Definition at line 822 of file pspg/System.tpp.
References UTIL_CHECK.
setUnitCell() [1/2]
template<int D> void Pscf::Pspg::System< D >::setUnitCell (UnitCell< D > const & unitCell)
Set parameters of the associated unit cell.
Parameters
unitCell new UnitCell<D> (i.e., new parameters)
Definition at line 835 of file pspg/System.tpp.
References UTIL_CHECK.
setUnitCell() [2/2]
template<int D> void Pscf::Pspg::System< D >::setUnitCell (FSArray< double, 6 > const & parameters)
Set parameters of the associated unit cell.
Parameters
parameters array of new unit cell parameters.
Definition at line 847 of file pspg/System.tpp.
References Util::FSArray< Data, Capacity >::size(), and UTIL_CHECK.
compute()
template<int D> void Pscf::Pspg::System< D >::compute (bool needStress = false)
Solve the modified diffusion equation once, without iteration.
This function calls the Mixture::compute() function to solve the statistical mechanics problem for a non-interacting system subjected to the currrent chemical potential fields (wFields and wFieldRGrid). This requires solution of the modified diffusion equation for all polymers, computation of Boltzmann weights for all solvents, computation of molecular partition functions for all species, and computation of concentration fields for blocks and solvents, and computation of overall concentrations for all monomer types. This function does not compute the canonical (Helmholtz) free energy or grand-canonical free energy (i.e., pressure). Upon return, the flag hasCFields is set true.
If argument needStress == true, then this function also calls Mixture<D>::computeStress() to compute the stress.
Parameters
needStress true if stress is needed, false otherwise
Definition at line 871 of file pspg/System.tpp.
References UTIL_CHECK.
iterate()
template<int D> int Pscf::Pspg::System< D >::iterate (bool isContinuation = false)
Iteratively solve a SCFT problem.
This function calls the iterator to attempt to solve the SCFT problem for the current mixture and system parameters, using the current chemical potential fields (wFields and wFieldRGrid) and current unit cell parameter values as initial guesses. Upon exist, hasCFields is set true whether or not convergence is obtained to within the desired tolerance. The Helmholtz free energy and pressure are computed if and only if convergence is obtained.
Precondition
The hasWFields flag must be true on entry
Parameters
isContinuation true iff continuation within a sweep
Returns
returns 0 for successful convergence, 1 for failure
Definition at line 893 of file pspg/System.tpp.
References Util::Log::file(), and UTIL_CHECK.
sweep()
template<int D> void Pscf::Pspg::System< D >::sweep
Sweep in parameter space, solving an SCF problem at each point.
This function uses a Sweep object that was initialized in the parameter file to solve the SCF problem at a sequence of points along a line in parameter space. The nature of this sequence is determined by implementation of a subclass of Sweep and the parameters passed to the sweep object in the parameter file.
An Exception is thrown if sweep() is called when no Sweep has been created.
Definition at line 924 of file pspg/System.tpp.
References Util::Log::file(), and UTIL_CHECK.
computeFreeEnergy()
template<int D> void Pscf::Pspg::System< D >::computeFreeEnergy
Compute free energy density and pressure for current fields.
This function should be called after a successful call of iterator().solve(). Resulting values are returned by the freeEnergy() and pressure() accessor functions.
Definition at line 576 of file pspg/System.tpp.
References Pscf::PolymerTmpl< Block >::length(), Pscf::Species::mu(), Pscf::Pspg::ThreadGrid::nBlocks(), Pscf::Pspg::ThreadGrid::nThreads(), Pscf::Species::phi(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), Pscf::SolventDescriptor::size(), and UTIL_CHECK.
fHelmholtz()
template<int D> double Pscf::Pspg::System< D >::fHelmholtz inline
Get precomputed Helmoltz free energy per monomer / kT.
The value retrieved by this function is computed by the computeFreeEnergy() function.
Definition at line 1088 of file pspg/System.h.
pressure()
template<int D> double Pscf::Pspg::System< D >::pressure inline
Get precomputed pressure x monomer volume kT.
The value retrieved by this function is computed by the computeFreeEnergy() function.
Definition at line 1093 of file pspg/System.h.
writeWBasis()
template<int D> void Pscf::Pspg::System< D >::writeWBasis (const std::string & filename)
Write chemical potential fields in symmetry adapted basis format.
Parameters
filename name of output file
Definition at line 941 of file pspg/System.tpp.
References UTIL_CHECK.
writeWRGrid()
template<int D> void Pscf::Pspg::System< D >::writeWRGrid (const std::string & filename) const
Write chemical potential fields in real space grid (r-grid) format.
Parameters
filename name of output file
Definition at line 952 of file pspg/System.tpp.
References UTIL_CHECK.
writeCBasis()
template<int D> void Pscf::Pspg::System< D >::writeCBasis (const std::string & filename)
Write concentrations in symmetry-adapted basis format.
Parameters
filename name of output file
Definition at line 962 of file pspg/System.tpp.
References UTIL_CHECK.
writeCRGrid()
template<int D> void Pscf::Pspg::System< D >::writeCRGrid (const std::string & filename) const
Write concentration fields in real space grid (r-grid) format.
Parameters
filename name of output file
Definition at line 973 of file pspg/System.tpp.
References UTIL_CHECK.
writeBlockCRGrid()
template<int D> void Pscf::Pspg::System< D >::writeBlockCRGrid (const std::string & filename) const
Write c-fields for all blocks and solvents in r-grid format.
Writes concentrations for all blocks of all polymers and all solvent species in r-grid format. Columns associated with blocks appear ordered by polymer id and then by block id, followed by solvent species ordered by solvent id.
Parameters
filename name of output file
Definition at line 984 of file pspg/System.tpp.
References Util::DArray< Data >::allocate(), Util::Array< Data >::capacity(), and UTIL_CHECK.
writePropagatorTail()
template<int D> void Pscf::Pspg::System< D >::writePropagatorTail (const std::string & filename, int polymerID, int blockID)
Write tail (last slice) of a propagator in r-grid format.
Parameters
filename name of output file
polymerID integer index of polymer species
blockID integer index of block within polymer
Definition at line 1005 of file pspg/System.tpp.
References Pscf::Pspg::RDField< D >::allocate(), and Pscf::Pspg::DField< Data >::cDField().
writeQSlice()
template<int D> void Pscf::Pspg::System< D >::writeQSlice (std::string const & filename, int polymerId, int blockId, int directionId, int segmentId) const
Write slice of a propagator at fixed s in r-grid format.
Parameters
filename name of output file
polymerId integer id of the polymer
blockId integer id of the block within the polymer
directionId integer id of the direction (0 or 1)
segmentId integer integration step index
Definition at line 1025 of file pspg/System.tpp.
References Pscf::Pspg::RDField< D >::allocate(), Pscf::Pspg::DField< Data >::cDField(), Pscf::PolymerTmpl< Block >::nBlock(), Pscf::PolymerTmpl< Block >::propagator(), Pscf::Pspg::Propagator< D >::q(), and UTIL_CHECK.
writeQTail()
template<int D> void Pscf::Pspg::System< D >::writeQTail (std::string const & filename, int polymerId, int blockId, int directionId) const
Write the final slice of a propagator in r-grid format.
Parameters
filename name of output file
polymerId integer id of the polymer
blockId integer id of the block within the polymer
directionId integer id of the direction (0 or 1)
Definition at line 1050 of file pspg/System.tpp.
References Pscf::Pspg::RDField< D >::allocate(), Pscf::Pspg::DField< Data >::cDField(), Pscf::PolymerTmpl< Block >::nBlock(), Pscf::PolymerTmpl< Block >::propagator(), Pscf::Pspg::Propagator< D >::tail(), and UTIL_CHECK.
writeQ()
template<int D> void Pscf::Pspg::System< D >::writeQ (std::string const & filename, int polymerId, int blockId, int directionId) const
Write one propagator for one block, in r-grid format.
Parameters
filename name of output file
polymerId integer id of the polymer
blockId integer id of the block within the polymer
directionId integer id of the direction (0 or 1)
Definition at line 1074 of file pspg/System.tpp.
References Pscf::Pspg::RDField< D >::allocate(), Pscf::Pspg::DField< Data >::cDField(), Pscf::PolymerTmpl< Block >::nBlock(), Pscf::Pspg::Propagator< D >::ns(), Pscf::PolymerTmpl< Block >::propagator(), Pscf::Pspg::Propagator< D >::q(), and UTIL_CHECK.
writeQAll()
template<int D> void Pscf::Pspg::System< D >::writeQAll (std::string const & basename)
Write all propagators of all blocks, each to a separate file.
Write all propagators for both directions for all blocks of all polymers, with each propagator in a separate file. The function writeQ is called internally for each propagator, and is passed an automatically generated file name. The file name for each propagator is given by a string of the form (basename)_(ip)_(ib)_(id), where (basename) denotes the value of the std::string function parameter basename, and where (ip), (ib), and (id) denote the string representations of a polymer indiex ip, a block index ib, and direction index id, with id = 0 or 1. For example, if basename == "out/q", then the file name of the propagator for direction 1 of block 2 of polymer 0 would be "out/q_0_2_1".
Parameters
basename common prefix for output file names
Definition at line 1117 of file pspg/System.tpp.
References Util::toString().
writeParamNoSweep()
template<int D> void Pscf::Pspg::System< D >::writeParamNoSweep (std::ostream & out) const
Write parameter file to an ostream, omitting the sweep block.
Definition at line 271 of file pspg/System.tpp.
writeThermo()
template<int D> void Pscf::Pspg::System< D >::writeThermo (std::ostream & out)
Write thermodynamic properties to a file.
This function outputs Helmholtz free energy per monomer, pressure (in units of kT per monomer volume), and the volume fraction and chemical potential of each species.
Parameters
out output stream
Definition at line 686 of file pspg/System.tpp.
writeStars()
template<int D> void Pscf::Pspg::System< D >::writeStars (const std::string & outFileName) const
Output information about stars and symmetrized basis functions.
This function opens a file with the specified filename and then calls Basis::outputStars.
Parameters
outFileName name of output file
Definition at line 1146 of file pspg/System.tpp.
writeWaves()
template<int D> void Pscf::Pspg::System< D >::writeWaves (const std::string & outFileName) const
Output information about waves.
This function opens a file with the specified filename and then calls Basis::outputWaves.
Parameters
outFileName name of output file for wave data
Definition at line 1159 of file pspg/System.tpp.
basisToRGrid()
template<int D> void Pscf::Pspg::System< D >::basisToRGrid (const std::string & inFileName, const std::string & outFileName)
Convert a field from symmetry-adapted basis to r-grid format.
This function uses the arrays that stored monomer concentration fields for temporary storage, and thus corrupts any previously stored values. As a result, flag hasCFields is false on output.
Parameters
inFileName name of input file
outFileName name of output file
Definition at line 1174 of file pspg/System.tpp.
rGridToBasis()
template<int D> void Pscf::Pspg::System< D >::rGridToBasis (const std::string & inFileName, const std::string & outFileName)
Convert a field from real-space grid to symmetrized basis format.
This function uses the arrays that stored monomer concentration fields for temporary storage, and thus corrupts any previously stored values. As a result, flag hasCFields is false on return.
Parameters
inFileName name of input file
outFileName name of output file
Definition at line 1187 of file pspg/System.tpp.
kGridToRGrid()
template<int D> void Pscf::Pspg::System< D >::kGridToRGrid (const std::string & inFileName, const std::string & outFileName) const
Convert fields from Fourier (k-grid) to real-space (r-grid) format.
Parameters
inFileName name of input file
outFileName name of output file
Definition at line 1200 of file pspg/System.tpp.
rGridToKGrid()
template<int D> void Pscf::Pspg::System< D >::rGridToKGrid (const std::string & inFileName, const std::string & outFileName) const
Convert fields from real-space (r-grid) to Fourier (k-grid) format.
Parameters
inFileName name of input file
outFileName name of output file
Definition at line 1216 of file pspg/System.tpp.
kGridToBasis()
template<int D> void Pscf::Pspg::System< D >::kGridToBasis (const std::string & inFileName, const std::string & outFileName) const
Convert fields from Fourier (k-grid) to symmetrized basis format.
Parameters
inFileName name of input file
outFileName name of output file
Definition at line 1233 of file pspg/System.tpp.
basisToKGrid()
template<int D> void Pscf::Pspg::System< D >::basisToKGrid (const std::string & inFileName, const std::string & outFileName) const
Convert fields from symmetrized basis to Fourier (k-grid) format.
Parameters
inFileName name of input file (basis format)
outFileName name of output file (k-grid format)
Definition at line 1246 of file pspg/System.tpp.
guessWfromC()
template<int D> void Pscf::Pspg::System< D >::guessWfromC (const std::string & inFileName, const std::string & outFileName)
Construct trial w-fields from c-fields.
This function reads concentration fields in symmetrized basis format and constructs an initial guess for corresponding chemical potential fields by setting the Lagrange multiplier field xi to zero. The resulting guess is stored in the System wFields arrays in basis and r-grid formats and is also output to a file in basis format.
Upon return, hasWFields and hasSymmetricFields are set true and hasCFields is set false.
Parameters
inFileName name of input c-field file (in, basis format)
outFileName name of output w-field file (out, basis format)
Definition at line 1281 of file pspg/System.tpp.
References Pscf::Pspg::ThreadGrid::nBlocks(), Pscf::Pspg::ThreadGrid::nThreads(), and Pscf::Pspg::ThreadGrid::setThreadsLogical().
wFieldsBasis()
template<int D> DArray< DArray< double > > const & Pscf::Pspg::System< D >::wFieldsBasis inline
Get array of chemical potential fields, in a basis.
This function returns an array in which each element is an array containing the coefficients of the chemical potential field (w field) in a symmetry-adapted basis for one monomer type. The array capacity is the number of monomer types.
Definition at line 1039 of file pspg/System.h.
wFieldBasis()
template<int D> DArray< double > const & Pscf::Pspg::System< D >::wFieldBasis (int monomerId) const inline
Get chemical potential field for one monomer type, in a basis.
This function returns an array containing coefficients of the chemical potential field (w field) in a symmetry-adapted basis for a specified monomer type.
Parameters
monomerId integer monomer type index
Definition at line 1045 of file pspg/System.h.
wFieldsRGrid()
template<int D> DArray< RDField< D > > const & Pscf::Pspg::System< D >::wFieldsRGrid inline
Get array of all w fields, in r-space format, by const ref.
This function returns an array in which each element is a WField object containing values of the chemical potential field (w field) on a regular grid for one monomer type. The array capacity is the number of monomer types.
Definition at line 1051 of file pspg/System.h.
wFieldRGrid()
template<int D> RDField< D > const & Pscf::Pspg::System< D >::wFieldRGrid (int monomerId) const inline
Get w field for one monomer type in r-space format by const ref.
Parameters
monomerId integer monomer type index
Definition at line 1058 of file pspg/System.h.
cFieldsBasis()
template<int D> DArray< DArray< double > > const & Pscf::Pspg::System< D >::cFieldsBasis inline
Get an array of all monomer concentration fields, in a basis.
This function returns an array in which each element is an array containing the coefficients of the monomer concentration field (cfield) for one monomer type in a symmetry-adapted basis. The array capacity is equal to the number of monomer types.
Definition at line 1064 of file pspg/System.h.
cFieldBasis()
template<int D> DArray< double > const & Pscf::Pspg::System< D >::cFieldBasis (int monomerId) const inline
Get the concentration field for one monomer type, in a basis.
This function returns an array containing the coefficients of the monomer concentration / volume fraction field (c field) for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 1070 of file pspg/System.h.
cFieldsRGrid()
template<int D> DArray< RDField< D > > const & Pscf::Pspg::System< D >::cFieldsRGrid inline
Get array of all concentration fields (c fields), on a grid.
This function returns an array in which each element is the monomer concentration field for one monomer type on a regular grid (an r-grid).
Definition at line 1076 of file pspg/System.h.
cFieldRGrid()
template<int D> RDField< D > const & Pscf::Pspg::System< D >::cFieldRGrid (int monomerId) const inline
Get the concentration (c field) for one monomer type, on a grid.
Parameters
monomerId integer monomer type index
Definition at line 1083 of file pspg/System.h.
mixture()
template<int D> Mixture< D > & Pscf::Pspg::System< D >::mixture inline
Get Mixture by reference.
Definition at line 960 of file pspg/System.h.
interaction() [1/2]
template<int D> Interaction & Pscf::Pspg::System< D >::interaction inline
Get interaction (i.e., excess free energy model) by reference.
Definition at line 965 of file pspg/System.h.
References UTIL_ASSERT.
interaction() [2/2]
template<int D> Interaction const & Pscf::Pspg::System< D >::interaction inline
Get interaction (i.e., excess free energy model) by const ref.
Definition at line 973 of file pspg/System.h.
References UTIL_ASSERT.
domain()
template<int D> Domain< D > const & Pscf::Pspg::System< D >::domain inline
Get Domain by const reference.
Definition at line 980 of file pspg/System.h.
unitCell()
template<int D> UnitCell< D > const & Pscf::Pspg::System< D >::unitCell inline
Get crystal UnitCell by const reference.
Definition at line 984 of file pspg/System.h.
mesh()
template<int D> Mesh< D > const & Pscf::Pspg::System< D >::mesh inline
Get spatial discretization Mesh by const reference.
Definition at line 989 of file pspg/System.h.
basis()
template<int D> Basis< D > const & Pscf::Pspg::System< D >::basis inline
Get the Basis by reference.
Definition at line 994 of file pspg/System.h.
wavelist()
template<int D> WaveList< D > & Pscf::Pspg::System< D >::wavelist inline
Get container for wavevector data.
Definition at line 1033 of file pspg/System.h.
iterator()
template<int D> Iterator< D > & Pscf::Pspg::System< D >::iterator inline
Get the iterator by reference.
Definition at line 1014 of file pspg/System.h.
References UTIL_ASSERT.
fieldIo()
template<int D> FieldIo< D > const & Pscf::Pspg::System< D >::fieldIo inline
Get the FieldIo by const reference.
Definition at line 1004 of file pspg/System.h.
fft()
template<int D> FFT< D > const & Pscf::Pspg::System< D >::fft inline
Get the FFT object by reference.
Definition at line 999 of file pspg/System.h.
homogeneous()
template<int D> Homogeneous::Mixture & Pscf::Pspg::System< D >::homogeneous inline
Get homogeneous mixture (for reference calculations).
Definition at line 1028 of file pspg/System.h.
fileMaster()
template<int D> FileMaster & Pscf::Pspg::System< D >::fileMaster inline
Get FileMaster by reference.
Definition at line 1022 of file pspg/System.h.
groupName()
template<int D> std::string Pscf::Pspg::System< D >::groupName inline
Get the group name string.
Definition at line 1009 of file pspg/System.h.
hasWFields()
template<int D> bool Pscf::Pspg::System< D >::hasWFields inline
Have monomer chemical potential fields (w fields) been set?
A true value is returned if and only if values have been set on a real space grid. The READ_W_BASIS command must immediately convert from a basis to a grid to satisfy this requirement.
Definition at line 1098 of file pspg/System.h.
hasCFields()
template<int D> bool Pscf::Pspg::System< D >::hasCFields inline
Have monomer concentration fields (c fields) been computed?
Returns true if and only if monomer concentration fields have been computed by solving the modified diffusion equation for the current w fields.
Definition at line 1103 of file pspg/System.h.
hasSymmetricFields()
template<int D> bool Pscf::Pspg::System< D >::hasSymmetricFields inline
Are w-fields symmetric under all elements of the space group?
Returns true if the system contains valid fields in basis format. This will be so if w fields were input in basis format, or have been explicitly symmetrized by calling symmetrizeWFields().
Definition at line 1108 of file pspg/System.h.
hasSweep()
template<int D> bool Pscf::Pspg::System< D >::hasSweep inline
Does this system have an associated Sweep object?
Definition at line 1113 of file pspg/System.h.
The documentation for this class was generated from the following files:
AmIteratorBasis.h
pspg/System.h
pspg/System.tpp