PSCF: Pscf::R1d::SweepParameter Class Reference
Pscf::R1d::SweepParameter Class Reference
Pscf namespace » Pscf::R1d - Real 1D fields » Sweep
Class for storing data about an individual sweep parameter.
#include <SweepParameter.h>
Public Member Functions
SweepParameter ()
Default constructor.
SweepParameter (System &system)
Constructor that stores a pointer to parent system.
void setSystem (System &system)
Set the system associated with this object.
void setParameterTypesArray (GArray< ParameterType > &array)
Set the pointer to the array of specialized sweep parameter types.
ParameterType & parameterType () const
Get the ParameterType object for a specialized sweep parameter.
int parameterTypeId () const
Get the array index for the specialized sweep parameter.
bool isSpecialized () const
Is this SweepParameter a specialized parameter type?
void getInitial ()
Store the pre-sweep value of the corresponding parameter.
void update (double newVal)
Update the corresponding parameter value in the system.
std::string type () const
Return a string representation of the parameter type.
void writeParamType (std::ostream &out) const
Write the parameter type to an output stream.
int id (int i) const
Get a id for a sub-object or element to which this is applied.
double current ()
Return the current system parameter value.
double initial () const
Return the initial system parameter value.
double change () const
Return the total change planned for this parameter during sweep.
template<class Archive >
void serialize (Archive ar, const unsigned int version)
Serialize to or from an archive.
Friends
std::istream & operator>> (std::istream &in, SweepParameter &param)
Inserter for reading a SweepParameter from an istream.
std::ostream & operator<< (std::ostream &out, SweepParameter const &param)
Extractor for writing a SweepParameter to ostream.
Detailed Description
Class for storing data about an individual sweep parameter.
This class stores the information required to sweep a single parameter value of any of several types. The type of parameter is indicated in the public interface and parameter file format by a string identifier with any of several allowed values. Each parameter is also identified by one or two associated index values, denoted here by id(0) and id(1), that specify the index or indices for a subobject or array element with which the parameter is associated applied. Allowed string representations and meanings of parameter types are given below, along with the meaning of any associated index value or pair of values. To indicate the meaning of index values, we use mId to denote a monomer type index, pId to denote a polymer species index, bId to denote the index of a block within a polymer, sId to denote a solvent species index, and lId to denote a lattice parameter index:
| Type        | Meaning                     | id(0) | id(1)
| ----------- | --------------------------- | ----- | -----
| kuhn        | monomer segment length      | mId   |
| chi         | Flory-Huggins parameter     | mId   | mId
| block       | block length                | pId   | bId
| solvent     | solvent size                | sId   |
| phi_polymer | polymer volume fraction     | pId   |
| mu_polymer  | polymer chemical potential  | pId   |
| phi_solvent | solvent volume fraction     | sId   |
| mu_solvent  | solvent chemical potential  | sId   |
The two indices for a Flory-Huggins chi parameter refer to indices in the chi matrix maintained by Interaction. Changes to element chi(i, j) automatically also update chi(j, i) for i !\ j, thus maintaining the symmetry of the matrix.
Each SweepParameter also has a "change" value that gives the intended difference between the final and initial value of the parameter over the course of a sweep, corresponding to a change sweep parameter s over the range [0,1]. The initial value of each parameter is obtained from a query of the state of the parent system at the beginning of a sweep, and thus does not need to be supplied as part of the text format for a SweepParameter.
A SweepParameter<D> object is initialized by reading the parameter type, index or index and change value from a parameter file as a a single line. An overloaded >> operator is defined that allows a SweepParameter<D> object named "parameter" to be read from an istream named "in" using the syntax "in >> parameter".
The text format for a parameter of a type that requires a single index id(0) is:
type id(0) change
where type indicates a type string, id(0) is an integer index value, and change is the a floating point value for the change in parameter value. The corresponding format for a parameter that requires two indices (e.g., block or chi) is instead: "type id(0) id(1) change".
All parameter types in the table above are hard-coded into this class, but this class has been written so that certain classes can also add "specialized" parameters to the list SweepTmpl::parameterTypes_ using the method SweepTmpl::addParameterTypes. This list of specialized parameters is then consulted if the user-specified parameter type is not found in the list of hard-coded parameter names. In order to add parameters to SweepTmpl::parameterTypes_, a class must be a subclass of ParameterModifier.
Currently, the only classes that can add parameters to parameterTypes_ are Iterators. The Iterator for a given calculation is determined via a Factory, so the type of Iterator is not known until run time. Therefore, Iterators can add sweepable parameters to parameterTypes_ as necessary at run time, depending on the type of Iterator used in that calculation. As a design principle, an object that is created by a Factory and used for SCFT calculations should also be a subclass of ParameterModifier so that it can add sweepable parameters at run time.
Definition at line 104 of file r1d/sweep/SweepParameter.h.
Constructor & Destructor Documentation
SweepParameter() [1/2]
Pscf::R1d::SweepParameter::SweepParameter ()
Default constructor.
Definition at line 29 of file SweepParameter.cpp.
SweepParameter() [2/2]
Pscf::R1d::SweepParameter::SweepParameter (System & system)
Constructor that stores a pointer to parent system.
Parameters
system parent system
Definition at line 43 of file SweepParameter.cpp.
Member Function Documentation
setSystem()
void Pscf::R1d::SweepParameter::setSystem (System & system) inline
Set the system associated with this object.
Invoke this function on objects created with the default constructor to create an association with a parent system.
Parameters
system parent system
Definition at line 129 of file r1d/sweep/SweepParameter.h.
setParameterTypesArray()
void Pscf::R1d::SweepParameter::setParameterTypesArray (GArray< ParameterType > & array) inline
Set the pointer to the array of specialized sweep parameter types.
Parameters
array array of specialized parameter types
Definition at line 137 of file r1d/sweep/SweepParameter.h.
parameterType()
ParameterType & Pscf::R1d::SweepParameter::parameterType () const
Get the ParameterType object for a specialized sweep parameter.
An error will result if this SweepParameter is not specialized and this function is called.
Definition at line 126 of file SweepParameter.cpp.
References isSpecialized(), and UTIL_CHECK.
Referenced by type().
parameterTypeId()
int Pscf::R1d::SweepParameter::parameterTypeId () const inline
Get the array index for the specialized sweep parameter.
Definition at line 151 of file r1d/sweep/SweepParameter.h.
isSpecialized()
bool Pscf::R1d::SweepParameter::isSpecialized () const inline
Is this SweepParameter a specialized parameter type?
Definition at line 157 of file r1d/sweep/SweepParameter.h.
Referenced by parameterType().
getInitial()
void Pscf::R1d::SweepParameter::getInitial ()
Store the pre-sweep value of the corresponding parameter.
Definition at line 135 of file SweepParameter.cpp.
update()
void Pscf::R1d::SweepParameter::update (double newVal)
Update the corresponding parameter value in the system.
Parameters
newVal new value for the parameter (input)
Definition at line 143 of file SweepParameter.cpp.
type()
std::string Pscf::R1d::SweepParameter::type () const
Return a string representation of the parameter type.
Definition at line 151 of file SweepParameter.cpp.
References parameterType(), and UTIL_THROW.
Referenced by pscfpp.field.Field::__init__(), pscfpp.field.Field::__str__(), pscfpp.field.Field::read(), and writeParamType().
writeParamType()
void Pscf::R1d::SweepParameter::writeParamType (std::ostream & out) const
Write the parameter type to an output stream.
Parameters
out output file stream
Definition at line 118 of file SweepParameter.cpp.
References type().
id()
int Pscf::R1d::SweepParameter::id (int i) const inline
Get a id for a sub-object or element to which this is applied.
This function returns a value from the id_ array. Elements of this array store indices associating the parameter with a particular subobject or value. Different types of parameters require either 1 or 2 such identifiers. The number of required identifiers is denoted by private variable nId_.
Parameters
i array index to access
Definition at line 195 of file r1d/sweep/SweepParameter.h.
current()
double Pscf::R1d::SweepParameter::current () inline
Return the current system parameter value.
Definition at line 201 of file r1d/sweep/SweepParameter.h.
initial()
double Pscf::R1d::SweepParameter::initial () const inline
Return the initial system parameter value.
Definition at line 207 of file r1d/sweep/SweepParameter.h.
change()
double Pscf::R1d::SweepParameter::change () const inline
Return the total change planned for this parameter during sweep.
Definition at line 213 of file r1d/sweep/SweepParameter.h.
serialize()
template<class Archive > void Pscf::R1d::SweepParameter::serialize (Archive ar, const unsigned int version)
Serialize to or from an archive.
Parameters
ar Archive object
version archive format version index
Definition at line 287 of file r1d/sweep/SweepParameter.h.
References Util::serializeEnum().
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & in, SweepParameter & param) friend
Inserter for reading a SweepParameter from an istream.
Parameters
in input stream
param SweepParameter object to read
Definition at line 238 of file SweepParameter.cpp.
operator<<
std::ostream & operator<< (std::ostream & out, SweepParameter const & param) friend
Extractor for writing a SweepParameter to ostream.
Parameters
out output stream
param SweepParameter object to write
Definition at line 259 of file SweepParameter.cpp.
The documentation for this class was generated from the following files:
r1d/sweep/SweepParameter.h
SweepParameter.cpp