PSCF: Pscf::Pspg::RFieldComparison< D > Class Template Reference
Pscf::Pspg::RFieldComparison< D > Class Template Reference
Pscf namespace » Periodic Pseudo-Spectral (GPU) » Fields
Comparator for fields in real-space (r-grid) format.
#include <RFieldComparison.h>
Public Member Functions
RFieldComparison ()
Constructor.
double compare (RDField< D > const &a, RDField< D > const &b)
Comparator for individual fields.
double compare (DArray< RDField< D > > const &a, DArray< RDField< D > > const &b)
Comparator for array of fields.
double maxDiff () const
Get precomputed maximum element-by-element difference.
double rmsDiff () const
Get precomputed rms difference.
Detailed Description
template<int D>
class Pscf::Pspg::RFieldComparison< D >
Comparator for fields in real-space (r-grid) format.
Definition at line 25 of file pspg/field/RFieldComparison.h.
Constructor & Destructor Documentation
RFieldComparison()
template<int D> Pscf::Pspg::RFieldComparison< D >::RFieldComparison
Constructor.
Definition at line 18 of file RFieldComparison.tpp.
Member Function Documentation
compare() [1/2]
template<int D> double Pscf::Pspg::RFieldComparison< D >::compare (RDField< D > const & a, RDField< D > const & b)
Comparator for individual fields.
Parameters
a first array of fields
b second array of fields
Definition at line 23 of file RFieldComparison.tpp.
References Util::DArray< Data >::allocate(), Pscf::Pspg::DField< Data >::capacity(), and Pscf::Pspg::DField< Data >::cDField().
compare() [2/2]
template<int D> double Pscf::Pspg::RFieldComparison< D >::compare (DArray< RDField< D > > const & a, DArray< RDField< D > > const & b)
Comparator for array of fields.
Parameters
a first array of fields
b second array of fields
Definition at line 49 of file RFieldComparison.tpp.
References Util::DArray< Data >::allocate().
maxDiff()
template<int D> double Pscf::Pspg::RFieldComparison< D >::maxDiff () const inline
Get precomputed maximum element-by-element difference.
Definition at line 54 of file pspg/field/RFieldComparison.h.
rmsDiff()
template<int D> double Pscf::Pspg::RFieldComparison< D >::rmsDiff () const inline
Get precomputed rms difference.
Definition at line 60 of file pspg/field/RFieldComparison.h.
The documentation for this class was generated from the following files:
pspg/field/RFieldComparison.h
RFieldComparison.tpp