PSCF: Pscf::SweepTmpl< State > Class Template Reference
Pscf::SweepTmpl< State > Class Template Reference abstract
Pscf namespace » Pscf Common » Sweep Template
Solve a sequence of problems along a path through parameter space.
#include <SweepTmpl.h>
Public Member Functions
~SweepTmpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read ns and baseFileName parameters.
virtual void sweep ()
Iterate to solution.
void addParameterType (std::string name, int nId, ParameterModifier &modifier)
Declare a specialized parameter type.
void addParameterType (ParameterType paramType)
Declare a single specialized sweep parameter type.
void addParameterTypes (GArray< ParameterType > paramTypes)
Declare an array of specialized sweep parameter types.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
SweepTmpl (int historyCapacity)
Constructor (protected).
State & state (int i)
Get reference to a stored state, with i=0 being most recent.
double s (int i) const
Get the value of s for a stored solution, with i = 0 most recent.
double c (int i) const
Get a coefficient of a previous state in a continuation.
int historySize () const
Get the current number of stored previous states.
int historyCapacity () const
Get the maximum number of stored previous states.
int nAccept () const
Get the number of converged solutions accepted thus far.
void initialize ()
Initialize variables that track history of solutions.
virtual void checkAllocation (State &state)=0
Check allocation of one state, allocate if necessary.
virtual void setup ()=0
Setup operation at the beginning of a sweep.
virtual void setParameters (double sNew)=0
Set non-adjustable system parameters to new values.
virtual void extrapolate (double sNew)=0
Create initial guess for the next state by extrapolation.
void setCoefficients (double sNew)
Compute coefficients of previous states for continuation.
virtual int solve (bool isContinuation)=0
Call current iterator to solve SCFT problem.
virtual void reset ()=0
Reset system to previous solution after iterature failure.
virtual void getSolution ()=0
Update state(0) and output data after successful solution.
virtual void cleanup ()
Clean up operation at the end of a sweep.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
int ns_
Number of steps.
std::string baseFileName_
Base name for output files.
GArray< ParameterType > parameterTypes_
Array of specialized parameter types.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<typename State>
class Pscf::SweepTmpl< State >
Solve a sequence of problems along a path through parameter space.
Definition at line 27 of file SweepTmpl.h.
Constructor & Destructor Documentation
~SweepTmpl()
template<class State> Pscf::SweepTmpl< State >::~SweepTmpl ()
Destructor.
Definition at line 35 of file SweepTmpl.tpp.
SweepTmpl()
template<class State> Pscf::SweepTmpl< State >::SweepTmpl (int historyCapacity) protected
Constructor (protected).
The value of historyCapacity depends on the order of continuation, e.g., 2 for 1st order or linear continuation or 3 for 2nd order or quadratic contination. The value passed to this constructor is a default value that may overridden by a optional parameter in the parameter file format implemented in readParam.
Parameters
historyCapacity default maximum number of stored states
Definition at line 22 of file SweepTmpl.tpp.
References baseFileName_, historyCapacity(), ns_, and Util::ParamComposite::setClassName().
Member Function Documentation
readParameters()
template<class State> void Pscf::SweepTmpl< State >::readParameters (std::istream & in) virtual
Read ns and baseFileName parameters.
Parameters
in input stream
Reimplemented from Util::ParamComposite.
Reimplemented in Pscf::R1d::LinearSweep, Pscf::R1d::Sweep, Pscf::Rpc::LinearSweep< D >, Pscf::Rpc::Sweep< D >, Pscf::Rpg::LinearSweep< D >, and Pscf::Rpg::Sweep< D >.
Definition at line 42 of file SweepTmpl.tpp.
Referenced by Pscf::R1d::Sweep::readParameters().
sweep()
template<class State> void Pscf::SweepTmpl< State >::sweep () virtual
Iterate to solution.
Definition at line 62 of file SweepTmpl.tpp.
addParameterType() [1/2]
template<class State> void Pscf::SweepTmpl< State >::addParameterType (std::string name, int nId, ParameterModifier & modifier)
Declare a specialized parameter type.
This function creates a new ParameterType object using the required input parameters and adds this object to the array of declared specialized parameter types.
Parameters
name parameter string identifier
nId number of associated integer indices
modifier object that can set and get the parameter
Definition at line 150 of file SweepTmpl.tpp.
References parameterTypes_, and UTIL_CHECK.
addParameterType() [2/2]
template<class State> void Pscf::SweepTmpl< State >::addParameterType (ParameterType paramType)
Declare a single specialized sweep parameter type.
This function adds a new ParameterType object to the array of declared specialized parameter types.
Parameters
paramType parameterType object defining the sweep parameter
Definition at line 168 of file SweepTmpl.tpp.
References parameterTypes_, and UTIL_CHECK.
addParameterTypes()
template<class State> void Pscf::SweepTmpl< State >::addParameterTypes (GArray< ParameterType > paramTypes)
Declare an array of specialized sweep parameter types.
This function adds an array of new ParameterType objects to the array of declared specialized parameter types.
Parameters
paramTypes array of parameterType objects
Definition at line 181 of file SweepTmpl.tpp.
References parameterTypes_, Util::GArray< Data >::size(), and UTIL_CHECK.
state()
template<typename State> State & Pscf::SweepTmpl< State >::state (int i) inline protected
Get reference to a stored state, with i=0 being most recent.
Call state(i) to return the ith from most recent previous state.
Parameters
i history index (i=0 is most recent)
Definition at line 127 of file SweepTmpl.h.
References UTIL_CHECK.
Referenced by checkAllocation().
s()
template<typename State> double Pscf::SweepTmpl< State >::s (int i) const inline protected
Get the value of s for a stored solution, with i = 0 most recent.
This function returns the value of the contour variable s for a stored state. Call s(i) to get the value of s for the ith most recent state.
Parameters
i history index (i = 0 is most the recent converged state)
Definition at line 142 of file SweepTmpl.h.
References UTIL_CHECK.
Referenced by getSolution(), and setCoefficients().
c()
template<typename State> double Pscf::SweepTmpl< State >::c (int i) const inline protected
Get a coefficient of a previous state in a continuation.
An extrapolated trial value for each field or other variables that describes a state is constructed as a linear superposition of corresponding values in previous states. Coefficient c(i) is the coefficient of state state(i) in this linear superposition, where i = 0 denotes the most recent accepted solution and increasing index i corresponds to increasingly far in the past. Valid values of i are in the range 0 <= i < historySize().
The function setCoefficients(double sNew) method computes and stores values coefficients c(0), ..., c(historySize-1) from values of sNew (the contour variable of the new state) and previous values of s. These coefficient values can then be retrieved by this function.
Parameters
i history index (i=0 is most recent)
Definition at line 167 of file SweepTmpl.h.
References UTIL_CHECK.
historySize()
template<typename State> int Pscf::SweepTmpl< State >::historySize () const inline protected
Get the current number of stored previous states.
Definition at line 177 of file SweepTmpl.h.
historyCapacity()
template<typename State> int Pscf::SweepTmpl< State >::historyCapacity () const inline protected
Get the maximum number of stored previous states.
The value of historyCapacity is a constant that is one greater than the maximum order of continuation (e.g., 3 for 2nd order continuation). The value is set by passing it as an argument to the constructor, and is constant after construction.
Definition at line 188 of file SweepTmpl.h.
Referenced by SweepTmpl().
nAccept()
template<typename State> int Pscf::SweepTmpl< State >::nAccept () const inline protected
Get the number of converged solutions accepted thus far.
This value is reset to zero by the initialize function, which must be called by the setup function, and is incremented by one by the accept function.
Definition at line 198 of file SweepTmpl.h.
initialize()
template<class State> void Pscf::SweepTmpl< State >::initialize () protected
Initialize variables that track history of solutions.
This must be called within implementation of the setup function.
Definition at line 199 of file SweepTmpl.tpp.
References UTIL_CHECK.
checkAllocation()
template<typename State> virtual void Pscf::SweepTmpl< State >::checkAllocation (State & state) protected pure virtual
Check allocation of one state, allocate if necessary.
This virtual function is called by SweepTmpl::initialize() during setup before a sweep to check allocation state and/or allocate memory for fields in all stored State objects.
Parameters
state an object that represents a state of the system
Implemented in Pscf::R1d::Sweep.
References state().
setup()
template<typename State> virtual void Pscf::SweepTmpl< State >::setup () protected pure virtual
Setup operation at the beginning of a sweep.
The implementations of this function must call initialize().
Implemented in Pscf::R1d::LinearSweep, Pscf::R1d::Sweep, Pscf::Rpc::LinearSweep< D >, Pscf::Rpc::Sweep< D >, Pscf::Rpg::LinearSweep< D >, and Pscf::Rpg::Sweep< D >.
setParameters()
template<typename State> virtual void Pscf::SweepTmpl< State >::setParameters (double sNew) protected pure virtual
Set non-adjustable system parameters to new values.
This function should set set values for variables that are treated as input parameters by the SCFT solver, such as block polymer block lengths, chi parameters, species volume fractions or chemical potentials, etc. The function must modify the values stored in the parent system to values appropriate to a new value of a contour variable value sNew that is passed as a parameter. The functional dependence of parameters on the contour variable over a range [0,1] is defined by the subclass implementation.
Parameters
sNew new value of path length coordinate, in range [0,1]
Implemented in Pscf::R1d::LinearSweep, Pscf::R1d::Sweep, Pscf::Rpc::LinearSweep< D >, Pscf::Rpc::Sweep< D >, Pscf::Rpg::LinearSweep< D >, and Pscf::Rpg::Sweep< D >.
extrapolate()
template<typename State> virtual void Pscf::SweepTmpl< State >::extrapolate (double sNew) protected pure virtual
Create initial guess for the next state by extrapolation.
This function should set extrapolated values of the variables that are modified by the iterative SCFT solver, i.e., values of fields (coefficients of basis functions or values grid points) and unit cell parameters or domain dimensions for problems involving an adjustable domain. Values should be extrapolated to a new contour variable sNew by constructing a linear combination of corresponding values obtained in previous converged states. After computing the desired extrapolated values, this function must set these values in the parent system.
Extrapolated values of adjustable variables at the new contour variable sNew that is passed as a parameter should be computed for each adjustable variable by constructing a Lagrange polynomial in s that passes through all stored values, and evaluating the resulting polynomial at sNew. This yields an expression for the extrapolated value as a linear combination of stored values with coefficients that depend only the values of sNew and the values of s at previous states. This function should call the setCoefficients function to compute these coefficients.
Parameters
sNew new value of path length coordinate.
Implemented in Pscf::R1d::Sweep, Pscf::Rpc::Sweep< D >, and Pscf::Rpg::Sweep< D >.
setCoefficients()
template<class State> void Pscf::SweepTmpl< State >::setCoefficients (double sNew) protected
Compute coefficients of previous states for continuation.
This function must be called by the implementation of extrapolate.
Parameters
sNew new value of path length coordinate.
Definition at line 252 of file SweepTmpl.tpp.
References s(), and UTIL_CHECK.
solve()
template<typename State> virtual int Pscf::SweepTmpl< State >::solve (bool isContinuation) protected pure virtual
Call current iterator to solve SCFT problem.
Return 0 for sucessful solution, 1 on failure to converge.
Implemented in Pscf::R1d::Sweep, Pscf::Rpc::Sweep< D >, and Pscf::Rpg::Sweep< D >.
reset()
template<typename State> virtual void Pscf::SweepTmpl< State >::reset () protected pure virtual
Reset system to previous solution after iterature failure.
The implementation of this function should reset the system state to correspond to that stored in state(0).
Implemented in Pscf::R1d::Sweep, Pscf::Rpc::Sweep< D >, and Pscf::Rpg::Sweep< D >.
getSolution()
template<typename State> virtual void Pscf::SweepTmpl< State >::getSolution () protected pure virtual
Update state(0) and output data after successful solution.
This function is called by accept(). The implementation of this function should copy the current system state into state(0), output any desired information about the current solution, and perform any other operations that should be performed immediately after acceptance of a converged solution.
Implemented in Pscf::R1d::Sweep, Pscf::Rpc::Sweep< D >, and Pscf::Rpg::Sweep< D >.
References s().
cleanup()
template<class State> void Pscf::SweepTmpl< State >::cleanup () protected virtual
Clean up operation at the end of a sweep.
Empty default implementation.
Reimplemented in Pscf::R1d::Sweep, Pscf::Rpc::Sweep< D >, and Pscf::Rpg::Sweep< D >.
Definition at line 287 of file SweepTmpl.tpp.
Member Data Documentation
ns_
template<typename State> int Pscf::SweepTmpl< State >::ns_ protected
Number of steps.
Definition at line 88 of file SweepTmpl.h.
Referenced by SweepTmpl().
baseFileName_
template<typename State> std::string Pscf::SweepTmpl< State >::baseFileName_ protected
Base name for output files.
Definition at line 91 of file SweepTmpl.h.
Referenced by SweepTmpl().
parameterTypes_
template<typename State> GArray<ParameterType> Pscf::SweepTmpl< State >::parameterTypes_ protected
Array of specialized parameter types.
This list allows other objects to add custom sweepable parameters to this object at run time, referred to as "specialized" parameter types. The method addParameterType is used to add to this list.
As a general design principle, any object whose class is determined at run time using a Factory object should use this list to add any sweepable parameters. In order to do this, the object must be a subclass of ParameterModifier.
Definition at line 105 of file SweepTmpl.h.
Referenced by addParameterType(), addParameterType(), and addParameterTypes().
The documentation for this class was generated from the following files:
SweepTmpl.h
SweepTmpl.tpp