PSCF: Pscf::Rpc::BasisFieldState< D > Class Template Reference
Pscf::Rpc::BasisFieldState< D > Class Template Reference
FieldState for fields in symmetry-adapted basis format.
#include <BasisFieldState.h>
Public Member Functions
BasisFieldState ()
Default constructor.
BasisFieldState (System< D > &system)
Constructor, create association with a parent system.
~BasisFieldState ()
Destructor.
void allocate ()
Allocate all fields.
void read (const std::string &filename)
Read state from file.
void write (const std::string &filename)
Write state to file.
void getSystemState ()
Copy the current state of the associated system.
void setSystemState (bool isFlexible)
Set the state of the associated system to this state.
Public Member Functions inherited from Pscf::Rpc::FieldState< D, DArray< double > >
FieldState ()
Default constructor.
~FieldState ()
Destructor.
void setSystem (System< D > &system)
Set association with System, after default construction.
const DArray< FT > & fields () const
Get array of all fields by const reference.
const DArray< double > & field (int monomerId) const
Get a field for a single monomer type by const reference.
const UnitCell< D > & unitCell () const
Get UnitCell (i.e., lattice type and parameters) by const reference.
Additional Inherited Members
Protected Member Functions inherited from Pscf::Rpc::FieldState< D, DArray< double > >
bool hasSystem ()
Has a system been set?
System< D > & system ()
Get associated System by reference.
Detailed Description
template<int D>
class Pscf::Rpc::BasisFieldState< D >
FieldState for fields in symmetry-adapted basis format.
Definition at line 24 of file rpc/scft/sweep/BasisFieldState.h.
Constructor & Destructor Documentation
BasisFieldState() [1/2]
template<int D> Pscf::Rpc::BasisFieldState< D >::BasisFieldState ()
Default constructor.
Definition at line 25 of file rpc/scft/sweep/BasisFieldState.tpp.
References Pscf::Rpc::FieldState< D, DArray< double > >::FieldState().
BasisFieldState() [2/2]
template<int D> Pscf::Rpc::BasisFieldState< D >::BasisFieldState (System< D > & system)
Constructor, create association with a parent system.
Parameters
system associated parent system
Definition at line 33 of file rpc/scft/sweep/BasisFieldState.tpp.
References Pscf::Rpc::FieldState< D, DArray< double > >::FieldState(), and Pscf::Rpc::FieldState< D, DArray< double > >::system().
~BasisFieldState()
template<int D> Pscf::Rpc::BasisFieldState< D >::~BasisFieldState ()
Destructor.
Definition at line 41 of file rpc/scft/sweep/BasisFieldState.tpp.
Member Function Documentation
allocate()
template<int D> void Pscf::Rpc::BasisFieldState< D >::allocate ()
Allocate all fields.
Precondition: hasSystem() == true
Definition at line 48 of file rpc/scft/sweep/BasisFieldState.tpp.
References Pscf::Rpc::FieldState< D, DArray< double > >::field(), Pscf::Rpc::FieldState< D, DArray< double > >::fields(), Pscf::Rpc::FieldState< D, DArray< double > >::hasSystem(), Pscf::Rpc::FieldState< D, DArray< double > >::system(), and UTIL_CHECK.
Referenced by getSystemState(), and read().
read()
template<int D> void Pscf::Rpc::BasisFieldState< D >::read (const std::string & filename)
Read state from file.
Parameters
filename name of input w-field file in symmetry-adapted format.
Definition at line 77 of file rpc/scft/sweep/BasisFieldState.tpp.
References allocate(), Pscf::Rpc::FieldState< D, DArray< double > >::fields(), Pscf::Rpc::FieldIo< D >::readFieldsBasis(), Pscf::Rpc::FieldState< D, DArray< double > >::system(), and Pscf::Rpc::FieldState< D, DArray< double > >::unitCell().
Referenced by pscfpp.command.Script::__init__(), pscfpp.field.Field::__init__(), pscfpp.output.Thermo::__init__(), pscfpp.param.Array::__init__(), pscfpp.param.Composite::__init__(), and pscfpp.param.Matrix::__init__().
write()
template<int D> void Pscf::Rpc::BasisFieldState< D >::write (const std::string & filename)
Write state to file.
Write fields in symmetry-adapted basis format.
Parameters
filename name of output file, in symmetry-adapated format.
Definition at line 90 of file rpc/scft/sweep/BasisFieldState.tpp.
References Pscf::Rpc::FieldState< D, DArray< double > >::fields(), Pscf::Rpc::FieldState< D, DArray< double > >::system(), Pscf::Rpc::FieldState< D, DArray< double > >::unitCell(), and Pscf::Rpc::FieldIo< D >::writeFieldsBasis().
getSystemState()
template<int D> void Pscf::Rpc::BasisFieldState< D >::getSystemState ()
Copy the current state of the associated system.
Copy the fields and the unit cell.
Definition at line 100 of file rpc/scft/sweep/BasisFieldState.tpp.
References allocate(), Pscf::Rpc::FieldState< D, DArray< double > >::field(), Pscf::Rpc::FieldState< D, DArray< double > >::system(), and Pscf::Rpc::FieldState< D, DArray< double > >::unitCell().
setSystemState()
template<int D> void Pscf::Rpc::BasisFieldState< D >::setSystemState (bool isFlexible)
Set the state of the associated system to this state.
Parameters
isFlexible update system unit cell iff isFlexible == true.
Definition at line 123 of file rpc/scft/sweep/BasisFieldState.tpp.
References Pscf::Rpc::FieldState< D, DArray< double > >::fields(), Pscf::Rpc::FieldState< D, DArray< double > >::system(), and Pscf::Rpc::FieldState< D, DArray< double > >::unitCell().
The documentation for this class was generated from the following files:
rpc/scft/sweep/BasisFieldState.h
rpc/scft/sweep/BasisFieldState.tpp