PSCF: Util::RadialDistribution Class Reference
Util::RadialDistribution Class Reference
Util namespace » Accumulators
Distribution (or histogram) of values for particle separations.
#include <RadialDistribution.h>
Public Member Functions
RadialDistribution ()
Default constructor.
RadialDistribution (const RadialDistribution &other)
Copy constructor.
RadialDistribution & operator= (const RadialDistribution &other)
Assignment.
virtual void readParameters (std::istream &in)
Read values of min, max, and nBin from file.
void setParam (double max, int nBin)
Set parameters and initialize.
virtual void loadParameters (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this RadialDistribution to/from an archive.
virtual void clear ()
Clear all accumulators.
void beginSnapshot ()
Mark the beginning of a "snapshot" (i.e., a sampled time step).
void setNorm (double norm)
Set the factor used to normalize the RDF before output.
void setOutputIntegral (bool outputIntegral)
Set true to enable output of spatial integral of g(r).
void output (std::ostream &out)
Output the distribution to file.
long nSnapshot ()
Get number of snapshots.
Public Member Functions inherited from Util::Distribution
Distribution ()
Default constructor.
Distribution (const Distribution &other)
Copy constructor.
Distribution & operator= (const Distribution &other)
Assignment operator.
virtual ~Distribution ()
Destructor.
void setParam (double min, double max, int nBin)
Set parameters and initialize.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this Distribution to/from an archive.
void sample (double value)
Sample a value.
void output (std::ostream &out)
Output the distribution to file.
int binIndex (double value) const
Return the index of the bin for a value.
double min () const
Get minimum value in range of histogram.
double max () const
Get maximum value in range of histogram.
double binWidth () const
Get binWidth, the width of each bin.
int nBin () const
Get the number of bins.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from Util::Distribution
DArray< long > histogram_
Histogram of occurences, one element per bin.
double min_
minimum value.
double max_
maximum value.
double binWidth_
width of bin = (max_-min_)/nBin_ .
int nBin_
number of bins.
int nSample_
Number of sampled values in Histogram.
int nReject_
Number of sampled values that were out of range.
Detailed Description
Distribution (or histogram) of values for particle separations.
Definition at line 21 of file RadialDistribution.h.
Constructor & Destructor Documentation
RadialDistribution() [1/2]
Util::RadialDistribution::RadialDistribution ()
Default constructor.
Definition at line 19 of file RadialDistribution.cpp.
References Util::Distribution::Distribution(), and Util::ParamComposite::setClassName().
Referenced by operator=(), and RadialDistribution().
RadialDistribution() [2/2]
Util::RadialDistribution::RadialDistribution (const RadialDistribution & other)
Copy constructor.
Parameters
other object to be copied.
Definition at line 29 of file RadialDistribution.cpp.
References Util::Distribution::Distribution(), and RadialDistribution().
Member Function Documentation
operator=()
RadialDistribution & Util::RadialDistribution::operator= (const RadialDistribution & other)
Assignment.
Parameters
other object to be assigned.
Definition at line 40 of file RadialDistribution.cpp.
References Util::Distribution::operator=(), and RadialDistribution().
readParameters()
void Util::RadialDistribution::readParameters (std::istream & in) virtual
Read values of min, max, and nBin from file.
Parameters
in input parameter file stream.
Reimplemented from Util::Distribution.
Definition at line 55 of file RadialDistribution.cpp.
References Util::Distribution::binWidth_, clear(), Util::Distribution::histogram_, Util::Distribution::max_, Util::Distribution::min_, Util::Distribution::nBin_, and Util::ParamComposite::read().
setParam()
void Util::RadialDistribution::setParam (double max, int nBin)
Set parameters and initialize.
Parameters
max upper bound of range
nBin number of bins in range [min, max]
Definition at line 68 of file RadialDistribution.cpp.
References Util::Distribution::binWidth_, clear(), Util::Distribution::histogram_, Util::Distribution::max(), Util::Distribution::max_, Util::Distribution::min_, Util::Distribution::nBin(), and Util::Distribution::nBin_.
loadParameters()
void Util::RadialDistribution::loadParameters (Serializable::IArchive & ar) virtual
Load internal state from an archive.
Parameters
ar input/loading archive
Reimplemented from Util::Distribution.
Definition at line 81 of file RadialDistribution.cpp.
References Util::Distribution::binWidth_, Util::feq(), Util::Distribution::histogram_, Util::ParamComposite::loadParameter(), Util::Distribution::max_, Util::Distribution::min_, Util::Distribution::nBin_, Util::Distribution::nReject_, Util::Distribution::nSample_, and UTIL_THROW.
save()
void Util::RadialDistribution::save (Serializable::OArchive & ar) virtual
Save internal state to an archive.
Parameters
ar output/saving archive
Reimplemented from Util::Distribution.
Definition at line 104 of file RadialDistribution.cpp.
serialize()
template<class Archive> void Util::RadialDistribution::serialize (Archive & ar, const unsigned int version)
Serialize this RadialDistribution to/from an archive.
Parameters
ar input or output archive
version file version id
Definition at line 160 of file RadialDistribution.h.
References Util::Distribution::serialize().
clear()
void Util::RadialDistribution::clear () virtual
Clear all accumulators.
Reimplemented from Util::Distribution.
Definition at line 110 of file RadialDistribution.cpp.
References Util::Distribution::clear().
Referenced by readParameters(), and setParam().
beginSnapshot()
void Util::RadialDistribution::beginSnapshot ()
Mark the beginning of a "snapshot" (i.e., a sampled time step).
Definition at line 125 of file RadialDistribution.cpp.
setNorm()
void Util::RadialDistribution::setNorm (double norm)
Set the factor used to normalize the RDF before output.
Parameters
norm normalizing factor
Definition at line 119 of file RadialDistribution.cpp.
setOutputIntegral()
void Util::RadialDistribution::setOutputIntegral (bool outputIntegral)
Set true to enable output of spatial integral of g(r).
Parameters
outputIntegral true to enable output of integral.
Definition at line 131 of file RadialDistribution.cpp.
output()
void Util::RadialDistribution::output (std::ostream & out)
Output the distribution to file.
Parameters
out pointer to output file
Definition at line 137 of file RadialDistribution.cpp.
References Util::Distribution::binWidth_, Util::Distribution::histogram_, and Util::Distribution::nBin_.
nSnapshot()
long Util::RadialDistribution::nSnapshot () inline
Get number of snapshots.
Definition at line 153 of file RadialDistribution.h.
The documentation for this class was generated from the following files:
RadialDistribution.h
RadialDistribution.cpp