PSCF: Util::Pair< Data > Class Template Reference
Util::Pair< Data > Class Template Reference
Util namespace » Container Templates » Object Arrays
An array of exactly 2 objects.
#include <Pair.h>
Static Public Member Functions
static void commitMpiType ()
Commit associated MPI DataType.
Static Public Member Functions inherited from Util::FArray< Data, 2 >
static void commitMpiType ()
Commit associated MPI DataType.
Additional Inherited Members
Public Member Functions inherited from Util::FArray< Data, 2 >
FArray ()
Constructor.
FArray (FArray< Data, Capacity > const &other)
Copy constructor.
FArray< Data, Capacity > & operator= (FArray< Data, Capacity > const &other)
Assignment, element by element.
int size () const
Return number of elements in this FArray.
int capacity () const
Return number of elements in this FArray.
void begin (ArrayIterator< Data > &iterator)
Set an ArrayIterator to the beginning of this Array.
void begin (ConstArrayIterator< Data > &iterator) const
Set a ConstArrayIterator to the beginning of this Array.
Data & operator[] (int i)
Mimic C array subscripting.
Data const & operator[] (int i) const
Mimic C array subscripting.
Data * cArray ()
Return pointer to underlying C array.
Data const * cArray () const
Return pointer to const to underlying C array.
void serialize (Archive &ar, const unsigned int version)
Serialize a FArray to/from an Archive.
int packedSize ()
Return packed size in a MemoryArchive, in bytes.
Detailed Description
template<typename Data>
class Util::Pair< Data >
An array of exactly 2 objects.
Definition at line 23 of file Pair.h.
Member Function Documentation
commitMpiType()
template<typename Data > void Util::Pair< Data >::commitMpiType static
Commit associated MPI DataType.
Definition at line 69 of file Pair.h.
References Util::MpiStructBuilder::addMember(), Util::MpiStructBuilder::commit(), and Util::MpiStructBuilder::setBase().
The documentation for this class was generated from the following file:
Pair.h