PSCF: Pscf::Rpc::RGridTrajectoryReader< D > Class Template Reference
Pscf::Rpc::RGridTrajectoryReader< D > Class Template Reference
Pscf namespace » Pscf::Rpc - Real Periodic Fields (CPU) » Field Theoretic Simulation (FTS) » Trajectory Readers
Trajectory file reader.
#include <RGridTrajectoryReader.h>
Public Member Functions
RGridTrajectoryReader (System< D > &system)
Constructor.
virtual ~RGridTrajectoryReader ()
Destructor.
void open (std::string filename)
Open trajectory file and read header, if any.
bool readFrame ()
Read a single frame.
void close ()
Close the trajectory file.
void readHeader ()
Read header of trajectory file.
Public Member Functions inherited from Pscf::Rpc::TrajectoryReader< D >
TrajectoryReader (System< D > &system)
Constructor.
virtual ~TrajectoryReader ()
Destructor.
Protected Member Functions
void allocate ()
Allocate memory required by trajectory reader.
Protected Member Functions inherited from Pscf::Rpc::TrajectoryReader< D >
System< D > & system ()
Return reference to parent system.
Detailed Description
template<int D>
class Pscf::Rpc::RGridTrajectoryReader< D >
Trajectory file reader.
Definition at line 34 of file rpc/fts/trajectory/RGridTrajectoryReader.h.
Constructor & Destructor Documentation
RGridTrajectoryReader()
template<int D> Pscf::Rpc::RGridTrajectoryReader< D >::RGridTrajectoryReader (System< D > & system)
Constructor.
Definition at line 30 of file rpc/fts/trajectory/RGridTrajectoryReader.tpp.
References Pscf::Rpc::TrajectoryReader< D >::system(), and Pscf::Rpc::TrajectoryReader< D >::TrajectoryReader().
~RGridTrajectoryReader()
template<int D> virtual Pscf::Rpc::RGridTrajectoryReader< D >::~RGridTrajectoryReader () inline virtual
Destructor.
Definition at line 47 of file rpc/fts/trajectory/RGridTrajectoryReader.h.
Member Function Documentation
open()
template<int D> void Pscf::Rpc::RGridTrajectoryReader< D >::open (std::string filename) virtual
Open trajectory file and read header, if any.
By convention, this function treats the trajectory filename as the name of an input file, and opens the file using the FileMaster:openInutFile function. This function prepends the input prefix (if any) to the file path.
Parameters
filename trajectory input file name.
Implements Pscf::Rpc::TrajectoryReader< D >.
Definition at line 55 of file rpc/fts/trajectory/RGridTrajectoryReader.tpp.
References allocate(), and Pscf::Rpc::TrajectoryReader< D >::system().
readFrame()
template<int D> bool Pscf::Rpc::RGridTrajectoryReader< D >::readFrame () virtual
Read a single frame.
Frames are assumed to be read consecutively.
This function reads a frame from the trajectory file that was opened by the open() function.
Returns
true if a frame is avaiable, false if at end of file
Implements Pscf::Rpc::TrajectoryReader< D >.
Definition at line 79 of file rpc/fts/trajectory/RGridTrajectoryReader.tpp.
References Util::checkString(), Util::Log::file(), Util::getNextLine(), Pscf::Rpc::FieldIo< D >::readFieldsRGridData(), Pscf::Rpc::TrajectoryReader< D >::system(), UTIL_CHECK, and UTIL_THROW.
close()
template<int D> void Pscf::Rpc::RGridTrajectoryReader< D >::close () virtual
Close the trajectory file.
Implements Pscf::Rpc::TrajectoryReader< D >.
Definition at line 130 of file rpc/fts/trajectory/RGridTrajectoryReader.tpp.
readHeader()
template<int D> void Pscf::Rpc::RGridTrajectoryReader< D >::readHeader () virtual
Read header of trajectory file.
Reimplemented from Pscf::Rpc::TrajectoryReader< D >.
Definition at line 62 of file rpc/fts/trajectory/RGridTrajectoryReader.tpp.
References Util::Log::file(), Pscf::Prdc::hasSymmetry(), Pscf::Rpc::FieldIo< D >::readFieldHeader(), and Pscf::Rpc::TrajectoryReader< D >::system().
allocate()
template<int D> void Pscf::Rpc::RGridTrajectoryReader< D >::allocate () protected
Allocate memory required by trajectory reader.
Definition at line 36 of file rpc/fts/trajectory/RGridTrajectoryReader.tpp.
References Pscf::Rpc::TrajectoryReader< D >::system(), and UTIL_CHECK.
Referenced by open().
The documentation for this class was generated from the following files:
rpc/fts/trajectory/RGridTrajectoryReader.h
rpc/fts/trajectory/RGridTrajectoryReader.tpp