PSCF: Util::AutoCorrStage< Data, Product > Class Template Reference
Util::AutoCorrStage< Data, Product > Class Template Reference
Util namespace » Accumulators
Hierarchical auto-correlation function algorithm.
#include <AutoCorrStage.h>
Public Member Functions
AutoCorrStage ()
Constructor.
virtual ~AutoCorrStage ()
Destructor.
void setParam (int bufferCapacity=64, int maxStageId=0, int blockFactor=2)
Set all parameters and allocate to initialize state.
virtual void sample (Data value)
Sample a value.
void clear ()
Clear accumulators and destroy descendants.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Accessors
int bufferCapacity_
Physical capacity (# of elements) of buffer, corr, and nCorr.
int maxStageId_
Maximum allowed stage index (controls maximum degree of blocking).
int blockFactor_
Number of values per block (ratio of intervals for successive stages).
void output (std::ostream &out)
Output the autocorrelation function, assuming zero mean.
void output (std::ostream &out, Product aveSq)
Output the autocorrelation function.
int bufferCapacity () const
Return capacity of history buffer.
int bufferSize () const
Return current size of history buffer.
long nSample () const
Return the number of sampled values.
long stageInterval () const
Return the number of primary values per block at this stage.
Product autoCorrelation (int t) const
Return autocorrelation at a given time, assuming zero average.
Product autoCorrelation (int t, Product aveSq) const
Return autocorrelation at a given lag time.
double corrTime () const
Estimate of autocorrelation time, in samples.
double corrTime (Product aveSq) const
Numerical integration of autocorrelation function.
void allocate ()
Allocate memory and initialize to empty state.
bool hasChild () const
Does this have a child AutoCorrStage?
AutoCorrStage & child ()
Return the child AutoCorrStage by reference.
virtual void registerDescendant (AutoCorrStage< Data, Product > *ptr)
Register the creation of a descendant stage.
template<class Archive>
void serializePrivate (Archive &ar, const unsigned int version)
Serialize private data members, and descendants.
Detailed Description
template<typename Data, typename Product>
class Util::AutoCorrStage< Data, Product >
Hierarchical auto-correlation function algorithm.
This class calculates an autocorrelation function for a sequence x(i) of values of a variable or object of type Data. The resulting autocorrelation function is and array of values of type Product, where C(j) = <x(i-j), x(i)>. Here <A,B> denotes an inner product of type Product for objects A and B of type Data.
The meaning of the inner product is defined for various data types b the overloaded function Product product(Data, Data) that is defined for double, complex and Vector data in the product.h file.
The zero value for variables of type Data is returned by the overloaded function void setToZero(Data) method defined in the setToData.h file.
This class implements a hierarchical algorithm to calculate C(j). The algorithm is implemented by a linked list of AutoCorrStage objects. Each object in this list is assigned an integer chainId.
The "primary" AutoCorrStage object in this list, with chainId=0, calculates the autocorrelation for a primary sequence of primary Data values that are passed to the sample method of this object. For each n > 0, the object with chainId = n calculates the autocorrelation function for a sequence of values in which each value is an average of a block of blockFactor**n consecutive values of the primary sequence or, equivalently, an average of blockFactor consecutive values of the sequence maintained by the parent object with chainId = n-1. Additional stages are added to this list dynamically as needed.
Definition at line 53 of file AutoCorrStage.h.
Constructor & Destructor Documentation
AutoCorrStage()
template<typename Data, typename Product> Util::AutoCorrStage< Data, Product >::AutoCorrStage ()
Constructor.
This constructor creates a primary AutoCorrStage object with stageId = 0 and stageInterval = 1. A private constructor is used to recursively create descendant stages as needed.
Definition at line 30 of file AutoCorrStage.tpp.
References blockFactor_, bufferCapacity_, maxStageId_, and Util::setToZero().
Referenced by Util::AutoCorrelation< Data, Product >::AutoCorrelation(), child(), Util::AutoCorrelation< Data, Product >::maxDelay(), Util::AutoCorrelation< Data, Product >::registerDescendant(), registerDescendant(), sample(), and serializePrivate().
~AutoCorrStage()
template<typename Data, typename Product> Util::AutoCorrStage< Data, Product >::~AutoCorrStage () virtual
Destructor.
Recursively destroy all descendant stages.
Definition at line 79 of file AutoCorrStage.tpp.
Member Function Documentation
setParam()
template<typename Data, typename Product> void Util::AutoCorrStage< Data, Product >::setParam (int bufferCapacity = 64, int maxStageId = 0, int blockFactor = 2)
Set all parameters and allocate to initialize state.
Parameters
bufferCapacity max. number of values stored in buffer
maxStageId maximum stage index (0=primary)
blockFactor ratio of block sizes of subsequent stages
Definition at line 90 of file AutoCorrStage.tpp.
References allocate(), blockFactor_, bufferCapacity(), bufferCapacity_, and maxStageId_.
sample()
template<typename Data, typename Product> void Util::AutoCorrStage< Data, Product >::sample (Data value) virtual
Sample a value.
Parameters
value current Data value
Definition at line 121 of file AutoCorrStage.tpp.
References allocate(), AutoCorrStage(), blockFactor_, bufferCapacity_, maxStageId_, Util::product(), and Util::setToZero().
clear()
template<typename Data, typename Product> void Util::AutoCorrStage< Data, Product >::clear ()
Clear accumulators and destroy descendants.
Definition at line 103 of file AutoCorrStage.tpp.
References bufferCapacity_, and Util::setToZero().
Referenced by allocate().
serialize()
template<typename Data, typename Product> template<class Archive> void Util::AutoCorrStage< Data, Product >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters
ar archive
version archive version id
Definition at line 168 of file AutoCorrStage.tpp.
References blockFactor_, bufferCapacity_, maxStageId_, and serializePrivate().
output() [1/2]
template<typename Data, typename Product> void Util::AutoCorrStage< Data, Product >::output (std::ostream & out)
Output the autocorrelation function, assuming zero mean.
This calls output(std::ostream out, Product aveSq) with a zero value for aveSq.
Parameters
out output stream.
Definition at line 259 of file AutoCorrStage.tpp.
References output(), and Util::setToZero().
Referenced by output().
output() [2/2]
template<typename Data, typename Product> void Util::AutoCorrStage< Data, Product >::output (std::ostream & out, Product aveSq)
Output the autocorrelation function.
The parameter avSq = ave(x)^2 is subtracted from the correlation function ave(x(t)x(0)).
Parameters
out output stream
aveSq square of ave(x)
Definition at line 270 of file AutoCorrStage.tpp.
References blockFactor_, bufferCapacity_, and Util::write().
bufferCapacity()
template<typename Data, typename Product> int Util::AutoCorrStage< Data, Product >::bufferCapacity () const
Return capacity of history buffer.
Definition at line 231 of file AutoCorrStage.tpp.
References bufferCapacity_.
Referenced by setParam().
bufferSize()
template<typename Data, typename Product> int Util::AutoCorrStage< Data, Product >::bufferSize () const
Return current size of history buffer.
Definition at line 238 of file AutoCorrStage.tpp.
Referenced by Util::AutoCorrelation< Data, Product >::maxDelay().
nSample()
template<typename Data, typename Product> long Util::AutoCorrStage< Data, Product >::nSample () const
Return the number of sampled values.
Definition at line 245 of file AutoCorrStage.tpp.
stageInterval()
template<typename Data, typename Product> long Util::AutoCorrStage< Data, Product >::stageInterval () const
Return the number of primary values per block at this stage.
Definition at line 252 of file AutoCorrStage.tpp.
Referenced by Util::AutoCorrelation< Data, Product >::maxDelay().
autoCorrelation() [1/2]
template<typename Data, typename Product> Product Util::AutoCorrStage< Data, Product >::autoCorrelation (int t) const
Return autocorrelation at a given time, assuming zero average.
This calls autoCorrelations(t, aveSq) with a zero value for for aveSq.
Parameters
t the lag time, in Data samples
Definition at line 296 of file AutoCorrStage.tpp.
References autoCorrelation(), and Util::setToZero().
Referenced by autoCorrelation().
autoCorrelation() [2/2]
template<typename Data, typename Product> Product Util::AutoCorrStage< Data, Product >::autoCorrelation (int t, Product aveSq) const
Return autocorrelation at a given lag time.
The parameter aveSq is subtracted from ave(x(t)x(0)) in output.
Parameters
t the lag time, in Data samples
aveSq square ave(x(t))
Definition at line 307 of file AutoCorrStage.tpp.
corrTime() [1/2]
template<typename Data, typename Product> double Util::AutoCorrStage< Data, Product >::corrTime () const
Estimate of autocorrelation time, in samples.
This variant assumes a zero average.
Definition at line 319 of file AutoCorrStage.tpp.
References corrTime(), and Util::setToZero().
Referenced by corrTime().
corrTime() [2/2]
template<typename Data, typename Product> double Util::AutoCorrStage< Data, Product >::corrTime (Product aveSq) const
Numerical integration of autocorrelation function.
This function returns the time integral of the autocorrelation function. The parameter aveSq is subtracted from ave(x(t)x(0)) in the integrand.
Parameters
aveSq square ave(x(t))
Definition at line 330 of file AutoCorrStage.tpp.
References Util::setToZero().
allocate()
template<typename Data, typename Product> void Util::AutoCorrStage< Data, Product >::allocate () protected
Allocate memory and initialize to empty state.
Definition at line 357 of file AutoCorrStage.tpp.
References bufferCapacity_, and clear().
Referenced by Util::AutoCorrelation< Data, Product >::readParameters(), sample(), and setParam().
hasChild()
template<typename Data, typename Product> bool Util::AutoCorrStage< Data, Product >::hasChild () const inline protected
Does this have a child AutoCorrStage?
Definition at line 305 of file AutoCorrStage.h.
Referenced by serializePrivate().
child()
template<typename Data, typename Product> AutoCorrStage< Data, Product > & Util::AutoCorrStage< Data, Product >::child () inline protected
Return the child AutoCorrStage by reference.
Definition at line 312 of file AutoCorrStage.h.
References AutoCorrStage().
registerDescendant()
template<typename Data, typename Product> void Util::AutoCorrStage< Data, Product >::registerDescendant (AutoCorrStage< Data, Product > * ptr) protected virtual
Register the creation of a descendant stage.
This should be called only by a root stage.
Parameters
ptr pointer to a descendant AutoCorrStage.
Reimplemented in Util::AutoCorrelation< Data, Product >.
Definition at line 385 of file AutoCorrStage.tpp.
References AutoCorrStage().
serializePrivate()
template<typename Data, typename Product> template<class Archive> void Util::AutoCorrStage< Data, Product >::serializePrivate (Archive & ar, const unsigned int version) protected
Serialize private data members, and descendants.
Parameters
ar archive
version archive version id
Definition at line 186 of file AutoCorrStage.tpp.
References AutoCorrStage(), blockFactor_, hasChild(), and maxStageId_.
Referenced by Util::AutoCorrelation< Data, Product >::load(), and serialize().
Member Data Documentation
bufferCapacity_
template<typename Data, typename Product> int Util::AutoCorrStage< Data, Product >::bufferCapacity_ protected
Physical capacity (# of elements) of buffer, corr, and nCorr.
Definition at line 193 of file AutoCorrStage.h.
Referenced by allocate(), AutoCorrStage(), bufferCapacity(), clear(), Util::AutoCorrelation< Data, Product >::load(), output(), Util::AutoCorrelation< Data, Product >::readParameters(), sample(), serialize(), and setParam().
maxStageId_
template<typename Data, typename Product> int Util::AutoCorrStage< Data, Product >::maxStageId_ protected
Maximum allowed stage index (controls maximum degree of blocking).
Definition at line 196 of file AutoCorrStage.h.
Referenced by AutoCorrStage(), Util::AutoCorrelation< Data, Product >::load(), Util::AutoCorrelation< Data, Product >::readParameters(), sample(), serialize(), serializePrivate(), and setParam().
blockFactor_
template<typename Data, typename Product> int Util::AutoCorrStage< Data, Product >::blockFactor_ protected
Number of values per block (ratio of intervals for successive stages).
Definition at line 199 of file AutoCorrStage.h.
Referenced by AutoCorrStage(), Util::AutoCorrelation< Data, Product >::load(), output(), Util::AutoCorrelation< Data, Product >::readParameters(), sample(), serialize(), serializePrivate(), and setParam().
The documentation for this class was generated from the following files:
AutoCorrStage.h
AutoCorrStage.tpp