PSCF: Pscf::Pspg::Block< D > Class Template Reference
Pscf::Pspg::Block< D > Class Template Reference
Pscf namespace » Periodic Pseudo-Spectral (GPU) » Solvers
Block within a branched polymer.
#include <Block.h>
Public Types
typedef Pscf::Pspg::Propagator< D >::Field Field
Generic field (base class)
typedef Pscf::Pspg::Propagator< D >::WField WField
Monomer chemical potential field.
typedef Pscf::Pspg::Propagator< D >::QField QField
Constrained partition function q(r,s) for fixed s.
Public Member Functions
Block ()
Constructor.
~Block ()
Destructor.
void setDiscretization (double ds, const Mesh< D > &mesh)
Initialize discretization and allocate required memory.
void setupUnitCell (const UnitCell< D > &unitCell, const WaveList< D > &waveList)
Setup parameters that depend on the unit cell.
void setLength (double length)
Set or reset block length.
void setKuhn (double kuhn)
Set or reset monomer statistical segment length.
void setupSolver (WField const &w)
Set solver for this block.
void setupFFT ()
Initialize FFT and batch FFT classes.
void step (const cudaReal *q, cudaReal *qNew)
Compute step of integration loop, from i to i+1.
void computeConcentration (double prefactor)
Compute unnormalized concentration for block by integration.
void computeStress (WaveList< D > &waveList, double prefactor)
Compute derivatives of free energy with respect to cell parameters.
double stress (int n)
Get derivative of free energy with respect to a unit cell parameter.
Mesh< D > const & mesh () const
Return associated spatial Mesh by reference.
double ds () const
Contour length step size.
int ns () const
Number of contour length steps.
void setId (int id)
Set the id for this block.
void setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
void setMonomerId (int monomerId)
Set the monomer id.
virtual void setLength (double length)
Set the length of this block.
int id () const
Get the id of this block.
int monomerId () const
Get the monomer type id.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
double length () const
Get the length (number of monomers) in this block.
Public Member Functions inherited from Pscf::BlockTmpl< Propagator< D > >
BlockTmpl ()
Constructor.
virtual ~BlockTmpl ()
Destructor.
virtual void setKuhn (double kuhn)
Set monomer statistical segment length.
Propagator< D > & propagator (int directionId)
Get a Propagator for a specified direction.
Propagator< D > const & propagator (int directionId) const
Get a const Propagator for a specified direction.
TP::CField & cField ()
Get the associated monomer concentration field.
double kuhn () const
Get monomer statistical segment length.
Public Member Functions inherited from Pscf::BlockDescriptor
BlockDescriptor ()
Constructor.
virtual ~BlockDescriptor ()
Destructor.
template<class Archive >
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
void setId (int id)
Set the id for this block.
void setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
void setMonomerId (int monomerId)
Set the monomer id.
void setPolymerType (PolymerType::Enum type)
Set the polymer type.
int id () const
Get the id of this block.
int monomerId () const
Get the monomer type id.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
double length () const
Get the length (number of monomers) in this block.
PolymerType::Enum polymerType () const
Get the type of the parent polymer (branched or linear).
Detailed Description
template<int D>
class Pscf::Pspg::Block< D >
Block within a branched polymer.
Derived from BlockTmpl< Propagator<D> >. A BlockTmpl< Propagator<D> > has two Propagator<D> members and is derived from BlockDescriptor.
Definition at line 39 of file pspg/solvers/Block.h.
Member Typedef Documentation
Field
template<int D> typedef Pscf::Pspg::Propagator<D>::Field Pscf::Pspg::Block< D >::Field
Generic field (base class)
Definition at line 47 of file pspg/solvers/Block.h.
WField
template<int D> typedef Pscf::Pspg::Propagator<D>::WField Pscf::Pspg::Block< D >::WField
Monomer chemical potential field.
Definition at line 52 of file pspg/solvers/Block.h.
QField
template<int D> typedef Pscf::Pspg::Propagator<D>::QField Pscf::Pspg::Block< D >::QField
Constrained partition function q(r,s) for fixed s.
Definition at line 57 of file pspg/solvers/Block.h.
Constructor & Destructor Documentation
Block()
template<int D> Pscf::Pspg::Block< D >::Block
Constructor.
Definition at line 179 of file pspg/solvers/Block.tpp.
References Pscf::BlockTmpl< Propagator< D > >::propagator().
~Block()
template<int D> Pscf::Pspg::Block< D >::~Block
Destructor.
Definition at line 198 of file pspg/solvers/Block.tpp.
Member Function Documentation
setDiscretization()
template<int D> void Pscf::Pspg::Block< D >::setDiscretization (double ds, const Mesh< D > & mesh)
Initialize discretization and allocate required memory.
Parameters
ds desired (optimal) value for contour length step
mesh spatial discretization mesh
Definition at line 213 of file pspg/solvers/Block.tpp.
References Pscf::Mesh< D >::dimensions(), Pscf::Pspg::ThreadGrid::setThreadsLogical(), Pscf::Mesh< D >::size(), and UTIL_CHECK.
setupUnitCell()
template<int D> void Pscf::Pspg::Block< D >::setupUnitCell (const UnitCell< D > & unitCell, const WaveList< D > & waveList)
Setup parameters that depend on the unit cell.
Parameters
unitCell unit cell, defining cell dimensions
waveList container for properties of recip wavevectors
Definition at line 314 of file pspg/solvers/Block.tpp.
References Pscf::UnitCellBase< D >::nParameter().
setLength() [1/2]
template<int D> void Pscf::Pspg::Block< D >::setLength (double length) virtual
Set or reset block length.
Parameters
length new block length
Reimplemented from Pscf::BlockDescriptor.
Definition at line 289 of file pspg/solvers/Block.tpp.
References Pscf::BlockDescriptor::setLength(), and UTIL_CHECK.
setKuhn()
template<int D> void Pscf::Pspg::Block< D >::setKuhn (double kuhn) virtual
Set or reset monomer statistical segment length.
Parameters
kuhn new monomer statistical segment length.
Reimplemented from Pscf::BlockTmpl< Propagator< D > >.
Definition at line 303 of file pspg/solvers/Block.tpp.
setupSolver()
template<int D> void Pscf::Pspg::Block< D >::setupSolver (WField const & w)
Set solver for this block.
Parameters
w chemical potential field for this monomer type
setupFFT()
template<int D> void Pscf::Pspg::Block< D >::setupFFT
Initialize FFT and batch FFT classes.
Definition at line 439 of file pspg/solvers/Block.tpp.
step()
template<int D> void Pscf::Pspg::Block< D >::step (const cudaReal * q, cudaReal * qNew)
Compute step of integration loop, from i to i+1.
Definition at line 453 of file pspg/solvers/Block.tpp.
References UTIL_CHECK.
computeConcentration()
template<int D> void Pscf::Pspg::Block< D >::computeConcentration (double prefactor)
Compute unnormalized concentration for block by integration.
Upon return, grid point r of array cField() contains the integral int ds q(r,s)q^{*}(r,L-s) times the prefactor, where q(r,s) is the solution obtained from propagator(0), and q^{*} is the solution of propagator(1), and s is a contour variable that is integrated over the domain 0 < s < length(), where length() is the block length.
Parameters
prefactor constant prefactor multiplying integral
Definition at line 399 of file pspg/solvers/Block.tpp.
References Pscf::Pspg::Propagator< D >::q(), and UTIL_CHECK.
computeStress()
template<int D> void Pscf::Pspg::Block< D >::computeStress (WaveList< D > & waveList, double prefactor)
Compute derivatives of free energy with respect to cell parameters.
The prefactor is the same as that used in computeConcentration.
Parameters
waveList container for properties of recip. latt. wavevectors.
prefactor constant prefactor multiplying integral
Definition at line 501 of file pspg/solvers/Block.tpp.
References Pscf::Pspg::Propagator< D >::head(), and UTIL_CHECK.
stress()
template<int D> double Pscf::Pspg::Block< D >::stress (int n) inline
Get derivative of free energy with respect to a unit cell parameter.
Get derivative of free energy w/ respect to a unit cell parameter.
Parameters
n unit cell parameter index
Definition at line 289 of file pspg/solvers/Block.h.
mesh()
template<int D> Mesh< D > const & Pscf::Pspg::Block< D >::mesh inline
Return associated spatial Mesh by reference.
Get Mesh by reference.
Definition at line 294 of file pspg/solvers/Block.h.
References UTIL_ASSERT.
ds()
template<int D> double Pscf::Pspg::Block< D >::ds inline
Contour length step size.
Get number of contour steps.
Definition at line 284 of file pspg/solvers/Block.h.
ns()
template<int D> int Pscf::Pspg::Block< D >::ns inline
Number of contour length steps.
Get number of contour steps.
Definition at line 279 of file pspg/solvers/Block.h.
setId()
template<int D> void Pscf::BlockDescriptor::setId (int id)
Set the id for this block.
Parameters
id integer index for this block
Definition at line 64 of file BlockDescriptor.cpp.
setVertexIds()
template<int D> void Pscf::BlockDescriptor::setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
Parameters
vertexAId integer id of vertex A
vertexBId integer id of vertex B
Definition at line 72 of file BlockDescriptor.cpp.
setMonomerId()
template<int D> void Pscf::BlockDescriptor::setMonomerId (int monomerId)
Set the monomer id.
Parameters
monomerId integer id of monomer type (>=0)
Definition at line 79 of file BlockDescriptor.cpp.
setLength() [2/2]
template<int D> void Pscf::BlockDescriptor::setLength (double length) virtual
Set the length of this block.
The ``length" is steric volume / reference volume.
Parameters
length block length (number of monomers).
Reimplemented from Pscf::BlockDescriptor.
Definition at line 88 of file BlockDescriptor.cpp.
id()
template<int D> int Pscf::BlockDescriptor::id () const inline
Get the id of this block.
Definition at line 114 of file BlockDescriptor.h.
monomerId()
template<int D> int Pscf::BlockDescriptor::monomerId () const inline
Get the monomer type id.
Definition at line 119 of file BlockDescriptor.h.
vertexIds()
template<int D> const Pair< int > & Pscf::BlockDescriptor::vertexIds () const inline
Get the pair of associated vertex ids.
Definition at line 124 of file BlockDescriptor.h.
vertexId()
template<int D> int Pscf::BlockDescriptor::vertexId (int i) const inline
Get id of an associated vertex.
Parameters
i index of vertex (0 or 1)
Definition at line 131 of file BlockDescriptor.h.
length()
template<int D> double Pscf::BlockDescriptor::length () const inline
Get the length (number of monomers) in this block.
Definition at line 136 of file BlockDescriptor.h.
The documentation for this class was generated from the following files:
pspg/solvers/Block.h
pspg/solvers/Block.tpp