PSCF: Pscf::Pspg::Mixture< D > Class Template Reference
Pscf::Pspg::Mixture< D > Class Template Reference
Pscf namespace » Periodic Pseudo-Spectral (GPU) » Solvers
Solver for a mixture of polymers and solvents.
#include <Mixture.h>
Public Types
typedef Propagator< D >::WField WField
Monomer chemical potential field type.
typedef Propagator< D >::CField CField
Monomer concentration or volume fraction field type.
Public Types inherited from Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >
typedef Polymer< D > Polymer
Polymer species solver type.
typedef Solvent< D > Solvent
Solvent species solver type.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Mixture ()
Constructor.
~Mixture ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
void setMesh (Mesh< D > const &mesh)
Create an association with the mesh and allocate memory.
void setupUnitCell (const UnitCell< D > &unitCell, const WaveList< D > &wavelist)
Set unit cell parameters used in solver.
void compute (DArray< WField > const &wFields, DArray< CField > &cFields)
Compute concentrations.
void computeStress (WaveList< D > &wavelist)
Get monomer reference volume.
double stress (int n)
Get derivative of free energy w/ respect to cell parameter.
double vMonomer () const
Get monomer reference volume.
Public Member Functions inherited from Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >
MixtureTmpl ()
Constructor.
~MixtureTmpl ()
Destructor.
Monomer & monomer (int id)
Get a Monomer type descriptor.
Polymer & polymer (int id)
Get a polymer object.
Solvent & solvent (int id)
Set a solvent solver object.
int nMonomer () const
Get number of monomer types.
int nPolymer () const
Get number of polymer species.
int nSolvent () const
Get number of solvent (point particle) species.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out)
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
template<int D>
class Pscf::Pspg::Mixture< D >
Solver for a mixture of polymers and solvents.
A Mixture contains a list of Polymer and Solvent objects. Each such object can solve the single-molecule statistical mechanics problem for an ideal gas of the associated species in a set of specified chemical potential fields, and thereby compute concentrations and single-molecule partition functions. A Mixture is thus both a chemistry descriptor and an ideal-gas solver.
A Mixture is associated with a Mesh<D> object, which models a spatial discretization mesh.
Definition at line 43 of file pspg/solvers/Mixture.h.
Member Typedef Documentation
template<int D> typedef Propagator<D>::WField Pscf::Pspg::Mixture< D >::WField
Monomer chemical potential field type.
Definition at line 53 of file pspg/solvers/Mixture.h.
template<int D> typedef Propagator<D>::CField Pscf::Pspg::Mixture< D >::CField
Monomer concentration or volume fraction field type.
Definition at line 58 of file pspg/solvers/Mixture.h.
Constructor & Destructor Documentation
template<int D> Pscf::Pspg::Mixture< D >::Mixture ()
Constructor.
Definition at line 33 of file pspg/solvers/Mixture.tpp.
References Util::ParamComposite::setClassName().
template<int D> Pscf::Pspg::Mixture< D >::~Mixture ()
Destructor.
Definition at line 40 of file pspg/solvers/Mixture.tpp.
Member Function Documentation
template<int D> void Pscf::Pspg::Mixture< D >::readParameters (std::istream & in) virtual
Read all parameters and initialize.
This function reads in a complete description of the chemical composition and structure of all species, as well as the target contour length step size ds.
Parameters
in input parameter stream
Reimplemented from Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >.
Definition at line 44 of file pspg/solvers/Mixture.tpp.
References Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nMonomer(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nPolymer(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nSolvent(), Util::ParamComposite::read(), Util::ParamComposite::readOptional(), and UTIL_CHECK.
template<int D> void Pscf::Pspg::Mixture< D >::setMesh (Mesh< D > const & mesh)
Create an association with the mesh and allocate memory.
The Mesh<D> object must have already been initialized, e.g., by reading its parameters from a file, so that the mesh dimensions are known on entry.
Parameters
mesh associated Mesh<D> object (stores address).
Definition at line 57 of file pspg/solvers/Mixture.tpp.
References Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nMonomer(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nPolymer(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nSolvent(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::polymer(), and UTIL_CHECK.
template<int D> void Pscf::Pspg::Mixture< D >::setupUnitCell (const UnitCell< D > & unitCell, const WaveList< D > & wavelist)
Set unit cell parameters used in solver.
Parameters
unitCell UnitCell<D> object that contains Bravais lattice.
Definition at line 76 of file pspg/solvers/Mixture.tpp.
References Pscf::Pspg::DField< Data >::cDField(), Pscf::Pspg::Mixture< D >::compute(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nMonomer(), Pscf::UnitCellBase< D >::nParameter(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nPolymer(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nSolvent(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::polymer(), and UTIL_CHECK.
template<int D> void Pscf::Pspg::Mixture< D >::compute (DArray< WField > const & wFields, DArray< CField > & cFields)
Compute concentrations.
This function calls the compute function of every molecular species, and then adds the resulting block concentration fields for blocks of each type to compute a total monomer concentration (or volume fraction) for each monomer type. Upon return, values are set for volume fraction and chemical potential (mu) members of each species, and for the concentration fields for each Block and Solvent. The total concentration for each monomer type is returned in the cFields output parameter.
The arrays wFields and cFields must each have size nMonomer(), and contain fields that are indexed by monomer type index.
Parameters
wFields array of chemical potential fields (input)
cFields array of monomer concentration fields (output)
Referenced by Pscf::Pspg::Mixture< D >::setupUnitCell().
template<int D> void Pscf::Pspg::Mixture< D >::computeStress (WaveList< D > & wavelist)
Get monomer reference volume.
Definition at line 136 of file pspg/solvers/Mixture.tpp.
References Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nPolymer(), and Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::polymer().
template<int D> double Pscf::Pspg::Mixture< D >::stress (int n) inline
Get derivative of free energy w/ respect to cell parameter.
Get precomputed value of derivative of free energy per monomer with respect to unit cell parameter number n.
n unit cell parameter id
Definition at line 136 of file pspg/solvers/Mixture.h.
References Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nMonomer(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nPolymer(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::nSolvent(), Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >::polymer(), Util::ParamComposite::read(), Util::ParamComposite::readOptional(), Util::ParamComposite::setClassName(), and Pscf::Pspg::Mixture< D >::vMonomer().
template<int D> double Pscf::Pspg::Mixture< D >::vMonomer () const inline
Get monomer reference volume.
Definition at line 183 of file pspg/solvers/Mixture.h.
References UTIL_ASSERT.
Referenced by Pscf::Pspg::Mixture< D >::stress().
The documentation for this class was generated from the following files:
pspg/solvers/Mixture.h
pspg/solvers/Mixture.tpp