PSCF: Pscf::Fd1d::AmIterator Class Reference
Pscf::Fd1d::AmIterator Class Reference
Pscf namespace » Finite-Difference 1D » Iterators
Anderson-Mixing iterator.
#include <AmIterator.h>
Public Member Functions
AmIterator (System &system)
Constructor.
~AmIterator ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
Public Member Functions inherited from Pscf::AmIteratorTmpl< Iterator, DArray< double > >
AmIteratorTmpl ()
Constructor.
~AmIteratorTmpl ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
int solve (bool isContinuation=false)
Iterate to a solution.
Protected Member Functions
void setup (bool isContinuation)
Setup iterator just before entering iteration loop.
Protected Member Functions inherited from Pscf::AmIteratorTmpl< Iterator, DArray< double > >
void setMaxItr (int maxItr)
Set value of maxItr.
void setMaxHist (int maxHist)
Set value of maxHist (number of retained previous states)
void setErrorType (std::string errorType)
Set and validate value of errorType string.
void readErrorType (std::istream &in)
Read and validate the optional errorType string parameter.
virtual bool isValidErrorType ()
Checks if a string is a valid error type.
virtual double norm (DArray< double > const &hist)
Find the L2 norm of a vector.
void allocateAM ()
Allocate memory required by AM algorithm, if necessary.
virtual void clear ()
Clear information about history.
virtual void setup (bool isContinuation)
Initialize just before entry to iterative loop.
virtual double computeError (int verbose)
Compute and return error used to test for convergence.
DArray< double > const & residual () const
Return the current residual vector by const reference.
DArray< double > const & field () const
Return the current field or state vector by const reference.
int verbose () const
Verbosity level, allowed values 0, 1, or 2.
bool isAllocatedAM () const
Have data structures required by the AM algorithm been allocated?
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Additional Inherited Members
Protected Attributes inherited from Pscf::AmIteratorTmpl< Iterator, DArray< double > >
std::string errorType_
Type of error criterion used to test convergence.
Detailed Description
Anderson-Mixing iterator.
Definition at line 29 of file fd1d/iterator/AmIterator.h.
Constructor & Destructor Documentation
AmIterator()
Pscf::Fd1d::AmIterator::AmIterator (System & system)
Constructor.
Parameters
system System object associated with this iterator.
Definition at line 20 of file fd1d/iterator/AmIterator.cpp.
~AmIterator()
Pscf::Fd1d::AmIterator::~AmIterator ()
Destructor.
Definition at line 26 of file fd1d/iterator/AmIterator.cpp.
Member Function Documentation
readParameters()
void Pscf::Fd1d::AmIterator::readParameters (std::istream & in)
Read all parameters and initialize.
Parameters
in input filestream
Definition at line 30 of file fd1d/iterator/AmIterator.cpp.
References Pscf::AmIteratorTmpl< Iterator, DArray< double > >::readErrorType(), readParameters(), and Pscf::AmbdInteraction::setNMonomer().
Referenced by readParameters().
setup()
void Pscf::Fd1d::AmIterator::setup (bool isContinuation) protected virtual
Setup iterator just before entering iteration loop.
Parameters
isContinuation Is this a continuation within a sweep?
Reimplemented from Pscf::AmIteratorTmpl< Iterator, DArray< double > >.
Definition at line 41 of file fd1d/iterator/AmIterator.cpp.
References setup(), and Pscf::AmbdInteraction::update().
Referenced by setup().
The documentation for this class was generated from the following files:
fd1d/iterator/AmIterator.h
fd1d/iterator/AmIterator.cpp