PSCF: Pscf::Pspc::FilmIteratorBase< D, IteratorType > Class Template Reference
Pscf::Pspc::FilmIteratorBase< D, IteratorType > Class Template Reference abstract
Pscf namespace » Pseudo-Spectral Periodic (CPU) » Iterators
Descriptor for a FilmIterator object.
#include <FilmIteratorBase.h>
Public Member Functions
FilmIteratorBase (System< D > &system)
Constructor.
~FilmIteratorBase ()
Destructor.
void readParameters (std::istream &in)
Read and initialize.
void setup ()
Allocate required memory, perform necessary checks to ensure user input is compatible with a film constraint, and create the mask / external fields that will be used to represent the walls during iteration.
int solve (bool isContinuation=false)
Iterate to a solution.
IteratorType const & iterator () const
Return const reference to the real iterator within this FilmIterator.
bool isFlexible () const
Return whether unit cell is flexible.
virtual void setFlexibleParams ()=0
Determine the indices of each flexible lattice parameter, based on normalVecId and unitCell definitions in param file.
virtual void checkLatticeVectors () const =0
Check that user-defined lattice basis vectors (stored in the Domain<D> object associated with this FilmIterator class) are compatible with the thin film constraint.
void generateWallFields ()
Generates the field representation of the walls, based on the values of wallThickness and interfaceThickness that were input by the user.
void updateWallFields ()
Checks whether the lattice parameters have been updated since the last call of generateWallFields(), and if the parameters have changed then calls generateWallFields() again to update them.
void adjustPhiVals ()
Iterates over all polymers and solvents in the Mixture, and multiplies their volume fractions (phi values) by (1-phi_w), where phi_w is the volume fraction occupied by the walls.
void checkSpaceGroup () const
Check that user-defined space group is compatible with the thin film constraint.
bool isSymmetric () const
Check whether or not the walls are chemically identical using the chi array.
bool isAthermal () const
Check whether or not the walls are athermal (this is only true if all of the values in the chi array are zero)
void setChi (int s, int w, double chi)
Set the value of chi between species s and wall w.
void writeWallField (std::ostream &out) const
Write the concentration field of the walls to an output stream, in basis format.
void writeWallField (std::string filename) const
Write the concentration field of the walls to a file specified by 'filename', in basis format.
void writeWallFieldRGrid (std::ostream &out) const
Write the concentration field of the walls to an output stream, in r-grid format.
void writeWallFieldRGrid (std::string filename) const
Write the concentration field of the walls to a file specified by 'filename', in r-grid format.
DArray< double > const & maskBasis () const
Returns the field that describes the mask imposed upon the unit cell, which represents the wall.
DArray< DArray< double > > const & externalFields () const
Returns the array of fields that describes the external potential field felt by each monomer species, which is a result of chemical interactions between the wall and the monomer species.
DArray< double > const & externalField (int monomerId) const
Returns the field that describes the external potential field felt by monomer species monomerId, which is a result of chemical interactions between the wall and the monomer species.
int normalVecId () const
Get const value of normalVecId.
double interfaceThickness () const
Get const value of interfaceThickness.
double wallThickness () const
Get const value of wallThickness.
DMatrix< double > const & chi () const
Get const chi matrix by reference.
double chi (int s, int w) const
Get the const chi parameter between wall w and species s by reference.
Public Member Functions inherited from Pscf::Pspc::Iterator< D >
Iterator ()
Default constructor.
Iterator (System< D > &system)
Constructor.
~Iterator ()
Destructor.
virtual void setup ()=0
Setup iterator.
virtual int solve (bool isContinuation)=0
Iterate to solution.
System< D > const & system () const
Return const reference to parent system.
virtual bool isFlexible () const
Return true if unit cell is flexible, false if rigid.
void setFlexibleParams (FSArray< int, 6 > const &flexParams)
Sets the flexibleParams_ array.
FSArray< int, 6 > flexibleParams () const
Return an array containing indices of each flexible lattice parameter, e.g.
void setMask (DArray< double > const &field)
Accepts a field array representing the concentration profile of the mask that will be imposed upon the unit cell, and stores it for use during iteration.
void setExternalFields (DArray< DArray< double > > const &fields)
Accepts an array of fields representing the external potential field felt by each monomer species, and stores it for use during iteration.
virtual DArray< double > const & maskBasis () const
Returns the field that represents the mask imposed upon the unit cell, or returns an unallocated field if the iterator does not have a mask.
virtual DArray< DArray< double > > const & externalFields () const
Returns the array of fields that represents the external potential field felt by each monomer species, or returns an unallocated field if the iterator does not have an external field.
virtual DArray< double > const & externalField (int monomerId) const
Returns the field that represents the external field imposed on the monomer species monomerId, or returns an unallocated field if the iterator does not have an external field.
bool hasMask () const
Return true if this iterator imposes a mask within the unit cell, false if no mask is imposed.
bool hasExternalFields () const
Return true if this iterator imposes an external field on any monomer species, returns false if no external field is present.
double maskPhi () const
Return the volume fraction of the unit cell occupied by the mask.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void readParam (std::istream &in)=0
Read parameter(s) from file.
virtual void writeParam (std::ostream &out) const =0
Read parameter(s) to file.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
virtual void save (OArchive &ar)=0
Save to an archive.
virtual void load (IArchive &ar)=0
Load from an archive.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
IteratorType & iterator ()
Return reference to the real iterator within this FilmIterator.
void generateExternalFields ()
Generate external fields only, and pass them into iterator object for use during calculation.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
Protected Member Functions inherited from Pscf::Pspc::Iterator< D >
System< D > & system ()
Return reference to parent system.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Attributes inherited from Pscf::Pspc::Iterator< D >
bool isFlexible_
Is the unit cell flexible during iteration?
FSArray< int, 6 > flexibleParams_
Array of indices of the lattice parameters that are flexible.
bool hasMask_
Does this iterator have a mask?
bool hasExternalFields_
Does this iterator have an external field?
Detailed Description
template<int D, typename IteratorType>
class Pscf::Pspc::FilmIteratorBase< D, IteratorType >
Descriptor for a FilmIterator object.
This base class template defines all traits of a FilmIterator that do not depend on D, the dimension of the system. The subclasses of FilmIteratorBase are the partial specializations of FilmIterator for 1D, 2D, and 3D.
If the user chooses a FilmIterator as their iterator, then the system will contain two parallel hard surfaces ("walls"), confining the polymers/solvents to a "thin film" region of the unit cell. This only affects the iterator, not the rest of SCFT, so we isolate the imposition of the thin film constraint to this subclass of iterator. This is essentially a wrapper for any other type of iterator (e.g., AmIterator), that adds the additional functionality required to impose the thin film constraint properly.
FilmIterator is generalized to be compatible with any iterator within it, as long as the iterator can impose 1) a mask that confines the polymers/solvents to a certain region of space, and 2) an external field. A FilmIterator object in the param file is created by appending "Film" to the end of the name of the iterator that is stored inside of FilmIterator (e.g., "AmIteratorFilm{" will create a FilmIterator with an AmIterator object inside of it).
Definition at line 51 of file FilmIteratorBase.h.
Constructor & Destructor Documentation
FilmIteratorBase()
template<int D, typename IteratorType > Pscf::Pspc::FilmIteratorBase< D, IteratorType >::FilmIteratorBase (System< D > & system)
Constructor.
Definition at line 34 of file FilmIteratorBase.tpp.
References Pscf::Pspc::Iterator< D >::hasMask_, and Util::ParamComposite::setClassName().
~FilmIteratorBase()
template<int D, typename IteratorType > Pscf::Pspc::FilmIteratorBase< D, IteratorType >::~FilmIteratorBase
Destructor.
Definition at line 53 of file FilmIteratorBase.tpp.
Member Function Documentation
readParameters()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::readParameters (std::istream & in) virtual
Read and initialize.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 60 of file FilmIteratorBase.tpp.
setup()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::setup virtual
Allocate required memory, perform necessary checks to ensure user input is compatible with a film constraint, and create the mask / external fields that will be used to represent the walls during iteration.
Implements Pscf::Pspc::Iterator< D >.
Definition at line 110 of file FilmIteratorBase.tpp.
solve()
template<int D, typename IteratorType > int Pscf::Pspc::FilmIteratorBase< D, IteratorType >::solve (bool isContinuation = false) virtual
Iterate to a solution.
Parameters
isContinuation true iff continuation within a sweep
Implements Pscf::Pspc::Iterator< D >.
Definition at line 143 of file FilmIteratorBase.tpp.
iterator() [1/2]
template<int D, typename IteratorType > IteratorType const & Pscf::Pspc::FilmIteratorBase< D, IteratorType >::iterator inline
Return const reference to the real iterator within this FilmIterator.
Definition at line 332 of file FilmIteratorBase.h.
Referenced by Pscf::Pspc::FilmIterator< 1, IteratorType >::FilmIterator(), Pscf::Pspc::FilmIterator< 2, IteratorType >::FilmIterator(), Pscf::Pspc::FilmIterator< 3, IteratorType >::FilmIterator(), Pscf::Pspc::FilmIterator< 1, IteratorType >::setFlexibleParams(), Pscf::Pspc::FilmIterator< 2, IteratorType >::setFlexibleParams(), and Pscf::Pspc::FilmIterator< 3, IteratorType >::setFlexibleParams().
isFlexible()
template<int D, typename IteratorType > bool Pscf::Pspc::FilmIteratorBase< D, IteratorType >::isFlexible inline virtual
Return whether unit cell is flexible.
Reimplemented from Pscf::Pspc::Iterator< D >.
Definition at line 337 of file FilmIteratorBase.h.
setFlexibleParams()
template<int D, typename IteratorType > virtual void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::setFlexibleParams () pure virtual
Determine the indices of each flexible lattice parameter, based on normalVecId and unitCell definitions in param file.
Assumes that isFlexible == true, and gives a warning if none of the parameters are actually able to be varied given the thin film constraints. Stores resulting array in flexibleParams_ member of this object, as well as the flexibleParams_ member of the iterator within this object.
This function varies depending on D, the dimensionality of the system. Therefore, it is implemented in the partial class specializations in FilmIterator, rather than in this base class.
Implemented in Pscf::Pspc::FilmIterator< 1, IteratorType >, Pscf::Pspc::FilmIterator< 2, IteratorType >, and Pscf::Pspc::FilmIterator< 3, IteratorType >.
Referenced by Pscf::Pspc::FilmIterator< 1, IteratorType >::setFlexibleParams(), Pscf::Pspc::FilmIterator< 2, IteratorType >::setFlexibleParams(), and Pscf::Pspc::FilmIterator< 3, IteratorType >::setFlexibleParams().
checkLatticeVectors()
template<int D, typename IteratorType > virtual void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::checkLatticeVectors () const pure virtual
Check that user-defined lattice basis vectors (stored in the Domain<D> object associated with this FilmIterator class) are compatible with the thin film constraint.
This function varies depending on D, the dimensionality of the system. Therefore, it is implemented in the partial class specializations in FilmIterator, rather than in this base class.
Implemented in Pscf::Pspc::FilmIterator< 1, IteratorType >, Pscf::Pspc::FilmIterator< 2, IteratorType >, and Pscf::Pspc::FilmIterator< 3, IteratorType >.
generateWallFields()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::generateWallFields
Generates the field representation of the walls, based on the values of wallThickness and interfaceThickness that were input by the user.
Then, passes this wall field into the iterator_ object to be used as a mask during iteration, and also passes the corresponding external potential fields into iterator_ if isAthermal() == false.
Definition at line 162 of file FilmIteratorBase.tpp.
References UTIL_CHECK.
updateWallFields()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::updateWallFields
Checks whether the lattice parameters have been updated since the last call of generateWallFields(), and if the parameters have changed then calls generateWallFields() again to update them.
Also updates the external fields if the wall/polymer chi parameters have been updated since external fields were last generated.
Definition at line 247 of file FilmIteratorBase.tpp.
References Util::FSArray< Data, Capacity >::size(), and UTIL_CHECK.
adjustPhiVals()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::adjustPhiVals
Iterates over all polymers and solvents in the Mixture, and multiplies their volume fractions (phi values) by (1-phi_w), where phi_w is the volume fraction occupied by the walls.
This correction ensures that the system will still be able to converge to a solution that satisfies the incompressibility constraint.
Definition at line 393 of file FilmIteratorBase.tpp.
References Util::Log::file(), and UTIL_CHECK.
checkSpaceGroup()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::checkSpaceGroup
Check that user-defined space group is compatible with the thin film constraint.
Definition at line 433 of file FilmIteratorBase.tpp.
References Util::Log::file(), Pscf::makeGroupFileName(), Pscf::SymmetryGroup< Symmetry >::size(), UTIL_CHECK, and UTIL_THROW.
isSymmetric()
template<int D, typename IteratorType > bool Pscf::Pspc::FilmIteratorBase< D, IteratorType >::isSymmetric
Check whether or not the walls are chemically identical using the chi array.
Definition at line 483 of file FilmIteratorBase.tpp.
References UTIL_CHECK.
isAthermal()
template<int D, typename IteratorType > bool Pscf::Pspc::FilmIteratorBase< D, IteratorType >::isAthermal
Check whether or not the walls are athermal (this is only true if all of the values in the chi array are zero)
Definition at line 504 of file FilmIteratorBase.tpp.
References UTIL_CHECK.
setChi()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::setChi (int s, int w, double chi) inline
Set the value of chi between species s and wall w.
Parameters
w wall index, 0 or 1
s species index, 0 <= id < nVertex
chi value of chi(s,w)
Definition at line 343 of file FilmIteratorBase.h.
writeWallField() [1/2]
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::writeWallField (std::ostream & out) const
Write the concentration field of the walls to an output stream, in basis format.
Parameters
out output stream
Definition at line 525 of file FilmIteratorBase.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
writeWallField() [2/2]
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::writeWallField (std::string filename) const
Write the concentration field of the walls to a file specified by 'filename', in basis format.
Parameters
filename name of file to which data will be written
Definition at line 543 of file FilmIteratorBase.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
writeWallFieldRGrid() [1/2]
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::writeWallFieldRGrid (std::ostream & out) const
Write the concentration field of the walls to an output stream, in r-grid format.
Parameters
out output stream
Definition at line 561 of file FilmIteratorBase.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
writeWallFieldRGrid() [2/2]
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::writeWallFieldRGrid (std::string filename) const
Write the concentration field of the walls to a file specified by 'filename', in r-grid format.
Parameters
filename name of file to which data will be written
Definition at line 585 of file FilmIteratorBase.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
maskBasis()
template<int D, typename IteratorType > DArray< double > const & Pscf::Pspc::FilmIteratorBase< D, IteratorType >::maskBasis inline virtual
Returns the field that describes the mask imposed upon the unit cell, which represents the wall.
Field is in symmetry-adapted basis format.
Reimplemented from Pscf::Pspc::Iterator< D >.
Definition at line 349 of file FilmIteratorBase.h.
externalFields()
template<int D, typename IteratorType > DArray< DArray< double > > const & Pscf::Pspc::FilmIteratorBase< D, IteratorType >::externalFields inline virtual
Returns the array of fields that describes the external potential field felt by each monomer species, which is a result of chemical interactions between the wall and the monomer species.
Fields are in symmetry-adapted basis format.
Reimplemented from Pscf::Pspc::Iterator< D >.
Definition at line 357 of file FilmIteratorBase.h.
externalField()
template<int D, typename IteratorType > DArray< double > const & Pscf::Pspc::FilmIteratorBase< D, IteratorType >::externalField (int monomerId) const inline virtual
Returns the field that describes the external potential field felt by monomer species monomerId, which is a result of chemical interactions between the wall and the monomer species.
Fields are in symmetry-adapted basis format.
Parameters
monomerId integer monomer type index
Reimplemented from Pscf::Pspc::Iterator< D >.
Definition at line 364 of file FilmIteratorBase.h.
normalVecId()
template<int D, typename IteratorType > int Pscf::Pspc::FilmIteratorBase< D, IteratorType >::normalVecId inline
Get const value of normalVecId.
Definition at line 370 of file FilmIteratorBase.h.
Referenced by Pscf::Pspc::FilmIterator< 3, IteratorType >::checkLatticeVectors(), Pscf::Pspc::FilmIterator< 2, IteratorType >::setFlexibleParams(), and Pscf::Pspc::FilmIterator< 3, IteratorType >::setFlexibleParams().
interfaceThickness()
template<int D, typename IteratorType > double Pscf::Pspc::FilmIteratorBase< D, IteratorType >::interfaceThickness inline
Get const value of interfaceThickness.
Definition at line 375 of file FilmIteratorBase.h.
wallThickness()
template<int D, typename IteratorType > double Pscf::Pspc::FilmIteratorBase< D, IteratorType >::wallThickness inline
Get const value of wallThickness.
Definition at line 381 of file FilmIteratorBase.h.
chi() [1/2]
template<int D, typename IteratorType > DMatrix< double > const & Pscf::Pspc::FilmIteratorBase< D, IteratorType >::chi inline
Get const chi matrix by reference.
Definition at line 386 of file FilmIteratorBase.h.
chi() [2/2]
template<int D, typename IteratorType > double Pscf::Pspc::FilmIteratorBase< D, IteratorType >::chi (int s, int w) const inline
Get the const chi parameter between wall w and species s by reference.
Parameters
s species index, 0 <= id < nVertex
w wall index, 0 or 1
Definition at line 392 of file FilmIteratorBase.h.
iterator() [2/2]
template<int D, typename IteratorType > IteratorType & Pscf::Pspc::FilmIteratorBase< D, IteratorType >::iterator inline protected
Return reference to the real iterator within this FilmIterator.
Definition at line 326 of file FilmIteratorBase.h.
generateExternalFields()
template<int D, typename IteratorType > void Pscf::Pspc::FilmIteratorBase< D, IteratorType >::generateExternalFields protected
Generate external fields only, and pass them into iterator object for use during calculation.
This is called by generateWallFields().
Definition at line 289 of file FilmIteratorBase.tpp.
References Util::DArray< Data >::allocate(), and UTIL_CHECK.
read()
template<int D, typename IteratorType > template<typename Type > ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value) protected
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 304 of file ParamComposite.h.
readOptional()
template<int D, typename IteratorType > template<typename Type > ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 318 of file ParamComposite.h.
readOptionalDMatrix()
template<int D, typename IteratorType > template<typename Type > DMatrixParam< Type > & Util::ParamComposite::readOptionalDMatrix (std::istream & in, const char * label, DMatrix< Type > & matrix, int m, int n) inline protected
Add and read an optional DMatrix < Type > matrix parameter.
Parameters
in input stream for reading
label Label string for new array
matrix DMatrix object
m number of rows (1st dimension)
n number of columns (2nd dimension)
Returns
reference to the DMatrixParam<Type> object
Definition at line 460 of file ParamComposite.h.
setParent()
template<int D, typename IteratorType > void Util::ParamComposite::setParent (ParamComponent & param, bool next = true) protected
Set this to the parent of a child component.
This function sets the indent and (ifdef UTIL_MPI) the ioCommunicator of the child component.
Parameters
param child ParamComponent
next if true, set indent level one higher than for parent.
Definition at line 868 of file ParamComposite.cpp.
addComponent()
template<int D, typename IteratorType > void Util::ParamComposite::addComponent (ParamComponent & param, bool isLeaf = true) protected
Add a new ParamComponent object to the format array.
Parameters
param Parameter object
isLeaf Is this a leaf or a ParamComposite node?
Definition at line 876 of file ParamComposite.cpp.
The documentation for this class was generated from the following files:
FilmIteratorBase.h
FilmIteratorBase.tpp