PSCF: Pscf::Pspg::FFTBatched< D > Class Template Reference
Pscf::Pspg::FFTBatched< D > Class Template Reference
Pscf namespace » Periodic Pseudo-Spectral (GPU) » Fields
Fourier transform wrapper for real data.
#include <FFTBatched.h>
Public Member Functions
FFTBatched ()
Default constructor.
virtual ~FFTBatched ()
Destructor.
void setup (RDField< D > &rDField, RDFieldDft< D > &kDField)
Check and setup grid dimensions if necessary.
void forwardTransform (RDField< D > &in, RDFieldDft< D > &out)
Compute forward (real-to-complex) Fourier transform.
void inverseTransform (RDFieldDft< D > &in, RDField< D > &out)
Compute inverse (complex-to-real) Fourier transform.
const IntVec< D > & meshDimensions () const
Return the dimensions of the grid for which this was allocated.
Detailed Description
template<int D>
class Pscf::Pspg::FFTBatched< D >
Fourier transform wrapper for real data.
Definition at line 36 of file FFTBatched.h.
Constructor & Destructor Documentation
template<int D> Pscf::Pspg::FFTBatched< D >::FFTBatched ()
Default constructor.
Definition at line 47 of file FFTBatched.tpp.
template<int D> Pscf::Pspg::FFTBatched< D >::~FFTBatched () virtual
Destructor.
Definition at line 60 of file FFTBatched.tpp.
Member Function Documentation
template<int D> void Pscf::Pspg::FFTBatched< D >::setup (RDField< D > & rDField, RDFieldDft< D > & kDField)
Check and setup grid dimensions if necessary.
Parameters
rDField real data on r-space grid (device mem)
kDField complex data on k-space grid (device mem)
Definition at line 74 of file FFTBatched.tpp.
References Pscf::Pspg::RDFieldDft< D >::meshDimensions(), Pscf::Pspg::RDField< D >::meshDimensions(), and UTIL_CHECK.
Referenced by Pscf::Pspg::FFTBatched< D >::forwardTransform(), and Pscf::Pspg::FFTBatched< D >::inverseTransform().
template<int D> void Pscf::Pspg::FFTBatched< D >::forwardTransform (RDField< D > & in, RDFieldDft< D > & out)
Compute forward (real-to-complex) Fourier transform.
Parameters
in array of real values on r-space grid (device mem)
out array of complex values on k-space grid (device mem)
Definition at line 249 of file FFTBatched.tpp.
References Pscf::Pspg::DField< cudaReal >::capacity(), Pscf::Pspg::DField< cudaComplex >::capacity(), Pscf::Pspg::DField< cudaReal >::cDField(), Pscf::Pspg::DField< cudaComplex >::cDField(), Pscf::Pspg::FFTBatched< D >::setup(), and UTIL_CHECK.
template<int D> void Pscf::Pspg::FFTBatched< D >::inverseTransform (RDFieldDft< D > & in, RDField< D > & out)
Compute inverse (complex-to-real) Fourier transform.
Parameters
in array of complex values on k-space grid (device mem)
out array of real values on r-space grid (device mem)
Definition at line 319 of file FFTBatched.tpp.
References Pscf::Pspg::DField< cudaComplex >::cDField(), Pscf::Pspg::DField< cudaReal >::cDField(), and Pscf::Pspg::FFTBatched< D >::setup().
template<int D> const IntVec< D > & Pscf::Pspg::FFTBatched< D >::meshDimensions () const inline
Return the dimensions of the grid for which this was allocated.
Definition at line 123 of file FFTBatched.h.
The documentation for this class was generated from the following files:
FFTBatched.h
FFTBatched.tpp