PSCF: Pscf::DeviceArray< Data > Class Template Reference
Pscf::DeviceArray< Data > Class Template Reference
Pscf namespace » Pscf Common » CUDA Utilities
Dynamic array on the GPU device with aligned data.
#include <DeviceArray.h>
Public Types
typedef Data ElementType
Data type of each element.
Public Member Functions
DeviceArray ()
Default constructor.
DeviceArray (int capacity)
Allocating constructor.
DeviceArray (DeviceArray< Data > const &other)
Copy constructor.
virtual ~DeviceArray ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array on the device.
void associate (DeviceArray< Data > &arr, int beginId, int capacity)
Associate this object with a slice of a different DeviceArray.
void deallocate ()
Dellocate the underlying C array.
void dissociate ()
Dissociate this object from the associated array.
virtual DeviceArray< Data > & operator= (const DeviceArray< Data > &other)
Assignment operator, assign from another DeviceArray<Data> array.
virtual DeviceArray< Data > & operator= (const HostDArray< Data > &other)
Assignment operator, assignment from HostDArray<Data> host array.
int capacity () const
Return allocated capacity.
bool isAllocated () const
Return true if the array has been allocated, false otherwise.
bool isOwner () const
Does this object own the underlying data?
Data * cArray ()
Return pointer to underlying C array.
Data const * cArray () const
Return const pointer to underlying C array.
Protected Attributes
Data * dataPtr_
Pointer to a C array of Data elements on the GPU device.
int capacity_
Allocated size (capacity) of the array.
DeviceArray< Data > const * ownerPtr_
Pointer to array that owns this data, if isOwner_ == false.
int ownerCapacity_
Capacity of parent array, if isOwner_ == false.
Data const * ownerDataPtr_
Const pointer to parent array, if isOwner_ == false.
Detailed Description
template<typename Data>
class Pscf::DeviceArray< Data >
Dynamic array on the GPU device with aligned data.
This class wraps an aligned C array with elements of type Data that is allocated in GPU device global memory. All member functions may be called from the CPU host, but this class does not offer access to individual elements via the subscript operator, operator[].
A DeviceArray can have one of two different relationships with its underlying data. In case 1, the data are owned by this object, so the allocation and destruction of the C array are performed by this object. In case 2, this object is instead "associated" with a slice of an array owned by a different DeviceArray. If this is the case, this object is not responsible for allocation or destruction of the underlying C array, and merely acts as a reference to the slice of the other array to which it is associated.
Definition at line 42 of file DeviceArray.h.
Member Typedef Documentation
ElementType
template<typename Data> typedef Data Pscf::DeviceArray< Data >::ElementType
Data type of each element.
Definition at line 50 of file DeviceArray.h.
Constructor & Destructor Documentation
DeviceArray() [1/3]
template<typename Data> Pscf::DeviceArray< Data >::DeviceArray ()
Default constructor.
Definition at line 210 of file DeviceArray.h.
References capacity_, dataPtr_, ownerCapacity_, ownerDataPtr_, and ownerPtr_.
Referenced by associate(), DeviceArray(), and operator=().
DeviceArray() [2/3]
template<typename Data> Pscf::DeviceArray< Data >::DeviceArray (int capacity)
Allocating constructor.
This function calls allocate(capacity) internally.
Parameters
capacity number of elements to allocate
Definition at line 222 of file DeviceArray.h.
References allocate(), capacity(), capacity_, dataPtr_, ownerCapacity_, ownerDataPtr_, and ownerPtr_.
DeviceArray() [3/3]
template<typename Data> Pscf::DeviceArray< Data >::DeviceArray (DeviceArray< Data > const & other)
Copy constructor.
Parameters
other DeviceArray<Data> to be copied (input)
Definition at line 236 of file DeviceArray.h.
References allocate(), capacity_, cArray(), dataPtr_, DeviceArray(), isAllocated(), and UTIL_THROW.
~DeviceArray()
template<typename Data> Pscf::DeviceArray< Data >::~DeviceArray () virtual
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 252 of file DeviceArray.h.
References capacity_, dataPtr_, isAllocated(), and isOwner().
Member Function Documentation
allocate()
template<typename Data> void Pscf::DeviceArray< Data >::allocate (int capacity)
Allocate the underlying C array on the device.
Exceptions
Exception if the array is already allocated.
Parameters
capacity number of elements to allocate.
Definition at line 264 of file DeviceArray.h.
References capacity(), capacity_, dataPtr_, isAllocated(), ownerPtr_, and UTIL_THROW.
Referenced by DeviceArray(), DeviceArray(), Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), operator=(), operator=(), and Pscf::Prdc::Cuda::Reduce::sum().
associate()
template<typename Data> void Pscf::DeviceArray< Data >::associate (DeviceArray< Data > & arr, int beginId, int capacity)
Associate this object with a slice of a different DeviceArray.
Exceptions
Exception if the array is already allocated.
Parameters
arr parent array that owns the data
beginId index in the parent array at which this array starts
capacity number of elements to allocate
Definition at line 285 of file DeviceArray.h.
References capacity(), capacity_, cArray(), dataPtr_, DeviceArray(), isAllocated(), isOwner(), ownerCapacity_, ownerDataPtr_, ownerPtr_, UTIL_CHECK, and UTIL_THROW.
Referenced by Pscf::Prdc::Cuda::CField< D >::associate(), Pscf::Prdc::Cuda::RField< D >::associate(), and Pscf::Prdc::Cuda::RFieldDft< D >::associate().
deallocate()
template<typename Data> void Pscf::DeviceArray< Data >::deallocate ()
Dellocate the underlying C array.
Exceptions
Exception if the array is not allocated.
Exception if this object does not own the array.
Definition at line 311 of file DeviceArray.h.
References capacity_, dataPtr_, isAllocated(), isOwner(), and UTIL_THROW.
Referenced by Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), and Pscf::Prdc::Cuda::Reduce::sum().
dissociate()
template<typename Data> void Pscf::DeviceArray< Data >::dissociate ()
Dissociate this object from the associated array.
Exceptions
Exception if this object is not associated with an array.
Definition at line 330 of file DeviceArray.h.
References capacity_, dataPtr_, isAllocated(), isOwner(), ownerCapacity_, ownerDataPtr_, ownerPtr_, and UTIL_THROW.
operator=() [1/2]
template<typename Data> DeviceArray< Data > & Pscf::DeviceArray< Data >::operator= (const DeviceArray< Data > & other) virtual
Assignment operator, assign from another DeviceArray<Data> array.
Performs a deep copy, by copying values of all elements from device memory to device memory.
This function will allocate memory if this (LHS) array is not allocated. If this is allocated, it must have the same dimensions as the RHS DeviceArray<Data>.
Parameters
other DeviceArray<Data> on rhs of assignent (input)
Definition at line 350 of file DeviceArray.h.
References allocate(), capacity(), capacity_, cArray(), dataPtr_, DeviceArray(), isAllocated(), and UTIL_THROW.
Referenced by Pscf::Prdc::Cuda::CField< D >::operator=(), Pscf::Prdc::Cuda::RField< D >::operator=(), and Pscf::Prdc::Cuda::RFieldDft< D >::operator=().
operator=() [2/2]
template<typename Data> DeviceArray< Data > & Pscf::DeviceArray< Data >::operator= (const HostDArray< Data > & other) virtual
Assignment operator, assignment from HostDArray<Data> host array.
Performs a deep copy from a RHS HostDArray<Data> host array to this LHS DeviceArray<Data> device array, by copying underlying C array from host memory to device memory.
This function will allocate memory if this (LHS) DeviceArray<Data> is not allocated. If this is allocated, it must have the same dimensions as the RHS HostDArray<Data>.
Parameters
other HostDArray<Data> on RHS of assignent (input)
Definition at line 383 of file DeviceArray.h.
References allocate(), Util::Array< Data >::capacity(), capacity_, Util::Array< Data >::cArray(), dataPtr_, isAllocated(), Util::DArray< Data >::isAllocated(), and UTIL_THROW.
capacity()
template<typename Data> int Pscf::DeviceArray< Data >::capacity () const inline
Return allocated capacity.
Returns
Number of elements allocated in array
Definition at line 460 of file DeviceArray.h.
References capacity_.
Referenced by Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqVc(), Pscf::Prdc::Cuda::VecOp::addVcVc(), Pscf::Prdc::Cuda::VecOp::addVcVcVc(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), allocate(), associate(), Pscf::Rpg::VecOpFts::computeDField(), Pscf::Rpg::VecOpFts::computeForceBias(), Pscf::HostDArray< Data >::copySlice(), DeviceArray(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqVc(), Pscf::Prdc::Cuda::VecOp::divSV(), Pscf::Prdc::Cuda::VecOp::divSV(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqVPair(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expVc(), Pscf::Prdc::Cuda::FFTBatched< D >::forwardTransform(), Pscf::Rpg::VecOpFts::fourierMove(), Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::FFTBatched< D >::inverseTransformUnsafe(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Rpg::VecOpFts::mcftsScale(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqVPair(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVVPair(), Pscf::CudaRandom::normal(), Pscf::CudaRandom::normal(), operator=(), Pscf::HostDArray< Data >::operator=(), Pscf::Prdc::Cuda::VecOp::sqNormV(), Pscf::Prdc::Cuda::VecOp::sqSqNormV(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVVS(), Pscf::Prdc::Cuda::Reduce::sum(), Pscf::CudaRandom::uniform(), and Pscf::CudaRandom::uniform().
isAllocated()
template<typename Data> bool Pscf::DeviceArray< Data >::isAllocated () const
Return true if the array has been allocated, false otherwise.
Definition at line 444 of file DeviceArray.h.
References dataPtr_, ownerCapacity_, ownerDataPtr_, ownerPtr_, and UTIL_CHECK.
Referenced by allocate(), associate(), Pscf::HostDArray< Data >::copySlice(), deallocate(), DeviceArray(), dissociate(), Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), operator=(), operator=(), Pscf::HostDArray< Data >::operator=(), Pscf::Prdc::Cuda::Reduce::sum(), and ~DeviceArray().
isOwner()
template<typename Data> bool Pscf::DeviceArray< Data >::isOwner () const inline
Does this object own the underlying data?
Definition at line 467 of file DeviceArray.h.
References dataPtr_, and ownerPtr_.
Referenced by associate(), deallocate(), dissociate(), and ~DeviceArray().
cArray() [1/2]
template<typename Data> Data * Pscf::DeviceArray< Data >::cArray ()
Return pointer to underlying C array.
Definition at line 412 of file DeviceArray.h.
References dataPtr_, ownerCapacity_, ownerDataPtr_, ownerPtr_, and UTIL_CHECK.
Referenced by Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqVc(), Pscf::Prdc::Cuda::VecOp::addVcVc(), Pscf::Prdc::Cuda::VecOp::addVcVcVc(), Pscf::Prdc::Cuda::VecOp::addVMany(), Pscf::Prdc::Cuda::VecOp::addVMany(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), associate(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), Pscf::Rpg::VecOpFts::computeDField(), Pscf::Rpg::VecOpFts::computeForceBias(), Pscf::HostDArray< Data >::copySlice(), DeviceArray(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqVc(), Pscf::Prdc::Cuda::VecOp::divSV(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqVPair(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expVc(), Pscf::Prdc::Cuda::FFTBatched< D >::forwardTransform(), Pscf::Rpg::VecOpFts::fourierMove(), Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::FFTBatched< D >::inverseTransformUnsafe(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Rpg::VecOpFts::mcftsScale(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqVPair(), Pscf::Prdc::Cuda::VecOp::mulVMany(), Pscf::Prdc::Cuda::VecOp::mulVMany(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVVPair(), Pscf::CudaRandom::normal(), Pscf::CudaRandom::normal(), operator=(), Pscf::HostDArray< Data >::operator=(), Pscf::Prdc::Cuda::VecOp::sqNormV(), Pscf::Prdc::Cuda::VecOp::sqSqNormV(), Pscf::Rpg::FilmFieldGenExt< D >::stress(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVVS(), Pscf::Prdc::Cuda::Reduce::sum(), Pscf::CudaRandom::uniform(), and Pscf::CudaRandom::uniform().
cArray() [2/2]
template<typename Data> const Data * Pscf::DeviceArray< Data >::cArray () const
Return const pointer to underlying C array.
Definition at line 428 of file DeviceArray.h.
References dataPtr_, ownerCapacity_, ownerDataPtr_, ownerPtr_, and UTIL_CHECK.
Member Data Documentation
dataPtr_
template<typename Data> Data* Pscf::DeviceArray< Data >::dataPtr_ protected
Pointer to a C array of Data elements on the GPU device.
Definition at line 176 of file DeviceArray.h.
Referenced by allocate(), associate(), cArray(), cArray(), deallocate(), DeviceArray(), DeviceArray(), DeviceArray(), dissociate(), isAllocated(), isOwner(), operator=(), operator=(), and ~DeviceArray().
capacity_
template<typename Data> int Pscf::DeviceArray< Data >::capacity_ protected
Allocated size (capacity) of the array.
Definition at line 179 of file DeviceArray.h.
Referenced by allocate(), associate(), capacity(), deallocate(), DeviceArray(), DeviceArray(), DeviceArray(), dissociate(), operator=(), operator=(), and ~DeviceArray().
ownerPtr_
template<typename Data> DeviceArray<Data> const* Pscf::DeviceArray< Data >::ownerPtr_ protected
Pointer to array that owns this data, if isOwner_ == false.
Used to check that parent array has not been deallocated and/or reallocated.
Definition at line 187 of file DeviceArray.h.
Referenced by allocate(), associate(), cArray(), cArray(), DeviceArray(), DeviceArray(), dissociate(), isAllocated(), and isOwner().
ownerCapacity_
template<typename Data> int Pscf::DeviceArray< Data >::ownerCapacity_ protected
Capacity of parent array, if isOwner_ == false.
Used to check that parent array has not been deallocated and/or reallocated.
Definition at line 195 of file DeviceArray.h.
Referenced by associate(), cArray(), cArray(), DeviceArray(), DeviceArray(), dissociate(), and isAllocated().
ownerDataPtr_
template<typename Data> Data const* Pscf::DeviceArray< Data >::ownerDataPtr_ protected
Const pointer to parent array, if isOwner_ == false.
Used to check that parent array has not been deallocated and/or reallocated.
Definition at line 203 of file DeviceArray.h.
Referenced by associate(), cArray(), cArray(), DeviceArray(), DeviceArray(), dissociate(), and isAllocated().
The documentation for this class was generated from the following file:
DeviceArray.h