PSCF: Pscf::BlockDescriptor Class Reference
Pscf::BlockDescriptor Class Reference
Pscf namespace » Pscf Common » Chemical Structure
Description of a linear homopolymer block within a block polymer.
#include <BlockDescriptor.h>
Public Member Functions
BlockDescriptor ()
Constructor.
virtual ~BlockDescriptor ()
Destructor.
template<class Archive >
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
Setters
void setId (int id)
Set the id for this block.
void setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
void setMonomerId (int monomerId)
Set the monomer type id.
virtual void setLength (double length)
Set the length of this block.
void setPolymerType (PolymerType::Enum type)
Set the polymer type (branched or linear).
Accessors (getters)
int id () const
Get the id of this block.
int monomerId () const
Get the monomer type id.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
double length () const
Get the length (number of monomers) in this block.
PolymerType::Enum polymerType () const
Get the type of the parent polymer (branched or linear).
std::istream & operator>> (std::istream &in, BlockDescriptor &block)
Input stream extractor (>>) for a BlockDescriptor.
std::ostream & operator<< (std::ostream &out, const BlockDescriptor &block)
Output stream inserter (<<) for a BlockDescriptor.
Detailed Description
Description of a linear homopolymer block within a block polymer.
This class defines the block id, monomerId, length and vertexIds of a block within a block polymer. It serves as a base class for the BlockTmpl class template, which is a base class for a class named Block in each implementation level namespace. Each such Block class is thus a subclass of BlockDescriptor.
Block objects associated with a polymer are normally stored in an array named blocks. The id value of each block should be set to the element index of the Block within that array. VertexIds should be set for all blocks in a block polymer before the associated Vertex objects are initialized.
Parameter File Format
Definition at line 39 of file BlockDescriptor.h.
Constructor & Destructor Documentation
BlockDescriptor()
Pscf::BlockDescriptor::BlockDescriptor ()
Constructor.
Definition at line 16 of file BlockDescriptor.cpp.
~BlockDescriptor()
Pscf::BlockDescriptor::~BlockDescriptor () virtual
Destructor.
Definition at line 31 of file BlockDescriptor.cpp.
Member Function Documentation
serialize()
template<class Archive > void Pscf::BlockDescriptor::serialize (Archive & ar, unsigned int versionId)
Serialize to/from archive.
Parameters
ar input or output Archive
versionId archive format version index
Definition at line 256 of file BlockDescriptor.h.
setId()
void Pscf::BlockDescriptor::setId (int id)
Set the id for this block.
Parameters
id integer index for this block
Definition at line 37 of file BlockDescriptor.cpp.
References id().
setVertexIds()
void Pscf::BlockDescriptor::setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
Parameters
vertexAId integer id of vertex A
vertexBId integer id of vertex B
Definition at line 43 of file BlockDescriptor.cpp.
setMonomerId()
void Pscf::BlockDescriptor::setMonomerId (int monomerId)
Set the monomer type id.
Parameters
monomerId integer id of monomer type
Definition at line 52 of file BlockDescriptor.cpp.
References monomerId().
setLength()
void Pscf::BlockDescriptor::setLength (double length) virtual
Set the length of this block.
The ``length" is steric volume / reference volume.
Parameters
length block length (number of monomers).
Reimplemented in Pscf::R1d::Block, Pscf::Rpc::Block< D >, and Pscf::Rpg::Block< D >.
Definition at line 58 of file BlockDescriptor.cpp.
References length().
Referenced by Pscf::R1d::Block::setLength(), Pscf::Rpc::Block< D >::setLength(), and Pscf::Rpg::Block< D >::setLength().
setPolymerType()
void Pscf::BlockDescriptor::setPolymerType (PolymerType::Enum type)
Set the polymer type (branched or linear).
By convention, if the polymer type of a block with block index id is PolymerType::Linear, then vertexId(0) = id and vertexId(1) = id + 1. The stream insertion and extraction operators for a BlockDescriptor can thus use a shorter string representation for linear polymers in in which vertex ids are omitted.
Parameters
type type of polymer (branched or linear)
Definition at line 64 of file BlockDescriptor.cpp.
id()
int Pscf::BlockDescriptor::id () const inline
Get the id of this block.
Definition at line 219 of file BlockDescriptor.h.
Referenced by Pscf::Vertex::addBlock(), and setId().
monomerId()
int Pscf::BlockDescriptor::monomerId () const inline
Get the monomer type id.
Definition at line 225 of file BlockDescriptor.h.
Referenced by setMonomerId().
vertexIds()
const Pair< int > & Pscf::BlockDescriptor::vertexIds () const inline
Get the pair of associated vertex ids.
Definition at line 231 of file BlockDescriptor.h.
vertexId()
int Pscf::BlockDescriptor::vertexId (int i) const inline
Get id of an associated vertex.
Parameters
i index of vertex (0 or 1)
Definition at line 237 of file BlockDescriptor.h.
Referenced by Pscf::Vertex::addBlock().
length()
double Pscf::BlockDescriptor::length () const inline
Get the length (number of monomers) in this block.
Definition at line 243 of file BlockDescriptor.h.
Referenced by Pscf::R1d::Block::setDiscretization(), setLength(), Pscf::R1d::Block::setLength(), and Pscf::R1d::Block::setupSolver().
polymerType()
PolymerType::Enum Pscf::BlockDescriptor::polymerType () const inline
Get the type of the parent polymer (branched or linear).
Definition at line 249 of file BlockDescriptor.h.
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & in, BlockDescriptor & block) friend
Input stream extractor (>>) for a BlockDescriptor.
Different text representations are used for linear and branched polymers, based on the value of the polymerType enumeratin value. Text representation for a branched polymer is:
monomerId length vertexId(0) vertexid(1)
The vertex ids are omitted from the text representation for a linear polymer, because the vertex ids for a linear polymer must be equal to id and id + 1, where id denotes the block id.
The polymerType must be set before a BlockDescriptor can be read from a stream. The block id must be set explicitly by calling setId, rather than read from an istream. Vertex id values for blocks in a linear polymer must be set explicitly by calling setVertexIds with consecutive values, as done in the function Pscf::PolymerTmpl::readParameters.
Parameters
in input stream
block BlockDescriptor to be read from stream
Returns
modified input stream
Definition at line 70 of file BlockDescriptor.cpp.
operator<<
std::ostream & operator<< (std::ostream & out, const BlockDescriptor & block) friend
Output stream inserter (<<) for a BlockDescriptor.
Different text representations are used for linear and branched polymers, as discussed in documentation for the stream extractor (>>) operator. Vertex ids are output only for blocks of branched polymers.
Parameters
out output stream
block BlockDescriptor to be written to stream
Returns
modified output stream
Definition at line 84 of file BlockDescriptor.cpp.
The documentation for this class was generated from the following files:
BlockDescriptor.h
BlockDescriptor.cpp