PSCF: Pscf::Prdc::FilmFieldGenExtBase< D > Class Template Reference
Pscf::Prdc::FilmFieldGenExtBase< D > Class Template Reference abstract
Pscf namespace » Pscf::Prdc - Periodic Systems » Field Utilities
Base class Field Generator for external fields in thin-film systems.
#include <FilmFieldGenExtBase.h>
Public Member Functions
FilmFieldGenExtBase ()
Constructor.
~FilmFieldGenExtBase ()
Destructor.
void readParameters (std::istream &in)
Read parameters and initialize.
bool needsUpdate () const
Check whether system has changed such that the fields need updating.
void checkCompatibility ()
Check that the system is compatible with these fields.
bool hasSymmetricWalls () const
Are the walls chemically identical?
bool isAthermal () const
Are the walls athermal?
GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to the Sweep object.
void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
DArray< double > const & chiBottom () const
Get const chiBottom matrix by reference.
DArray< double > const & chiTop () const
Get const chiTop array by reference.
double chiBottom (int s) const
Get the chi parameter between the bottom wall and species s.
double chiTop (int s) const
Get the chi parameter between the top wall and species s.
int normalVecId () const
Get value of normalVecId.
double interfaceThickness () const
Get value of interfaceThickness.
double excludedThickness () const
Get value of excludedThickness.
virtual double stress (int paramId) const =0
Get contribution to the stress from these external fields.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Public Member Functions inherited from Pscf::Prdc::FieldGenerator
FieldGenerator ()
Constructor.
~FieldGenerator ()
Destructor.
virtual double modifyStress (int paramId, double stress) const
Modify stress to minimize a property other than fHelmholtz.
Public Member Functions inherited from Pscf::FieldGeneratorBase
FieldGeneratorBase ()
Constructor.
~FieldGeneratorBase ()
Destructor.
void generate ()
Checks if fields need to be (re)generated.
Type type () const
Return Type enumeration value (Mask, External, or None)
bool isDependent () const
Is this object dependent on parameters of another FieldGeneratorBase?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Public Member Functions inherited from Pscf::ParameterModifier
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Protected Member Functions
virtual void compute ()=0
Compute the field(s) and store where the System can access.
virtual std::string systemSpaceGroup () const =0
Get the space group name for this system.
virtual RealVec< D > systemLatticeVector (int id) const =0
Get one of the lattice vectors for this system.
virtual int systemNMonomer () const =0
Get the number of monomer species for this system.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
RealVec< D > normalVecCurrent_
The lattice vector normal to the film used to generate these fields.
DArray< double > chiBottomCurrent_
The chiBottom array used to generate the current external fields.
DArray< double > chiTopCurrent_
The chiTop array used to generate the current external fields.
Protected Attributes inherited from Pscf::FieldGeneratorBase
Type type_
Type of field (Mask, External, or None).
bool isDependent_
Is this object dependent on parameters of another FieldGeneratorBase?
Additional Inherited Members
Public Types inherited from Pscf::FieldGeneratorBase
enum Type
Enum representing the type of field (mask, external field, or none).
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<int D>
class Pscf::Prdc::FilmFieldGenExtBase< D >
Base class Field Generator for external fields in thin-film systems.
This is a base class for FilmFieldGenExt that defines all traits of a FilmFieldGenExt that do not require access to the System. System access is needed, for example, to access the mask and set the external fields.
If the user chooses a FilmFieldGenExt object to generate external fields, the external fields will have the same shape as the mask, with a magnitude defined by a Flory–Huggins-like chi parameter. This class is specific to thin-film systems because it also allows for a different chi parameter to be defined on the top boundary than on the bottom, through user input arrays chi_bottom and chi_top. See Thin-Film Confinement for more information.
Definition at line 50 of file FilmFieldGenExtBase.h.
Constructor & Destructor Documentation
FilmFieldGenExtBase()
template<int D> Pscf::Prdc::FilmFieldGenExtBase< D >::FilmFieldGenExtBase ()
Constructor.
Definition at line 26 of file FilmFieldGenExtBase.tpp.
References Pscf::Prdc::FieldGenerator::FieldGenerator(), Pscf::FieldGeneratorBase::isDependent_, and Pscf::FieldGeneratorBase::type_.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::FilmFieldGenExt(), Pscf::Rpc::FilmFieldGenExt< D >::FilmFieldGenExt(), Pscf::Rpg::FilmFieldGenExt< D >::FilmFieldGenExt(), and Pscf::Rpg::FilmFieldGenExt< D >::FilmFieldGenExt().
~FilmFieldGenExtBase()
template<int D> Pscf::Prdc::FilmFieldGenExtBase< D >::~FilmFieldGenExtBase ()
Destructor.
Definition at line 40 of file FilmFieldGenExtBase.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Prdc::FilmFieldGenExtBase< D >::readParameters (std::istream & in) virtual
Read parameters and initialize.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 47 of file FilmFieldGenExtBase.tpp.
References Util::ParamComponent::echo(), Util::ParamComposite::read(), Util::ParamComposite::readDArray(), Util::ParamComposite::readOptional(), Util::ParamComposite::resetParam(), Util::ParamComponent::setEcho(), systemNMonomer(), and UTIL_THROW.
needsUpdate()
template<int D> bool Pscf::Prdc::FilmFieldGenExtBase< D >::needsUpdate () const virtual
Check whether system has changed such that the fields need updating.
Implements Pscf::FieldGeneratorBase.
Definition at line 88 of file FilmFieldGenExtBase.tpp.
References chiBottomCurrent_, chiTopCurrent_, isAthermal(), normalVecCurrent_, systemLatticeVector(), and UTIL_CHECK.
checkCompatibility()
template<int D> void Pscf::Prdc::FilmFieldGenExtBase< D >::checkCompatibility () virtual
Check that the system is compatible with these fields.
The external fields generated by this class have the same functional form and system constraints as the mask, so it is assumed that these checks have already been performed by the object that generated the mask. However, there is one exception: the external fields can have different chi values on top and bottom, which makes the system less symmetric than the mask. If chiBottom != chiTop, this method checks that the space group is compatible with a thin film unit cell with asymmetric walls.
Implements Pscf::FieldGeneratorBase.
Definition at line 122 of file FilmFieldGenExtBase.tpp.
References hasSymmetricWalls(), Pscf::Prdc::SymmetryGroup< Symmetry >::size(), systemSpaceGroup(), and UTIL_THROW.
hasSymmetricWalls()
template<int D> bool Pscf::Prdc::FilmFieldGenExtBase< D >::hasSymmetricWalls () const
Are the walls chemically identical?
This is true if and only if chiBottom is equal to chiTop.
Definition at line 165 of file FilmFieldGenExtBase.tpp.
References systemNMonomer(), and UTIL_CHECK.
Referenced by checkCompatibility().
isAthermal()
template<int D> bool Pscf::Prdc::FilmFieldGenExtBase< D >::isAthermal () const
Are the walls athermal?
This is true only if all values in chiBottom and chiTop are zero.
Definition at line 186 of file FilmFieldGenExtBase.tpp.
References systemNMonomer(), and UTIL_CHECK.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), needsUpdate(), Pscf::Rpc::FilmFieldGenExt< D >::stress(), and Pscf::Rpg::FilmFieldGenExt< D >::stress().
getParameterTypes()
template<int D> GArray< ParameterType > Pscf::Prdc::FilmFieldGenExtBase< D >::getParameterTypes () virtual
Return specialized sweep parameter types to add to the Sweep object.
In this class, the two specialized sweep parameters are chi_top and chi_bottom.
Reimplemented from Pscf::ParameterModifier.
Definition at line 207 of file FilmFieldGenExtBase.tpp.
References Util::GArray< Data >::append().
setParameter() [1/2]
template<int D> void Pscf::Prdc::FilmFieldGenExtBase< D >::setParameter (std::string name, DArray< int > ids, double value, bool & success) virtual
Set the value of a specialized sweep parameter.
In this class, the two specialized sweep parameters are chi_top and chi_bottom.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
value the value to which the parameter is set
success was the attempt to set the parameter successful?
Reimplemented from Pscf::ParameterModifier.
Definition at line 219 of file FilmFieldGenExtBase.tpp.
getParameter() [1/2]
template<int D> double Pscf::Prdc::FilmFieldGenExtBase< D >::getParameter (std::string name, DArray< int > ids, bool & success) const virtual
Get the value of a specialized sweep parameter.
In this class, the two specialized sweep parameters are chi_top and chi_bottom.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
success was the attempt to get the parameter successful?
Reimplemented from Pscf::ParameterModifier.
Definition at line 238 of file FilmFieldGenExtBase.tpp.
chiBottom() [1/2]
template<int D> DArray< double > const & Pscf::Prdc::FilmFieldGenExtBase< D >::chiBottom () const inline
Get const chiBottom matrix by reference.
Definition at line 289 of file FilmFieldGenExtBase.h.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), Pscf::Rpc::FilmFieldGenExt< D >::stress(), and Pscf::Rpg::FilmFieldGenExt< D >::stress().
chiTop() [1/2]
template<int D> DArray< double > const & Pscf::Prdc::FilmFieldGenExtBase< D >::chiTop () const inline
Get const chiTop array by reference.
Definition at line 294 of file FilmFieldGenExtBase.h.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), Pscf::Rpc::FilmFieldGenExt< D >::stress(), and Pscf::Rpg::FilmFieldGenExt< D >::stress().
chiBottom() [2/2]
template<int D> double Pscf::Prdc::FilmFieldGenExtBase< D >::chiBottom (int s) const inline
Get the chi parameter between the bottom wall and species s.
Parameters
s species index, 0 <= id < nVertex
Definition at line 299 of file FilmFieldGenExtBase.h.
chiTop() [2/2]
template<int D> double Pscf::Prdc::FilmFieldGenExtBase< D >::chiTop (int s) const inline
Get the chi parameter between the top wall and species s.
Parameters
s species index, 0 <= id < nVertex
Definition at line 304 of file FilmFieldGenExtBase.h.
normalVecId()
template<int D> int Pscf::Prdc::FilmFieldGenExtBase< D >::normalVecId () const inline
Get value of normalVecId.
Definition at line 309 of file FilmFieldGenExtBase.h.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), Pscf::Rpc::FilmFieldGenExt< D >::stress(), and Pscf::Rpg::FilmFieldGenExt< D >::stress().
interfaceThickness()
template<int D> double Pscf::Prdc::FilmFieldGenExtBase< D >::interfaceThickness () const inline
Get value of interfaceThickness.
Definition at line 314 of file FilmFieldGenExtBase.h.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::stress(), and Pscf::Rpg::FilmFieldGenExt< D >::stress().
excludedThickness()
template<int D> double Pscf::Prdc::FilmFieldGenExtBase< D >::excludedThickness () const inline
Get value of excludedThickness.
Definition at line 319 of file FilmFieldGenExtBase.h.
stress()
template<int D> virtual double Pscf::Prdc::FilmFieldGenExtBase< D >::stress (int paramId) const pure virtual
Get contribution to the stress from these external fields.
The external fields defined by this class change in a non-affine manner upon changing the lattice parameter corresponding to normalVecId. Thus, if this lattice parameter is allowed to be flexible, the "stress" used to optimize the parameter must contain an additional term arising from the external fields. This method evaluates this term and returns its value. Access to various System properties is required, so the method must be implemented by subclasses.
Parameters
paramId index of the lattice parameter being varied
Reimplemented from Pscf::Prdc::FieldGenerator.
Implemented in Pscf::Rpc::FilmFieldGenExt< D >, and Pscf::Rpg::FilmFieldGenExt< D >.
References Pscf::ParameterModifier::getParameter(), and Pscf::ParameterModifier::setParameter().
compute()
template<int D> virtual void Pscf::Prdc::FilmFieldGenExtBase< D >::compute () protected pure virtual
Compute the field(s) and store where the System can access.
Implements Pscf::FieldGeneratorBase.
Implemented in Pscf::Rpc::FilmFieldGenExt< D >, and Pscf::Rpg::FilmFieldGenExt< D >.
systemSpaceGroup()
template<int D> virtual std::string Pscf::Prdc::FilmFieldGenExtBase< D >::systemSpaceGroup () const protected pure virtual
Get the space group name for this system.
Implemented in Pscf::Rpc::FilmFieldGenExt< D >, and Pscf::Rpg::FilmFieldGenExt< D >.
Referenced by checkCompatibility().
systemLatticeVector()
template<int D> virtual RealVec< D > Pscf::Prdc::FilmFieldGenExtBase< D >::systemLatticeVector (int id) const protected pure virtual
Get one of the lattice vectors for this system.
Parameters
id index of the desired lattice vector
Implemented in Pscf::Rpc::FilmFieldGenExt< D >, and Pscf::Rpg::FilmFieldGenExt< D >.
Referenced by needsUpdate().
systemNMonomer()
template<int D> virtual int Pscf::Prdc::FilmFieldGenExtBase< D >::systemNMonomer () const protected pure virtual
Get the number of monomer species for this system.
Implemented in Pscf::Rpc::FilmFieldGenExt< D >, and Pscf::Rpg::FilmFieldGenExt< D >.
Referenced by hasSymmetricWalls(), isAthermal(), and readParameters().
setParameter() [2/2]
template<int D> void Pscf::ParameterModifier::setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
This is an overloaded version of the setParameter method above, which should be used only when the caller is certain that the specialized sweep parameter belongs to this ParameterModifier. An error will be thrown if the specialized parameter is not settable using this class.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
value the value to which the parameter is set
Definition at line 122 of file ParameterModifier.cpp.
getParameter() [2/2]
template<int D> double Pscf::ParameterModifier::getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
This is an overloaded version of the getParameter method above, which should be used only when the caller is certain that the specialized sweep parameter belongs to this ParameterModifier. An error will be thrown if the specialized parameter is not gettable using this class.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
Definition at line 136 of file ParameterModifier.cpp.
Member Data Documentation
normalVecCurrent_
template<int D> RealVec<D> Pscf::Prdc::FilmFieldGenExtBase< D >::normalVecCurrent_ protected
The lattice vector normal to the film used to generate these fields.
This vector is set to be equal to the system's lattice vector with index normalVecId_ each time the external fields are generated. The system's lattice vectors may then change, and this normalVecCurrent_ vector is used to detect whether they have changed. This is used to decide whether a new set of external fields needs to be generated.
Definition at line 231 of file FilmFieldGenExtBase.h.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), and needsUpdate().
chiBottomCurrent_
template<int D> DArray<double> Pscf::Prdc::FilmFieldGenExtBase< D >::chiBottomCurrent_ protected
The chiBottom array used to generate the current external fields.
This array is set to be equal to chiBottom_ each time the external fields are generated. The chiBottom array may then be changed via the setParameter method, and this chiBottomCurrent_ array is used to detect whether they have changed. This is used to determine whether a new set of external fields needs to be generated.
Definition at line 242 of file FilmFieldGenExtBase.h.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), and needsUpdate().
chiTopCurrent_
template<int D> DArray<double> Pscf::Prdc::FilmFieldGenExtBase< D >::chiTopCurrent_ protected
The chiTop array used to generate the current external fields.
This array is set to be equal to chiTop_ each time the external fields are generated. The chiTop array may then be changed via the setParameter method, and this chiTopCurrent_ array is used to detect whether they have changed. This is used to determine whether a new set of external fields needs to be generated.
Definition at line 253 of file FilmFieldGenExtBase.h.
Referenced by Pscf::Rpc::FilmFieldGenExt< D >::compute(), Pscf::Rpg::FilmFieldGenExt< D >::compute(), and needsUpdate().
The documentation for this class was generated from the following files:
FilmFieldGenExtBase.h
FilmFieldGenExtBase.tpp