PSCF: Pscf::Rpg::Domain< D > Class Template Reference
Pscf::Rpg::Domain< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Fields
Spatial domain for a periodic structure with real fields, on a GPU.
#include <Domain.h>
Public Types
using Base = DomainTmpl< D, FFT<D>, WaveList<D>, FieldIo<D> >
Typename alias base class.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Domain ()
Constructor.
void setFileMaster (FileMaster &fileMaster)
Create association with a FileMaster, needed by FieldIo.
virtual void readParameters (std::istream &in)
Read body of parameter block (without opening and closing lines).
void readRGridFieldHeader (std::istream &in, int &nMonomer)
Read initialization data from header of an r-grid field file.
void makeBasis ()
Construct basis if not done already.
UnitCell< D > & unitCell ()
Get the UnitCell by non-const reference.
UnitCell< D > const & unitCell () const
Get the UnitCell by const reference.
Mesh< D > & mesh ()
Get the Mesh by non-const reference.
Mesh< D > const & mesh () const
Get the Mesh by const reference.
SpaceGroup< D > const & group () const
Get the SpaceGroup by const reference.
Basis< D > & basis ()
Get the Basis object by non-const reference.
Basis< D > const & basis () const
Get the Basis by const reference.
FFT & fft ()
Get the FFT by non-const reference.
FFT const & fft () const
Get the FFT object by non-const reference.
WaveList< D > & waveList ()
Get the WaveList by non-const reference.
WaveList< D > const & waveList () const
Get the WaveList by const reference.
FieldIo< D > & fieldIo ()
Get the FieldIo by non-const reference.
FieldIo< D > const & fieldIo () const
Get the FieldIo by const reference.
UnitCell< D >::LatticeSystem lattice () const
Get the lattice system (enumeration value).
std::string groupName () const
Get the group name.
bool hasGroup () const
Has a space group been declared?
bool hasBasis () const
Has a symmetry-adapted Fourier basis been initialized?
void writeStars (std::string const &filename) const
Output information about stars and symmetrized basis functions.
void writeWaves (std::string const &filename) const
Output information about waves.
void writeGroup (std::string const &filename) const
Output all elements of the space group.
Public Member Functions inherited from Pscf::Prdc::DomainTmpl< D, FFT< D >, WaveList< D >, FieldIo< D > >
DomainTmpl ()
Constructor.
~DomainTmpl ()
Destructor.
void setFileMaster (FileMaster &fileMaster)
Create association with a FileMaster, needed by FieldIo.
void readRGridFieldHeader (std::istream &in, int &nMonomer)
Read initialization data from header of an r-grid field file.
void makeBasis ()
Construct basis if not done already.
Mesh< D > & mesh ()
Get the Mesh by non-const reference.
Mesh< D > const & mesh () const
Get the Mesh by const reference.
UnitCell< D > & unitCell ()
Get the UnitCell by non-const reference.
UnitCell< D > const & unitCell () const
Get the UnitCell by const reference.
SpaceGroup< D > const & group () const
Get the SpaceGroup by const reference.
Basis< D > & basis ()
Get the Basis object by non-const reference.
Basis< D > const & basis () const
Get the Basis by const reference.
FFT & fft ()
Get the FFT by non-const reference.
FFT const & fft () const
Get the FFT object by non-const reference.
WaveList< D > & waveList ()
Get the WaveList by non-const reference.
WaveList< D > const & waveList () const
Get the WaveList by const reference.
FieldIo< D > & fieldIo ()
Get the FieldIo by non-const reference.
FieldIo< D > const & fieldIo () const
Get the FieldIo by const reference.
UnitCell< D >::LatticeSystem lattice () const
Get the lattice system (enumeration value).
std::string groupName () const
Get the group name.
bool hasGroup () const
Has a space group been declared?
bool hasBasis () const
Has a symmetry-adapted Fourier basis been initialized?
void writeWaves (std::string const &filename) const
Output information about waves.
void writeStars (std::string const &filename) const
Output information about stars and symmetrized basis functions.
void writeGroup (std::string const &filename) const
Output all elements of the space group.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
template<int D>
class Pscf::Rpg::Domain< D >
Spatial domain for a periodic structure with real fields, on a GPU.
See the interface of the Prdc::DomainTmpl base class template for complete API documentation. The Rpg::Domain class template is basically a named partial specialization of the base class template, defined using template type parameters FFT = Prdc::Cuda::FFT<D>, WLT = Prdc::Cuda::WaveList<D>, and FIT = Rpg::FieldIo<D> . The public interface is identical to that of the base class.
Definition at line 59 of file rpg/field/Domain.h.
Member Typedef Documentation
Base
template<int D> using Pscf::Rpg::Domain< D >::Base = DomainTmpl< D, FFT<D>, WaveList<D>, FieldIo<D> >
Typename alias base class.
Definition at line 73 of file rpg/field/Domain.h.
Constructor & Destructor Documentation
Domain()
template<int D> Pscf::Rpg::Domain< D >::Domain ()
Constructor.
Sets the class name used in the parameter file to "Domain".
Definition at line 29 of file rpg/field/Domain.tpp.
References Pscf::Prdc::DomainTmpl< D, FFT< D >, WaveList< D >, FieldIo< D > >::DomainTmpl(), and Util::ParamComposite::setClassName().
Member Function Documentation
setFileMaster()
template<int D> void Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::setFileMaster (FileMaster & fileMaster)
Create association with a FileMaster, needed by FieldIo.
Parameters
fileMaster associated FileMaster object.
readParameters()
template<int D> virtual void Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::readParameters (std::istream & in) virtual
Read body of parameter block (without opening and closing lines).
Parameters
in input parameter stream
Reimplemented from Pscf::Prdc::DomainTmpl< D, FFT< D >, WaveList< D >, FieldIo< D > >.
readRGridFieldHeader()
template<int D> void Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::readRGridFieldHeader (std::istream & in, int & nMonomer)
Read initialization data from header of an r-grid field file.
This is an alternative to reading the parameter file that is only used for unit testing.
Parameters
in input parameter stream
nMonomer number of monomers in field file (output)
makeBasis()
template<int D> void Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::makeBasis ()
Construct basis if not done already.
unitCell() [1/2]
template<int D> UnitCell< D > & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::unitCell ()
Get the UnitCell by non-const reference.
Referenced by Pscf::Rpg::Simulator< D >::computeHamiltonian(), Pscf::Rpg::ConcentrationWriter< D >::writeFrame(), Pscf::Rpg::TrajectoryWriter< D >::writeFrame(), and Pscf::Rpg::ConcentrationWriter< D >::writeHeader().
unitCell() [2/2]
template<int D> UnitCell< D > const & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::unitCell () const
Get the UnitCell by const reference.
mesh() [1/2]
template<int D> Mesh< D > & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::mesh ()
Get the Mesh by non-const reference.
Referenced by Pscf::Rpg::Simulator< D >::computeHamiltonian().
mesh() [2/2]
template<int D> Mesh< D > const & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::mesh () const
Get the Mesh by const reference.
group()
template<int D> SpaceGroup< D > const & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::group () const
Get the SpaceGroup by const reference.
basis() [1/2]
template<int D> Basis< D > & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::basis ()
Get the Basis object by non-const reference.
basis() [2/2]
template<int D> Basis< D > const & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::basis () const
Get the Basis by const reference.
fft() [1/2]
template<int D> FFT & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::fft ()
Get the FFT by non-const reference.
fft() [2/2]
template<int D> FFT const & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::fft () const
Get the FFT object by non-const reference.
waveList() [1/2]
template<int D> WaveList< D > & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::waveList ()
Get the WaveList by non-const reference.
waveList() [2/2]
template<int D> WaveList< D > const & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::waveList () const
Get the WaveList by const reference.
fieldIo() [1/2]
template<int D> FieldIo< D > & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::fieldIo ()
Get the FieldIo by non-const reference.
Referenced by Pscf::Rpg::ConcentrationWriter< D >::writeFrame(), Pscf::Rpg::TrajectoryWriter< D >::writeFrame(), and Pscf::Rpg::ConcentrationWriter< D >::writeHeader().
fieldIo() [2/2]
template<int D> FieldIo< D > const & Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::fieldIo () const
Get the FieldIo by const reference.
lattice()
template<int D> UnitCell< D >::LatticeSystem Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::lattice () const
Get the lattice system (enumeration value).
groupName()
template<int D> std::string Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::groupName () const
Get the group name.
hasGroup()
template<int D> bool Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::hasGroup () const
Has a space group been declared?
hasBasis()
template<int D> bool Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::hasBasis () const
Has a symmetry-adapted Fourier basis been initialized?
writeStars()
template<int D> void Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::writeStars (std::string const & filename) const
Output information about stars and symmetrized basis functions.
This function opens a file with the specified filename, calls Basis<D>::outputStars, and closes the file before returning.
Parameters
filename name of output file
writeWaves()
template<int D> void Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::writeWaves (std::string const & filename) const
Output information about waves.
This function opens a file with the specified filename, calls Basis<D>::outputWaves, and closes the file before returning.
Parameters
filename name of output file
writeGroup()
template<int D> void Pscf::Prdc::DomainTmpl< D, FFT, WaveList< D >, FieldIo< D > >::writeGroup (std::string const & filename) const
Output all elements of the space group.
Parameters
filename name of output file
The documentation for this class was generated from the following files:
rpg/field/Domain.h
rpg/field/Domain.tpp