PSCF: Pscf::FloryHuggins::Clump Class Reference
Pscf::FloryHuggins::Clump Class Reference
Pscf namespace » Pscf Common » Flory-Huggins Theory
All monomers of a specific monomer type in a molecule.
#include <Clump.h>
Public Member Functions
Clump ()
Constructor.
template<class Archive>
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
Setters
void setMonomerId (int monomerId)
Set the monomer type id.
void setSize (double size)
Set the size of this clump.
Accessors
int monomerId () const
Get the monomer type id.
double size () const
Get the size (number of monomers) in this block.
std::istream & operator>> (std::istream &in, Clump &block)
istream extractor for a Clump.
std::ostream & operator<< (std::ostream &out, const Clump &block)
ostream inserter for a Clump.
Detailed Description
All monomers of a specific monomer type in a molecule.
A clump has a monomer id and a size. The size of a clump is the volume occupied by all monomers of the specified type in a particular molecular species, divided by a monomer reference volume.
For a block copolymer, a clump is generally different than a block because a clump may include the monomers in two or more blocks of the same monomer type. Hompolymer and point solvent molecular species each have only one clump.
Definition at line 35 of file Clump.h.
Constructor & Destructor Documentation
Clump()
Pscf::FloryHuggins::Clump::Clump ()
Constructor.
Definition at line 16 of file Clump.cpp.
Referenced by operator<<, and operator>>.
Member Function Documentation
serialize()
template<class Archive> void Pscf::FloryHuggins::Clump::serialize (Archive & ar, unsigned int versionId)
Serialize to/from archive.
Parameters
ar input or output Archive
versionId archive format version index
Definition at line 140 of file Clump.h.
setMonomerId()
void Pscf::FloryHuggins::Clump::setMonomerId (int monomerId)
Set the monomer type id.
Parameters
monomerId integer id of monomer type (>=0)
Definition at line 24 of file Clump.cpp.
References monomerId().
Referenced by Pscf::FloryHuggins::Mixture::initialize().
setSize()
void Pscf::FloryHuggins::Clump::setSize (double size)
Set the size of this clump.
The ``size" is steric volume / reference volume.
Parameters
size clump size (volume / monomer volume)
Definition at line 30 of file Clump.cpp.
References size().
Referenced by Pscf::FloryHuggins::Mixture::initialize().
monomerId()
int Pscf::FloryHuggins::Clump::monomerId () const inline
Get the monomer type id.
Definition at line 127 of file Clump.h.
Referenced by Pscf::FloryHuggins::Mixture::computeMu(), Pscf::FloryHuggins::Mixture::computePhi(), setMonomerId(), and Pscf::FloryHuggins::Mixture::validate().
size()
double Pscf::FloryHuggins::Clump::size () const inline
Get the size (number of monomers) in this block.
Definition at line 133 of file Clump.h.
Referenced by Pscf::FloryHuggins::Mixture::computeMu(), Pscf::FloryHuggins::Mixture::computePhi(), and setSize().
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & in, Clump & block) friend
istream extractor for a Clump.
Parameters
in input stream
block Clump to be read from stream
Returns
modified input stream
Definition at line 36 of file Clump.cpp.
References Clump().
operator<<
std::ostream & operator<< (std::ostream & out, const Clump & block) friend
ostream inserter for a Clump.
Parameters
out output stream
block Clump to be written to stream
Returns
modified output stream
Definition at line 46 of file Clump.cpp.
References Clump().
The documentation for this class was generated from the following files:
Clump.h
Clump.cpp