PSCF: Util::DSArray< Data > Class Template Reference
Util::DSArray< Data > Class Template Reference
Util namespace » Container Templates » Object Arrays
Dynamically allocated array with variable logical size.
#include <DSArray.h>
Public Member Functions
DSArray ()
Constructor.
DSArray (DSArray< Data > const &other)
Copy constructor.
DSArray< Data > & operator= (DSArray< Data > const &other)
Assignment, element by element.
virtual ~DSArray ()
Destructor.
void allocate (int capacity)
Allocates the underlying C array.
void append (Data const &data)
Append data to the end of the array.
void resize (int size)
Modify logical size without modifying data.
void clear ()
Set logical size to zero.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize a DSArray to/from an Archive.
void begin (ArrayIterator< Data > &iterator)
Set an ArrayIterator to the beginning of this Array.
void begin (ConstArrayIterator< Data > &iterator) const
Set a ConstArrayIterator to the beginning of this Array.
Data & operator[] (int i)
Mimic C array subscripting.
Data const & operator[] (int i) const
Mimic C array subscripting.
int capacity () const
Return physical capacity of array.
int size () const
Return logical size of this array (i.e., number of elements).
bool isAllocated () const
Return true if the DSArray has been allocated, false otherwise.
Protected Attributes
Data * data_
C array of Data elements.
int size_
Logical size of array (number of elements used).
int capacity_
Capacity (physical size) of underlying C array.
Detailed Description
template<typename Data>
class Util::DSArray< Data >
Dynamically allocated array with variable logical size.
A DSArray < Data > is a wrapper for a dynamically allocated C array, with continuous elements and a logical size that may be less than or equal to its physical capacity. The logical size is the number of contiguous elements that have been added using the append() method.
Definition at line 30 of file DSArray.h.
Constructor & Destructor Documentation
DSArray() [1/2]
template<class Data> Util::DSArray< Data >::DSArray ()
Constructor.
Definition at line 170 of file DSArray.h.
References capacity_, data_, and size_.
Referenced by DSArray(), and operator=().
DSArray() [2/2]
template<class Data> Util::DSArray< Data >::DSArray (DSArray< Data > const & other)
Copy constructor.
Parameters
other the DSArray to be copied.
Definition at line 180 of file DSArray.h.
References Util::Memory::allocate(), capacity_, data_, DSArray(), isAllocated(), and size_.
~DSArray()
template<class Data> Util::DSArray< Data >::~DSArray () virtual
Destructor.
Definition at line 233 of file DSArray.h.
References capacity_, data_, Util::Memory::deallocate(), isAllocated(), and size_.
Member Function Documentation
operator=()
template<class Data> DSArray< Data > & Util::DSArray< Data >::operator= (DSArray< Data > const & other)
Assignment, element by element.
Capacity of LHS must be either zero or equal that of RHS DSArray.
Parameters
other the RHS DSArray
Definition at line 204 of file DSArray.h.
References allocate(), capacity_, data_, DSArray(), isAllocated(), size_, and UTIL_THROW.
allocate()
template<class Data> void Util::DSArray< Data >::allocate (int capacity)
Allocates the underlying C array.
Throw an exception if the DSArray has already been allocated - A DSArray can only be allocated once.
Parameters
capacity number of elements to allocate
Definition at line 247 of file DSArray.h.
References Util::Memory::allocate(), capacity(), capacity_, data_, isAllocated(), size_, and UTIL_THROW.
Referenced by operator=(), and serialize().
append()
template<class Data> void Util::DSArray< Data >::append (Data const & data) inline
Append data to the end of the array.
Parameters
data Data to add to end of array.
Definition at line 345 of file DSArray.h.
References capacity_, data_, size_, and UTIL_THROW.
resize()
template<class Data> void Util::DSArray< Data >::resize (int size) inline
Modify logical size without modifying data.
The size parameter must be non-negative and may not exceed the physical allocated capacity.
This function simply changes the logical size without modifying any elements of the underlying physical array. When the size increases, added elements are uninitialized.
Parameters
size new logical size, 0 <= size < capacity.
Definition at line 365 of file DSArray.h.
References size(), and size_.
clear()
template<class Data> void Util::DSArray< Data >::clear () inline
Set logical size to zero.
Definition at line 372 of file DSArray.h.
References size_.
serialize()
template<class Data> template<class Archive> void Util::DSArray< Data >::serialize (Archive & ar, const unsigned int version)
Serialize a DSArray to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 265 of file DSArray.h.
References allocate(), capacity(), capacity_, data_, isAllocated(), size_, and UTIL_THROW.
begin() [1/2]
template<class Data> void Util::DSArray< Data >::begin (ArrayIterator< Data > & iterator) inline
Set an ArrayIterator to the beginning of this Array.
Parameters
iterator ArrayIterator, initialized on output.
Definition at line 302 of file DSArray.h.
References data_, Util::ArrayIterator< Data >::setCurrent(), Util::ArrayIterator< Data >::setEnd(), and size_.
begin() [2/2]
template<class Data> void Util::DSArray< Data >::begin (ConstArrayIterator< Data > & iterator) const inline
Set a ConstArrayIterator to the beginning of this Array.
Parameters
iterator ConstArrayIterator, initialized on output.
Definition at line 313 of file DSArray.h.
References data_, Util::ConstArrayIterator< Data >::setCurrent(), Util::ConstArrayIterator< Data >::setEnd(), and size_.
operator[]() [1/2]
template<class Data> Data & Util::DSArray< Data >::operator[] (int i) inline
Mimic C array subscripting.
Parameters
i array index
Returns
reference to element i
Definition at line 323 of file DSArray.h.
References data_, and size_.
operator[]() [2/2]
template<class Data> Data const & Util::DSArray< Data >::operator[] (int i) const inline
Mimic C array subscripting.
Parameters
i array index
Returns
const reference to element i
Definition at line 334 of file DSArray.h.
References data_, and size_.
capacity()
template<class Data> int Util::DSArray< Data >::capacity () const inline
Return physical capacity of array.
Definition at line 379 of file DSArray.h.
References capacity_.
Referenced by allocate(), and serialize().
size()
template<class Data> int Util::DSArray< Data >::size () const inline
Return logical size of this array (i.e., number of elements).
Definition at line 386 of file DSArray.h.
References size_.
Referenced by resize().
isAllocated()
template<class Data> bool Util::DSArray< Data >::isAllocated () const inline
Return true if the DSArray has been allocated, false otherwise.
Definition at line 393 of file DSArray.h.
References data_.
Referenced by allocate(), DSArray(), operator=(), serialize(), and ~DSArray().
Member Data Documentation
data_
template<typename Data> Data* Util::DSArray< Data >::data_ protected
C array of Data elements.
Definition at line 154 of file DSArray.h.
Referenced by allocate(), append(), begin(), begin(), DSArray(), DSArray(), isAllocated(), operator=(), operator[](), operator[](), serialize(), and ~DSArray().
size_
template<typename Data> int Util::DSArray< Data >::size_ protected
Logical size of array (number of elements used).
Definition at line 157 of file DSArray.h.
Referenced by allocate(), append(), begin(), begin(), clear(), DSArray(), DSArray(), operator=(), operator[](), operator[](), resize(), serialize(), size(), and ~DSArray().
capacity_
template<typename Data> int Util::DSArray< Data >::capacity_ protected
Capacity (physical size) of underlying C array.
Definition at line 160 of file DSArray.h.
Referenced by allocate(), append(), capacity(), DSArray(), DSArray(), operator=(), serialize(), and ~DSArray().
The documentation for this class was generated from the following file:
DSArray.h