PSCF: Pscf::Prdc::SystemConstRefReal< ST > Class Template Reference
Pscf::Prdc::SystemConstRefReal< ST > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems
Const access to main components of an associated System.
#include <SystemConstRefReal.h>
Public Member Functions
SystemConstRefReal ()
Default constructor.
SystemConstRefReal (SystemT const &system)
Constructor.
~SystemConstRefReal ()
Destructor.
void associate (SystemT const &system)
Create associations with a system and its components.
SystemT const & system () const
Get the associated System.
MixtureT const & mixture () const
Get the Mixture.
InteractionT const & interaction () const
Get the Interaction.
DomainT const & domain () const
Get the Domain.
CFieldContainerT const & c () const
Get the concentration (c) field container.
WFieldContainerT const & w () const
Get the chemical potential (w) field container.
WFieldContainerT const & h () const
Get the external potential (h) field container.
MaskT const & mask () const
Get the mask.
FileMaster const & fileMaster () const
Get the FileMaster.
Detailed Description
template<class ST>
class Pscf::Prdc::SystemConstRefReal< ST >
Const access to main components of an associated System.
A SystemConstRefReal holds read-only (const) pointers to an associated System object (type parameter ST) and several of its primary components, for a model with real fields and periodic boundary conditions. Accessor functions return the system and its components as const references.
Definition at line 32 of file SystemConstRefReal.h.
Constructor & Destructor Documentation
SystemConstRefReal() [1/2]
template<class ST> Pscf::Prdc::SystemConstRefReal< ST >::SystemConstRefReal ()
Default constructor.
Definition at line 20 of file SystemConstRefReal.tpp.
Referenced by Pscf::Prdc::ScftReal< D, ST >::ScftReal().
SystemConstRefReal() [2/2]
template<class ST> Pscf::Prdc::SystemConstRefReal< ST >::SystemConstRefReal (SystemT const & system)
Constructor.
Definition at line 36 of file SystemConstRefReal.tpp.
References associate(), and system().
~SystemConstRefReal()
template<class ST> Pscf::Prdc::SystemConstRefReal< ST >::~SystemConstRefReal ()
Destructor.
Definition at line 52 of file SystemConstRefReal.tpp.
Member Function Documentation
associate()
template<class ST> void Pscf::Prdc::SystemConstRefReal< ST >::associate (SystemT const & system)
Create associations with a system and its components.
Definition at line 56 of file SystemConstRefReal.tpp.
References system().
Referenced by SystemConstRefReal().
system()
template<class ST> SystemT const & Pscf::Prdc::SystemConstRefReal< ST >::system () const inline
Get the associated System.
Definition at line 70 of file SystemConstRefReal.h.
Referenced by associate(), and SystemConstRefReal().
mixture()
template<class ST> MixtureT const & Pscf::Prdc::SystemConstRefReal< ST >::mixture () const inline
Get the Mixture.
Definition at line 74 of file SystemConstRefReal.h.
interaction()
template<class ST> InteractionT const & Pscf::Prdc::SystemConstRefReal< ST >::interaction () const inline
Get the Interaction.
Definition at line 78 of file SystemConstRefReal.h.
domain()
template<class ST> DomainT const & Pscf::Prdc::SystemConstRefReal< ST >::domain () const inline
Get the Domain.
Definition at line 82 of file SystemConstRefReal.h.
c()
template<class ST> CFieldContainerT const & Pscf::Prdc::SystemConstRefReal< ST >::c () const inline
Get the concentration (c) field container.
Definition at line 86 of file SystemConstRefReal.h.
w()
template<class ST> WFieldContainerT const & Pscf::Prdc::SystemConstRefReal< ST >::w () const inline
Get the chemical potential (w) field container.
Definition at line 90 of file SystemConstRefReal.h.
h()
template<class ST> WFieldContainerT const & Pscf::Prdc::SystemConstRefReal< ST >::h () const inline
Get the external potential (h) field container.
Definition at line 94 of file SystemConstRefReal.h.
mask()
template<class ST> MaskT const & Pscf::Prdc::SystemConstRefReal< ST >::mask () const inline
Get the mask.
Definition at line 98 of file SystemConstRefReal.h.
fileMaster()
template<class ST> FileMaster const & Pscf::Prdc::SystemConstRefReal< ST >::fileMaster () const inline
Get the FileMaster.
Definition at line 102 of file SystemConstRefReal.h.
The documentation for this class was generated from the following files:
SystemConstRefReal.h
SystemConstRefReal.tpp