PSCF: Pscf::Prdc::FilmFieldGenMaskBase< D > Class Template Reference
Pscf::Prdc::FilmFieldGenMaskBase< D > Class Template Reference abstract
Pscf namespace » Pscf::Prdc - Periodic Systems » Field Utilities
Base class Field Generator for thin-film masks.
#include <FilmFieldGenMaskBase.h>
Public Member Functions
FilmFieldGenMaskBase ()
Constructor.
~FilmFieldGenMaskBase ()
Destructor.
void readParameters (std::istream &in)
Read parameter file block and initialize.
bool needsUpdate () const
Check whether system has changed such that the field needs updating.
void checkCompatibility ()
Check that the system is compatible with this field.
int normalVecId () const
Get value of normalVecId.
double interfaceThickness () const
Get value of interfaceThickness.
double excludedThickness () const
Get value of excludedThickness.
double fBulk () const
Get value of fBulk.
bool hasFBulk () const
Check whether a value of fBulk was provided.
virtual double stress (int paramId) const =0
Get contribution to the stress from this mask.
virtual double modifyStress (int paramId, double stress) const =0
Modify stress value in direction normal to the film.
Public Member Functions inherited from Pscf::Prdc::FieldGenerator
FieldGenerator ()
Constructor.
~FieldGenerator ()
Destructor.
Public Member Functions inherited from Pscf::FieldGeneratorBase
FieldGeneratorBase ()
Constructor.
~FieldGeneratorBase ()
Destructor.
void generate ()
Checks if fields need to be (re)generated.
Type type () const
Return Type enumeration value (Mask, External, or None)
bool isDependent () const
Is this object dependent on parameters of another FieldGeneratorBase?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Public Member Functions inherited from Pscf::ParameterModifier
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
virtual GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to the Sweep object.
virtual void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
virtual double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Protected Member Functions
virtual void compute ()=0
Compute the field and store where the System can access.
void checkSpaceGroup () const
Check that space group is compatible with the mask.
void checkLatticeVectors () const
Check that lattice vectors are compatible with thin film constraint.
FSArray< bool, 6 > modifyFlexibleParams (FSArray< bool, 6 > current, UnitCell< D > const &cell) const
Modifies a flexibleParams array to be compatible with this mask.
virtual void setFlexibleParams () const =0
Sets iterator's flexibleParams array to be compatible with the mask.
virtual std::string systemSpaceGroup () const =0
Get the space group name for this system.
virtual RealVec< D > systemLatticeVector (int id) const =0
Get one of the lattice vectors for this system.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
RealVec< D > normalVecCurrent_
The lattice vector normal to the film used to generate these fields.
double fBulk_
Reference free energy used to calculate stress normal to the film.
Protected Attributes inherited from Pscf::FieldGeneratorBase
Type type_
Type of field (Mask, External, or None).
bool isDependent_
Is this object dependent on parameters of another FieldGeneratorBase?
Additional Inherited Members
Public Types inherited from Pscf::FieldGeneratorBase
enum Type
Enum representing the type of field (mask, external field, or none).
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<int D>
class Pscf::Prdc::FilmFieldGenMaskBase< D >
Base class Field Generator for thin-film masks.
This is a base class for FilmFieldGenMask that defines all traits of a FilmFieldGenMask that do not require access to the System (System access is needed, for example, to get the space group and set the mask field).
If the user chooses a FilmFieldGenMask object to construct the mask, then the system will contain two parallel hard surfaces ("walls"), confining the polymers/solvents to a "thin film" region of the unit cell. The shape of the mask is defined by three input parameters: normalVecId, excludedThickness, and interfaceThickness. See Thin-Film Confinement for more information.
Definition at line 39 of file FilmFieldGenMaskBase.h.
Constructor & Destructor Documentation
FilmFieldGenMaskBase()
template<int D> Pscf::Prdc::FilmFieldGenMaskBase< D >::FilmFieldGenMaskBase ()
Constructor.
Definition at line 26 of file FilmFieldGenMaskBase.tpp.
References fBulk_, Pscf::Prdc::FieldGenerator::FieldGenerator(), normalVecCurrent_, and Pscf::FieldGeneratorBase::type_.
Referenced by Pscf::Rpc::FilmFieldGenMask< D >::FilmFieldGenMask(), Pscf::Rpc::FilmFieldGenMask< D >::FilmFieldGenMask(), Pscf::Rpg::FilmFieldGenMask< D >::FilmFieldGenMask(), and Pscf::Rpg::FilmFieldGenMask< D >::FilmFieldGenMask().
~FilmFieldGenMaskBase()
template<int D> Pscf::Prdc::FilmFieldGenMaskBase< D >::~FilmFieldGenMaskBase ()
Destructor.
Definition at line 43 of file FilmFieldGenMaskBase.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Prdc::FilmFieldGenMaskBase< D >::readParameters (std::istream & in) virtual
Read parameter file block and initialize.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 50 of file FilmFieldGenMaskBase.tpp.
References fBulk_, Util::Parameter::isActive(), read(), readOptional(), and UTIL_THROW.
needsUpdate()
template<int D> bool Pscf::Prdc::FilmFieldGenMaskBase< D >::needsUpdate () const virtual
Check whether system has changed such that the field needs updating.
Implements Pscf::FieldGeneratorBase.
Definition at line 77 of file FilmFieldGenMaskBase.tpp.
References normalVecCurrent_, Pscf::Vec< D, T >::setToZero(), systemLatticeVector(), and UTIL_CHECK.
checkCompatibility()
template<int D> void Pscf::Prdc::FilmFieldGenMaskBase< D >::checkCompatibility () virtual
Check that the system is compatible with this field.
This method calls setFlexibleParams, checkLatticeVectors, and checkSpaceGroup.
Implements Pscf::FieldGeneratorBase.
Definition at line 103 of file FilmFieldGenMaskBase.tpp.
References checkLatticeVectors(), checkSpaceGroup(), and setFlexibleParams().
normalVecId()
template<int D> int Pscf::Prdc::FilmFieldGenMaskBase< D >::normalVecId () const inline
Get value of normalVecId.
Definition at line 253 of file FilmFieldGenMaskBase.h.
Referenced by checkSpaceGroup(), Pscf::Rpc::FilmFieldGenMask< D >::compute(), Pscf::Rpg::FilmFieldGenMask< D >::compute(), Pscf::Rpc::FilmFieldGenMask< D >::modifyStress(), Pscf::Rpg::FilmFieldGenMask< D >::modifyStress(), Pscf::Rpc::FilmFieldGenMask< D >::stress(), and Pscf::Rpg::FilmFieldGenMask< D >::stress().
interfaceThickness()
template<int D> double Pscf::Prdc::FilmFieldGenMaskBase< D >::interfaceThickness () const inline
Get value of interfaceThickness.
Definition at line 258 of file FilmFieldGenMaskBase.h.
Referenced by Pscf::Rpc::FilmFieldGenMask< D >::compute(), Pscf::Rpg::FilmFieldGenMask< D >::compute(), Pscf::Rpc::FilmFieldGenMask< D >::stress(), and Pscf::Rpg::FilmFieldGenMask< D >::stress().
excludedThickness()
template<int D> double Pscf::Prdc::FilmFieldGenMaskBase< D >::excludedThickness () const inline
Get value of excludedThickness.
Definition at line 263 of file FilmFieldGenMaskBase.h.
Referenced by Pscf::Rpc::FilmFieldGenMask< D >::compute(), Pscf::Rpg::FilmFieldGenMask< D >::compute(), Pscf::Rpc::FilmFieldGenMask< D >::modifyStress(), Pscf::Rpg::FilmFieldGenMask< D >::modifyStress(), Pscf::Rpc::FilmFieldGenMask< D >::stress(), and Pscf::Rpg::FilmFieldGenMask< D >::stress().
fBulk()
template<int D> double Pscf::Prdc::FilmFieldGenMaskBase< D >::fBulk () const inline
Get value of fBulk.
Definition at line 268 of file FilmFieldGenMaskBase.h.
References fBulk_.
hasFBulk()
template<int D> bool Pscf::Prdc::FilmFieldGenMaskBase< D >::hasFBulk () const inline
Check whether a value of fBulk was provided.
Definition at line 273 of file FilmFieldGenMaskBase.h.
Referenced by Pscf::Rpc::FilmFieldGenMask< D >::modifyStress(), and Pscf::Rpg::FilmFieldGenMask< D >::modifyStress().
stress()
template<int D> virtual double Pscf::Prdc::FilmFieldGenMaskBase< D >::stress (int paramId) const pure virtual
Get contribution to the stress from this mask.
The mask defined by this class changes in a non-affine manner upon changing the lattice parameter corresponding to normalVecId. Thus, if this lattice parameter is allowed to be flexible, the "stress" used to optimize the parameter must contain additional terms arising from the mask. This method evaluates these terms and returns their value. Access to various System properties is required, so the method must be implemented by subclasses.
Parameters
paramId index of the lattice parameter being varied
Reimplemented from Pscf::Prdc::FieldGenerator.
Implemented in Pscf::Rpc::FilmFieldGenMask< D >, and Pscf::Rpg::FilmFieldGenMask< D >.
Referenced by modifyStress().
modifyStress()
template<int D> virtual double Pscf::Prdc::FilmFieldGenMaskBase< D >::modifyStress (int paramId, double stress) const pure virtual
Modify stress value in direction normal to the film.
The "stress" calculated by the System object is used to minimize fHelmholtz with respect to a given lattice parameter. In a thin film it is useful to instead minimize the excess free energy per unit area, (fHelmholtz - fRef) * Delta, where fRef is a reference free energy and Delta is the film thickness. The information needed to perform such a modification is contained within this object. This method performs this modification. The stress will not be modified for lattice parameters that are parallel to the film.
This method requires access to various attributes of the System, so it is left as a pure virtual method here and should be implemented by subclasses.
Parameters
paramId index of the lattice parameter with this stress
stress stress value calculated by Mixture object
Reimplemented from Pscf::Prdc::FieldGenerator.
Implemented in Pscf::Rpc::FilmFieldGenMask< D >, and Pscf::Rpg::FilmFieldGenMask< D >.
References stress().
compute()
template<int D> virtual void Pscf::Prdc::FilmFieldGenMaskBase< D >::compute () protected pure virtual
Compute the field and store where the System can access.
Implements Pscf::FieldGeneratorBase.
Implemented in Pscf::Rpc::FilmFieldGenMask< D >, and Pscf::Rpg::FilmFieldGenMask< D >.
checkSpaceGroup()
template<int D> void Pscf::Prdc::FilmFieldGenMaskBase< D >::checkSpaceGroup () const protected
Check that space group is compatible with the mask.
Definition at line 122 of file FilmFieldGenMaskBase.tpp.
References normalVecId(), Pscf::Prdc::SymmetryGroup< Symmetry >::size(), systemSpaceGroup(), and UTIL_THROW.
Referenced by checkCompatibility().
checkLatticeVectors()
template<int D> void Pscf::Prdc::FilmFieldGenMaskBase< D >::checkLatticeVectors () const protected
Check that lattice vectors are compatible with thin film constraint.
Check that user-defined lattice basis vectors (stored in the Domain member of the parent System object) are compatible with thin film confinement. The lattice basis vector with index normalVecId should be normal to the walls, while any other lattice basis vectors must be parallel to the walls.
Referenced by checkCompatibility().
modifyFlexibleParams()
template<int D> FSArray< bool, 6 > Pscf::Prdc::FilmFieldGenMaskBase< D >::modifyFlexibleParams (FSArray< bool, 6 > current, UnitCell< D > const & cell) const protected
Modifies a flexibleParams array to be compatible with this mask.
An iterator that is compatible with this mask should either have a strictly rigid unit cell (lattice parameters are fixed), or should allow some lattice parameters to be flexible while others are rigid. In the latter case, an FSArray<bool,6> will be used to keep track of which parameters are flexible and which are not.
This "flexibleParams" array may not be compatible with the constraints of this mask, so this method will read the current array, modify it for compatibility, and then return the corrected version. In particular, this method will ensure that the lattice parameter defining the film thickness is rigid, unless the optional input parameter fBulk is provided (since this parameter is necessary to compute the stress in the direction normal to the film). Further, all angles between basis vectors should be fixed except the angle in the plane of the film.
Subclasses should use this method in generate() to set the flexibleParams array of the iterator.
Parameters
current flexibleParams array
cell unit cell (read only)
Referenced by Pscf::Rpc::FilmFieldGenMask< D >::setFlexibleParams(), and Pscf::Rpg::FilmFieldGenMask< D >::setFlexibleParams().
setFlexibleParams()
template<int D> virtual void Pscf::Prdc::FilmFieldGenMaskBase< D >::setFlexibleParams () const protected pure virtual
Sets iterator's flexibleParams array to be compatible with the mask.
If the iterator allows for flexible lattice parameters, this method will access the "flexibleParams" array of the iterator (a FSArray<bool,6> that indicates which parameters are flexible), create a modified version using modifyFlexibleParams to be compatible with this mask, and then update the flexibleParams array owned by the iterator to match this modified array.
Because this requires access to the iterator, it must be implemented by subclasses.
Implemented in Pscf::Rpc::FilmFieldGenMask< D >, and Pscf::Rpg::FilmFieldGenMask< D >.
Referenced by checkCompatibility().
systemSpaceGroup()
template<int D> virtual std::string Pscf::Prdc::FilmFieldGenMaskBase< D >::systemSpaceGroup () const protected pure virtual
Get the space group name for this system.
Implemented in Pscf::Rpc::FilmFieldGenMask< D >, and Pscf::Rpg::FilmFieldGenMask< D >.
Referenced by checkSpaceGroup().
systemLatticeVector()
template<int D> virtual RealVec< D > Pscf::Prdc::FilmFieldGenMaskBase< D >::systemLatticeVector (int id) const protected pure virtual
Get one of the lattice vectors for this system.
Parameters
id index of the desired lattice vector
Implemented in Pscf::Rpc::FilmFieldGenMask< D >, and Pscf::Rpg::FilmFieldGenMask< D >.
Referenced by needsUpdate().
read()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value) protected
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 305 of file ParamComposite.h.
Referenced by readParameters().
readOptional()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
Referenced by readParameters().
Member Data Documentation
normalVecCurrent_
template<int D> RealVec<D> Pscf::Prdc::FilmFieldGenMaskBase< D >::normalVecCurrent_ protected
The lattice vector normal to the film used to generate these fields.
This vector is set to be equal to the system's lattice vector with index normalVecId_ each time the mask is generated. The system's lattice vectors may then change, and this normalVecCurrent_ vector is used to detect whether they have changed. This is used to decide whether a new mask needs to be generated.
Definition at line 223 of file FilmFieldGenMaskBase.h.
Referenced by Pscf::Rpc::FilmFieldGenMask< D >::compute(), Pscf::Rpg::FilmFieldGenMask< D >::compute(), FilmFieldGenMaskBase(), and needsUpdate().
fBulk_
template<int D> double Pscf::Prdc::FilmFieldGenMaskBase< D >::fBulk_ protected
Reference free energy used to calculate stress normal to the film.
Definition at line 226 of file FilmFieldGenMaskBase.h.
Referenced by fBulk(), FilmFieldGenMaskBase(), Pscf::Rpc::FilmFieldGenMask< D >::modifyStress(), Pscf::Rpg::FilmFieldGenMask< D >::modifyStress(), and readParameters().
The documentation for this class was generated from the following files:
FilmFieldGenMaskBase.h
FilmFieldGenMaskBase.tpp