PSCF: Pscf::PolymerTmpl< BT, PT > Class Template Reference
Pscf::PolymerTmpl< BT, PT > Class Template Reference
Pscf namespace » Pscf Common » Solver Templates
Template for an MDE solver and descriptor for a block polymer.
#include <PolymerTmpl.h>
Public Types
using BlockT = BT
Block of a block polymer.
using PropagatorT = PT
Modified diffusion equation solver for one block, in one direction.
Public Types inherited from Pscf::Species
enum Ensemble
Statistical ensemble for number of molecules.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
PolymerTmpl ()
Constructor.
~PolymerTmpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read and initialize.
virtual void solve (double phiTot=1.0)
Solve modified diffusion equation for all propagators.
const Vertex & vertex (int id) const
Get a specified Vertex by const reference.
Pair< int > const & propagatorId (int id) const
Get a propagator identifier, indexed by order of computation.
Pair< int > const & path (int is, int it) const
Get an id for a propagator from one vertex towards a target.
int nBlock () const
Number of blocks.
int nVertex () const
Number of vertices (junctions and chain ends).
int nPropagator () const
Number of propagators (2*nBlock).
double length () const
Sum of the lengths of all blocks in the polymer (thread model).
int nBead () const
Total number of beads in the polymer (bead model).
PolymerType::Enum type () const
Get Polymer type (Branched or Linear)
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble () const
Get the statistical ensemble for this species (open or closed).
Accessors (objects, by reference)
Edge & edge (int id) final
Get a specified Edge (block descriptor) by non-const reference.
Edge const & edge (int id) const final
Get a specified Edge (block descriptor) by const reference.
BT & block (int id)
Get a specified Block (solver and descriptor).
BT const & block (int id) const
Get a specified Block (solver and descriptor) by const reference.
PT & propagator (int blockId, int directionId)
Get the propagator for a specific block and direction (non-const).
PT const & propagator (int blockId, int directionId) const
Get the propagator for a specific block and direction (const).
PT & propagator (int id)
Get a propagator indexed in order of computation (non-const).
Public Member Functions inherited from Pscf::PolymerSpecies
PolymerSpecies ()
Constructor.
~PolymerSpecies ()
Destructor.
const Vertex & vertex (int id) const
Get a specified Vertex by const reference.
int nBlock () const
Number of blocks.
int nVertex () const
Number of vertices (junctions and chain ends).
int nPropagator () const
Number of propagators (2*nBlock).
double length () const
Sum of the lengths of all blocks in the polymer (thread model).
int nBead () const
Total number of beads in the polymer (bead model).
PolymerType::Enum type () const
Get Polymer type (Branched or Linear)
Pair< int > const & propagatorId (int id) const
Get a propagator identifier, indexed by order of computation.
Pair< int > const & path (int is, int it) const
Get an id for a propagator from one vertex towards a target.
Public Member Functions inherited from Pscf::Species
Species ()
Default constructor.
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble () const
Get the statistical ensemble for this species (open or closed).
void setPhi (double phi)
Set value of phi (volume fraction), if ensemble is closed.
void setMu (double mu)
Set value of mu (chemical potential), if ensemble is closed.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
void allocateBlocks () final
Allocate array of Block objects.
void readBlocks (std::istream &in) final
Read array of data for blocks from parameter file.
Protected Member Functions inherited from Pscf::PolymerSpecies
virtual void makePlan ()
Make a plan for order in which propagators should be computed.
void makePaths ()
Create a matrix of vertex-to-vertex path signposts.
Protected Member Functions inherited from Pscf::Species
void setQ (double q)
Set q and compute phi or mu (depending on the ensemble).
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<class BT, class PT>
class Pscf::PolymerTmpl< BT, PT >
Template for an MDE solver and descriptor for a block polymer.
Class template argument BT is an alias for a class that represents a block of a block polymer. By convention, this is a class named Block defined in each implementation-level sub-namespace of Pscf. Each such namespace contains a class named Block that is a subclass of Pscf::Edge, and a class named Polymer that is a subclass of the template instantiation PolymerTmpl<Block>.
A PolymerTmpl<Block> object has an array of Block objects, as well as an array of Vertex objects inherited from the PolymerSpecies base class. Each Block has two Propagator MDE solver objects associated with the two directions along each block.
The solve() member function solves the modified diffusion equation (MDE) for all propagators in the molecule (i.e., all blocks, in both directions) in a pre-defined order.
Definition at line 44 of file PolymerTmpl.h.
Member Typedef Documentation
BlockT
template<class BT, class PT> using Pscf::PolymerTmpl< BT, PT >::BlockT = BT
Block of a block polymer.
Definition at line 54 of file PolymerTmpl.h.
PropagatorT
template<class BT, class PT> using Pscf::PolymerTmpl< BT, PT >::PropagatorT = PT
Modified diffusion equation solver for one block, in one direction.
Definition at line 59 of file PolymerTmpl.h.
Constructor & Destructor Documentation
PolymerTmpl()
template<class BT, class PT> Pscf::PolymerTmpl< BT, PT >::PolymerTmpl ()
Constructor.
Definition at line 22 of file PolymerTmpl.tpp.
References Pscf::PolymerSpecies::PolymerSpecies(), and Util::ParamComposite::setClassName().
Referenced by edge().
~PolymerTmpl()
template<class BT, class PT> Pscf::PolymerTmpl< BT, PT >::~PolymerTmpl ()
Destructor.
Definition at line 31 of file PolymerTmpl.tpp.
Member Function Documentation
readParameters()
template<class BT, class PT> void Pscf::PolymerTmpl< BT, PT >::readParameters (std::istream & in) virtual
Read and initialize.
Parameters
in input parameter stream
Reimplemented from Pscf::PolymerSpecies.
Definition at line 52 of file PolymerTmpl.tpp.
References Pscf::PolymerSpecies::readParameters().
solve()
template<class BT, class PT> void Pscf::PolymerTmpl< BT, PT >::solve (double phiTot = 1.0) virtual
Solve modified diffusion equation for all propagators.
Upon return, all propagators for all blocks, molecular partition function q, phi and mu are all set. The implementation of PolymerTmpl::solve() the calls the solve() function for all propagators in the molecule in a predeternined order, then computes q, and finally computes mu from phi or phi from mu, depending on the ensemble (open or closed) for this species. This solve() function does not compute monomer concentration field.
Each implementation-level namespace defines a concrete subclass of PolymerTmpl<BT,PT> that is named Polymer by convention. Each such Polymer class defines a function named "compute" that takes an array of chemical fields (w-fields) as an argument, and that calls PolymerTmpl<BT,PT>::solve internally. Before calling the solve() function declared here, the Polymer::compute() function must pass pass the w-fields and any other required mutable data to all Block objects in order to set up the MDE solver for each block. After calling the solve() function, the Polymer::compute function must also compute monomer concentrations for all blocks, each of which is stored in a field container owned by the associated Block.
The optional parameter phiTot is only relevant to problems involving a Mask that excludes material from part of the unit cell, as done to define thin film problems.
Parameters
phiTot fraction of unit cell volume occupied by material
Definition at line 153 of file PolymerTmpl.tpp.
References nPropagator(), and propagator().
edge() [1/2]
template<class BT, class PT> Edge & Pscf::PolymerTmpl< BT, PT >::edge (int id) inline final virtual
Get a specified Edge (block descriptor) by non-const reference.
The edge member functions implements pure virtual functions defined by the PolymerSpecies base class, and provide access to each Block as a reference to an Edge (a block descriptor).
Parameters
id block index, 0 <= id < nBlock
Implements Pscf::PolymerSpecies.
Reimplemented in Pscf::Rpc::Polymer< D >, and Pscf::Rpg::Polymer< D >.
Definition at line 232 of file PolymerTmpl.h.
References edge(), and PolymerTmpl().
Referenced by edge().
edge() [2/2]
template<class BT, class PT> Edge const & Pscf::PolymerTmpl< BT, PT >::edge (int id) const inline final virtual
Get a specified Edge (block descriptor) by const reference.
Parameters
id block index, 0 <= id < nBlock
Implements Pscf::PolymerSpecies.
Reimplemented in Pscf::Rpc::Polymer< D >, and Pscf::Rpg::Polymer< D >.
Definition at line 240 of file PolymerTmpl.h.
block() [1/2]
template<class BT, class PT> BT & Pscf::PolymerTmpl< BT, PT >::block (int id) inline
Get a specified Block (solver and descriptor).
Parameters
id block index, 0 <= id < nBlock
Definition at line 248 of file PolymerTmpl.h.
Referenced by propagator(), and propagator().
block() [2/2]
template<class BT, class PT> BT const & Pscf::PolymerTmpl< BT, PT >::block (int id) const inline
Get a specified Block (solver and descriptor) by const reference.
Parameters
id block index, 0 <= id < nBlock
Definition at line 256 of file PolymerTmpl.h.
propagator() [1/3]
template<class BT, class PT> PT & Pscf::PolymerTmpl< BT, PT >::propagator (int blockId, int directionId)
Get the propagator for a specific block and direction (non-const).
For an edge that terminates at vertices with vertex indices given by the return values of Edge::vertexId(0) and Edge::vertexId(1):
direction 0 propagates from vertexId(0) to vertexId(1)
direction 1 propagates from vertexId(1) to vertexId(0)
Parameters
blockId integer index of associated block
directionId integer index for direction (0 or 1)
Definition at line 184 of file PolymerTmpl.tpp.
References block().
Referenced by solve(), Pscf::R1d::System::writeQ(), Pscf::R1d::System::writeQSlice(), Pscf::R1d::System::writeQTail(), and Pscf::R1d::FieldIo::writeVertexQ().
propagator() [2/3]
template<class BT, class PT> PT const & Pscf::PolymerTmpl< BT, PT >::propagator (int blockId, int directionId) const
Get the propagator for a specific block and direction (const).
Parameters
blockId integer index of associated block
directionId integer index for direction (0 or 1)
Definition at line 192 of file PolymerTmpl.tpp.
References block().
propagator() [3/3]
template<class BT, class PT> PT & Pscf::PolymerTmpl< BT, PT >::propagator (int id)
Get a propagator indexed in order of computation (non-const).
The propagator index argument must satisfy 0 <= id < 2*nBlock.
Parameters
id propagator index, in order of computation plan
Definition at line 199 of file PolymerTmpl.tpp.
References propagatorId().
allocateBlocks()
template<class BT, class PT> void Pscf::PolymerTmpl< BT, PT >::allocateBlocks () final protected virtual
Allocate array of Block objects.
Implements Pscf::PolymerSpecies.
Definition at line 38 of file PolymerTmpl.tpp.
References nBlock().
readBlocks()
template<class BT, class PT> void Pscf::PolymerTmpl< BT, PT >::readBlocks (std::istream & in) final protected virtual
Read array of data for blocks from parameter file.
Parameters
in parameter input stream
Implements Pscf::PolymerSpecies.
Definition at line 45 of file PolymerTmpl.tpp.
References nBlock(), and Util::ParamComposite::readDArray().
vertex()
template<class BT, class PT> Vertex const & Pscf::PolymerSpecies::vertex (int id) const inline
Get a specified Vertex by const reference.
Chain ends and block junctions are all vertices.
Parameters
id vertex index, 0 <= id < nVertex
Definition at line 124 of file PolymerSpecies.h.
Referenced by Pscf::R1d::FieldIo::writeVertexQ().
propagatorId()
template<class BT, class PT> Pair< int > const & Pscf::PolymerSpecies::propagatorId (int id) const inline
Get a propagator identifier, indexed by order of computation.
The return value is a pair of integers that identifies a directed edge, or a propagator. The first integer is a block index between 0 and nBlock - 1, and the second is a propagator direction id, which must be 0 or 1. By convention, direction 0 of Edge i propagates from vertex edge(i).vertexId(0) to vertex edge(i).vertexId(1), while direction 1 propagates in the other direction, from edge(i).vertexId(1) to edge(i).vertexId(0).
The propagators are indexed in an order that is computed by the protected function PolymerSpecies::makePlan. The indexing is chosen such that, if MDEs for different propagators are solved in sequential order by propagator index, then information required to construct the initial condition for the MDE within each propagator (the source slice) is guaranteed to be available from the solution of previous calculations.
Parameters
id propagator index, in order of computation plan
Definition at line 192 of file PolymerSpecies.h.
Referenced by propagator().
path()
template<class BT, class PT> Pair< int > const & Pscf::PolymerSpecies::path (int is, int it) const inline
Get an id for a propagator from one vertex towards a target.
For is != it, the return value is an identifier for an outgoing propagator that begins at the source vertex (vertex index is) and is the first edge of the directed path that leads from the source vertex to the target vertex (vertex id it). The return value is a pair of integers analogous to that returned by the propagatorId(int) member function, for which the first element is a block index and the second element is a direction id (0 or 1) for the propagator direction for that block that is outgoing from from the source vertex along the unique path leading to the target vertex. The requirement that the propagator be outgoing from vertex is implies that if path(is, it) == [ib, id], then edge(ib).vertexId(id) == is.
Parameters
is index of the source vertex
it index of the target vertex
Definition at line 212 of file PolymerSpecies.h.
nBlock()
template<class BT, class PT> int Pscf::PolymerSpecies::nBlock () const inline
Number of blocks.
Definition at line 133 of file PolymerSpecies.h.
Referenced by allocateBlocks(), readBlocks(), Pscf::R1d::System::writeQ(), Pscf::R1d::System::writeQSlice(), Pscf::R1d::System::writeQTail(), and Pscf::R1d::FieldIo::writeVertexQ().
nVertex()
template<class BT, class PT> int Pscf::PolymerSpecies::nVertex () const inline
Number of vertices (junctions and chain ends).
A theorem of graph theory tells us that, for any linear or acyclic branched polymer, nVertex = nBlock + 1.
Definition at line 141 of file PolymerSpecies.h.
nPropagator()
template<class BT, class PT> int Pscf::PolymerSpecies::nPropagator () const inline
Number of propagators (2*nBlock).
Definition at line 146 of file PolymerSpecies.h.
Referenced by solve().
length()
template<class BT, class PT> double Pscf::PolymerSpecies::length () const
Sum of the lengths of all blocks in the polymer (thread model).
Precondition: PolymerModel::isThread()
Definition at line 153 of file PolymerSpecies.cpp.
Referenced by Pscf::R1d::System::computeFreeEnergy().
nBead()
template<class BT, class PT> int Pscf::PolymerSpecies::nBead () const
Total number of beads in the polymer (bead model).
Precondition: PolymerModel::isBead()
Definition at line 160 of file PolymerSpecies.cpp.
type()
template<class BT, class PT> PolymerType::Enum Pscf::PolymerSpecies::type () const inline
Get Polymer type (Branched or Linear)
Definition at line 165 of file PolymerSpecies.h.
phi()
template<class BT, class PT> double Pscf::Species::phi () const inline
Get the overall volume fraction for this species.
Definition at line 62 of file Species.h.
Referenced by Pscf::R1d::System::computeFreeEnergy(), and ensemble().
mu()
template<class BT, class PT> double Pscf::Species::mu () const inline
Get the chemical potential for this species (units kT=1).
Definition at line 67 of file Species.h.
Referenced by Pscf::R1d::System::computeFreeEnergy(), and ensemble().
q()
template<class BT, class PT> double Pscf::Species::q () const inline
Get the molecular partition function for this species.
Definition at line 72 of file Species.h.
Referenced by ensemble().
ensemble()
template<class BT, class PT> Species::Ensemble Pscf::Species::ensemble () const inline
Get the statistical ensemble for this species (open or closed).
Definition at line 77 of file Species.h.
References mu(), phi(), and q().
The documentation for this class was generated from the following files:
PolymerTmpl.h
PolymerTmpl.tpp