PSCF: Pscf::Fd1d::HomogeneousComparison Class Reference
Pscf::Fd1d::HomogeneousComparison Class Reference
Pscf namespace » Finite-Difference 1D
Command to compute properties of homogeneous reference system.
#include <HomogeneousComparison.h>
Public Member Functions
HomogeneousComparison ()
Default constructor.
HomogeneousComparison (System &system)
Constructor.
~HomogeneousComparison ()
Destructor.
void compute (int mode)
Compute properties of a homogeneous reference system.
void output (int mode, std::ostream &out)
Output comparison to a homogeneous reference system.
Public Member Functions inherited from Pscf::Fd1d::SystemAccess
SystemAccess ()
Default constructor.
SystemAccess (System &system)
Constructor.
~SystemAccess ()
Destructor.
virtual void setSystem (System &system)
Set the system after construction.
const System & system () const
Get parent System by reference.
System & system ()
Get parent System by reference.
const Mixture & mixture () const
Get Mixture by reference.
Mixture & mixture ()
Get Mixture by reference.
const Domain & domain () const
Get spatial domain (including grid info) by reference.
Domain & domain ()
Get spatial domain (including grid info) by reference.
const Interaction & interaction () const
Get interaction (i.e., excess free energy model) by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
const Homogeneous::Mixture & homogeneous () const
Get homogeneous mixture (for reference calculations).
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
DArray< System::WField > & wFields ()
Get array of all chemical potential fields.
System::WField & wField (int monomerId)
Get chemical potential field for a specific monomer type.
DArray< System::CField > & cFields ()
Get array of all chemical potential fields.
System::CField & cField (int monomerId)
Get chemical potential field for a specific monomer type.
Detailed Description
Command to compute properties of homogeneous reference system.
Definition at line 21 of file HomogeneousComparison.h.
Constructor & Destructor Documentation
Pscf::Fd1d::HomogeneousComparison::HomogeneousComparison ()
Default constructor.
Definition at line 33 of file HomogeneousComparison.cpp.
Pscf::Fd1d::HomogeneousComparison::HomogeneousComparison (System & system)
Constructor.
Definition at line 40 of file HomogeneousComparison.cpp.
Pscf::Fd1d::HomogeneousComparison::~HomogeneousComparison ()
Destructor.
Definition at line 47 of file HomogeneousComparison.cpp.
References Util::DArray< Data >::allocate(), Util::Array< Data >::capacity(), Util::DArray< Data >::isAllocated(), Pscf::BlockDescriptor::length(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::BlockDescriptor::monomerId(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::MixtureTmpl< TP, TS >::polymer(), and UTIL_CHECK.
Member Function Documentation
void Pscf::Fd1d::HomogeneousComparison::compute (int mode)
Compute properties of a homogeneous reference system.
This function should be called after iterator().solve() to compute properties of a homogeneous reference system to which the properties of the system of interest can be compared. The value of the mode parameter controls the choice of homogeneous reference system used for this comparison.
Mode parameter values:
mode = 0 : homogeneous system with same phi's
mode = 1,2 : homogeneous system with same mu's
The difference between mode indices 1 and 2 is the initial guess used in the iterative computation of the composition of the homogeneous reference system:
mode = 1 : composition at last grid point (nx -1)
mode = 2 : composition at first grid point (0)
Mode indices 1 and 2 are intended to be used for calculation of excess properties in, e.g., computation of properties of a micelle or an interface.
Parameters
mode mode index
Definition at line 139 of file HomogeneousComparison.cpp.
References Util::DArray< Data >::allocate(), Util::Array< Data >::capacity(), Pscf::Homogeneous::Mixture::computeFreeEnergy(), Pscf::Homogeneous::Mixture::computeMu(), Pscf::Homogeneous::Mixture::computePhi(), Pscf::Fd1d::SystemAccess::domain(), Pscf::Fd1d::SystemAccess::homogeneous(), Pscf::Fd1d::SystemAccess::interaction(), Util::DArray< Data >::isAllocated(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::Homogeneous::Mixture::nMolecule(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::MixtureTmpl< TP, TS >::nSolvent(), Pscf::Fd1d::Domain::nx(), Pscf::MixtureTmpl< TP, TS >::polymer(), Pscf::Homogeneous::Mixture::setComposition(), UTIL_CHECK, and UTIL_THROW.
Referenced by Pscf::Fd1d::System::readCommands(), and Pscf::Fd1d::Sweep::solve().
void Pscf::Fd1d::HomogeneousComparison::output (int mode, std::ostream & out)
Output comparison to a homogeneous reference system.
Parameters
mode mode index
out output stream
Definition at line 208 of file HomogeneousComparison.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Homogeneous::Mixture::fHelmholtz(), Pscf::Fd1d::System::fHelmholtz(), Pscf::Fd1d::SystemAccess::homogeneous(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::Homogeneous::Mixture::nMolecule(), Pscf::Homogeneous::Mixture::phi(), Pscf::MixtureTmpl< TP, TS >::polymer(), Pscf::Homogeneous::Mixture::pressure(), Pscf::Fd1d::System::pressure(), Pscf::Fd1d::SystemAccess::system(), Pscf::Fd1d::Mixture::vMonomer(), and Pscf::Fd1d::Domain::volume().
Referenced by Pscf::Fd1d::Sweep::outputSolution(), and Pscf::Fd1d::System::readCommands().
The documentation for this class was generated from the following files:
HomogeneousComparison.h
HomogeneousComparison.cpp