PSCF: Pscf::Fd1d::Domain Class Reference
Pscf::Fd1d::Domain Class Reference
Pscf namespace » Finite-Difference 1D » Domain
One-dimensional spatial domain and discretization grid.
#include <Domain.h>
Public Types
typedef DArray< double > Field
Generic field type (base class)
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Domain ()
Constructor.
~Domain ()
Destructor.
Initialize parameters
void readParameters (std::istream &in)
Read all parameters and initialize.
void setPlanarParameters (double xMin, double xMax, int nx)
Set grid parameters for a planar domain.
void setShellParameters (GeometryMode mode, double xMin, double xMax, int nx)
Set grid parameters for a cylindrical or spherical shell.
void setCylinderParameters (double xMax, int nx)
Set grid parameters for a cylinder.
void setSphereParameters (double xMax, int nx)
Set grid parameters for a sphere.
Accessors
double xMin () const
Get minimum spatial coordinate.
double xMax () const
Get maximum spatial coordinate.
double volume () const
Get generalized volume of domain.
double dx () const
Get spatial grid step size.
int nx () const
Get number of spatial grid points, including both endpoints.
GeometryMode const & mode () const
Get coordinate system flag (Planar, Cylindrical or Spherical).
bool isShell () const
Is this a cylindrical or spherical shell?
Spatial integrals
double spatialAverage (Field const &f) const
Compute spatial average of a field.
double innerProduct (Field const &f, Field const &g) const
Compute inner product of two real fields.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void readParam (std::istream &in)=0
Read parameter(s) from file.
virtual void writeParam (std::ostream &out) const =0
Read parameter(s) to file.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
virtual void save (OArchive &ar)=0
Save to an archive.
virtual void load (IArchive &ar)=0
Load from an archive.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
One-dimensional spatial domain and discretization grid.
Parameter File Format
Definition at line 26 of file fd1d/domain/Domain.h.
Member Typedef Documentation
Field
typedef DArray<double> Pscf::Fd1d::Domain::Field
Generic field type (base class)
Definition at line 34 of file fd1d/domain/Domain.h.
Constructor & Destructor Documentation
Domain()
Pscf::Fd1d::Domain::Domain ()
Constructor.
Definition at line 15 of file fd1d/domain/Domain.cpp.
References Util::ParamComposite::setClassName().
~Domain()
Pscf::Fd1d::Domain::~Domain ()
Destructor.
Definition at line 25 of file fd1d/domain/Domain.cpp.
Member Function Documentation
readParameters()
void Pscf::Fd1d::Domain::readParameters (std::istream & in) virtual
Read all parameters and initialize.
Reimplemented from Util::ParamComposite.
Definition at line 28 of file fd1d/domain/Domain.cpp.
References Util::ParamComposite::read(), Util::ParamComposite::readOptional(), and UTIL_CHECK.
setPlanarParameters()
void Pscf::Fd1d::Domain::setPlanarParameters (double xMin, double xMax, int nx)
Set grid parameters for a planar domain.
Parameters
xMin minimum normal coordinate value
xMax maximum normal coordinate value
nx number of grid points, including endpoints
Definition at line 48 of file fd1d/domain/Domain.cpp.
References nx(), xMax(), and xMin().
setShellParameters()
void Pscf::Fd1d::Domain::setShellParameters (GeometryMode mode, double xMin, double xMax, int nx)
Set grid parameters for a cylindrical or spherical shell.
Parameters
mode enumeration (Llamellar, Cylindrical or Spherical)
xMin minimum radius
xMax maximum radius
nx number of grid points, including endpoints
Definition at line 59 of file fd1d/domain/Domain.cpp.
References mode(), nx(), xMax(), and xMin().
setCylinderParameters()
void Pscf::Fd1d::Domain::setCylinderParameters (double xMax, int nx)
Set grid parameters for a cylinder.
Parameters
xMax maximum radius
nx number of grid points, including endpoints
Definition at line 71 of file fd1d/domain/Domain.cpp.
References nx(), and xMax().
setSphereParameters()
void Pscf::Fd1d::Domain::setSphereParameters (double xMax, int nx)
Set grid parameters for a sphere.
Parameters
xMax maximum radius
nx number of grid points, including endpoints
Definition at line 82 of file fd1d/domain/Domain.cpp.
References nx(), and xMax().
xMin()
double Pscf::Fd1d::Domain::xMin () const inline
Get minimum spatial coordinate.
Definition at line 219 of file fd1d/domain/Domain.h.
Referenced by Pscf::Fd1d::FieldIo::remesh(), setPlanarParameters(), setShellParameters(), and Pscf::Fd1d::Block::setupSolver().
xMax()
double Pscf::Fd1d::Domain::xMax () const inline
Get maximum spatial coordinate.
Definition at line 222 of file fd1d/domain/Domain.h.
Referenced by Pscf::Fd1d::FieldIo::remesh(), setCylinderParameters(), setPlanarParameters(), setShellParameters(), setSphereParameters(), and Pscf::Fd1d::Block::setupSolver().
volume()
double Pscf::Fd1d::Domain::volume () const inline
Get generalized volume of domain.
Returns volume of spherical domain, area of cylindrical domain, or a length of a planar domain.
Definition at line 225 of file fd1d/domain/Domain.h.
Referenced by Pscf::Fd1d::HomogeneousComparison::output(), and Pscf::Fd1d::Sweep::outputSummary().
dx()
double Pscf::Fd1d::Domain::dx () const inline
Get spatial grid step size.
Definition at line 216 of file fd1d/domain/Domain.h.
Referenced by Pscf::Fd1d::FieldIo::remesh(), and Pscf::Fd1d::Block::setupSolver().
nx()
int Pscf::Fd1d::Domain::nx () const inline
Get number of spatial grid points, including both endpoints.
Definition at line 213 of file fd1d/domain/Domain.h.
Referenced by Pscf::Fd1d::Sweep::checkAllocation(), Pscf::Fd1d::Mixture::compute(), Pscf::Fd1d::HomogeneousComparison::compute(), Pscf::Fd1d::Solvent::compute(), Pscf::Fd1d::Block::computeConcentration(), Pscf::Fd1d::System::computeFreeEnergy(), Pscf::Fd1d::Sweep::extrapolate(), Pscf::Fd1d::FieldIo::remesh(), setCylinderParameters(), Pscf::Fd1d::Solvent::setDiscretization(), Pscf::Fd1d::Block::setDiscretization(), setPlanarParameters(), setShellParameters(), setSphereParameters(), Pscf::Fd1d::Block::setupSolver(), Pscf::Fd1d::BinaryRelaxIterator::solve(), Pscf::Fd1d::NrIterator::solve(), Pscf::Fd1d::Block::step(), Pscf::Fd1d::FieldIo::writeBlockCFields(), and Pscf::Fd1d::FieldIo::writeVertexQ().
mode()
GeometryMode const & Pscf::Fd1d::Domain::mode () const inline
Get coordinate system flag (Planar, Cylindrical or Spherical).
Definition at line 228 of file fd1d/domain/Domain.h.
Referenced by setShellParameters(), and Pscf::Fd1d::Block::setupSolver().
isShell()
bool Pscf::Fd1d::Domain::isShell () const inline
Is this a cylindrical or spherical shell?
This value is relevant only if the geometry mode is spherical or cylindrical. If so, isShell is set true if the optional parameter xMin is present and assigned a positive value in the parameter file. If geometryMode is planar or xMin is absent, then isShell is false.
Definition at line 231 of file fd1d/domain/Domain.h.
Referenced by Pscf::Fd1d::Block::setupSolver().
spatialAverage()
double Pscf::Fd1d::Domain::spatialAverage (Field const & f) const
Compute spatial average of a field.
Parameters
f a field that depends on one spatial coordinate
Returns
spatial average of field f
Definition at line 119 of file fd1d/domain/Domain.cpp.
References Util::Array< Data >::capacity(), UTIL_CHECK, and UTIL_THROW.
Referenced by Pscf::Fd1d::Solvent::compute(), Pscf::Fd1d::System::computeFreeEnergy(), and innerProduct().
innerProduct()
double Pscf::Fd1d::Domain::innerProduct (Field const & f, Field const & g) const
Compute inner product of two real fields.
Parameters
f first field
g second field
Returns
spatial average of product of two fields.
Definition at line 201 of file fd1d/domain/Domain.cpp.
References Util::DArray< Data >::allocate(), Util::Array< Data >::capacity(), Util::DArray< Data >::isAllocated(), spatialAverage(), UTIL_ASSERT, and UTIL_CHECK.
Referenced by Pscf::Fd1d::System::computeFreeEnergy(), and Pscf::Fd1d::Propagator::computeQ().
The documentation for this class was generated from the following files:
fd1d/domain/Domain.h
fd1d/domain/Domain.cpp