PSCF: Pscf::Rpg::Mixture< D > Class Template Reference
Pscf::Rpg::Mixture< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Solvers
Solver and descriptor for a mixture of polymers and solvents.
#include <Mixture.h>
Public Types
using MixtureRealT = typename Prdc::MixtureReal<D, Polymer<D>, Solvent<D> >
Direct (parent) base class.
Public Types inherited from Pscf::Prdc::MixtureReal< D, Polymer< D >, Solvent< D > >
using MixtureTmplT
MixtureTmplT class.
using FieldT
Field type, for data defined on a real-space grid.
using FFTT
WaveList type.
using WaveListT
WaveList type.
using FieldIoT
FieldIo type.
Public Types inherited from Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >
using SolventT
Solvent species solver type.
using PolymerT
Polymer species solver type.
using BlockT
Block polymer block type.
using PropagatorT
Polymer block propagator type.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Mixture ()
Constructor.
void readParameters (std::istream &in) override
Read all parameters and initialize.
int nMonomer () const
Get number of monomer types.
Monomer const & monomer (int id) const
Get a Monomer type descriptor by const reference.
Monomer & monomer (int id)
Get a Monomer type descriptor (non-const reference).
int nPolymer () const
Get number of polymer species.
int nSolvent () const
Get number of solvent (point particle) species.
int nBlock () const
Get total number blocks among all polymer species.
double vMonomer () const
Get monomer reference volume (set to 1.0 by default).
bool isCanonical () const
Is this mixture being treated in canonical ensemble?
Public Member Functions inherited from Pscf::Prdc::MixtureReal< D, Polymer< D >, Solvent< D > >
MixtureReal ()
Constructor.
~MixtureReal ()
Destructor.
void associate (Mesh< D > const &mesh, FFTT const &fft, UnitCell< D > const &cell, WaveListT &waveList)
Create associations with Mesh, FFT, UnitCell, and WaveList objects.
void setFieldIo (FieldIoT const &fieldIo)
Create an association with a FieldIoT object.
void allocate ()
Allocate required internal memory for all solvers.
void compute (DArray< FieldT > const &wFields, DArray< FieldT > &cFields, double phiTot=1.0)
Compute partition functions and concentrations.
void setIsSymmetric (bool isSymmetric)
Set the isSymmetric flag true or false.
void computeStress (double phiTot=1.0)
Compute derivatives of free energy w/ respect to cell parameters.
bool hasStress () const
Has the stress been computed since the last MDE solution?
double stress (int parameterId) const
Get derivative of free energy w/ respect to a unit cell parameter.
void setKuhn (int monomerId, double kuhn)
Reset statistical segment length for one monomer type.
void clearUnitCellData ()
Clear all data that depends on the unit cell parameters.
void createBlockCRGrid (DArray< FieldT > &blockCFields) const
Get c-fields for all blocks and solvents as array of r-grid fields.
void writeBlockCRGrid (std::string const &filename) const
Write c fields for all blocks and solvents in r-grid format.
void writeQSlice (std::string const &filename, int polymerId, int blockId, int directionId, int segmentId) const
Write one slice of a propagator at fixed s in r-grid format.
void writeQTail (std::string const &filename, int polymerId, int blockId, int directionId) const
Write the final slice of a propagator in r-grid format.
void writeQ (std::string const &filename, int polymerId, int blockId, int directionId) const
Write the complete propagator for one block, in r-grid format.
void writeQAll (std::string const &basename)
Write all propagators of all blocks, each to a separate file.
void writeStress (std::ostream &out) const
Write stress values to output stream.
Public Member Functions inherited from Pscf::MixtureTmpl< Polymer< D >, Solvent< D > >
MixtureTmpl ()
Constructor.
~MixtureTmpl ()
Destructor.
PolymerT & polymer (int id)
Get a polymer solver object by non-const reference.
SolventT & solvent (int id)
Get a solvent solver object.
Public Member Functions inherited from Pscf::MixtureBase
MixtureBase ()
Constructor.
~MixtureBase ()
Destructor.
void setVmonomer (double vMonomer)
Set new vMonomer value.
int nMonomer () const
Get number of monomer types.
int nPolymer () const
Get number of polymer species.
int nSolvent () const
Get number of solvent (point particle) species.
int nBlock () const
Get total number blocks among all polymer species.
double vMonomer () const
Get monomer reference volume (set to 1.0 by default).
bool isCanonical () const
Is this mixture being treated in canonical ensemble?
Monomer const & monomer (int id) const
Get a Monomer type descriptor by const reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Pscf::Prdc::MixtureReal< D, Polymer< D >, Solvent< D > >
Mesh< D > const & mesh () const
Return associated Mesh<D> by const reference.
UnitCell< D > const & unitCell () const
Return associated UnitCell<D> by const reference.
FieldIoT const & fieldIo () const
Return associated FieldIoT by const reference.
double ds () const
Return target value for the contour step size ds.
Protected Member Functions inherited from Pscf::MixtureBase
Monomer & monomer (int id)
Get a Monomer type descriptor (non-const reference).
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from Pscf::MixtureBase
DArray< Monomer > monomers_
Array of monomer type descriptors.
int nMonomer_
Number of monomer types.
int nPolymer_
Number of polymer species.
int nSolvent_
Number of solvent species.
int nBlock_
Number of blocks total, across all polymers.
double vMonomer_
Monomer reference volume (set to 1.0 by default).
Detailed Description
template<int D>
class Pscf::Rpg::Mixture< D >
Solver and descriptor for a mixture of polymers and solvents.
A Mixture is derived from a partial specialization of the template Prdc::MixtureReal, and has the same public interface as this base class template.
Manual Page
Definition at line 29 of file rpg/solvers/Mixture.h.
Member Typedef Documentation
MixtureRealT
template<int D> using Pscf::Rpg::Mixture< D >::MixtureRealT = typename Prdc::MixtureReal<D, Polymer<D>, Solvent<D> >
Direct (parent) base class.
Definition at line 35 of file rpg/solvers/Mixture.h.
Constructor & Destructor Documentation
Mixture()
template<int D> Pscf::Rpg::Mixture< D >::Mixture ()
Constructor.
Definition at line 27 of file rpg/solvers/Mixture.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::Mixture< D >::readParameters (std::istream & in) override virtual
Read all parameters and initialize.
Parameters
in input parameter stream
Reimplemented from Pscf::Prdc::MixtureReal< D, Polymer< D >, Solvent< D > >.
Definition at line 36 of file rpg/solvers/Mixture.tpp.
References Util::ParamComposite::readOptional().
nMonomer()
template<int D> int Pscf::MixtureBase::nMonomer () const inline
Get number of monomer types.
Definition at line 84 of file MixtureBase.h.
Referenced by Pscf::Rpg::Simulator< D >::computeHamiltonian().
monomer() [1/2]
template<int D> Monomer const & Pscf::MixtureBase::monomer (int id) const inline
Get a Monomer type descriptor by const reference.
Parameters
id integer monomer type index (0 <= id < nMonomer)
Definition at line 124 of file MixtureBase.h.
Referenced by Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations().
monomer() [2/2]
template<int D> Monomer & Pscf::MixtureBase::monomer (int id) inline
Get a Monomer type descriptor (non-const reference).
Parameters
id integer monomer type index (0 <= id < nMonomer)
Definition at line 151 of file MixtureBase.h.
nPolymer()
template<int D> int Pscf::MixtureBase::nPolymer () const inline
Get number of polymer species.
Definition at line 89 of file MixtureBase.h.
Referenced by Pscf::Rpg::Simulator< D >::computeHamiltonian(), and Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations().
nSolvent()
template<int D> int Pscf::MixtureBase::nSolvent () const inline
Get number of solvent (point particle) species.
Definition at line 94 of file MixtureBase.h.
Referenced by Pscf::Rpg::Simulator< D >::computeHamiltonian(), and Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations().
nBlock()
template<int D> int Pscf::MixtureBase::nBlock () const inline
Get total number blocks among all polymer species.
Definition at line 99 of file MixtureBase.h.
vMonomer()
template<int D> double Pscf::MixtureBase::vMonomer () const inline
Get monomer reference volume (set to 1.0 by default).
Definition at line 104 of file MixtureBase.h.
Referenced by Pscf::Rpg::Simulator< D >::computeHamiltonian(), and Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations().
isCanonical()
template<int D> bool Pscf::MixtureBase::isCanonical () const
Is this mixture being treated in canonical ensemble?
Returns true iff a closed ensemble is used for every polymer and solve species, by specifying a volume fraction phi rather than a chemical potential mu for every species in the mixture.
Definition at line 113 of file MixtureBase.cpp.
The documentation for this class was generated from the following files:
rpg/solvers/Mixture.h
rpg/solvers/Mixture.tpp