PSCF: Pscf::Rpc::Sweep< D > Class Template Reference
Pscf::Rpc::Sweep< D > Class Template Reference abstract
Solve a sequence of SCFT problems along a line in parameter space.
#include <Sweep.h>
Public Member Functions
Sweep ()
Default Constructor.
Sweep (System< D > &system)
Constructor, creates assocation with parent system.
~Sweep ()
Destructor.
void setSystem (System< D > &system)
Set association with parent System.
virtual void readParameters (std::istream &in)
Read parameters from param file.
Public Member Functions inherited from Pscf::SweepTmpl< BasisFieldState< D > >
~SweepTmpl ()
Destructor.
virtual void sweep ()
Iterate to solution.
void addParameterType (std::string name, int nId, ParameterModifier &modifier)
Declare a specialized parameter type.
void addParameterTypes (GArray< ParameterType > paramTypes)
Declare an array of specialized sweep parameter types.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
virtual void checkAllocation (BasisFieldState< D > &state)
Check allocation of fields in one state, allocate if necessary.
virtual void setup ()
Setup operation at the beginning of a sweep.
virtual void setParameters (double sNew)=0
Set system parameters to new values.
virtual void extrapolate (double sNew)
Create a guess for adjustable variables by continuation.
virtual int solve (bool isContinuation)
Call current iterator to solve SCFT problem.
virtual void reset ()
Reset system to previous solution after iterature failure.
virtual void getSolution ()
Update state(0) and output data after successful convergence.
virtual void cleanup ()
Cleanup operation at the beginning of a sweep.
bool hasSystem ()
Does an association with the parent System exist?
System< D > & system ()
Return the parent system by reference.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Protected Member Functions inherited from Pscf::SweepTmpl< BasisFieldState< D > >
SweepTmpl (int historyCapacity)
Constructor (protected).
BasisFieldState< D > & state (int i)
Get reference to a stored state, with i=0 being most recent.
double s (int i) const
Get the value of s for a stored solution, with i = 0 most recent.
double c (int i) const
Get a coefficient of a previous state in a continuation.
int historySize () const
Get the current number of stored previous states.
int historyCapacity () const
Get the maximum number of stored previous states.
int nAccept () const
Get the number of converged solutions accepted thus far.
void initialize ()
Initialize variables that track history of solutions.
virtual void checkAllocation (BasisFieldState< D > &state)=0
Check allocation of one state, allocate if necessary.
void setCoefficients (double sNew)
Compute coefficients of previous states for continuation.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
bool writeCRGrid_
Should concentration fields be written to file in r-grid format?
bool writeCBasis_
Should concentration fields be written to file in basis format?
bool writeWRGrid_
Should converged w fields be written to file in r-grid format?
Protected Attributes inherited from Pscf::SweepTmpl< BasisFieldState< D > >
int ns_
Number of steps.
std::string baseFileName_
Base name for output files.
GArray< ParameterType > parameterTypes_
Array of specialized parameter types.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<int D>
class Pscf::Rpc::Sweep< D >
Solve a sequence of SCFT problems along a line in parameter space.
See also: Manual page
Definition at line 27 of file rpc/scft/sweep/Sweep.h.
Constructor & Destructor Documentation
Sweep() [1/2]
template<int D> Pscf::Rpc::Sweep< D >::Sweep ()
Default Constructor.
Definition at line 31 of file rpc/scft/sweep/Sweep.tpp.
References Pscf::SweepTmpl< BasisFieldState< D > >::SweepTmpl(), writeCBasis_, writeCRGrid_, and writeWRGrid_.
Referenced by Pscf::Rpc::LinearSweep< D >::LinearSweep().
Sweep() [2/2]
template<int D> Pscf::Rpc::Sweep< D >::Sweep (System< D > & system)
Constructor, creates assocation with parent system.
Parameters
system reference to parent system
Definition at line 43 of file rpc/scft/sweep/Sweep.tpp.
References Pscf::SweepTmpl< BasisFieldState< D > >::addParameterTypes(), Pscf::SweepTmpl< BasisFieldState< D > >::SweepTmpl(), system(), writeCBasis_, writeCRGrid_, and writeWRGrid_.
~Sweep()
template<int D> Pscf::Rpc::Sweep< D >::~Sweep ()
Destructor.
Definition at line 60 of file rpc/scft/sweep/Sweep.tpp.
Member Function Documentation
setSystem()
template<int D> void Pscf::Rpc::Sweep< D >::setSystem (System< D > & system)
Set association with parent System.
Call for objects created with default constructor.
Parameters
system reference to parent system
Definition at line 67 of file rpc/scft/sweep/Sweep.tpp.
References system().
readParameters()
template<int D> void Pscf::Rpc::Sweep< D >::readParameters (std::istream & in) virtual
Read parameters from param file.
Parameters
in parameter file input stream
Reimplemented from Pscf::SweepTmpl< BasisFieldState< D > >.
Reimplemented in Pscf::Rpc::LinearSweep< D >.
Definition at line 74 of file rpc/scft/sweep/Sweep.tpp.
References readOptional(), readParameters(), Pscf::SweepTmpl< BasisFieldState< D > >::SweepTmpl(), writeCBasis_, writeCRGrid_, and writeWRGrid_.
Referenced by Pscf::Rpc::LinearSweep< D >::readParameters(), and readParameters().
checkAllocation()
template<int D> void Pscf::Rpc::Sweep< D >::checkAllocation (BasisFieldState< D > & state) protected virtual
Check allocation of fields in one state, allocate if necessary.
Parameters
state object that represents a stored state of the system.
Definition at line 89 of file rpc/scft/sweep/Sweep.tpp.
References hasSystem(), Pscf::SweepTmpl< BasisFieldState< D > >::state(), system(), and UTIL_CHECK.
Referenced by setup().
setup()
template<int D> void Pscf::Rpc::Sweep< D >::setup () protected virtual
Setup operation at the beginning of a sweep.
Implements Pscf::SweepTmpl< BasisFieldState< D > >.
Reimplemented in Pscf::Rpc::LinearSweep< D >.
Definition at line 101 of file rpc/scft/sweep/Sweep.tpp.
References Pscf::SweepTmpl< BasisFieldState< D > >::baseFileName_, checkAllocation(), Pscf::SweepTmpl< BasisFieldState< D > >::initialize(), and system().
Referenced by Pscf::Rpc::LinearSweep< D >::setup().
setParameters()
template<int D> void Pscf::Rpc::Sweep< D >::setParameters (double sNew) protected pure virtual
Set system parameters to new values.
Parameters
sNew contour variable value for new trial solution.
Implements Pscf::SweepTmpl< BasisFieldState< D > >.
Implemented in Pscf::Rpc::LinearSweep< D >.
Definition at line 120 of file rpc/scft/sweep/Sweep.tpp.
References Pscf::SweepTmpl< BasisFieldState< D > >::s(), and UTIL_THROW.
extrapolate()
template<int D> void Pscf::Rpc::Sweep< D >::extrapolate (double sNew) protected virtual
Create a guess for adjustable variables by continuation.
The "adjustable variables" in a standard SCFT problem are omega fields and adjustable unit cell parameters, i.e., variables that are adjusted by the iterator.
Parameters
sNew contour variable value for new trial solution.
Implements Pscf::SweepTmpl< BasisFieldState< D > >.
Definition at line 130 of file rpc/scft/sweep/Sweep.tpp.
References Pscf::SweepTmpl< BasisFieldState< D > >::c(), Pscf::SweepTmpl< BasisFieldState< D > >::historyCapacity(), Pscf::SweepTmpl< BasisFieldState< D > >::historySize(), Pscf::SweepTmpl< BasisFieldState< D > >::setCoefficients(), Util::FSArray< Data, Capacity >::size(), Pscf::SweepTmpl< BasisFieldState< D > >::state(), system(), and UTIL_CHECK.
solve()
template<int D> int Pscf::Rpc::Sweep< D >::solve (bool isContinuation) protected virtual
Call current iterator to solve SCFT problem.
Parameters
isContinuation If true, use information from previous states
Returns
0 for sucessful solution, 1 on failure to converge.
Implements Pscf::SweepTmpl< BasisFieldState< D > >.
Definition at line 231 of file rpc/scft/sweep/Sweep.tpp.
References system().
reset()
template<int D> void Pscf::Rpc::Sweep< D >::reset () protected virtual
Reset system to previous solution after iterature failure.
The implementation of this function should reset the system state to correspond to that stored in state(0).
Implements Pscf::SweepTmpl< BasisFieldState< D > >.
Definition at line 241 of file rpc/scft/sweep/Sweep.tpp.
References Pscf::SweepTmpl< BasisFieldState< D > >::state(), and system().
getSolution()
template<int D> void Pscf::Rpc::Sweep< D >::getSolution () protected virtual
Update state(0) and output data after successful convergence.
The implementation of this function should copy the current system state into state(0) and output any desired information about the current converged solution.
Implements Pscf::SweepTmpl< BasisFieldState< D > >.
Definition at line 255 of file rpc/scft/sweep/Sweep.tpp.
References Pscf::SweepTmpl< BasisFieldState< D > >::state(), and system().
cleanup()
template<int D> void Pscf::Rpc::Sweep< D >::cleanup () protected virtual
Cleanup operation at the beginning of a sweep.
Reimplemented from Pscf::SweepTmpl< BasisFieldState< D > >.
Definition at line 347 of file rpc/scft/sweep/Sweep.tpp.
hasSystem()
template<int D> bool Pscf::Rpc::Sweep< D >::hasSystem () inline protected
Does an association with the parent System exist?
Definition at line 143 of file rpc/scft/sweep/Sweep.h.
Referenced by checkAllocation(), and Pscf::Rpc::LinearSweep< D >::setup().
system()
template<int D> System< D > & Pscf::Rpc::Sweep< D >::system () inline protected
Return the parent system by reference.
Definition at line 149 of file rpc/scft/sweep/Sweep.h.
References UTIL_CHECK.
Referenced by checkAllocation(), extrapolate(), getSolution(), Pscf::Rpc::LinearSweep< D >::LinearSweep(), reset(), setSystem(), Pscf::Rpc::LinearSweep< D >::setup(), setup(), solve(), and Sweep().
readOptional()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
Referenced by readParameters().
Member Data Documentation
writeCRGrid_
template<int D> bool Pscf::Rpc::Sweep< D >::writeCRGrid_ protected
Should concentration fields be written to file in r-grid format?
Definition at line 162 of file rpc/scft/sweep/Sweep.h.
Referenced by readParameters(), Sweep(), and Sweep().
writeCBasis_
template<int D> bool Pscf::Rpc::Sweep< D >::writeCBasis_ protected
Should concentration fields be written to file in basis format?
Definition at line 167 of file rpc/scft/sweep/Sweep.h.
Referenced by readParameters(), Sweep(), and Sweep().
writeWRGrid_
template<int D> bool Pscf::Rpc::Sweep< D >::writeWRGrid_ protected
Should converged w fields be written to file in r-grid format?
Definition at line 172 of file rpc/scft/sweep/Sweep.h.
Referenced by readParameters(), Sweep(), and Sweep().
The documentation for this class was generated from the following files:
rpc/scft/sweep/Sweep.h
rpc/scft/sweep/Sweep.tpp