PSCF: Pscf::Rpg::FieldState< D, FT > Class Template Reference
Pscf::Rpg::FieldState< D, FT > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Self-Consistent Field Theory (SCFT) » Sweep
Record of a state of a System (fields + unit cell).
#include <FieldState.h>
Public Member Functions
Construction and Destruction
FieldState ()
Default constructor.
FieldState (System< D > &system)
Constructor, creates association with a System.
~FieldState ()
Destructor.
void setSystem (System< D > &system)
Set association with System, after default construction.
Accessors
const DArray< FT > & fields () const
Get array of all fields by const reference.
DArray< FT > & fields ()
Get array of all chemical potential fields (non-const reference).
const FT & field (int monomerId) const
Get a field for a single monomer type by const reference.
FT & field (int monomerId)
Get field for a specific monomer type (non-const reference).
const UnitCell< D > & unitCell () const
Get UnitCell (i.e., lattice type and parameters) by const reference.
UnitCell< D > & unitCell ()
Get the UnitCell by non-const reference.
bool hasSystem ()
Has a system been set?
System< D > & system ()
Get associated System by reference.
Detailed Description
template<int D, class FT>
class Pscf::Rpg::FieldState< D, FT >
Record of a state of a System (fields + unit cell).
An array of field objects of class FT
a UnitCell<D> object
The template parameter D is the dimension of space, while parameter FT is a field type.
A FieldState can be used to store either chemical potential or concentration fields, along with an associated UnitCell<D>. Different choices for class FT can be used to store fields in symmetry-adapted basis function, r-grid or k-grid format.
Definition at line 42 of file rpg/scft/sweep/FieldState.h.
Constructor & Destructor Documentation
FieldState() [1/2]
template<int D, class FT> Pscf::Rpg::FieldState< D, FT >::FieldState ()
Default constructor.
Definition at line 34 of file rpg/scft/sweep/FieldState.tpp.
FieldState() [2/2]
template<int D, class FT> Pscf::Rpg::FieldState< D, FT >::FieldState (System< D > & system)
Constructor, creates association with a System.
Equivalent to default construction followed by setSystem(system).
Parameters
system associated parent System<D> object.
Definition at line 44 of file rpg/scft/sweep/FieldState.tpp.
References setSystem(), and system().
~FieldState()
template<int D, class FT> Pscf::Rpg::FieldState< D, FT >::~FieldState ()
Destructor.
Definition at line 54 of file rpg/scft/sweep/FieldState.tpp.
Member Function Documentation
setSystem()
template<int D, class FT> void Pscf::Rpg::FieldState< D, FT >::setSystem (System< D > & system)
Set association with System, after default construction.
Parameters
system associated parent System<D> object.
Definition at line 61 of file rpg/scft/sweep/FieldState.tpp.
References hasSystem(), system(), and UTIL_CHECK.
Referenced by FieldState().
fields() [1/2]
template<int D, class FT> const DArray< FT > & Pscf::Rpg::FieldState< D, FT >::fields () const inline
Get array of all fields by const reference.
The array capacity is equal to the number of monomer types.
Definition at line 156 of file rpg/scft/sweep/FieldState.h.
fields() [2/2]
template<int D, class FT> DArray< FT > & Pscf::Rpg::FieldState< D, FT >::fields () inline
Get array of all chemical potential fields (non-const reference).
The array capacity is equal to the number of monomer types.
Definition at line 162 of file rpg/scft/sweep/FieldState.h.
field() [1/2]
template<int D, class FT> FT const & Pscf::Rpg::FieldState< D, FT >::field (int monomerId) const inline
Get a field for a single monomer type by const reference.
Parameters
monomerId integer monomer type index
Definition at line 168 of file rpg/scft/sweep/FieldState.h.
field() [2/2]
template<int D, class FT> FT & Pscf::Rpg::FieldState< D, FT >::field (int monomerId) inline
Get field for a specific monomer type (non-const reference).
Parameters
monomerId integer monomer type index
Definition at line 173 of file rpg/scft/sweep/FieldState.h.
unitCell() [1/2]
template<int D, class FT> UnitCell< D > const & Pscf::Rpg::FieldState< D, FT >::unitCell () const inline
Get UnitCell (i.e., lattice type and parameters) by const reference.
Definition at line 179 of file rpg/scft/sweep/FieldState.h.
unitCell() [2/2]
template<int D, class FT> UnitCell< D > & Pscf::Rpg::FieldState< D, FT >::unitCell () inline
Get the UnitCell by non-const reference.
Definition at line 185 of file rpg/scft/sweep/FieldState.h.
hasSystem()
template<int D, class FT> bool Pscf::Rpg::FieldState< D, FT >::hasSystem () inline protected
Has a system been set?
Definition at line 193 of file rpg/scft/sweep/FieldState.h.
Referenced by setSystem().
system()
template<int D, class FT> System< D > & Pscf::Rpg::FieldState< D, FT >::system () inline protected
Get associated System by reference.
Definition at line 199 of file rpg/scft/sweep/FieldState.h.
Referenced by FieldState(), and setSystem().
The documentation for this class was generated from the following files:
rpg/scft/sweep/FieldState.h
rpg/scft/sweep/FieldState.tpp