PSCF: Pscf::PolymerSpecies Class Reference
Pscf::PolymerSpecies Class Reference abstract
Pscf namespace » Pscf Common » Chemical Structure
Descriptor for a linear or acyclic branched block polymer.
#include <PolymerSpecies.h>
Public Member Functions
PolymerSpecies ()
Constructor.
~PolymerSpecies ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters and initialize.
Accessors (objects, by reference)
virtual Edge & edge (int id)=0
Get a specified Edge (block descriptor) by non-const reference.
virtual Edge const & edge (int id) const =0
Get a specified Edge (block descriptor) by const reference.
const Vertex & vertex (int id) const
Get a specified Vertex by const reference.
Pair< int > const & propagatorId (int id) const
Get a propagator identifier, indexed by order of computation.
Pair< int > const & path (int is, int it) const
Get an id for a propagator from one vertex towards a target.
Accessors (by value)
int nBlock () const
Number of blocks.
int nVertex () const
Number of vertices (junctions and chain ends).
int nPropagator () const
Number of propagators (2*nBlock).
double length () const
Sum of the lengths of all blocks in the polymer.
PolymerType::Enum type () const
Get Polymer type (Branched or Linear)
Public Member Functions inherited from Pscf::Species
Species ()
Default constructor.
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble ()
Get the statistical ensemble for this species (open or closed).
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
virtual void allocateBlocks ()=0
Allocate array of blocks.
virtual void readBlocks (std::istream &in)=0
Read array of blocks from parameter file.
virtual void makePlan ()
Make a plan for order in which propagators should be computed.
void makePaths ()
Create a matrix of vertex-to-vertex path signposts.
void isValid ()
Check validity of graph.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Pscf::Species
enum Ensemble
Statistical ensemble for number of molecules.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Attributes inherited from Pscf::Species
double phi_
Volume fraction, set by either setPhi or a compute function.
double mu_
Chemical potential, set by either setPhi or a compute function.
double q_
Partition function, set in subclass by a compute function.
Ensemble ensemble_
Statistical ensemble for this species (open or closed).
Detailed Description
Descriptor for a linear or acyclic branched block polymer.
A PolymerSpecies has an array of Vertex objects and an associated array of Edge objects that, together, provide a description of the connectivity and properties of blocks with a polymer polymer, and of the associated graph. A PolymerSpecies object is a descriptor for for a polymer species, but does not contain functions or data structures required to solve the modified diffusion equation (MDE), and so is not a solver class.
Each implementation level sub-namespace of Pscf (R1d, Rpc or Rpg) contains a concrete class named Polymer that is a subclass of Pscf::Polymer species, and that acts as both a descriptor and MDE solver for the associated species. Each such implementation level sub-namespace also contains a class named Block that is a subclass of Pscf::Edge, and that is a descriptor and MDE solver for a single block. The Polymer class in each such namespace is a subclass of a class template instantiation PolymerTmpl<Block> that is itself a subclass of PolymerSpecies.
Each PolymerTmpl<Block> class has a private member variable that is an array of Block objects. The PolymerTmpl class template defines implementations of the pure virtual edge(int id) member functions declared by PolymerSpecies, which return a single element of this array as a reference to an Edge.
Definition at line 56 of file PolymerSpecies.h.
Constructor & Destructor Documentation
PolymerSpecies()
Pscf::PolymerSpecies::PolymerSpecies ()
Constructor.
Definition at line 25 of file PolymerSpecies.cpp.
References Util::ParamComposite::setClassName().
~PolymerSpecies()
Pscf::PolymerSpecies::~PolymerSpecies ()
Destructor.
Definition at line 37 of file PolymerSpecies.cpp.
Member Function Documentation
readParameters()
void Pscf::PolymerSpecies::readParameters (std::istream & in) virtual
Read parameters and initialize.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Reimplemented in Pscf::PolymerTmpl< Block >, and Pscf::PolymerTmpl< Block< D > >.
Definition at line 40 of file PolymerSpecies.cpp.
References allocateBlocks(), edge(), Pscf::Species::ensemble_, isValid(), makePaths(), makePlan(), Pscf::Species::mu_, Pscf::Species::phi_, Util::ParamComposite::read(), readBlocks(), Util::ParamComposite::readOptional(), Pscf::Edge::setId(), Pscf::Edge::setPolymerType(), Pscf::Edge::setVertexIds(), and Pscf::Edge::vertexId().
Referenced by Pscf::PolymerTmpl< Block >::readParameters().
edge() [1/2]
virtual Edge & Pscf::PolymerSpecies::edge (int id) pure virtual
Get a specified Edge (block descriptor) by non-const reference.
This function is implemented by the class template Pscf::PolymerTmpl<class Block>, which is derived from Pscf::Edge.
Parameters
id block index, 0 <= id < nBlock
Implemented in Pscf::PolymerTmpl< Block >, and Pscf::PolymerTmpl< Block< D > >.
Referenced by Pscf::EdgeIterator::begin(), isValid(), length(), makePlan(), Pscf::EdgeIterator::operator++(), Pscf::VertexIterator::operator++(), and readParameters().
edge() [2/2]
virtual Edge const & Pscf::PolymerSpecies::edge (int id) const pure virtual
Get a specified Edge (block descriptor) by const reference.
This function is implemented by the class template Pscf::PolymerTmpl<class Block>, which is derived from Pscf::Edge.
Parameters
id block index, 0 <= id < nBlock
Implemented in Pscf::PolymerTmpl< Block >, and Pscf::PolymerTmpl< Block< D > >.
vertex()
Vertex const & Pscf::PolymerSpecies::vertex (int id) const inline
Get a specified Vertex by const reference.
Both chain ends and junctions are vertices.
Parameters
id vertex index, 0 <= id < nVertex
Definition at line 265 of file PolymerSpecies.h.
Referenced by isValid().
propagatorId()
Pair< int > const & Pscf::PolymerSpecies::propagatorId (int id) const inline
Get a propagator identifier, indexed by order of computation.
The return value is a pair of integers that identifies a directed edge, or a propagator. The first integer is a block index between 0 and nBlock - 1, and the second is a propagator direction id, which must be 0 or 1. By convention, direction 0 of edge propagates from vertex edge(i).vertexId(0) to vertex edge(i).vertexId(1), while direction 1 propagates in the reverse direction.
Parameters
id propagator index, in order of computation plan
Definition at line 272 of file PolymerSpecies.h.
References UTIL_CHECK.
Referenced by makePlan().
path()
Pair< int > const & Pscf::PolymerSpecies::path (int is, int it) const inline
Get an id for a propagator from one vertex towards a target.
For is != it, the return value is an identifier for an outgoing propagator that begins at the source vertex (vertex index is) and is the first edge of the directed path that leads from the source vertex to the target vertex (vertex id it). The return value is a pair of integers analogous to that returned by the propagatorId(int) member function, for which the first element is a block index and the second element is a direction id (0 or 1) for the propagator direction for that block that is outgoing from the source vertex.
For the case is == it, the return value is a pair [-1, -1].
Parameters
is vertex index of the source vertex
it vertex index of the target vertex
Definition at line 283 of file PolymerSpecies.h.
References UTIL_CHECK.
Referenced by pscfpp.file.File::__eq__(), pscfpp.file.Directory::__init__(), pscfpp.file.File::__init__(), pscfpp.make.MakeMaker::__init__(), pscfpp.file.Directory::__repr__(), pscfpp.file.File::__repr__(), pscfpp.file.Directory::__str__(), pscfpp.file.File::__str__(), Pscf::EdgeIterator::begin(), pscfpp.file.Directory::filenames(), pscfpp.make.MakeMaker::find(), pscfpp.file.File::open(), Pscf::EdgeIterator::operator++(), Pscf::VertexIterator::operator++(), and pscfpp.file.Directory::xml().
nBlock()
int Pscf::PolymerSpecies::nBlock () const inline
Number of blocks.
Definition at line 252 of file PolymerSpecies.h.
nVertex()
int Pscf::PolymerSpecies::nVertex () const inline
Number of vertices (junctions and chain ends).
A theorem of graph theory tells us that, for any linear or acyclic branched polymer, nVertex = nBlock + 1.
Definition at line 246 of file PolymerSpecies.h.
nPropagator()
int Pscf::PolymerSpecies::nPropagator () const inline
Number of propagators (2*nBlock).
Definition at line 258 of file PolymerSpecies.h.
length()
double Pscf::PolymerSpecies::length () const
Sum of the lengths of all blocks in the polymer.
Definition at line 407 of file PolymerSpecies.cpp.
References edge(), and Pscf::Edge::length().
type()
PolymerType::Enum Pscf::PolymerSpecies::type () const inline
Get Polymer type (Branched or Linear)
Definition at line 296 of file PolymerSpecies.h.
Referenced by pscfpp.field.Field::__init__(), pscfpp.field.Field::__str__(), and pscfpp.field.Field::read().
allocateBlocks()
virtual void Pscf::PolymerSpecies::allocateBlocks () protected pure virtual
Allocate array of blocks.
Implemented in Pscf::PolymerTmpl< Block >, and Pscf::PolymerTmpl< Block< D > >.
Referenced by readParameters().
readBlocks()
virtual void Pscf::PolymerSpecies::readBlocks (std::istream & in) protected pure virtual
Read array of blocks from parameter file.
Parameters
in parameter input stream
Implemented in Pscf::PolymerTmpl< Block >, and Pscf::PolymerTmpl< Block< D > >.
Referenced by readParameters().
makePlan()
void Pscf::PolymerSpecies::makePlan () protected virtual
Make a plan for order in which propagators should be computed.
The algorithm creates a plan for computing propagators in an that guarantees that the inital conditions required for each propagator are known before it is processed. The algorithm is works for any acyclic branched block copolymer. This function is called in the default implementation of readParameters, and must be called the readParameters method of any subclass.
Definition at line 118 of file PolymerSpecies.cpp.
References Util::DMatrix< Data >::allocate(), edge(), Pscf::Vertex::inPropagatorId(), propagatorId(), Pscf::Vertex::size(), UTIL_THROW, and Pscf::Edge::vertexId().
Referenced by readParameters().
makePaths()
void Pscf::PolymerSpecies::makePaths () protected
Create a matrix of vertex-to-vertex path signposts.
This function constructs the data structure that is accessed by the paths member function.
Definition at line 169 of file PolymerSpecies.cpp.
Referenced by readParameters().
isValid()
void Pscf::PolymerSpecies::isValid () protected
Check validity of graph.
Definition at line 334 of file PolymerSpecies.cpp.
References edge(), Pscf::Vertex::inPropagatorId(), Pscf::Vertex::outPropagatorId(), Pscf::Vertex::size(), UTIL_CHECK, vertex(), and Pscf::Edge::vertexId().
Referenced by readParameters().
The documentation for this class was generated from the following files:
PolymerSpecies.h
PolymerSpecies.cpp