PSCF: Pscf::Rpg::AverageListAnalyzer< D > Class Template Reference
Pscf::Rpg::AverageListAnalyzer< D > Class Template Reference abstract
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Field Theoretic Simulation (FTS) » Analyzers
Analyze averages and block averages of several real variables.
#include <AverageListAnalyzer.h>
Public Member Functions
AverageListAnalyzer (System< D > &system)
Constructor.
virtual ~AverageListAnalyzer ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval, outputFileName and (optionally) nSamplePerOutput.
virtual void clear ()
Clear accumulators.
virtual void setup ()
Setup before loop.
virtual void sample (long iStep)
Compute a sampled value and update the accumulator.
virtual void output ()
Write final results to file after a simulation.
int nSamplePerOutput () const
Get value of nSamplePerOutput.
int nValue () const
Get number of variables.
const std::string & name (int i) const
Get name associated with value.
const Average & accumulator (int i) const
Get Average accumulator for a specific value.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Public Member Functions inherited from Pscf::Rpg::Analyzer< D >
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Public Attributes
System< D > * systemPtr_
Pointer to the parent system.
Protected Member Functions
void initializeAccumulators (int nValue)
Instantiate Average accumulators and set nSamplePerOutput set nValue.
void clearAccumulators ()
Clear internal state of the accumulator.
void setName (int i, std::string name)
Set name of variable.
void setValue (int i, double value)
Set current value, used by compute function.
virtual void compute ()=0
Compute value of sampled quantity.
double value (int i) const
Get current value of a specific variable.
void updateAccumulators (long iStep)
Add current value to accumulator, output block average if needed.
void outputAccumulators ()
Write results of statistical analysis to files.
System< D > & system ()
Return reference to parent system.
Protected Member Functions inherited from Pscf::Rpg::Analyzer< D >
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Pscf::Rpg::Analyzer< D >
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Pscf::Rpg::Analyzer< D >
static long baseInterval
The interval for every Analyzer must be a multiple of baseInterval.
Detailed Description
template<int D>
class Pscf::Rpg::AverageListAnalyzer< D >
Analyze averages and block averages of several real variables.
This class evaluates the average of several sampled real variables, and optionally writes block averages to a data file during a simulation. It is intended for use as a base class for Analyzers that evaluate averages and (optionally) block averages for several physical variables.
Definition at line 33 of file rpg/fts/analyzer/AverageListAnalyzer.h.
Constructor & Destructor Documentation
AverageListAnalyzer()
template<int D> Pscf::Rpg::AverageListAnalyzer< D >::AverageListAnalyzer (System< D > & system)
Constructor.
Parameters
system parent SystemType object.
Definition at line 29 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References Pscf::Rpg::Analyzer< D >::Analyzer(), system(), and systemPtr_.
Referenced by Pscf::Rpg::HamiltonianAnalyzer< D >::HamiltonianAnalyzer().
~AverageListAnalyzer()
template<int D> Pscf::Rpg::AverageListAnalyzer< D >::~AverageListAnalyzer () virtual
Destructor.
Definition at line 41 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::readParameters (std::istream & in) virtual
Read interval, outputFileName and (optionally) nSamplePerOutput.
The optional variable nSamplePerOutput defaults to 0, which disables computation and output of block averages. Setting nSamplePerOutput = 1 outputs every sampled value.
Parameters
in input parameter file
Reimplemented from Pscf::Rpg::Analyzer< D >.
Reimplemented in Pscf::Rpg::HamiltonianAnalyzer< D >.
Definition at line 48 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References nSamplePerOutput(), Pscf::Rpg::Analyzer< D >::outputFileName(), readOptional(), Pscf::Rpg::Analyzer< D >::readParameters(), and system().
Referenced by Pscf::Rpg::HamiltonianAnalyzer< D >::readParameters().
clear()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::clear () virtual
Clear accumulators.
Definition at line 65 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References clearAccumulators(), and UTIL_CHECK.
Referenced by setup().
setup()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::setup () virtual
Setup before loop.
Opens an output file, if nSamplePerOutput > 0.
Reimplemented from Pscf::Rpg::Analyzer< D >.
Definition at line 75 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References clear(), and UTIL_CHECK.
sample()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::sample (long iStep) virtual
Compute a sampled value and update the accumulator.
Parameters
iStep MD time step index
Implements Pscf::Rpg::Analyzer< D >.
Definition at line 85 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References compute(), Pscf::Rpg::Analyzer< D >::isAtInterval(), updateAccumulators(), and UTIL_CHECK.
output()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::output () virtual
Write final results to file after a simulation.
Reimplemented from Pscf::Rpg::Analyzer< D >.
Definition at line 97 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References outputAccumulators(), Pscf::Rpg::Analyzer< D >::outputFileName(), system(), UTIL_CHECK, and Util::ParamComposite::writeParam().
nSamplePerOutput()
template<int D> int Pscf::Rpg::AverageListAnalyzer< D >::nSamplePerOutput () const inline
Get value of nSamplePerOutput.
If nSamplePerOutput == 0, output of block averages is disabled. For nSamplePerOutput > 0, the value is the number of sampled values averaged in each block.
Definition at line 244 of file rpg/fts/analyzer/AverageListAnalyzer.h.
Referenced by readParameters().
nValue()
template<int D> int Pscf::Rpg::AverageListAnalyzer< D >::nValue () const inline
Get number of variables.
Definition at line 251 of file rpg/fts/analyzer/AverageListAnalyzer.h.
References UTIL_CHECK.
Referenced by initializeAccumulators(), outputAccumulators(), and updateAccumulators().
name()
template<int D> const std::string & Pscf::Rpg::AverageListAnalyzer< D >::name (int i) const inline
Get name associated with value.
Call only on processors that have accumulators.
Parameters
i integer index of name/value pair.
Definition at line 272 of file rpg/fts/analyzer/AverageListAnalyzer.h.
References UTIL_CHECK.
Referenced by setName().
accumulator()
template<int D> const Average & Pscf::Rpg::AverageListAnalyzer< D >::accumulator (int i) const inline
Get Average accumulator for a specific value.
Parameters
i integer index of value.
Definition at line 283 of file rpg/fts/analyzer/AverageListAnalyzer.h.
References UTIL_CHECK.
initializeAccumulators()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::initializeAccumulators (int nValue) protected
Instantiate Average accumulators and set nSamplePerOutput set nValue.
Set nValue and allocate arrays with dimensions nValue.
Precondition
hasAccumulator == false
nSamplePerOutput >= 0
Definition at line 122 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References clearAccumulators(), nValue(), and UTIL_CHECK.
Referenced by Pscf::Rpg::HamiltonianAnalyzer< D >::readParameters().
clearAccumulators()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::clearAccumulators () protected
Clear internal state of the accumulator.
Precondition
hasAccumulator == true
Definition at line 148 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References UTIL_CHECK.
Referenced by clear(), and initializeAccumulators().
setName()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::setName (int i, std::string name) protected
Set name of variable.
Call only on master.
Parameters
i integer index of variable
name name of variable number i
Definition at line 158 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References name(), and UTIL_CHECK.
Referenced by Pscf::Rpg::HamiltonianAnalyzer< D >::readParameters().
setValue()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::setValue (int i, double value) inline protected
Set current value, used by compute function.
Parameters
i integer index of variable
value current value of variable
Definition at line 294 of file rpg/fts/analyzer/AverageListAnalyzer.h.
References UTIL_CHECK, and value().
Referenced by Pscf::Rpg::HamiltonianAnalyzer< D >::compute().
compute()
template<int D> virtual void Pscf::Rpg::AverageListAnalyzer< D >::compute () protected pure virtual
Compute value of sampled quantity.
Call on all processors.
Implemented in Pscf::Rpg::HamiltonianAnalyzer< D >.
Referenced by sample().
value()
template<int D> double Pscf::Rpg::AverageListAnalyzer< D >::value (int i) const inline protected
Get current value of a specific variable.
Call only on master.
Parameters
i integer index of variable.
Definition at line 261 of file rpg/fts/analyzer/AverageListAnalyzer.h.
References UTIL_CHECK.
Referenced by setValue(), and updateAccumulators().
updateAccumulators()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::updateAccumulators (long iStep) protected
Add current value to accumulator, output block average if needed.
Parameters
iStep simulation step counter
Definition at line 169 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References Pscf::Rpg::Analyzer< D >::interval(), nValue(), UTIL_CHECK, and value().
Referenced by sample().
outputAccumulators()
template<int D> void Pscf::Rpg::AverageListAnalyzer< D >::outputAccumulators () protected
Write results of statistical analysis to files.
Definition at line 201 of file rpg/fts/analyzer/AverageListAnalyzer.tpp.
References nValue(), Pscf::Rpg::Analyzer< D >::outputFileName(), system(), and UTIL_CHECK.
Referenced by output().
system()
template<int D> System< D > & Pscf::Rpg::AverageListAnalyzer< D >::system () inline protected
Return reference to parent system.
Definition at line 303 of file rpg/fts/analyzer/AverageListAnalyzer.h.
References systemPtr_.
Referenced by AverageListAnalyzer(), output(), outputAccumulators(), and readParameters().
read()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value)
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 305 of file ParamComposite.h.
readOptional()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
Referenced by readParameters().
Member Data Documentation
systemPtr_
template<int D> System<D>* Pscf::Rpg::AverageListAnalyzer< D >::systemPtr_
Pointer to the parent system.
Definition at line 134 of file rpg/fts/analyzer/AverageListAnalyzer.h.
Referenced by AverageListAnalyzer(), and system().
The documentation for this class was generated from the following files:
rpg/fts/analyzer/AverageListAnalyzer.h
rpg/fts/analyzer/AverageListAnalyzer.tpp