PSCF: Pscf::Prdc::Cpu::RField< D > Class Template Reference
Pscf::Prdc::Cpu::RField< D > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CPU)
Field of real double precision values on an FFT mesh.
#include <RField.h>
Public Types
typedef double ElementType
Type of each array element.
Public Member Functions
RField ()
Default constructor.
RField (const RField &other)
Copy constructor.
virtual ~RField ()
Destructor.
RField & operator= (const RField &other)
Assignment operator.
void allocate (IntVec< D > const &meshDimensions)
Allocate the underlying C array for an FFT grid.
virtual void deallocate ()
Deallocate memory and return to empty state.
const IntVec< D > & meshDimensions () const
Return mesh dimensions by constant reference.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a Field to/from an Archive.
Public Member Functions inherited from Pscf::Prdc::Cpu::FftwDArray< double >
FftwDArray ()
Default constructor.
virtual ~FftwDArray ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array.
bool isAllocated () const
Return true if the FftwDArray has been allocated, false otherwise.
void serialize (Archive &ar, const unsigned int version)
Serialize a FftwDArray to/from an Archive.
Public Member Functions inherited from Util::Array< double >
virtual ~Array ()
Destructor.
int capacity () const
Return allocated size.
void begin (ArrayIterator< double > &iterator)
Set an iterator to begin this Array.
void begin (ConstArrayIterator< double > &iterator) const
Set a const iterator to begin this Array.
double & operator[] (int i)
Get an element by non-const reference.
double const & operator[] (int i) const
Get an element by const reference.
double * cArray ()
Return a pointer to the underlying C array.
double const * cArray () const
Return pointer to const to the underlying C array.
Additional Inherited Members
Protected Member Functions inherited from Util::Array< double >
Array ()
Default constructor.
Protected Attributes inherited from Util::Array< double >
double * data_
Pointer to an array of Data elements.
int capacity_
Allocated size of the data_ array.
Detailed Description
template<int D>
class Pscf::Prdc::Cpu::RField< D >
Field of real double precision values on an FFT mesh.
Definition at line 26 of file rpc/solvers/Mixture.h.
Member Typedef Documentation
ElementType
template<int D> double Pscf::Prdc::Cpu::RField< D >::ElementType
Type of each array element.
Definition at line 36 of file cpu/RField.h.
Constructor & Destructor Documentation
RField() [1/2]
template<int D> Pscf::Prdc::Cuda::RField< D >::RField ()
Default constructor.
Definition at line 23 of file cpu/RField.tpp.
RField() [2/2]
template<int D> Pscf::Prdc::Cuda::RField< D >::RField (const RField< D > & other)
Copy constructor.
Allocates new memory and copies all elements by value.
Parameters
other the RField to be copied.
Definition at line 43 of file cpu/RField.tpp.
References Pscf::Prdc::Cpu::FftwDArray< Data >::isAllocated().
~RField()
template<int D> Pscf::Prdc::Cuda::RField< D >::~RField () virtual
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 32 of file cpu/RField.tpp.
Member Function Documentation
operator=()
template<int D> RField< D > & Pscf::Prdc::Cuda::RField< D >::operator= (const RField< D > & other)
Assignment operator.
If this Field is not allocated, allocates and copies all elements.
If this and the other Field are both allocated, the capacities must be exactly equal. If so, this method copies all elements.
Parameters
other the RHS RField
Definition at line 66 of file cpu/RField.tpp.
References Util::Array< Data >::capacity_, Pscf::Prdc::Cpu::FftwDArray< Data >::isAllocated(), UTIL_CHECK, and UTIL_THROW.
allocate()
template<int D> void Pscf::Prdc::Cuda::RField< D >::allocate (IntVec< D > const & meshDimensions)
Allocate the underlying C array for an FFT grid.
Exceptions
Exception if the RField is already allocated.
Parameters
meshDimensions vector of numbers of grid points per direction
Definition at line 94 of file cpu/RField.tpp.
References Pscf::Prdc::Cpu::FftwDArray< Data >::allocate(), and UTIL_CHECK.
Referenced by Pscf::Rpg::FourthOrderParameter< D >::compute(), Pscf::Rpg::MaxOrderParameter< D >::compute(), Pscf::Rpc::MaskGenFilm< D >::generate(), Pscf::Rpg::MaskGenFilm< D >::generate(), Pscf::Rpg::EinsteinCrystalPerturbation< D >::hamiltonian(), Pscf::Rpg::EinsteinCrystalPerturbation< D >::incrementDc(), Pscf::Prdc::Cuda::RField< D >::RField(), Pscf::Prdc::Cpu::FFT< D >::setup(), Pscf::Rpc::ExtGenFilm< D >::stressTerm(), Pscf::Rpc::MaskGenFilm< D >::stressTerm(), and Pscf::Rpg::MaskGenFilm< D >::stressTerm().
deallocate()
template<int D> void Pscf::Prdc::Cpu::RField< D >::deallocate () virtual
Deallocate memory and return to empty state.
Reimplemented from Pscf::Prdc::Cpu::FftwDArray< double >.
Definition at line 109 of file cpu/RField.tpp.
References Pscf::Prdc::Cpu::FftwDArray< Data >::deallocate().
meshDimensions()
template<int D> const IntVec< D > & Pscf::Prdc::Cuda::RField< D >::meshDimensions () const inline
Return mesh dimensions by constant reference.
Definition at line 112 of file cpu/RField.h.
Referenced by Pscf::Prdc::Cpu::FFT< D >::forwardTransform(), Pscf::Prdc::Cpu::FFT< D >::inverseTransformUnsafe(), Pscf::Prdc::Cuda::RField< D >::RField(), Pscf::Prdc::Cpu::FFT< D >::setup(), Pscf::Rpc::FieldIo< D >::writeFieldRGrid(), and Pscf::Rpg::FieldIo< D >::writeFieldRGrid().
serialize()
template<int D> template<class Archive > void Pscf::Prdc::Cuda::RField< D >::serialize (Archive & ar, const unsigned int version)
Serialize a Field to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 120 of file cpu/RField.h.
References Pscf::Prdc::Cpu::FftwDArray< Data >::serialize().
The documentation for this class was generated from the following files:
FieldBasisConverter.h
cpu/RField.h
FieldIoReal.h
rpc/fts/perturbation/EinsteinCrystalPerturbation.h
rpc/fts/perturbation/Perturbation.h
rpc/solvers/Mixture.h
cpu/RField.tpp
cuda/RField.h
cuda/RField.tpp