PSCF: Pscf::Pspg::RDFieldDft< D > Class Template Reference
Pscf::Pspg::RDFieldDft< D > Class Template Reference
Pscf namespace » Periodic Pseudo-Spectral (GPU) » Fields
Fourier transform of a real field on an FFT mesh.
#include <RDFieldDft.h>
Public Member Functions
RDFieldDft ()
Default constructor.
RDFieldDft (const RDFieldDft< D > &other)
Copy constructor.
virtual ~RDFieldDft ()
Destructor.
RDFieldDft< D > & operator= (const RDFieldDft< D > &other)
Assignment operator.
void allocate (const IntVec< D > &meshDimensions)
Allocate the underlying C array for an FFT grid.
const IntVec< D > & meshDimensions () const
Return vector of mesh dimensions by constant reference.
const IntVec< D > & dftDimensions () const
Return vector of dft (Fourier) grid dimensions by constant reference.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a Field to/from an Archive.
Public Member Functions inherited from Pscf::Pspg::DField< cudaComplex >
DField ()
Default constructor.
virtual ~DField ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array.
void deallocate ()
Dellocate the underlying C array.
bool isAllocated () const
Return true if the Field has been allocated, false otherwise.
int capacity () const
Return allocated size.
cudaComplex * cDField ()
Return pointer to underlying C array.
const cudaComplex * cDField () const
Return pointer to const to underlying C array.
Additional Inherited Members
Protected Attributes inherited from Pscf::Pspg::DField< cudaComplex >
cudaComplex * data_
Serialize a Field to/from an Archive.
int capacity_
Allocated size of the data_ array.
Detailed Description
template<int D>
class Pscf::Pspg::RDFieldDft< D >
Fourier transform of a real field on an FFT mesh.
Definition at line 31 of file RDFieldDft.h.
Constructor & Destructor Documentation
template<int D> Pscf::Pspg::RDFieldDft< D >::RDFieldDft ()
Default constructor.
Definition at line 22 of file RDFieldDft.tpp.
template<int D> Pscf::Pspg::RDFieldDft< D >::RDFieldDft (const RDFieldDft< D > & other)
Copy constructor.
Allocates new memory and copies all elements by value.
Parameters
other the RFieldDft to be copied.
Definition at line 41 of file RDFieldDft.tpp.
References Pscf::Pspg::DField< cudaComplex >::capacity_, Pscf::Pspg::DField< cudaComplex >::cDField(), Pscf::Pspg::DField< cudaComplex >::data_, Pscf::Pspg::DField< cudaComplex >::isAllocated(), and UTIL_THROW.
template<int D> Pscf::Pspg::RDFieldDft< D >::~RDFieldDft () virtual
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 30 of file RDFieldDft.tpp.
Member Function Documentation
template<int D> RDFieldDft< D > & Pscf::Pspg::RDFieldDft< D >::operator= (const RDFieldDft< D > & other)
Assignment operator.
If this Field is not allocated, allocates and copies all elements.
If this and the other Field are both allocated, the capacities must be exactly equal. If so, this method copies all elements.
Parameters
other the RHS Field
Definition at line 66 of file RDFieldDft.tpp.
References Pscf::Pspg::RDFieldDft< D >::allocate(), Pscf::Pspg::DField< cudaComplex >::capacity(), Pscf::Pspg::DField< cudaComplex >::capacity_, Pscf::Pspg::DField< cudaComplex >::cDField(), Pscf::Pspg::DField< cudaComplex >::data_, Pscf::Pspg::DField< cudaComplex >::isAllocated(), and UTIL_THROW.
template<int D> void Pscf::Pspg::RDFieldDft< D >::allocate (const IntVec< D > & meshDimensions)
Allocate the underlying C array for an FFT grid.
Exceptions
Exception if the RFieldDft is already allocated.
Parameters
meshDimensions vector containing number of grid points in each direction
Definition at line 117 of file RDFieldDft.h.
References Pscf::Pspg::DField< Data >::allocate(), and UTIL_CHECK.
Referenced by Pscf::Pspg::RDFieldDft< D >::operator=().
template<int D> const IntVec< D > & Pscf::Pspg::RDFieldDft< D >::meshDimensions () const inline
Return vector of mesh dimensions by constant reference.
Definition at line 138 of file RDFieldDft.h.
Referenced by Pscf::Pspg::FFT< D >::setup(), and Pscf::Pspg::FFTBatched< D >::setup().
template<int D> const IntVec< D > & Pscf::Pspg::RDFieldDft< D >::dftDimensions () const inline
Return vector of dft (Fourier) grid dimensions by constant reference.
The last element of dftDimensions() and meshDimensions() differ by about a factor of two: dftDimension()[D-1] = meshDimensions()/2 + 1. For D > 1, other elements are equal.
Definition at line 145 of file RDFieldDft.h.
Referenced by Pscf::Pspg::FieldIo< D >::convertBasisToKGrid(), and Pscf::Pspg::FieldIo< D >::convertKGridToBasis().
template<int D> template<class Archive > void Pscf::Pspg::RDFieldDft< D >::serialize (Archive & ar, const unsigned int version)
Serialize a Field to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 153 of file RDFieldDft.h.
References UTIL_THROW.
The documentation for this class was generated from the following files:
RDFieldDft.h
RDFieldDft.tpp