PSCF: Util::End Class Reference
Util::End Class Reference
Util namespace » Parameter File IO
End bracket of a ParamComposite parameter block.
#include <End.h>
Public Member Functions
End ()
Constructor.
virtual ~End ()
Destructor.
virtual void readParam (std::istream &in)
Read the closing bracket.
virtual void writeParam (std::ostream &out) const
Write the closing bracket.
void resetParam ()
Do-nothing implementation of virtual resetParam function.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
End bracket of a ParamComposite parameter block.
Definition at line 24 of file End.h.
Constructor & Destructor Documentation
End()
Util::End::End ()
Constructor.
Definition at line 17 of file End.cpp.
~End()
Util::End::~End () virtual
Destructor.
Definition at line 24 of file End.cpp.
Member Function Documentation
readParam()
void Util::End::readParam (std::istream & in) virtual
Read the closing bracket.
Parameters
in input stream
Implements Util::ParamComponent.
Definition at line 30 of file End.cpp.
References Util::ParamComponent::echo(), Util::Log::file(), Util::MpiFileIo::isIoProcessor(), and writeParam().
Referenced by Util::ParamComposite::readEnd().
writeParam()
void Util::End::writeParam (std::ostream & out) const virtual
Write the closing bracket.
Parameters
out output stream
Implements Util::ParamComponent.
Definition at line 43 of file End.cpp.
References Util::ParamComponent::indent().
Referenced by Util::Manager< Data >::endReadManager(), Util::ParamComposite::load(), and readParam().
resetParam()
void Util::End::resetParam () virtual
Do-nothing implementation of virtual resetParam function.
Reimplemented from Util::ParamComponent.
Definition at line 49 of file End.cpp.
The documentation for this class was generated from the following files:
End.h
End.cpp