PSCF: Pscf::Pspg::DField< Data > Class Template Reference
Pscf::Pspg::DField< Data > Class Template Reference
Pscf namespace » Periodic Pseudo-Spectral (GPU) » Fields
Dynamic array with aligned data, for use with cufftw library/device code.
#include <DField.h>
Public Member Functions
DField ()
Default constructor.
virtual ~DField ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array.
void deallocate ()
Dellocate the underlying C array.
bool isAllocated () const
Return true if the Field has been allocated, false otherwise.
int capacity () const
Return allocated size.
Data * cDField ()
Return pointer to underlying C array.
const Data * cDField () const
Return pointer to const to underlying C array.
Protected Attributes
Data * data_
Serialize a Field to/from an Archive.
int capacity_
Allocated size of the data_ array.
Detailed Description
template<typename Data>
class Pscf::Pspg::DField< Data >
Dynamic array with aligned data, for use with cufftw library/device code.
This class does not offer memory access via operator[]
Definition at line 26 of file DField.h.
Constructor & Destructor Documentation
template<typename Data > Pscf::Pspg::DField< Data >::DField ()
Default constructor.
Definition at line 26 of file DField.tpp.
template<typename Data > Pscf::Pspg::DField< Data >::~DField () virtual
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 35 of file DField.tpp.
References Pscf::Pspg::DField< Data >::capacity_, Pscf::Pspg::DField< Data >::data_, and Pscf::Pspg::DField< Data >::isAllocated().
Member Function Documentation
template<typename Data > void Pscf::Pspg::DField< Data >::allocate (int capacity)
Allocate the underlying C array.
Exceptions
Exception if the Field is already allocated.
Parameters
capacity number of elements to allocate.
Definition at line 51 of file DField.tpp.
References Pscf::Pspg::DField< Data >::capacity(), Pscf::Pspg::DField< Data >::capacity_, Pscf::Pspg::DField< Data >::data_, Pscf::Pspg::DField< Data >::isAllocated(), and UTIL_THROW.
Referenced by Pscf::Pspg::RDFieldDft< D >::allocate(), and Pscf::Pspg::RDField< D >::allocate().
template<typename Data > void Pscf::Pspg::DField< Data >::deallocate ()
Dellocate the underlying C array.
Exceptions
Exception if the Field is not allocated.
Definition at line 69 of file DField.tpp.
References Pscf::Pspg::DField< Data >::capacity_, Pscf::Pspg::DField< Data >::data_, Pscf::Pspg::DField< Data >::isAllocated(), and UTIL_THROW.
template<typename Data > bool Pscf::Pspg::DField< Data >::isAllocated () const inline
Return true if the Field has been allocated, false otherwise.
Definition at line 141 of file DField.h.
Referenced by Pscf::Pspg::DField< Data >::allocate(), Pscf::Pspg::DField< Data >::deallocate(), and Pscf::Pspg::DField< Data >::~DField().
template<typename Data > int Pscf::Pspg::DField< Data >::capacity () const inline
Return allocated size.
Returns
Number of elements allocated in array.
Definition at line 120 of file DField.h.
Referenced by Pscf::Pspg::DField< Data >::allocate().
template<typename Data > Data * Pscf::Pspg::DField< Data >::cDField () inline
Return pointer to underlying C array.
Definition at line 127 of file DField.h.
Referenced by Pscf::Pspg::System< D >::readCommands(), Pscf::Pspg::Block< D >::setupUnitCell(), and Pscf::Pspg::Mixture< D >::setupUnitCell().
template<typename Data > const Data * Pscf::Pspg::DField< Data >::cDField () const inline
Return pointer to const to underlying C array.
Definition at line 134 of file DField.h.
Member Data Documentation
template<typename Data> Data* Pscf::Pspg::DField< Data >::data_ protected
Serialize a Field to/from an Archive.
Parameters
ar archive
version archive version idPointer to an array of Data elements.
Definition at line 97 of file DField.h.
Referenced by Pscf::Pspg::DField< Data >::allocate(), Pscf::Pspg::DField< Data >::deallocate(), and Pscf::Pspg::DField< Data >::~DField().
template<typename Data> int Pscf::Pspg::DField< Data >::capacity_ protected
Allocated size of the data_ array.
Definition at line 100 of file DField.h.
Referenced by Pscf::Pspg::DField< Data >::allocate(), Pscf::Pspg::DField< Data >::deallocate(), and Pscf::Pspg::DField< Data >::~DField().
The documentation for this class was generated from the following files:
DField.h
DField.tpp