PSCF: Pscf::R1d::BinaryRelaxIterator Class Reference
Pscf::R1d::BinaryRelaxIterator Class Reference
Pscf namespace » Pscf::R1d - Real 1D fields » Iterators
Relaxation iterator for SCF equations for two-monomer system.
#include <BinaryRelaxIterator.h>
Public Types
typedef Mixture::WField WField
Monomer chemical potential field.
typedef Mixture::CField CField
Monomer concentration / volume fraction field.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
BinaryRelaxIterator (System &system)
Constructor.
virtual ~BinaryRelaxIterator ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
int solve (bool isContinuation=false)
Iterate self-consistent field equations to solution.
Public Member Functions inherited from Pscf::R1d::Iterator
Iterator ()
Default constructor.
Iterator (System &system)
Constructor.
~Iterator ()
Destructor.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from Pscf::R1d::SystemAccess
SystemAccess ()
Default constructor.
SystemAccess (System &system)
Constructor.
~SystemAccess ()
Destructor.
virtual void setSystem (System &system)
Set the system after construction.
const System & system () const
Get parent System by reference.
System & system ()
Get parent System by reference.
const Mixture & mixture () const
Get Mixture by reference.
Mixture & mixture ()
Get Mixture by reference.
const Domain & domain () const
Get spatial domain (including grid info) by reference.
Domain & domain ()
Get spatial domain (including grid info) by reference.
const Interaction & interaction () const
Get interaction (i.e., excess free energy model) by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
const Homogeneous::Mixture & homogeneous () const
Get homogeneous mixture (for reference calculations).
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
DArray< System::WField > & wFields ()
Get array of all chemical potential fields.
System::WField & wField (int monomerId)
Get chemical potential field for a specific monomer type.
DArray< System::CField > & cFields ()
Get array of all chemical potential fields.
System::CField & cField (int monomerId)
Get chemical potential field for a specific monomer type.
Public Member Functions inherited from Pscf::ParameterModifier
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
virtual GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to the Sweep object.
virtual void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
virtual double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
Relaxation iterator for SCF equations for two-monomer system.
This class implements the simple Picard-type relaxation iterator for systems with two monomer types that was introduced by Drolet and Fredrickson (PRL, 1999).
Reference: F. Drolet & G.H. Fredrickson, Phys. Rev. Lett. vol. 83, 4317 (1999).
Definition at line 37 of file BinaryRelaxIterator.h.
Member Typedef Documentation
WField
Mixture::WField Pscf::R1d::BinaryRelaxIterator::WField
Monomer chemical potential field.
Definition at line 45 of file BinaryRelaxIterator.h.
CField
Mixture::CField Pscf::R1d::BinaryRelaxIterator::CField
Monomer concentration / volume fraction field.
Definition at line 50 of file BinaryRelaxIterator.h.
Constructor & Destructor Documentation
BinaryRelaxIterator()
Pscf::R1d::BinaryRelaxIterator::BinaryRelaxIterator (System & system)
Constructor.
Parameters
system parent System object.
Definition at line 21 of file BinaryRelaxIterator.cpp.
References Util::ParamComposite::setClassName().
~BinaryRelaxIterator()
Pscf::R1d::BinaryRelaxIterator::~BinaryRelaxIterator () virtual
Destructor.
Definition at line 32 of file BinaryRelaxIterator.cpp.
Member Function Documentation
readParameters()
void Pscf::R1d::BinaryRelaxIterator::readParameters (std::istream & in) virtual
Read all parameters and initialize.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 36 of file BinaryRelaxIterator.cpp.
References Pscf::R1d::SystemAccess::domain(), Util::ParamComposite::read(), and UTIL_CHECK.
solve()
int Pscf::R1d::BinaryRelaxIterator::solve (bool isContinuation = false) virtual
Iterate self-consistent field equations to solution.
Parameters
isContinuation True if part of sweep, and not first step.
Returns
error code: 0 for success, 1 for failure.
Implements Pscf::R1d::Iterator.
Definition at line 132 of file BinaryRelaxIterator.cpp.
References Pscf::R1d::System::cField(), Pscf::R1d::SystemAccess::cFields(), Pscf::R1d::Mixture::compute(), Pscf::R1d::System::computeFreeEnergy(), Pscf::R1d::SystemAccess::domain(), Util::Log::file(), Pscf::R1d::SystemAccess::mixture(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::R1d::Domain::nx(), Pscf::MixtureTmpl< TP, TS >::polymer(), Util::Timer::start(), Util::Timer::stop(), Pscf::R1d::SystemAccess::system(), Util::Timer::time(), UTIL_CHECK, UTIL_THROW, Pscf::R1d::System::wField(), and Pscf::R1d::SystemAccess::wFields().
The documentation for this class was generated from the following files:
BinaryRelaxIterator.h
BinaryRelaxIterator.cpp