PSCF: Pscf::Prdc::Cuda::FFTBatched< D > Class Template Reference
Pscf::Prdc::Cuda::FFTBatched< D > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CUDA)
Batched Fourier transform wrapper for real data.
#include <FFTBatched.h>
Public Member Functions
FFTBatched ()
Default constructor.
virtual ~FFTBatched ()
Destructor.
void setup (IntVec< D > const &meshDimensions, int batchSize)
Set up FFT calculation (get grid dimensions and make FFT plan)
void forwardTransform (DeviceArray< cudaReal > const &rFields, DeviceArray< cudaComplex > &kFields) const
Compute batched forward (real-to-complex) DFTs.
void inverseTransformUnsafe (DeviceArray< cudaComplex > &kFields, DeviceArray< cudaReal > &rFields) const
Compute inverse (complex-to-real) Fourier transform.
const IntVec< D > & meshDimensions () const
Return the dimensions of the grid for which this was allocated.
void resetBatchSize (int batchSize)
Set the batch size to a new value.
bool isSetup () const
Has the setup method been called?
Detailed Description
template<int D>
class Pscf::Prdc::Cuda::FFTBatched< D >
Batched Fourier transform wrapper for real data.
Definition at line 31 of file FFTBatched.h.
Constructor & Destructor Documentation
FFTBatched()
template<int D> Pscf::Prdc::Cuda::FFTBatched< D >::FFTBatched ()
Default constructor.
Definition at line 66 of file FFTBatched.tpp.
~FFTBatched()
template<int D> Pscf::Prdc::Cuda::FFTBatched< D >::~FFTBatched () virtual
Destructor.
Definition at line 80 of file FFTBatched.tpp.
Member Function Documentation
setup()
template<int D> void Pscf::Prdc::Cuda::FFTBatched< D >::setup (IntVec< D > const & meshDimensions, int batchSize)
Set up FFT calculation (get grid dimensions and make FFT plan)
Parameters
meshDimensions dimensions of real-space grid
batchSize number of simultaneous FFTs to perform
Definition at line 94 of file FFTBatched.tpp.
References meshDimensions(), and UTIL_CHECK.
forwardTransform()
template<int D> void Pscf::Prdc::Cuda::FFTBatched< D >::forwardTransform (DeviceArray< cudaReal > const & rFields, DeviceArray< cudaComplex > & kFields) const
Compute batched forward (real-to-complex) DFTs.
The resulting complex array is the output of cuFFT's batched forward transform method scaled by a factor of 1/N (where N is the number of grid points). The scaling ensures that a round-trip Fourier transform (forward + inverse) reproduces the original input array.
The number of Fourier transforms performed per batch is pre-set by the setup() method.
This transform is inherently "safe", meaning that the input array will not be modified during the DFT.
Parameters
rFields real values on r-grid (input, gpu mem)
kFields complex values on k-grid (output, gpu mem)
Definition at line 191 of file FFTBatched.tpp.
References Pscf::DeviceArray< Data >::capacity(), Pscf::DeviceArray< Data >::cArray(), Pscf::Prdc::Cuda::VecOp::mulEqS(), UTIL_CHECK, and UTIL_THROW.
inverseTransformUnsafe()
template<int D> void Pscf::Prdc::Cuda::FFTBatched< D >::inverseTransformUnsafe (DeviceArray< cudaComplex > & kFields, DeviceArray< cudaReal > & rFields) const
Compute inverse (complex-to-real) Fourier transform.
The resulting real array is the unaltered output of cuFFT's inverse transform function.
This transform is inherently "unsafe", meaning that the input array will be overwritten during the DFT. Accordingly, the input array kField is not const like it is in all the other transform methods.
Parameters
kFields complex values on k-grid (input, gpu mem)
rFields real values on r-grid (output, gpu mem)
Definition at line 225 of file FFTBatched.tpp.
References Pscf::DeviceArray< Data >::capacity(), Pscf::DeviceArray< Data >::cArray(), UTIL_CHECK, and UTIL_THROW.
meshDimensions()
template<int D> const IntVec< D > & Pscf::Prdc::Cuda::FFTBatched< D >::meshDimensions () const inline
Return the dimensions of the grid for which this was allocated.
Definition at line 145 of file FFTBatched.h.
Referenced by setup().
resetBatchSize()
template<int D> void Pscf::Prdc::Cuda::FFTBatched< D >::resetBatchSize (int batchSize)
Set the batch size to a new value.
isSetup() must already be true.
Parameters
batchSize The new batch size.
isSetup() must already be true.
Definition at line 124 of file FFTBatched.tpp.
References UTIL_CHECK.
isSetup()
template<int D> bool Pscf::Prdc::Cuda::FFTBatched< D >::isSetup () const inline
Has the setup method been called?
Definition at line 150 of file FFTBatched.h.
The documentation for this class was generated from the following files:
FFTBatched.h
FFTBatched.tpp