PSCF: Pscf::Species Class Reference
Pscf::Species Class Reference
Pscf namespace » Pscf Common » Chemical Structure
Base class for a molecular species (polymer or solvent).
#include <Species.h>
Public Types
enum Ensemble
Statistical ensemble for number of molecules.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Species ()
Default constructor.
virtual void readParameters (std::istream &in)
Read phi or mu (but not both) and set ensemble accordingly.
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble () const
Get the statistical ensemble for this species (open or closed).
void setPhi (double phi)
Set value of phi (volume fraction), if ensemble is closed.
void setMu (double mu)
Set value of mu (chemical potential), if ensemble is closed.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
void setQ (double q)
Set q and compute phi or mu (depending on the ensemble).
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
Base class for a molecular species (polymer or solvent).
Species is a base class for both polymeric and solvent species descriptors and solvers. Each Species has values of phi, mu and q, and an ensemble enumeration value. The value of either phi or mu must be provided as a parameter in the parameter file, thereby also determining the choice of ensemble. A subclass of Species that actually solves the single single-molecule statistical mechanics problem must use the function setQ(double) to set set the value of the molecular partition function q and to compute a new value for either mu or phi, depending on the ensemble.
Definition at line 33 of file Species.h.
Member Enumeration Documentation
Ensemble
enum Pscf::Species::Ensemble
Statistical ensemble for number of molecules.
Definition at line 40 of file Species.h.
Constructor & Destructor Documentation
Species()
Pscf::Species::Species ()
Default constructor.
Definition at line 18 of file Species.cpp.
References Util::ParamComposite::setClassName(), and Species().
Referenced by Pscf::PolymerSpecies::PolymerSpecies(), Pscf::SolventSpecies::SolventSpecies(), and Species().
Member Function Documentation
readParameters()
void Pscf::Species::readParameters (std::istream & in) virtual
Read phi or mu (but not both) and set ensemble accordingly.
This function either reads a value for either phi (species volume fraction) and sets the ensemble to Closed or reads mu (species chemical potential) and sets the ensemble to Open. An Exception is thrown if neither a phi or mu parameter appears in the input stream.
Parameters
in input stream (parameter file)
Reimplemented from Util::ParamComposite.
Reimplemented in Pscf::PolymerSpecies, Pscf::PolymerTmpl< BT >, Pscf::PolymerTmpl< Block >, Pscf::PolymerTmpl< Block< D > >, and Pscf::SolventSpecies.
Definition at line 28 of file Species.cpp.
References Util::ParamComposite::read(), and Util::ParamComposite::readOptional().
Referenced by Pscf::PolymerSpecies::readParameters(), and Pscf::SolventSpecies::readParameters().
phi()
double Pscf::Species::phi () const inline
Get the overall volume fraction for this species.
Definition at line 149 of file Species.h.
Referenced by Pscf::Prdc::ScftReal< D, ST >::compute(), Pscf::R1d::Solvent::compute(), Pscf::R1d::System::computeFreeEnergy(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::PolymerTmpl< Block< D > >::propagator(), and setPhi().
mu()
double Pscf::Species::mu () const inline
Get the chemical potential for this species (units kT=1).
Definition at line 155 of file Species.h.
Referenced by Pscf::Prdc::ScftReal< D, ST >::compute(), Pscf::R1d::System::computeFreeEnergy(), Pscf::PolymerTmpl< Block< D > >::propagator(), and setMu().
q()
double Pscf::Species::q () const inline
Get the molecular partition function for this species.
Definition at line 161 of file Species.h.
Referenced by Pscf::PolymerTmpl< Block< D > >::propagator(), and setQ().
ensemble()
Species::Ensemble Pscf::Species::ensemble () const inline
Get the statistical ensemble for this species (open or closed).
Definition at line 167 of file Species.h.
Referenced by Pscf::R1d::Solvent::compute(), Pscf::PolymerTmpl< Block< D > >::propagator(), setMu(), setPhi(), and setQ().
setPhi()
void Pscf::Species::setPhi (double phi)
Set value of phi (volume fraction), if ensemble is closed.
An initial value for phi or mu is normally read from a parameter file. This function is provided for use by a sweep or other procedure in which phi for a species with a closed enesmble is modified after initialization. It is an error to call setPhi for a polymer species with an open ensemble.
Exceptions
Exception if ensemble is open
Parameters
phi new volume fraction value for this species
Definition at line 43 of file Species.cpp.
References ensemble(), phi(), and UTIL_CHECK.
setMu()
void Pscf::Species::setMu (double mu)
Set value of mu (chemical potential), if ensemble is closed.
An initial value for phi or mu is normally read from a parameter file. This function is provided for use in a sweep or other procedure in which mu for a species with an open enesmble is modified after initialization. It is an error to call setMu for a polymer species with a closed ensemble.
Exceptions
Exception if ensemble is closed
Parameters
mu new chemical potential value for this species
Definition at line 54 of file Species.cpp.
References ensemble(), mu(), and UTIL_CHECK.
setQ()
void Pscf::Species::setQ (double q) protected
Set q and compute phi or mu (depending on the ensemble).
This function alllows a subclass to set the value of the molecular partition function q, and use this value to compute a corresponding value for either mu (for a closed ensemble) or phi (for an open ensemble). Upon return these variables are related by the equation: \(\phi = \exp(\mu) q \).
Parameters
q new value of molecular partition function q
Definition at line 63 of file Species.cpp.
References ensemble(), and q().
Referenced by Pscf::R1d::Solvent::compute(), Pscf::Rpc::Solvent< D >::compute(), Pscf::Rpg::Solvent< D >::compute(), and Pscf::PolymerTmpl< BT >::solve().
The documentation for this class was generated from the following files:
Species.h
Species.cpp