PSCF: Util::Log Class Reference
Util::Log Class Reference
Util namespace » Miscellaneous Utilities
A static class that holds a log output stream.
#include <Log.h>
Static Public Member Functions
static void initStatic ()
Initialize static members.
static void setFile (std::ofstream &file)
Set the log ostream to a file.
static void close ()
Close log file, if any.
static std::ostream & file ()
Get log ostream by reference.
Detailed Description
A static class that holds a log output stream.
The Log class has one a static pointer member that points to an ostream that should be used by all other classes to output log and error messages. This stream is accessed by the file() method.
The log file initialized to point to std::cout. It may be reset to point to a ofstream file object using the static setFile() method.
Definition at line 30 of file Log.h.
Member Function Documentation
initStatic()
void Util::Log::initStatic () static
Initialize static members.
Definition at line 24 of file Log.cpp.
References UTIL_CHECK.
Referenced by Util::initStatic().
setFile()
void Util::Log::setFile (std::ofstream & file) static
Set the log ostream to a file.
Parameters
file ofstream open for writing.
Definition at line 36 of file Log.cpp.
References file().
close()
void Util::Log::close () static
Close log file, if any.
Definition at line 45 of file Log.cpp.
Referenced by Util::MpiThrow().
file()
std::ostream & Util::Log::file () static
Get log ostream by reference.
Definition at line 57 of file Log.cpp.
Referenced by Pscf::SweepTmpl< DArray< System::WField > >::addParameterType(), Pscf::Rpc::BdSimulator< D >::analyze(), Pscf::Rpc::McSimulator< D >::analyze(), Pscf::Rpg::BdSimulator< D >::analyze(), Pscf::Rpg::McSimulator< D >::analyze(), Pscf::Rpc::Simulator< D >::analyzeChi(), Pscf::Rpg::Simulator< D >::analyzeChi(), Pscf::ThreadMesh::checkConfig(), Pscf::Prdc::SpaceGroup< D >::checkMeshDimensions(), Util::checkString(), Pscf::AmIteratorTmpl< Iterator, T >::clear(), Pscf::AmIteratorTmpl< Iterator, DArray< double > >::clear(), Pscf::Rpc::System< D >::compare(), Pscf::Rpc::System< D >::compare(), Pscf::Rpg::System< D >::compare(), Pscf::Rpg::System< D >::compare(), Pscf::Rpc::LrCompressor< D >::compress(), Pscf::Rpg::LrCompressor< D >::compress(), Pscf::Rpc::FourthOrderParameter< D >::compute(), Pscf::AmIteratorTmpl< Iterator, T >::computeError(), Pscf::Rpg::LrAmPreCompressor< D >::computeError(), Pscf::Rpg::WaveList< D >::computeMinimumImages(), Pscf::Prdc::FieldIoReal< D, RField< D >, RFieldDft< D >, FFT< D > >::convertKGridToRGrid(), Pscf::Prdc::FieldIoReal< D, RField< D >, RFieldDft< D >, FFT< D > >::convertRGridToKGrid(), Util::Manager< Data >::endReadManager(), Util::Exception::Exception(), Util::Exception::Exception(), Util::XmlStartTag::finish(), Pscf::ThreadArray::init(), Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::AmIteratorTmpl< Iterator, DArray< double > >::isValidErrorType(), Pscf::R1d::System::iterate(), Pscf::Rpc::System< D >::iterate(), Pscf::Rpg::System< D >::iterate(), Util::ParamComposite::load(), Util::Parameter::load(), Util::Factory< Data >::loadObject(), Util::ParamComposite::loadOptional(), Util::XmlEndTag::match(), Util::XmlStartTag::matchLabel(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), Util::MpiThrow(), Pscf::Rpc::LinearRamp< D >::output(), Pscf::Rpg::LinearRamp< D >::output(), Pscf::Prdc::readBasisData(), Pscf::R1d::System::readCommands(), Pscf::Rpc::System< D >::readCommands(), Pscf::Rpg::System< D >::readCommands(), Pscf::Rpc::Simulator< D >::readCompressor(), Pscf::Rpg::Simulator< D >::readCompressor(), Pscf::Rpc::RGridTrajectoryReader< D >::readFrame(), Pscf::Rpg::RGridTrajectoryReader< D >::readFrame(), Pscf::Prdc::readGroup(), Pscf::Rpc::RGridTrajectoryReader< D >::readHeader(), Pscf::Rpg::RGridTrajectoryReader< D >::readHeader(), Pscf::Prdc::readMeshDimensions(), Util::Factory< Data >::readObject(), Util::Begin::readParam(), Util::Blank::readParam(), Util::End::readParam(), Util::Parameter::readParam(), Pscf::Rpc::BdSimulator< D >::readParameters(), Pscf::Rpc::System< D >::readParameters(), Pscf::Rpg::System< D >::readParameters(), Pscf::Rpc::Simulator< D >::readPerturbation(), Pscf::Rpg::Simulator< D >::readPerturbation(), Pscf::Rpc::Simulator< D >::readRamp(), Pscf::Rpg::Simulator< D >::readRamp(), Pscf::Rpc::StepLogger< D >::sample(), Pscf::Rpg::StepLogger< D >::sample(), Pscf::ThreadMesh::setConfig(), setFile(), Pscf::AmIteratorTmpl< Iterator, DArray< double > >::setMaxHist(), Pscf::R1d::System::setOptions(), Pscf::Rpc::System< D >::setOptions(), Pscf::Rpg::System< D >::setOptions(), Pscf::ThreadMesh::setThreadsPerBlock(), Pscf::AmIteratorTmpl< Iterator, DArray< double > >::setup(), Pscf::Rpc::BdSimulator< D >::simulate(), Pscf::Rpc::McSimulator< D >::simulate(), Pscf::Rpg::BdSimulator< D >::simulate(), Pscf::Rpg::McSimulator< D >::simulate(), Pscf::R1d::BinaryRelaxIterator::solve(), Pscf::R1d::NrIterator::solve(), Pscf::Prdc::Cuda::Reduce::sum(), Pscf::R1d::System::sweep(), Pscf::Rpc::System< D >::sweep(), Pscf::Rpg::System< D >::sweep(), Pscf::SweepTmpl< DArray< System::WField > >::SweepTmpl(), Pscf::Rpc::System< D >::writeTimers(), and Pscf::Rpg::System< D >::writeTimers().
The documentation for this class was generated from the following files:
Log.h
Log.cpp