PSCF: Util::MatrixParam< Type > Class Template Reference
Util::MatrixParam< Type > Class Template Reference
Util namespace » Parameter File IO
An array-valued parameter in a parameter file.
#include <MatrixParam.h>
Public Member Functions
MatrixParam (const char *label, int m, int n, bool isRequired=true)
Constructor.
virtual ~MatrixParam ()
Destructor.
int m () const
Get the logical array dimension.
int n () const
Get the logical array dimension.
std::string indent () const
Return indent string for this object (string of spaces).
virtual void readValue (std::istream &in)
Read parameter value from an input stream.
virtual void load (Serializable::IArchive &ar)
Load from an archive.
virtual void save (Serializable::OArchive &ar)
Save to an archive.
std::string label () const
Return label string.
bool isRequired () const
Is this an optional parameter?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::Parameter
Parameter (const char *label, bool isRequired=true)
Constructor.
virtual ~Parameter ()
Destructor.
virtual void readParam (std::istream &in)
Read a label and (if the label matches) a parameter value.
std::string label () const
Return label string.
bool isRequired () const
Is this an optional parameter?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void writeParam (std::ostream &out) const =0
Read parameter(s) to file.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
virtual void readLabel (std::istream &in)
Read parameter label from an input stream.
void readEndBracket (std::istream &in)
Read the closing delimiter, if any.
void writeEndBracket (std::ostream &out) const
Write the end bracket delimiter, if any.
bool hasBrackets () const
Are brackets being used as delimiters?
void setBrackets (std::string lBracket, std::string rBracket)
Set left and right bracket / delimiter strings.
Protected Member Functions inherited from Util::Parameter
virtual void loadValue (Serializable::IArchive &ar)
Load bare parameter value from an archive.
virtual void saveValue (Serializable::OArchive &ar)
Save parameter value to an archive.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
Label label_
Label object that contains parameter label string.
Protected Attributes inherited from Util::Parameter
Label label_
Label object that contains parameter label string.
bool isActive_
Is this parameter active (always true if isRequired).
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::Parameter
template<class Type>
static void saveOptional (Serializable::OArchive &ar, Type &value, bool isActive)
Save an optional parameter value to an output archive.
template<class Type>
static void saveOptionalCArray (Serializable::OArchive &ar, Type *ptr, int n, bool isActive)
Save an optional C-array of n values to an output archive.
template<class Type>
static void saveOptionalCArray2D (Serializable::OArchive &ar, Type *ptr, int m, int n, int np, bool isActive)
Save an optional two-dimensional C array to an output archive.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Util::Parameter
static const int Width = 20
Width of output field for a scalar variable.
static const int Precision = 12
Precision for io of floating point data field.
Detailed Description
template<typename Type>
class Util::MatrixParam< Type >
An array-valued parameter in a parameter file.
MatrixParam is a base class for objects that read and write the value of an matrix or 2D array containing a list of parameters of the same
type.
Matrices can be read and written in either of two formats:
Bracketed format begins with a label immediately followed by an opening delimiter on a line by itself, followed by several data lines, and ends with a closing delimiter.
Bracket-free format begins with a label on the same line as the first line of data, with no opening or closing bracket delimiters.
Different subclasses may use different formats for the data lines, and different choices of delmiting brackets (e.g., square brackets or parentheses). Two different conventions are in use:
Row data format puts values of all the elements in each row of the matrix on a single line, with rows appearing in order of increasing index, as in standard linear algebra matrix format.
Element format puts each element on a single line, in which each line contains the row and column index followed by the value.
Either row or element data format may be input and output in either bracketed or bracket-free format. The choice of whether to use bracketed or bracket-free format is determined by the global bracket policy returned by the function Util::BracketPolicy::get().
If the policy is BracketPolicy::Forbidden, the bracket-free format must be used for both reading and writing.
If the policy is BracketPolicy::Required, the bracketed format must be used for both reading and writing.
If the policy is BracketPolicy::Optional, then either format can be read, but the bracketed format is used for writing.
Definition at line 61 of file MatrixParam.h.
Constructor & Destructor Documentation
MatrixParam()
template<typename Type> Util::MatrixParam< Type >::MatrixParam (const char * label, int m, int n, bool isRequired = true)
Constructor.
Parameters
label label string (without any opening bracket)
m number of rows
n number of columns
isRequired Is this a required parameter?
Definition at line 24 of file MatrixParam.tpp.
References Util::BracketPolicy::get(), isRequired(), label(), label_, m(), n(), and Util::Parameter::Parameter().
Referenced by Util::CArray2DParam< Type >::CArray2DParam(), Util::DMatrixParam< Type >::DMatrixParam(), and Util::DSymmMatrixParam< Type >::DSymmMatrixParam().
~MatrixParam()
template<typename Type> Util::MatrixParam< Type >::~MatrixParam () virtual
Destructor.
Definition at line 47 of file MatrixParam.tpp.
Member Function Documentation
m()
template<typename Type> int Util::MatrixParam< Type >::m () const inline
Get the logical array dimension.
Definition at line 84 of file MatrixParam.h.
Referenced by Util::CArray2DParam< Type >::CArray2DParam(), Util::DMatrixParam< Type >::DMatrixParam(), Util::CArray2DParam< Type >::loadValue(), Util::DMatrixParam< Type >::loadValue(), MatrixParam(), Util::CArray2DParam< Type >::readValue(), Util::DMatrixParam< Type >::readValue(), Util::CArray2DParam< Type >::saveValue(), Util::DMatrixParam< Type >::saveValue(), Util::CArray2DParam< Type >::writeParam(), and Util::DMatrixParam< Type >::writeParam().
n()
template<typename Type> int Util::MatrixParam< Type >::n () const inline
Get the logical array dimension.
Definition at line 90 of file MatrixParam.h.
Referenced by Util::CArray2DParam< Type >::CArray2DParam(), Util::DMatrixParam< Type >::DMatrixParam(), Util::DSymmMatrixParam< Type >::DSymmMatrixParam(), Util::CArray2DParam< Type >::loadValue(), Util::DMatrixParam< Type >::loadValue(), Util::DSymmMatrixParam< Type >::loadValue(), MatrixParam(), Util::CArray2DParam< Type >::readValue(), Util::DMatrixParam< Type >::readValue(), Util::DSymmMatrixParam< Type >::readValue(), Util::CArray2DParam< Type >::saveValue(), Util::DMatrixParam< Type >::saveValue(), Util::DSymmMatrixParam< Type >::saveValue(), Util::CArray2DParam< Type >::writeParam(), Util::DMatrixParam< Type >::writeParam(), and Util::DSymmMatrixParam< Type >::writeParam().
readLabel()
template<typename Type> void Util::MatrixParam< Type >::readLabel (std::istream & in) protected virtual
Read parameter label from an input stream.
Parameters
in input stream from which to read
Reimplemented from Util::Parameter.
Definition at line 76 of file MatrixParam.tpp.
References Util::BracketPolicy::get(), Util::Parameter::isActive_, Util::Label::isMatched(), and label_.
readEndBracket()
template<class Type> void Util::MatrixParam< Type >::readEndBracket (std::istream & in) protected
Read the closing delimiter, if any.
Attempts to read closing bracket iff hasBrackets is true. Throws an exception if hasBrackets is true but the expected delimiter is not found.
Parameters
in input stream from which to read
Definition at line 126 of file MatrixParam.tpp.
References Util::BracketPolicy::get(), label_, and UTIL_CHECK.
Referenced by Util::CArray2DParam< Type >::readValue(), Util::DMatrixParam< Type >::readValue(), and Util::DSymmMatrixParam< Type >::readValue().
writeEndBracket()
template<class Type> void Util::MatrixParam< Type >::writeEndBracket (std::ostream & out) const protected
Write the end bracket delimiter, if any.
Parameters
out output stream to which to write
Definition at line 150 of file MatrixParam.tpp.
References indent().
Referenced by Util::CArray2DParam< Type >::writeParam(), Util::DMatrixParam< Type >::writeParam(), and Util::DSymmMatrixParam< Type >::writeParam().
hasBrackets()
template<typename Type> bool Util::MatrixParam< Type >::hasBrackets () const inline protected
Are brackets being used as delimiters?
Definition at line 131 of file MatrixParam.h.
Referenced by Util::DSymmMatrixParam< Type >::readValue(), Util::CArray2DParam< Type >::writeParam(), Util::DMatrixParam< Type >::writeParam(), and Util::DSymmMatrixParam< Type >::writeParam().
setBrackets()
template<typename Type> void Util::MatrixParam< Type >::setBrackets (std::string lBracket, std::string rBracket) protected
Set left and right bracket / delimiter strings.
Parameters
lBracket left bracket string
rBracket right bracket string
Definition at line 54 of file MatrixParam.tpp.
References Util::BracketPolicy::get(), and label_.
Referenced by Util::CArray2DParam< Type >::CArray2DParam(), Util::DMatrixParam< Type >::DMatrixParam(), and Util::DSymmMatrixParam< Type >::DSymmMatrixParam().
indent()
template<typename Type> std::string Util::ParamComponent::indent () const
Return indent string for this object (string of spaces).
Definition at line 96 of file ParamComponent.cpp.
Referenced by writeEndBracket().
readValue()
template<typename Type> virtual void Util::Parameter::readValue (std::istream & in) inline virtual
Read parameter value from an input stream.
Parameters
in input stream from which to read
Reimplemented from Util::Parameter.
Definition at line 202 of file Parameter.h.
load()
template<typename Type> void Util::Parameter::load (Serializable::IArchive & ar) virtual
Load from an archive.
An optional Parameter loads the value of an isActive flag, and then loads the parameter value only if the isActive is true. A required Parameter simply loads the parameter value. The variable associated with an optional Parameter must be set to its default value before attempting to load the parameter. Optional parameters should be saved either using the save() method of an associated Parameter object or using the appropriate overloaded Parameter::saveOptional() static member function, which both use the required format.
Parameters
ar input archive from which to load
Reimplemented from Util::Parameter.
Definition at line 150 of file Parameter.cpp.
Referenced by Util::ParamComposite::loadCArray2D(), Util::ParamComposite::loadDMatrix(), and Util::ParamComposite::loadDSymmMatrix().
save()
template<typename Type> void Util::Parameter::save (Serializable::OArchive & ar) virtual
Save to an archive.
An optional Parameter saves the value of the isActive flag, and then saves a parameter value only if the isActive is true. A required Parameter simply saves its value. The label string is not saved to the archive.
The overloaded static saveOptional functions can also be used to save optional parameter values in this format.
Parameters
ar output archive to which to save
Reimplemented from Util::Parameter.
Definition at line 165 of file Parameter.cpp.
label()
template<typename Type> std::string Util::Parameter::label () const
Return label string.
Definition at line 170 of file Parameter.cpp.
Referenced by Util::CArray2DParam< Type >::CArray2DParam(), Util::DMatrixParam< Type >::DMatrixParam(), Util::DSymmMatrixParam< Type >::DSymmMatrixParam(), and MatrixParam().
isRequired()
template<typename Type> bool Util::Parameter::isRequired () const
Is this an optional parameter?
Definition at line 175 of file Parameter.cpp.
Referenced by Util::CArray2DParam< Type >::CArray2DParam(), Util::DMatrixParam< Type >::DMatrixParam(), Util::DSymmMatrixParam< Type >::DSymmMatrixParam(), and MatrixParam().
isActive()
template<typename Type> bool Util::Parameter::isActive () const
Is this parameter active?
Definition at line 180 of file Parameter.cpp.
Member Data Documentation
label_
template<typename Type> Label Util::Parameter::label_ protected
Label object that contains parameter label string.
Definition at line 185 of file Parameter.h.
Referenced by MatrixParam(), readEndBracket(), readLabel(), and setBrackets().
The documentation for this class was generated from the following files:
MatrixParam.h
MatrixParam.tpp