PSCF: Pscf::Pspc::RField< D > Class Template Reference
Pscf::Pspc::RField< D > Class Template Reference
Pscf namespace » Pseudo-Spectral Periodic (CPU) » Fields
Field of real double precision values on an FFT mesh.
#include <RField.h>
Public Member Functions
RField ()
Default constructor.
RField (const RField &other)
Copy constructor.
virtual ~RField ()
Destructor.
RField & operator= (const RField &other)
Assignment operator.
void allocate (const IntVec< D > &meshDimensions)
Allocate the underlying C array for an FFT grid.
const IntVec< D > & meshDimensions () const
Return mesh dimensions by constant reference.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a Field to/from an Archive.
Public Member Functions inherited from Pscf::Field< double >
Field ()
Constructor.
Field (Field< double > const &other)
Copy constructor.
Field< double > & operator= (Field< double > const &other)
Assignment operator.
Field< double > & operator= (double &scalar)
Assignment - assign all elements to a common scalar.
Field< double > & operator+= (Field< double > &other)
Increment operator - add one field by another.
Field< double > & operator-= (Field< double > &other)
Decrement operator - subtract one field from another.
Field< double > & operator*= (double scalar)
Multiplication operator - multiply one field by a scalar.
Field< double > & operator*= (Field< double > &other)
Pointwise multipication of one field by another.
void setToZero ()
Set all elements to zero.
double average () const
Compute and return average of all elements.
Public Member Functions inherited from Util::DArray< double >
DArray ()
Default constructor.
DArray (DArray< double > const &other)
Copy constructor.
virtual ~DArray ()
Destructor.
DArray< double > & operator= (DArray< double > const &other)
Assignment operator.
void allocate (int capacity)
Allocate the underlying C array.
void deallocate ()
Dellocate the underlying C array.
void reallocate (int capacity)
Reallocate the underlying C array and copy to new location.
bool isAllocated () const
Return true if this DArray has been allocated, false otherwise.
void serialize (Archive &ar, const unsigned int version)
Serialize a DArray to/from an Archive.
Public Member Functions inherited from Util::Array< double >
virtual ~Array ()
Destructor.
int capacity () const
Return allocated size.
void begin (ArrayIterator< double > &iterator)
Set an iterator to begin this Array.
void begin (ConstArrayIterator< double > &iterator) const
Set a const iterator to begin this Array.
double & operator[] (int i)
Get an element by non-const reference.
double const & operator[] (int i) const
Get an element by const reference.
double * cArray ()
Return a pointer to the underlying C array.
double const * cArray () const
Return pointer to const to the underlying C array.
Additional Inherited Members
Protected Member Functions inherited from Util::Array< double >
Array ()
Default constructor.
Protected Attributes inherited from Util::Array< double >
double * data_
Pointer to an array of Data elements.
int capacity_
Allocated size of the data_ array.
Detailed Description
template<int D>
class Pscf::Pspc::RField< D >
Field of real double precision values on an FFT mesh.
Definition at line 28 of file RField.h.
Constructor & Destructor Documentation
RField() [1/2]
template<int D> Pscf::Pspc::RField< D >::RField
Default constructor.
Definition at line 23 of file RField.tpp.
RField() [2/2]
template<int D> Pscf::Pspc::RField< D >::RField (const RField< D > & other)
Copy constructor.
Allocates new memory and copies all elements by value.
Parameters
other the RField to be copied.
Definition at line 42 of file RField.tpp.
References Util::Array< double >::capacity_, Util::Array< Data >::capacity_, Util::Array< Data >::data_, Util::Array< double >::data_, Util::DArray< Data >::isAllocated(), and UTIL_THROW.
~RField()
template<int D> Pscf::Pspc::RField< D >::~RField virtual
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 31 of file RField.tpp.
Member Function Documentation
operator=()
template<int D> RField< D > & Pscf::Pspc::RField< D >::operator= (const RField< D > & other)
Assignment operator.
If this Field is not allocated, allocates and copies all elements.
If this and the other Field are both allocated, the capacities must be exactly equal. If so, this method copies all elements.
Parameters
other the RHS RField
Definition at line 68 of file RField.tpp.
References Util::Array< Data >::capacity(), Util::Array< Data >::capacity_, Util::DArray< Data >::isAllocated(), and UTIL_THROW.
allocate()
template<int D> void Pscf::Pspc::RField< D >::allocate (const IntVec< D > & meshDimensions)
Allocate the underlying C array for an FFT grid.
Exceptions
Exception if the RField is already allocated.
Parameters
meshDimensions vector of numbers of grid points per direction
Definition at line 97 of file RField.tpp.
References Util::DArray< double >::allocate(), and UTIL_CHECK.
Referenced by Pscf::Pspc::FieldIo< D >::readFieldRGrid(), Pscf::Pspc::FFT< D >::setup(), and Pscf::Pspc::FieldIo< D >::writeFieldRGrid().
meshDimensions()
template<int D> const IntVec< D > & Pscf::Pspc::RField< D >::meshDimensions inline
Return mesh dimensions by constant reference.
Definition at line 102 of file RField.h.
Referenced by Pscf::Pspc::FFT< D >::forwardTransform(), Pscf::Pspc::FFT< D >::inverseTransform(), Pscf::Pspc::FieldIo< D >::readFieldRGrid(), and Pscf::Pspc::FFT< D >::setup().
serialize()
template<int D> template<class Archive > void Pscf::Pspc::RField< D >::serialize (Archive & ar, const unsigned int version)
Serialize a Field to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 110 of file RField.h.
References Util::DArray< double >::serialize().
The documentation for this class was generated from the following files:
RField.h
RField.tpp