PSCF: Pscf::R1d::SystemAccess Class Reference
Pscf::R1d::SystemAccess Class Reference
Pscf namespace » Pscf::R1d - Real 1D fields
Concise accesss to an associated System.
#include <SystemAccess.h>
Public Member Functions
SystemAccess ()
Default constructor.
SystemAccess (System &system)
Constructor.
~SystemAccess ()
Destructor.
virtual void setSystem (System &system)
Set the system after construction.
Accessors (get objects by reference)
const System & system () const
Get parent System by reference.
System & system ()
Get parent System by reference.
const Mixture & mixture () const
Get Mixture by reference.
Mixture & mixture ()
Get Mixture by reference.
const Domain & domain () const
Get spatial domain (including grid info) by reference.
Domain & domain ()
Get spatial domain (including grid info) by reference.
const Interaction & interaction () const
Get interaction (i.e., excess free energy model) by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
const Homogeneous::Mixture & homogeneous () const
Get homogeneous mixture (for reference calculations).
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
Fields
DArray< System::WField > & wFields ()
Get array of all chemical potential fields.
System::WField & wField (int monomerId)
Get chemical potential field for a specific monomer type.
DArray< System::CField > & cFields ()
Get array of all chemical potential fields.
System::CField & cField (int monomerId)
Get chemical potential field for a specific monomer type.
Detailed Description
Concise accesss to an associated System.
This class is intended to be a base class for classes that maintain a pointer to an associated system, and that implement code that frequently accesses the main members of that System.
Definition at line 27 of file SystemAccess.h.
Constructor & Destructor Documentation
SystemAccess() [1/2]
Pscf::R1d::SystemAccess::SystemAccess ()
Default constructor.
Definition at line 18 of file SystemAccess.cpp.
SystemAccess() [2/2]
Pscf::R1d::SystemAccess::SystemAccess (System & system)
Constructor.
Definition at line 25 of file SystemAccess.cpp.
~SystemAccess()
Pscf::R1d::SystemAccess::~SystemAccess ()
Destructor.
Definition at line 32 of file SystemAccess.cpp.
Member Function Documentation
setSystem()
void Pscf::R1d::SystemAccess::setSystem (System & system) virtual
Set the system after construction.
Definition at line 38 of file SystemAccess.cpp.
References system().
Referenced by Pscf::R1d::System::readParameters().
system() [1/2]
const System & Pscf::R1d::SystemAccess::system () const inline
Get parent System by reference.
Definition at line 158 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::R1d::HomogeneousComparison::output(), Pscf::R1d::Sweep::outputSolution(), Pscf::R1d::Sweep::outputSummary(), setSystem(), Pscf::R1d::LinearSweep::setup(), Pscf::R1d::BinaryRelaxIterator::solve(), Pscf::R1d::NrIterator::solve(), Pscf::R1d::Sweep::solve(), and Pscf::R1d::Sweep::Sweep().
system() [2/2]
System & Pscf::R1d::SystemAccess::system () inline
Get parent System by reference.
Definition at line 167 of file SystemAccess.h.
References UTIL_ASSERT.
mixture() [1/2]
const Mixture & Pscf::R1d::SystemAccess::mixture () const inline
Get Mixture by reference.
Definition at line 176 of file SystemAccess.h.
References Pscf::R1d::System::mixture(), and UTIL_ASSERT.
Referenced by Pscf::R1d::Sweep::checkAllocation(), Pscf::R1d::HomogeneousComparison::compute(), Pscf::R1d::Sweep::extrapolate(), Pscf::R1d::HomogeneousComparison::output(), and Pscf::R1d::BinaryRelaxIterator::solve().
mixture() [2/2]
Mixture & Pscf::R1d::SystemAccess::mixture () inline
Get Mixture by reference.
Definition at line 185 of file SystemAccess.h.
References Pscf::R1d::System::mixture(), and UTIL_ASSERT.
domain() [1/2]
const Domain & Pscf::R1d::SystemAccess::domain () const inline
Get spatial domain (including grid info) by reference.
Definition at line 194 of file SystemAccess.h.
References Pscf::R1d::System::domain(), and UTIL_ASSERT.
Referenced by Pscf::R1d::Sweep::checkAllocation(), Pscf::R1d::HomogeneousComparison::compute(), Pscf::R1d::Sweep::extrapolate(), Pscf::R1d::HomogeneousComparison::output(), Pscf::R1d::Sweep::outputSummary(), Pscf::R1d::BinaryRelaxIterator::readParameters(), Pscf::R1d::BinaryRelaxIterator::solve(), and Pscf::R1d::NrIterator::solve().
domain() [2/2]
Domain & Pscf::R1d::SystemAccess::domain () inline
Get spatial domain (including grid info) by reference.
Definition at line 203 of file SystemAccess.h.
References Pscf::R1d::System::domain(), and UTIL_ASSERT.
interaction() [1/2]
const Interaction & Pscf::R1d::SystemAccess::interaction () const inline
Get interaction (i.e., excess free energy model) by reference.
Definition at line 212 of file SystemAccess.h.
References Pscf::R1d::System::interaction(), and UTIL_ASSERT.
Referenced by Pscf::R1d::HomogeneousComparison::compute().
interaction() [2/2]
Interaction & Pscf::R1d::SystemAccess::interaction () inline
Get interaction (i.e., excess free energy model) by reference.
Definition at line 221 of file SystemAccess.h.
References Pscf::R1d::System::interaction(), and UTIL_ASSERT.
homogeneous() [1/2]
const Homogeneous::Mixture & Pscf::R1d::SystemAccess::homogeneous () const
Get homogeneous mixture (for reference calculations).
Referenced by Pscf::R1d::HomogeneousComparison::compute(), and Pscf::R1d::HomogeneousComparison::output().
homogeneous() [2/2]
Homogeneous::Mixture & Pscf::R1d::SystemAccess::homogeneous () inline
Get homogeneous mixture (for reference calculations).
Definition at line 240 of file SystemAccess.h.
References Pscf::R1d::System::homogeneous(), and UTIL_ASSERT.
fileMaster()
FileMaster & Pscf::R1d::SystemAccess::fileMaster () inline
Get FileMaster by reference.
Definition at line 230 of file SystemAccess.h.
References Pscf::R1d::System::fileMaster(), and UTIL_ASSERT.
Referenced by Pscf::R1d::Sweep::outputSolution(), and Pscf::R1d::Sweep::setup().
wFields()
DArray< System::WField > & Pscf::R1d::SystemAccess::wFields () inline
Get array of all chemical potential fields.
The array capacity is equal to the number of monomer types.
Definition at line 250 of file SystemAccess.h.
References UTIL_ASSERT, and Pscf::R1d::System::wFields().
Referenced by Pscf::R1d::Sweep::getSolution(), Pscf::R1d::Sweep::outputSolution(), Pscf::R1d::Sweep::reset(), Pscf::R1d::BinaryRelaxIterator::solve(), and Pscf::R1d::NrIterator::solve().
wField()
System::WField & Pscf::R1d::SystemAccess::wField (int monomerId) inline
Get chemical potential field for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 260 of file SystemAccess.h.
References UTIL_ASSERT, and Pscf::R1d::System::wField().
Referenced by Pscf::R1d::Sweep::extrapolate().
cFields()
DArray< System::CField > & Pscf::R1d::SystemAccess::cFields () inline
Get array of all chemical potential fields.
The array capacity is equal to the number of monomer types.
Definition at line 270 of file SystemAccess.h.
References Pscf::R1d::System::cFields(), and UTIL_ASSERT.
Referenced by Pscf::R1d::Sweep::outputSolution(), Pscf::R1d::BinaryRelaxIterator::solve(), and Pscf::R1d::NrIterator::solve().
cField()
System::CField & Pscf::R1d::SystemAccess::cField (int monomerId) inline
Get chemical potential field for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 279 of file SystemAccess.h.
References Pscf::R1d::System::cField(), and UTIL_ASSERT.
The documentation for this class was generated from the following files:
SystemAccess.h
SystemAccess.cpp