PSCF: Pscf::R1d::Polymer Class Reference
Pscf::R1d::Polymer Class Reference
Pscf namespace » Pscf::R1d - Real 1D fields » Solvers
Descriptor and solver for a branched polymer species.
#include <Polymer.h>
Public Member Functions
Polymer ()
Default constructor.
~Polymer ()
Destructor.
void setPhi (double phi)
Set volume fraction (if ensemble is closed).
void setMu (double mu)
Set chemical potential mu (if ensemble is open).
void compute (DArray< Block::WField > const &wFields)
Compute solution to modified diffusion equation.
Public Member Functions inherited from Pscf::PolymerTmpl< Block >
PolymerTmpl ()
Constructor.
~PolymerTmpl ()
Destructor.
virtual void readParameters (std::istream &in)
Read and initialize.
virtual void solve (double phiTot=1.0)
Solve modified diffusion equation.
const Vertex & vertex (int id) const
Get a specified Vertex by const reference.
Pair< int > const & propagatorId (int id) const
Get a propagator identifier, indexed by order of computation.
Pair< int > const & path (int is, int it) const
Get an id for a propagator from one vertex towards a target.
int nBlock () const
Number of blocks.
int nVertex () const
Number of vertices (junctions and chain ends).
int nPropagator () const
Number of propagators (2*nBlock).
double length () const
Sum of the lengths of all blocks in the polymer (thread model).
int nBead () const
Total number of beads in the polymer (bead model).
PolymerType::Enum type () const
Get Polymer type (Branched or Linear)
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble ()
Get the statistical ensemble for this species (open or closed).
virtual Edge & edge (int id)
Get a specified Edge (block descriptor) by non-const reference.
virtual Edge const & edge (int id) const
Get a specified Edge (block descriptor) by const reference.
Block & block (int id)
Get a specified Block (block solver and descriptor)
Block const & block (int id) const
Get a specified Block (solver and descriptor) by const reference.
Propagator & propagator (int blockId, int directionId)
Get the Propagator for a specific block and direction (non-const).
Propagator const & propagator (int blockId, int directionId) const
Get the Propagator for a specific block and direction (const).
Propagator & propagator (int id)
Get propagator indexed in order of computation (non-const).
Public Member Functions inherited from Pscf::PolymerSpecies
PolymerSpecies ()
Constructor.
~PolymerSpecies ()
Destructor.
const Vertex & vertex (int id) const
Get a specified Vertex by const reference.
Pair< int > const & propagatorId (int id) const
Get a propagator identifier, indexed by order of computation.
Pair< int > const & path (int is, int it) const
Get an id for a propagator from one vertex towards a target.
int nBlock () const
Number of blocks.
int nVertex () const
Number of vertices (junctions and chain ends).
int nPropagator () const
Number of propagators (2*nBlock).
double length () const
Sum of the lengths of all blocks in the polymer (thread model).
int nBead () const
Total number of beads in the polymer (bead model).
PolymerType::Enum type () const
Get Polymer type (Branched or Linear)
Public Member Functions inherited from Pscf::Species
Species ()
Default constructor.
double phi () const
Get the overall volume fraction for this species.
double mu () const
Get the chemical potential for this species (units kT=1).
double q () const
Get the molecular partition function for this species.
Ensemble ensemble ()
Get the statistical ensemble for this species (open or closed).
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Public Types inherited from Pscf::PolymerTmpl< Block >
Public Types inherited from Pscf::Species
enum Ensemble
Statistical ensemble for number of molecules.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Pscf::PolymerTmpl< Block >
virtual void allocateBlocks ()
Allocate array of Block objects.
virtual void readBlocks (std::istream &in)
Read array of data for blocks from parameter file.
Protected Member Functions inherited from Pscf::PolymerSpecies
virtual void makePlan ()
Make a plan for order in which propagators should be computed.
void makePaths ()
Create a matrix of vertex-to-vertex path signposts.
void isValid ()
Check validity of the polymer graph.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes inherited from Pscf::Species
double phi_
Volume fraction, set by either setPhi or a solve function.
double mu_
Chemical potential, set by either setPhi or a solve function.
double q_
Partition function, set in subclass by a solve function.
Ensemble ensemble_
Statistical ensemble for this species (open or closed).
Detailed Description
Descriptor and solver for a branched polymer species.
The block concentrations stored in the constituent Block objects contain the block concentrations (i.e., volume fractions) computed in the most recent call of the compute function.
The phi() and mu() accessor functions, which are inherited from PolymerTmp<Block>, return the value of phi (spatial average volume fraction of a species) or mu (chemical potential) computed in the last call of the compute function. If the ensemble for this species is closed, phi is read from the parameter file and mu is computed. If the ensemble is open, mu is read from the parameter file and phi is computed.
Parameter File Format
Definition at line 39 of file r1d/solvers/Polymer.h.
Constructor & Destructor Documentation
Polymer()
Pscf::R1d::Polymer::Polymer ()
Default constructor.
Definition at line 14 of file r1d/solvers/Polymer.cpp.
References Util::ParamComposite::setClassName().
~Polymer()
Pscf::R1d::Polymer::~Polymer ()
Destructor.
Definition at line 17 of file r1d/solvers/Polymer.cpp.
Member Function Documentation
setPhi()
void Pscf::R1d::Polymer::setPhi (double phi)
Set volume fraction (if ensemble is closed).
Parameters
phi new volume fraction for this species
Definition at line 20 of file r1d/solvers/Polymer.cpp.
References Pscf::PolymerTmpl< Block >::ensemble(), Pscf::PolymerTmpl< Block >::phi(), and UTIL_CHECK.
setMu()
void Pscf::R1d::Polymer::setMu (double mu)
Set chemical potential mu (if ensemble is open).
Parameters
mu new chemical potential for this species
Definition at line 28 of file r1d/solvers/Polymer.cpp.
References Pscf::PolymerTmpl< Block >::ensemble(), Pscf::PolymerTmpl< Block >::mu(), and UTIL_CHECK.
compute()
void Pscf::R1d::Polymer::compute (DArray< Block::WField > const & wFields)
Compute solution to modified diffusion equation.
Upon return, q functions and block concentration fields are computed for all propagators and blocks.
Parameters
wFields array of chemica potential fields.
Definition at line 37 of file r1d/solvers/Polymer.cpp.
References Pscf::PolymerTmpl< Block >::block(), Pscf::PolymerTmpl< Block >::length(), Pscf::PolymerTmpl< Block >::nBlock(), Pscf::PolymerTmpl< Block >::phi(), Pscf::PolymerTmpl< Block >::q(), and Pscf::PolymerTmpl< Block >::solve().
The documentation for this class was generated from the following files:
r1d/solvers/Polymer.h
r1d/solvers/Polymer.cpp