PSCF: Pscf::Rpg::ImposedFieldsGenerator< D > Class Template Reference
Pscf::Rpg::ImposedFieldsGenerator< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Self-Consistent Field Theory (SCFT) » Iterators
Class defining mask & external fields to impose on the calculation.
#include <ImposedFieldsGenerator.h>
Public Member Functions
ImposedFieldsGenerator (System< D > &sys)
Constructor.
~ImposedFieldsGenerator ()
Destructor.
std::string type () const
Get the type string associated with this object.
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Pscf::ImposedFieldsTmpl
ImposedFieldsTmpl ()
Constructor.
~ImposedFieldsTmpl ()
Destructor.
void readParameters (std::istream &in)
Read parameters from input stream.
void setup ()
Allocate, check compatibility, calculate, and store the field(s).
void update ()
Check whether system has changed, update the field(s) if necessary.
double correctedStress (int paramId, double stress) const
Correct the stress value if necessary.
std::string type () const
Get the type string associated with this object.
FieldGenerator const & fieldGenerator1 () const
Return const references to the FieldGenerator child objects.
GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to a Sweep object.
void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from Pscf::ParameterModifier
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Protected Member Functions
virtual double modifyStress (int paramId, double stress) const
Modify the stress value if necessary.
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from Pscf::ImposedFieldsTmpl
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
FieldGenerator * fieldGenPtr1_
Pointer to the first FieldGenerator object (required).
FieldGenerator * fieldGenPtr2_
Pointer to the second FieldGenerator object (optional).
Protected Attributes inherited from Pscf::ImposedFieldsTmpl
FieldGenerator * fieldGenPtr1_
Pointer to the first FieldGenerator object (required).
FieldGenerator * fieldGenPtr2_
Pointer to the second FieldGenerator object (optional).
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<int D>
class Pscf::Rpg::ImposedFieldsGenerator< D >
Class defining mask & external fields to impose on the calculation.
Definition at line 28 of file rpg/scft/iterator/ImposedFieldsGenerator.h.
Constructor & Destructor Documentation
ImposedFieldsGenerator()
template<int D> Pscf::Rpg::ImposedFieldsGenerator< D >::ImposedFieldsGenerator (System< D > & sys)
Constructor.
Parameters
sys System parent object
Definition at line 20 of file rpg/scft/iterator/ImposedFieldsGenerator.tpp.
References Pscf::Rpg::ImposedFieldsGenerator< D >::setClassName().
~ImposedFieldsGenerator()
template<int D> Pscf::Rpg::ImposedFieldsGenerator< D >::~ImposedFieldsGenerator ()
Destructor.
Definition at line 27 of file rpg/scft/iterator/ImposedFieldsGenerator.tpp.
Member Function Documentation
modifyStress()
template<int D> double Pscf::Rpg::ImposedFieldsGenerator< D >::modifyStress (int paramId, double stress) const protected virtual
Modify the stress value if necessary.
It may be preferable with certain imposed fields to minimize a property other than fHelmholtz with respect to the lattice parameters. For instance, in a thin film it is useful to minimize the excess free energy per unit area, (fHelmholtz - fRef) * Delta, where fRef is a reference free energy and Delta is the film thickness. Therefore, this method modifies the stress value accordingly, depending on the "type" parameter that is read from the parameter file. This method is called by the method correctedStress after adding in the stress contributions from non-affine distortions of the imposed fields.
In some cases, the modification may be performed directly by this class, and in others it requires parameters that are stored in the FieldGenerator objects. In the latter case, the method FieldGenerator::modifyStress is called to perform the actual modification. The specific way that the modification is performed is determined based on the "type" parameter of this object.
Parameters
paramId index of the lattice parameter with this stress
stress stress value
Reimplemented from Pscf::ImposedFieldsTmpl.
Definition at line 39 of file rpg/scft/iterator/ImposedFieldsGenerator.tpp.
type()
template<int D> std::string Pscf::ImposedFieldsTmpl::type () const
Get the type string associated with this object.
Definition at line 103 of file ImposedFieldsTmpl.cpp.
Referenced by pscfpp.field.Field::__init__(), pscfpp.field.Field::__str__(), and pscfpp.field.Field::read().
isActive()
template<int D> bool Util::ParamComposite::isActive () const inline
Is this parameter active?
Definition at line 889 of file ParamComposite.h.
setClassName()
template<int D> void Util::ParamComposite::setClassName (const char * className) protected
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by Pscf::Rpg::ImposedFieldsGenerator< D >::ImposedFieldsGenerator().
Member Data Documentation
fieldGenPtr1_
template<int D> FieldGenerator* Pscf::ImposedFieldsTmpl::fieldGenPtr1_ protected
Pointer to the first FieldGenerator object (required).
This FieldGenerator may generate a mask, a set of external fields, or both.
Definition at line 190 of file ImposedFieldsTmpl.h.
fieldGenPtr2_
template<int D> FieldGenerator* Pscf::ImposedFieldsTmpl::fieldGenPtr2_ protected
Pointer to the second FieldGenerator object (optional).
If fieldGenPtr1_ points to an object that generates a mask, then fieldGenPtr2_ points to an object that generates a set of external fields, and vice versa. If fieldGenPtr1_ points to an object that generates both, then fieldGenPtr2_ must be a null pointer.
Definition at line 200 of file ImposedFieldsTmpl.h.
The documentation for this class was generated from the following files:
rpg/scft/iterator/ImposedFieldsGenerator.h
rpg/scft/iterator/ImposedFieldsGenerator.tpp