PSCF: Pscf::Rpg::Analyzer< D > Class Template Reference
Pscf::Rpg::Analyzer< D > Class Template Reference abstract
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Field Theoretic Simulation (FTS) » Analyzers
Abstract base for periodic output and/or analysis actions.
#include <Analyzer.h>
Public Member Functions
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters from archive.
virtual void setup ()
Complete any required initialization.
virtual void sample (long iStep)=0
Calculate, analyze and/or output a physical quantity.
virtual void output ()
Output any results at the end of the simulation.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Static Public Member Functions
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes
static long baseInterval
The interval for every Analyzer must be a multiple of baseInterval.
Protected Member Functions
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (const std::string &suffix) const
Return outputFileName string with added suffix.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Detailed Description
template<int D>
class Pscf::Rpg::Analyzer< D >
Abstract base for periodic output and/or analysis actions.
The periodic action associated with an Analyzer may involve retrieval or computation of a physical property, adding it to a statistical accumulator, and/or outputting it to file. This periodic action must be implemented by the pure virtual sample() method.
The sample() method should take the desired action only when the simulation step index is an integer multiple of the associated interval parameter. The interval must be a positive integer that is a multiple of the static member Analyzer::baseInterval, which is set equal to 1 by default.
Definition at line 33 of file rpg/fts/analyzer/Analyzer.h.
Constructor & Destructor Documentation
Analyzer()
template<int D> Pscf::Rpg::Analyzer< D >::Analyzer ()
Default constructor.
Definition at line 23 of file rpg/fts/analyzer/Analyzer.tpp.
~Analyzer()
template<int D> Pscf::Rpg::Analyzer< D >::~Analyzer () virtual
Destructor.
Definition at line 34 of file rpg/fts/analyzer/Analyzer.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::Analyzer< D >::readParameters (std::istream & in) virtual
Read parameters from archive.
Default implementation, reads interval and outputFileName.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Reimplemented in Pscf::Rpg::AverageAnalyzer< D >, Pscf::Rpg::AverageListAnalyzer< D >, Pscf::Rpg::BinaryStructureFactorGrid< D >, Pscf::Rpg::ConcentrationWriter< D >, Pscf::Rpg::HamiltonianAnalyzer< D >, Pscf::Rpg::StepLogger< D >, and Pscf::Rpg::TrajectoryWriter< D >.
Definition at line 41 of file rpg/fts/analyzer/Analyzer.tpp.
Referenced by Pscf::Rpg::AverageAnalyzer< D >::readParameters(), Pscf::Rpg::AverageListAnalyzer< D >::readParameters(), Pscf::Rpg::ConcentrationWriter< D >::readParameters(), and Pscf::Rpg::TrajectoryWriter< D >::readParameters().
setup()
template<int D> virtual void Pscf::Rpg::Analyzer< D >::setup () inline virtual
Complete any required initialization.
This method will be called just before the beginning of the main simulation loop, after an initial field configuration is known. It may be used to complete any initialization that cannot be completed in the readParameters method.
The default implementation is an empty function.
Reimplemented in Pscf::Rpg::AverageAnalyzer< D >, Pscf::Rpg::AverageListAnalyzer< D >, Pscf::Rpg::BinaryStructureFactorGrid< D >, Pscf::Rpg::ConcentrationWriter< D >, Pscf::Rpg::FourthOrderParameter< D >, Pscf::Rpg::MaxOrderParameter< D >, and Pscf::Rpg::TrajectoryWriter< D >.
Definition at line 67 of file rpg/fts/analyzer/Analyzer.h.
sample()
template<int D> virtual void Pscf::Rpg::Analyzer< D >::sample (long iStep) pure virtual
Calculate, analyze and/or output a physical quantity.
Take an action if iStep is a multiple of interval. If iStep is not a multiple of interval, this method should do nothing and return immediately.
Parameters
iStep current simulation step index.
Implemented in Pscf::Rpg::AverageAnalyzer< D >, Pscf::Rpg::AverageListAnalyzer< D >, Pscf::Rpg::BinaryStructureFactorGrid< D >, Pscf::Rpg::ConcentrationWriter< D >, Pscf::Rpg::StepLogger< D >, and Pscf::Rpg::TrajectoryWriter< D >.
output()
template<int D> virtual void Pscf::Rpg::Analyzer< D >::output () inline virtual
Output any results at the end of the simulation.
The default implementation is an empty function.
Reimplemented in Pscf::Rpg::AverageAnalyzer< D >, Pscf::Rpg::AverageListAnalyzer< D >, Pscf::Rpg::BinaryStructureFactorGrid< D >, Pscf::Rpg::ConcentrationWriter< D >, and Pscf::Rpg::TrajectoryWriter< D >.
Definition at line 86 of file rpg/fts/analyzer/Analyzer.h.
interval()
template<int D> int Pscf::Rpg::Analyzer< D >::interval () const inline
Get interval value.
Definition at line 170 of file rpg/fts/analyzer/Analyzer.h.
isAtInterval()
template<int D> bool Pscf::Rpg::Analyzer< D >::isAtInterval (long counter) const inline
Return true iff counter is a multiple of the interval.
Parameters
counter simulation step counter
Definition at line 177 of file rpg/fts/analyzer/Analyzer.h.
initStatic()
template<int D> void Pscf::Rpg::Analyzer< D >::initStatic () static
Define and initialize baseInterval.
Definition at line 16 of file rpg/fts/analyzer/Analyzer.tpp.
setFileMaster()
template<int D> void Pscf::Rpg::Analyzer< D >::setFileMaster (FileMaster & fileMaster) protected
Set the FileMaster to use to open files.
Definition at line 85 of file rpg/fts/analyzer/Analyzer.tpp.
readInterval()
template<int D> void Pscf::Rpg::Analyzer< D >::readInterval (std::istream & in) protected
Read interval from file, with error checking.
Parameters
in input parameter file stream
Definition at line 51 of file rpg/fts/analyzer/Analyzer.tpp.
References Util::ParamComposite::readOptional(), and UTIL_THROW.
Referenced by Pscf::Rpg::StepLogger< D >::readParameters().
readOutputFileName()
template<int D> void Pscf::Rpg::Analyzer< D >::readOutputFileName (std::istream & in) protected
Read outputFileName from file.
Parameters
in input parameter file stream.
Definition at line 78 of file rpg/fts/analyzer/Analyzer.tpp.
fileMaster()
template<int D> FileMaster & Pscf::Rpg::Analyzer< D >::fileMaster () protected
Get the FileMaster by reference.
This can be used to open multiple output files.
Definition at line 92 of file rpg/fts/analyzer/Analyzer.tpp.
outputFileName() [1/2]
template<int D> const std::string & Pscf::Rpg::Analyzer< D >::outputFileName () const inline protected
Return outputFileName string.
Definition at line 184 of file rpg/fts/analyzer/Analyzer.h.
outputFileName() [2/2]
template<int D> std::string Pscf::Rpg::Analyzer< D >::outputFileName (const std::string & suffix) const protected
Return outputFileName string with added suffix.
Definition at line 103 of file rpg/fts/analyzer/Analyzer.tpp.
Member Data Documentation
baseInterval
template<int D> long Pscf::Rpg::Analyzer< D >::baseInterval static
The interval for every Analyzer must be a multiple of baseInterval.
Definition at line 106 of file rpg/fts/analyzer/Analyzer.h.
The documentation for this class was generated from the following files:
rpg/fts/analyzer/Analyzer.h
rpg/fts/analyzer/Analyzer.tpp