PSCF: Pscf::MeshIterator< D > Class Template Reference
Pscf::MeshIterator< D > Class Template Reference
Pscf namespace » Pscf Common » Spatial Mesh
Iterator over points in a Mesh<D>.
#include <MeshIterator.h>
Public Member Functions
MeshIterator ()
Default constructor.
MeshIterator (const IntVec< D > &dimensions)
Constructor.
void setDimensions (const IntVec< D > &dimensions)
Set the grid dimensions in all directions.
void begin ()
Set iterator to the first point in the mesh.
void operator++ ()
Increment iterator to next mesh point.
bool atEnd () const
Is this the end (i.e., one past the last point)?
IntVec< D > position () const
Get current position in the grid, as integer vector.
int position (int i) const
Get component i of the current position vector.
int rank () const
Get the rank of current element.
Detailed Description
template<int D>
class Pscf::MeshIterator< D >
Iterator over points in a Mesh<D>.
A mesh iterator iterates over the points of a mesh, keeping track of both the IntVec<D> position and integer rank of the current point as it goes.
Definition at line 28 of file MeshIterator.h.
Constructor & Destructor Documentation
MeshIterator() [1/2]
template<int D> Pscf::MeshIterator< D >::MeshIterator ()
Default constructor.
Definition at line 20 of file MeshIterator.tpp.
MeshIterator() [2/2]
template<int D> Pscf::MeshIterator< D >::MeshIterator (const IntVec< D > & dimensions)
Constructor.
Parameters
dimensions IntVec<D> of grid dimensions
Definition at line 31 of file MeshIterator.tpp.
References Pscf::MeshIterator< D >::setDimensions().
Member Function Documentation
setDimensions()
template<int D> void Pscf::MeshIterator< D >::setDimensions (const IntVec< D > & dimensions)
Set the grid dimensions in all directions.
Parameters
dimensions IntVec<D> of grid dimensions.
Definition at line 42 of file MeshIterator.tpp.
References UTIL_THROW.
Referenced by Pscf::Rpc::FourthOrderParameter< D >::compute(), Pscf::Rpc::MaxOrderParameter< D >::compute(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpc::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::Rpg::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::MeshIterator< D >::MeshIterator(), and Pscf::Rpg::BinaryStructureFactorGrid< D >::setup().
begin()
template<int D> void Pscf::MeshIterator< D >::begin ()
Set iterator to the first point in the mesh.
Definition at line 61 of file MeshIterator.tpp.
Referenced by Pscf::Rpg::WaveList< D >::allocate(), Pscf::Rpc::FourthOrderParameter< D >::compute(), Pscf::Rpc::MaxOrderParameter< D >::compute(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::WaveList< D >::computeMinimumImages(), Pscf::Rpc::FourthOrderParameter< D >::computePrefactor(), Pscf::Rpg::FourthOrderParameter< D >::computePrefactor(), Pscf::Rpc::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::Rpg::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::Prdc::Basis< D >::isValid(), Pscf::Rpc::BinaryStructureFactorGrid< D >::setup(), and Pscf::Rpg::BinaryStructureFactorGrid< D >::setup().
operator++()
template<int D> void Pscf::MeshIterator< D >::operator++ () inline
Increment iterator to next mesh point.
Definition at line 76 of file MeshIterator.tpp.
atEnd()
template<int D> bool Pscf::MeshIterator< D >::atEnd () const inline
Is this the end (i.e., one past the last point)?
Definition at line 141 of file MeshIterator.h.
Referenced by Pscf::Rpg::WaveList< D >::allocate(), Pscf::Rpc::FourthOrderParameter< D >::compute(), Pscf::Rpc::MaxOrderParameter< D >::compute(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::WaveList< D >::computeMinimumImages(), Pscf::Rpc::FourthOrderParameter< D >::computePrefactor(), Pscf::Rpg::FourthOrderParameter< D >::computePrefactor(), Pscf::Rpc::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::Rpg::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::Prdc::Basis< D >::isValid(), Pscf::Rpc::BinaryStructureFactorGrid< D >::setup(), and Pscf::Rpg::BinaryStructureFactorGrid< D >::setup().
position() [1/2]
template<int D> IntVec< D > Pscf::MeshIterator< D >::position () const inline
Get current position in the grid, as integer vector.
Definition at line 122 of file MeshIterator.h.
Referenced by Pscf::Rpg::WaveList< D >::allocate(), Pscf::Rpc::FourthOrderParameter< D >::compute(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::WaveList< D >::computeMinimumImages(), Pscf::Rpc::FourthOrderParameter< D >::computePrefactor(), Pscf::Rpg::FourthOrderParameter< D >::computePrefactor(), Pscf::Prdc::Basis< D >::isValid(), and Pscf::Rpc::BinaryStructureFactorGrid< D >::setup().
position() [2/2]
template<int D> int Pscf::MeshIterator< D >::position (int i) const inline
Get component i of the current position vector.
Parameters
i index of Cartesian direction 0 <=i < D.
Definition at line 127 of file MeshIterator.h.
rank()
template<int D> int Pscf::MeshIterator< D >::rank () const inline
Get the rank of current element.
Definition at line 136 of file MeshIterator.h.
Referenced by Pscf::Rpg::WaveList< D >::allocate(), Pscf::Rpc::FourthOrderParameter< D >::compute(), Pscf::Rpc::MaxOrderParameter< D >::compute(), Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::WaveList< D >::computeMinimumImages(), Pscf::Rpc::FourthOrderParameter< D >::computePrefactor(), Pscf::Rpg::FourthOrderParameter< D >::computePrefactor(), Pscf::Rpc::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::Rpg::BinaryStructureFactorGrid< D >::computeStructureFactor(), Pscf::Rpc::BinaryStructureFactorGrid< D >::setup(), and Pscf::Rpg::BinaryStructureFactorGrid< D >::setup().
The documentation for this class was generated from the following files:
MeshIterator.h
MeshIterator.tpp