PSCF: Util::Rational Class Reference
Util::Rational Class Reference
Util namespace » Mathematics
A Rational number (a ratio of integers).
#include <Rational.h>
Public Member Functions
Constructors
Rational ()
Default constructor.
Rational (int num, int den)
Constructor, explicit numerator and denominator.
Rational (int number)
Constructor, construct from integer.
Rational (Rational const &v)
Copy constructor.
~Rational ()
Destructor.
Assignment and Conversion.
Rational & operator= (Rational const &other)
Copy assignment from another Rational.
Rational & operator= (int other)
Assignment from integer.
Arithmetic Assignment Operators
Rational & operator+= (Rational const &a)
Add another rational to this one.
Rational & operator+= (int a)
Add an integer to this rational.
Rational & operator-= (Rational const &a)
Subtract another rational from this one.
Rational & operator-= (int)
Subtract an integer from this rational.
Rational & operator*= (Rational const &a)
Multiply this rational by another.
Rational & operator*= (int a)
Multiply this rational by an integer.
Rational & operator/= (Rational const &a)
Divide this rational by another.
Rational & operator/= (int a)
Divide this rational by an integer.
Accessors
int num () const
Return numerator.
int den () const
Return denominator.
operator double () const
Cast (convert) to double precision floating point.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Rational operator+ (Rational const &a, Rational const &b)
Compute sum of two rationals.
Rational operator+ (Rational const &a, int b)
Compute sum of rational and integer.
Rational operator- (Rational const &a, Rational const &b)
Compute difference of rationals.
Rational operator- (Rational const &a, int b)
Compute difference of rational and integer.
Rational operator- (int b, Rational const &a)
Compute difference of integer and rational.
Rational operator* (Rational const &a, Rational const &b)
Compute product of rationals.
Rational operator* (Rational const &a, int b)
Compute product of rational and integer.
Rational operator/ (Rational const &a, Rational const &b)
Compute quotient of two rationals.
Rational operator/ (Rational const &a, int b)
Compute quotient Rational divided by integer.
Rational operator/ (int b, Rational const &a)
Compute quotient integer divided by Rational.
bool operator== (Rational const &a, Rational const &b)
Equality operators.
bool operator== (Rational const &a, int b)
Equality operator for a Rational and an integer.
Rational operator- (Rational const &a)
Unary negation of Rational.
std::ostream & operator<< (std::ostream &out, Rational const &rational)
Output stream inserter for a Rational.
Detailed Description
A Rational number (a ratio of integers).
A rational is always stored in a standard reduced form in which the denominator is a positive integer and the numerator and denominator have no common divisors other than unity. All integers, including zero, are stored with a denominator of 1.
Definition at line 33 of file Rational.h.
Constructor & Destructor Documentation
Rational() [1/4]
Util::Rational::Rational () inline
Default constructor.
Definition at line 271 of file Rational.h.
Referenced by operator*, operator*, operator*=(), operator*=(), operator+, operator+, operator+=(), operator+=(), operator-, operator-, operator-, operator-, operator-=(), operator-=(), operator/, operator/, operator/, operator/=(), operator/=(), operator<<, operator=(), operator=(), operator==, operator==, and Rational().
Rational() [2/4]
Util::Rational::Rational (int num, int den) inline
Constructor, explicit numerator and denominator.
Denominator is reduced to greatest common divisor before return.
Parameters
num numerator
den denominator
Definition at line 280 of file Rational.h.
References den(), and num().
Rational() [3/4]
Util::Rational::Rational (int number) inline
Constructor, construct from integer.
Creates a rational with a denominator == 1.
Parameters
number integer number.
Definition at line 289 of file Rational.h.
Rational() [4/4]
Util::Rational::Rational (Rational const & v) inline
Copy constructor.
Parameters
v Rational to be copied
Definition at line 298 of file Rational.h.
References Rational().
~Rational()
Util::Rational::~Rational () inline
Destructor.
Definition at line 75 of file Rational.h.
Member Function Documentation
operator=() [1/2]
Rational & Util::Rational::operator= (Rational const & other) inline
Copy assignment from another Rational.
Parameters
other Rational to assign.
Definition at line 307 of file Rational.h.
References Rational().
operator=() [2/2]
Rational & Util::Rational::operator= (int other) inline
Assignment from integer.
Creates an integer using a denominator == 1.
Parameters
other integer to assign.
Definition at line 318 of file Rational.h.
References Rational().
operator+=() [1/2]
Rational & Util::Rational::operator+= (Rational const & a) inline
Add another rational to this one.
Upon return, *this = this + a.
Parameters
a increment (input)
Definition at line 331 of file Rational.h.
References Rational().
operator+=() [2/2]
Rational & Util::Rational::operator+= (int a) inline
Add an integer to this rational.
Upon return, *this = this + a.
Parameters
a increment (input)
Definition at line 343 of file Rational.h.
References Rational().
operator-=() [1/2]
Rational & Util::Rational::operator-= (Rational const & a) inline
Subtract another rational from this one.
Upon return, *this = this + a.
Parameters
a rational decrement (input)
Definition at line 354 of file Rational.h.
References Rational().
operator-=() [2/2]
Rational & Util::Rational::operator-= (int a) inline
Subtract an integer from this rational.
Upon return, *this = this + a.
Parameters
a integer decrement (input)
Definition at line 366 of file Rational.h.
References Rational().
operator*=() [1/2]
Rational & Util::Rational::operator*= (Rational const & a) inline
Multiply this rational by another.
Upon return, *this = this*a.
Parameters
a Rational number to multiply this by (input)
Definition at line 377 of file Rational.h.
References Rational().
operator*=() [2/2]
Rational & Util::Rational::operator*= (int a) inline
Multiply this rational by an integer.
Upon return, *this = this*a.
Parameters
a integer to multiply this by (input)
Definition at line 389 of file Rational.h.
References Rational().
operator/=() [1/2]
Rational & Util::Rational::operator/= (Rational const & a) inline
Divide this rational by another.
Upon return, *this = this*a.
Parameters
a rational number to divide this by (input)
Definition at line 400 of file Rational.h.
References Rational(), and UTIL_THROW.
operator/=() [2/2]
Rational & Util::Rational::operator/= (int a) inline
Divide this rational by an integer.
Upon return, *this = this*a.
Parameters
a integer to divide this by (input)
Definition at line 415 of file Rational.h.
References Rational(), and UTIL_THROW.
num()
int Util::Rational::num () const inline
Return numerator.
Definition at line 431 of file Rational.h.
Referenced by operator*, operator+, operator+, operator-, operator-, operator-, operator/, and Rational().
den()
int Util::Rational::den () const inline
Return denominator.
Definition at line 438 of file Rational.h.
Referenced by operator*, operator+, operator-, operator/, and Rational().
operator double()
Util::Rational::operator double () const inline
Cast (convert) to double precision floating point.
Returns
double precision representation of this.
Definition at line 445 of file Rational.h.
serialize()
template<class Archive> void Util::Rational::serialize (Archive & ar, const unsigned int version) inline
Serialize to/from an archive.
Parameters
ar archive
version archive version id
Definition at line 454 of file Rational.h.
Friends And Related Symbol Documentation
operator+ [1/2]
Rational operator+ (Rational const & a, Rational const & b) friend
Compute sum of two rationals.
Parameters
a 1st argument
b 2st argument
Returns
sum a + b
Definition at line 490 of file Rational.h.
References den(), num(), and Rational().
operator+ [2/2]
Rational operator+ (Rational const & a, int b) friend
Compute sum of rational and integer.
Parameters
a Rational argument
b integer argument
Returns
sum a + b
Definition at line 505 of file Rational.h.
References num(), and Rational().
operator- [1/4]
Rational operator- (Rational const & a, Rational const & b) friend
Compute difference of rationals.
Parameters
a 1st argument
b 2st argument
Returns
difference a - b
Definition at line 530 of file Rational.h.
References den(), num(), and Rational().
operator- [2/4]
Rational operator- (Rational const & a, int b) friend
Compute difference of rational and integer.
Parameters
a Rational argument
b integer argument
Returns
difference a - b
Definition at line 545 of file Rational.h.
References num(), and Rational().
operator- [3/4]
Rational operator- (int b, Rational const & a) friend
Compute difference of integer and rational.
Parameters
b integer argument
a Rational argument
Returns
difference b - a
Definition at line 559 of file Rational.h.
References num(), and Rational().
operator* [1/2]
Rational operator* (Rational const & a, Rational const & b) friend
Compute product of rationals.
Parameters
a 1st Rational argument
b 2st Rational argument
Returns
product a*b
Definition at line 573 of file Rational.h.
References den(), num(), and Rational().
operator* [2/2]
Rational operator* (Rational const & a, int b) friend
Compute product of rational and integer.
Parameters
a Rational argument
b integer argument
Returns
product a*b
Definition at line 588 of file Rational.h.
References Rational().
operator/ [1/3]
Rational operator/ (Rational const & a, Rational const & b) friend
Compute quotient of two rationals.
Parameters
a 1st Rational argument (numerator)
b 2st Rational argument (denominator)
Returns
ratio a/b
Definition at line 610 of file Rational.h.
References den(), num(), Rational(), and UTIL_THROW.
operator/ [2/3]
Rational operator/ (Rational const & a, int b) friend
Compute quotient Rational divided by integer.
Parameters
a Rational argument (numerator)
b integer argument (denominator)
Returns
ratio a/b
Definition at line 628 of file Rational.h.
References Rational(), and UTIL_THROW.
operator/ [3/3]
Rational operator/ (int b, Rational const & a) friend
Compute quotient integer divided by Rational.
Parameters
b integer argument (numerator)
a Rational argument (denominator)
Returns
ratio b/a
Definition at line 644 of file Rational.h.
References Rational(), and UTIL_THROW.
operator== [1/2]
bool operator== (Rational const & a, Rational const & b) friend
Equality operators.
Equality operator for two Rational numbers.
Parameters
a 1st Rational
b 2nd Rational
Returns
true if equal, false otherwise
Definition at line 674 of file Rational.h.
References Rational().
operator== [2/2]
bool operator== (Rational const & a, int b) friend
Equality operator for a Rational and an integer.
Parameters
a Rational number
b integer number
Returns
true if equal, false otherwise
Definition at line 684 of file Rational.h.
References Rational().
operator- [4/4]
Rational operator- (Rational const & a) friend
Unary negation of Rational.
Parameters
a Rational number
Returns
negation -a
Definition at line 661 of file Rational.h.
References Rational().
operator<<
std::ostream & operator<< (std::ostream & out, Rational const & rational) friend
Output stream inserter for a Rational.
Output elements of a rational to stream, without line breaks.
Parameters
out output stream
rational Rational to be written to stream
Returns
modified output stream
Definition at line 16 of file Rational.cpp.
References Rational(), and UTIL_CHECK.
The documentation for this class was generated from the following file:
Rational.h