PSCF: Pscf::Prdc::Cuda::RField< D > Class Template Reference
Pscf::Prdc::Cuda::RField< D > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CUDA)
Field of real values on a regular mesh, allocated on a GPU device.
#include <RField.h>
Public Member Functions
RField ()
Default constructor.
RField (IntVec< D > const &meshDimensions)
Allocating constructor.
RField (RField< D > const &other)
Copy constructor.
virtual ~RField ()
Destructor.
void allocate (IntVec< D > const &meshDimensions)
Allocate the underlying C array for data on a regular mesh.
void associate (DeviceArray< cudaReal > &arr, int beginId, IntVec< D > const &meshDimensions)
Associate this object with a slice of another DeviceArray.
RField< D > & operator= (const RField< D > &other)
Assignment operator, assignment from another RField<D>.
RField< D > & operator= (const HostDArray< cudaReal > &other)
Assignment operator, assignment from a HostDArray<cudaReal>.
IntVec< D > const & meshDimensions () const
Return mesh dimensions by constant reference.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize a Field to/from an Archive.
Public Member Functions inherited from Pscf::DeviceArray< cudaReal >
DeviceArray ()
Default constructor.
DeviceArray (int capacity)
Allocating constructor.
DeviceArray (DeviceArray< cudaReal > const &other)
Copy constructor.
virtual ~DeviceArray ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array on the device.
void associate (DeviceArray< cudaReal > &arr, int beginId, int capacity)
Associate this object with a slice of a different DeviceArray.
void deallocate ()
Dellocate the underlying C array.
void dissociate ()
Dissociate this object from the associated array.
virtual DeviceArray< cudaReal > & operator= (const DeviceArray< cudaReal > &other)
Assignment operator, assign from another DeviceArray<Data> array.
virtual DeviceArray< cudaReal > & operator= (const HostDArray< cudaReal > &other)
Assignment operator, assignment from HostDArray<Data> host array.
int capacity () const
Return allocated capacity.
bool isAllocated () const
Return true if the array has been allocated, false otherwise.
bool isOwner () const
Does this object own the underlying data?
cudaReal * cArray ()
Return pointer to underlying C array.
cudaReal const * cArray () const
Return const pointer to underlying C array.
Additional Inherited Members
Public Types inherited from Pscf::DeviceArray< cudaReal >
typedef cudaReal ElementType
Data type of each element.
Protected Attributes inherited from Pscf::DeviceArray< cudaReal >
cudaReal * dataPtr_
Pointer to a C array of Data elements on the GPU device.
int capacity_
Allocated size (capacity) of the array.
DeviceArray< cudaReal > const * ownerPtr_
Pointer to array that owns this data, if isOwner_ == false.
int ownerCapacity_
Capacity of parent array, if isOwner_ == false.
cudaReal const * ownerDataPtr_
Const pointer to parent array, if isOwner_ == false.
Detailed Description
template<int D>
class Pscf::Prdc::Cuda::RField< D >
Field of real values on a regular mesh, allocated on a GPU device.
Type cudaReal is float or double, depending on preprocessor macro.
Definition at line 31 of file cuda/RField.h.
Constructor & Destructor Documentation
RField() [1/3]
template<int D> Pscf::Prdc::Cuda::RField< D >::RField ()
Default constructor.
References meshDimensions().
Referenced by operator=(), operator=(), RField(), and RField().
RField() [2/3]
template<int D> Pscf::Prdc::Cuda::RField< D >::RField (IntVec< D > const & meshDimensions)
Allocating constructor.
Allocates memory by calling allocate(meshDimensions) internally.
Parameters
meshDimensions number of grid points in each dimension
Definition at line 32 of file cuda/RField.tpp.
References Pscf::Prdc::Cpu::RField< D >::allocate(), Pscf::DeviceArray< cudaReal >::DeviceArray(), meshDimensions(), and RField().
RField() [3/3]
template<int D> Pscf::Prdc::Cuda::RField< D >::RField (RField< D > const & other)
Copy constructor.
Allocates new memory and copies all elements by value.
Parameters
other the RField to be copied.
References RField().
~RField()
template<int D> virtual Pscf::Prdc::Cuda::RField< D >::~RField () virtual
Destructor.
Deletes underlying C array, if allocated previously.
Member Function Documentation
allocate()
template<int D> void Pscf::Prdc::Cuda::RField< D >::allocate (IntVec< D > const & meshDimensions)
Allocate the underlying C array for data on a regular mesh.
Exceptions
Exception if the RField is already allocated.
Parameters
meshDimensions number of grid points in each dimension
References associate(), Pscf::DeviceArray< cudaReal >::DeviceArray(), and meshDimensions().
Referenced by serialize().
associate()
template<int D> void Pscf::Prdc::Cuda::RField< D >::associate (DeviceArray< cudaReal > & arr, int beginId, IntVec< D > const & meshDimensions)
Associate this object with a slice of another DeviceArray.
Exceptions
Exception if the array is already allocated.
Parameters
arr parent array that owns the data
beginId index in the parent array at which this array starts
meshDimensions number of grid points in each dimension
Definition at line 71 of file cuda/RField.tpp.
References Pscf::DeviceArray< Data >::associate(), Pscf::DeviceArray< cudaReal >::DeviceArray(), meshDimensions(), and UTIL_CHECK.
Referenced by allocate(), and serialize().
operator=() [1/2]
template<int D> RField< D > & Pscf::Prdc::Cuda::RField< D >::operator= (const RField< D > & other)
Assignment operator, assignment from another RField<D>.
Performs a deep copy, by copying all elements of the RHS RField<D> from device memory to device memory, and copying the meshDimensions.
The RHS RField<D> must be allocated on entry. If this LHS object is not allocated, allocate with the required capacity. If the LHS and RHS arrays are both allocated, capacity values must be equal.
Parameters
other the RHS RField
References RField().
operator=() [2/2]
template<int D> RField< D > & Pscf::Prdc::Cuda::RField< D >::operator= (const HostDArray< cudaReal > & other)
Assignment operator, assignment from a HostDArray<cudaReal>.
Performs a deep copy, by copying all elements of the RHS RField<D> from host memory to device memory.
The RHS HostDArray<cudaReal> and LHS RField<D> must both be allocated with equal capacity values on entry.
Parameters
other the RHS HostDArray<cudaReal>
Definition at line 99 of file cuda/RField.tpp.
References Util::Array< Data >::capacity(), Pscf::DeviceArray< cudaReal >::capacity_, Pscf::DeviceArray< cudaReal >::isAllocated(), Util::DArray< Data >::isAllocated(), Pscf::DeviceArray< Data >::operator=(), RField(), and UTIL_THROW.
meshDimensions()
template<int D> IntVec< D > const & Pscf::Prdc::Cuda::RField< D >::meshDimensions () const
Return mesh dimensions by constant reference.
Referenced by allocate(), associate(), RField(), and RField().
serialize()
template<int D> template<class Archive> void Pscf::Prdc::Cuda::RField< D >::serialize (Archive & ar, const unsigned int version)
Serialize a Field to/from an Archive.
Parameters
ar archive
version archive version id
References allocate(), associate(), and Pscf::DeviceArray< cudaReal >::DeviceArray().
The documentation for this class was generated from the following files:
cuda/RField.h
cuda/RField.tpp