PSCF: Pscf::Rpc::ConcentrationWriter< D > Class Template Reference
Pscf::Rpc::ConcentrationWriter< D > Class Template Reference
Pscf namespace » Pscf::Rpc - Real Periodic Fields (CPU) » Field Theoretic Simulation (FTS) » Analyzers
Periodically write snapshots to a trajectory file.
#include <ConcentrationWriter.h>
Public Member Functions
ConcentrationWriter (Simulator< D > &simulator, System< D > &system)
Constructor.
virtual ~ConcentrationWriter ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval and output file name.
virtual void setup ()
Clear nSample counter.
virtual void sample (long iStep)
Write a frame/snapshot to trajectory file.
virtual void output ()
Close trajectory file after run.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
void setClassName (const char *className)
Set class name string.
Public Member Functions inherited from Pscf::Rpc::Analyzer< D >
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
void writeHeader (std::ofstream &out)
Write data that should appear once, at beginning of the file.
void writeFrame (std::ofstream &out, long iStep)
Write data that should appear in every frame.
System< D > & system ()
Return reference to parent system.
Simulator< D > & simulator ()
Return reference to parent Simulator.
Protected Member Functions inherited from Pscf::Rpc::Analyzer< D >
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Optionally read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (std::string suffix) const
Return outputFileName string with added suffix.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
long nSample_
Number of configurations dumped thus far (first dump is zero).
long isInitialized_
Has readParam been called?
Simulator< D > * simulatorPtr_
Pointer to parent Simulator.
System< D > * systemPtr_
Pointer to the parent system.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Pscf::Rpc::Analyzer< D >
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Pscf::Rpc::Analyzer< D >
static long baseInterval
The interval for an Analyzer must be a multiple of baseInterval.
Detailed Description
template<int D>
class Pscf::Rpc::ConcentrationWriter< D >
Periodically write snapshots to a trajectory file.
See also
Manual Page
Definition at line 30 of file rpc/fts/analyzer/ConcentrationWriter.h.
Constructor & Destructor Documentation
ConcentrationWriter()
template<int D> Pscf::Rpc::ConcentrationWriter< D >::ConcentrationWriter (Simulator< D > & simulator, System< D > & system)
Constructor.
Definition at line 35 of file rpc/fts/analyzer/ConcentrationWriter.tpp.
References Pscf::Rpc::Analyzer< D >::Analyzer(), isInitialized_, nSample_, setClassName(), simulator(), simulatorPtr_, system(), and systemPtr_.
~ConcentrationWriter()
template<int D> virtual Pscf::Rpc::ConcentrationWriter< D >::~ConcentrationWriter () inline virtual
Destructor.
Definition at line 43 of file rpc/fts/analyzer/ConcentrationWriter.h.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpc::ConcentrationWriter< D >::readParameters (std::istream & in) virtual
Read interval and output file name.
Parameters
in input parameter file
Reimplemented from Pscf::Rpc::Analyzer< D >.
Definition at line 48 of file rpc/fts/analyzer/ConcentrationWriter.tpp.
References isInitialized_, and Pscf::Rpc::Analyzer< D >::readParameters().
setup()
template<int D> void Pscf::Rpc::ConcentrationWriter< D >::setup () virtual
Clear nSample counter.
Reimplemented from Pscf::Rpc::Analyzer< D >.
Definition at line 58 of file rpc/fts/analyzer/ConcentrationWriter.tpp.
References nSample_, Pscf::Rpc::Analyzer< D >::outputFileName(), system(), and writeHeader().
sample()
template<int D> void Pscf::Rpc::ConcentrationWriter< D >::sample (long iStep) virtual
Write a frame/snapshot to trajectory file.
Parameters
iStep step index
Implements Pscf::Rpc::Analyzer< D >.
Definition at line 103 of file rpc/fts/analyzer/ConcentrationWriter.tpp.
References Pscf::Rpc::Analyzer< D >::isAtInterval(), nSample_, and writeFrame().
output()
template<int D> void Pscf::Rpc::ConcentrationWriter< D >::output () virtual
Close trajectory file after run.
Reimplemented from Pscf::Rpc::Analyzer< D >.
Definition at line 115 of file rpc/fts/analyzer/ConcentrationWriter.tpp.
writeHeader()
template<int D> void Pscf::Rpc::ConcentrationWriter< D >::writeHeader (std::ofstream & out) protected
Write data that should appear once, at beginning of the file.
Called by sample on first invocation. Default implementation is empty.
Parameters
out output file stream
Definition at line 87 of file rpc/fts/analyzer/ConcentrationWriter.tpp.
References Pscf::Rpc::Domain< D >::fieldIo(), system(), Pscf::Rpc::Domain< D >::unitCell(), and Pscf::Rpc::FieldIo< D >::writeFieldHeader().
Referenced by setup(), and writeFrame().
writeFrame()
template<int D> void Pscf::Rpc::ConcentrationWriter< D >::writeFrame (std::ofstream & out, long iStep) protected
Write data that should appear in every frame.
Parameters
out output file stream
iStep MC time step index
Definition at line 68 of file rpc/fts/analyzer/ConcentrationWriter.tpp.
References Pscf::Rpc::Domain< D >::fieldIo(), system(), Pscf::Rpc::Domain< D >::unitCell(), UTIL_CHECK, Pscf::Rpc::FieldIo< D >::writeFieldsRGrid(), and writeHeader().
Referenced by sample().
system()
template<int D> System< D > & Pscf::Rpc::ConcentrationWriter< D >::system () inline protected
Return reference to parent system.
Definition at line 133 of file rpc/fts/analyzer/ConcentrationWriter.h.
References systemPtr_.
Referenced by ConcentrationWriter(), setup(), writeFrame(), and writeHeader().
simulator()
template<int D> Simulator< D > & Pscf::Rpc::ConcentrationWriter< D >::simulator () inline protected
Return reference to parent Simulator.
Definition at line 138 of file rpc/fts/analyzer/ConcentrationWriter.h.
References simulatorPtr_.
Referenced by ConcentrationWriter().
read()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value)
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 305 of file ParamComposite.h.
setClassName()
template<int D> void Util::ParamComposite::setClassName (const char * className)
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by ConcentrationWriter().
Member Data Documentation
nSample_
template<int D> long Pscf::Rpc::ConcentrationWriter< D >::nSample_ protected
Number of configurations dumped thus far (first dump is zero).
Definition at line 84 of file rpc/fts/analyzer/ConcentrationWriter.h.
Referenced by ConcentrationWriter(), sample(), and setup().
isInitialized_
template<int D> long Pscf::Rpc::ConcentrationWriter< D >::isInitialized_ protected
Has readParam been called?
Definition at line 87 of file rpc/fts/analyzer/ConcentrationWriter.h.
Referenced by ConcentrationWriter(), and readParameters().
simulatorPtr_
template<int D> Simulator<D>* Pscf::Rpc::ConcentrationWriter< D >::simulatorPtr_ protected
Pointer to parent Simulator.
Definition at line 92 of file rpc/fts/analyzer/ConcentrationWriter.h.
Referenced by ConcentrationWriter(), and simulator().
systemPtr_
template<int D> System<D>* Pscf::Rpc::ConcentrationWriter< D >::systemPtr_ protected
Pointer to the parent system.
Definition at line 97 of file rpc/fts/analyzer/ConcentrationWriter.h.
Referenced by ConcentrationWriter(), and system().
The documentation for this class was generated from the following files:
rpc/fts/analyzer/ConcentrationWriter.h
rpc/fts/analyzer/ConcentrationWriter.tpp