PSCF: Pscf::Fd1d::System Class Reference
Pscf::Fd1d::System Class Reference
Pscf namespace » Finite-Difference 1D
Main class in SCFT simulation of one system.
#include <System.h>
Public Types
typedef DArray< double > Field
Generic Field type.
typedef DArray< double > WField
Monomer chemical potential field type.
typedef DArray< double > CField
Monomer concentration / volume fraction field type.
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Public Member Functions
Construction and Destruction
System ()
Constructor.
~System ()
Destructor.
Lifetime (Actions)
void setOptions (int argc, char **argv)
Process command line options.
virtual void readParam (std::istream &in)
Read input parameters (with opening and closing lines).
void readParam ()
Read input parameters from default param file.
virtual void readParameters (std::istream &in)
Read input parameters (without opening and closing lines).
void writeParamNoSweep (std::ostream &out) const
Write parameter file to an ostream, omitting the sweep block.
void readCommands (std::istream &in)
Read command script.
void readCommands ()
Read commands from default command file.
Primary SCFT Computations <br>
void compute ()
Solve the modified diffusion equation once, without iteration.
int iterate (bool isContinuation=false)
Iteratively solve a SCFT problem.
void sweep ()
Sweep in parameter space, solving an SCF problem at each point.
Thermodynamic Properties
void computeFreeEnergy ()
Compute free energy density and pressure for current fields.
double fHelmholtz () const
Get precomputed Helmoltz free energy per monomer / kT.
double pressure () const
Get precomputed pressure x monomer volume kT.
void writeThermo (std::ostream &out)
Write thermodynamic properties to a file.
Output Operations (correspond to command file commands)
void writeW (std::string const &filename)
Write chemical potential fields in symmetrized basis format.
void writeC (std::string const &filename)
Write concentration fields in symmetrized basis format.
void writeBlockC (std::string const &filename)
Write c-fields for all blocks and solvents in r-grid format.
Field Accessors
DArray< WField > & wFields ()
Get array of all chemical potential fields.
WField & wField (int monomerId)
Get chemical potential field for a specific monomer type.
DArray< CField > & cFields ()
Get array of all chemical potential fields.
CField & cField (int monomerId)
Get chemical potential field for a specific monomer type.
Member object accessors (get sub-objects by reference)
Mixture & mixture ()
Get Mixture by reference.
Mixture const & mixture () const
Get Mixture by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy) by reference.
Interaction const & interaction () const
Get interaction (i.e., excess free energy) by const reference.
Domain & domain ()
Get spatial domain (including grid info) by reference.
Iterator & iterator ()
Get the Iterator by reference.
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void readParam (std::istream &in)=0
Read parameter(s) from file.
virtual void writeParam (std::ostream &out) const =0
Read parameter(s) to file.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
virtual void resetParam ()
Nontrivial implementation provided by ParamComposite subclass.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
virtual void save (OArchive &ar)=0
Save to an archive.
virtual void load (IArchive &ar)=0
Load from an archive.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Additional Inherited Members
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
Main class in SCFT simulation of one system.
Parameter File Format
Definition at line 39 of file fd1d/System.h.
Member Typedef Documentation
Field
typedef DArray<double> Pscf::Fd1d::System::Field
Generic Field type.
Definition at line 45 of file fd1d/System.h.
WField
typedef DArray<double> Pscf::Fd1d::System::WField
Monomer chemical potential field type.
Definition at line 48 of file fd1d/System.h.
CField
typedef DArray<double> Pscf::Fd1d::System::CField
Monomer concentration / volume fraction field type.
Definition at line 51 of file fd1d/System.h.
Constructor & Destructor Documentation
System()
Pscf::Fd1d::System::System ()
Constructor.
Definition at line 39 of file fd1d/System.cpp.
References Pscf::Fd1d::FieldIo::associate(), Util::BracketPolicy::set(), and Util::ParamComposite::setClassName().
~System()
Pscf::Fd1d::System::~System ()
Destructor.
Definition at line 74 of file fd1d/System.cpp.
Member Function Documentation
setOptions()
void Pscf::Fd1d::System::setOptions (int argc, char ** argv)
Process command line options.
Definition at line 96 of file fd1d/System.cpp.
References Util::Log::file(), fileMaster(), Util::FileMaster::setCommandFileName(), Util::ParamComponent::setEcho(), Util::FileMaster::setInputPrefix(), Util::FileMaster::setOutputPrefix(), Util::FileMaster::setParamFileName(), and UTIL_THROW.
readParam() [1/2]
void Pscf::Fd1d::System::readParam (std::istream & in) virtual
Read input parameters (with opening and closing lines).
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 213 of file fd1d/System.cpp.
References Util::ParamComposite::className(), Util::ParamComposite::readBegin(), Util::ParamComposite::readEnd(), and readParameters().
readParam() [2/2]
void Pscf::Fd1d::System::readParam ()
Read input parameters from default param file.
Definition at line 223 of file fd1d/System.cpp.
References fileMaster(), and readParam().
Referenced by readParam().
readParameters()
void Pscf::Fd1d::System::readParameters (std::istream & in) virtual
Read input parameters (without opening and closing lines).
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 168 of file fd1d/System.cpp.
References Util::ParamComposite::className(), domain(), interaction(), mixture(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::MixtureTmpl< TP, TS >::nSolvent(), Util::Factory< Data >::readObject(), Util::Factory< Data >::readObjectOptional(), Util::ParamComposite::readParamComposite(), Pscf::Homogeneous::Mixture::setNMolecule(), Pscf::Homogeneous::Mixture::setNMonomer(), Pscf::Interaction::setNMonomer(), Pscf::Fd1d::SystemAccess::setSystem(), and UTIL_THROW.
Referenced by readParam().
writeParamNoSweep()
void Pscf::Fd1d::System::writeParamNoSweep (std::ostream & out) const
Write parameter file to an ostream, omitting the sweep block.
Definition at line 229 of file fd1d/System.cpp.
References Util::ParamComposite::writeParam().
readCommands() [1/2]
void Pscf::Fd1d::System::readCommands (std::istream & in)
Read command script.
Parameters
in command script file.
Definition at line 266 of file fd1d/System.cpp.
References cFields(), compute(), Pscf::Fd1d::HomogeneousComparison::compute(), Pscf::Fd1d::FieldIo::extend(), Util::Log::file(), fileMaster(), iterate(), Util::FileMaster::openOutputFile(), Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::FieldIo::readFields(), Pscf::Fd1d::FieldIo::remesh(), sweep(), UTIL_CHECK, wFields(), Pscf::Fd1d::FieldIo::writeBlockCFields(), Pscf::Fd1d::FieldIo::writeFields(), Util::ParamComposite::writeParam(), writeThermo(), and Pscf::Fd1d::FieldIo::writeVertexQ().
readCommands() [2/2]
void Pscf::Fd1d::System::readCommands ()
Read commands from default command file.
Definition at line 392 of file fd1d/System.cpp.
References fileMaster(), readCommands(), and UTIL_THROW.
Referenced by readCommands().
compute()
void Pscf::Fd1d::System::compute ()
Solve the modified diffusion equation once, without iteration.
This function calls the Mixture::compute() function to solve the statistical mechanics problem for a non-interacting system subjected to the currrent chemical potential fields (wFields). This requires solution of the modified diffusion equation for all polymers, computation of Boltzmann weights for all solvents, computation of molecular partition functions for all species, computation of concentration fields for blocks and solvents, and computation of overall concentrations for all monomer types. This function does not compute the canonical (Helmholtz) free energy or grand-canonical free energy (i.e., pressure). Upon return, the flag hasCFields is set true.
Definition at line 414 of file fd1d/System.cpp.
References Pscf::Fd1d::Mixture::compute(), and wFields().
Referenced by readCommands().
iterate()
int Pscf::Fd1d::System::iterate (bool isContinuation = false)
Iteratively solve a SCFT problem.
This function calls the iterator to attempt to solve the SCFT problem for the current mixture and system parameters, using the current chemical potential fields (wFields) as initial guesses.
Parameters
isContinuation true if continuation within a sweep.
Returns
returns 0 for successful convergence, 1 for failure.
Definition at line 427 of file fd1d/System.cpp.
References computeFreeEnergy(), Util::Log::file(), iterator(), Pscf::Fd1d::Iterator::solve(), and writeThermo().
Referenced by readCommands(), and Pscf::Fd1d::Sweep::solve().
sweep()
void Pscf::Fd1d::System::sweep ()
Sweep in parameter space, solving an SCF problem at each point.
This function uses a Sweep object that was initialized in the parameter file to solve the SCF problem at a sequence of points along a line in parameter space. The nature of this sequence of points is determined by implementation of a subclass of Sweep and the parameters passed to the sweep object in the parameter file. The Iterator that is initialized in the parameter file is called at each state point.
Definition at line 450 of file fd1d/System.cpp.
References Util::Log::file(), Pscf::SweepTmpl< State >::sweep(), and UTIL_CHECK.
Referenced by readCommands().
computeFreeEnergy()
void Pscf::Fd1d::System::computeFreeEnergy ()
Compute free energy density and pressure for current fields.
This function should be called after a successful call of iterator().solve(). Resulting values are returned by the freeEnergy() and pressure() accessor functions.
Definition at line 465 of file fd1d/System.cpp.
References Util::DArray< Data >::allocate(), domain(), Pscf::Interaction::fHelmholtz(), Pscf::Fd1d::Domain::innerProduct(), interaction(), Util::DArray< Data >::isAllocated(), Pscf::PolymerTmpl< Block >::length(), mixture(), Pscf::Species::mu(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::MixtureTmpl< TP, TS >::nSolvent(), Pscf::Fd1d::Domain::nx(), Pscf::Species::phi(), Pscf::MixtureTmpl< TP, TS >::polymer(), Pscf::SolventDescriptor::size(), Pscf::MixtureTmpl< TP, TS >::solvent(), and Pscf::Fd1d::Domain::spatialAverage().
Referenced by iterate(), Pscf::Fd1d::BinaryRelaxIterator::solve(), and Pscf::Fd1d::NrIterator::solve().
fHelmholtz()
double Pscf::Fd1d::System::fHelmholtz () const inline
Get precomputed Helmoltz free energy per monomer / kT.
The value retrieved by this function is computed by the computeFreeEnergy() function.
Definition at line 533 of file fd1d/System.h.
Referenced by Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::Sweep::outputSummary(), and writeThermo().
pressure()
double Pscf::Fd1d::System::pressure () const inline
Get precomputed pressure x monomer volume kT.
The value retrieved by this function is computed by the computeFreeEnergy() function.
Definition at line 539 of file fd1d/System.h.
Referenced by Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::Sweep::outputSummary(), and writeThermo().
writeThermo()
void Pscf::Fd1d::System::writeThermo (std::ostream & out)
Write thermodynamic properties to a file.
This function outputs Helmholtz free energy per monomer, pressure (in units of kT per monomer volume), and the volume fraction and chemical potential of each species.
Parameters
out output stream
Definition at line 637 of file fd1d/System.cpp.
References fHelmholtz(), mixture(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::MixtureTmpl< TP, TS >::nSolvent(), and pressure().
Referenced by iterate(), Pscf::Fd1d::Sweep::outputSolution(), and readCommands().
writeW()
void Pscf::Fd1d::System::writeW (std::string const & filename)
Write chemical potential fields in symmetrized basis format.
Parameters
filename name of output file
Definition at line 685 of file fd1d/System.cpp.
References wFields(), and Pscf::Fd1d::FieldIo::writeFields().
writeC()
void Pscf::Fd1d::System::writeC (std::string const & filename)
Write concentration fields in symmetrized basis format.
Parameters
filename name of output file
Definition at line 694 of file fd1d/System.cpp.
References cFields(), and Pscf::Fd1d::FieldIo::writeFields().
writeBlockC()
void Pscf::Fd1d::System::writeBlockC (std::string const & filename)
Write c-fields for all blocks and solvents in r-grid format.
Writes concentrations for all blocks of all polymers and all solvent species in r-grid format. Columns associated with blocks appear ordered by polymer id and then by block id, followed by solvent species ordered by solvent id.
Parameters
filename name of output file
Definition at line 704 of file fd1d/System.cpp.
References Pscf::Fd1d::FieldIo::writeBlockCFields().
wFields()
DArray< System::WField > & Pscf::Fd1d::System::wFields () inline
Get array of all chemical potential fields.
The array capacity is equal to the number of monomer types.
Definition at line 507 of file fd1d/System.h.
Referenced by compute(), readCommands(), Pscf::Fd1d::SystemAccess::wFields(), and writeW().
wField()
System::WField & Pscf::Fd1d::System::wField (int monomerId) inline
Get chemical potential field for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 514 of file fd1d/System.h.
Referenced by Pscf::Fd1d::BinaryRelaxIterator::solve(), Pscf::Fd1d::NrIterator::solve(), and Pscf::Fd1d::SystemAccess::wField().
cFields()
DArray< System::CField > & Pscf::Fd1d::System::cFields () inline
Get array of all chemical potential fields.
The array capacity is equal to the number of monomer types.
Definition at line 521 of file fd1d/System.h.
Referenced by Pscf::Fd1d::SystemAccess::cFields(), readCommands(), and writeC().
cField()
System::CField & Pscf::Fd1d::System::cField (int monomerId) inline
Get chemical potential field for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 527 of file fd1d/System.h.
Referenced by Pscf::Fd1d::SystemAccess::cField(), Pscf::Fd1d::BinaryRelaxIterator::solve(), and Pscf::Fd1d::NrIterator::solve().
mixture() [1/2]
Mixture & Pscf::Fd1d::System::mixture () inline
Get Mixture by reference.
Definition at line 448 of file fd1d/System.h.
Referenced by computeFreeEnergy(), Pscf::Fd1d::SystemAccess::mixture(), readParameters(), Pscf::Fd1d::NrIterator::solve(), and writeThermo().
mixture() [2/2]
Mixture const & Pscf::Fd1d::System::mixture () const inline
Get Mixture by reference.
Definition at line 454 of file fd1d/System.h.
interaction() [1/2]
Interaction & Pscf::Fd1d::System::interaction () inline
Get interaction (i.e., excess free energy) by reference.
Definition at line 460 of file fd1d/System.h.
References UTIL_ASSERT.
Referenced by computeFreeEnergy(), Pscf::Fd1d::SystemAccess::interaction(), and readParameters().
interaction() [2/2]
Interaction const & Pscf::Fd1d::System::interaction () const inline
Get interaction (i.e., excess free energy) by const reference.
Definition at line 469 of file fd1d/System.h.
References UTIL_ASSERT.
domain()
Domain & Pscf::Fd1d::System::domain () inline
Get spatial domain (including grid info) by reference.
Definition at line 478 of file fd1d/System.h.
Referenced by computeFreeEnergy(), Pscf::Fd1d::SystemAccess::domain(), readParameters(), and Pscf::Fd1d::Sweep::Sweep().
iterator()
Iterator & Pscf::Fd1d::System::iterator () inline
Get the Iterator by reference.
Definition at line 491 of file fd1d/System.h.
References UTIL_ASSERT.
Referenced by iterate().
homogeneous()
Homogeneous::Mixture & Pscf::Fd1d::System::homogeneous () inline
Get homogeneous mixture (for reference calculations).
Definition at line 485 of file fd1d/System.h.
Referenced by Pscf::Fd1d::SystemAccess::homogeneous(), and Pscf::Fd1d::Sweep::outputSummary().
fileMaster()
FileMaster & Pscf::Fd1d::System::fileMaster () inline
Get FileMaster by reference.
Definition at line 500 of file fd1d/System.h.
Referenced by Pscf::Fd1d::SystemAccess::fileMaster(), readCommands(), readParam(), setOptions(), and Pscf::Fd1d::Sweep::Sweep().
The documentation for this class was generated from the following files:
fd1d/System.h
fd1d/System.cpp