PSCF: Pscf::Edge Class Reference
Pscf::Edge Class Reference
Pscf namespace » Pscf Common » Chemical Structure
Descriptor for a block within an acyclic block polymer.
#include <Edge.h>
Public Member Functions
Edge ()
Constructor.
virtual ~Edge ()
Destructor.
template<class Archive >
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
Setters
void setId (int id)
Set the id for this block.
void setMonomerId (int monomerId)
Set the monomer type id.
void setVertexIds (int vertexId0, int vertexId1)
Set indices of associated vertices.
void setVertexOwnership (bool own0, bool own1)
Set ownership of associated vertices (only valid for bead model).
virtual void setNBead (int nBead)
Set the number of beads in this block (only valid for bead model).
virtual void setLength (double length)
Set the length of this block (only valid for thread model).
void setPolymerType (PolymerType::Enum type)
Set the polymer type (branched or linear).
Accessors (getters)
int id () const
Get the id of this block.
int monomerId () const
Get the monomer type id.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
bool ownsVertex (int i) const
Does this block own an associated vertex (bead model).
double nBead () const
Get the number of beads in this block, in the bead model.
double length () const
Get the length of this block, in the thread model.
PolymerType::Enum polymerType () const
Get the type of the parent polymer (branched or linear).
std::istream & operator>> (std::istream &in, Edge &block)
Input stream extractor (>>) for a Edge.
std::ostream & operator<< (std::ostream &out, const Edge &block)
Output stream inserter (<<) for a Edge.
Detailed Description
Descriptor for a block within an acyclic block polymer.
An Edge has:
a monomer type id
a length (thread model) or number of beads (bead model)
a block id (unique with the polymer)
ids of the two vertices at which it terminates
Edge is a base class for the BlockTmpl class template, which is a a base class for a class named Block in each implementation-level sub-namespace of Pscf (i.e., in R1d, Rpc, or Rpg).
An Edge is a descriptor for a block within a block polymer, but does not provide functions or data structure needed to solve the modified diffusion equation (MDE). The Block class defined in each implementation-level namespace is designed to be used as an MDE solver as well as a descriptor.
An Edge can store either a value for length (the contour length of the block) when PolymerModel::isThread(), or a value for nBead (the number of beads in the block) when PolymerModel::isBead(). In the case of the bead model, it also stores a pair of boolean flags to indicate whether the block owns either or both of the associated vertices. It is an error to try to set or get a value for nBead or the vertex ownership flags when the thread model is in use, because these variables are only meaningful for a bead model. Similarly, it is an error to get or set a value for the block length when a bead model is in use, because the length variable is only meaningful in the context of a thread model.
Block objects associated with a polymer are normally stored in an array that is a private member of the Pscf::PolymerTmpl class template. The block id for each edge be set to the element index of the Block within that array.
Parameter File Format
Definition at line 62 of file Edge.h.
Constructor & Destructor Documentation
Edge()
Pscf::Edge::Edge ()
Constructor.
Definition at line 16 of file Edge.cpp.
~Edge()
Pscf::Edge::~Edge () virtual
Destructor.
Definition at line 33 of file Edge.cpp.
Member Function Documentation
serialize()
template<class Archive > void Pscf::Edge::serialize (Archive & ar, unsigned int versionId)
Serialize to/from archive.
Parameters
ar input or output Archive
versionId archive format version index
Definition at line 376 of file Edge.h.
setId()
void Pscf::Edge::setId (int id)
Set the id for this block.
Parameters
id integer index for this block
Definition at line 39 of file Edge.cpp.
References id().
Referenced by Pscf::PolymerSpecies::readParameters().
setMonomerId()
void Pscf::Edge::setMonomerId (int monomerId)
Set the monomer type id.
Parameters
monomerId integer id of monomer type
Definition at line 45 of file Edge.cpp.
References monomerId().
setVertexIds()
void Pscf::Edge::setVertexIds (int vertexId0, int vertexId1)
Set indices of associated vertices.
Parameters
vertexId0 integer id of vertex 0
vertexId1 integer id of vertex 1
Definition at line 51 of file Edge.cpp.
Referenced by Pscf::PolymerSpecies::readParameters().
setVertexOwnership()
void Pscf::Edge::setVertexOwnership (bool own0, bool own1)
Set ownership of associated vertices (only valid for bead model).
The concept of "ownership" of vertex beads is only meaningful in the context of a bead model, in which we require that each vertex be owned by one of the associated blocks. The monomer type of the vertex is the same as the type of the block that owns it.
Precondition: PolymerModel::isBead()
Parameters
own0 Does this block own vertex 0 ?
own1 Does this block own vertex 1 ?
Definition at line 60 of file Edge.cpp.
Referenced by Pscf::PolymerSpecies::readParameters().
setNBead()
void Pscf::Edge::setNBead (int nBead) virtual
Set the number of beads in this block (only valid for bead model).
Precondition: PolymerModel::isBead()
Parameters
nBead number of beads (bead model)
Definition at line 69 of file Edge.cpp.
References Pscf::PolymerModel::isBead(), nBead(), and UTIL_CHECK.
setLength()
void Pscf::Edge::setLength (double length) virtual
Set the length of this block (only valid for thread model).
In the continuous thread model, the length of a block is given by the ratio of block steric volume / monomer reference volume.
Precondition: PolymerModel::isThread()
Parameters
length block length (thread model).
Reimplemented in Pscf::R1d::Block, Pscf::Rpc::Block< D >, and Pscf::Rpg::Block< D >.
Definition at line 78 of file Edge.cpp.
References Pscf::PolymerModel::isThread(), length(), and UTIL_CHECK.
Referenced by Pscf::R1d::Block::setLength(), Pscf::Rpc::Block< D >::setLength(), and Pscf::Rpg::Block< D >::setLength().
setPolymerType()
void Pscf::Edge::setPolymerType (PolymerType::Enum type)
Set the polymer type (branched or linear).
By convention, if the polymer type of a block with index id is PolymerType::Linear, then vertexId(0) = id and vertexId(1) = id + 1. In the case of a bead model, a standard convention also exists for ownership of the two attached vertices. The stream insertion and extraction operators for an Edge can thus use a shorter string representation for linear polymers in which vertex ids and (when relevant) owhership flags are omitted.
Parameters
type type of polymer (branched or linear)
Definition at line 87 of file Edge.cpp.
Referenced by Pscf::PolymerSpecies::readParameters().
id()
int Pscf::Edge::id () const inline
Get the id of this block.
Definition at line 318 of file Edge.h.
Referenced by Pscf::Vertex::addEdge(), and setId().
monomerId()
int Pscf::Edge::monomerId () const inline
Get the monomer type id.
Definition at line 324 of file Edge.h.
Referenced by setMonomerId().
vertexIds()
const Pair< int > & Pscf::Edge::vertexIds () const inline
Get the pair of associated vertex ids.
Definition at line 330 of file Edge.h.
vertexId()
int Pscf::Edge::vertexId (int i) const inline
Get id of an associated vertex.
Parameters
i index of vertex (0 or 1)
Definition at line 336 of file Edge.h.
Referenced by Pscf::Vertex::addEdge(), Pscf::EdgeIterator::begin(), Pscf::PolymerSpecies::isValid(), Pscf::PolymerSpecies::makePaths(), Pscf::PolymerSpecies::makePlan(), Pscf::EdgeIterator::operator++(), Pscf::VertexIterator::operator++(), and Pscf::PolymerSpecies::readParameters().
ownsVertex()
bool Pscf::Edge::ownsVertex (int i) const inline
Does this block own an associated vertex (bead model).
Precondition: PolymerModel::isBead()
Parameters
i index of vertex (0 or 1)
Definition at line 342 of file Edge.h.
References Pscf::PolymerModel::isBead(), and UTIL_CHECK.
nBead()
double Pscf::Edge::nBead () const inline
Get the number of beads in this block, in the bead model.
Precondition: PolymerModel::isBead()
Definition at line 351 of file Edge.h.
References Pscf::PolymerModel::isBead(), and UTIL_CHECK.
Referenced by Pscf::PolymerSpecies::nBead(), and setNBead().
length()
double Pscf::Edge::length () const inline
Get the length of this block, in the thread model.
Precondition: PolymerModel::isThread()
Definition at line 360 of file Edge.h.
References Pscf::PolymerModel::isThread(), and UTIL_CHECK.
Referenced by Pscf::PolymerSpecies::length(), Pscf::R1d::Block::setDiscretization(), setLength(), Pscf::R1d::Block::setLength(), and Pscf::R1d::Block::setupSolver().
polymerType()
PolymerType::Enum Pscf::Edge::polymerType () const inline
Get the type of the parent polymer (branched or linear).
Definition at line 369 of file Edge.h.
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & in, Edge & block) friend
Input stream extractor (>>) for a Edge.
The polymerType must be set before an Edge can be read from a stream. The block id must be set explicitly by calling setId, and are not read from an istream. Vertex id values for blocks in a linear polymer must be set explicitly by calling setVertexIds with consecutive values, as done in the function Pscf::PolymerTmpl::readParameters.
Different text representations are used for bead and thread models, and for linear and branched polymers:
Thread model:
In the thread model, if PolymerModel::isThread(), the text representation of an Edge for a branched polymer is:
monomerId length vertexId(0) vertexid(1)
Here, length is a floating point number. For a linear polymer in the thread model, the vertex ids are omitted, because the vertex ids for block id of linear polymer must be equal to id and id + 1.
Bead model:
In the bead model, if PolymerModel::isBead(), the text representation for a branched polymer is:
monomerId nBead vertexId(0) vertexid(1) ownsVertex(0) ownsVertex(1)
Here, nBead is the integer number of beads in the chain, while ownsVertex(0) and ownsVertex(1) are boolean variables (0 or 1) that indicate whether the block owns vertex 0 and 1, respecively. The corresponding text representation for a bead-spring linear chain omits both the vertex ids and the ownsVertex flags, because values of these are set by convention. In a linear bead-spring polymer, vertex ids for block number id are id and id+1, ownsVertex(1) == 1, while ownsVertex(0) == 1 for the first block (id = 0) and ownsVertex(0) = 0 for all other blocks (id > 0).
Parameters
in input stream
block Edge to be read from stream
Returns
modified input stream
Definition at line 93 of file Edge.cpp.
operator<<
std::ostream & operator<< (std::ostream & out, const Edge & block) friend
Output stream inserter (<<) for a Edge.
Different text representations are used for linear and branched polymers, as discussed in documentation for the stream extractor (>>) operator. Vertex ids are output only for blocks of branched polymers.
Parameters
out output stream
block Edge to be written to stream
Returns
modified output stream
Definition at line 122 of file Edge.cpp.
The documentation for this class was generated from the following files:
Edge.h
Edge.cpp