PSCF: Pscf::Monomer Class Reference
Pscf::Monomer Class Reference
Pscf namespace » Pscf Common » Chemical Structure
Descriptor for a monomer type.
#include <Monomer.h>
Public Member Functions
Monomer ()
Constructor.
void setId (int id)
Set the integer index for this monomer type.
void setKuhn (double kuhn)
Set statistical segment length.
int id () const
Unique integer index for monomer type.
double kuhn () const
Statistical segment length (random walk step size).
template<class Archive>
void serialize (Archive ar, const unsigned int version)
Serialize to or from an archive.
Friends
std::istream & operator>> (std::istream &in, Monomer &monomer)
Stream extractor (>>) for a Monomer.
std::ostream & operator<< (std::ostream &out, const Monomer &monomer)
Stream inserter (<<) for a Monomer.
Detailed Description
Descriptor for a monomer type.
A Monomer has:
a unique integer monomer id
a statistical segment length
Iostream extractor (>>) and inserter (<<) operators are defined for a Monomer, allowing the description of a monomer to be read from or written to file like a primitive variable. The text representation contains only the value of the kuhn (statistical segment) length, as described here.
Data for all monomers in a system is normally read from a parameter file into an array-valued parameter named "monomers" in which each element is a Monomer object. The id of each Monomer should be set to its element index within this array.
Definition at line 38 of file Monomer.h.
Constructor & Destructor Documentation
Monomer()
Pscf::Monomer::Monomer ()
Constructor.
Definition at line 13 of file Monomer.cpp.
Referenced by operator<<, and operator>>.
Member Function Documentation
setId()
void Pscf::Monomer::setId (int id)
Set the integer index for this monomer type.
Parameters
id new value for index
Definition at line 18 of file Monomer.cpp.
References id().
setKuhn()
void Pscf::Monomer::setKuhn (double kuhn) inline
Set statistical segment length.
Parameters
kuhn value of statistical segment length
Definition at line 139 of file Monomer.h.
References kuhn().
Referenced by Pscf::R1d::Mixture::setKuhn().
id()
int Pscf::Monomer::id () const inline
Unique integer index for monomer type.
Definition at line 125 of file Monomer.h.
Referenced by setId().
kuhn()
double Pscf::Monomer::kuhn () const inline
Statistical segment length (random walk step size).
Definition at line 131 of file Monomer.h.
Referenced by Pscf::Rpc::IntraCorrelation< D >::computeIntraCorrelations(), Pscf::Rpg::IntraCorrelation< D >::computeIntraCorrelations(), and setKuhn().
serialize()
template<class Archive> void Pscf::Monomer::serialize (Archive ar, const unsigned int version)
Serialize to or from an archive.
Parameters
ar Archive object
version archive format version index
Definition at line 146 of file Monomer.h.
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & in, Monomer & monomer) friend
Stream extractor (>>) for a Monomer.
The text representation is given by the value of the kuhn data member (i.e., the monomer statistical segment length). The type id is thus not read from a stream, and so must be set explicitly with setId.
Parameters
in input stream
monomer Monomer to be read from stream
Returns
modified input stream
Definition at line 24 of file Monomer.cpp.
References Monomer().
operator<<
std::ostream & operator<< (std::ostream & out, const Monomer & monomer) friend
Stream inserter (<<) for a Monomer.
Parameters
out output stream
monomer Monomer to be written to stream
Returns
modified output stream
Definition at line 34 of file Monomer.cpp.
References Monomer().
The documentation for this class was generated from the following files:
Monomer.h
Monomer.cpp