PSCF: pscfpp.text.Wrapper Class Reference
pscfpp.text.Wrapper Class Reference
Class to wrap line breaks.
Public Member Functions
def __init__ (self, eol='\n', nIndent=0)
Constructor.
def clear (self)
Clear mutable attributes (column and text).
def append (self, string)
Add contents of string to wrapped text.
def __str__ (self)
Return string containing wrapped text (self.text).
def __repr__ (self)
Return string containing wrapped text (self.text).
Detailed Description
Class to wrap line breaks.
Definition at line 12 of file text.py.
Constructor & Destructor Documentation
__init__()
def pscfpp.text.Wrapper.__init__ (self, eol = '\n', nIndent = 0)
Constructor.
Data attributes:
eol : end-of-line character
nIndent : number of spaces preceding each line
column : current column index (cursor)
limit : maximum number of columns (78 by default)
text : string containing resuling wrapped text
Parameters
eol end-of-line character
nIndent number of space preceding each line
Definition at line 28 of file text.py.
References pscfpp.text.Wrapper.column, pscfpp.text.Wrapper.eol, pscfpp.text.Wrapper.limit, pscfpp.text.Wrapper.nIndent, and pscfpp.text.Wrapper.text.
Member Function Documentation
clear()
def pscfpp.text.Wrapper.clear (self)
Clear mutable attributes (column and text).
Definition at line 38 of file text.py.
References pscfpp.text.Wrapper.column, and pscfpp.text.Wrapper.text.
append()
def pscfpp.text.Wrapper.append (self, string)
Add contents of string to wrapped text.
Parameters
string input string
Definition at line 47 of file text.py.
References pscfpp.text.Wrapper.column, pscfpp.text.Wrapper.eol, pscfpp.text.Wrapper.limit, pscfpp.text.Wrapper.nIndent, and pscfpp.text.Wrapper.text.
__str__()
def pscfpp.text.Wrapper.__str__ (self)
Return string containing wrapped text (self.text).
Definition at line 64 of file text.py.
References pscfpp.text.Wrapper.text.
Referenced by pscfpp.field.Field.write(), pscfpp.output.Thermo.write(), and pscfpp.output.State.write().
__repr__()
def pscfpp.text.Wrapper.__repr__ (self)
Return string containing wrapped text (self.text).
Definition at line 70 of file text.py.
References pscfpp.text.Wrapper.text.
The documentation for this class was generated from the following file:
text.py