PSCF: Util::Memory Class Reference
Util::Memory Class Reference
Util namespace » Miscellaneous Utilities
Provides method to allocate array.
#include <Memory.h>
Static Public Member Functions
template<typename Data>
static void allocate (Data *&ptr, size_t size)
Allocate a C++ array.
template<typename Data>
static void deallocate (Data *&ptr, size_t size)
Deallocate a C++ array.
template<typename Data>
static void reallocate (Data *&ptr, size_t oldSize, size_t newSize)
Reallocate a C++ array.
static int nAllocate ()
Return number of times allocate() was called.
static int nDeallocate ()
Return number of times deallocate() was called.
static int total ()
Return total amount of memory currently allocated.
static int max ()
Return the maximum amount of allocated heap memory thus far.
static void initStatic ()
Call this just to guarantee initialization of static memory.
Detailed Description
Provides method to allocate array.
The Memory::allocate() method invokes the new operator within a try catch block, and keeps track of the total memory allocated.
Definition at line 28 of file Memory.h.
Member Function Documentation
allocate()
template<typename Data> void Util::Memory::allocate (Data *& ptr, size_t size) static
Allocate a C++ array.
Uses new to allocates a Data array of size elements, assigns ptr the address of the first element.
Parameters
ptr reference to pointer (output)
size number of elements
Definition at line 132 of file Memory.h.
References UTIL_THROW.
Referenced by Util::ArraySet< Data >::allocate(), Util::ArrayStack< Data >::allocate(), Util::DArray< Data >::allocate(), Util::DMatrix< Data >::allocate(), Util::DPArray< Data >::allocate(), Util::DRaggedMatrix< Data >::allocate(), Util::DSArray< Data >::allocate(), Util::GridArray< Data >::allocate(), Util::ListArray< Data >::allocate(), Util::MemoryIArchive::allocate(), Util::MemoryOArchive::allocate(), Util::RingBuffer< Data >::allocate(), Util::GArray< Data >::append(), Util::GPArray< Data >::append(), Util::DArray< Data >::DArray(), Util::DSArray< Data >::DSArray(), Util::GArray< Data >::GArray(), Util::GPArray< Data >::GPArray(), Util::GStack< Data >::GStack(), Util::RingBuffer< Data >::operator=(), Util::GStack< Data >::push(), Util::DArray< Data >::reallocate(), reallocate(), Util::GArray< Data >::reserve(), Util::GPArray< Data >::reserve(), Util::GStack< Data >::reserve(), and Util::GArray< Data >::resize().
deallocate()
template<typename Data> void Util::Memory::deallocate (Data *& ptr, size_t size) static
Deallocate a C++ array.
Uses free to deallocate a Data array of size elements.
Parameters
ptr reference to pointer (intput, ptr = 0 on output)
size number of elements in existing array
Definition at line 152 of file Memory.h.
References UTIL_CHECK.
Referenced by Util::GArray< Data >::append(), Util::GPArray< Data >::append(), Util::DArray< Data >::deallocate(), Util::DMatrix< Data >::deallocate(), Util::GArray< Data >::deallocate(), Util::GPArray< Data >::deallocate(), Util::GStack< Data >::deallocate(), Util::GStack< Data >::push(), reallocate(), Util::GArray< Data >::reserve(), Util::GPArray< Data >::reserve(), Util::GStack< Data >::reserve(), Util::GArray< Data >::resize(), Util::ArraySet< Data >::~ArraySet(), Util::ArrayStack< Data >::~ArrayStack(), Util::DArray< Data >::~DArray(), Util::DMatrix< Data >::~DMatrix(), Util::DPArray< Data >::~DPArray(), Util::DRaggedMatrix< Data >::~DRaggedMatrix(), Util::DSArray< Data >::~DSArray(), Util::GArray< Data >::~GArray(), Util::GPArray< Data >::~GPArray(), Util::GridArray< Data >::~GridArray(), Util::GStack< Data >::~GStack(), Util::ListArray< Data >::~ListArray(), Util::MemoryIArchive::~MemoryIArchive(), Util::MemoryOArchive::~MemoryOArchive(), and Util::RingBuffer< Data >::~RingBuffer().
reallocate()
template<typename Data> void Util::Memory::reallocate (Data *& ptr, size_t oldSize, size_t newSize) static
Reallocate a C++ array.
This function calls allocate to allocate a new array, copies all existing elements and deallocates old and calls deallocate to free the old array. On outputs, ptr is the address of the new array.
Precondition: On input, newSize > oldSize.
Parameters
ptr reference to pointer (input/output)
oldSize number of elements in existing array
newSize number of elements in new array
Definition at line 168 of file Memory.h.
References allocate(), deallocate(), and UTIL_CHECK.
Referenced by Util::DArray< Data >::reallocate().
nAllocate()
int Util::Memory::nAllocate () static
Return number of times allocate() was called.
Each call to reallocate() also increments nAllocate(), because allocate() is called internally.
Definition at line 34 of file Memory.cpp.
nDeallocate()
int Util::Memory::nDeallocate () static
Return number of times deallocate() was called.
Each call to reallocate() also increments nDeallocate(), because deallocate() is called internally.
Definition at line 40 of file Memory.cpp.
total()
int Util::Memory::total () static
Return total amount of memory currently allocated.
Definition at line 46 of file Memory.cpp.
max()
int Util::Memory::max () static
Return the maximum amount of allocated heap memory thus far.
This function returns the temporal maximum of total().
Definition at line 52 of file Memory.cpp.
initStatic()
void Util::Memory::initStatic () static
Call this just to guarantee initialization of static memory.
Definition at line 28 of file Memory.cpp.
Referenced by Util::initStatic().
The documentation for this class was generated from the following files:
Memory.h
Memory.cpp