PSCF: Pscf::Mesh< D > Class Template Reference
Pscf::Mesh< D > Class Template Reference
Pscf namespace » Pscf Common » Spatial Mesh
Description of a regular grid of points in a periodic domain.
#include <Mesh.h>
Public Member Functions
Mesh ()
Default constructor.
Mesh (Mesh< D > const &other)
Copy constructor.
Mesh (IntVec< D > const &dimensions)
Constructor from grid dimensions.
Mesh< D > & operator= (Mesh< D > const &other)
Assignment operator.
void setDimensions (IntVec< D > const &dimensions)
Set the grid dimensions for an existing mesh.
IntVec< D > dimensions () const
Get an IntVec<D> of the grid dimensions.
int dimension (int i) const
Get grid dimension along Cartesian direction i.
int size () const
Get total number of grid points.
IntVec< D > position (int rank) const
Get the position IntVec<D> of a grid point with a specified rank.
int rank (IntVec< D > const &position) const
Get the rank of a grid point with specified position.
bool isInMesh (int coordinate, int i) const
Is this coordinate in range?
bool isInMesh (IntVec< D > const &position) const
Is this IntVec<D> grid position within the grid?
int shift (int &coordinate, int i) const
Shift a periodic coordinate into range.
IntVec< D > shift (IntVec< D > &position) const
Shift a periodic position into primary grid.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Friends
std::istream & operator>> (std::istream &, Mesh< D > &)
Input stream extractor for reading a Mesh<D> object.
std::ostream & operator<< (std::ostream &, Mesh< D > const &)
Output stream inserter for writing a Mesh<D> object.
Detailed Description
template<int D>
class Pscf::Mesh< D >
Description of a regular grid of points in a periodic domain.
The coordinates of a point on a grid form an IntVec<D>, referred to here as a grid position. Each element of a grid position must lie in the range 0 <= position[i] < dimension(i), where i indexes a Cartesian axis, and dimension(i) is the dimension of the grid along axis i.
Each grid position is also assigned a non-negative integer rank. Mesh position ranks are ordered sequentially like elements in a multi-dimensional C array, with the last coordinate being the most rapidly varying.
Definition at line 60 of file Mesh.h.
Constructor & Destructor Documentation
Mesh() [1/3]
template<int D> Pscf::Mesh< D >::Mesh
Default constructor.
Grid dimensions and size are initialized to zero. All functions that set the dimensions and size after construction require that all dimensions are positive, yielding a positive size.
Definition at line 21 of file Mesh.tpp.
Mesh() [2/3]
template<int D> Pscf::Mesh< D >::Mesh (Mesh< D > const & other)
Copy constructor.
Parameters
other Mesh<D> object being copied.
Definition at line 29 of file Mesh.tpp.
Mesh() [3/3]
template<int D> Pscf::Mesh< D >::Mesh (IntVec< D > const & dimensions)
Constructor from grid dimensions.
Parameters
dimensions IntVec<D> of grid dimensions
Definition at line 37 of file Mesh.tpp.
References Pscf::Mesh< D >::dimensions(), and Pscf::Mesh< D >::setDimensions().
Member Function Documentation
operator=()
template<int D> Mesh< D > & Pscf::Mesh< D >::operator= (Mesh< D > const & other)
Assignment operator.
Parameters
other Mesh<D> object being copied.
Definition at line 45 of file Mesh.tpp.
setDimensions()
template<int D> void Pscf::Mesh< D >::setDimensions (IntVec< D > const & dimensions)
Set the grid dimensions for an existing mesh.
Parameters
dimensions IntVec<D> of grid dimensions.
Definition at line 53 of file Mesh.tpp.
References UTIL_THROW.
Referenced by Pscf::Mesh< D >::Mesh().
dimensions()
template<int D> IntVec< D > Pscf::Mesh< D >::dimensions inline
Get an IntVec<D> of the grid dimensions.
Definition at line 217 of file Mesh.h.
Referenced by Pscf::Pspc::Propagator< D >::allocate(), Pscf::Pspg::WaveList< D >::allocate(), Pscf::Pspg::WaveList< D >::computeMinimumImages(), Pscf::Basis< D >::makeBasis(), Pscf::Mesh< D >::Mesh(), Pscf::Pspc::Block< D >::setDiscretization(), Pscf::Pspg::Block< D >::setDiscretization(), Pscf::Pspc::Solvent< D >::setDiscretization(), and Pscf::Pspg::Solvent< D >::setDiscretization().
dimension()
template<int D> int Pscf::Mesh< D >::dimension (int i) const inline
Get grid dimension along Cartesian direction i.
Parameters
i index of Cartesian direction 0 <=i < Util::Dimension
Definition at line 221 of file Mesh.h.
References Util::Dimension.
Referenced by Pscf::Pspg::WaveList< D >::allocate(), and Pscf::Pspg::WaveList< D >::computeMinimumImages().
size()
template<int D> int Pscf::Mesh< D >::size inline
Get total number of grid points.
Value size() == 0 will be obtained iff the mesh was default constructed and has not yet been given meaningful initial values.
Definition at line 229 of file Mesh.h.
Referenced by Pscf::Pspg::Propagator< D >::allocate(), Pscf::Pspg::WaveList< D >::allocate(), Pscf::Pspg::WaveList< D >::computeMinimumImages(), Pscf::Pspg::FieldIo< D >::convertBasisToKGrid(), Pscf::Pspc::FieldIo< D >::convertBasisToKGrid(), Pscf::Basis< D >::makeBasis(), Pscf::Pspc::Block< D >::setDiscretization(), and Pscf::Pspg::Block< D >::setDiscretization().
position()
template<int D> IntVec< D > Pscf::Mesh< D >::position (int rank) const
Get the position IntVec<D> of a grid point with a specified rank.
Parameters
rank integer rank of a grid point.
Returns
IntVec<D> containing coordinates of specified point.
Definition at line 89 of file Mesh.tpp.
rank()
template<int D> int Pscf::Mesh< D >::rank (IntVec< D > const & position) const
Get the rank of a grid point with specified position.
Parameters
position integer position of a grid point
Returns
integer rank of specified grid point
Definition at line 72 of file Mesh.tpp.
Referenced by Pscf::Pspg::WaveList< D >::computeMinimumImages(), Pscf::Pspg::FieldIo< D >::convertBasisToKGrid(), Pscf::Pspc::FieldIo< D >::convertBasisToKGrid(), Pscf::Pspg::FieldIo< D >::convertKGridToBasis(), Pscf::Pspc::FieldIo< D >::convertKGridToBasis(), and Pscf::Pspc::FieldIo< D >::hasSymmetry().
isInMesh() [1/2]
template<int D> bool Pscf::Mesh< D >::isInMesh (int coordinate, int i) const
Is this coordinate in range?
Parameters
coordinate coordinate value for direction i
i index for Cartesian direction
Returns
true iff 0 <= coordinate < dimension(i).
Definition at line 105 of file Mesh.tpp.
isInMesh() [2/2]
template<int D> bool Pscf::Mesh< D >::isInMesh (IntVec< D > const & position) const
Is this IntVec<D> grid position within the grid?
Returns true iff 0 <= coordinate[i] < dimension(i) for all i.
Parameters
position grid point position
Returns
true iff 0 <= coordinate[i] < dimension(i) for all i.
Definition at line 117 of file Mesh.tpp.
shift() [1/2]
template<int D> int Pscf::Mesh< D >::shift (int & coordinate, int i) const
Shift a periodic coordinate into range.
Upon return, the coordinate will be shifted to lie within the range 0 <= coordinate < dimension(i) by subtracting an integer multiple of dimension(i), giving coordinate - shift*dimension(i). The return value is the required integer ‘shift’.
Parameters
coordinate coordinate in Cartesian direction i.
i index of Cartesian direction, i >= 0.
Returns
multiple of dimension(i) subtracted from input value.
Definition at line 131 of file Mesh.tpp.
Referenced by Pscf::Pspg::WaveList< D >::computeMinimumImages().
shift() [2/2]
template<int D> IntVec< D > Pscf::Mesh< D >::shift (IntVec< D > & position) const
Shift a periodic position into primary grid.
Upon return, each element of the parameter position is shifted to lie within the range 0 <= position[i] < dimension(i) by adding or subtracting an integer multiple of dimension(i). The IntVec<D> of shift values is returned.
Parameters
position IntVec<D> position within a grid.
Returns
IntVec<D> of integer shifts.
Definition at line 145 of file Mesh.tpp.
serialize()
template<int D> template<class Archive > void Pscf::Mesh< D >::serialize (Archive & ar, const unsigned int version)
Serialize to/from an archive.
Parameters
ar archive
version archive version id
Definition at line 237 of file Mesh.h.
Friends And Related Function Documentation
operator>>
template<int D> std::istream & operator>> (std::istream & in, Mesh< D > & mesh) friend
Input stream extractor for reading a Mesh<D> object.
Parameters
in input stream
mesh Mesh<D> object to be read
Returns
modified input stream
Definition at line 245 of file Mesh.h.
operator<<
template<int D> std::ostream & operator<< (std::ostream & out, Mesh< D > const & mesh) friend
Output stream inserter for writing a Mesh<D> object.
Parameters
out output stream
mesh Mesh<D> to be written
Returns
modified output stream
Definition at line 257 of file Mesh.h.
The documentation for this class was generated from the following files:
Mesh.h
Mesh.tpp