PSCF: Util::RingBuffer< Data > Class Template Reference
Util::RingBuffer< Data > Class Template Reference
Util namespace » Container Templates » Object Arrays
Class for storing history of previous values in an array.
#include <RingBuffer.h>
Public Member Functions
RingBuffer ()
Contructor.
RingBuffer (RingBuffer< Data > const &other)
Copy contructor.
RingBuffer & operator= (RingBuffer< Data > const &other)
Assignment.
virtual ~RingBuffer ()
Destructor.
void allocate (int capacity)
Allocate a new empty buffer.
void clear ()
Set previously allocated buffer to empty state.
void append (Data const &value)
Add a new value to the buffer.
void advance ()
Advances the pointer to an added element without assigning a value.
int size () const
Return number of values currently in the buffer.
int capacity () const
Return the capacity of the buffer.
bool isAllocated () const
Return true if the RingBuffer has been allocated, false otherwise.
bool isFull () const
Return true if full (if size == capacity), false otherwise.
Data const & operator[] (int offset) const
Retrieve a const value, a specified number of time steps ago.
Data & operator[] (int offset)
Retrieve a value, a specified number of time steps ago.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize a RingBuffer to/from an Archive.
Detailed Description
template<class Data>
class Util::RingBuffer< Data >
Class for storing history of previous values in an array.
Data is stored in a circular buffer, in which, once the array is full, the newest data value overwrites the oldest.
Definition at line 26 of file RingBuffer.h.
Constructor & Destructor Documentation
RingBuffer() [1/2]
template<class Data> Util::RingBuffer< Data >::RingBuffer ()
Contructor.
Definition at line 169 of file RingBuffer.h.
Referenced by operator=(), operator[](), operator[](), and RingBuffer().
RingBuffer() [2/2]
template<class Data> Util::RingBuffer< Data >::RingBuffer (RingBuffer< Data > const & other)
Copy contructor.
Parameters
other object to be copied.
Definition at line 184 of file RingBuffer.h.
References RingBuffer().
~RingBuffer()
template<class Data> Util::RingBuffer< Data >::~RingBuffer () virtual
Destructor.
Definition at line 248 of file RingBuffer.h.
References Util::Memory::deallocate(), and ~RingBuffer().
Referenced by ~RingBuffer().
Member Function Documentation
operator=()
template<class Data> RingBuffer< Data > & Util::RingBuffer< Data >::operator= (RingBuffer< Data > const & other)
Assignment.
Parameters
other object to be assigned.
Definition at line 211 of file RingBuffer.h.
References Util::Memory::allocate(), isAllocated(), RingBuffer(), and UTIL_THROW.
allocate()
template<class Data> void Util::RingBuffer< Data >::allocate (int capacity)
Allocate a new empty buffer.
Allocate a new array containing capacity elements.
Throw an Exception if this RingBuffer has already been allocated - a RingBuffer can only be allocated once.
Parameters
capacity number of elements to allocate.
Definition at line 257 of file RingBuffer.h.
References Util::Memory::allocate(), allocate(), capacity(), and UTIL_THROW.
Referenced by allocate(), and serialize().
clear()
template<class Data> void Util::RingBuffer< Data >::clear () inline
Set previously allocated buffer to empty state.
Definition at line 274 of file RingBuffer.h.
References clear().
Referenced by clear().
append()
template<class Data> void Util::RingBuffer< Data >::append (Data const & value) inline
Add a new value to the buffer.
This function updates the pointer to the most recent element and then uses an assignment (=) operator to assign argument "value" to this element of the underlying array.
Parameters
value new value to be added
Definition at line 285 of file RingBuffer.h.
References append().
Referenced by append().
advance()
template<class Data> void Util::RingBuffer< Data >::advance () inline
Advances the pointer to an added element without assigning a value.
This function advances the pointer that identifies the the newest element but does not assign a value to that element. Immediately after applying this function to a RingBuffer<T> named buffer, the value of the most recently added element, buffer[0], is undefined. A call to RingBuffer<T>::advance must be thus always be followed by code that assigns this value. The simplest usage for a Ringbuffer<T> named buffer would thus be:
buffer.advance();
buffer[0] = value;
where "value" is an object of type T. This combination is equivalent to buffer.append(value).
Rationale: This is designed as an alternative to the append memmber function for cases in which type T is a large object. This avoids the need to construct and assign a value to a T object outside the buffer which must then be re-assigned to an array element inside the RingBuffer<T>::append function.
Definition at line 306 of file RingBuffer.h.
References advance().
Referenced by advance().
size()
template<class Data> int Util::RingBuffer< Data >::size () const inline
Return number of values currently in the buffer.
Definition at line 325 of file RingBuffer.h.
References size().
Referenced by size().
capacity()
template<class Data> int Util::RingBuffer< Data >::capacity () const inline
Return the capacity of the buffer.
Definition at line 333 of file RingBuffer.h.
References capacity().
Referenced by allocate(), capacity(), and serialize().
isAllocated()
template<class Data> bool Util::RingBuffer< Data >::isAllocated () const inline
Return true if the RingBuffer has been allocated, false otherwise.
Definition at line 341 of file RingBuffer.h.
References isAllocated().
Referenced by isAllocated(), operator=(), and serialize().
isFull()
template<class Data> bool Util::RingBuffer< Data >::isFull () const inline
Return true if full (if size == capacity), false otherwise.
Definition at line 349 of file RingBuffer.h.
References isFull().
Referenced by isFull().
operator[]() [1/2]
template<class Data> Data const & Util::RingBuffer< Data >::operator[] (int offset) const inline
Retrieve a const value, a specified number of time steps ago.
Parameters
offset number of steps back in time (offset=0 is current value).
Definition at line 357 of file RingBuffer.h.
References RingBuffer(), and UTIL_THROW.
operator[]() [2/2]
template<class Data> Data & Util::RingBuffer< Data >::operator[] (int offset) inline
Retrieve a value, a specified number of time steps ago.
Parameters
offset number of steps back in time (offset=0 is current value).
Definition at line 375 of file RingBuffer.h.
References RingBuffer(), and UTIL_THROW.
serialize()
template<class Data> template<class Archive> void Util::RingBuffer< Data >::serialize (Archive & ar, const unsigned int version)
Serialize a RingBuffer to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 393 of file RingBuffer.h.
References allocate(), capacity(), isAllocated(), serialize(), and UTIL_THROW.
Referenced by serialize().
The documentation for this class was generated from the following file:
RingBuffer.h