PSCF: Util::Lng Class Reference
Util::Lng Class Reference
Util namespace » Output Format
Wrapper for a long int, for formatted ostream output.
#include <Lng.h>
Public Member Functions
Constructors
Lng ()
Default constructor.
Lng (long int value)
Constructor, value only.
Lng (long int value, int width)
Constructor, value and width.
Setters
void setValue (long int value)
Set value of long int.
void setWidth (int width)
Set field width.
Accessors
long int value ()
Get value of long int.
int width ()
Get field width.
std::istream & operator>> (std::istream &in, Lng &object)
Input stream extractor for an Lng object.
std::ostream & operator<< (std::ostream &out, const Lng &object)
Output stream inserter for an Lng object.
Detailed Description
Wrapper for a long int, for formatted ostream output.
An Lng object has a long int numerical value, and a minimum output field width. The << operator for an Lng uses the specified width. The numerical value and width may both be optionally specified as parameters to a constructor. If the width is not specified, it is is is set to a default value equal to Format::defaultWidth().
An Lng object may be passed to an ostream as a temporary object. For example, the expression:
std::cout << Lng(13) << Lng(25, 10) << std::endl;
outputs the number 13 using the default width, followed by the number 25 in a field of minimum width 10.
Definition at line 35 of file Lng.h.
Constructor & Destructor Documentation
Lng() [1/3]
Util::Lng::Lng ()
Default constructor.
Definition at line 15 of file Lng.cpp.
Referenced by operator<<, and operator>>.
Lng() [2/3]
Util::Lng::Lng (long int value) explicit
Constructor, value only.
Parameters
value associated long int
Definition at line 22 of file Lng.cpp.
References value().
Lng() [3/3]
Util::Lng::Lng (long int value, int width)
Constructor, value and width.
Parameters
value associated long int
width field width
Definition at line 29 of file Lng.cpp.
References value(), and width().
Member Function Documentation
setValue()
void Util::Lng::setValue (long int value)
Set value of long int.
Parameters
value associated long int
Definition at line 34 of file Lng.cpp.
References value().
setWidth()
void Util::Lng::setWidth (int width)
Set field width.
Parameters
width field width
Definition at line 37 of file Lng.cpp.
References width().
value()
long int Util::Lng::value ()
Get value of long int.
Definition at line 40 of file Lng.cpp.
Referenced by Lng(), Lng(), and setValue().
width()
int Util::Lng::width ()
Get field width.
Definition at line 43 of file Lng.cpp.
Referenced by Lng(), and setWidth().
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & in, Lng & object) friend
Input stream extractor for an Lng object.
Parameters
in input stream
object Lng object to be read from stream
Returns
modified input stream
Definition at line 53 of file Lng.cpp.
References Lng().
operator<<
std::ostream & operator<< (std::ostream & out, const Lng & object) friend
Output stream inserter for an Lng object.
Parameters
out output stream
object Lng to be written to stream
Returns
modified output stream
Definition at line 66 of file Lng.cpp.
References Lng().
The documentation for this class was generated from the following files:
Lng.h
Lng.cpp