PSCF: Pscf::Rpg::AnalyzerManager< D > Class Template Reference
Pscf::Rpg::AnalyzerManager< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Field Theoretic Simulation (FTS) » Analyzers
Manager for a list of Analyzer objects.
#include <AnalyzerManager.h>
Public Member Functions
AnalyzerManager (Simulator< D > &simulator, System< D > &system)
Constructor.
virtual ~AnalyzerManager ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameter file.
void setup ()
Call initialize method of each Analyzer.
void sample (long iStep)
Call sample method of each Analyzer.
void output ()
Call output method of each analyzer.
Public Member Functions inherited from Util::Manager< Analyzer< D > >
Manager (bool uniqueNames=false)
Constructor.
virtual ~Manager ()
Destructor.
void addSubfactory (Factory< Analyzer< D > > &subfactory)
Set a SubFactory for this Manager.
void setFactory (Factory< Analyzer< D > > &factory)
Associate a Factory with this Manager.
void setFactory (Factory< Analyzer< D > > *factoryPtr)
Associated a Factory with this Manager (pass by pointer).
virtual void readParam (std::istream &in)
Read and create a set of objects.
virtual void readParamOptional (std::istream &in)
Optionally read and create a set of objects.
virtual void loadParameters (Serializable::IArchive &ar)
Load a set of objects to an output archive.
virtual void save (Serializable::OArchive &ar)
Save a set of objects to an output archive.
void append (Analyzer< D > &data, const std::string &name)
Append a Data object to the end of the sequence.
int size () const
Get logical size.
std::string className (int i) const
Get the subclass name for object number i.
Factory< Analyzer< D > > & factory ()
Return a reference to the factory.
bool hasFactory () const
Return true if this Manager has a Factory, false otherwise.
Analyzer< D > & operator[] (int i) const
Mimic C array subscripting.
Analyzer< D > * findFirst (std::string const &className)
Return pointer to first object with specified class name.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void setClassName (const char *className)
Set class name string.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
Protected Member Functions inherited from Util::Manager< Analyzer< D > >
void beginReadManager (std::istream &in)
Read (or attempt to read) opening line: "ManagerName{".
void endReadManager ()
Add closing bracket to output format.
virtual void initFactory ()
Create factory if necessary.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Attributes inherited from Util::Manager< Analyzer< D > >
Factory< Analyzer< D > > * factoryPtr_
Pointer to an associated Factory<Data> object.
Detailed Description
template<int D>
class Pscf::Rpg::AnalyzerManager< D >
Manager for a list of Analyzer objects.
Definition at line 22 of file rpg/fts/analyzer/AnalyzerManager.h.
Constructor & Destructor Documentation
AnalyzerManager()
template<int D> Pscf::Rpg::AnalyzerManager< D >::AnalyzerManager (Simulator< D > & simulator, System< D > & system)
Constructor.
Parameters
simulator parent McSimulator
system parent System
Definition at line 19 of file rpg/fts/analyzer/AnalyzerManager.tpp.
References Pscf::Rpg::AnalyzerManager< D >::setClassName().
~AnalyzerManager()
template<int D> Pscf::Rpg::AnalyzerManager< D >::~AnalyzerManager () virtual
Destructor.
Definition at line 30 of file rpg/fts/analyzer/AnalyzerManager.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::AnalyzerManager< D >::readParameters (std::istream & in) virtual
Read parameter file.
Parameters
in input parameter file stream.
Reimplemented from Util::Manager< Analyzer< D > >.
Definition at line 46 of file rpg/fts/analyzer/AnalyzerManager.tpp.
setup()
template<int D> void Pscf::Rpg::AnalyzerManager< D >::setup ()
Call initialize method of each Analyzer.
This method should be called just before the main simulation loop, after an initial configuration is known. It calls the setup() functionfor each analyzer, or does nothing if size() == 0.
Definition at line 58 of file rpg/fts/analyzer/AnalyzerManager.tpp.
sample()
template<int D> void Pscf::Rpg::AnalyzerManager< D >::sample (long iStep)
Call sample method of each Analyzer.
Precondition
Analyzer::baseInterval > 0
iStep::baseInterval == 0
Parameters
iStep step counter for main loop
Definition at line 69 of file rpg/fts/analyzer/AnalyzerManager.tpp.
References UTIL_CHECK.
output()
template<int D> void Pscf::Rpg::AnalyzerManager< D >::output ()
Call output method of each analyzer.
This method should be called after the main simulation loop. It calls the output() function of each analyzer, or does nothing if size() == 0.
Definition at line 82 of file rpg/fts/analyzer/AnalyzerManager.tpp.
setClassName()
template<int D> void Util::ParamComposite::setClassName (const char * className) protected
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by Pscf::Rpg::AnalyzerManager< D >::AnalyzerManager().
readOptional()
template<int D> template<typename Type > ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
read()
template<int D> template<typename Type > ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value) protected
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 305 of file ParamComposite.h.
Referenced by pscfpp.command.Script::__init__(), pscfpp.field.Field::__init__(), pscfpp.output.Thermo::__init__(), pscfpp.param.Array::__init__(), pscfpp.param.Composite::__init__(), and pscfpp.param.Matrix::__init__().
The documentation for this class was generated from the following files:
rpg/fts/analyzer/AnalyzerManager.h
rpg/fts/analyzer/AnalyzerManager.tpp