PSCF: Util::Vector Class Reference
Util::Vector Class Reference
Util namespace » Space (Vector, Tensor)
A Vector is a Cartesian vector.
#include <Vector.h>
Public Member Functions
Constructors
Vector ()
Default constructor.
Vector (const Vector &v)
Copy constructor.
Vector (double scalar)
Constructor, initialize all elements to a scalar value.
Vector (const double *v)
Construct Vector from C double[3] array.
Vector (double x, double y, double z=0.0)
Construct Vector from its coordinates.
Vector & zero ()
Set all elements of a 3D vector to zero.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize to/from an archive.
Assignment
Vector & operator= (const Vector &v)
Copy assignment.
Vector & operator= (const double *v)
Assignment from C double[3] array.
Arithmetic Assignment
void operator+= (const Vector &dv)
Add vector dv to this vector.
void operator-= (const Vector &dv)
Subtract vector dv from this vector.
void operator*= (double s)
Multiply this vector by scalar s.
void operator/= (double s)
Divide this vector by scalar s.
Array Subscript
const double & operator[] (int i) const
Return one Cartesian element by value.
double & operator[] (int i)
Return one element of the vector by references.
Scalar-valued functions
double square () const
Return square magnitude of this vector.
double abs () const
Return absolute magnitude of this vector.
double dot (const Vector &v) const
Return dot product of this vector and vector v.
double projection (const Vector &p) const
Return projection of this vector along vector p.
Vector valued functions (result assigned to invoking object)
Vector & add (const Vector &v1, const Vector &v2)
Add vectors v1 and v2.
Vector & subtract (const Vector &v1, const Vector &v2)
Subtract vector v2 from v1.
Vector & multiply (const Vector &v, double s)
Multiply a vector v by a scalar s.
Vector & divide (const Vector &v, double s)
Divide vector v by scalar s.
Vector & cross (const Vector &v1, const Vector &v2)
Calculate cross product of vectors v1 and v2.
Vector & versor (const Vector &v)
Calculate unit vector parallel to input vector v.
Vector & parallel (const Vector &v, const Vector &p)
Calculate component of vector v parallel to vector p.
Vector & transverse (const Vector &v, const Vector &p)
Calculate component of vector v transverse to vector p.
int minId (const Vector &v)
Computes the index corresponding to minimum element in a vector.
int maxId (const Vector &v)
Computes the index corresponding to maximum element in a vector.
Static Members
static const Vector Zero = Vector(0.0)
Zero Vector = {0.0, 0.0, 0.0}.
static void initStatic ()
Initialize Zero Vector.
bool operator== (const Vector &v1, const Vector &v2)
Equality for Vectors.
bool operator== (const Vector &v1, const double *v2)
Equality of Vector and C array.
std::istream & operator>> (std::istream &in, Vector &vector)
istream extractor for a Vector.
std::ostream & operator<< (std::ostream &out, const Vector &vector)
ostream inserter for a Vector.
Detailed Description
A Vector is a Cartesian vector.
The Cartesian elements of a Vector can be accessed using array notation: The elements of a three dimensional Vector v are v[0], v[1], and v[2]. The subscript operator [] returns elements as references, which can be used on either the left or right side of an assignment operator.
The arithmetic assignment operators +=, -=, *=, and /= are overloaded. The operators += and -= represent increment or decrement by a vector, while *= and /= represent multiplication or division by a scalar.
All other unary and binary mathematical operations are implemented as methods. Operations that yield a scalar result, such as a dot product, are implemented as methods that return the resulting value. Operations that yield a Vector, such as vector addition, are implemented by methods that assign the result to the invoking vector, and return a reference to the invoking vector. For example,
Vector a, b, c;
double s;
a[0] = 0.0
a[1] = 1.0
a[2] = 2.0
b[0] =  0.5
b[1] = -0.5
b[2] = -1.5
// Set s = a.b
s = a.dot(b)
// Set c = a + b
c.add(a, b)
// Set a = a + b
a += b
// Set b = b*2
b *= 2
This syntax for Vector valued operations avoids dynamic allocation of temporary Vector objects, by requiring that the invoking function provide an object to hold the result.
For efficiency, all methods in this class are declared inline.
Definition at line 75 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/5]
Util::Vector::Vector () inline
Default constructor.
Definition at line 463 of file Vector.h.
Referenced by add(), cross(), divide(), dot(), maxId(), minId(), multiply(), operator+=(), operator-=(), operator<<, operator=(), operator=(), operator==, operator==, operator>>, parallel(), projection(), subtract(), transverse(), Vector(), versor(), and zero().
Vector() [2/5]
Util::Vector::Vector (const Vector & v) inline
Copy constructor.
Parameters
v Vector to be copied
Definition at line 470 of file Vector.h.
References Vector().
Vector() [3/5]
Util::Vector::Vector (double scalar) inline explicit
Constructor, initialize all elements to a scalar value.
Parameters
scalar initial value for all elements.
Definition at line 481 of file Vector.h.
Vector() [4/5]
Util::Vector::Vector (const double * v) inline explicit
Construct Vector from C double[3] array.
Parameters
v array of 3 coordinates
Definition at line 492 of file Vector.h.
Vector() [5/5]
Util::Vector::Vector (double x, double y, double z = 0.0) inline
Construct Vector from its coordinates.
Parameters
x x-axis coordinate, v[0]
y y-axis coordinate, v[1]
z z-axis coordinate, v[2]
Definition at line 503 of file Vector.h.
Member Function Documentation
zero()
Vector & Util::Vector::zero () inline
Set all elements of a 3D vector to zero.
Definition at line 514 of file Vector.h.
References Vector().
Referenced by Util::setToZero().
serialize()
template<class Archive> void Util::Vector::serialize (Archive & ar, const unsigned int version) inline
Serialize to/from an archive.
Parameters
ar archive
version archive version id
Definition at line 818 of file Vector.h.
operator=() [1/2]
Vector & Util::Vector::operator= (const Vector & v) inline
Copy assignment.
Parameters
v Vector to assign.
Definition at line 526 of file Vector.h.
References Vector().
operator=() [2/2]
Vector & Util::Vector::operator= (const double * v) inline
Assignment from C double[3] array.
Parameters
v C-array of components
Definition at line 538 of file Vector.h.
References Vector().
operator+=()
void Util::Vector::operator+= (const Vector & dv) inline
Add vector dv to this vector.
Upon return, *this = this + dv.
Parameters
dv vector increment (input)
Definition at line 550 of file Vector.h.
References Vector().
operator-=()
void Util::Vector::operator-= (const Vector & dv) inline
Subtract vector dv from this vector.
Upon return, *this = this + dv.
Parameters
dv vector increment (input)
Definition at line 561 of file Vector.h.
References Vector().
operator*=()
void Util::Vector::operator*= (double s) inline
Multiply this vector by scalar s.
Upon return, *this = (*this)*s.
Parameters
s scalar multiplier
Definition at line 572 of file Vector.h.
operator/=()
void Util::Vector::operator/= (double s) inline
Divide this vector by scalar s.
Upon return, *this = (*this)/s.
Parameters
s scalar divisor (input)
Definition at line 583 of file Vector.h.
operator[]() [1/2]
const double & Util::Vector::operator[] (int i) const inline
Return one Cartesian element by value.
Parameters
i element index
Returns
element i of the vector
Definition at line 594 of file Vector.h.
References Util::Dimension.
operator[]() [2/2]
double & Util::Vector::operator[] (int i) inline
Return one element of the vector by references.
Parameters
i element index
Returns
element i of this vector
Definition at line 605 of file Vector.h.
References Util::Dimension.
square()
double Util::Vector::square () const inline
Return square magnitude of this vector.
Returns
square magnitude of this vector
Definition at line 616 of file Vector.h.
Referenced by abs(), parallel(), and transverse().
abs()
double Util::Vector::abs () const inline
Return absolute magnitude of this vector.
Returns
absolute magnitude (norm) of this vector.
Definition at line 625 of file Vector.h.
References square().
Referenced by projection(), and versor().
dot()
double Util::Vector::dot (const Vector & v) const inline
Return dot product of this vector and vector v.
Parameters
v input vector
Returns
dot product of this vector and vector v
Definition at line 632 of file Vector.h.
References Vector().
Referenced by parallel(), Util::product(), projection(), and transverse().
projection()
double Util::Vector::projection (const Vector & p) const inline
Return projection of this vector along vector p.
Parameters
p vector parallel to direction along which to project
Returns
scalar projection this->dot(p)/p.abs()
Definition at line 641 of file Vector.h.
References abs(), dot(), and Vector().
add()
Vector & Util::Vector::add (const Vector & v1, const Vector & v2) inline
Add vectors v1 and v2.
Upon return, *this = v1 + v2.
Parameters
v1 vector (input)
v2 vector (input)
Returns
modified invoking vector
Definition at line 657 of file Vector.h.
References Vector().
subtract()
Vector & Util::Vector::subtract (const Vector & v1, const Vector & v2) inline
Subtract vector v2 from v1.
Upon return, *this = v1 - v2.
Parameters
v1 vector (input)
v2 vector (input)
Returns
modified invoking vector
Definition at line 672 of file Vector.h.
References Vector().
multiply()
Vector & Util::Vector::multiply (const Vector & v, double s) inline
Multiply a vector v by a scalar s.
Upon return, *this = v*s.
Parameters
v vector input
s scalar input
Returns
modified invoking vector
Definition at line 686 of file Vector.h.
References Vector().
divide()
Vector & Util::Vector::divide (const Vector & v, double s) inline
Divide vector v by scalar s.
Upon return, *this = v/s;
Parameters
v vector input
s scalar input
Returns
modified invoking vector
Definition at line 700 of file Vector.h.
References Vector().
cross()
Vector & Util::Vector::cross (const Vector & v1, const Vector & v2) inline
Calculate cross product of vectors v1 and v2.
Upon return, *this = v1 x v2.
Parameters
v1 input vector
v2 input vector
Returns
modified invoking vector
Definition at line 714 of file Vector.h.
References Vector().
versor()
Vector & Util::Vector::versor (const Vector & v) inline
Calculate unit vector parallel to input vector v.
Upon return *this = unit vector.
Parameters
v input vector
Returns
modified invoking Vector
Definition at line 726 of file Vector.h.
References abs(), and Vector().
parallel()
Vector & Util::Vector::parallel (const Vector & v, const Vector & p) inline
Calculate component of vector v parallel to vector p.
Upon return, the invoking vector is equal to the vector projection of vector v along a direction parallel to vector p.
The vector projection of v along p is parallel to p and has an absolute magnitude equal to the scalar projection of v along p.
Parameters
v vector to project
p vector along which to project
Returns
modified invoking Vector
Definition at line 749 of file Vector.h.
References dot(), square(), and Vector().
transverse()
Vector & Util::Vector::transverse (const Vector & v, const Vector & p) inline
Calculate component of vector v transverse to vector p.
Upon return, the invoking vector is equal to the vector projection of vector v perpendicular to vector p.
Parameters
v input vector
p vector perpendicular to which to project.
Returns
modified invoking Vector
Definition at line 771 of file Vector.h.
References dot(), square(), and Vector().
minId()
int Util::Vector::minId (const Vector & v)
Computes the index corresponding to minimum element in a vector.
Parameters
v input vector
Returns
index of the minimum element.
References Vector().
maxId()
int Util::Vector::maxId (const Vector & v)
Computes the index corresponding to maximum element in a vector.
Parameters
v input vector
Returns
index of the maximum element.
References Vector().
initStatic()
void Util::Vector::initStatic () static
Initialize Zero Vector.
Definition at line 119 of file Vector.cpp.
References UTIL_CHECK.
Referenced by Util::initStatic().
Friends And Related Symbol Documentation
operator== [1/2]
bool operator== (const Vector & v1, const Vector & v2) friend
Equality for Vectors.
Definition at line 26 of file Vector.cpp.
References Util::Dimension, and Vector().
operator== [2/2]
bool operator== (const Vector & v1, const double * v2) friend
Equality of Vector and C array.
Definition at line 36 of file Vector.cpp.
References Util::Dimension, and Vector().
operator>>
std::istream & operator>> (std::istream & in, Vector & vector) friend
istream extractor for a Vector.
Input elements of a vector from stream, without line breaks.
Parameters
in input stream
vector Vector to be read from stream
Returns
modified input stream
Definition at line 65 of file Vector.cpp.
References Util::Dimension, and Vector().
operator<<
std::ostream & operator<< (std::ostream & out, const Vector & vector) friend
ostream inserter for a Vector.
Output elements of a vector to stream, without line breaks.
Parameters
out output stream
vector Vector to be written to stream
Returns
modified output stream
Definition at line 76 of file Vector.cpp.
References Util::Dimension, and Vector().
Member Data Documentation
Zero
const Vector Util::Vector::Zero = Vector(0.0) static
Zero Vector = {0.0, 0.0, 0.0}.
Definition at line 369 of file Vector.h.
The documentation for this class was generated from the following files:
Vector.h
Vector.cpp