PSCF: Pscf::Rpg::McSimulator< D > Class Template Reference
Pscf::Rpg::McSimulator< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Field Theoretic Simulation (FTS) » Monte Carlo
Monte-Carlo simulation coordinator.
#include <McSimulator.h>
Public Member Functions
McSimulator (System< D > &system)
Constructor.
~McSimulator ()
Destructor.
virtual void readParameters (std::istream &in)
Read parameters for a MC simulation.
Primary Actions: Simulation and Analysis
void simulate (int nStep)
Perform a field theoretic Monte-Carlo simulation.
virtual void analyze (int min, int max, std::string classname, std::string filename)
Read and analyze a trajectory file.
virtual void outputTimers (std::ostream &out) const
Output timing results.
virtual void clearTimers ()
Clear timers.
bool needsCc ()
Return the simulations whether needs to store cc fields.
bool needsDc ()
Return the simulations whether needs to store Dc fields.
Miscellaneous
bool hasMcMoves () const
Does this McSimulator have any MC moves defined?
McMoveManager< D > & mcMoveManager ()
Get McMoveManger.
AnalyzerManager< D > & analyzerManager ()
Get AnalyzerManger.
Factory< TrajectoryReader< D > > & trajectoryReaderFactory ()
Get the trajectory reader factory by reference.
Public Member Functions inherited from Pscf::Rpg::Simulator< D >
Simulator (System< D > &system)
Constructor.
~Simulator ()
Destructor.
void allocate ()
Allocate required memory.
void clearData ()
Clear field eigen-components and hamiltonian components.
virtual void outputMdeCounter (std::ostream &out) const
Output MDE counter.
long iStep ()
Return the current converged simulation step index.
long iTotalStep ()
Return the current simulation step index.
void analyzeChi ()
Perform eigenvalue analysis of projected chi matrix.
DArray< double > const & chiEvals () const
Get an array of the eigenvalues of the projected chi matrix.
double chiEval (int a) const
Get a single eigenvalue of the projected chi matrix.
DMatrix< double > const & chiEvecs () const
Get the matrix of all eigenvectors of the projected chi matrix.
double chiEvecs (int a, int i) const
Get one element of an eigenvector of the projected chi matrix.
DArray< double > const & sc () const
Get all components of the vector S.
double sc (int a) const
Get a single component of the S vector.
void computeHamiltonian ()
Compute the Hamiltonian used in field theoretic simulations.
double hamiltonian () const
Get the Hamiltonian used in field theoretic simulations.
double idealHamiltonian () const
Get ideal gas contribution (-lnQ) to MC Hamiltonian.
double fieldHamiltonian () const
Get the quadratic field contribution (HW) to MC Hamiltonian.
double perturbationHamiltonian () const
Get the perturbation to the standard Hamiltonian (if any).
bool hasHamiltonian () const
Has the MC Hamiltonian been computed for current w and c fields?
void computeWc ()
Compute eigenvector components of the current w fields.
DArray< RField< D > > const & wc () const
Get all eigenvector components of the current w fields.
RField< D > const & wc (int a) const
Get one eigenvector component of the current w fields.
bool hasWc () const
Are eigen-components of current w fields valid ?
void computeCc ()
Compute eigenvector components of the current c fields.
DArray< RField< D > > const & cc () const
Get all eigenvector components of the current c fields.
RField< D > const & cc (int a) const
Get one eigenvector component of the current c fields.
bool hasCc () const
Are eigen-components of current c fields valid ?
void computeDc ()
Compute functional derivatives of the Hamiltonian.
DArray< RField< D > > const & dc () const
Get all of the current d fields.
RField< D > const & dc (int i) const
Get one eigenvector component of the current d fields.
bool hasDc () const
Are the current d fields valid ?
void saveState ()
Save a copy of the fts move state.
void restoreState ()
Restore the saved copy of the fts move state.
void clearState ()
Clear the saved copy of the fts state.
System< D > & system ()
Get parent system by reference.
Compressor< D > & compressor ()
Get the compressor by non-const reference.
Compressor< D > const & compressor () const
Get the compressor by const reference.
bool hasCompressor () const
Does this Simulator have a Compressor object?
Random & random ()
Get random number generator by reference.
CudaRandom & cudaRandom ()
Get cuda random number generator by reference.
bool hasPerturbation () const
Does this Simulator have a Perturbation?
Perturbation< D > const & perturbation () const
Get the associated Perturbation by const reference.
Perturbation< D > & perturbation ()
Get the perturbation factory by non-const reference.
bool hasRamp () const
Does this Simulator have a Ramp?
Ramp< D > const & ramp () const
Get the associated Ramp by const reference.
Ramp< D > & ramp ()
Get the ramp by non-const reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Protected Member Functions
void setClassName (const char *className)
Set class name string.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
Protected Member Functions inherited from Pscf::Rpg::Simulator< D >
void readRandomSeed (std::istream &in)
Read random seed and initialize random number generators.
CompressorFactory< D > & compressorFactory ()
Get the compressor factory by reference.
void readCompressor (std::istream &in, bool &isEnd)
Read the compressor block of the parameter file.
PerturbationFactory< D > & perturbationFactory ()
Get the perturbation factory by reference.
void readPerturbation (std::istream &in, bool &isEnd)
Optionally read an associated perturbation.
void setPerturbation (Perturbation< D > *ptr)
Set the associated perturbation.
RampFactory< D > & rampFactory ()
Get the ramp factory by reference.
void readRamp (std::istream &in, bool &isEnd)
Optionally read an associated ramp.
void setRamp (Ramp< D > *ptr)
Set the associated ramp.
void setClassName (const char *className)
Set class name string.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Attributes inherited from Pscf::Rpg::Simulator< D >
Random random_
Random number generator.
CudaRandom cudaRandom_
Random number generator.
DArray< RField< D > > wc_
Eigenvector components of w fields on a real space grid.
DArray< RField< D > > cc_
Eigenvector components of c fields on a real space grid.
DArray< RField< D > > dc_
Components of d fields on a real space grid.
SimState< D > state_
State saved during fts simulation.
double hamiltonian_
Field theoretic Hamiltonian H[W] (extensive value).
double idealHamiltonian_
Ideal gas contribution (lnQ) to Hamiltonian H[W].
double fieldHamiltonian_
Field contribution (H_W) to Hamiltonian.
double perturbationHamiltonian_
Perturbation to the standard Hamiltonian (if any).
long iStep_
Simulation step counter.
long iTotalStep_
Simulation step counter.
long seed_
Random number generator seed.
bool hasHamiltonian_
Has the Hamiltonian been computed for the current w and c fields?
bool hasWc_
Have eigen-components of the current w fields been computed ?
bool hasCc_
Have eigen-components of the current c fields been computed ?
bool hasDc_
Have functional derivatives of H[W] been computed ?
Detailed Description
template<int D>
class Pscf::Rpg::McSimulator< D >
Monte-Carlo simulation coordinator.
Definition at line 30 of file rpg/fts/montecarlo/McSimulator.h.
Constructor & Destructor Documentation
McSimulator()
template<int D> Pscf::Rpg::McSimulator< D >::McSimulator (System< D > & system)
Constructor.
Parameters
system parent System
Definition at line 41 of file rpg/fts/montecarlo/McSimulator.tpp.
References setClassName(), Pscf::Rpg::Simulator< D >::Simulator(), and Pscf::Rpg::Simulator< D >::system().
~McSimulator()
template<int D> Pscf::Rpg::McSimulator< D >::~McSimulator ()
Destructor.
Definition at line 56 of file rpg/fts/montecarlo/McSimulator.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::McSimulator< D >::readParameters (std::istream & in) virtual
Read parameters for a MC simulation.
Parameters
in input parameter stream
Reimplemented from Pscf::Rpg::Simulator< D >.
Definition at line 67 of file rpg/fts/montecarlo/McSimulator.tpp.
References Pscf::Rpg::Simulator< D >::allocate(), Pscf::Rpg::Analyzer< D >::baseInterval, Pscf::Rpg::Simulator< D >::hasCompressor(), hasMcMoves(), Pscf::Rpg::Simulator< D >::readCompressor(), readParamCompositeOptional(), Pscf::Rpg::Simulator< D >::readPerturbation(), Pscf::Rpg::Simulator< D >::readRamp(), Pscf::Rpg::Simulator< D >::readRandomSeed(), Pscf::Rpg::Simulator< D >::state_, and UTIL_CHECK.
simulate()
template<int D> void Pscf::Rpg::McSimulator< D >::simulate (int nStep) virtual
Perform a field theoretic Monte-Carlo simulation.
Perform a field theoretic Monte-Carlo simulation using the partial saddle-point approximation.
Parameters
nStep number of Monte-Carlo steps
Reimplemented from Pscf::Rpg::Simulator< D >.
Definition at line 159 of file rpg/fts/montecarlo/McSimulator.tpp.
References Pscf::Rpg::Analyzer< D >::baseInterval, Util::Log::file(), Pscf::Rpg::Simulator< D >::hasCompressor(), hasMcMoves(), Pscf::Rpg::Simulator< D >::hasRamp(), Pscf::Rpg::Simulator< D >::iStep_, Pscf::Rpg::Simulator< D >::iTotalStep_, Pscf::Rpg::Simulator< D >::outputMdeCounter(), Pscf::Rpg::Simulator< D >::ramp(), Util::Timer::start(), Util::Timer::stop(), Util::Timer::time(), and UTIL_CHECK.
analyze()
template<int D> void Pscf::Rpg::McSimulator< D >::analyze (int min, int max, std::string classname, std::string filename) virtual
Read and analyze a trajectory file.
This function uses an instance of the TrajectoryReader class specified by the "classname" argument to read a trajectory file.
Parameters
min start at this frame number
max end at this frame number
classname name of the TrajectoryReader class to use
filename name of the trajectory file
Reimplemented from Pscf::Rpg::Simulator< D >.
Definition at line 281 of file rpg/fts/montecarlo/McSimulator.tpp.
References Pscf::Rpg::Analyzer< D >::baseInterval, Pscf::Rpg::Simulator< D >::clearData(), Pscf::Rpg::TrajectoryReader< D >::close(), Util::Log::file(), Pscf::Rpg::Simulator< D >::iStep_, Pscf::Rpg::TrajectoryReader< D >::open(), Pscf::Rpg::TrajectoryReader< D >::readFrame(), Util::Timer::start(), Util::Timer::stop(), Util::Timer::time(), trajectoryReaderFactory(), UTIL_CHECK, and UTIL_THROW.
outputTimers()
template<int D> void Pscf::Rpg::McSimulator< D >::outputTimers (std::ostream & out) const virtual
Output timing results.
Reimplemented from Pscf::Rpg::Simulator< D >.
Definition at line 352 of file rpg/fts/montecarlo/McSimulator.tpp.
References Pscf::Rpg::Simulator< D >::compressor().
clearTimers()
template<int D> void Pscf::Rpg::McSimulator< D >::clearTimers () virtual
Clear timers.
Reimplemented from Pscf::Rpg::Simulator< D >.
Definition at line 364 of file rpg/fts/montecarlo/McSimulator.tpp.
needsCc()
template<int D> bool Pscf::Rpg::McSimulator< D >::needsCc () inline
Return the simulations whether needs to store cc fields.
Definition at line 248 of file rpg/fts/montecarlo/McSimulator.h.
References Pscf::Rpg::Simulator< D >::state_.
needsDc()
template<int D> bool Pscf::Rpg::McSimulator< D >::needsDc () inline
Return the simulations whether needs to store Dc fields.
Definition at line 255 of file rpg/fts/montecarlo/McSimulator.h.
References Pscf::Rpg::Simulator< D >::state_.
hasMcMoves()
template<int D> bool Pscf::Rpg::McSimulator< D >::hasMcMoves () const inline
Does this McSimulator have any MC moves defined?
Equivalent to a test for mcMoveManager().size() > 0.
Definition at line 224 of file rpg/fts/montecarlo/McSimulator.h.
Referenced by readParameters(), and simulate().
mcMoveManager()
template<int D> McMoveManager< D > & Pscf::Rpg::McSimulator< D >::mcMoveManager () inline
Get McMoveManger.
Definition at line 229 of file rpg/fts/montecarlo/McSimulator.h.
analyzerManager()
template<int D> AnalyzerManager< D > & Pscf::Rpg::McSimulator< D >::analyzerManager () inline
Get AnalyzerManger.
Definition at line 234 of file rpg/fts/montecarlo/McSimulator.h.
trajectoryReaderFactory()
template<int D> Factory< TrajectoryReader< D > > & Pscf::Rpg::McSimulator< D >::trajectoryReaderFactory () inline
Get the trajectory reader factory by reference.
Definition at line 240 of file rpg/fts/montecarlo/McSimulator.h.
References UTIL_ASSERT.
Referenced by analyze().
setClassName()
template<int D> void Util::ParamComposite::setClassName (const char * className) protected
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by McSimulator().
read()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::read (std::istream & in, const char * label, Type & value) protected
Add and read a new required ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, true).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 305 of file ParamComposite.h.
readOptional()
template<int D> template<typename Type> ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
readParamComposite()
template<int D> void Util::ParamComposite::readParamComposite (std::istream & in, ParamComposite & child, bool next = true) protected
Add and read a required child ParamComposite.
Parameters
in input stream for reading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 281 of file ParamComposite.cpp.
readParamCompositeOptional()
template<int D> void Util::ParamComposite::readParamCompositeOptional (std::istream & in, ParamComposite & child, bool next = true) protected
Add and attempt to read an optional child ParamComposite.
Parameters
in input stream for reading
child child ParamComposite object
next true if the indent level is one higher than parent.
Definition at line 292 of file ParamComposite.cpp.
Referenced by readParameters().
The documentation for this class was generated from the following files:
rpg/fts/montecarlo/McMove.h
rpg/fts/montecarlo/McSimulator.h
rpg/fts/montecarlo/McSimulator.tpp