PSCF: Pscf::Field< T > Class Template Reference
Pscf::Field< T > Class Template Reference
Base class template for a field defined on a spatial grid.
#include <Field.h>
Public Member Functions
Field ()
Constructor.
Field (Field< T > const &other)
Copy constructor.
Field< T > & operator= (Field< T > const &other)
Assignment operator.
Field< T > & operator= (T &scalar)
Assignment - assign all elements to a common scalar.
Field< T > & operator+= (Field< T > &other)
Increment operator - add one field by another.
Field< T > & operator-= (Field< T > &other)
Decrement operator - subtract one field from another.
Field< T > & operator*= (T scalar)
Multiplication operator - multiply one field by a scalar.
Field< T > & operator*= (Field< T > &other)
Pointwise multipication of one field by another.
void setToZero ()
Set all elements to zero.
T average () const
Compute and return average of all elements.
Public Member Functions inherited from Util::DArray< T >
DArray ()
Default constructor.
DArray (const DArray< T > &other)
Copy constructor.
virtual ~DArray ()
Destructor.
DArray< T > & operator= (const DArray< T > &other)
Assignment operator.
void allocate (int capacity)
Allocate the underlying C array.
void deallocate ()
Dellocate the underlying C array.
void reallocate (int capacity)
Reallocate the underlying C array and copy to new location.
bool isAllocated () const
Return true if the DArray has been allocated, false otherwise.
void serialize (Archive &ar, const unsigned int version)
Serialize a DArray to/from an Archive.
Public Member Functions inherited from Util::Array< T >
virtual ~Array ()
Destructor.
int capacity () const
Return allocated size.
void begin (ArrayIterator< T > &iterator)
Set an iterator to begin this Array.
void begin (ConstArrayIterator< T > &iterator) const
Set a const iterator to begin this Array.
T & operator[] (int i)
Get an element by non-const reference.
const T & operator[] (int i) const
Get an element by const reference.
T * cArray ()
Return pointer to underlying C array.
const T * cArray () const
Return pointer to const to underlying C array.
Additional Inherited Members
Protected Member Functions inherited from Util::Array< T >
Array ()
Default constructor.
Protected Attributes inherited from Util::Array< T >
T * data_
Pointer to an array of Data elements.
int capacity_
Allocated size of the data_ array.
Detailed Description
template<typename T = double>
class Pscf::Field< T >
Base class template for a field defined on a spatial grid.
Derived from DArray<T>, and provides useful arithmetic operations.
Definition at line 23 of file pscf/math/Field.h.
Constructor & Destructor Documentation
template<typename Data > Pscf::Pspc::Field< Data >::Field ()
Constructor.
Definition at line 26 of file Field.tpp.
Referenced by Pscf::Pspc::Field< Data >::~Field().
template<class T> Pscf::Field< T >::Field (Field< T > const & other)
Copy constructor.
Definition at line 98 of file pscf/math/Field.h.
References Util::Memory::allocate(), Util::Array< T >::capacity_, Util::Array< T >::data_, Util::DArray< T >::isAllocated(), and UTIL_THROW.
Member Function Documentation
template<class T> Field< T > & Pscf::Field< T >::operator= (Field< T > const & other)
Assignment operator.
Definition at line 122 of file pscf/math/Field.h.
References Util::DArray< T >::allocate(), Util::Array< T >::capacity(), Util::Array< T >::capacity_, Util::Array< T >::data_, Util::DArray< T >::isAllocated(), and UTIL_THROW.
Referenced by Pscf::Pspc::Field< Data >::~Field().
template<typename T> Field< T > & Pscf::Field< T >::operator= (T & scalar)
Assignment - assign all elements to a common scalar.
Definition at line 150 of file pscf/math/Field.h.
References Util::Array< T >::capacity_, Util::Array< T >::data_, Util::DArray< T >::isAllocated(), and UTIL_THROW.
template<typename T> Field< T > & Pscf::Field< T >::operator+= (Field< T > & other)
Increment operator - add one field by another.
Definition at line 165 of file pscf/math/Field.h.
References Util::Array< T >::capacity_, Util::Array< T >::data_, Util::DArray< T >::isAllocated(), and UTIL_THROW.
template<typename T> Field< T > & Pscf::Field< T >::operator-= (Field< T > & other)
Decrement operator - subtract one field from another.
Definition at line 186 of file pscf/math/Field.h.
References Util::Array< T >::capacity_, Util::Array< T >::data_, Util::DArray< T >::isAllocated(), and UTIL_THROW.
template<typename T> Field< T > & Pscf::Field< T >::operator*= (T scalar)
Multiplication operator - multiply one field by a scalar.
Definition at line 210 of file pscf/math/Field.h.
References Util::Array< T >::capacity_, Util::Array< T >::data_, Util::DArray< T >::isAllocated(), and UTIL_THROW.
template<typename T> Field< T > & Pscf::Field< T >::operator*= (Field< T > & other)
Pointwise multipication of one field by another.
Definition at line 227 of file pscf/math/Field.h.
References Util::Array< T >::capacity_, Util::Array< T >::data_, Util::DArray< T >::isAllocated(), and UTIL_THROW.
template<typename T > void Pscf::Field< T >::setToZero ()
Set all elements to zero.
Definition at line 250 of file pscf/math/Field.h.
References Util::Array< T >::capacity_, and Util::Array< T >::data_.
template<typename T > T Pscf::Field< T >::average () const
Compute and return average of all elements.
Definition at line 261 of file pscf/math/Field.h.
References Util::Array< T >::capacity_, and Util::Array< T >::data_.
The documentation for this class was generated from the following files:
pscf/math/Field.h
Field.tpp