PSCF: Pscf::Rpc::FourthOrderParameter< D > Class Template Reference
Pscf::Rpc::FourthOrderParameter< D > Class Template Reference
Pscf namespace » Pscf::Rpc - Real Periodic Fields (CPU) » Field Theoretic Simulation (FTS) » Analyzers
FourthOrderParameter is used to detect an order-disorder transition.
#include <FourthOrderParameter.h>
Public Member Functions
FourthOrderParameter (Simulator< D > &simulator, System< D > &system)
Constructor.
virtual ~FourthOrderParameter ()
Destructor.
virtual void setup ()
Setup before simulation loop.
virtual double compute ()
Compute and return the derivative of H w/ respect to chi.
virtual void outputValue (int step, double value)
Output a sampled or block average value.
void computePrefactor ()
Compute prefactor for each Fourier wavevector.
Public Member Functions inherited from Pscf::Rpc::AverageAnalyzer< D >
AverageAnalyzer (Simulator< D > &simulator, System< D > &system)
Constructor.
virtual ~AverageAnalyzer ()
Destructor.
virtual void readParameters (std::istream &in)
Read interval, outputFileName and (optionally) nSamplePerOutput.
virtual void sample (long iStep)
Compute a sampled value and update the accumulator.
virtual void output ()
Write final results to file after a simulation.
int nSamplePerOutput () const
Get value of nSamplePerOutput.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Public Member Functions inherited from Pscf::Rpc::Analyzer< D >
Analyzer ()
Default constructor.
virtual ~Analyzer ()
Destructor.
int interval () const
Get interval value.
bool isAtInterval (long counter) const
Return true iff counter is a multiple of the interval.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from Pscf::Rpc::AverageAnalyzer< D >
Simulator< D > & simulator ()
Return reference to parent simulator.
System< D > & system ()
Return reference to parent system.
Protected Member Functions inherited from Pscf::Rpc::Analyzer< D >
void setFileMaster (FileMaster &fileMaster)
Set the FileMaster to use to open files.
void readInterval (std::istream &in)
Optionally read interval from file, with error checking.
void readOutputFileName (std::istream &in)
Read outputFileName from file.
FileMaster & fileMaster ()
Get the FileMaster by reference.
const std::string & outputFileName () const
Return outputFileName string.
std::string outputFileName (std::string suffix) const
Return outputFileName string with added suffix.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Pscf::Rpc::Analyzer< D >
static void initStatic ()
Define and initialize baseInterval.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Static Public Attributes inherited from Pscf::Rpc::Analyzer< D >
static long baseInterval
The interval for an Analyzer must be a multiple of baseInterval.
Protected Attributes inherited from Pscf::Rpc::AverageAnalyzer< D >
Average accumulator_
Average object.
Detailed Description
template<int D>
class Pscf::Rpc::FourthOrderParameter< D >
FourthOrderParameter is used to detect an order-disorder transition.
This class evaluates the sum of fourth power of the Fourier mode amplitude of fluctuating fields.
The order parameter is defined as
\[ \Psi_{\text{fourth}} \equiv \left[ \sum W_{-}(\bf G)^4 \right] ^{\frac{1}{4}} \]
where \(W_(G)\) is a Fourier mode of fluctuating field.
See also
Manual Page
Definition at line 47 of file rpc/fts/analyzer/FourthOrderParameter.h.
Constructor & Destructor Documentation
FourthOrderParameter()
template<int D> Pscf::Rpc::FourthOrderParameter< D >::FourthOrderParameter (Simulator< D > & simulator, System< D > & system)
Constructor.
Definition at line 45 of file rpc/fts/analyzer/FourthOrderParameter.tpp.
References Pscf::Rpc::FourthOrderParameter< D >::setClassName().
~FourthOrderParameter()
template<int D> Pscf::Rpc::FourthOrderParameter< D >::~FourthOrderParameter () virtual
Destructor.
Definition at line 56 of file rpc/fts/analyzer/FourthOrderParameter.tpp.
Member Function Documentation
setup()
template<int D> void Pscf::Rpc::FourthOrderParameter< D >::setup () virtual
Setup before simulation loop.
Reimplemented from Pscf::Rpc::AverageAnalyzer< D >.
Definition at line 63 of file rpc/fts/analyzer/FourthOrderParameter.tpp.
References Pscf::Rpc::AverageAnalyzer< D >::setup(), UTIL_CHECK, and UTIL_THROW.
compute()
template<int D> double Pscf::Rpc::FourthOrderParameter< D >::compute () virtual
Compute and return the derivative of H w/ respect to chi.
Implements Pscf::Rpc::AverageAnalyzer< D >.
Definition at line 103 of file rpc/fts/analyzer/FourthOrderParameter.tpp.
References Pscf::MeshIterator< D >::atEnd(), Pscf::MeshIterator< D >::begin(), Util::Log::file(), Pscf::Prdc::UnitCellBase< D >::ksq(), Pscf::MeshIterator< D >::position(), Pscf::MeshIterator< D >::rank(), Pscf::MeshIterator< D >::setDimensions(), and UTIL_CHECK.
outputValue()
template<int D> void Pscf::Rpc::FourthOrderParameter< D >::outputValue (int step, double value) virtual
Output a sampled or block average value.
Parameters
step value for step counter
value value of physical observable
Reimplemented from Pscf::Rpc::AverageAnalyzer< D >.
Definition at line 172 of file rpc/fts/analyzer/FourthOrderParameter.tpp.
References Pscf::Rpc::AverageAnalyzer< D >::outputValue(), and UTIL_CHECK.
computePrefactor()
template<int D> void Pscf::Rpc::FourthOrderParameter< D >::computePrefactor ()
Compute prefactor for each Fourier wavevector.
For the real-valued function W_, each Fourier coefficient G satisfies W_(G) = W_(-G). This function uses Brillouin Zone (BZ) indices representation. After applying fftw, if both the wavevector G and its inverse -G exist in k-space, the prefactor is assigned to be 1/2 for both G and -G. Otherwise, it is assigned to be 1.
Definition at line 188 of file rpc/fts/analyzer/FourthOrderParameter.tpp.
References Util::DArray< T >::allocate(), Pscf::MeshIterator< D >::atEnd(), Pscf::MeshIterator< D >::begin(), Pscf::Vec< D, T >::negate(), Pscf::MeshIterator< D >::position(), and Pscf::MeshIterator< D >::rank().
setClassName()
template<int D> void Util::ParamComposite::setClassName (const char * className) protected
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by Pscf::Rpc::FourthOrderParameter< D >::FourthOrderParameter().
The documentation for this class was generated from the following files:
rpc/fts/analyzer/FourthOrderParameter.h
rpc/fts/analyzer/FourthOrderParameter.tpp