PSCF: Pscf::Vertex Class Reference
Pscf::Vertex Class Reference
Pscf namespace » Pscf Common » Chemical Structure
A junction or chain end in a block polymer.
#include <Vertex.h>
Public Member Functions
Vertex ()
Constructor.
~Vertex ()
Destructor.
void setId (int id)
Set the integer identifier of this vertex.
void addEdge (Edge const &block)
Add block to the list of attached blocks.
int id () const
Get the id of this vertex.
int size () const
Get the number of attached blocks.
Pair< int > const & inPropagatorId (int i) const
Get the block and direction of an incoming propagator.
Pair< int > const & outPropagatorId (int i) const
Get the block and direction of an outgoing propagator.
Detailed Description
A junction or chain end in a block polymer.
A vertex represents a vertex within the graph associated with a linear or acyclic branched polymer. Each vertex is either a free end of a block or a junction at which two or more blocks (or edges) are connected.
Definition at line 30 of file Vertex.h.
Constructor & Destructor Documentation
Vertex()
Pscf::Vertex::Vertex ()
Constructor.
Definition at line 18 of file Vertex.cpp.
~Vertex()
Pscf::Vertex::~Vertex ()
Destructor.
Definition at line 27 of file Vertex.cpp.
Member Function Documentation
setId()
void Pscf::Vertex::setId (int id)
Set the integer identifier of this vertex.
Parameters
id identifier
Definition at line 34 of file Vertex.cpp.
References id().
addEdge()
void Pscf::Vertex::addEdge (Edge const & block)
Add block to the list of attached blocks.
Preconditions: The id for this vertex must have been set, vertex ids must have been set for the block, and the id of this vertex must match one of the ids for the two vertices attached to the block.
Parameters
block attached Edge object
Definition at line 40 of file Vertex.cpp.
References Pscf::Edge::id(), UTIL_THROW, and Pscf::Edge::vertexId().
id()
int Pscf::Vertex::id () const inline
Get the id of this vertex.
Definition at line 107 of file Vertex.h.
Referenced by setId().
size()
int Pscf::Vertex::size () const inline
Get the number of attached blocks.
Definition at line 110 of file Vertex.h.
References Util::GArray< Data >::size().
Referenced by Pscf::PolymerSpecies::makePaths(), Pscf::PolymerSpecies::makePlan(), Pscf::PolymerTmpl< Block >::solve(), and Pscf::R1d::FieldIo::writeVertexQ().
inPropagatorId()
Pair< int > const & Pscf::Vertex::inPropagatorId (int i) const inline
Get the block and direction of an incoming propagator.
The first element of the integer pair is the block id, and the second is a direction id which is 0 if this vertex is vertex 1 of the block, and 1 if this vertex is vertex 0.
Parameters
i index of incoming propagator
Returns
Pair<int> containing block index, direction index
Definition at line 114 of file Vertex.h.
Referenced by Pscf::PolymerSpecies::makePlan(), and Pscf::R1d::FieldIo::writeVertexQ().
outPropagatorId()
Pair< int > const & Pscf::Vertex::outPropagatorId (int i) const inline
Get the block and direction of an outgoing propagator.
The first element of the integer pair is the block id, and the second is a direction id which is 0 if this vertex is vertex 0 of the block, and 1 if this vertex is vertex 1.
Parameters
i index of incoming propagator
Returns
Pair<int> containing block index, direction index
Definition at line 118 of file Vertex.h.
Referenced by Pscf::PolymerSpecies::makePaths().
The documentation for this class was generated from the following files:
Vertex.h
Vertex.cpp