PSCF: Pscf::Prdc::Cuda::CField< D > Class Template Reference
Pscf::Prdc::Cuda::CField< D > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CUDA)
Field of complex values on a regular mesh, allocated on a GPU device.
#include <CField.h>
Public Member Functions
CField ()
Default constructor.
CField (IntVec< D > const &meshDimensions)
Allocating constructor.
CField (CField const &other)
Copy constructor.
virtual ~CField ()
Destructor.
CField< D > & operator= (CField< D > const &other)
Assignment operator, assignment from another CField<D>.
CField< D > & operator= (HostDArray< cudaComplex > const &other)
Assignment operator, assignment from a HostDArray<cudaComplex>.
void allocate (IntVec< D > const &meshDimensions)
Allocate the underlying C array for data on a regular mesh.
void associate (DeviceArray< cudaComplex > &arr, int beginId, IntVec< D > const &meshDimensions)
Associate this object with a slice of another DeviceArray.
IntVec< D > const & meshDimensions () const
Return mesh dimensions by constant reference.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize a Field to/from an Archive.
Public Member Functions inherited from Pscf::DeviceArray< cudaComplex >
DeviceArray ()
Default constructor.
virtual ~DeviceArray ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array on the device.
void associate (DeviceArray< cudaComplex > &arr, int beginId, int capacity)
Associate this object with a slice of a different DeviceArray.
void deallocate ()
Dellocate the underlying C array.
void dissociate ()
Dissociate this object from the associated array.
virtual DeviceArray< cudaComplex > & operator= (const DeviceArray< cudaComplex > &other)
Assignment operator, assign from another DeviceArray<Data> array.
int capacity () const
Return allocated capacity.
bool isAllocated () const
Return true if the array has been allocated, false otherwise.
bool isOwner () const
Does this object own the underlying data?
cudaComplex * cArray ()
Return pointer to underlying C array.
Additional Inherited Members
Public Types inherited from Pscf::DeviceArray< cudaComplex >
typedef cudaComplex ElementType
Data type of each element.
Protected Attributes inherited from Pscf::DeviceArray< cudaComplex >
cudaComplex * dataPtr_
Pointer to a C array of Data elements on the GPU device.
int capacity_
Allocated size (capacity) of the array.
DeviceArray< cudaComplex > const * ownerPtr_
Pointer to array that owns this data, if isOwner_ == false.
int ownerCapacity_
Capacity of parent array, if isOwner_ == false.
cudaComplex const * ownerDataPtr_
Const pointer to parent array, if isOwner_ == false.
Detailed Description
template<int D>
class Pscf::Prdc::Cuda::CField< D >
Field of complex values on a regular mesh, allocated on a GPU device.
Definition at line 30 of file cuda/CField.h.
Constructor & Destructor Documentation
CField() [1/3]
template<int D> Pscf::Prdc::Cuda::CField< D >::CField ()
Default constructor.
References meshDimensions().
Referenced by CField(), CField(), operator=(), and operator=().
CField() [2/3]
template<int D> Pscf::Prdc::Cuda::CField< D >::CField (IntVec< D > const & meshDimensions)
Allocating constructor.
Calls allocate(meshDimension) internally.
Parameters
meshDimensions numbers of grid points in each dimension
Definition at line 32 of file cuda/CField.tpp.
References Pscf::Prdc::Cpu::CField< D >::allocate(), CField(), Pscf::DeviceArray< cudaComplex >::DeviceArray(), and meshDimensions().
CField() [3/3]
template<int D> Pscf::Prdc::Cuda::CField< D >::CField (CField< D > const & other)
Copy constructor.
Allocates new memory and copies all elements by value.
Parameters
other the CField to be copied.
References CField().
~CField()
template<int D> virtual Pscf::Prdc::Cuda::CField< D >::~CField () virtual
Destructor.
Deletes underlying C array, if allocated previously.
Member Function Documentation
operator=() [1/2]
template<int D> CField< D > & Pscf::Prdc::Cuda::CField< D >::operator= (CField< D > const & other)
Assignment operator, assignment from another CField<D>.
Performs a deep copy, by copying all elements of the RHS CField<D> from device memory to device memory.
The RHS CField must be allocated. If this LHS CField is not allocated on entry, allocate it before copying elements. If both LHS and RHS objects are allocated on entry, the capacities must be equal.
Parameters
other the RHS CField<D>
References CField().
operator=() [2/2]
template<int D> CField< D > & Pscf::Prdc::Cuda::CField< D >::operator= (HostDArray< cudaComplex > const & other)
Assignment operator, assignment from a HostDArray<cudaComplex>.
Performs a deep copy, by copying all elements of the RHS CField<D> from host memory to device memory.
The RHS HostDArray<cudaComplex> and LHS CField<D> must both be allocated with equal capacity values on entry.
Parameters
other the RHS HostDArray<cudaComplex>
Definition at line 70 of file cuda/CField.tpp.
References Util::Array< Data >::capacity(), Pscf::DeviceArray< cudaComplex >::capacity_, CField(), Pscf::DeviceArray< cudaComplex >::isAllocated(), Util::DArray< Data >::isAllocated(), Pscf::DeviceArray< Data >::operator=(), and UTIL_THROW.
allocate()
template<int D> void Pscf::Prdc::Cuda::CField< D >::allocate (IntVec< D > const & meshDimensions)
Allocate the underlying C array for data on a regular mesh.
Exceptions
Exception if the CField is already allocated.
Parameters
meshDimensions number of grid points in each dimension
References associate(), Pscf::DeviceArray< cudaComplex >::DeviceArray(), and meshDimensions().
Referenced by serialize().
associate()
template<int D> void Pscf::Prdc::Cuda::CField< D >::associate (DeviceArray< cudaComplex > & arr, int beginId, IntVec< D > const & meshDimensions)
Associate this object with a slice of another DeviceArray.
Exceptions
Exception if the array is already allocated.
Parameters
arr parent array that owns the data
beginId index in the parent array at which this array starts
meshDimensions number of grid points in each dimension
Definition at line 108 of file cuda/CField.tpp.
References Pscf::DeviceArray< Data >::associate(), Pscf::DeviceArray< cudaComplex >::DeviceArray(), meshDimensions(), and UTIL_CHECK.
Referenced by allocate(), and serialize().
meshDimensions()
template<int D> IntVec< D > const & Pscf::Prdc::Cuda::CField< D >::meshDimensions () const
Return mesh dimensions by constant reference.
Referenced by allocate(), associate(), CField(), and CField().
serialize()
template<int D> template<class Archive> void Pscf::Prdc::Cuda::CField< D >::serialize (Archive & ar, const unsigned int version)
Serialize a Field to/from an Archive.
Parameters
ar archive
version archive version id
References allocate(), associate(), and Pscf::DeviceArray< cudaComplex >::DeviceArray().
The documentation for this class was generated from the following files:
cuda/CField.h
cuda/CField.tpp