PSCF: Pscf::Fd1d::FieldIo Class Reference
Pscf::Fd1d::FieldIo Class Reference
Pscf namespace » Finite-Difference 1D
Read and write fields to file.
#include <FieldIo.h>
Public Member Functions
FieldIo ()
Default constructor.
FieldIo (System &system)
Constructor.
~FieldIo ()
Destructor.
void readFields (Array< Field > &fields, std::istream &in)
Read a set of fields, one per monomer type.
void readFields (Array< Field > &fields, std::string const &filename)
Read a set of fields, one per monomer type.
void writeFields (Array< Field > const &fields, std::ostream &out)
Write a set of fields, one per monomer type.
void writeFields (Array< Field > const &fields, std::string const &filename)
Write a set of fields, one per monomer type.
void writeBlockCFields (std::ostream &out)
Write block concentration fields for all blocks.
void writeBlockCFields (std::string const &filename)
Write block concentration fields for all blocks.
void writeVertexQ (int polymerId, int vertexId, std::ostream &out)
Write incoming q fields for a specified vertex.
void writeVertexQ (int polymerId, int vertexId, std::string const &filename)
Write incoming q fields for a specified vertex.
void remesh (Array< Field > const &fields, int nx, std::ostream &out)
Interpolate an array of fields onto a new mesh.
void remesh (Array< Field > const &fields, int nx, std::string const &filename)
Interpolate an array of fields onto a new mesh and write to file.
void extend (Array< Field > const &fields, int m, std::ostream &out)
Add points to the end of mesh.
void extend (Array< Field > const &fields, int m, std::string const &filename)
Add points to the end of mesh.
Public Member Functions inherited from Pscf::Fd1d::SystemAccess
SystemAccess ()
Default constructor.
SystemAccess (System &system)
Constructor.
~SystemAccess ()
Destructor.
virtual void setSystem (System &system)
Set the system after construction.
const System & system () const
Get parent System by reference.
System & system ()
Get parent System by reference.
const Mixture & mixture () const
Get Mixture by reference.
Mixture & mixture ()
Get Mixture by reference.
const Domain & domain () const
Get spatial domain (including grid info) by reference.
Domain & domain ()
Get spatial domain (including grid info) by reference.
const Interaction & interaction () const
Get interaction (i.e., excess free energy model) by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
const Homogeneous::Mixture & homogeneous () const
Get homogeneous mixture (for reference calculations).
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
DArray< System::WField > & wFields ()
Get array of all chemical potential fields.
System::WField & wField (int monomerId)
Get chemical potential field for a specific monomer type.
DArray< System::CField > & cFields ()
Get array of all chemical potential fields.
System::CField & cField (int monomerId)
Get chemical potential field for a specific monomer type.
Detailed Description
Read and write fields to file.
Definition at line 23 of file fd1d/misc/FieldIo.h.
Constructor & Destructor Documentation
Pscf::Fd1d::FieldIo::FieldIo ()
Default constructor.
Definition at line 29 of file fd1d/misc/FieldIo.cpp.
Pscf::Fd1d::FieldIo::FieldIo (System & system)
Constructor.
Definition at line 36 of file fd1d/misc/FieldIo.cpp.
Pscf::Fd1d::FieldIo::~FieldIo ()
Destructor.
Definition at line 43 of file fd1d/misc/FieldIo.cpp.
Member Function Documentation
void Pscf::Fd1d::FieldIo::readFields (Array< Field > & fields, std::istream & in)
Read a set of fields, one per monomer type.
Precondition
File in must be open for reading.
Parameters
fields array of fields to read, indexed by monomer id
in input stream, open for reading.
Definition at line 56 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Fd1d::SystemAccess::mixture(), and UTIL_CHECK.
Referenced by Pscf::Fd1d::System::readCommands(), and readFields().
void Pscf::Fd1d::FieldIo::readFields (Array< Field > & fields, std::string const & filename)
Read a set of fields, one per monomer type.
This function uses the system FileMaster to opens and close a input file named filename.
Parameters
fields array of fields to read, indexed by monomer id.
filename name of input file
Definition at line 47 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::fileMaster(), Util::FileMaster::openInputFile(), and readFields().
void Pscf::Fd1d::FieldIo::writeFields (Array< Field > const & fields, std::ostream & out)
Write a set of fields, one per monomer type.
Precondition
Stream out must be open for writing.
Parameters
fields set of fields to written.
out output stream
Definition at line 92 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), and Pscf::Fd1d::Domain::nx().
Referenced by Pscf::Fd1d::Sweep::outputSolution(), Pscf::Fd1d::System::readCommands(), and writeFields().
void Pscf::Fd1d::FieldIo::writeFields (Array< Field > const & fields, std::string const & filename)
Write a set of fields, one per monomer type.
This function uses the system FileMaster to opens and close a output file named filename.
Parameters
fields array of fields to read, indexed by monomer id
filename output filename
Definition at line 83 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::fileMaster(), Util::FileMaster::openOutputFile(), and writeFields().
void Pscf::Fd1d::FieldIo::writeBlockCFields (std::ostream & out)
Write block concentration fields for all blocks.
Precondition
Stream out must be open for writing.
Parameters
out output stream
Definition at line 121 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::Fd1d::Domain::nx(), and Pscf::MixtureTmpl< TP, TS >::polymer().
Referenced by Pscf::Fd1d::System::readCommands(), and writeBlockCFields().
void Pscf::Fd1d::FieldIo::writeBlockCFields (std::string const & filename)
Write block concentration fields for all blocks.
This function uses the system FileMaster to opens and close a output file named filename.
Parameters
filename name of output file
Definition at line 110 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::fileMaster(), Util::FileMaster::openOutputFile(), and writeBlockCFields().
void Pscf::Fd1d::FieldIo::writeVertexQ (int polymerId, int vertexId, std::ostream & out)
Write incoming q fields for a specified vertex.
Precondition
Stream out must be open for writing.
Parameters
polymerId integer id of polymer species
vertexId integer id of vertex (end or junction)
out output stream
Definition at line 156 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Vertex::inPropagatorId(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::Fd1d::Domain::nx(), Pscf::MixtureTmpl< TP, TS >::polymer(), Util::product(), Pscf::PolymerTmpl< Block >::propagator(), Pscf::Vertex::size(), and Pscf::PolymerTmpl< Block >::vertex().
Referenced by Pscf::Fd1d::System::readCommands(), and writeVertexQ().
void Pscf::Fd1d::FieldIo::writeVertexQ (int polymerId, int vertexId, std::string const & filename)
Write incoming q fields for a specified vertex.
Parameters
polymerId integer id of polymer species
vertexId integer id of vertex (end or junction)
filename name of output file
Definition at line 144 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::fileMaster(), Util::FileMaster::openOutputFile(), and writeVertexQ().
void Pscf::Fd1d::FieldIo::remesh (Array< Field > const & fields, int nx, std::ostream & out)
Interpolate an array of fields onto a new mesh.
Parameters
fields field to be remeshed
nx number of grid points in new mesh
out output stream for remeshed field
Definition at line 197 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Fd1d::Domain::dx(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::Fd1d::Domain::nx(), Pscf::Fd1d::Domain::xMax(), and Pscf::Fd1d::Domain::xMin().
Referenced by Pscf::Fd1d::System::readCommands(), and remesh().
void Pscf::Fd1d::FieldIo::remesh (Array< Field > const & fields, int nx, std::string const & filename)
Interpolate an array of fields onto a new mesh and write to file.
Parameters
fields field to be remeshed
nx number of grid points in new mesh
filename name of output file for remeshed field
Definition at line 184 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::fileMaster(), Util::FileMaster::openOutputFile(), and remesh().
void Pscf::Fd1d::FieldIo::extend (Array< Field > const & fields, int m, std::ostream & out)
Add points to the end of mesh.
Parameters
fields array of fields to be extended
m number of added grid points
out output stream for extended field
Definition at line 260 of file fd1d/misc/FieldIo.cpp.
References Pscf::Fd1d::SystemAccess::domain(), Pscf::Fd1d::SystemAccess::mixture(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), and Pscf::Fd1d::Domain::nx().
Referenced by extend(), and Pscf::Fd1d::System::readCommands().
void Pscf::Fd1d::FieldIo::extend (Array< Field > const & fields, int m, std::string const & filename)
Add points to the end of mesh.
Parameters
fields field to be remeshed
m number of added grid points
filename name of output file for remeshed field
Definition at line 247 of file fd1d/misc/FieldIo.cpp.
References extend(), Pscf::Fd1d::SystemAccess::fileMaster(), and Util::FileMaster::openOutputFile().
The documentation for this class was generated from the following files:
fd1d/misc/FieldIo.h
fd1d/misc/FieldIo.cpp