PSCF: ParamFileTest Class Reference
ParamFileTest Class Reference
Unit Test Framework
A UnitTest with a built-in input file.
#include <ParamFileTest.h>
Public Member Functions
ParamFileTest ()
Constructor.
~ParamFileTest ()
Destructor.
virtual void tearDown ()
Close the input file.
void openFile (const char *fileName)
Open the input file.
void closeFile ()
Close the input file.
std::ifstream & file ()
Returns input file by reference.
Public Member Functions inherited from UnitTest
UnitTest ()
Constructor.
virtual ~UnitTest ()
Destructor.
virtual void setUp ()
Set up before each test method (empty default implementation).
void setVerbose (int verbose)
Set verbosity level.
void setFilePrefix (const std::string &prefix)
Set file prefix.
const std::string & filePrefix ()
Get file prefix string.
bool isIoProcessor () const
Should this processor read and write to file?
Additional Inherited Members
Protected Member Functions inherited from UnitTest
void printMethod (const char *methodName)
Write name of a class method, iff ioProcessor.
void printEndl ()
Write carriage return, iff isIoProcessor.
virtual void endMarker ()
Print a line of hashes, iff isIoProcessor.
void openInputFile (const std::string &name, std::ifstream &in) const
Open C++ input file ifstream.
void openOutputFile (const std::string &name, std::ofstream &out) const
Open C++ output file ofstream.
FILE * openFile (const std::string &name, const char *mode) const
Open C file handle with specified mode.
int verbose () const
Return integer verbosity level (0 == silent).
Static Protected Member Functions inherited from UnitTest
static bool eq (int s1, int s2)
Return true if two integers are equal.
static bool eq (double s1, double s2)
Return true if two double precision floats are equal.
Detailed Description
A UnitTest with a built-in input file.
Definition at line 15 of file ParamFileTest.h.
Constructor & Destructor Documentation
ParamFileTest()
ParamFileTest::ParamFileTest () inline
Constructor.
Definition at line 23 of file ParamFileTest.h.
~ParamFileTest()
ParamFileTest::~ParamFileTest () inline
Destructor.
Definition at line 30 of file ParamFileTest.h.
References closeFile().
Member Function Documentation
tearDown()
virtual void ParamFileTest::tearDown () inline virtual
Close the input file.
Reimplemented from UnitTest.
Definition at line 36 of file ParamFileTest.h.
References closeFile().
openFile()
void ParamFileTest::openFile (const char * fileName) inline
Open the input file.
Definition at line 42 of file ParamFileTest.h.
References UnitTest::isIoProcessor(), and UnitTest::openInputFile().
closeFile()
void ParamFileTest::closeFile () inline
Close the input file.
Definition at line 52 of file ParamFileTest.h.
Referenced by tearDown(), and ~ParamFileTest().
file()
std::ifstream & ParamFileTest::file () inline
Returns input file by reference.
Definition at line 58 of file ParamFileTest.h.
The documentation for this class was generated from the following file:
ParamFileTest.h