PSCF: Pscf::Rpg::LrAmPreCompressor< D > Class Template Reference
Pscf::Rpg::LrAmPreCompressor< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Field Theoretic Simulation (FTS) » Compressors
Anderson Mixing compressor with linear-response preconditioning.
#include <LrAmPreCompressor.h>
Public Member Functions
LrAmPreCompressor (System< D > &system)
Constructor.
~LrAmPreCompressor ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
void setup (bool isContinuation)
Initialize just before entry to iterative loop.
int compress ()
Compress to obtain partial saddle point w+.
void outputTimers (std::ostream &out)
Write a report of time contributions used by this algorithm.
void clearTimers ()
Reset / clear all timers.
double computeError (DeviceArray< cudaReal > &residTrial, DeviceArray< cudaReal > &fieldTrial, std::string errorType, int verbose)
Compute and return error used to test for convergence.
Public Member Functions inherited from Pscf::AmIteratorTmpl< Compressor< D >, DeviceArray< cudaReal > >
AmIteratorTmpl ()
Constructor.
~AmIteratorTmpl ()
Destructor.
void readParameters (std::istream &in)
Read all parameters and initialize.
int solve (bool isContinuation=false)
Iterate to a solution.
void outputTimers (std::ostream &out)
Log output timing results.
void clearTimers ()
Clear timers.
std::string errorType () const
Obtain error type.
Protected Member Functions
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Protected Member Functions inherited from Pscf::AmIteratorTmpl< Compressor< D >, DeviceArray< cudaReal > >
void setMaxItr (int maxItr)
Set value of maxItr.
void setMaxHist (int maxHist)
Set value of maxHist (number of retained previous states)
void setErrorType (std::string errorType)
Set and validate value of errorType string.
void readErrorType (std::istream &in)
Read and validate the optional errorType string parameter.
virtual bool isValidErrorType ()
Checks if a string is a valid error type.
virtual double norm (DeviceArray< cudaReal > const &hist)
Find the L2 norm of a vector.
void allocateAM ()
Allocate memory required by AM algorithm, if necessary.
virtual void clear ()
Clear information about history.
virtual double computeError (DeviceArray< cudaReal > &residTrial, DeviceArray< cudaReal > &fieldTrial, std::string errorType, int verbose)
Compute and return error used to test for convergence.
double computeError (int verbose)
Compute and return error used to test for convergence.
DeviceArray< cudaReal > const & residual () const
Return the current residual vector by const reference.
DeviceArray< cudaReal > const & field () const
Return the current field or state vector by const reference.
int verbose () const
Verbosity level, allowed values 0, 1, or 2.
int totalItr ()
Return the total number of iterations needed to converge.
double timerTotal ()
Get total time.
double timerMDE ()
Get time solving modified diffusion equation (MDE).
double timerAM ()
Get total time for AM algorithm, excluding MDE solution.
double timerResid ()
Get time computing residual.
double timerError ()
Get time evaluating scalar error.
double timerCoeff ()
Get time evaluating Anderson mixing coefficients.
double timerOmega ()
Get time updating w fields.
bool isAllocatedAM () const
Have data structures required by the AM algorithm been allocated?
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
Additional Inherited Members
Protected Attributes inherited from Pscf::AmIteratorTmpl< Compressor< D >, DeviceArray< cudaReal > >
std::string errorType_
Type of error criterion used to test convergence.
Detailed Description
template<int D>
class Pscf::Rpg::LrAmPreCompressor< D >
Anderson Mixing compressor with linear-response preconditioning.
Class LrAmPreCompressor implements an Anderson mixing algorithm in which the residual is defined using a preconditioning scheme that would yield a Jacobian of unity if applied to a homogeneous system. The residual in the unpreconditioned form of Anderson mixing is a vector in which each that represents a deviations in the sum of volume fractions from unity. In this preconditioned algorithm, each Fourier component of this deviation is multiplied by the inverse of Fourier representation of the linear response of total concentration to changes in pressure in a homogeneous system of the same chemical composition as the system of interest.
Definition at line 47 of file LrAmPreCompressor.h.
Constructor & Destructor Documentation
LrAmPreCompressor()
template<int D> Pscf::Rpg::LrAmPreCompressor< D >::LrAmPreCompressor (System< D > & system)
Constructor.
Parameters
system System object associated with this compressor.
Definition at line 28 of file LrAmPreCompressor.tpp.
~LrAmPreCompressor()
template<int D> Pscf::Rpg::LrAmPreCompressor< D >::~LrAmPreCompressor ()
Destructor.
Definition at line 37 of file LrAmPreCompressor.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Rpg::LrAmPreCompressor< D >::readParameters (std::istream & in)
Read all parameters and initialize.
Parameters
in input filestream
Definition at line 42 of file LrAmPreCompressor.tpp.
setup()
template<int D> void Pscf::Rpg::LrAmPreCompressor< D >::setup (bool isContinuation) virtual
Initialize just before entry to iterative loop.
This function is called by the solve function before entering the loop over iterations. Store the current values of the fields at the beginning of iteration
Parameters
isContinuation true iff continuation within a sweep
Reimplemented from Pscf::AmIteratorTmpl< Compressor< D >, DeviceArray< cudaReal > >.
Definition at line 51 of file LrAmPreCompressor.tpp.
References Pscf::Prdc::Cuda::VecOp::eqV().
compress()
template<int D> int Pscf::Rpg::LrAmPreCompressor< D >::compress ()
Compress to obtain partial saddle point w+.
Returns
0 for convergence, 1 for failure
Definition at line 106 of file LrAmPreCompressor.tpp.
outputTimers()
template<int D> void Pscf::Rpg::LrAmPreCompressor< D >::outputTimers (std::ostream & out)
Write a report of time contributions used by this algorithm.
Parameters
out output stream to which to write
Definition at line 258 of file LrAmPreCompressor.tpp.
clearTimers()
template<int D> void Pscf::Rpg::LrAmPreCompressor< D >::clearTimers ()
Reset / clear all timers.
Definition at line 268 of file LrAmPreCompressor.tpp.
computeError()
template<int D> double Pscf::Rpg::LrAmPreCompressor< D >::computeError (DeviceArray< cudaReal > & residTrial, DeviceArray< cudaReal > & fieldTrial, std::string errorType, int verbose)
Compute and return error used to test for convergence.
Parameters
residTrial current residual vector
fieldTrial current field vector
errorType type of error
verbose verbosity level of output report.
Returns
error measure used to test for convergence.
Definition at line 281 of file LrAmPreCompressor.tpp.
References Pscf::Prdc::Cuda::VecOp::addEqV(), Util::Log::file(), Pscf::Prdc::Cuda::VecOp::subVS(), UTIL_CHECK, and UTIL_THROW.
readOptional()
template<int D> template<typename Type > ScalarParam< Type > & Util::ParamComposite::readOptional (std::istream & in, const char * label, Type & value) inline protected
Add and read a new optional ScalarParam < Type > object.
This is equivalent to ScalarParam<Type>(in, label, value, false).
Parameters
in input stream for reading
label Label string
value reference to new ScalarParam< Type >
Definition at line 319 of file ParamComposite.h.
The documentation for this class was generated from the following files:
LrAmPreCompressor.h
LrAmPreCompressor.tpp