PSCF: Util::Begin Class Reference
Util::Begin Class Reference
Util namespace » Parameter File IO
Beginning line of a composite parameter block.
#include <Begin.h>
Public Member Functions
Begin (const char *label, bool isRequired=true)
Constructor.
virtual void readParam (std::istream &in)
Read the opening line.
virtual void writeParam (std::ostream &out) const
Write the opening line.
bool isRequired () const
Is this the beginning line for a required element?
bool isActive () const
Is this an active element (has it been read from file)?
virtual void resetParam ()
Do-nothing implementation of virtual resetParam function.
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
virtual void load (Serializable::IArchive &ar)
Load internal state from an archive.
virtual void save (Serializable::OArchive &ar)
Save internal state to an archive.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Detailed Description
Beginning line of a composite parameter block.
Definition at line 24 of file Begin.h.
Constructor & Destructor Documentation
Begin()
Util::Begin::Begin (const char * label, bool isRequired = true)
Constructor.
Definition at line 21 of file Begin.cpp.
References isRequired().
Member Function Documentation
readParam()
void Util::Begin::readParam (std::istream & in) virtual
Read the opening line.
Parameters
in input stream
Implements Util::ParamComponent.
Definition at line 33 of file Begin.cpp.
References Util::ParamComponent::echo(), Util::Log::file(), Util::ParamComponent::indent(), Util::Label::isClear(), Util::MpiFileIo::isIoProcessor(), isRequired(), UTIL_THROW, and writeParam().
Referenced by Util::ParamComposite::readBegin().
writeParam()
void Util::Begin::writeParam (std::ostream & out) const virtual
Write the opening line.
Parameters
out output stream
Implements Util::ParamComponent.
Definition at line 80 of file Begin.cpp.
References Util::ParamComponent::indent().
Referenced by Util::ParamComposite::load(), Util::Factory< Data >::readObject(), and readParam().
isRequired()
bool Util::Begin::isRequired () const inline
Is this the beginning line for a required element?
Definition at line 78 of file Begin.h.
References Util::Label::isRequired().
Referenced by Begin(), and readParam().
isActive()
bool Util::Begin::isActive () const inline
Is this an active element (has it been read from file)?
Definition at line 84 of file Begin.h.
Referenced by Util::Manager< Data >::beginReadManager(), Util::ParamComposite::readBegin(), and Util::ParamComposite::readParamOptional().
resetParam()
void Util::Begin::resetParam () virtual
Do-nothing implementation of virtual resetParam function.
Reimplemented from Util::ParamComponent.
Definition at line 86 of file Begin.cpp.
The documentation for this class was generated from the following files:
Begin.h
Begin.cpp