PSCF: Pscf::Homogeneous::Clump Class Reference
Pscf::Homogeneous::Clump Class Reference
Pscf namespace » Pscf Common » Homogeneous Mixtures
Collection of all monomers of a single type in a molecule.
#include <Clump.h>
Public Member Functions
Clump ()
Constructor.
template<class Archive >
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
Setters
void setMonomerId (int monomerId)
Set the monomer id.
void setSize (double size)
Set the size of this block.
Accessors (getters)
int monomerId () const
Get the monomer type id.
double size () const
Get the size (number of monomers) in this block.
Friends
std::istream & operator>> (std::istream &in, Clump &block)
istream extractor for a Clump.
std::ostream & operator<< (std::ostream &out, const Clump &block)
ostream inserter for a Clump.
Detailed Description
Collection of all monomers of a single type in a molecule.
A clump has a monomer id and a size. The size of a clump is the volume occupied by all monomers of the specified type in a particular molecular species, divided by a monomer reference volume.
For a block copolymer, a clump is generally different than a block because a clump may include the monomers in two or more blocks of the same monomer type. Hompolymer and point solvent molecular species each have only one clump.
Definition at line 35 of file Clump.h.
Constructor & Destructor Documentation
Pscf::Homogeneous::Clump::Clump ()
Constructor.
Definition at line 16 of file Clump.cpp.
Member Function Documentation
template<class Archive > void Pscf::Homogeneous::Clump::serialize (Archive & ar, unsigned int versionId)
Serialize to/from archive.
Parameters
ar input or output Archive
versionId archive format version index
Definition at line 140 of file Clump.h.
void Pscf::Homogeneous::Clump::setMonomerId (int monomerId)
Set the monomer id.
Parameters
monomerId integer id of monomer type (>=0)
Definition at line 24 of file Clump.cpp.
References monomerId().
Referenced by Pscf::Fd1d::System::computeFreeEnergy(), Pscf::Pspc::System< D >::outputThermo(), and Pscf::Pspg::System< D >::readCommands().
void Pscf::Homogeneous::Clump::setSize (double size)
Set the size of this block.
The ``size" is steric volume / reference volume.
Parameters
size block size (number of monomers).
Definition at line 30 of file Clump.cpp.
References size().
Referenced by Pscf::Fd1d::System::computeFreeEnergy(), Pscf::Pspc::System< D >::outputThermo(), and Pscf::Pspg::System< D >::readCommands().
int Pscf::Homogeneous::Clump::monomerId () const inline
Get the monomer type id.
Definition at line 127 of file Clump.h.
Referenced by Pscf::Homogeneous::Mixture::computeMu(), Pscf::Homogeneous::Mixture::computePhi(), Pscf::Homogeneous::Mixture::setComposition(), setMonomerId(), and Pscf::Homogeneous::Mixture::validate().
double Pscf::Homogeneous::Clump::size () const inline
Get the size (number of monomers) in this block.
Definition at line 133 of file Clump.h.
Referenced by Pscf::Homogeneous::Mixture::computeMu(), Pscf::Homogeneous::Mixture::computePhi(), Pscf::Homogeneous::Mixture::setComposition(), and setSize().
Friends And Related Function Documentation
std::istream& operator>> (std::istream & in, Clump & block) friend
istream extractor for a Clump.
Parameters
in input stream
block Clump to be read from stream
Returns
modified input stream
Definition at line 36 of file Clump.cpp.
std::ostream& operator<< (std::ostream & out, const Clump & block) friend
ostream inserter for a Clump.
Parameters
out output stream
block Clump to be written to stream
Returns
modified output stream
Definition at line 46 of file Clump.cpp.
The documentation for this class was generated from the following files:
Clump.h
Clump.cpp