PSCF: Pscf::Rpg::FilmFieldGenMask< D > Class Template Reference
Pscf::Rpg::FilmFieldGenMask< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Fields
Field Generator for thin-film masks.
#include <FilmFieldGenMask.h>
Public Member Functions
FilmFieldGenMask ()
Default constructor.
FilmFieldGenMask (System< D > &sys)
Constructor.
~FilmFieldGenMask ()
Destructor.
double stress (int paramId) const
Get contribution to the stress from this mask.
double modifyStress (int paramId, double stress) const
Modify stress value in direction normal to the film.
Public Member Functions inherited from Pscf::Prdc::FilmFieldGenMaskBase< D >
FilmFieldGenMaskBase ()
Constructor.
~FilmFieldGenMaskBase ()
Destructor.
void readParameters (std::istream &in)
Read parameter file block and initialize.
bool needsUpdate () const
Check whether system has changed such that the field needs updating.
void checkCompatibility ()
Check that the system is compatible with this field.
int normalVecId () const
Get value of normalVecId.
double interfaceThickness () const
Get value of interfaceThickness.
double excludedThickness () const
Get value of excludedThickness.
double fBulk () const
Get value of fBulk.
bool hasFBulk () const
Check whether a value of fBulk was provided.
Public Member Functions inherited from Pscf::Prdc::FieldGenerator
FieldGenerator ()
Constructor.
~FieldGenerator ()
Destructor.
Public Member Functions inherited from Pscf::FieldGeneratorBase
FieldGeneratorBase ()
Constructor.
~FieldGeneratorBase ()
Destructor.
void generate ()
Checks if fields need to be (re)generated.
Type type () const
Return Type enumeration value (Mask, External, or None)
bool isDependent () const
Is this object dependent on parameters of another FieldGeneratorBase?
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type>
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type>
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type>
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type>
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type>
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type>
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type>
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type>
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type, int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type>
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type>
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type>
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
Public Member Functions inherited from Pscf::ParameterModifier
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
virtual GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to the Sweep object.
virtual void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
virtual double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Protected Member Functions
void compute ()
Compute the field and store where the System can access.
void setFlexibleParams () const
Modifies iterator().flexibleParams_ to be compatible with the mask.
System< D > & system ()
Get the System associated with this object by reference.
System< D > const & system () const
Get the System associated with this object by const reference.
std::string systemSpaceGroup () const
Get the space group name for this system.
RealVec< D > systemLatticeVector (int id) const
Get one of the lattice vectors for this system.
void setClassName (const char *className)
Set class name string.
Protected Member Functions inherited from Pscf::Prdc::FilmFieldGenMaskBase< D >
void checkSpaceGroup () const
Check that space group is compatible with the mask.
void checkLatticeVectors () const
Check that lattice vectors are compatible with thin film constraint.
FSArray< bool, 6 > modifyFlexibleParams (FSArray< bool, 6 > current, UnitCell< D > const &cell) const
Modifies a flexibleParams array to be compatible with this mask.
template<typename Type>
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type>
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type>
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type>
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type>
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type, int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type, int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type>
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type>
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Additional Inherited Members
Public Types inherited from Pscf::FieldGeneratorBase
enum Type
Enum representing the type of field (mask, external field, or none).
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Protected Attributes inherited from Pscf::Prdc::FilmFieldGenMaskBase< D >
RealVec< D > normalVecCurrent_
The lattice vector normal to the film used to generate these fields.
double fBulk_
Reference free energy used to calculate stress normal to the film.
Protected Attributes inherited from Pscf::FieldGeneratorBase
Type type_
Type of field (Mask, External, or None).
bool isDependent_
Is this object dependent on parameters of another FieldGeneratorBase?
Detailed Description
template<int D>
class Pscf::Rpg::FilmFieldGenMask< D >
Field Generator for thin-film masks.
The parent FilmFieldGenMaskBase class template defines all traits of a FilmFieldGenMask that do not require access to the System. This subclass defines all methods that need System access.
If a MixAndMatchEnv contains a FilmFieldGenMask, then the system will contain two parallel hard surfaces ("walls"), confining the polymers/solvents to a "thin film" region of the unit cell.
Definition at line 34 of file rpg/environment/FilmFieldGenMask.h.
Constructor & Destructor Documentation
FilmFieldGenMask() [1/2]
template<int D> Pscf::Rpg::FilmFieldGenMask< D >::FilmFieldGenMask ()
Default constructor.
Definition at line 151 of file rpg/environment/FilmFieldGenMask.tpp.
References Pscf::Prdc::FilmFieldGenMaskBase< D >::FilmFieldGenMaskBase(), and setClassName().
FilmFieldGenMask() [2/2]
template<int D> Pscf::Rpg::FilmFieldGenMask< D >::FilmFieldGenMask (System< D > & sys)
Constructor.
Parameters
sys System parent object
Definition at line 160 of file rpg/environment/FilmFieldGenMask.tpp.
References Pscf::Prdc::FilmFieldGenMaskBase< D >::FilmFieldGenMaskBase(), and setClassName().
~FilmFieldGenMask()
template<int D> Pscf::Rpg::FilmFieldGenMask< D >::~FilmFieldGenMask ()
Destructor.
Definition at line 169 of file rpg/environment/FilmFieldGenMask.tpp.
Member Function Documentation
stress()
template<int D> double Pscf::Rpg::FilmFieldGenMask< D >::stress (int paramId) const virtual
Get contribution to the stress from this mask.
The mask defined by this class changes in a non-affine manner upon changing the lattice parameter corresponding to normalVecId. Thus, if this lattice parameter is allowed to be flexible, the "stress" used to optimize the parameter must contain an additional contribution arising from the mask. This method evaluates this contribution and returns its value.
Parameters
paramId index of the lattice parameter being varied
Implements Pscf::Prdc::FilmFieldGenMaskBase< D >.
Definition at line 176 of file rpg/environment/FilmFieldGenMask.tpp.
References Pscf::Prdc::Cuda::VecOp::addEqVc(), Pscf::Prdc::Cpu::RField< D >::allocate(), Pscf::ThreadMesh::blockDims(), Util::Array< Data >::capacity(), Util::Array< Data >::cArray(), Pscf::Prdc::convertFullParamIdToReduced(), Pscf::Prdc::Cpu::VecOp::eqV(), Pscf::Prdc::FilmFieldGenMaskBase< D >::excludedThickness(), Pscf::ThreadMesh::gridDims(), Pscf::Prdc::Cpu::Reduce::innerProduct(), Pscf::Prdc::FilmFieldGenMaskBase< D >::interfaceThickness(), Pscf::ThreadMesh::meshDims(), Pscf::Prdc::FilmFieldGenMaskBase< D >::normalVecId(), Pscf::ThreadMesh::setConfig(), Pscf::Prdc::Cpu::VecOp::subVV(), system(), and UTIL_CHECK.
Referenced by modifyStress().
modifyStress()
template<int D> double Pscf::Rpg::FilmFieldGenMask< D >::modifyStress (int paramId, double stress) const virtual
Modify stress value in direction normal to the film.
The "stress" calculated by the System is used to minimize fHelmholtz with respect to a given lattice parameter. In a thin film it is useful to instead minimize the excess free energy per unit area, (fHelmholtz - fRef) * Delta, where fRef is a reference free energy and Delta is the film thickness. The information needed to perform such a modification is contained within this object. This method performs this modification. The stress will not be modified for lattice parameters that are parallel to the film.
Parameters
paramId index of the lattice parameter with this stress
stress stress value calculated by Mixture object
Implements Pscf::Prdc::FilmFieldGenMaskBase< D >.
Definition at line 241 of file rpg/environment/FilmFieldGenMask.tpp.
References Pscf::Prdc::convertFullParamIdToReduced(), Pscf::Prdc::FilmFieldGenMaskBase< D >::excludedThickness(), Pscf::Prdc::FilmFieldGenMaskBase< D >::fBulk_, Pscf::Prdc::FilmFieldGenMaskBase< D >::hasFBulk(), Pscf::Prdc::FilmFieldGenMaskBase< D >::normalVecId(), stress(), system(), UTIL_CHECK, and UTIL_THROW.
compute()
template<int D> void Pscf::Rpg::FilmFieldGenMask< D >::compute () protected virtual
Compute the field and store where the System can access.
Implements Pscf::Prdc::FilmFieldGenMaskBase< D >.
Definition at line 276 of file rpg/environment/FilmFieldGenMask.tpp.
References Pscf::Prdc::Cpu::RField< D >::allocate(), Pscf::ThreadMesh::blockDims(), Util::Array< Data >::cArray(), Pscf::Prdc::convertFullParamIdToReduced(), Pscf::Prdc::FilmFieldGenMaskBase< D >::excludedThickness(), Pscf::ThreadMesh::gridDims(), Pscf::Prdc::FilmFieldGenMaskBase< D >::interfaceThickness(), Pscf::ThreadMesh::meshDims(), Pscf::Prdc::FilmFieldGenMaskBase< D >::normalVecCurrent_, Pscf::Prdc::FilmFieldGenMaskBase< D >::normalVecId(), Pscf::ThreadMesh::setConfig(), system(), systemLatticeVector(), and UTIL_CHECK.
setFlexibleParams()
template<int D> void Pscf::Rpg::FilmFieldGenMask< D >::setFlexibleParams () const protected virtual
Modifies iterator().flexibleParams_ to be compatible with the mask.
Implements Pscf::Prdc::FilmFieldGenMaskBase< D >.
Definition at line 316 of file rpg/environment/FilmFieldGenMask.tpp.
References Pscf::Prdc::FilmFieldGenMaskBase< D >::modifyFlexibleParams(), and system().
system() [1/2]
template<int D> System< D > & Pscf::Rpg::FilmFieldGenMask< D >::system () protected
Get the System associated with this object by reference.
Definition at line 142 of file rpg/environment/FilmFieldGenMask.h.
Referenced by compute(), modifyStress(), setFlexibleParams(), stress(), systemLatticeVector(), and systemSpaceGroup().
system() [2/2]
template<int D> System< D > const & Pscf::Rpg::FilmFieldGenMask< D >::system () const protected
Get the System associated with this object by const reference.
Definition at line 147 of file rpg/environment/FilmFieldGenMask.h.
systemSpaceGroup()
template<int D> std::string Pscf::Rpg::FilmFieldGenMask< D >::systemSpaceGroup () const inline protected virtual
Get the space group name for this system.
Implements Pscf::Prdc::FilmFieldGenMaskBase< D >.
Definition at line 152 of file rpg/environment/FilmFieldGenMask.h.
References system().
systemLatticeVector()
template<int D> RealVec< D > Pscf::Rpg::FilmFieldGenMask< D >::systemLatticeVector (int id) const inline protected virtual
Get one of the lattice vectors for this system.
Parameters
id index of the desired lattice vector
Implements Pscf::Prdc::FilmFieldGenMaskBase< D >.
Definition at line 157 of file rpg/environment/FilmFieldGenMask.h.
References system().
Referenced by compute().
setClassName()
template<int D> void Util::ParamComposite::setClassName (const char * className) protected
Set class name string.
Should be set in subclass constructor.
Definition at line 900 of file ParamComposite.cpp.
Referenced by FilmFieldGenMask(), and FilmFieldGenMask().
The documentation for this class was generated from the following files:
rpg/environment/FilmFieldGenMask.h
rpg/environment/FilmFieldGenMask.tpp