PSCF: Util::GridArray< Data > Class Template Reference
Util::GridArray< Data > Class Template Reference
Util namespace » Container Templates » Object Arrays
Multi-dimensional array with the dimensionality of space.
#include <GridArray.h>
Public Member Functions
GridArray ()
Constructor.
GridArray (GridArray< Data > const &other)
Copy constructor.
~GridArray ()
Destructor.
GridArray< Data > & operator= (GridArray< Data > const &other)
Assignment.
void allocate (IntVector const &dimensions)
Allocate memory for a matrix.
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Serialize a GridArray to/from an Archive.
bool isAllocated () const
Return true if the GridArray has been allocated, false otherwise.
IntVector const & dimensions ()
Get all dimensions of array as an IntVector.
int dimension (int i) const
Get number of grid points along direction i.
int size () const
Get total number of grid points.
IntVector position (int rank) const
Get the position IntVector of a grid point with a specified rank.
int rank (IntVector const &position) const
Get the rank of a grid point with specified position.
bool isInGrid (int coordinate, int i) const
Is this 1D coordinate in range?
bool isInGrid (IntVector &position) const
Is this position within the grid?
int shift (int &coordinate, int i) const
Shift a periodic 1D coordinate into primary range.
IntVector shift (IntVector &position) const
Shift a periodic position into primary grid.
Data const & operator[] (int rank) const
Return element by const reference, indexed by 1D rank.
Data & operator[] (int rank)
Return element by reference, indexed by 1D rank.
Data const & operator() (IntVector const &position) const
Return element by const reference, indexed by IntVector position.
Data & operator() (IntVector const &position)
Return element by reference, indexed by IntVector position.
Detailed Description
template<typename Data>
class Util::GridArray< Data >
Multi-dimensional array with the dimensionality of space.
The memory for a GridArray is stored in a single one-dimensional C array. The subscript [] operator is overloaded to return an element indexed by a one-dimensional rank, and the () operator is overloaded to return an element indexed by an IntVector of grid coordinates.
Definition at line 28 of file GridArray.h.
Constructor & Destructor Documentation
GridArray() [1/2]
template<typename Data> Util::GridArray< Data >::GridArray () inline
Constructor.
Constructor (protected).
Definition at line 217 of file GridArray.h.
Referenced by GridArray(), and operator=().
GridArray() [2/2]
template<typename Data> Util::GridArray< Data >::GridArray (GridArray< Data > const & other)
Copy constructor.
Definition at line 242 of file GridArray.h.
References allocate(), GridArray(), isAllocated(), and UTIL_THROW.
~GridArray()
template<typename Data> Util::GridArray< Data >::~GridArray ()
Destructor.
Delete dynamically allocated C array, if allocated.
Definition at line 230 of file GridArray.h.
References Util::Memory::deallocate().
Member Function Documentation
operator=()
template<typename Data> GridArray< Data > & Util::GridArray< Data >::operator= (GridArray< Data > const & other)
Assignment.
Definition at line 273 of file GridArray.h.
References allocate(), GridArray(), isAllocated(), and UTIL_THROW.
allocate()
template<typename Data> void Util::GridArray< Data >::allocate (IntVector const & dimensions)
Allocate memory for a matrix.
Parameters
dimensions IntVector containing dimensions
Definition at line 313 of file GridArray.h.
References Util::Memory::allocate(), Util::Dimension, dimensions(), isAllocated(), and UTIL_THROW.
Referenced by GridArray(), operator=(), and serialize().
serialize()
template<class Data> template<class Archive> void Util::GridArray< Data >::serialize (Archive & ar, const unsigned int version)
Serialize a GridArray to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 337 of file GridArray.h.
References allocate(), dimensions(), and isAllocated().
isAllocated()
template<class Data> bool Util::GridArray< Data >::isAllocated () const inline
Return true if the GridArray has been allocated, false otherwise.
Definition at line 519 of file GridArray.h.
Referenced by allocate(), GridArray(), operator=(), and serialize().
dimensions()
template<typename Data> IntVector const & Util::GridArray< Data >::dimensions () inline
Get all dimensions of array as an IntVector.
Returns
IntVector containing number of elements in each direction.
Definition at line 358 of file GridArray.h.
Referenced by allocate(), and serialize().
dimension()
template<class Data> int Util::GridArray< Data >::dimension (int i) const inline
Get number of grid points along direction i.
Parameters
i index of Cartesian direction 0 <=i < 3.
Definition at line 365 of file GridArray.h.
size()
template<class Data> int Util::GridArray< Data >::size () const inline
Get total number of grid points.
Definition at line 372 of file GridArray.h.
position()
template<typename Data> IntVector Util::GridArray< Data >::position (int rank) const
Get the position IntVector of a grid point with a specified rank.
Parameters
rank integer rank of a grid point.
Returns
IntVector containing coordinates of specified point.
Definition at line 405 of file GridArray.h.
References Util::Dimension, position(), and rank().
Referenced by isInGrid(), operator()(), operator()(), position(), rank(), and shift().
rank()
template<typename Data> int Util::GridArray< Data >::rank (IntVector const & position) const inline
Get the rank of a grid point with specified position.
Parameters
position integer position of a grid point
Returns
integer rank of specified grid point
Definition at line 395 of file GridArray.h.
References position().
Referenced by operator()(), operator()(), operator[](), operator[](), and position().
isInGrid() [1/2]
template<typename Data> bool Util::GridArray< Data >::isInGrid (int coordinate, int i) const
Is this 1D coordinate in range?
Returns true iff 0 <= coordinate < dimension(i).
Parameters
coordinate coordinate value for direction i
i index for Cartesian direction
Definition at line 423 of file GridArray.h.
isInGrid() [2/2]
template<typename Data> bool Util::GridArray< Data >::isInGrid (IntVector & position) const
Is this position within the grid?
Returns true iff 0 <= coordinate[i] < dimension(i) for all i.
Parameters
position grid point position
Definition at line 437 of file GridArray.h.
References Util::Dimension, and position().
shift() [1/2]
template<typename Data> int Util::GridArray< Data >::shift (int & coordinate, int i) const
Shift a periodic 1D coordinate into primary range.
Upon return, the coordinate will be shifted to lie within the range 0 <= coordinate < dimension(i) by subtracting an integer multiple of dimension(i), giving coordinate - shift*dimension(i). The return value is the required integer ‘shift’.
Parameters
coordinate coordinate in Cartesian direction i.
i index of Cartesian direction, i >= 0.
Returns
multiple of dimension(i) subtracted from input value.
Definition at line 453 of file GridArray.h.
References shift().
Referenced by shift(), and shift().
shift() [2/2]
template<typename Data> IntVector Util::GridArray< Data >::shift (IntVector & position) const
Shift a periodic position into primary grid.
Upon return, each element of the parameter position is shifted to lie within the range 0 <= position[i] < dimension(i) by adding or subtracting an integer multiple of dimension(i). The IntVector of shift values is returned.
Parameters
position IntVector position within a grid.
Returns
IntVector of integer shifts.
Definition at line 469 of file GridArray.h.
References Util::Dimension, position(), and shift().
operator[]() [1/2]
template<typename Data> Data const & Util::GridArray< Data >::operator[] (int rank) const inline
Return element by const reference, indexed by 1D rank.
Parameters
rank 1D array index of element
Definition at line 482 of file GridArray.h.
References rank().
operator[]() [2/2]
template<typename Data> Data & Util::GridArray< Data >::operator[] (int rank) inline
Return element by reference, indexed by 1D rank.
Parameters
rank 1D rank of element
Definition at line 489 of file GridArray.h.
References rank().
operator()() [1/2]
template<typename Data> Data const & Util::GridArray< Data >::operator() (IntVector const & position) const inline
Return element by const reference, indexed by IntVector position.
Parameters
position IntVector of coordinates.
Definition at line 497 of file GridArray.h.
References position(), and rank().
operator()() [2/2]
template<typename Data> Data & Util::GridArray< Data >::operator() (IntVector const & position) inline
Return element by reference, indexed by IntVector position.
Parameters
position IntVector of coordinates.
Definition at line 505 of file GridArray.h.
References position(), and rank().
The documentation for this class was generated from the following file:
GridArray.h