PSCF: Pscf::Prdc::SystemConstRefTmpl< ST > Class Template Reference
Pscf::Prdc::SystemConstRefTmpl< ST > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » System Templates
Base class template for const access to an associated System.
#include <SystemConstRefTmpl.h>
Public Member Functions
SystemConstRefTmpl ()
Default constructor.
SystemConstRefTmpl (SystemT const &system)
Constructor.
~SystemConstRefTmpl ()
Destructor.
void associate (SystemT const &system)
Create associations with a system and its components.
SystemT const & system () const
Get the associated System.
MixtureT const & mixture () const
Get the Mixture.
InteractionT const & interaction () const
Get the Interaction.
DomainT const & domain () const
Get the Domain.
CFieldsT const & c () const
Get the concentration (c) field container.
WFieldsT const & w () const
Get the chemical potential (w) field container.
WFieldsT const & h () const
Get the external potential (h) field container.
MaskT const & mask () const
Get the mask.
FileMaster const & fileMaster () const
Get the FileMaster.
Detailed Description
template<class ST>
class Pscf::Prdc::SystemConstRefTmpl< ST >
Base class template for const access to an associated System.
A SystemConstRefTmpl holds read-only (const) pointers to an associated SystemT object (type parameter ST) and several of its primary components, for a model with real fields and periodic boundary conditions. Accessor functions return the system and its components as const references.
Definition at line 33 of file SystemConstRefTmpl.h.
Constructor & Destructor Documentation
SystemConstRefTmpl() [1/2]
template<class ST> Pscf::Prdc::SystemConstRefTmpl< ST >::SystemConstRefTmpl ()
Default constructor.
Definition at line 20 of file SystemConstRefTmpl.tpp.
Referenced by Pscf::Prdc::ScftThermoTmpl< D, ST >::ScftThermoTmpl().
SystemConstRefTmpl() [2/2]
template<class ST> Pscf::Prdc::SystemConstRefTmpl< ST >::SystemConstRefTmpl (SystemT const & system)
Constructor.
Definition at line 36 of file SystemConstRefTmpl.tpp.
References associate(), and system().
~SystemConstRefTmpl()
template<class ST> Pscf::Prdc::SystemConstRefTmpl< ST >::~SystemConstRefTmpl ()
Destructor.
Definition at line 52 of file SystemConstRefTmpl.tpp.
Member Function Documentation
associate()
template<class ST> void Pscf::Prdc::SystemConstRefTmpl< ST >::associate (SystemT const & system)
Create associations with a system and its components.
Definition at line 56 of file SystemConstRefTmpl.tpp.
References system().
Referenced by SystemConstRefTmpl().
system()
template<class ST> SystemT const & Pscf::Prdc::SystemConstRefTmpl< ST >::system () const inline
Get the associated System.
Definition at line 71 of file SystemConstRefTmpl.h.
Referenced by associate(), and SystemConstRefTmpl().
mixture()
template<class ST> MixtureT const & Pscf::Prdc::SystemConstRefTmpl< ST >::mixture () const inline
Get the Mixture.
Definition at line 75 of file SystemConstRefTmpl.h.
interaction()
template<class ST> InteractionT const & Pscf::Prdc::SystemConstRefTmpl< ST >::interaction () const inline
Get the Interaction.
Definition at line 79 of file SystemConstRefTmpl.h.
domain()
template<class ST> DomainT const & Pscf::Prdc::SystemConstRefTmpl< ST >::domain () const inline
Get the Domain.
Definition at line 83 of file SystemConstRefTmpl.h.
c()
template<class ST> CFieldsT const & Pscf::Prdc::SystemConstRefTmpl< ST >::c () const inline
Get the concentration (c) field container.
Definition at line 87 of file SystemConstRefTmpl.h.
w()
template<class ST> WFieldsT const & Pscf::Prdc::SystemConstRefTmpl< ST >::w () const inline
Get the chemical potential (w) field container.
Definition at line 91 of file SystemConstRefTmpl.h.
h()
template<class ST> WFieldsT const & Pscf::Prdc::SystemConstRefTmpl< ST >::h () const inline
Get the external potential (h) field container.
Definition at line 95 of file SystemConstRefTmpl.h.
mask()
template<class ST> MaskT const & Pscf::Prdc::SystemConstRefTmpl< ST >::mask () const inline
Get the mask.
Definition at line 99 of file SystemConstRefTmpl.h.
fileMaster()
template<class ST> FileMaster const & Pscf::Prdc::SystemConstRefTmpl< ST >::fileMaster () const inline
Get the FileMaster.
Definition at line 103 of file SystemConstRefTmpl.h.
The documentation for this class was generated from the following files:
SystemConstRefTmpl.h
SystemConstRefTmpl.tpp