PSCF: Pscf::Prdc::ExtGenFilmBase< D > Class Template Reference
Pscf::Prdc::ExtGenFilmBase< D > Class Template Reference abstract
Pscf namespace » Pscf::Prdc - Periodic Systems » Iterator tools
Base class defining external fields for thin film systems.
#include <ExtGenFilmBase.h>
Public Member Functions
ExtGenFilmBase ()
Constructor.
~ExtGenFilmBase ()
Destructor.
void readParameters (std::istream &in)
Read and initialize.
void checkCompatibility ()
Check that the system is compatible with these fields.
bool updateNeeded () const
Check whether system has changed such that the fields needs updating.
bool hasSymmetricWalls () const
Are the walls chemically identical?
bool isAthermal () const
Are the walls athermal?
GArray< ParameterType > getParameterTypes ()
Return specialized sweep parameter types to add to the Sweep object.
void setParameter (std::string name, DArray< int > ids, double value, bool &success)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids, bool &success) const
Get the value of a specialized sweep parameter.
DArray< double > const & chiBottom () const
Get const chiBottom matrix by reference.
DArray< double > const & chiTop () const
Get const chiTop array by reference.
double chiBottom (int s) const
Get the chi parameter between the bottom wall and species s.
double chiTop (int s) const
Get the chi parameter between the top wall and species s.
int normalVecId () const
Get value of normalVecId.
double interfaceThickness () const
Get value of interfaceThickness.
double excludedThickness () const
Get value of excludedThickness.
bool isGenerated () const =0
Check whether the fields have been generated.
virtual double stressTerm (int paramId) const =0
Get contribution to the stress from these external fields.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Public Member Functions inherited from Pscf::FieldGenerator
FieldGenerator ()
Constructor.
~FieldGenerator ()
Destructor.
void setup ()
Allocate, check compatibility, calculate, and store the field(s)
void update ()
Check whether system has changed and update the field(s) if necessary.
bool isDependent () const
Is this object dependent on the parameters of another FieldGenerator?
virtual double modifyStress (int paramId, double stress) const
Modify stress value if necessary.
Type type () const
Return Type enumeration value (Mask, External, or None)
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Public Member Functions inherited from Pscf::ParameterModifier
ParameterModifier ()
Constructor.
~ParameterModifier ()
Destructor.
void setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
double getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
Protected Member Functions
virtual void allocate ()=0
Allocate container necessary to generate and store fields.
virtual void generate ()=0
Generate the fields and store where the Iterator can access.
virtual std::string systemSpaceGroup () const =0
Get the space group name for this system.
virtual RealVec< D > systemLatticeVector (int id) const =0
Get one of the lattice vectors for this system.
virtual int systemNMonomer () const =0
Get the number of monomer species for this system.
Protected Member Functions inherited from Pscf::FieldGenerator
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
RealVec< D > normalVecCurrent_
The lattice vector normal to the film used to generate these fields.
DArray< double > chiBottomCurrent_
The chiBottom array used to generate the current external fields.
DArray< double > chiTopCurrent_
The chiTop array used to generate the current external fields.
bool isDependent_
Is this object dependent on the parameters of another FieldGenerator?
Type type_
Type of field (Mask, External, Both, or None)
Protected Attributes inherited from Pscf::FieldGenerator
Type type_
Type of field (Mask, External, Both, or None)
bool isDependent_
Is this object dependent on the parameters of another FieldGenerator?
Additional Inherited Members
Public Types inherited from Pscf::FieldGenerator
enum Type
Enum representing the type of field (mask, external field, or both).
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<int D>
class Pscf::Prdc::ExtGenFilmBase< D >
Base class defining external fields for thin film systems.
This is a base class for ExtGenFilm that defines all traits of an ExtGenFilm that do not require access to the System (System access is needed, for example, to access the mask and set the external fields).
If the user chooses an ExtGenFilm object to generate external fields, the external fields will have the same shape as the mask, with a magnitude defined by a Flory–Huggins-like chi parameter. This class is specific to thin-film systems because it also allows for a different chi parameter to be defined on the top boundary than on the bottom, through user input arrays chi_bottom and chi_top. See Thin-Film Confinement for more information.
Definition at line 42 of file ExtGenFilmBase.h.
Constructor & Destructor Documentation
ExtGenFilmBase()
template<int D> Pscf::Prdc::ExtGenFilmBase< D >::ExtGenFilmBase ()
Constructor.
Definition at line 25 of file ExtGenFilmBase.tpp.
References Pscf::Prdc::ExtGenFilmBase< D >::isDependent_, and Pscf::Prdc::ExtGenFilmBase< D >::type_.
~ExtGenFilmBase()
template<int D> Pscf::Prdc::ExtGenFilmBase< D >::~ExtGenFilmBase ()
Destructor.
Definition at line 44 of file ExtGenFilmBase.tpp.
Member Function Documentation
readParameters()
template<int D> void Pscf::Prdc::ExtGenFilmBase< D >::readParameters (std::istream & in) virtual
Read and initialize.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Definition at line 51 of file ExtGenFilmBase.tpp.
References Util::ParamComponent::echo(), Util::ParamComposite::resetParam(), Util::ParamComponent::setEcho(), and UTIL_THROW.
checkCompatibility()
template<int D> void Pscf::Prdc::ExtGenFilmBase< D >::checkCompatibility () virtual
Check that the system is compatible with these fields.
The external fields generated by this class have the same functional form and system constraints as the mask, so it is assumed that these checks have already been performed by the object that generated the mask. However, there is one exception: the external fields can have different chi values on top and bottom, which reduces the symmetry of the system below the symmetry of the mask. If chiBottom != chiTop, this method checks that the space group is compatible with a thin film unit cell with asymmetric walls.
Implements Pscf::FieldGenerator.
Definition at line 92 of file ExtGenFilmBase.tpp.
References Pscf::Prdc::SymmetryGroup< Symmetry >::size(), and UTIL_THROW.
updateNeeded()
template<int D> bool Pscf::Prdc::ExtGenFilmBase< D >::updateNeeded () const virtual
Check whether system has changed such that the fields needs updating.
Implements Pscf::FieldGenerator.
Definition at line 134 of file ExtGenFilmBase.tpp.
References UTIL_CHECK.
hasSymmetricWalls()
template<int D> bool Pscf::Prdc::ExtGenFilmBase< D >::hasSymmetricWalls () const
Are the walls chemically identical?
This is the case when chiBottom is equal to chiTop.
Definition at line 172 of file ExtGenFilmBase.tpp.
References UTIL_CHECK.
isAthermal()
template<int D> bool Pscf::Prdc::ExtGenFilmBase< D >::isAthermal () const
Are the walls athermal?
This is only true if all values in chiBottom and chiTop are zero.
Definition at line 193 of file ExtGenFilmBase.tpp.
References UTIL_CHECK.
getParameterTypes()
template<int D> GArray< ParameterType > Pscf::Prdc::ExtGenFilmBase< D >::getParameterTypes () virtual
Return specialized sweep parameter types to add to the Sweep object.
In this class, the two specialized sweep parameters are chi_top and chi_bottom.
Reimplemented from Pscf::ParameterModifier.
Definition at line 214 of file ExtGenFilmBase.tpp.
References Util::GArray< Data >::append().
setParameter() [1/2]
template<int D> void Pscf::Prdc::ExtGenFilmBase< D >::setParameter (std::string name, DArray< int > ids, double value, bool & success) virtual
Set the value of a specialized sweep parameter.
In this class, the two specialized sweep parameters are chi_top and chi_bottom.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
value the value to which the parameter is set
success was the attempt to set the parameter successful?
Reimplemented from Pscf::ParameterModifier.
Definition at line 226 of file ExtGenFilmBase.tpp.
getParameter() [1/2]
template<int D> double Pscf::Prdc::ExtGenFilmBase< D >::getParameter (std::string name, DArray< int > ids, bool & success) const virtual
Get the value of a specialized sweep parameter.
In this class, the two specialized sweep parameters are chi_top and chi_bottom.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
success was the attempt to get the parameter successful?
Reimplemented from Pscf::ParameterModifier.
Definition at line 252 of file ExtGenFilmBase.tpp.
chiBottom() [1/2]
template<int D> DArray< double > const & Pscf::Prdc::ExtGenFilmBase< D >::chiBottom () const inline
Get const chiBottom matrix by reference.
Definition at line 291 of file ExtGenFilmBase.h.
chiTop() [1/2]
template<int D> DArray< double > const & Pscf::Prdc::ExtGenFilmBase< D >::chiTop () const inline
Get const chiTop array by reference.
Definition at line 296 of file ExtGenFilmBase.h.
chiBottom() [2/2]
template<int D> double Pscf::Prdc::ExtGenFilmBase< D >::chiBottom (int s) const inline
Get the chi parameter between the bottom wall and species s.
Parameters
s species index, 0 <= id < nVertex
Definition at line 301 of file ExtGenFilmBase.h.
chiTop() [2/2]
template<int D> double Pscf::Prdc::ExtGenFilmBase< D >::chiTop (int s) const inline
Get the chi parameter between the top wall and species s.
Parameters
s species index, 0 <= id < nVertex
Definition at line 306 of file ExtGenFilmBase.h.
normalVecId()
template<int D> int Pscf::Prdc::ExtGenFilmBase< D >::normalVecId () const inline
Get value of normalVecId.
Definition at line 311 of file ExtGenFilmBase.h.
interfaceThickness()
template<int D> double Pscf::Prdc::ExtGenFilmBase< D >::interfaceThickness () const inline
Get value of interfaceThickness.
Definition at line 316 of file ExtGenFilmBase.h.
excludedThickness()
template<int D> double Pscf::Prdc::ExtGenFilmBase< D >::excludedThickness () const inline
Get value of excludedThickness.
Definition at line 321 of file ExtGenFilmBase.h.
isGenerated()
template<int D> bool Pscf::Prdc::ExtGenFilmBase< D >::isGenerated () const pure virtual
Check whether the fields have been generated.
Implements Pscf::FieldGenerator.
Implemented in Pscf::Rpc::ExtGenFilm< D >, and Pscf::Rpg::ExtGenFilm< D >.
stressTerm()
template<int D> virtual double Pscf::Prdc::ExtGenFilmBase< D >::stressTerm (int paramId) const pure virtual
Get contribution to the stress from these external fields.
The external fields defined by this class change in a non-affine manner upon changing the lattice parameter corresponding to normalVecId. Thus, if this lattice parameter is allowed to be flexible, the "stress" used to optimize the parameter must contain an additional term arising from the external fields. This method evaluates this term and returns its value. Access to various System properties is required, so the method must be implemented by subclasses.
Parameters
paramId index of the lattice parameter being varied
Reimplemented from Pscf::FieldGenerator.
Implemented in Pscf::Rpc::ExtGenFilm< D >, and Pscf::Rpg::ExtGenFilm< D >.
allocate()
template<int D> virtual void Pscf::Prdc::ExtGenFilmBase< D >::allocate () protected pure virtual
Allocate container necessary to generate and store fields.
Implements Pscf::FieldGenerator.
Implemented in Pscf::Rpc::ExtGenFilm< D >, and Pscf::Rpg::ExtGenFilm< D >.
generate()
template<int D> virtual void Pscf::Prdc::ExtGenFilmBase< D >::generate () protected pure virtual
Generate the fields and store where the Iterator can access.
Implements Pscf::FieldGenerator.
Implemented in Pscf::Rpc::ExtGenFilm< D >, and Pscf::Rpg::ExtGenFilm< D >.
systemSpaceGroup()
template<int D> virtual std::string Pscf::Prdc::ExtGenFilmBase< D >::systemSpaceGroup () const protected pure virtual
Get the space group name for this system.
Implemented in Pscf::Rpc::ExtGenFilm< D >, and Pscf::Rpg::ExtGenFilm< D >.
systemLatticeVector()
template<int D> virtual RealVec< D > Pscf::Prdc::ExtGenFilmBase< D >::systemLatticeVector (int id) const protected pure virtual
Get one of the lattice vectors for this system.
Parameters
id index of the desired lattice vector
Implemented in Pscf::Rpc::ExtGenFilm< D >, and Pscf::Rpg::ExtGenFilm< D >.
systemNMonomer()
template<int D> virtual int Pscf::Prdc::ExtGenFilmBase< D >::systemNMonomer () const protected pure virtual
Get the number of monomer species for this system.
Implemented in Pscf::Rpc::ExtGenFilm< D >, and Pscf::Rpg::ExtGenFilm< D >.
setParameter() [2/2]
template<int D> void Pscf::ParameterModifier::setParameter (std::string name, DArray< int > ids, double value)
Set the value of a specialized sweep parameter.
This is an overloaded version of the setParameter method above, which should be used only when the caller is certain that the specialized sweep parameter belongs to this ParameterModifier. An error will be thrown if the specialized parameter is not settable using this class.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
value the value to which the parameter is set
Definition at line 122 of file ParameterModifier.cpp.
getParameter() [2/2]
template<int D> double Pscf::ParameterModifier::getParameter (std::string name, DArray< int > ids) const
Get the value of a specialized sweep parameter.
This is an overloaded version of the getParameter method above, which should be used only when the caller is certain that the specialized sweep parameter belongs to this ParameterModifier. An error will be thrown if the specialized parameter is not gettable using this class.
Parameters
name name of the specialized parameter
ids array of integer indices specifying the value to set
Definition at line 136 of file ParameterModifier.cpp.
Member Data Documentation
normalVecCurrent_
template<int D> RealVec<D> Pscf::Prdc::ExtGenFilmBase< D >::normalVecCurrent_ protected
The lattice vector normal to the film used to generate these fields.
This vector is set to be equal to the system's lattice vector with index normalVecId_ each time the external fields are generated. The system's lattice vectors may then change, and this normalVecCurrent_ vector is used to detect whether they have changed. This is used to decide whether a new set of external fields needs to be generated.
Definition at line 233 of file ExtGenFilmBase.h.
chiBottomCurrent_
template<int D> DArray<double> Pscf::Prdc::ExtGenFilmBase< D >::chiBottomCurrent_ protected
The chiBottom array used to generate the current external fields.
This array is set to be equal to chiBottom_ each time the external fields are generated. The chiBottom array may then be changed via the setParameter method, and this chiBottomCurrent_ array is used to detect whether they have changed. This is used to determine whether a new set of external fields needs to be generated.
Definition at line 244 of file ExtGenFilmBase.h.
chiTopCurrent_
template<int D> DArray<double> Pscf::Prdc::ExtGenFilmBase< D >::chiTopCurrent_ protected
The chiTop array used to generate the current external fields.
This array is set to be equal to chiTop_ each time the external fields are generated. The chiTop array may then be changed via the setParameter method, and this chiTopCurrent_ array is used to detect whether they have changed. This is used to determine whether a new set of external fields needs to be generated.
Definition at line 255 of file ExtGenFilmBase.h.
isDependent_
template<int D> bool Pscf::FieldGenerator::isDependent_ protected
Is this object dependent on the parameters of another FieldGenerator?
Definition at line 181 of file FieldGenerator.h.
Referenced by Pscf::Prdc::ExtGenFilmBase< D >::ExtGenFilmBase().
type_
template<int D> Type Pscf::FieldGenerator::type_ protected
Type of field (Mask, External, Both, or None)
This parameter should be a private member of subclasses, and should be set in the constructor and left unchanged for the remainder of the calculation.
Definition at line 178 of file FieldGenerator.h.
Referenced by Pscf::Prdc::ExtGenFilmBase< D >::ExtGenFilmBase().
The documentation for this class was generated from the following files:
ExtGenFilmBase.h
ExtGenFilmBase.tpp