PSCF: Pscf::R1d::Block Class Reference
Pscf::R1d::Block Class Reference
Pscf namespace » Pscf::R1d - Real 1D fields » Solvers
Block within a branched polymer.
#include <Block.h>
Public Member Functions
Block ()
Constructor.
~Block ()
Destructor.
void setDiscretization (Domain const &domain, double ds)
Initialize discretization and allocate required memory.
virtual void setLength (double newLength)
Set length and readjust ds_ accordingly.
void setupSolver (DArray< double > const &w)
Set Crank-Nicholson solver for this block.
void computeConcentration (double prefactor)
Compute concentration for block by integration.
void step (DArray< double > const &q, DArray< double > &qNew)
Compute one step of integration loop, from i to i+1.
Domain const & domain () const
Return associated domain by reference.
int ns () const
Number of contour length steps.
Public Member Functions inherited from Pscf::BlockTmpl< Propagator >
BlockTmpl ()
Constructor.
virtual ~BlockTmpl ()
Destructor.
virtual void setKuhn (double kuhn)
Set monomer statistical segment length.
Propagator & propagator (int directionId)
Get a Propagator for a specified direction.
Propagator const & propagator (int directionId) const
Get a const Propagator for a specified direction.
Propagator::CField & cField ()
Get the associated monomer concentration field.
Propagator::CField const & cField () const
Get the associated const monomer concentration field.
double kuhn () const
Get monomer statistical segment length.
Public Member Functions inherited from Pscf::Edge
Edge ()
Constructor.
virtual ~Edge ()
Destructor.
template<class Archive >
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
void setId (int id)
Set the id for this block.
void setMonomerId (int monomerId)
Set the monomer type id.
void setVertexIds (int vertexId0, int vertexId1)
Set indices of associated vertices.
void setVertexOwnership (bool own0, bool own1)
Set ownership of associated vertices (only valid for bead model).
virtual void setNBead (int nBead)
Set the number of beads in this block (only valid for bead model).
void setPolymerType (PolymerType::Enum type)
Set the polymer type (branched or linear).
int id () const
Get the id of this block.
int monomerId () const
Get the monomer type id.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
bool ownsVertex (int i) const
Does this block own an associated vertex (bead model).
double nBead () const
Get the number of beads in this block, in the bead model.
double length () const
Get the length of this block, in the thread model.
PolymerType::Enum polymerType () const
Get the type of the parent polymer (branched or linear).
Detailed Description
Block within a branched polymer.
Derived from BlockTmpl<Propagator>. A BlockTmpl<Propagator> has two Propagator members and is derived from Edge.
Definition at line 31 of file r1d/solvers/Block.h.
Constructor & Destructor Documentation
Block()
Pscf::R1d::Block::Block ()
Constructor.
Definition at line 20 of file r1d/solvers/Block.cpp.
References Pscf::BlockTmpl< Propagator >::propagator().
~Block()
Pscf::R1d::Block::~Block ()
Destructor.
Definition at line 33 of file r1d/solvers/Block.cpp.
Member Function Documentation
setDiscretization()
void Pscf::R1d::Block::setDiscretization (Domain const & domain, double ds)
Initialize discretization and allocate required memory.
Parameters
domain associated Domain object, with grid info
ds desired (optimal) value for contour length step
Definition at line 36 of file r1d/solvers/Block.cpp.
References Pscf::TridiagonalSolver::allocate(), Util::DArray< T >::allocate(), Pscf::BlockTmpl< Propagator >::cField(), domain(), Pscf::Edge::length(), Pscf::R1d::Domain::nx(), Pscf::BlockTmpl< Propagator >::propagator(), and UTIL_CHECK.
setLength()
void Pscf::R1d::Block::setLength (double newLength) virtual
Set length and readjust ds_ accordingly.
Parameters
newLength length (# of monomers) for this block
Reimplemented from Pscf::Edge.
Definition at line 68 of file r1d/solvers/Block.cpp.
References Pscf::Edge::length(), Pscf::BlockTmpl< Propagator >::propagator(), Pscf::Edge::setLength(), and UTIL_CHECK.
setupSolver()
void Pscf::R1d::Block::setupSolver (DArray< double > const & w)
Set Crank-Nicholson solver for this block.
Parameters
w Chemical potential field (input)
Definition at line 120 of file r1d/solvers/Block.cpp.
References Util::Array< Data >::capacity(), Pscf::TridiagonalSolver::computeLU(), domain(), Pscf::R1d::Domain::dx(), Pscf::R1d::Domain::isShell(), Pscf::BlockTmpl< Propagator >::kuhn(), Pscf::Edge::length(), Pscf::R1d::Domain::mode(), Pscf::R1d::Domain::nx(), Pscf::BlockTmpl< Propagator >::propagator(), UTIL_CHECK, UTIL_THROW, Pscf::R1d::Domain::xMax(), and Pscf::R1d::Domain::xMin().
computeConcentration()
void Pscf::R1d::Block::computeConcentration (double prefactor)
Compute concentration for block by integration.
Upon return, grid point r of array cField() contains the integral int ds q(r,s)q^{*}(r,L-s) times the prefactor, where q(r,s) is the solution obtained from propagator(0), and q^{*} is the solution of propagator(1), and s is a contour variable that is integrated over the domain 0 < s < length(), where length() is the block length.
Parameters
prefactor constant prefactor multiplying integral
Definition at line 241 of file r1d/solvers/Block.cpp.
References Util::Array< Data >::capacity(), Pscf::BlockTmpl< Propagator >::cField(), domain(), Pscf::R1d::Domain::nx(), Pscf::BlockTmpl< Propagator >::propagator(), and UTIL_CHECK.
step()
void Pscf::R1d::Block::step (DArray< double > const & q, DArray< double > & qNew)
Compute one step of integration loop, from i to i+1.
Parameters
q propagator slice at step i (input)
qNew propagator slice at step i + 1 (output)
Definition at line 294 of file r1d/solvers/Block.cpp.
References domain(), Pscf::R1d::Domain::nx(), and Pscf::TridiagonalSolver::solve().
Referenced by Pscf::R1d::Propagator::solve(), and Pscf::R1d::Propagator::solve().
domain()
Domain const & Pscf::R1d::Block::domain () const inline
Return associated domain by reference.
Get Domain by reference.
Definition at line 148 of file r1d/solvers/Block.h.
References UTIL_ASSERT.
Referenced by computeConcentration(), Pscf::R1d::Propagator::computeQ(), setDiscretization(), setupSolver(), and step().
ns()
int Pscf::R1d::Block::ns () const inline
Number of contour length steps.
Get number of contour steps.
Definition at line 155 of file r1d/solvers/Block.h.
The documentation for this class was generated from the following files:
r1d/solvers/Block.h
r1d/solvers/Block.cpp