PSCF: Util::MemoryCounter Class Reference
Util::MemoryCounter Class Reference
Archive to computed packed size of a sequence of objects, in bytes.
#include <MemoryCounter.h>
Public Member Functions
MemoryCounter ()
Constructor.
~MemoryCounter ()
Destructor.
void clear ()
Resets the size counter to zero.
template<typename T >
MemoryCounter & operator<< (T &data)
Add packed size of one object via operator <<.
template<typename T >
MemoryCounter & operator& (T &data)
Add packed size of one object via operator &.
template<typename T , size_t N>
MemoryCounter & operator<< (T(&data)[N])
Add packed size of a fixed size array via operator <<.
template<typename T , size_t N>
MemoryCounter & operator& (T(&data)[N])
Add packed size of a fixed size array via operator &.
template<typename T >
void count (const T &data)
Add size of one object in memory.
template<typename T >
void count (T *array, int n)
Compute the size in memory of a C array.
size_t size () const
Return size required for archive, in Bytes.
Static Public Member Functions
static bool is_saving ()
Returns true.
static bool is_loading ()
Returns false.
Detailed Description
Archive to computed packed size of a sequence of objects, in bytes.
This class computes the number of bytes required to pack a sequence of objects within a MemoryOArchive. The interface is that of a loading Archive, but the << and & operators are overloaded to compute the size required for an object and to increment a size counter, rather than to actually save data.
The size() method returns the number of bytes required to pack all of the objects serialized thus far. The size counter is set to zero upon construction. The clear() method resets the size counter to zero.
Definition at line 35 of file MemoryCounter.h.
Constructor & Destructor Documentation
MemoryCounter()
Util::MemoryCounter::MemoryCounter ()
Constructor.
Definition at line 16 of file MemoryCounter.cpp.
~MemoryCounter()
Util::MemoryCounter::~MemoryCounter ()
Destructor.
Definition at line 24 of file MemoryCounter.cpp.
Member Function Documentation
is_saving()
bool Util::MemoryCounter::is_saving () inline static
Returns true.
Definition at line 159 of file MemoryCounter.h.
is_loading()
bool Util::MemoryCounter::is_loading () inline static
Returns false.
Definition at line 162 of file MemoryCounter.h.
clear()
void Util::MemoryCounter::clear ()
Resets the size counter to zero.
Definition at line 30 of file MemoryCounter.cpp.
operator<<() [1/2]
template<typename T > MemoryCounter & Util::MemoryCounter::operator<< (T & data) inline
Add packed size of one object via operator <<.
Parameters
data object to be analyzed
Definition at line 175 of file MemoryCounter.h.
operator&() [1/2]
template<typename T > MemoryCounter & Util::MemoryCounter::operator& (T & data) inline
Add packed size of one object via operator &.
Parameters
data object to be analyzed
Definition at line 185 of file MemoryCounter.h.
operator<<() [2/2]
template<typename T , size_t N> MemoryCounter & Util::MemoryCounter::operator<< (T(&) data[N]) inline
Add packed size of a fixed size array via operator <<.
Parameters
data fixed size array to be analyzed
Definition at line 195 of file MemoryCounter.h.
operator&() [2/2]
template<typename T , size_t N> MemoryCounter & Util::MemoryCounter::operator& (T(&) data[N]) inline
Add packed size of a fixed size array via operator &.
Parameters
data fixed size array to be analyzed
Definition at line 207 of file MemoryCounter.h.
count() [1/2]
template<typename T > void Util::MemoryCounter::count (const T & data) inline
Add size of one object in memory.
This method just increments the size by sizeof(T). It is appropriate only for primitive C++ variables and POD types for which a bitwise copy is appropriate.
Definition at line 221 of file MemoryCounter.h.
count() [2/2]
template<typename T > void Util::MemoryCounter::count (T * array, int n) inline
Compute the size in memory of a C array.
This method increments the size by n*sizeof(T). It is appropriate for C arrays of primitive variables and of POD types for which a bitwise copy is appropriate.
Definition at line 228 of file MemoryCounter.h.
size()
size_t Util::MemoryCounter::size () const inline
Return size required for archive, in Bytes.
Definition at line 168 of file MemoryCounter.h.
Referenced by pscfpp.file.File::__eq__(), pscfpp.file.File::__init__(), pscfpp.text.Record::__init__(), pscfpp.file.File::__repr__(), pscfpp.text.Record::__str__(), and Util::memorySize().
The documentation for this class was generated from the following files:
MemoryCounter.h
MemoryCounter.cpp