PSCF: Pscf::Prdc::Cuda::RFieldComparison< D > Class Template Reference
Pscf::Prdc::Cuda::RFieldComparison< D > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CUDA)
Comparator for fields in real-space (r-grid) format.
#include <RFieldComparison.h>
Public Member Functions
RFieldComparison ()
Constructor.
double compare (RField< D > const &a, RField< D > const &b)
Comparator for individual fields.
double compare (DArray< RField< D > > const &a, DArray< RField< D > > const &b)
Comparator for arrays of fields.
double maxDiff () const
Get precomputed maximum element-by-element difference.
double rmsDiff () const
Get precomputed rms difference.
Detailed Description
template<int D>
class Pscf::Prdc::Cuda::RFieldComparison< D >
Comparator for fields in real-space (r-grid) format.
Definition at line 28 of file cuda/RFieldComparison.h.
Constructor & Destructor Documentation
RFieldComparison()
template<int D> Pscf::Prdc::Cuda::RFieldComparison< D >::RFieldComparison ()
Constructor.
Definition at line 20 of file RFieldComparison.tpp.
Member Function Documentation
compare() [1/2]
template<int D> double Pscf::Prdc::Cuda::RFieldComparison< D >::compare (RField< D > const & a, RField< D > const & b)
Comparator for individual fields.
Parameters
a first array of fields
b second array of fields
Definition at line 25 of file RFieldComparison.tpp.
References Util::Array< Data >::capacity().
compare() [2/2]
template<int D> double Pscf::Prdc::Cuda::RFieldComparison< D >::compare (DArray< RField< D > > const & a, DArray< RField< D > > const & b)
Comparator for arrays of fields.
Parameters
a first array of fields
b second array of fields
Definition at line 44 of file RFieldComparison.tpp.
References Util::DArray< T >::allocate(), and Util::Array< Data >::capacity().
maxDiff()
template<int D> double Pscf::Prdc::Cuda::RFieldComparison< D >::maxDiff () const inline
Get precomputed maximum element-by-element difference.
Definition at line 57 of file cuda/RFieldComparison.h.
rmsDiff()
template<int D> double Pscf::Prdc::Cuda::RFieldComparison< D >::rmsDiff () const inline
Get precomputed rms difference.
Definition at line 63 of file cuda/RFieldComparison.h.
The documentation for this class was generated from the following files:
cuda/RFieldComparison.h
RFieldComparison.tpp