PSCF: Pscf::Prdc::Cpu::FieldBasisConverter< D > Class Template Reference
Pscf::Prdc::Cpu::FieldBasisConverter< D > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CPU)
Tool for conversion of fields to a basis in composition space.
#include <FieldBasisConverter.h>
Public Member Functions
FieldBasisConverter ()
Default constructor.
FieldBasisConverter (DMatrix< double > basis)
Constructor.
virtual ~FieldBasisConverter ()
Destructor.
void setBasis (DMatrix< double > basis)
Set or reset the basis after construction.
double maxBasisError (double normSq=1.0) const
Check validity (orthogonality and normalization) of the basis.
void convertToBasis (DArray< RField< D > > const &in, DArray< RField< D > > &out, double prefactor=1.0) const
Convert a set of monomer fields to field basis components.
void convertFromBasis (DArray< RField< D > > const &in, DArray< RField< D > > &out, double prefactor=1.0) const
Convert a set of field basis components to monomer fields.
int nMonomer () const
Return the number of monomer types (dimension of basis).
bool hasBasis () const
Has a basis been initialized?
Detailed Description
template<int D>
class Pscf::Prdc::Cpu::FieldBasisConverter< D >
Tool for conversion of fields to a basis in composition space.
A FieldBasisConverter has an associated orthogonal basis of vectors in a real vector space of dimension nMonomer, where nMonomer is the number of monomer types. This class provides functions that can convert between a list of fields associated with different monomer types to a corresponding list of field components that are each associated with a vector in such a basis.
This class is designed primarily for use in field theory simulations in which it useful to define field components associated with eigenvectors of an nMonomer x nMonomer symmetric matrix that describes interactions among monomers of different types.
Definition at line 44 of file FieldBasisConverter.h.
Constructor & Destructor Documentation
FieldBasisConverter() [1/2]
template<int D> Pscf::Prdc::Cpu::FieldBasisConverter< D >::FieldBasisConverter ()
Default constructor.
Definition at line 26 of file FieldBasisConverter.tpp.
FieldBasisConverter() [2/2]
template<int D> Pscf::Prdc::Cpu::FieldBasisConverter< D >::FieldBasisConverter (DMatrix< double > basis)
Constructor.
The parameter basis is an nMonomer times nMonomer matrix of orthogonal basis vectors in which the first index (row index) identifies a basis vector and the second index identifies a monomer type of a particular basis vector. The design assumes that the basis vectors are orthogonal, and that they all have the same norm, but does not require that they be orthonormal (i.e., have a unit norm).
The matrix basis is passed by value, and a local copy is made internally during construction.
Parameters
basis Matrix of basis vectors
Definition at line 35 of file FieldBasisConverter.tpp.
References Pscf::Prdc::Cpu::FieldBasisConverter< D >::setBasis().
~FieldBasisConverter()
template<int D> Pscf::Prdc::Cpu::FieldBasisConverter< D >::~FieldBasisConverter () virtual
Destructor.
Definition at line 44 of file FieldBasisConverter.tpp.
Member Function Documentation
setBasis()
template<int D> void Pscf::Prdc::Cpu::FieldBasisConverter< D >::setBasis (DMatrix< double > basis)
Set or reset the basis after construction.
The parameter basis has the same meaning as parameters of the non-default constructor.
Parameters
basis Matrix of vectors.
Definition at line 51 of file FieldBasisConverter.tpp.
References Util::Matrix< Data >::capacity1(), Util::Matrix< Data >::capacity2(), Util::DMatrix< Data >::isAllocated(), and UTIL_CHECK.
Referenced by Pscf::Prdc::Cpu::FieldBasisConverter< D >::FieldBasisConverter().
maxBasisError()
template<int D> double Pscf::Prdc::Cpu::FieldBasisConverter< D >::maxBasisError (double normSq = 1.0) const
Check validity (orthogonality and normalization) of the basis.
This function returns the maximum absolute magnitude of the difference between the dot product of any two basis vectors and the expected value. The expected value is zero for any two distinct basis vectors, and is equal to the parameter normSq for a dot product of any basis vector with itself.
Parameters
normSq square norm of all basis vectors
Definition at line 65 of file FieldBasisConverter.tpp.
References UTIL_CHECK.
convertToBasis()
template<int D> void Pscf::Prdc::Cpu::FieldBasisConverter< D >::convertToBasis (DArray< RField< D > > const & in, DArray< RField< D > > & out, double prefactor = 1.0) const
Convert a set of monomer fields to field basis components.
The value of the component associated with a specific basis vector at each grid point (parameter out) is obtained by taking a dot product of that basis vector with the vector of values of fields associated with different monomer types (parameter in) at the same grid point, and multiplying that by the prefactor.
Parameters
in input fields, indexed by monomer type id
out output field components, indexed by basis vector id
prefactor common scalar prefactor
Definition at line 96 of file FieldBasisConverter.tpp.
References UTIL_CHECK.
convertFromBasis()
template<int D> void Pscf::Prdc::Cpu::FieldBasisConverter< D >::convertFromBasis (DArray< RField< D > > const & in, DArray< RField< D > > & out, double prefactor = 1.0) const
Convert a set of field basis components to monomer fields.
The vector of nMonomer values of output fields (parameter out) at each grid point is given by a linear superposition of basis vectors with component values given by the values of the input fields components (parameter in) at the the same grid point, multiplied by a common prefactor.
Parameters
in input field components, indexed by basis vector id
out output fields, indexed by monomer type id
prefactor common scalar prefactor
Definition at line 142 of file FieldBasisConverter.tpp.
References UTIL_CHECK.
nMonomer()
template<int D> int Pscf::Prdc::Cpu::FieldBasisConverter< D >::nMonomer () const inline
Return the number of monomer types (dimension of basis).
Definition at line 137 of file FieldBasisConverter.h.
hasBasis()
template<int D> bool Pscf::Prdc::Cpu::FieldBasisConverter< D >::hasBasis () const inline
Has a basis been initialized?
Definition at line 143 of file FieldBasisConverter.h.
The documentation for this class was generated from the following files:
FieldBasisConverter.h
FieldBasisConverter.tpp