PSCF: Pscf::Rpg::Simulator< D > Class Template Reference
Pscf::Rpg::Simulator< D > Class Template Reference
Pscf namespace » Pscf::Rpg - Real Periodic Fields (GPU) » Field Theoretic Simulation (FTS)
Field theoretic simulator (base class).
#include <Simulator.h>
Public Member Functions
Simulator (System< D > &system)
Constructor.
~Simulator ()
Destructor.
void allocate ()
Allocate required memory.
virtual void readParameters (std::istream &in)
Read parameters for a simulation.
Primary Actions: Simulation and Analysis
virtual void simulate (int nStep)
Perform a field theoretic Monte-Carlo simulation.
virtual void analyze (int min, int max, std::string classname, std::string filename)
Read and analyze a trajectory file.
void clearData ()
Clear field eigen-components and hamiltonian components.
virtual void outputTimers (std::ostream &out)
Output timing results.
virtual void outputMdeCounter (std::ostream &out)
Output MDE counter.
virtual void clearTimers ()
Clear timers.
long iStep ()
Return the current converged simulation step index.
long iTotalStep ()
Return the current simulation step index.
Projected Chi Matrix
void analyzeChi ()
Perform eigenvalue analysis of projected chi matrix.
DArray< double > const & chiEvals () const
Get an array of the eigenvalues of the projected chi matrix.
double chiEval (int a) const
Get a single eigenvalue of the projected chi matrix.
DMatrix< double > const & chiEvecs () const
Get the matrix of all eigenvectors of the projected chi matrix.
double chiEvecs (int a, int i) const
Get one element of an eigenvector of the projected chi matrix.
DArray< double > const & sc () const
Get all components of the vector S.
double sc (int a) const
Get a single component of the S vector.
Field Theoretic Hamiltonian
void computeHamiltonian ()
Compute the Hamiltonian used in field theoretic simulations.
double hamiltonian () const
Get the Hamiltonian used in field theoretic simulations.
double idealHamiltonian () const
Get ideal gas contribution (-lnQ) to MC Hamiltonian.
double fieldHamiltonian () const
Get the quadratic field contribution (HW) to MC Hamiltonian.
double perturbationHamiltonian () const
Get the perturbation to the standard Hamiltonian (if any).
bool hasHamiltonian () const
Has the MC Hamiltonian been computed for current w and c fields?
Chemical Potential Field (W Field) Components
void computeWc ()
Compute eigenvector components of the current w fields.
DArray< RField< D > > const & wc () const
Get all eigenvector components of the current w fields.
RField< D > const & wc (int a) const
Get one eigenvector component of the current w fields.
bool hasWc () const
Are eigen-components of current w fields valid ?
Monomer Concentration Field (C-Field) Components
void computeCc ()
Compute eigenvector components of the current c fields.
DArray< RField< D > > const & cc () const
Get all eigenvector components of the current c fields.
RField< D > const & cc (int a) const
Get one eigenvector component of the current c fields.
bool hasCc () const
Are eigen-components of current c fields valid ?
Functional Derivatives of H[W]
void computeDc ()
Compute functional derivatives of the Hamiltonian.
DArray< RField< D > > const & dc () const
Get all of the current d fields.
RField< D > const & dc (int i) const
Get one eigenvector component of the current d fields.
bool hasDc () const
Are the current d fields valid ?
Utilities for moves
void saveState ()
Save a copy of the fts move state.
void restoreState ()
Restore the saved copy of the fts move state.
void clearState ()
Clear the saved copy of the fts state.
Miscellaneous
System< D > & system ()
Get parent system by reference.
Compressor< D > & compressor ()
Get the compressor by reference.
bool hasCompressor () const
Does this Simulator have a Compressor object?
Random & random ()
Get random number generator by reference.
CudaRandom & cudaRandom ()
Get cuda random number generator by reference.
bool hasPerturbation () const
Does this Simulator have a Perturbation?
Perturbation< D > const & perturbation () const
Get the associated Perturbation by const reference.
Perturbation< D > & perturbation ()
Get the perturbation factory by non-const reference.
bool hasRamp () const
Does this Simulator have a Ramp?
Ramp< D > const & ramp () const
Get the associated Ramp by const reference.
Ramp< D > & ramp ()
Get the ramp by non-const reference.
Public Member Functions inherited from Util::ParamComposite
ParamComposite ()
Constructor.
ParamComposite (const ParamComposite &other)
Copy constructor.
ParamComposite (int capacity)
Constructor.
virtual ~ParamComposite ()
Virtual destructor.
void resetParam ()
Resets ParamComposite to its empty state.
virtual void readParam (std::istream &in)
Read the parameter file block.
virtual void readParamOptional (std::istream &in)
Read optional parameter file block.
virtual void writeParam (std::ostream &out) const
Write all parameters to an output stream.
virtual void load (Serializable::IArchive &ar)
Load all parameters from an input archive.
virtual void loadOptional (Serializable::IArchive &ar)
Load an optional ParamComposite.
virtual void loadParameters (Serializable::IArchive &ar)
Load state from archive, without adding Begin and End lines.
virtual void save (Serializable::OArchive &ar)
Saves all parameters to an archive.
void saveOptional (Serializable::OArchive &ar)
Saves isActive flag, and then calls save() iff isActive is true.
void readParamComposite (std::istream &in, ParamComposite &child, bool next=true)
Add and read a required child ParamComposite.
void readParamCompositeOptional (std::istream &in, ParamComposite &child, bool next=true)
Add and attempt to read an optional child ParamComposite.
template<typename Type >
ScalarParam< Type > & read (std::istream &in, const char *label, Type &value)
Add and read a new required ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & readOptional (std::istream &in, const char *label, Type &value)
Add and read a new optional ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & readCArray (std::istream &in, const char *label, Type *value, int n)
Add and read a required C array parameter.
template<typename Type >
CArrayParam< Type > & readOptionalCArray (std::istream &in, const char *label, Type *value, int n)
Add and read an optional C array parameter.
template<typename Type >
DArrayParam< Type > & readDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read a required DArray < Type > parameter.
template<typename Type >
DArrayParam< Type > & readOptionalDArray (std::istream &in, const char *label, DArray< Type > &array, int n)
Add and read an optional DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read a required FArray < Type, N > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & readOptionalFArray (std::istream &in, const char *label, FArray< Type, N > &array)
Add and read an optional FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read a required FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & readOptionalFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size)
Add and read an optional FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & readCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read a required CArray2DParam < Type > 2D C-array.
template<typename Type >
CArray2DParam< Type > & readOptionalCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np)
Add and read an optional CArray2DParam < Type > 2D C-array parameter.
template<typename Type >
DMatrixParam< Type > & readDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read a required DMatrix < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & readOptionalDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and read an optional DMatrix < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & readDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read a required symmetrix DMatrix.
template<typename Type >
DSymmMatrixParam< Type > & readOptionalDSymmMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int n)
Add and read an optional DMatrix matrix parameter.
Begin & readBegin (std::istream &in, const char *label, bool isRequired=true)
Add and read a class label and opening bracket.
End & readEnd (std::istream &in)
Add and read the closing bracket.
Blank & readBlank (std::istream &in)
Add and read a new Blank object, representing a blank line.
void loadParamComposite (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load a required child ParamComposite.
void loadParamCompositeOptional (Serializable::IArchive &ar, ParamComposite &child, bool next=true)
Add and load an optional child ParamComposite if isActive.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value, bool isRequired)
Add and load a new ScalarParam < Type > object.
template<typename Type >
ScalarParam< Type > & loadParameter (Serializable::IArchive &ar, const char *label, Type &value)
Add and load new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n, bool isRequired)
Add a C array parameter and load its elements.
template<typename Type >
CArrayParam< Type > & loadCArray (Serializable::IArchive &ar, const char *label, Type *value, int n)
Add and load a required CArrayParam< Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n, bool isRequired)
Add an load a DArray < Type > array parameter.
template<typename Type >
DArrayParam< Type > & loadDArray (Serializable::IArchive &ar, const char *label, DArray< Type > &array, int n)
Add and load a required DArray< Type > array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array, bool isRequired)
Add and load an FArray < Type, N > fixed-size array parameter.
template<typename Type , int N>
FArrayParam< Type, N > & loadFArray (Serializable::IArchive &ar, const char *label, FArray< Type, N > &array)
Add and load a required FArray < Type > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size, bool isRequired)
Add and load an FSArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & loadFSArray (Serializable::IArchive &ar, const char *label, FSArray< Type, N > &array, int size)
Add and load a required FSArray < Type > array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np, bool isRequired)
Add and load a CArray2DParam < Type > C 2D array parameter.
template<typename Type >
CArray2DParam< Type > & loadCArray2D (Serializable::IArchive &ar, const char *label, Type *value, int m, int n, int np)
Add and load a required < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired)
Add and load a DMatrixParam < Type > matrix parameter.
template<typename Type >
DMatrixParam< Type > & loadDMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int m, int n)
Add and load a required DMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n, bool isRequired)
Add and load a symmetric DSymmMatrixParam < Type > matrix parameter.
template<typename Type >
DSymmMatrixParam< Type > & loadDSymmMatrix (Serializable::IArchive &ar, const char *label, DMatrix< Type > &matrix, int n)
Add and load a required DSymmMatrixParam < Type > matrix parameter.
void addParamComposite (ParamComposite &child, bool next=true)
Add a child ParamComposite object to the format array.
Begin & addBegin (const char *label)
Add a Begin object representing a class name and bracket.
End & addEnd ()
Add a closing bracket.
Blank & addBlank ()
Create and add a new Blank object, representing a blank line.
std::string className () const
Get class name string.
bool isRequired () const
Is this ParamComposite required in the input file?
bool isActive () const
Is this parameter active?
Public Member Functions inherited from Util::ParamComponent
virtual ~ParamComponent ()
Destructor.
void setIndent (const ParamComponent &parent, bool next=true)
Set indent level.
std::string indent () const
Return indent string for this object (string of spaces).
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize this ParamComponent as a string.
Public Member Functions inherited from Util::Serializable
virtual ~Serializable ()
Destructor.
Public Member Functions inherited from Util::MpiFileIo
MpiFileIo ()
Constructor.
MpiFileIo (const MpiFileIo &other)
Copy constructor.
bool isIoProcessor () const
Can this processor do file I/O ?
void setIoCommunicator (MPI::Intracomm &communicator)
Set the communicator.
void clearCommunicator ()
Clear (nullify) the communicator.
bool hasIoCommunicator () const
Does this object have an associated MPI communicator?
MPI::Intracomm & ioCommunicator () const
Get the MPI communicator by reference.
Protected Member Functions
void readRandomSeed (std::istream &in)
Read random seed and initialize random number generators.
CompressorFactory< D > & compressorFactory ()
Get the compressor factory by reference.
void readCompressor (std::istream &in, bool &isEnd)
Read the compressor block of the parameter file.
PerturbationFactory< D > & perturbationFactory ()
Get the perturbation factory by reference.
void readPerturbation (std::istream &in, bool &isEnd)
Optionally read an associated perturbation.
void setPerturbation (Perturbation< D > *ptr)
Set the associated perturbation.
RampFactory< D > & rampFactory ()
Get the ramp factory by reference.
void readRamp (std::istream &in, bool &isEnd)
Optionally read an associated ramp.
void setRamp (Ramp< D > *ptr)
Set the associated ramp.
Protected Member Functions inherited from Util::ParamComposite
void setClassName (const char *className)
Set class name string.
void setIsRequired (bool isRequired)
Set or unset the isActive flag.
void setIsActive (bool isActive)
Set or unset the isActive flag.
void setParent (ParamComponent &param, bool next=true)
Set this to the parent of a child component.
void addComponent (ParamComponent &param, bool isLeaf=true)
Add a new ParamComponent object to the format array.
template<typename Type >
ScalarParam< Type > & add (std::istream &in, const char *label, Type &value, bool isRequired=true)
Add a new required ScalarParam < Type > object.
template<typename Type >
CArrayParam< Type > & addCArray (std::istream &in, const char *label, Type *value, int n, bool isRequired=true)
Add (but do not read) a required C array parameter.
template<typename Type >
DArrayParam< Type > & addDArray (std::istream &in, const char *label, DArray< Type > &array, int n, bool isRequired=true)
Add (but do not read) a DArray < Type > parameter.
template<typename Type , int N>
FArrayParam< Type, N > & addFArray (std::istream &in, const char *label, FArray< Type, N > &array, bool isRequired=true)
Add (but do not read) a FArray < Type, N > array parameter.
template<typename Type , int N>
FSArrayParam< Type, N > & addFSArray (std::istream &in, const char *label, FSArray< Type, N > &array, int size, bool isRequired=true)
Add (but do not read) a FSArray < Type, N > array parameter.
template<typename Type >
CArray2DParam< Type > & addCArray2D (std::istream &in, const char *label, Type *value, int m, int n, int np, bool isRequired=true)
Add (but do not read) a CArray2DParam < Type > 2D C-array.
template<typename Type >
DMatrixParam< Type > & addDMatrix (std::istream &in, const char *label, DMatrix< Type > &matrix, int m, int n, bool isRequired=true)
Add and read a required DMatrix < Type > matrix parameter.
Protected Member Functions inherited from Util::ParamComponent
ParamComponent ()
Constructor.
ParamComponent (const ParamComponent &other)
Copy constructor.
Protected Attributes
Random random_
Random number generator.
CudaRandom cudaRandom_
Random number generator.
DArray< RField< D > > wc_
Eigenvector components of w fields on a real space grid.
DArray< RField< D > > cc_
Eigenvector components of c fields on a real space grid.
DArray< RField< D > > dc_
Components of d fields on a real space grid.
SimState< D > state_
State saved during fts simulation.
double hamiltonian_
Field theoretic Hamiltonian H[W] (extensive value).
double idealHamiltonian_
Ideal gas contribution (lnQ) to Hamiltonian H[W].
double fieldHamiltonian_
Field contribution (H_W) to Hamiltonian.
double perturbationHamiltonian_
Perturbation to the standard Hamiltonian (if any).
long iStep_
Simulation step counter.
long iTotalStep_
Simulation step counter.
long seed_
Random number generator seed.
bool hasHamiltonian_
Has the Hamiltonian been computed for the current w and c fields?
bool hasWc_
Have eigen-components of the current w fields been computed ?
bool hasCc_
Have eigen-components of the current c fields been computed ?
bool hasDc_
Have functional derivatives of H[W] been computed ?
Additional Inherited Members
Public Types inherited from Util::Serializable
typedef BinaryFileOArchive OArchive
Type of output archive used by save method.
typedef BinaryFileIArchive IArchive
Type of input archive used by load method.
Static Public Member Functions inherited from Util::ParamComponent
static void initStatic ()
Initialize static echo member to false.
static void setEcho (bool echo=true)
Enable or disable echoing for all subclasses of ParamComponent.
static bool echo ()
Get echo parameter.
Detailed Description
template<int D>
class Pscf::Rpg::Simulator< D >
Field theoretic simulator (base class).
The Simulator base class provides tools needed in field-theoretic simulations that are based on a partial saddle-point approximation, including field theoretic Monte Carlo and field-theoretic Langevin simulations. Subclasses of this class provide algorithms and more specialized data structures needed by specific sampling methods.
The analyzeChi() function constructs and diagonalizes the projected chi matrix. This is a singular nMonomer x nMonomer matrix defined by evaluating the projection of the chi matrix into the subspace of fluctuations that preserves total monomer concentration. The eigenvalues and eigenvectors of this matrix via the chiEvals and chiEvecs functions, respectively.
The functions computeWc, computeCc and computeDc compute components components of various types of multi-component fields (i.e., fields that are associated with a monomer type index) in a basis of eigenvectors of the projected chi matrix. Names such as wc, cc and dc that end with a suffix "c" refer to components of multi-component fields that are defined using this eigenvector basis.
Definition at line 45 of file rpg/System.h.
Constructor & Destructor Documentation
Simulator()
template<int D> Pscf::Rpg::Simulator< D >::Simulator (System< D > & system)
Constructor.
Parameters
system parent System
Definition at line 43 of file rpg/fts/simulator/Simulator.tpp.
References Util::ParamComposite::setClassName(), and Pscf::Rpg::Simulator< D >::system().
~Simulator()
template<int D> Pscf::Rpg::Simulator< D >::~Simulator ()
Destructor.
Definition at line 76 of file rpg/fts/simulator/Simulator.tpp.
Member Function Documentation
allocate()
template<int D> void Pscf::Rpg::Simulator< D >::allocate ()
Allocate required memory.
Values of nMonomer and the mesh dimensions must be defined in Mixture and Domain members of the parent System on entry. This function should be called by the readParameters method of any subclass.
Definition at line 102 of file rpg/fts/simulator/Simulator.tpp.
References UTIL_CHECK.
readParameters()
template<int D> void Pscf::Rpg::Simulator< D >::readParameters (std::istream & in) virtual
Read parameters for a simulation.
The default implemention is a do-nothing placeholder that throws an error if called, and must be re-implemented by subclasses.
Parameters
in input parameter stream
Reimplemented from Util::ParamComposite.
Reimplemented in Pscf::Rpg::BdSimulator< D >, and Pscf::Rpg::McSimulator< D >.
Definition at line 145 of file rpg/fts/simulator/Simulator.tpp.
simulate()
template<int D> void Pscf::Rpg::Simulator< D >::simulate (int nStep) virtual
Perform a field theoretic Monte-Carlo simulation.
Perform a field theoretic simulation of nSteps using the partial saddle-point approximation.
The default implemention is a do-nothing placeholder that throws an error if called, and must be re-implemented by subclasses.
Parameters
nStep number of simulation steps
Reimplemented in Pscf::Rpg::BdSimulator< D >, and Pscf::Rpg::McSimulator< D >.
Definition at line 176 of file rpg/fts/simulator/Simulator.tpp.
References UTIL_THROW.
analyze()
template<int D> void Pscf::Rpg::Simulator< D >::analyze (int min, int max, std::string classname, std::string filename) virtual
Read and analyze a trajectory file.
This function uses an instance of the TrajectoryReader class specified by the "classname" argument to read a trajectory file with the specified filename. The function opens the file, performs the analysis, and closes the file before returning.
The default implemention is a do-nothing placeholder that throws an error if called, and must be re-implemented by subclasses.
Parameters
min first frame number
max last frame number
classname name of TrajectoryReader class
filename name of trajectory file
Reimplemented in Pscf::Rpg::BdSimulator< D >, and Pscf::Rpg::McSimulator< D >.
Definition at line 183 of file rpg/fts/simulator/Simulator.tpp.
References UTIL_THROW.
clearData()
template<int D> void Pscf::Rpg::Simulator< D >::clearData () inline
Clear field eigen-components and hamiltonian components.
Immediately calling this function, hasHamiltonian(), hasWc(), hasCc(), and hasDc() will all return false.
Definition at line 1013 of file rpg/fts/simulator/Simulator.h.
outputTimers()
template<int D> void Pscf::Rpg::Simulator< D >::outputTimers (std::ostream & out) virtual
Output timing results.
Empty default implementation.
Parameters
out output stream
Reimplemented in Pscf::Rpg::BdSimulator< D >, and Pscf::Rpg::McSimulator< D >.
Definition at line 699 of file rpg/fts/simulator/Simulator.tpp.
outputMdeCounter()
template<int D> void Pscf::Rpg::Simulator< D >::outputMdeCounter (std::ostream & out) virtual
Output MDE counter.
Output the number of times the modified diffusion equation has been solved.
Parameters
out output stream
Definition at line 709 of file rpg/fts/simulator/Simulator.tpp.
clearTimers()
template<int D> void Pscf::Rpg::Simulator< D >::clearTimers () virtual
Clear timers.
Empty default implementation.
Reimplemented in Pscf::Rpg::McSimulator< D >.
Definition at line 721 of file rpg/fts/simulator/Simulator.tpp.
References UTIL_CHECK.
iStep()
template<int D> long Pscf::Rpg::Simulator< D >::iStep () inline
Return the current converged simulation step index.
Definition at line 1023 of file rpg/fts/simulator/Simulator.h.
iTotalStep()
template<int D> long Pscf::Rpg::Simulator< D >::iTotalStep () inline
Return the current simulation step index.
Definition at line 1028 of file rpg/fts/simulator/Simulator.h.
analyzeChi()
template<int D> void Pscf::Rpg::Simulator< D >::analyzeChi ()
Perform eigenvalue analysis of projected chi matrix.
Uses a chi matrix obtained from the Interaction member of the parent System.
Definition at line 298 of file rpg/fts/simulator/Simulator.tpp.
References Util::DArray< T >::allocate(), Util::DMatrix< Data >::allocate(), Util::Log::file(), and UTIL_CHECK.
chiEvals()
template<int D> DArray< double > const & Pscf::Rpg::Simulator< D >::chiEvals () const inline
Get an array of the eigenvalues of the projected chi matrix.
The projected chi matrix is given by the matrix product P*chi*P, where P is the symmetric projection matrix that projects onto the subspace orthogonal to the vector e = (1,1,...,1). The projected chi matrix is singular, and has a zero eigenvalue with associated eigenvector e. By convention, this zero eigenvalue and its eigenvector e are listed last, with index nMonomer - 1.
Definition at line 906 of file rpg/fts/simulator/Simulator.h.
chiEval()
template<int D> double Pscf::Rpg::Simulator< D >::chiEval (int a) const inline
Get a single eigenvalue of the projected chi matrix.
Parameters
a index of eigenvalue (0, ... , nMonomer - 1)
Definition at line 901 of file rpg/fts/simulator/Simulator.h.
chiEvecs() [1/2]
template<int D> DMatrix< double > const & Pscf::Rpg::Simulator< D >::chiEvecs () const inline
Get the matrix of all eigenvectors of the projected chi matrix.
This function returns the entire nMonomer x nMonomer matrix of the eigenvectors of the projected chi matrix, in which each row is an eigenvector. The first (row) index of this matrix thus identifies an eigenvector, while the second (column) index identifies the monomer type associated with one component of an eigen-vector.
Each eigenvector is normalized such that the sum of the squares of its elements is equal to nMonomer, the number of monomer types. The sign of each vector is chosen so as to make the first (0) component non-negative. The last eigenvector is always the null vector e = (1,1,...,1).
For the case nMonomer = 2 of an AB system, the resulting two eigenvectors are (1,-1) and (1,1).
Definition at line 911 of file rpg/fts/simulator/Simulator.h.
chiEvecs() [2/2]
template<int D> double Pscf::Rpg::Simulator< D >::chiEvecs (int a, int i) const inline
Get one element of an eigenvector of the projected chi matrix.
See documentation of chiEvecs(), which returns the entire matrix.
Parameters
a eigenvector index (0, ..., nMonomer - 1)
i monomoner type index (0, ..., nMonomer - 1)
Definition at line 916 of file rpg/fts/simulator/Simulator.h.
sc() [1/2]
template<int D> DArray< double > const & Pscf::Rpg::Simulator< D >::sc () const inline
Get all components of the vector S.
The value of component \(S_{a} \) may be expressed using Einstein summation convention as
\[ S_{a} \equiv \frac{1}{M^2} v_{ai}\chi_{ij}e_{j} \]
for any \(a = 0, \ldots, M - 1 \), where M = nMonomer (the number of monomer types), \(e_{j} =1 \) for any j, and \(v_{ai} \) is component associated with monomer type i of eigenvector a of the projected chi matrix, with the convention \(v_{ia} = e_{i} = 1 \) for a = nMonomer - 1.
Definition at line 921 of file rpg/fts/simulator/Simulator.h.
sc() [2/2]
template<int D> double Pscf::Rpg::Simulator< D >::sc (int a) const inline
Get a single component of the S vector.
This function retrieves on component of the vector defined in the documentation for function sc().
Parameters
a eigenvector index (0, ..., nMonomer - 1)
Definition at line 926 of file rpg/fts/simulator/Simulator.h.
computeHamiltonian()
template<int D> void Pscf::Rpg::Simulator< D >::computeHamiltonian ()
Compute the Hamiltonian used in field theoretic simulations.
Definition at line 192 of file rpg/fts/simulator/Simulator.tpp.
References Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::PolymerModel::isThread(), Pscf::PolymerTmpl< Block >::length(), Pscf::Rpg::Domain< D >::mesh(), Pscf::Rpg::Polymer< D >::mu(), Pscf::Species::mu(), Pscf::PolymerTmpl< Block >::nBead(), Pscf::MixtureTmpl< TP, TS >::nMonomer(), Pscf::MixtureTmpl< TP, TS >::nPolymer(), Pscf::MixtureTmpl< TP, TS >::nSolvent(), Pscf::Rpg::Polymer< D >::phi(), Pscf::Species::phi(), Pscf::MixtureTmpl< TP, TS >::polymer(), Pscf::SolventSpecies::size(), Pscf::MixtureTmpl< TP, TS >::solvent(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::Reduce::sum(), Pscf::Rpg::Domain< D >::unitCell(), UTIL_CHECK, and Pscf::MixtureTmpl< TP, TS >::vMonomer().
hamiltonian()
template<int D> double Pscf::Rpg::Simulator< D >::hamiltonian () const inline
Get the Hamiltonian used in field theoretic simulations.
This function returns the real, thermodynamically extensive Hamiltonian used in simulations based on partial saddle-point approximation.
Definition at line 936 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
idealHamiltonian()
template<int D> double Pscf::Rpg::Simulator< D >::idealHamiltonian () const inline
Get ideal gas contribution (-lnQ) to MC Hamiltonian.
Definition at line 944 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
fieldHamiltonian()
template<int D> double Pscf::Rpg::Simulator< D >::fieldHamiltonian () const inline
Get the quadratic field contribution (HW) to MC Hamiltonian.
Definition at line 952 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
perturbationHamiltonian()
template<int D> double Pscf::Rpg::Simulator< D >::perturbationHamiltonian () const inline
Get the perturbation to the standard Hamiltonian (if any).
A perturbation to the Hamiltonian, if any, is computed by an associated Perturbation object. When a perturbation exists, as indicated by the return value of hasPerturbation(), the perturbationHamiltonian component is added to the idealHamiltonian and fieldHamiltonian components to obtain the total value that is returned by hamiltonian() function.
Definition at line 960 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
hasHamiltonian()
template<int D> bool Pscf::Rpg::Simulator< D >::hasHamiltonian () const inline
Has the MC Hamiltonian been computed for current w and c fields?
Definition at line 931 of file rpg/fts/simulator/Simulator.h.
computeWc()
template<int D> void Pscf::Rpg::Simulator< D >::computeWc ()
Compute eigenvector components of the current w fields.
Compute and store the components of the values of the w fields on nodes of a real-space grid (r-grid) in a basis of the eigenvectors of the projected chi matrix. The component field \(W_{a}({\bf r}) \) at grid point \({\bf r} \) is given using Einstein summation by
\[ W_{a}({\bf r}) = v_{ai} w_{i}({\bf r}) / M \]
where \(w_{i}({\bf r}) \) is the w-field associated with monomer type \(i \), \(v_{ai} \) is eigenvector a of the projected chi matrix, and M = nMonomer.
Definition at line 466 of file rpg/fts/simulator/Simulator.tpp.
References Pscf::Prdc::Cuda::VecOp::addEqVc(), Pscf::Prdc::Cuda::VecOp::eqS(), and UTIL_CHECK.
wc() [1/2]
template<int D> DArray< RField< D > > const & Pscf::Rpg::Simulator< D >::wc () const inline
Get all eigenvector components of the current w fields.
This function returns a DArray of fields in which each field is a chemical field component \(W_{a}({\bf r}) \) as defined in the documentation of computeWc(), for a = 0, ..., nMonomer - 1.
Definition at line 968 of file rpg/fts/simulator/Simulator.h.
wc() [2/2]
template<int D> RField< D > const & Pscf::Rpg::Simulator< D >::wc (int a) const inline
Get one eigenvector component of the current w fields.
See documentation of functions computeWc() and wc() for details.
Parameters
a eigenvector index in range 0 , ..., nMonomer -1
Definition at line 973 of file rpg/fts/simulator/Simulator.h.
hasWc()
template<int D> bool Pscf::Rpg::Simulator< D >::hasWc () const inline
Are eigen-components of current w fields valid ?
Definition at line 978 of file rpg/fts/simulator/Simulator.h.
computeCc()
template<int D> void Pscf::Rpg::Simulator< D >::computeCc ()
Compute eigenvector components of the current c fields.
Compute and store the components of the values of the c fields on nodes of a real-space grid (r-grid) in a basis of the eigenvectors of the projected chi matrix.
Definition at line 505 of file rpg/fts/simulator/Simulator.tpp.
References Pscf::Prdc::Cuda::VecOp::addEqVc(), Pscf::Prdc::Cuda::VecOp::eqS(), and UTIL_CHECK.
cc() [1/2]
template<int D> DArray< RField< D > > const & Pscf::Rpg::Simulator< D >::cc () const inline
Get all eigenvector components of the current c fields.
Each component \(C_{a}({\bf r}) \) is a point-wise projection of the monomer c fields onto a corresponding eigenvector of the projected chi matrix. The resulting value \(C_{a}({\bf r}) \) for eigen-component a at grid point \({\bf r} \) is given using Einstein notation as
\[ C_{a}({\bf r}) = v_{ai} c_{i}({\bf r}) \]
where \(c_{i}({\bf r}) \) is the concentration / volume fraction field associated with monomer type i.
Note: The above definition \(C_{a} \) uses a different prefactor than that used to define the corresponding w-field component \(W_{a} \) given in the documentation of the function wc(), without the prefactor of 1/nMonomer. This is intentional, and is convenient for other aspects of the underlying theory.
Definition at line 983 of file rpg/fts/simulator/Simulator.h.
cc() [2/2]
template<int D> RField< D > const & Pscf::Rpg::Simulator< D >::cc (int a) const inline
Get one eigenvector component of the current c fields.
This returns a reference to a field \(C_{a}({\bf r}) \) as defined in the documentation of function cc().
Parameters
a eigenvector / eigenvalue index
Definition at line 988 of file rpg/fts/simulator/Simulator.h.
hasCc()
template<int D> bool Pscf::Rpg::Simulator< D >::hasCc () const inline
Are eigen-components of current c fields valid ?
Definition at line 993 of file rpg/fts/simulator/Simulator.h.
computeDc()
template<int D> void Pscf::Rpg::Simulator< D >::computeDc ()
Compute functional derivatives of the Hamiltonian.
Compute and store the functional derivatives of the field theoretic Hamiltonian with respect to eigenvector components of the w fields (i.e., with respect to components of wc).
Definition at line 546 of file rpg/fts/simulator/Simulator.tpp.
References Pscf::Rpg::VecOpFts::computeDField(), and UTIL_CHECK.
dc() [1/2]
template<int D> DArray< RField< D > > const & Pscf::Rpg::Simulator< D >::dc () const inline
Get all of the current d fields.
This function returns an array of fields in which element a is the functional derivative of the Hamiltonian H[W] with respect to the field component \(W_{a} \) that is returned by the function wc(a).
Definition at line 998 of file rpg/fts/simulator/Simulator.h.
dc() [2/2]
template<int D> RField< D > const & Pscf::Rpg::Simulator< D >::dc (int i) const inline
Get one eigenvector component of the current d fields.
Parameters
i eigenvector / eigenvalue index
Definition at line 1003 of file rpg/fts/simulator/Simulator.h.
hasDc()
template<int D> bool Pscf::Rpg::Simulator< D >::hasDc () const inline
Are the current d fields valid ?
Definition at line 1008 of file rpg/fts/simulator/Simulator.h.
saveState()
template<int D> void Pscf::Rpg::Simulator< D >::saveState ()
Save a copy of the fts move state.
This function and restoreState() are intended for use in the implementation of field theoretic moves. This function stores the current w fields and the corresponding Hamiltonian value. Current cc fields and dc fields are saved based on save policy. This is normally the first step of a fts move, prior to an attempted modification of the fields stored in the system w field container.
Definition at line 586 of file rpg/fts/simulator/Simulator.tpp.
References Pscf::Prdc::Cuda::VecOp::eqV(), and UTIL_CHECK.
restoreState()
template<int D> void Pscf::Rpg::Simulator< D >::restoreState ()
Restore the saved copy of the fts move state.
This function and saveState() are intended to be used together in the implementation of fts moves. If an attempted Monte-Carle move is rejected or an fts move fails to converge restoreState() is called to restore the fields and Hamiltonian value that were saved by a previous call to the function saveState().
Definition at line 641 of file rpg/fts/simulator/Simulator.tpp.
References Pscf::Prdc::Cuda::VecOp::eqV(), and UTIL_CHECK.
clearState()
template<int D> void Pscf::Rpg::Simulator< D >::clearState ()
Clear the saved copy of the fts state.
This function, restoreState(), and saveState() are intended to be used together in the implementation of fts moves. If an attempted move is accepted, clearState() is called to clear clear state_.hasData
Definition at line 692 of file rpg/fts/simulator/Simulator.tpp.
system()
template<int D> System< D > & Pscf::Rpg::Simulator< D >::system () inline
Get parent system by reference.
Definition at line 804 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
Referenced by Pscf::Rpg::BdSimulator< D >::BdSimulator(), Pscf::Rpg::McSimulator< D >::McSimulator(), Pscf::Rpg::RampParameter< D >::setSimulator(), and Pscf::Rpg::Simulator< D >::Simulator().
compressor()
template<int D> Compressor< D > & Pscf::Rpg::Simulator< D >::compressor () inline
Get the compressor by reference.
Definition at line 827 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
hasCompressor()
template<int D> bool Pscf::Rpg::Simulator< D >::hasCompressor () const inline
Does this Simulator have a Compressor object?
Definition at line 822 of file rpg/fts/simulator/Simulator.h.
random()
template<int D> Random & Pscf::Rpg::Simulator< D >::random () inline
Get random number generator by reference.
Definition at line 812 of file rpg/fts/simulator/Simulator.h.
cudaRandom()
template<int D> CudaRandom & Pscf::Rpg::Simulator< D >::cudaRandom () inline
Get cuda random number generator by reference.
Definition at line 817 of file rpg/fts/simulator/Simulator.h.
hasPerturbation()
template<int D> bool Pscf::Rpg::Simulator< D >::hasPerturbation () const inline
Does this Simulator have a Perturbation?
Definition at line 843 of file rpg/fts/simulator/Simulator.h.
perturbation() [1/2]
template<int D> Perturbation< D > const & Pscf::Rpg::Simulator< D >::perturbation () const inline
Get the associated Perturbation by const reference.
Definition at line 848 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
perturbation() [2/2]
template<int D> Perturbation< D > & Pscf::Rpg::Simulator< D >::perturbation () inline
Get the perturbation factory by non-const reference.
Definition at line 856 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
hasRamp()
template<int D> bool Pscf::Rpg::Simulator< D >::hasRamp () const inline
Does this Simulator have a Ramp?
Definition at line 872 of file rpg/fts/simulator/Simulator.h.
ramp() [1/2]
template<int D> Ramp< D > const & Pscf::Rpg::Simulator< D >::ramp () const inline
Get the associated Ramp by const reference.
Definition at line 877 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
ramp() [2/2]
template<int D> Ramp< D > & Pscf::Rpg::Simulator< D >::ramp () inline
Get the ramp by non-const reference.
Definition at line 885 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
readRandomSeed()
template<int D> void Pscf::Rpg::Simulator< D >::readRandomSeed (std::istream & in) protected
Read random seed and initialize random number generators.
Parameters
in input parameter stream
Definition at line 733 of file rpg/fts/simulator/Simulator.tpp.
compressorFactory()
template<int D> CompressorFactory< D > & Pscf::Rpg::Simulator< D >::compressorFactory () inline protected
Get the compressor factory by reference.
Definition at line 835 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
readCompressor()
template<int D> void Pscf::Rpg::Simulator< D >::readCompressor (std::istream & in, bool & isEnd) protected
Read the compressor block of the parameter file.
If isEnd is true on entry, this function returns without attempting to read the Compressor block.
Parameters
in input parameter stream
isEnd Has the end bracket of Simulator block been read?
Definition at line 749 of file rpg/fts/simulator/Simulator.tpp.
References Util::ParamComponent::echo(), Util::Log::file(), and UTIL_CHECK.
perturbationFactory()
template<int D> PerturbationFactory< D > & Pscf::Rpg::Simulator< D >::perturbationFactory () inline protected
Get the perturbation factory by reference.
Definition at line 864 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
readPerturbation()
template<int D> void Pscf::Rpg::Simulator< D >::readPerturbation (std::istream & in, bool & isEnd) protected
Optionally read an associated perturbation.
If isEnd is true on entry, this function returns without attempting to read the Perturbation block.
Parameters
in input parameter stream
isEnd Has the end bracket of Simulator block been read?
Definition at line 770 of file rpg/fts/simulator/Simulator.tpp.
References Util::ParamComponent::echo(), Util::Log::file(), and UTIL_CHECK.
setPerturbation()
template<int D> void Pscf::Rpg::Simulator< D >::setPerturbation (Perturbation< D > * ptr) protected
Set the associated perturbation.
Parameters
ptr pointer to a new Perturbation<D> object.
Definition at line 789 of file rpg/fts/simulator/Simulator.tpp.
References UTIL_CHECK.
rampFactory()
template<int D> RampFactory< D > & Pscf::Rpg::Simulator< D >::rampFactory () inline protected
Get the ramp factory by reference.
Definition at line 893 of file rpg/fts/simulator/Simulator.h.
References UTIL_CHECK.
readRamp()
template<int D> void Pscf::Rpg::Simulator< D >::readRamp (std::istream & in, bool & isEnd) protected
Optionally read an associated ramp.
If isEnd is true on entry, this function returns without attempting to read the Ramp block.
Parameters
in input parameter stream
isEnd Has the end bracket of Simulator block been read?
Definition at line 799 of file rpg/fts/simulator/Simulator.tpp.
References Util::ParamComponent::echo(), Util::Log::file(), and UTIL_CHECK.
setRamp()
template<int D> void Pscf::Rpg::Simulator< D >::setRamp (Ramp< D > * ptr) protected
Set the associated ramp.
Parameters
ptr pointer to a new Ramp<D> object.
Definition at line 818 of file rpg/fts/simulator/Simulator.tpp.
References UTIL_CHECK.
Member Data Documentation
random_
template<int D> Random Pscf::Rpg::Simulator< D >::random_ protected
Random number generator.
Definition at line 621 of file rpg/fts/simulator/Simulator.h.
cudaRandom_
template<int D> CudaRandom Pscf::Rpg::Simulator< D >::cudaRandom_ protected
Random number generator.
Definition at line 626 of file rpg/fts/simulator/Simulator.h.
wc_
template<int D> DArray< RField<D> > Pscf::Rpg::Simulator< D >::wc_ protected
Eigenvector components of w fields on a real space grid.
Each field component corresponds to a point-wise projection of w onto an eigenvector of the projected chi matrix.
Definition at line 634 of file rpg/fts/simulator/Simulator.h.
cc_
template<int D> DArray< RField<D> > Pscf::Rpg::Simulator< D >::cc_ protected
Eigenvector components of c fields on a real space grid.
Each field component corresponds to a point-wise projection of c onto an eigenvector of the projected chi matrix.
Definition at line 642 of file rpg/fts/simulator/Simulator.h.
dc_
template<int D> DArray< RField<D> > Pscf::Rpg::Simulator< D >::dc_ protected
Components of d fields on a real space grid.
Each field component is the functional derivative of H[W] with respect to one eigenvector w-field component.
Definition at line 650 of file rpg/fts/simulator/Simulator.h.
state_
template<int D> SimState<D> Pscf::Rpg::Simulator< D >::state_ mutable protected
State saved during fts simulation.
Definition at line 655 of file rpg/fts/simulator/Simulator.h.
hamiltonian_
template<int D> double Pscf::Rpg::Simulator< D >::hamiltonian_ protected
Field theoretic Hamiltonian H[W] (extensive value).
Definition at line 660 of file rpg/fts/simulator/Simulator.h.
idealHamiltonian_
template<int D> double Pscf::Rpg::Simulator< D >::idealHamiltonian_ protected
Ideal gas contribution (lnQ) to Hamiltonian H[W].
Definition at line 665 of file rpg/fts/simulator/Simulator.h.
fieldHamiltonian_
template<int D> double Pscf::Rpg::Simulator< D >::fieldHamiltonian_ protected
Field contribution (H_W) to Hamiltonian.
Definition at line 670 of file rpg/fts/simulator/Simulator.h.
perturbationHamiltonian_
template<int D> double Pscf::Rpg::Simulator< D >::perturbationHamiltonian_ protected
Perturbation to the standard Hamiltonian (if any).
A perturbation to the Hamiltonian, if any, is computed by an associated Perturbation object and added to the ideal and field components to obtain the total hamiltonian_ value.
Definition at line 679 of file rpg/fts/simulator/Simulator.h.
iStep_
template<int D> long Pscf::Rpg::Simulator< D >::iStep_ protected
Simulation step counter.
Definition at line 684 of file rpg/fts/simulator/Simulator.h.
iTotalStep_
template<int D> long Pscf::Rpg::Simulator< D >::iTotalStep_ protected
Simulation step counter.
Definition at line 689 of file rpg/fts/simulator/Simulator.h.
seed_
template<int D> long Pscf::Rpg::Simulator< D >::seed_ protected
Random number generator seed.
Definition at line 694 of file rpg/fts/simulator/Simulator.h.
hasHamiltonian_
template<int D> bool Pscf::Rpg::Simulator< D >::hasHamiltonian_ protected
Has the Hamiltonian been computed for the current w and c fields?
Definition at line 699 of file rpg/fts/simulator/Simulator.h.
hasWc_
template<int D> bool Pscf::Rpg::Simulator< D >::hasWc_ protected
Have eigen-components of the current w fields been computed ?
Definition at line 704 of file rpg/fts/simulator/Simulator.h.
hasCc_
template<int D> bool Pscf::Rpg::Simulator< D >::hasCc_ protected
Have eigen-components of the current c fields been computed ?
Definition at line 709 of file rpg/fts/simulator/Simulator.h.
hasDc_
template<int D> bool Pscf::Rpg::Simulator< D >::hasDc_ protected
Have functional derivatives of H[W] been computed ?
Definition at line 714 of file rpg/fts/simulator/Simulator.h.
The documentation for this class was generated from the following files:
rpg/fts/analyzer/AnalyzerFactory.h
rpg/fts/analyzer/AnalyzerManager.h
rpg/fts/analyzer/AverageAnalyzer.h
rpg/fts/analyzer/BinaryStructureFactorGrid.h
rpg/fts/analyzer/ChiDerivative.h
rpg/fts/analyzer/ConcentrationDerivative.h
rpg/fts/analyzer/ConcentrationWriter.h
rpg/fts/analyzer/FourthOrderParameter.h
rpg/fts/analyzer/HamiltonianAnalyzer.h
rpg/fts/analyzer/MaxOrderParameter.h
rpg/fts/analyzer/PerturbationDerivative.h
rpg/fts/analyzer/TrajectoryWriter.h
rpg/fts/perturbation/EinsteinCrystalPerturbation.h
rpg/fts/perturbation/Perturbation.h
rpg/fts/perturbation/PerturbationFactory.h
rpg/fts/ramp/LinearRamp.h
rpg/fts/ramp/Ramp.h
rpg/fts/ramp/RampFactory.h
rpg/fts/ramp/RampParameter.h
rpg/fts/simulator/Simulator.h
rpg/System.h
rpg/fts/simulator/Simulator.tpp