PSCF: Util::Str Class Reference
Util::Str Class Reference
Util namespace » Output Format
Wrapper for a std::string, for formatted ostream output.
#include <Str.h>
Public Member Functions
Constructors
Str ()
Default constructor.
Str (std::string value)
Constructor, set value only.
Str (std::string value, int width)
Constructor, set value and width.
Mutators
void setValue (std::string value)
Set the string value.
void setWidth (int width)
Set the default width.
Accessors
std::string value () const
Return string value.
int width () const
Return default string width.
std::istream & operator>> (std::istream &in, Str &object)
Input stream extractor for an Str object.
std::ostream & operator<< (std::ostream &out, const Str &object)
Output stream inserter for an Str object.
Detailed Description
Wrapper for a std::string, for formatted ostream output.
An Str object has std::string value, and an integer output field width. The << operator for an Str object uses the specified width. The value and width may both be specified as parameters to a constructor. If the width is not specified as a constructor parameter, it is set within the constructor to a default value given by Format::defaultWidth().
An Str object may be passed to an ostream as a temporary object. For example, the expression:
std::cout << Str("Hello") << Str("World", 20) << std::endl;
outputs "Hello" using the default width, followed by "World" in a field of width 20.
Definition at line 36 of file Str.h.
Constructor & Destructor Documentation
Str() [1/3]
Util::Str::Str ()
Default constructor.
Definition at line 17 of file Str.cpp.
Referenced by operator<<, and operator>>.
Str() [2/3]
Util::Str::Str (std::string value) explicit
Constructor, set value only.
Constructor, value only (explicit).
Parameters
value value of the string
Definition at line 23 of file Str.cpp.
References value().
Str() [3/3]
Util::Str::Str (std::string value, int width)
Constructor, set value and width.
Constructor, value and width.
Parameters
value value of the string
width default width (minimum number of characters)
Definition at line 29 of file Str.cpp.
References value(), and width().
Member Function Documentation
setValue()
void Util::Str::setValue (std::string value)
Set the string value.
Parameters
value value of the string
Definition at line 34 of file Str.cpp.
References value().
setWidth()
void Util::Str::setWidth (int width)
Set the default width.
Parameters
width default width (minimum number of characters)
Definition at line 37 of file Str.cpp.
References width().
value()
std::string Util::Str::value () const
Return string value.
Definition at line 40 of file Str.cpp.
Referenced by setValue(), Str(), and Str().
width()
int Util::Str::width () const
Return default string width.
Definition at line 43 of file Str.cpp.
Referenced by setWidth(), and Str().
Friends And Related Symbol Documentation
operator>>
std::istream & operator>> (std::istream & in, Str & object) friend
Input stream extractor for an Str object.
Parameters
in input stream
object Str object to be read from stream
Returns
modified input stream
Definition at line 49 of file Str.cpp.
References Str().
operator<<
std::ostream & operator<< (std::ostream & out, const Str & object) friend
Output stream inserter for an Str object.
Parameters
out output stream
object Str to be written to stream
Returns
modified output stream
Definition at line 58 of file Str.cpp.
References Str().
The documentation for this class was generated from the following files:
Str.h
Str.cpp