PSCF: Pscf::Fd1d::SystemAccess Class Reference
Pscf::Fd1d::SystemAccess Class Reference
Pscf namespace » Finite-Difference 1D
Streamlined accesss to an associated System.
#include <SystemAccess.h>
Public Member Functions
SystemAccess ()
Default constructor.
SystemAccess (System &system)
Constructor.
~SystemAccess ()
Destructor.
virtual void setSystem (System &system)
Set the system after construction.
Accessors (get objects by reference)
const System & system () const
Get parent System by reference.
System & system ()
Get parent System by reference.
const Mixture & mixture () const
Get Mixture by reference.
Mixture & mixture ()
Get Mixture by reference.
const Domain & domain () const
Get spatial domain (including grid info) by reference.
Domain & domain ()
Get spatial domain (including grid info) by reference.
const Interaction & interaction () const
Get interaction (i.e., excess free energy model) by reference.
Interaction & interaction ()
Get interaction (i.e., excess free energy model) by reference.
const Homogeneous::Mixture & homogeneous () const
Get homogeneous mixture (for reference calculations).
Homogeneous::Mixture & homogeneous ()
Get homogeneous mixture (for reference calculations).
FileMaster & fileMaster ()
Get FileMaster by reference.
Fields
DArray< System::WField > & wFields ()
Get array of all chemical potential fields.
System::WField & wField (int monomerId)
Get chemical potential field for a specific monomer type.
DArray< System::CField > & cFields ()
Get array of all chemical potential fields.
System::CField & cField (int monomerId)
Get chemical potential field for a specific monomer type.
Detailed Description
Streamlined accesss to an associated System.
Definition at line 23 of file SystemAccess.h.
Constructor & Destructor Documentation
Pscf::Fd1d::SystemAccess::SystemAccess ()
Default constructor.
Definition at line 18 of file SystemAccess.cpp.
Pscf::Fd1d::SystemAccess::SystemAccess (System & system)
Constructor.
Definition at line 25 of file SystemAccess.cpp.
Pscf::Fd1d::SystemAccess::~SystemAccess ()
Destructor.
Definition at line 32 of file SystemAccess.cpp.
Member Function Documentation
void Pscf::Fd1d::SystemAccess::setSystem (System & system) virtual
Set the system after construction.
Reimplemented in Pscf::Fd1d::Sweep.
Definition at line 38 of file SystemAccess.cpp.
References system().
Referenced by Pscf::Fd1d::Sweep::setSystem().
const System & Pscf::Fd1d::SystemAccess::system () const inline
Get parent System by reference.
Definition at line 154 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::NrIterator::computeJacobian(), Pscf::Fd1d::NrIterator::computeResidual(), Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::Sweep::outputSolution(), Pscf::Fd1d::MuSweep::outputSummary(), Pscf::Fd1d::CompositionSweep::outputSummary(), Pscf::Fd1d::LengthSweep::outputSummary(), Pscf::Fd1d::Sweep::outputSummary(), setSystem(), Pscf::Fd1d::NrIterator::solve(), and Pscf::Fd1d::Sweep::solve().
System & Pscf::Fd1d::SystemAccess::system () inline
Get parent System by reference.
Definition at line 163 of file SystemAccess.h.
References UTIL_ASSERT.
const Mixture & Pscf::Fd1d::SystemAccess::mixture () const inline
Get Mixture by reference.
Definition at line 172 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::HomogeneousComparison::compute(), Pscf::Fd1d::NrIterator::computeJacobian(), Pscf::Fd1d::NrIterator::computeResidual(), Pscf::Fd1d::FieldIo::extend(), Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::LengthSweep::outputSummary(), Pscf::Fd1d::CompositionSweep::outputSummary(), Pscf::Fd1d::MuSweep::outputSummary(), Pscf::Fd1d::Sweep::outputSummary(), Pscf::Fd1d::FieldIo::readFields(), Pscf::Fd1d::MuSweep::readParameters(), Pscf::Fd1d::CompositionSweep::readParameters(), Pscf::Fd1d::NrIterator::readParameters(), Pscf::Fd1d::FieldIo::remesh(), Pscf::Fd1d::NrIterator::residualNorm(), Pscf::Fd1d::MuSweep::setState(), Pscf::Fd1d::CompositionSweep::setState(), Pscf::Fd1d::LengthSweep::setState(), Pscf::Fd1d::LengthSweep::setup(), Pscf::Fd1d::CompositionSweep::setup(), Pscf::Fd1d::MuSweep::setup(), Pscf::Fd1d::NrIterator::solve(), Pscf::Fd1d::Sweep::solve(), Pscf::Fd1d::FieldIo::writeBlockCFields(), Pscf::Fd1d::FieldIo::writeFields(), Pscf::Fd1d::FieldIo::writeVertexQ(), and Pscf::Fd1d::HomogeneousComparison::~HomogeneousComparison().
Mixture & Pscf::Fd1d::SystemAccess::mixture () inline
Get Mixture by reference.
Definition at line 181 of file SystemAccess.h.
References UTIL_ASSERT.
const Domain & Pscf::Fd1d::SystemAccess::domain () const inline
Get spatial domain (including grid info) by reference.
Definition at line 190 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::HomogeneousComparison::compute(), Pscf::Fd1d::NrIterator::computeJacobian(), Pscf::Fd1d::NrIterator::computeResidual(), Pscf::Fd1d::FieldIo::extend(), Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::LengthSweep::outputSummary(), Pscf::Fd1d::MuSweep::outputSummary(), Pscf::Fd1d::CompositionSweep::outputSummary(), Pscf::Fd1d::Sweep::outputSummary(), Pscf::Fd1d::FieldIo::readFields(), Pscf::Fd1d::NrIterator::readParameters(), Pscf::Fd1d::FieldIo::remesh(), Pscf::Fd1d::NrIterator::residualNorm(), Pscf::Fd1d::NrIterator::solve(), Pscf::Fd1d::Sweep::solve(), Pscf::Fd1d::FieldIo::writeBlockCFields(), Pscf::Fd1d::FieldIo::writeFields(), and Pscf::Fd1d::FieldIo::writeVertexQ().
Domain & Pscf::Fd1d::SystemAccess::domain () inline
Get spatial domain (including grid info) by reference.
Definition at line 199 of file SystemAccess.h.
References UTIL_ASSERT.
const Interaction & Pscf::Fd1d::SystemAccess::interaction () const inline
Get interaction (i.e., excess free energy model) by reference.
Definition at line 208 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::HomogeneousComparison::compute().
Interaction & Pscf::Fd1d::SystemAccess::interaction () inline
Get interaction (i.e., excess free energy model) by reference.
Definition at line 217 of file SystemAccess.h.
References UTIL_ASSERT.
const Homogeneous::Mixture& Pscf::Fd1d::SystemAccess::homogeneous () const
Get homogeneous mixture (for reference calculations).
Referenced by Pscf::Fd1d::HomogeneousComparison::compute(), Pscf::Fd1d::HomogeneousComparison::output(), Pscf::Fd1d::LengthSweep::outputSummary(), Pscf::Fd1d::MuSweep::outputSummary(), and Pscf::Fd1d::CompositionSweep::outputSummary().
Homogeneous::Mixture & Pscf::Fd1d::SystemAccess::homogeneous () inline
Get homogeneous mixture (for reference calculations).
Definition at line 236 of file SystemAccess.h.
References UTIL_ASSERT.
FileMaster & Pscf::Fd1d::SystemAccess::fileMaster () inline
Get FileMaster by reference.
Definition at line 226 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::FieldIo::extend(), Pscf::Fd1d::Sweep::outputSolution(), Pscf::Fd1d::FieldIo::readFields(), Pscf::Fd1d::FieldIo::remesh(), Pscf::Fd1d::Sweep::solve(), Pscf::Fd1d::FieldIo::writeBlockCFields(), Pscf::Fd1d::FieldIo::writeFields(), and Pscf::Fd1d::FieldIo::writeVertexQ().
DArray< System::WField > & Pscf::Fd1d::SystemAccess::wFields () inline
Get array of all chemical potential fields.
The array capacity is equal to the number of monomer types.
Definition at line 246 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::Sweep::outputSolution(), Pscf::Fd1d::NrIterator::solve(), and Pscf::Fd1d::Sweep::solve().
System::WField & Pscf::Fd1d::SystemAccess::wField (int monomerId) inline
Get chemical potential field for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 256 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::NrIterator::computeJacobian().
DArray< System::CField > & Pscf::Fd1d::SystemAccess::cFields () inline
Get array of all chemical potential fields.
The array capacity is equal to the number of monomer types.
Definition at line 266 of file SystemAccess.h.
References UTIL_ASSERT.
Referenced by Pscf::Fd1d::Sweep::outputSolution(), and Pscf::Fd1d::NrIterator::solve().
System::CField & Pscf::Fd1d::SystemAccess::cField (int monomerId) inline
Get chemical potential field for a specific monomer type.
Parameters
monomerId integer monomer type index
Definition at line 275 of file SystemAccess.h.
References UTIL_ASSERT.
The documentation for this class was generated from the following files:
SystemAccess.h
SystemAccess.cpp