PSCF: Pscf::Prdc::Cpu::CField< D > Class Template Reference
Pscf::Prdc::Cpu::CField< D > Class Template Reference
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CPU)
Field of complex double precision values on an FFT mesh.
#include <CField.h>
Public Types
typedef fftw_complex ElementType
Type of each element.
typedef fftw_complex Complex
Complex number type.
typedef double Real
Real and imaginary parts of a Complex number.
Public Member Functions
CField ()
Default constructor.
CField (const CField &other)
Copy constructor.
virtual ~CField ()
Destructor.
CField & operator= (const CField &other)
Assignment operator.
void allocate (const IntVec< D > &meshDimensions)
Allocate the underlying C array for an FFT grid.
virtual void deallocate ()
Deallocate underlying C array and clear mesh dimensions.
const IntVec< D > & meshDimensions () const
Return mesh dimensions by constant reference.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Serialize a Field to/from an Archive.
Public Member Functions inherited from Pscf::Prdc::Cpu::FftwDArray< fftw_complex >
FftwDArray ()
Default constructor.
virtual ~FftwDArray ()
Destructor.
void allocate (int capacity)
Allocate the underlying C array.
bool isAllocated () const
Return true if the FftwDArray has been allocated, false otherwise.
void serialize (Archive &ar, const unsigned int version)
Serialize a FftwDArray to/from an Archive.
Public Member Functions inherited from Util::Array< fftw_complex >
virtual ~Array ()
Destructor.
int capacity () const
Return allocated size.
void begin (ArrayIterator< fftw_complex > &iterator)
Set an iterator to begin this Array.
void begin (ConstArrayIterator< fftw_complex > &iterator) const
Set a const iterator to begin this Array.
fftw_complex & operator[] (int i)
Get an element by non-const reference.
fftw_complex const & operator[] (int i) const
Get an element by const reference.
fftw_complex * cArray ()
Return a pointer to the underlying C array.
fftw_complex const * cArray () const
Return pointer to const to the underlying C array.
Additional Inherited Members
Protected Member Functions inherited from Util::Array< fftw_complex >
Array ()
Default constructor.
Protected Attributes inherited from Util::Array< fftw_complex >
fftw_complex * data_
Pointer to an array of Data elements.
int capacity_
Allocated size of the data_ array.
Detailed Description
template<int D>
class Pscf::Prdc::Cpu::CField< D >
Field of complex double precision values on an FFT mesh.
Definition at line 29 of file cpu/CField.h.
Member Typedef Documentation
ElementType
template<int D> fftw_complex Pscf::Prdc::Cpu::CField< D >::ElementType
Type of each element.
Definition at line 39 of file cpu/CField.h.
Complex
template<int D> fftw_complex Pscf::Prdc::Cpu::CField< D >::Complex
Complex number type.
Definition at line 44 of file cpu/CField.h.
Real
template<int D> double Pscf::Prdc::Cpu::CField< D >::Real
Real and imaginary parts of a Complex number.
Definition at line 49 of file cpu/CField.h.
Constructor & Destructor Documentation
CField() [1/2]
template<int D> Pscf::Prdc::Cuda::CField< D >::CField ()
Default constructor.
Definition at line 23 of file cpu/CField.tpp.
CField() [2/2]
template<int D> Pscf::Prdc::Cuda::CField< D >::CField (const CField< D > & other)
Copy constructor.
Allocates new memory and copies all elements by value.
Parameters
other the CField to be copied.
Definition at line 43 of file cpu/CField.tpp.
References Util::Array< Data >::capacity_, and Pscf::Prdc::Cpu::FftwDArray< Data >::isAllocated().
~CField()
template<int D> Pscf::Prdc::Cuda::CField< D >::~CField () virtual
Destructor.
Deletes underlying C array, if allocated previously.
Definition at line 32 of file cpu/CField.tpp.
Member Function Documentation
operator=()
template<int D> CField< D > & Pscf::Prdc::Cuda::CField< D >::operator= (const CField< D > & other)
Assignment operator.
If this Field is not allocated, allocates and copies all elements.
If this and the other Field are both allocated, the capacities must be exactly equal. If so, this method copies all elements.
Parameters
other the RHS CField
Definition at line 63 of file cpu/CField.tpp.
References Util::Array< Data >::capacity_, Util::Array< Data >::data_, Pscf::Prdc::Cpu::FftwDArray< Data >::isAllocated(), UTIL_CHECK, and UTIL_THROW.
allocate()
template<int D> void Pscf::Prdc::Cuda::CField< D >::allocate (const IntVec< D > & meshDimensions)
Allocate the underlying C array for an FFT grid.
Exceptions
Exception if the CField is already allocated.
Parameters
meshDimensions vector of numbers of grid points per direction
Definition at line 92 of file cpu/CField.tpp.
References Pscf::Prdc::Cpu::FftwDArray< Data >::allocate(), and UTIL_CHECK.
Referenced by Pscf::Prdc::Cuda::CField< D >::CField(), and Pscf::Prdc::Cpu::FFT< D >::setup().
deallocate()
template<int D> void Pscf::Prdc::Cpu::CField< D >::deallocate () virtual
Deallocate underlying C array and clear mesh dimensions.
Reimplemented from Pscf::Prdc::Cpu::FftwDArray< fftw_complex >.
Definition at line 107 of file cpu/CField.tpp.
References Pscf::Prdc::Cpu::FftwDArray< Data >::deallocate().
meshDimensions()
template<int D> const IntVec< D > & Pscf::Prdc::Cuda::CField< D >::meshDimensions () const inline
Return mesh dimensions by constant reference.
Definition at line 127 of file cpu/CField.h.
Referenced by Pscf::Prdc::Cuda::CField< D >::CField(), Pscf::Prdc::Cpu::FFT< D >::forwardTransform(), Pscf::Prdc::Cpu::FFT< D >::inverseTransform(), and Pscf::Prdc::Cpu::FFT< D >::setup().
serialize()
template<int D> template<class Archive > void Pscf::Prdc::Cuda::CField< D >::serialize (Archive & ar, const unsigned int version)
Serialize a Field to/from an Archive.
Parameters
ar archive
version archive version id
Definition at line 135 of file cpu/CField.h.
References Pscf::Prdc::Cpu::FftwDArray< Data >::serialize().
The documentation for this class was generated from the following files:
cpu/CField.h
cpu/CField.tpp
cuda/CField.h
cuda/CField.tpp