PSCF: Pscf::Pspc::Block< D > Class Template Reference
Pscf::Pspc::Block< D > Class Template Reference
Pscf namespace » Pseudo-Spectral Periodic (CPU) » Solvers
Block within a branched polymer.
#include <Block.h>
Public Types
typedef Propagator< D >::Field Field
Generic field (r-grid format).
typedef Propagator< D >::WField WField
Monomer chemical potential field (r-grid format).
typedef Propagator< D >::QField QField
Constrained partition function q(r,s) for fixed s.
Public Member Functions
Block ()
Constructor.
~Block ()
Destructor.
void setDiscretization (double ds, const Mesh< D > &mesh)
Initialize discretization and allocate required memory.
void setupUnitCell (const UnitCell< D > &unitCell)
Setup parameters that depend on the unit cell.
void setLength (double length)
Set or reset block length.
void setKuhn (double kuhn)
Set or reset monomer statistical segment length.
void setupSolver (WField const &w)
Set solver for this block.
void step (QField const &q, QField &qNew)
Compute one step of solution of MDE, from i to i+1.
void computeConcentration (double prefactor)
Compute concentration (volume fraction) for block by integration.
void computeStress (double prefactor)
Compute stress contribution for this block.
Mesh< D > const & mesh () const
Get associated spatial Mesh by const reference.
double ds () const
Get contour length step size.
int ns () const
Get the number of contour length steps in this block.
double stress (int n) const
Get derivative of free energy w/ respect to unit cell parameter n.
void setId (int id)
Set the id for this block.
void setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
void setMonomerId (int monomerId)
Set the monomer id.
virtual void setLength (double length)
Set the length of this block.
int id () const
Get the id of this block.
int monomerId () const
Get the monomer type id.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
double length () const
Get the length (number of monomers) in this block.
Public Member Functions inherited from Pscf::BlockTmpl< Propagator< D > >
BlockTmpl ()
Constructor.
virtual ~BlockTmpl ()
Destructor.
virtual void setKuhn (double kuhn)
Set monomer statistical segment length.
Propagator< D > & propagator (int directionId)
Get a Propagator for a specified direction.
Propagator< D > const & propagator (int directionId) const
Get a const Propagator for a specified direction.
TP::CField & cField ()
Get the associated monomer concentration field.
double kuhn () const
Get monomer statistical segment length.
Public Member Functions inherited from Pscf::BlockDescriptor
BlockDescriptor ()
Constructor.
virtual ~BlockDescriptor ()
Destructor.
template<class Archive >
void serialize (Archive &ar, unsigned int versionId)
Serialize to/from archive.
void setId (int id)
Set the id for this block.
void setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
void setMonomerId (int monomerId)
Set the monomer id.
void setPolymerType (PolymerType::Enum type)
Set the polymer type.
int id () const
Get the id of this block.
int monomerId () const
Get the monomer type id.
const Pair< int > & vertexIds () const
Get the pair of associated vertex ids.
int vertexId (int i) const
Get id of an associated vertex.
double length () const
Get the length (number of monomers) in this block.
PolymerType::Enum polymerType () const
Get the type of the parent polymer (branched or linear).
Detailed Description
template<int D>
class Pscf::Pspc::Block< D >
Block within a branched polymer.
Derived from BlockTmpl< Propagator<D> >. A BlockTmpl< Propagator<D> > has two Propagator<D> members and is derived from BlockDescriptor.
Definition at line 40 of file pspc/solvers/Block.h.
Member Typedef Documentation
Field
template<int D> typedef Propagator<D>::Field Pscf::Pspc::Block< D >::Field
Generic field (r-grid format).
Definition at line 50 of file pspc/solvers/Block.h.
WField
template<int D> typedef Propagator<D>::WField Pscf::Pspc::Block< D >::WField
Monomer chemical potential field (r-grid format).
Definition at line 55 of file pspc/solvers/Block.h.
QField
template<int D> typedef Propagator<D>::QField Pscf::Pspc::Block< D >::QField
Constrained partition function q(r,s) for fixed s.
Definition at line 60 of file pspc/solvers/Block.h.
Constructor & Destructor Documentation
Block()
template<int D> Pscf::Pspc::Block< D >::Block
Constructor.
Definition at line 31 of file pspc/solvers/Block.tpp.
References Pscf::BlockTmpl< Propagator< D > >::propagator().
~Block()
template<int D> Pscf::Pspc::Block< D >::~Block
Destructor.
Definition at line 47 of file pspc/solvers/Block.tpp.
Member Function Documentation
setDiscretization()
template<int D> void Pscf::Pspc::Block< D >::setDiscretization (double ds, const Mesh< D > & mesh)
Initialize discretization and allocate required memory.
Parameters
ds desired (optimal) value for contour length step
mesh spatial discretization mesh
Definition at line 51 of file pspc/solvers/Block.tpp.
References Pscf::Mesh< D >::dimensions(), Pscf::Mesh< D >::size(), and UTIL_CHECK.
setupUnitCell()
template<int D> void Pscf::Pspc::Block< D >::setupUnitCell (const UnitCell< D > & unitCell)
Setup parameters that depend on the unit cell.
This should be called once after every change in unit cell parameters. Internal variables that depend on the unit cell parameters are actually reset later, in in the setupSolver function just before solving the MDE, using a pointer to the unit cell that is set in this function. The associated UnitCell<D> object should thus not be modified after calling this function and before the MDEs are solved.
Parameters
unitCell unit cell, defining cell dimensions
Definition at line 140 of file pspc/solvers/Block.tpp.
setLength() [1/2]
template<int D> void Pscf::Pspc::Block< D >::setLength (double length) virtual
Set or reset block length.
Parameters
length new block length
Reimplemented from Pscf::BlockDescriptor.
Definition at line 116 of file pspc/solvers/Block.tpp.
References Pscf::BlockDescriptor::setLength(), and UTIL_CHECK.
setKuhn()
template<int D> void Pscf::Pspc::Block< D >::setKuhn (double kuhn) virtual
Set or reset monomer statistical segment length.
Parameters
kuhn new monomer statistical segment length.
Reimplemented from Pscf::BlockTmpl< Propagator< D > >.
Definition at line 130 of file pspc/solvers/Block.tpp.
setupSolver()
template<int D> void Pscf::Pspc::Block< D >::setupSolver (WField const & w)
Set solver for this block.
This should be called once after every change in w fields, the unit cell parameters, block length or kuhn lenght, before entering the loop used to solve the MDE for either propagator.
Parameters
w chemical potential field for this monomer type
step()
template<int D> void Pscf::Pspc::Block< D >::step (QField const & q, QField & qNew)
Compute one step of solution of MDE, from i to i+1.
This function is called internally by the PropagatorTmpl solve function within a loop over steps. It is implemented in the Block class because the same private data structures are needed for the two propagators associated with a Block.
Parameters
q input value of QField, from step i
qNew ouput value of QField, from step i+1
Definition at line 366 of file pspc/solvers/Block.tpp.
References Util::Array< Data >::capacity(), Util::DArray< Data >::isAllocated(), and UTIL_CHECK.
computeConcentration()
template<int D> void Pscf::Pspc::Block< D >::computeConcentration (double prefactor)
Compute concentration (volume fraction) for block by integration.
This should be called after both associated propagators are known. Upon return, grid point r of array cField() contains the integal, int ds q(r,s)q^{*}(r,L-s) times the prefactor parameter, where q(r,s) is the solution obtained from propagator(0), q^{*}(r,s) is the solution of propagator(1), and s is a contour variable that is integrated over the domain 0 < s < length(), where length() is the block length. The "prefactor" parameter should be set to prefactor = phi/(L q), where phi is the overall volume fraction for this molecular species, L is the total number of monomers in the species, and q is the species partition function, i.e., the spatial average of q(r,L). This function is called by Polymer<D>::compute().
Parameters
prefactor constant multiplying integral over s
Definition at line 201 of file pspc/solvers/Block.tpp.
References UTIL_CHECK.
computeStress()
template<int D> void Pscf::Pspc::Block< D >::computeStress (double prefactor)
Compute stress contribution for this block.
This function is called by Polymer<D>::computeStress. The prefactor parameter should be the same as that passed to function computeConcentration.
Parameters
prefactor constant multiplying integral over s
Definition at line 253 of file pspc/solvers/Block.tpp.
References Util::FSArray< Data, Capacity >::append(), and UTIL_CHECK.
mesh()
template<int D> Mesh< D > const & Pscf::Pspc::Block< D >::mesh inline
Get associated spatial Mesh by const reference.
Get Mesh by reference.
Definition at line 305 of file pspc/solvers/Block.h.
References UTIL_ASSERT.
ds()
template<int D> double Pscf::Pspc::Block< D >::ds inline
Get contour length step size.
Get number of contour steps.
Definition at line 295 of file pspc/solvers/Block.h.
ns()
template<int D> int Pscf::Pspc::Block< D >::ns inline
Get the number of contour length steps in this block.
Get number of contour steps.
Definition at line 290 of file pspc/solvers/Block.h.
stress()
template<int D> double Pscf::Pspc::Block< D >::stress (int n) const inline
Get derivative of free energy w/ respect to unit cell parameter n.
Stress with respect to unit cell parameter n.
This function returns a value computed by a previous call to the computeStress function.
Parameters
n index of unit cell parameter
Definition at line 300 of file pspc/solvers/Block.h.
setId()
template<int D> void Pscf::BlockDescriptor::setId (int id)
Set the id for this block.
Parameters
id integer index for this block
Definition at line 64 of file BlockDescriptor.cpp.
setVertexIds()
template<int D> void Pscf::BlockDescriptor::setVertexIds (int vertexAId, int vertexBId)
Set indices of associated vertices.
Parameters
vertexAId integer id of vertex A
vertexBId integer id of vertex B
Definition at line 72 of file BlockDescriptor.cpp.
setMonomerId()
template<int D> void Pscf::BlockDescriptor::setMonomerId (int monomerId)
Set the monomer id.
Parameters
monomerId integer id of monomer type (>=0)
Definition at line 79 of file BlockDescriptor.cpp.
setLength() [2/2]
template<int D> void Pscf::BlockDescriptor::setLength (double length) virtual
Set the length of this block.
The ``length" is steric volume / reference volume.
Parameters
length block length (number of monomers).
Reimplemented from Pscf::BlockDescriptor.
Definition at line 88 of file BlockDescriptor.cpp.
id()
template<int D> int Pscf::BlockDescriptor::id () const inline
Get the id of this block.
Definition at line 114 of file BlockDescriptor.h.
monomerId()
template<int D> int Pscf::BlockDescriptor::monomerId () const inline
Get the monomer type id.
Definition at line 119 of file BlockDescriptor.h.
vertexIds()
template<int D> const Pair< int > & Pscf::BlockDescriptor::vertexIds () const inline
Get the pair of associated vertex ids.
Definition at line 124 of file BlockDescriptor.h.
vertexId()
template<int D> int Pscf::BlockDescriptor::vertexId (int i) const inline
Get id of an associated vertex.
Parameters
i index of vertex (0 or 1)
Definition at line 131 of file BlockDescriptor.h.
length()
template<int D> double Pscf::BlockDescriptor::length () const inline
Get the length (number of monomers) in this block.
Definition at line 136 of file BlockDescriptor.h.
The documentation for this class was generated from the following files:
pspc/solvers/Block.h
pspc/solvers/Block.tpp