PSCF: Pscf::Rpc::SweepParameter< D > Class Template Reference
Pscf::Rpc::SweepParameter< D > Class Template Reference
Pscf namespace » Pscf::Rpc - Real Periodic Fields (CPU) » Self-Consistent Field Theory (SCFT) » Sweep
Class for storing data about an individual sweep parameter.
#include <SweepParameter.h>
Public Member Functions
SweepParameter ()
Default constructor.
SweepParameter (System< D > &system)
Constructor that stores a pointer to parent system.
void setSystem (System< D > &system)
Set the system associated with this object.
void setParameterTypesArray (GArray< ParameterType > &array)
Set the pointer to the array of specialized sweep parameter types.
ParameterType & parameterType () const
Get the ParameterType object for a specialized sweep parameter.
int parameterTypeId () const
Get the array index for the specialized sweep parameter.
bool isSpecialized () const
Is this SweepParameter a specialized parameter type?
void getInitial ()
Get and store initial value of this parameter.
void update (double newVal)
Update the corresponding parameter value in the System.
std::string type () const
Return a string representation of the parameter type.
void writeParamType (std::ostream &out) const
Write the parameter type to an output stream.
int id (int i) const
Get id for a sub-object or element to which this is applied.
int nId () const
Number of indices associated with this type of parameter.
double current ()
Get the current system parameter value.
double initial () const
Get the initial system parameter value.
double change () const
Get the total change planned for this parameter during sweep.
template<class Archive>
void serialize (Archive ar, const unsigned int version)
Serialize to or from an archive.
Detailed Description
template<int D>
class Pscf::Rpc::SweepParameter< D >
Class for storing data about an individual sweep parameter.
This class stores the information required to sweep a single parameter value of any of several types. The type of parameter is indicated in the public interface and parameter file format by a string identifier with any of several allowed values. Each parameter is also identified by one or two associated index values, denoted here by id(0) and id(1), that specify the index or indices for a subobject or array element with which the parameter is associated applied. Allowed string representations and meanings of parameter types are given below, along with the meaning of any associated index value or pair of values. To indicate the meaning of index values, we use mId to denote a monomer type index, pId to denote a polymer species index, bId to denote the index of a block within a polymer, sId to denote a solvent species index, lId to denote a lattice parameter index, and wId to denote a wall index:
| Type        | Meaning                            | id(0) | id(1)
| ----------- | ---------------------------------- | ----- | -----
| kuhn        | monomer segment length             | mId   |
| chi         | Flory-Huggins parameter            | mId   | mId
| block       | block length                       | pId   | bId
| solvent     | solvent size                       | sId   |
| phi_polymer | polymer volume fraction            | pId   |
| mu_polymer  | polymer chemical potential         | pId   |
| phi_solvent | solvent volume fraction            | sId   |
| mu_solvent  | solvent chemical potential         | sId   |
| cell_param  | lattice parameter                  | lId   |
| chi_bottom  | thin film wall/monomer interaction | mId   |
| chi_top     | thin film wall/monomer interaction | mId   |
The two indices for a Flory-Huggins chi parameter refer to indices in the chi matrix maintained by Interaction. Changes to element chi(i, j) automatically also update chi(j, i) for i !\ j, thus maintaining the symmetry of the matrix.
Each SweepParameter also has a "change" value that gives the intended difference between the final and initial value of the parameter over the course of a sweep, corresponding to a change sweep parameter s over the range [0,1]. The initial value of each parameter is obtained from a query of the state of the parent system at the beginning of a sweep, and thus does not need to be supplied as part of the text format for a SweepParameter.
A SweepParameter<D> object is initialized by reading the parameter type, index or index and change value from a parameter file as a a single line. An overloaded >> operator is defined that allows a SweepParameter<D> object named "parameter" to be read from an istream named "in" using the syntax "in >> parameter".
The text format for a parameter of a type that requires a single index id(0) is:
type id(0) change
where type indicates a type string, id(0) is an integer index value, and change is the a floating point value for the change in parameter value. The corresponding format for a parameter that requires two indices (e.g., block or chi) is instead: "type id(0) id(1) change".
Most of the parameter types in the table above are hard-coded into this class, but certain classes can also add "specialized" parameters to the list SweepTmpl::parameterTypes_ using the method SweepTmpl::addParameterTypes. This list of specialized parameters is then consulted if the user-specified parameter type is not found in the list of hard-coded parameter names. In order to add parameters to SweepTmpl::parameterTypes_, a class must be a subclass of ParameterModifier.
Currently, the only classes that can add parameters to parameterTypes_ are Iterators. The Iterator for a given calculation is determined via a Factory, so the type of Iterator is not known until run time. Therefore, Iterators can add sweepable parameters to parameterTypes_ as necessary at run time, depending on the type of Iterator used in that calculation. As a design principle, an object that is created by a Factory and used for SCFT calculations should also be a subclass of ParameterModifier so that it can add sweepable parameters at run time.
Definition at line 104 of file rpc/scft/sweep/SweepParameter.h.
Constructor & Destructor Documentation
SweepParameter() [1/2]
template<int D> Pscf::Rpc::SweepParameter< D >::SweepParameter ()
Default constructor.
Definition at line 34 of file rpc/scft/sweep/SweepParameter.tpp.
References SweepParameter().
Referenced by SweepParameter(), and SweepParameter().
SweepParameter() [2/2]
template<int D> Pscf::Rpc::SweepParameter< D >::SweepParameter (System< D > & system)
Constructor that stores a pointer to parent system.
Parameters
system parent system
Definition at line 49 of file rpc/scft/sweep/SweepParameter.tpp.
References SweepParameter().
Member Function Documentation
setSystem()
template<int D> void Pscf::Rpc::SweepParameter< D >::setSystem (System< D > & system) inline
Set the system associated with this object.
Invoke this function on objects created with the default constructor to create an association with a parent system.
Parameters
system parent system
Definition at line 129 of file rpc/scft/sweep/SweepParameter.h.
setParameterTypesArray()
template<int D> void Pscf::Rpc::SweepParameter< D >::setParameterTypesArray (GArray< ParameterType > & array) inline
Set the pointer to the array of specialized sweep parameter types.
Parameters
array array of specialized parameter types
Definition at line 137 of file rpc/scft/sweep/SweepParameter.h.
parameterType()
template<int D> ParameterType & Pscf::Rpc::SweepParameter< D >::parameterType () const
Get the ParameterType object for a specialized sweep parameter.
An error will result if this SweepParameter is not specialized and this function is called.
Definition at line 136 of file rpc/scft/sweep/SweepParameter.tpp.
References isSpecialized(), and UTIL_CHECK.
Referenced by type().
parameterTypeId()
template<int D> int Pscf::Rpc::SweepParameter< D >::parameterTypeId () const inline
Get the array index for the specialized sweep parameter.
Definition at line 151 of file rpc/scft/sweep/SweepParameter.h.
isSpecialized()
template<int D> bool Pscf::Rpc::SweepParameter< D >::isSpecialized () const inline
Is this SweepParameter a specialized parameter type?
Definition at line 157 of file rpc/scft/sweep/SweepParameter.h.
Referenced by parameterType().
getInitial()
template<int D> void Pscf::Rpc::SweepParameter< D >::getInitial ()
Get and store initial value of this parameter.
This function is called before a sweep begins, and simply gets current values of this parameter.
Definition at line 147 of file rpc/scft/sweep/SweepParameter.tpp.
update()
template<int D> void Pscf::Rpc::SweepParameter< D >::update (double newVal)
Update the corresponding parameter value in the System.
Parameters
newVal new value for this parameter (input)
Definition at line 154 of file rpc/scft/sweep/SweepParameter.tpp.
type()
template<int D> std::string Pscf::Rpc::SweepParameter< D >::type () const
Return a string representation of the parameter type.
Definition at line 161 of file rpc/scft/sweep/SweepParameter.tpp.
References parameterType(), and UTIL_THROW.
Referenced by writeParamType().
writeParamType()
template<int D> void Pscf::Rpc::SweepParameter< D >::writeParamType (std::ostream & out) const
Write the parameter type to an output stream.
Parameters
out output file stream
Definition at line 129 of file rpc/scft/sweep/SweepParameter.tpp.
References type().
Referenced by Pscf::Rpc::operator<<().
id()
template<int D> int Pscf::Rpc::SweepParameter< D >::id (int i) const inline
Get id for a sub-object or element to which this is applied.
This function returns a value from the id_ array. Elements of array store indices associating with a parameter value, which may, for example, identify a molecule type index, one or more monomer type indices or a unit cell parameter index.
Different types of parameters require either 1 or 2 such identifiers. The number of required identifiers is returned by the function nId().
Parameters
i array index to access
Definition at line 201 of file rpc/scft/sweep/SweepParameter.h.
References UTIL_CHECK.
Referenced by Pscf::Rpc::operator<<().
nId()
template<int D> int Pscf::Rpc::SweepParameter< D >::nId () const inline
Number of indices associated with this type of parameter.
See documentation of id(int).
Definition at line 212 of file rpc/scft/sweep/SweepParameter.h.
current()
template<int D> double Pscf::Rpc::SweepParameter< D >::current () inline
Get the current system parameter value.
Definition at line 218 of file rpc/scft/sweep/SweepParameter.h.
initial()
template<int D> double Pscf::Rpc::SweepParameter< D >::initial () const inline
Get the initial system parameter value.
Definition at line 224 of file rpc/scft/sweep/SweepParameter.h.
change()
template<int D> double Pscf::Rpc::SweepParameter< D >::change () const inline
Get the total change planned for this parameter during sweep.
Definition at line 230 of file rpc/scft/sweep/SweepParameter.h.
serialize()
template<int D> template<class Archive> void Pscf::Rpc::SweepParameter< D >::serialize (Archive ar, const unsigned int version)
Serialize to or from an archive.
Parameters
ar Archive object
version archive format version index
Definition at line 262 of file rpc/scft/sweep/SweepParameter.tpp.
References Util::serializeEnum().
The documentation for this class was generated from the following files:
rpc/scft/sweep/SweepParameter.h
rpc/scft/sweep/SweepParameter.tpp