PSCF: Pscf::Pspg::KFieldComparison< D > Class Template Reference
Pscf::Pspg::KFieldComparison< D > Class Template Reference
Pscf namespace » Periodic (GPU) » Fields
Comparator for RDFieldDft (k-grid) arrays.
#include <KFieldComparison.h>
Public Member Functions
KFieldComparison ()
Default constructor.
double compare (RDFieldDft< D > const &a, RDFieldDft< D > const &b)
Compare individual fields.
double compare (DArray< RDFieldDft< D > > const &a, DArray< RDFieldDft< D > > const &b)
Compare arrays of fields associated with different monomer types.
double maxDiff () const
Return the precomputed maximum element-by-element difference.
double rmsDiff () const
Return the precomputed root-mean-squared difference.
Detailed Description
template<int D>
class Pscf::Pspg::KFieldComparison< D >
Comparator for RDFieldDft (k-grid) arrays.
Definition at line 26 of file pspg/field/KFieldComparison.h.
Constructor & Destructor Documentation
KFieldComparison()
template<int D> Pscf::Pspg::KFieldComparison< D >::KFieldComparison
Default constructor.
Initializes maxDiff and rmsDiff to zero.
Definition at line 19 of file pspg/field/KFieldComparison.tpp.
Member Function Documentation
compare() [1/2]
template<int D> double Pscf::Pspg::KFieldComparison< D >::compare (RDFieldDft< D > const & a, RDFieldDft< D > const & b)
Compare individual fields.
Array dimensions must agree. An Exception is thrown if the capacities of fields a and b are not equal.
Parameters
a 1st field
b 2nd field
Returns
maximum element-by-element difference (maxDiff)
Definition at line 26 of file pspg/field/KFieldComparison.tpp.
References Pscf::Pspg::DField< Data >::capacity(), Pscf::Pspg::DField< Data >::cDField(), and UTIL_CHECK.
compare() [2/2]
template<int D> double Pscf::Pspg::KFieldComparison< D >::compare (DArray< RDFieldDft< D > > const & a, DArray< RDFieldDft< D > > const & b)
Compare arrays of fields associated with different monomer types.
All array dimensions must agree.
An exception is thrown if the capacities of the enclosing DArrays (the number of monomers) are not equal or if the capacities of any pair of individual fields (number of grid points or basis functions) are not equal.
Parameters
a 1st DArray of field
b 2nd DArray of field
Returns
maximum element-by-element difference (maxDiff)
Definition at line 58 of file pspg/field/KFieldComparison.tpp.
References Util::DArray< Data >::allocate(), Util::Array< Data >::capacity(), and UTIL_CHECK.
maxDiff()
template<int D> double Pscf::Pspg::KFieldComparison< D >::maxDiff () const inline
Return the precomputed maximum element-by-element difference.
This function returns the maximum difference between corresponding field array elements found by the most recent comparison.
Definition at line 74 of file pspg/field/KFieldComparison.h.
rmsDiff()
template<int D> double Pscf::Pspg::KFieldComparison< D >::rmsDiff () const inline
Return the precomputed root-mean-squared difference.
This function returns the root-mean-squared difference between corresponding elements found by the most recent comparison.
Definition at line 83 of file pspg/field/KFieldComparison.h.
The documentation for this class was generated from the following files:
pspg/field/KFieldComparison.h
pspg/field/KFieldComparison.tpp