PSCF: Complex Arithmetic (CPU)
Complex Arithmetic (CPU)
Pscf namespace » Pscf::Prdc - Periodic Systems » Fields and FFT (CPU)
Functions
template<>
double Pscf::real< fftw_complex, double > (fftw_complex const &a)
Return the real part of a complex number.
template<>
double Pscf::imag< fftw_complex, double > (fftw_complex const &a)
Return the imaginary part of a complex number.
template<>
double Pscf::abs< fftw_complex, double > (fftw_complex const &a)
Return absolute magnitude of a complex number.
template<>
double Pscf::absSq< fftw_complex, double > (fftw_complex const &a)
Return square of absolute magnitude of a complex number.
template<>
void Pscf::conj (fftw_complex &z, fftw_complex const &a)
Compute complex conjugate, z = a^*.
template<>
void Pscf::conj (fftw_complex &a)
In-place complex conjugation of a complex number, a = a^* .
template<>
void Pscf::assign (fftw_complex &z, double const &a, double const &b)
Create a complex number from real and imaginary parts, z = a + ib.
template<>
void Pscf::assign (fftw_complex &z, double const &a)
Assign a real input to a complex variable.
template<>
void Pscf::assign (fftw_complex &z, fftw_complex const &a)
Assign a complex input to a complex variable.
template<>
void Pscf::assign (fftw_complex &z, std::complex< double > const &a)
Assign a std::complex input to a complex variable.
template<>
void Pscf::assign (std::complex< double > &z, fftw_complex const &a)
Assign a complex input to a std::complex variable.
template<>
void Pscf::add (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Addition of two complex numbers, z = a + b.
template<>
void Pscf::add (fftw_complex &z, fftw_complex const &a, double const &b)
Addition of a complex and real number, z = a + b.
template<>
void Pscf::addEq (fftw_complex &a, fftw_complex const &b)
In place addition of complex numbers, a += b.
template<>
void Pscf::addEq (fftw_complex &a, double const &b)
In place addition of a complex and real number, a += b.
template<>
void Pscf::sub (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Subtraction of two complex numbers, z = a - b.
template<>
void Pscf::sub (fftw_complex &z, fftw_complex const &a, double const &b)
Subtraction of a real number from a complex number, z = a - b.
template<>
void Pscf::subEq (fftw_complex &a, fftw_complex const &b)
In place subtraction of two complex numbers, a -= b.
template<>
void Pscf::subEq (fftw_complex &a, double const &b)
In place subtraction of real number from a complex number, a -= b.
template<>
double Pscf::absSqDiff (fftw_complex const &a, fftw_complex const &b)
Return square of the absolute magnitude of a complex difference.
template<>
void Pscf::mul (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Multiplication of two complex numbers, z = a * b.
template<>
void Pscf::mul (fftw_complex &z, fftw_complex const &a, double const &b)
Multiplication of complex and real numbers, z = a * b.
template<>
void Pscf::mulEq (fftw_complex &a, fftw_complex const &b)
In place multiplication of two complex number, a *= b.
template<>
void Pscf::mulEq (fftw_complex &a, double const &b)
In place multiplication of a complex and real number, a *= b.
template<>
void Pscf::square (fftw_complex &z, fftw_complex const &a)
Compute complex square of a complex number, z = a * a.
template<>
void Pscf::div (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Division of two complex numbers, z = a / b .
template<>
void Pscf::div (fftw_complex &z, fftw_complex const &a, double const &b)
Division of a complex number by a real number, z = a / b .
template<>
void Pscf::divEq (fftw_complex &a, fftw_complex const &b)
In place division of two complex number, a /= b.
template<>
void Pscf::divEq (fftw_complex &a, double const &b)
In place division of a complex number by a real number, a /= b.
Detailed Description
Typdedefs and functions for complex arithmetic using the complex type fftw_complex defined by FFTW.
Function Documentation
real< fftw_complex, double >()
template<> double Pscf::real< fftw_complex, double > (fftw_complex const & a) inline
Return the real part of a complex number.
Parameters
a complex argument (input)
Definition at line 34 of file prdc/cpu/complex.h.
imag< fftw_complex, double >()
template<> double Pscf::imag< fftw_complex, double > (fftw_complex const & a) inline
Return the imaginary part of a complex number.
Parameters
a complex argument (input)
Definition at line 45 of file prdc/cpu/complex.h.
abs< fftw_complex, double >()
template<> double Pscf::abs< fftw_complex, double > (fftw_complex const & a) inline
Return absolute magnitude of a complex number.
Parameters
a complex argument (in)
Definition at line 58 of file prdc/cpu/complex.h.
absSq< fftw_complex, double >()
template<> double Pscf::absSq< fftw_complex, double > (fftw_complex const & a) inline
Return square of absolute magnitude of a complex number.
Parameters
a complex argument (in)
Definition at line 69 of file prdc/cpu/complex.h.
Referenced by Pscf::absSqDiff().
conj() [1/2]
template<> void Pscf::conj (fftw_complex & z, fftw_complex const & a) inline
Compute complex conjugate, z = a^*.
Parameters
z complex conjugate of argument (out)
a complex argument (in)
Definition at line 83 of file prdc/cpu/complex.h.
conj() [2/2]
template<> void Pscf::conj (fftw_complex & a) inline
In-place complex conjugation of a complex number, a = a^* .
Parameters
a argument (in) and complex conjugate (out)
Definition at line 97 of file prdc/cpu/complex.h.
assign() [1/5]
template<> void Pscf::assign (fftw_complex & z, double const & a, double const & b) inline
Create a complex number from real and imaginary parts, z = a + ib.
Parameters
z complex (out)
a real part (in)
b imaginary part (in)
Definition at line 115 of file prdc/cpu/complex.h.
assign() [2/5]
template<> void Pscf::assign (fftw_complex & z, double const & a) inline
Assign a real input to a complex variable.
Parameters
z complex (out)
a real (in)
Definition at line 130 of file prdc/cpu/complex.h.
assign() [3/5]
template<> void Pscf::assign (fftw_complex & z, fftw_complex const & a) inline
Assign a complex input to a complex variable.
Parameters
z complex (out)
a complex (in)
Definition at line 145 of file prdc/cpu/complex.h.
assign() [4/5]
template<> void Pscf::assign (fftw_complex & z, std::complex< double > const & a) inline
Assign a std::complex input to a complex variable.
Parameters
z complex (out)
a std::complex (in)
Definition at line 160 of file prdc/cpu/complex.h.
assign() [5/5]
template<> void Pscf::assign (std::complex< double > & z, fftw_complex const & a) inline
Assign a complex input to a std::complex variable.
Parameters
z std::complex (out)
a complex (in)
Definition at line 175 of file prdc/cpu/complex.h.
add() [1/2]
template<> void Pscf::add (fftw_complex & z, fftw_complex const & a, fftw_complex const & b) inline
Addition of two complex numbers, z = a + b.
Parameters
z complex sum (out)
a complex summand (in)
b complex summand (in)
Definition at line 190 of file prdc/cpu/complex.h.
add() [2/2]
template<> void Pscf::add (fftw_complex & z, fftw_complex const & a, double const & b) inline
Addition of a complex and real number, z = a + b.
Parameters
z complex sum (out)
a complex summand (in)
b real summand (in)
Definition at line 206 of file prdc/cpu/complex.h.
addEq() [1/2]
template<> void Pscf::addEq (fftw_complex & a, fftw_complex const & b) inline
In place addition of complex numbers, a += b.
Parameters
a complex summand (in) and sum (out)
b complex summand (in)
Definition at line 221 of file prdc/cpu/complex.h.
addEq() [2/2]
template<> void Pscf::addEq (fftw_complex & a, double const & b) inline
In place addition of a complex and real number, a += b.
Parameters
a complex summand (in) and sum (out)
b real summand (in)
Definition at line 236 of file prdc/cpu/complex.h.
sub() [1/2]
template<> void Pscf::sub (fftw_complex & z, fftw_complex const & a, fftw_complex const & b) inline
Subtraction of two complex numbers, z = a - b.
Parameters
z complex difference (out)
a complex 1st argument (in)
b complex 2nd argument (in)
Definition at line 253 of file prdc/cpu/complex.h.
sub() [2/2]
template<> void Pscf::sub (fftw_complex & z, fftw_complex const & a, double const & b) inline
Subtraction of a real number from a complex number, z = a - b.
Parameters
z complex difference (out)
a complex 1st argument (in)
b real 2nd argument (in)
Definition at line 269 of file prdc/cpu/complex.h.
subEq() [1/2]
template<> void Pscf::subEq (fftw_complex & a, fftw_complex const & b) inline
In place subtraction of two complex numbers, a -= b.
Parameters
a complex argument (in) and difference (out)
b complex argument (in)
Definition at line 284 of file prdc/cpu/complex.h.
subEq() [2/2]
template<> void Pscf::subEq (fftw_complex & a, double const & b) inline
In place subtraction of real number from a complex number, a -= b.
Parameters
a complex argument (in) and difference (out)
b real argument (in)
Definition at line 299 of file prdc/cpu/complex.h.
absSqDiff()
template<> double Pscf::absSqDiff (fftw_complex const & a, fftw_complex const & b) inline
Return square of the absolute magnitude of a complex difference.
This function returns |a-b|^2 for complex a and b.
Parameters
a complex 1st argument (in)
b complex 2nd argument (in)
Definition at line 315 of file prdc/cpu/complex.h.
References Pscf::absSq< fftw_complex, double >(), and Pscf::sub().
mul() [1/2]
template<> void Pscf::mul (fftw_complex & z, fftw_complex const & a, fftw_complex const & b) inline
Multiplication of two complex numbers, z = a * b.
Parameters
z complex product (out)
a complex factor (in)
b complex factor (in)
Definition at line 334 of file prdc/cpu/complex.h.
mul() [2/2]
template<> void Pscf::mul (fftw_complex & z, fftw_complex const & a, double const & b) inline
Multiplication of complex and real numbers, z = a * b.
Parameters
z complex product (out)
a complex factor (in)
b real factor (in)
Definition at line 350 of file prdc/cpu/complex.h.
mulEq() [1/2]
template<> void Pscf::mulEq (fftw_complex & a, fftw_complex const & b) inline
In place multiplication of two complex number, a *= b.
Parameters
a complex factor (in) and product (out)
b complex factor (in)
Definition at line 365 of file prdc/cpu/complex.h.
mulEq() [2/2]
template<> void Pscf::mulEq (fftw_complex & a, double const & b) inline
In place multiplication of a complex and real number, a *= b.
Parameters
a complex factor (in) and product (out)
b real factor (in)
Definition at line 382 of file prdc/cpu/complex.h.
square()
template<> void Pscf::square (fftw_complex & z, fftw_complex const & a) inline
Compute complex square of a complex number, z = a * a.
Parameters
z complex product (out)
a complex factor (in)
Definition at line 397 of file prdc/cpu/complex.h.
div() [1/2]
template<> void Pscf::div (fftw_complex & z, fftw_complex const & a, fftw_complex const & b) inline
Division of two complex numbers, z = a / b .
Parameters
z complex ratio (out)
a complex numerator (in)
b complex denominator (in)
Definition at line 415 of file prdc/cpu/complex.h.
div() [2/2]
template<> void Pscf::div (fftw_complex & z, fftw_complex const & a, double const & b) inline
Division of a complex number by a real number, z = a / b .
Parameters
z complex ratio (out)
a complex numerator (in)
b real denominator (in)
Definition at line 432 of file prdc/cpu/complex.h.
divEq() [1/2]
template<> void Pscf::divEq (fftw_complex & a, fftw_complex const & b) inline
In place division of two complex number, a /= b.
Parameters
a complex numerator (in) and ratio (out)
b complex denominator (in)
Definition at line 447 of file prdc/cpu/complex.h.
divEq() [2/2]
template<> void Pscf::divEq (fftw_complex & a, double const & b) inline
In place division of a complex number by a real number, a /= b.
Parameters
a complex numerator (in) and ratio (out)
b real denominator (in)
Definition at line 464 of file prdc/cpu/complex.h.