PSCF: ThreadArray
ThreadArray
Pscf namespace » Pscf Common » CUDA Utilities
Management of GPU resources and setting of execution configurations.
Functions
void Pscf::ThreadArray::init ()
Initialize static variables in Pscf::ThreadArray namespace.
void Pscf::ThreadArray::setThreadsPerBlock ()
Set the number of threads per block to a default value.
void Pscf::ThreadArray::setThreadsPerBlock (int nThreadsPerBlock)
Set the number of threads per block to a specified value.
void Pscf::ThreadArray::setThreadsLogical (int nThreadsLogical)
Given total number of threads, set 1D execution configuration.
void Pscf::ThreadArray::setThreadsLogical (int nThreadsLogical, int &nBlocks)
Given total number of threads, set 1D execution configuration.
void Pscf::ThreadArray::setThreadsLogical (int nThreadsLogical, int &nBlocks, int &nThreads)
Given total number of threads, set 1D execution configuration.
void Pscf::ThreadArray::checkExecutionConfig ()
Check the execution configuration (threads and block counts).
int Pscf::ThreadArray::nBlocks ()
Get the current number of blocks for execution.
int Pscf::ThreadArray::nThreads ()
Get the number of threads per block for execution.
int Pscf::ThreadArray::nThreadsLogical ()
Return previously requested total number of threads.
int Pscf::ThreadArray::warpSize ()
Get the warp size.
bool Pscf::ThreadArray::hasUnusedThreads ()
Indicates whether there will be unused threads.
Detailed Description
Management of GPU resources and setting of execution configurations.
Function Documentation
init()
void Pscf::ThreadArray::init ()
Initialize static variables in Pscf::ThreadArray namespace.
Definition at line 40 of file ThreadArray.cu.
References Util::Log::file(), setThreadsPerBlock(), and UTIL_THROW.
Referenced by setThreadsLogical(), and Pscf::Rpg::System< D >::System().
setThreadsPerBlock() [1/2]
void Pscf::ThreadArray::setThreadsPerBlock ()
Set the number of threads per block to a default value.
Query the hardware to determine a reasonable number.
Definition at line 58 of file ThreadArray.cu.
References setThreadsPerBlock().
Referenced by init(), Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), Pscf::Rpg::System< D >::setThreadCount(), setThreadsPerBlock(), and Pscf::Prdc::Cuda::Reduce::sum().
setThreadsPerBlock() [2/2]
void Pscf::ThreadArray::setThreadsPerBlock (int nThreadsPerBlock)
Set the number of threads per block to a specified value.
Parameters
nThreadsPerBlock the number of threads per block (input)
Definition at line 79 of file ThreadArray.cu.
References checkExecutionConfig().
setThreadsLogical() [1/3]
void Pscf::ThreadArray::setThreadsLogical (int nThreadsLogical)
Given total number of threads, set 1D execution configuration.
Calculates the number of blocks and threads per block, and stores the results in static variables along with the total number of threads requested.
Parameters
nThreadsLogical total number of required threads (input)
Definition at line 87 of file ThreadArray.cu.
References init(), nThreadsLogical(), and UTIL_ASSERT.
Referenced by Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqS(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqV(), Pscf::Prdc::Cuda::VecOp::addEqVc(), Pscf::Prdc::Cuda::VecOp::addVcVc(), Pscf::Prdc::Cuda::VecOp::addVcVcVc(), Pscf::Prdc::Cuda::VecOp::addVMany(), Pscf::Prdc::Cuda::VecOp::addVMany(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVS(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Prdc::Cuda::VecOp::addVV(), Pscf::Rpg::VecOpFts::computeDField(), Pscf::Rpg::VecOpFts::computeForceBias(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqS(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqV(), Pscf::Prdc::Cuda::VecOp::divEqVc(), Pscf::Prdc::Cuda::VecOp::divSV(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVS(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::divVV(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqS(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqV(), Pscf::Prdc::Cuda::VecOp::eqVPair(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expV(), Pscf::Prdc::Cuda::VecOp::expVc(), Pscf::Rpg::VecOpFts::fourierMove(), Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Rpg::VecOpFts::mcftsScale(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqS(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqV(), Pscf::Prdc::Cuda::VecOp::mulEqVPair(), Pscf::Prdc::Cuda::VecOp::mulVMany(), Pscf::Prdc::Cuda::VecOp::mulVMany(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVS(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVV(), Pscf::Prdc::Cuda::VecOp::mulVVPair(), setThreadsLogical(), setThreadsLogical(), Pscf::Prdc::Cuda::VecOp::sqNormV(), Pscf::Prdc::Cuda::VecOp::sqSqNormV(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqS(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subEqV(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVS(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVV(), Pscf::Prdc::Cuda::VecOp::subVVS(), and Pscf::Prdc::Cuda::Reduce::sum().
setThreadsLogical() [2/3]
void Pscf::ThreadArray::setThreadsLogical (int nThreadsLogical, int & nBlocks)
Given total number of threads, set 1D execution configuration.
Calculates the number of blocks and threads per block, and stores the results in static variables along with the total number of threads requested.
Sets the parameter nBlocks equal to the calculated number of blocks.
Parameters
nThreadsLogical total number of required threads (input)
nBlocks updated number of blocks (output)
Definition at line 115 of file ThreadArray.cu.
References nBlocks(), nThreadsLogical(), and setThreadsLogical().
setThreadsLogical() [3/3]
void Pscf::ThreadArray::setThreadsLogical (int nThreadsLogical, int & nBlocks, int & nThreads)
Given total number of threads, set 1D execution configuration.
Calculates the number of blocks and threads per block, and stores the results in static variables along with the total number of threads requested.
Sets the parameter nBlocks equal to the calculated number of blocks, and nThreads to the calculated number of threads per block.
Parameters
nThreadsLogical total number of required threads (input)
nBlocks updated number of blocks (output)
nThreads updated number threads per block (output)
Definition at line 123 of file ThreadArray.cu.
References nBlocks(), nThreads(), nThreadsLogical(), and setThreadsLogical().
checkExecutionConfig()
void Pscf::ThreadArray::checkExecutionConfig ()
Check the execution configuration (threads and block counts).
Check for validity and optimality, based on hardware warp size and streaming multiprocessor constraints.
Definition at line 131 of file ThreadArray.cu.
References UTIL_THROW.
Referenced by setThreadsPerBlock().
nBlocks()
int Pscf::ThreadArray::nBlocks ()
Get the current number of blocks for execution.
Definition at line 178 of file ThreadArray.cu.
Referenced by setThreadsLogical(), and setThreadsLogical().
nThreads()
int Pscf::ThreadArray::nThreads ()
Get the number of threads per block for execution.
Definition at line 181 of file ThreadArray.cu.
Referenced by setThreadsLogical().
nThreadsLogical()
int Pscf::ThreadArray::nThreadsLogical ()
Return previously requested total number of threads.
Definition at line 184 of file ThreadArray.cu.
Referenced by setThreadsLogical(), setThreadsLogical(), and setThreadsLogical().
warpSize()
int Pscf::ThreadArray::warpSize ()
Get the warp size.
Definition at line 187 of file ThreadArray.cu.
Referenced by Pscf::Prdc::Cuda::Reduce::innerProduct(), Pscf::Prdc::Cuda::Reduce::max(), Pscf::Prdc::Cuda::Reduce::maxAbs(), Pscf::Prdc::Cuda::Reduce::min(), Pscf::Prdc::Cuda::Reduce::minAbs(), and Pscf::Prdc::Cuda::Reduce::sum().
hasUnusedThreads()
bool Pscf::ThreadArray::hasUnusedThreads ()
Indicates whether there will be unused threads.
Returns true iff nThreads*nBlocks != nThreadsLogical.
Definition at line 190 of file ThreadArray.cu.