PSCF: Complex Arithmetic
Complex Arithmetic
Pscf namespace » Pscf Common » Mathematics
Functions
template<typename CT , typename RT >
RT Pscf::real (CT const &a)
Return the real part of a complex number.
template<typename CT , typename RT >
RT Pscf::imag (CT const &a)
Return the imaginary part of a complex number.
template<typename CT , typename RT >
RT Pscf::abs (CT const &a)
Return absolute magnitude of a complex number.
template<typename CT , typename RT >
RT Pscf::absSq (CT const &a)
Return square of absolute magnitude of a complex number.
template<typename CT >
void Pscf::conj (CT &z, CT const &a)
Compute complex conjugate, z = a^*.
template<typename CT >
void Pscf::conj (CT &a)
In-place complex conjugation of a complex number, a = a^* .
template<typename CT , typename RT >
void Pscf::assign (CT &z, RT const &a, RT const &b)
Create a complex number from real and imaginary parts, z = a + ib.
template<typename CT , typename RT >
void Pscf::assign (CT &z, RT const &a)
Assign a real input to a complex variable.
template<typename CT >
void Pscf::assign (CT &z, CT const &a)
Assign a complex input to a complex variable, z=a.
template<typename CT , typename RT >
void Pscf::assign (CT &z, std::complex< RT > const &a)
Assign a std::complex input to a complex variable, z=a.
template<typename CT , typename RT >
void Pscf::assign (std::complex< RT > &z, CT const &a)
Assign a complex input to a std::complex variable, z=a.
template<typename CT >
void Pscf::add (CT &z, CT const &a, CT const &b)
Addition of two complex numbers, z = a + b.
template<typename CT , typename RT >
void Pscf::add (CT &z, CT const &a, RT const &b)
Addition of a complex and real number, z = a + b.
template<typename CT >
void Pscf::addEq (CT &a, CT const &b)
In place addition of complex numbers, a += b.
template<typename CT , typename RT >
void Pscf::addEq (CT &a, RT const &b)
In place addition of a complex and real number, a += b.
template<typename CT >
void Pscf::sub (CT &z, CT const &a, CT const &b)
Subtraction of two complex numbers, z = a - b.
template<typename CT , typename RT >
void Pscf::sub (CT &z, CT const &a, RT const &b)
Subtraction of a real number from a complex number, z = a - b.
template<typename CT >
void Pscf::subEq (CT &a, CT const &b)
In place subtraction of two complex numbers, a -= b.
template<typename CT , typename RT >
void Pscf::subEq (CT &a, RT const &b)
In place subtraction of real number from a complex number, a -= b.
template<typename CT , typename RT >
RT Pscf::absSqDiff (CT const &a, CT const &b)
Return square of the absolute magnitude of a complex difference.
template<typename CT >
void Pscf::mul (CT &z, CT const &a, CT const &b)
Multiplication of two complex numbers, z = a * b.
template<typename CT , typename RT >
void Pscf::mul (CT &z, CT const &a, RT const &b)
Multiplication of complex and real numbers, z = a * b.
template<typename CT >
void Pscf::mulEq (CT &a, CT const &b)
In place multiplication of two complex number, a *= b.
template<typename CT , typename RT >
void Pscf::mulEq (CT &a, RT const &b)
In place multiplication of a complex and real number, a *= b.
template<typename CT >
void Pscf::square (CT &z, CT const &a)
Compute complex square of a complex number, z = a * a.
template<typename CT >
void Pscf::div (CT &z, CT const &a, CT const &b)
Division of two complex numbers, z = a / b .
template<typename CT , typename RT >
void Pscf::div (CT &z, CT const &a, RT const &b)
Division of a complex number by a real number, z = a / b .
template<typename CT >
void Pscf::divEq (CT &a, CT const &b)
In place division of two complex number, a /= b.
template<typename CT , typename RT >
void Pscf::divEq (CT &a, RT const &b)
In place division of a complex number by a real number, a /= b.
Detailed Description
Declarations of function templates for complex arithmetic using an unspecified complex data type. No definition is given for the general template for any of these functions. Instances of these templates must instead be explicit specializations for specific complex number types, such those defined by the different FFT libraries used on CPU and GPU hardware.
Function Documentation
real()
template<typename CT , typename RT > RT Pscf::real (CT const & a)
Return the real part of a complex number.
Parameters
a complex argument (input)
Referenced by Pscf::Prdc::readBasisData().
imag()
template<typename CT , typename RT > RT Pscf::imag (CT const & a)
Return the imaginary part of a complex number.
Parameters
a complex argument (input)
Referenced by Pscf::Prdc::readBasisData().
abs()
template<typename CT , typename RT > RT Pscf::abs (CT const & a)
Return absolute magnitude of a complex number.
Parameters
a complex argument (in)
absSq()
template<typename CT , typename RT > RT Pscf::absSq (CT const & a)
Return square of absolute magnitude of a complex number.
Parameters
a complex argument (in)
Referenced by Pscf::absSqDiff(), and Pscf::Rpg::BinaryStructureFactorGrid< D >::sample().
conj() [1/2]
template<typename CT > void Pscf::conj (CT & z, CT const & a)
Compute complex conjugate, z = a^*.
Parameters
z complex conjugate of argument (out)
a complex argument (in)
conj() [2/2]
template<typename CT > void Pscf::conj (CT & a)
In-place complex conjugation of a complex number, a = a^* .
Parameters
a argument (in) and complex conjugate (out)
assign() [1/5]
template<typename CT , typename RT > void Pscf::assign (CT & z, RT const & a, RT const & b)
Create a complex number from real and imaginary parts, z = a + ib.
Parameters
z complex (out)
a real part (in)
b imaginary part (in)
assign() [2/5]
template<typename CT , typename RT > void Pscf::assign (CT & z, RT const & a)
Assign a real input to a complex variable.
Parameters
z complex (out)
a real (in)
assign() [3/5]
template<typename CT > void Pscf::assign (CT & z, CT const & a)
Assign a complex input to a complex variable, z=a.
Parameters
z complex (out)
a complex (in)
assign() [4/5]
template<typename CT , typename RT > void Pscf::assign (CT & z, std::complex< RT > const & a)
Assign a std::complex input to a complex variable, z=a.
Parameters
z complex (out)
a std::complex (in)
assign() [5/5]
template<typename CT , typename RT > void Pscf::assign (std::complex< RT > & z, CT const & a)
Assign a complex input to a std::complex variable, z=a.
Parameters
z std::complex (out)
a complex (in)
add() [1/2]
template<typename CT > void Pscf::add (CT & z, CT const & a, CT const & b)
Addition of two complex numbers, z = a + b.
Parameters
z complex sum (out)
a complex summand (in)
b complex summand (in)
Referenced by Pscf::Prdc::SymmetryGroup< Symmetry >::makeCompleteGroup().
add() [2/2]
template<typename CT , typename RT > void Pscf::add (CT & z, CT const & a, RT const & b)
Addition of a complex and real number, z = a + b.
Parameters
z complex sum (out)
a complex summand (in)
b real summand (in)
addEq() [1/2]
template<typename CT > void Pscf::addEq (CT & a, CT const & b)
In place addition of complex numbers, a += b.
Parameters
a complex summand (in) and sum (out)
b complex summand (in)
addEq() [2/2]
template<typename CT , typename RT > void Pscf::addEq (CT & a, RT const & b)
In place addition of a complex and real number, a += b.
Parameters
a complex summand (in) and sum (out)
b real summand (in)
sub() [1/2]
template<typename CT > void Pscf::sub (CT & z, CT const & a, CT const & b)
Subtraction of two complex numbers, z = a - b.
Parameters
z complex difference (out)
a complex 1st argument (in)
b complex 2nd argument (in)
Referenced by Pscf::absSqDiff(), and Pscf::absSqDiff().
sub() [2/2]
template<typename CT , typename RT > void Pscf::sub (CT & z, CT const & a, RT const & b)
Subtraction of a real number from a complex number, z = a - b.
Parameters
z complex difference (out)
a complex 1st argument (in)
b real 2nd argument (in)
subEq() [1/2]
template<typename CT > void Pscf::subEq (CT & a, CT const & b)
In place subtraction of two complex numbers, a -= b.
Parameters
a complex argument (in) and difference (out)
b complex argument (in)
subEq() [2/2]
template<typename CT , typename RT > void Pscf::subEq (CT & a, RT const & b)
In place subtraction of real number from a complex number, a -= b.
Parameters
a complex argument (in) and difference (out)
b real argument (in)
absSqDiff()
template<typename CT , typename RT > RT Pscf::absSqDiff (CT const & a, CT const & b)
Return square of the absolute magnitude of a complex difference.
This function returns |a-b|^2 for complex a and b.
Parameters
a complex 1st argument (in)
b complex 2nd argument (in)
mul() [1/2]
template<typename CT > void Pscf::mul (CT & z, CT const & a, CT const & b)
Multiplication of two complex numbers, z = a * b.
Parameters
z complex product (out)
a complex factor (in)
b complex factor (in)
mul() [2/2]
template<typename CT , typename RT > void Pscf::mul (CT & z, CT const & a, RT const & b)
Multiplication of complex and real numbers, z = a * b.
Parameters
z complex product (out)
a complex factor (in)
b real factor (in)
mulEq() [1/2]
template<typename CT > void Pscf::mulEq (CT & a, CT const & b)
In place multiplication of two complex number, a *= b.
Parameters
a complex factor (in) and product (out)
b complex factor (in)
mulEq() [2/2]
template<typename CT , typename RT > void Pscf::mulEq (CT & a, RT const & b)
In place multiplication of a complex and real number, a *= b.
Parameters
a complex factor (in) and product (out)
b real factor (in)
square()
template<typename CT > void Pscf::square (CT & z, CT const & a)
Compute complex square of a complex number, z = a * a.
Parameters
z complex product (out)
a complex factor (in)
div() [1/2]
template<typename CT > void Pscf::div (CT & z, CT const & a, CT const & b)
Division of two complex numbers, z = a / b .
Parameters
z complex ratio (out)
a complex numerator (in)
b complex denominator (in)
div() [2/2]
template<typename CT , typename RT > void Pscf::div (CT & z, CT const & a, RT const & b)
Division of a complex number by a real number, z = a / b .
Parameters
z complex ratio (out)
a complex numerator (in)
b real denominator (in)
divEq() [1/2]
template<typename CT > void Pscf::divEq (CT & a, CT const & b)
In place division of two complex number, a /= b.
Parameters
a complex numerator (in) and ratio (out)
b complex denominator (in)
divEq() [2/2]
template<typename CT , typename RT > void Pscf::divEq (CT & a, RT const & b)
In place division of a complex number by a real number, a /= b.
Parameters
a complex numerator (in) and ratio (out)
b real denominator (in)