PSCF: Pscf::Rpc - Real Periodic Fields (CPU)
Pscf::Rpc - Real Periodic Fields (CPU)
Pscf namespace
SCFT and PS-FTS with real periodic fields on a CPU (namespace Pscf::Rpc)
Topics
Environment
Classes for imposing masks and external fields in periodic systems (CPU).
Fields
Field containers, FieldIo and Domain classes.
Field Theoretic Simulation (FTS)
Classes for performing field theoretic simulations in a partial saddle-point approximation (PS-FTS).
Self-Consistent Field Theory (SCFT)
Classes used only for performing SCFT calculations.
Solvers
Classes that solve the modified diffusion equation (MDE).
Classes
class Pscf::Rpc::System< D >
Main class, representing one complete system.
Functions
template<int D>
void Pscf::Rpc::run (int argc, char **argv)
Function template for main pscf_pc program.
int main (int argc, char **argv)
Main pscf_pc program.
Detailed Description
SCFT and PS-FTS with real periodic fields on a CPU (namespace Pscf::Rpc)
Function Documentation
run()
template<int D> void Pscf::Rpc::run (int argc, char ** argv)
Function template for main pscf_pc program.
Parameters
argc number of command line parameters
argv array of command line parameter strings
Definition at line 26 of file pscf_pc.cpp.
References Pscf::PolymerModel::lock(), Pscf::Rpc::System< D >::readCommands(), Pscf::Rpc::System< D >::readParam(), and Pscf::Rpc::System< D >::setOptions().
Referenced by main().
main()
int main (int argc, char ** argv)
Main pscf_pc program.
Parameters
argc number of command line arguments
argv array of command line arguments
Definition at line 52 of file pscf_pc.cpp.
References Pscf::Rpc::run().