PSCF: Pscf::Rpg - Real Periodic Fields (GPU)
Pscf::Rpg - Real Periodic Fields (GPU)
Pscf namespace
SCFT and PS-FTS with real periodic fields on a GPU (namespace Pscf::Rpg)
Topics
Environment
Classes for imposing masks and external fields in periodic systems.
Fields
Field containers, FieldIo and Domain classes.
Field Theoretic Simulation (FTS)
Classes for partial saddle-point field theoretic simulations (PS-FTS).
Self-Consistent Field Theory (SCFT)
Classes used only for SCFT calculations with GPU acceleration.
Solvers
Classes that solve the modified diffusion equation (MDE).
System
Classes that define an entire physical system.
Functions
template<int D>
void Pscf::Rpg::run (int argc, char **argv)
Function template for main pscf_pg program.
int main (int argc, char **argv)
Main pscf_pg program.
Detailed Description
SCFT and PS-FTS with real periodic fields on a GPU (namespace Pscf::Rpg)
Function Documentation
run()
template<int D> void Pscf::Rpg::run (int argc, char ** argv)
Function template for main pscf_pg program.
Parameters
argc number of command line parameters
argv array of command line parameter strings
Definition at line 24 of file pscf_pg.cu.
References Pscf::Prdc::SystemTmpl< D, T >::readCommands(), Pscf::Prdc::SystemTmpl< D, T >::readParam(), and Pscf::Prdc::SystemTmpl< D, T >::setOptions().
Referenced by main().
main()
int main (int argc, char ** argv)
Main pscf_pg program.
Parameters
argc number of command line arguments
argv array of command line arguments
Definition at line 50 of file pscf_pg.cu.
References Pscf::Rpg::run().