PSCF: Pscf::R1d - Real 1D fields
Pscf::R1d - Real 1D fields
Pscf namespace
One-dimensional SCFT (namespace Pscf::R1d)
Topics
Domain
Spatial domain for one-dimensional (1D) finite difference solvers.
Iterators
Iterators for use with one-dimensional (1D) finite difference solvers.
Solvers
Classes that solve modified diffusion equations using a one-dimensional (1D) finite difference discretization.
Sweep
Sweep (continuation) classes.
Classes
class Pscf::R1d::FieldIo
Read and write fields to file.
class Pscf::R1d::HomogeneousComparison
Command to compute properties of homogeneous reference system.
class Pscf::R1d::System
Main class in SCFT simulation of one system.
class Pscf::R1d::SystemAccess
Concise accesss to an associated System.
Functions
int main (int argc, char **argv)
Main function for pscf_1d program.
Detailed Description
One-dimensional SCFT (namespace Pscf::R1d)
Function Documentation
main()
int main (int argc, char ** argv)
Main function for pscf_1d program.
Parameters
argc number of command line parameter strings
argv array of command line parameter strings
Definition at line 20 of file pscf_1d.cpp.
References Pscf::R1d::System::readCommands(), Pscf::R1d::System::readParam(), and Pscf::R1d::System::setOptions().