PSCF: Util::BracketPolicy Namespace Reference
Util::BracketPolicy Namespace Reference
Util namespace » Parameter File IO
Namespace to define of policies for brackets on arrays and matrices.
Enumerations
enum Type
Typeeration of policies regarding use of delimiters on arrays.
Functions
void set (BracketPolicy::Type policy)
Set policy regarding use of bracket delimiters on arrays.
BracketPolicy::Type get ()
Get value of bracket policy.
Detailed Description
Namespace to define of policies for brackets on arrays and matrices.
Enumeration Type Documentation
Type
enum Util::BracketPolicy::Type
Typeeration of policies regarding use of delimiters on arrays.
Definition at line 27 of file BracketPolicy.h.
Function Documentation
set()
void Util::BracketPolicy::set (BracketPolicy::Type policy)
Set policy regarding use of bracket delimiters on arrays.
Definition at line 28 of file BracketPolicy.cpp.
Referenced by Pscf::Fd1d::System::System(), Pscf::Pspc::System< D >::System(), and Pscf::Pspg::System< D >::System().
get()
Type Util::BracketPolicy::get ()
Get value of bracket policy.
Definition at line 34 of file BracketPolicy.cpp.
Referenced by Util::ArrayParam< Type >::ArrayParam(), Util::MatrixParam< Type >::MatrixParam(), Util::ArrayParam< Type >::readEndBracket(), Util::MatrixParam< Type >::readEndBracket(), Util::ArrayParam< Type >::readLabel(), Util::MatrixParam< Type >::readLabel(), Util::DSymmMatrixParam< Type >::readValue(), and Util::MatrixParam< Type >::setBrackets().