PSCF: Pscf::PolymerModel Namespace Reference
Pscf::PolymerModel Namespace Reference
Enumeration and functions to specify a model for polymer chains.
Enumerations
enum Type
Scoped enumeration of polymer models.
Functions
void setModel (PolymerModel::Type model)
Set the global polymer model enumeration value.
void lock ()
Make the model immutable hereafter (this is irreversible).
Type model ()
Get the global polymer model enumeration value.
bool isThread ()
Is the global polymer model a thread model ?
bool isBead ()
Is the global polymer model a discrete bead-spring model ?
bool isLocked ()
Has the model type been locked (i.e., made immutable) ?
int nSet ()
How many times has the choice of model been set?
std::istream & operator>> (std::istream &in, PolymerModel::Type &model)
Input stream extractor for a PolymerModel::Type enumeration.
std::ostream & operator<< (std::ostream &out, PolymerModel::Type const &model)
Output stream inserter for a PolymerModel::Type enumeration.
template<class Archive >
void serialize (Archive &ar, PolymerModel::Type &data, const unsigned int version)
Serialize a PolymerModel::Type enumeration.
Detailed Description
Enumeration and functions to specify a model for polymer chains.
PSCF allows the use of two types of model for a polymer chain, which we refer to as the "Thread" and "Bead" models:
The "Thread" model treats each polymer block as a continuous random walk, and uses numerical approximations that attempt to closely approximate the behavior of that physical model. Specifically, it uses a pseudo-spectral scheme for solving the modified diffusion equation and algorithms for integration with respect to contour coordinates that converges rapidly to the behavior of that model with decreasing contour length step size. The thread model describes the length of each block by a real value denoted by the "length" of a block, which can take on any value.
The "Bead" model is instead based directly on a model of each block of the polymer as a string of an integer number of beads connected by Gaussian springs, and attempts to approximate the behavior of such a discrete chain as closely as possible. In this model, the w fields act on the discrete beads, rather than acting continuously along the chain. The bead model specifies the length of a block by an integer value for the number of beads within the block, denoted by "nBead".
The two allowed PolymerModel::Thread and PolymerModel::Bead of the PolymerModel::Type each identify one of these two models.
Functions defined in the PolymerModel namespace can be used to set and query the value of a pseudo-private PolymerModel::Type that specifies which model should be used throughout a program. The model type is initialized to PolymerModel::Thread by default. In PSCF programs that can support either thread or bead models, a choice of model should be made made in the early stages of program execution and not not changed again before the program terminates.
Function Documentation
setModel()
void Pscf::PolymerModel::setModel (Type model)
Set the global polymer model enumeration value.
Definition at line 40 of file PolymerModel.cpp.
References model(), and UTIL_CHECK.
Referenced by Pscf::Rpc::System< D >::readParameters(), and Pscf::Rpg::System< D >::readParameters().
lock()
void Pscf::PolymerModel::lock ()
Make the model immutable hereafter (this is irreversible).
Advice: Lock the model early in execution in production code, but do not lock the model in unit tests.
Definition at line 50 of file PolymerModel.cpp.
Referenced by Pscf::Rpc::run().
model()
PolymerModel::Type Pscf::PolymerModel::model ()
Get the global polymer model enumeration value.
Definition at line 58 of file PolymerModel.cpp.
Referenced by setModel().
isThread()
bool Pscf::PolymerModel::isThread ()
Is the global polymer model a thread model ?
Definition at line 64 of file PolymerModel.cpp.
Referenced by Pscf::Rpc::Block< D >::allocate(), Pscf::Rpg::Block< D >::allocate(), Pscf::Rpc::Polymer< D >::compute(), Pscf::Rpg::Polymer< D >::compute(), Pscf::Rpc::System< D >::computeFreeEnergy(), Pscf::Rpg::System< D >::computeFreeEnergy(), Pscf::Rpc::Simulator< D >::computeHamiltonian(), Pscf::Rpg::Simulator< D >::computeHamiltonian(), Pscf::Rpc::Propagator< D >::computeQ(), Pscf::Rpg::Propagator< D >::computeQ(), Pscf::Rpc::Polymer< D >::computeStress(), Pscf::Rpg::Polymer< D >::computeStress(), Pscf::Rpc::Block< D >::computeStressThread(), Pscf::Edge::length(), Pscf::PolymerSpecies::length(), Pscf::Rpc::Mixture< D >::readParameters(), Pscf::Rpg::Mixture< D >::readParameters(), Pscf::Edge::setLength(), Pscf::Rpc::Block< D >::setLength(), Pscf::Rpg::Block< D >::setLength(), Pscf::Rpc::Block< D >::setupSolver(), Pscf::Rpg::Block< D >::setupSolver(), Pscf::PolymerTmpl< Block >::solve(), Pscf::Rpc::Propagator< D >::solve(), Pscf::Rpc::Propagator< D >::solve(), Pscf::Rpg::Propagator< D >::solve(), Pscf::Rpc::Block< D >::stepThread(), and Pscf::Rpc::RampParameter< D >::type().
isBead()
bool Pscf::PolymerModel::isBead ()
Is the global polymer model a discrete bead-spring model ?
Definition at line 70 of file PolymerModel.cpp.
Referenced by Pscf::Rpc::Block< D >::allocate(), Pscf::Rpg::Block< D >::allocate(), Pscf::Rpc::Polymer< D >::compute(), Pscf::Rpc::Propagator< D >::computeHeadBead(), Pscf::Rpg::Propagator< D >::computeHeadBead(), Pscf::Rpc::Block< D >::computeStressBead(), Pscf::Rpg::Block< D >::computeStressBead(), Pscf::Edge::nBead(), Pscf::PolymerSpecies::nBead(), Pscf::PropagatorTmpl< TP >::ownsHead(), Pscf::PropagatorTmpl< TP >::ownsTail(), Pscf::Edge::ownsVertex(), Pscf::PolymerSpecies::readParameters(), Pscf::PolymerTmpl< Block >::readParameters(), Pscf::Edge::setNBead(), Pscf::Rpc::Block< D >::setupSolver(), Pscf::PropagatorTmpl< TP >::setVertexOwnership(), Pscf::PolymerTmpl< Block >::solve(), Pscf::Rpc::Propagator< D >::solve(), Pscf::Rpc::Propagator< D >::solve(), Pscf::Rpg::Propagator< D >::solve(), and Pscf::Rpc::Block< D >::stepBead().
isLocked()
bool Pscf::PolymerModel::isLocked ()
Has the model type been locked (i.e., made immutable) ?
Definition at line 76 of file PolymerModel.cpp.
Referenced by Pscf::Rpc::System< D >::readParameters(), and Pscf::Rpg::System< D >::readParameters().
nSet()
int Pscf::PolymerModel::nSet ()
How many times has the choice of model been set?
This returns a counter that is initialized to zero, and is incremented every times setModel is invoked.
Definition at line 82 of file PolymerModel.cpp.
Referenced by Pscf::Rpc::System< D >::readParameters(), and Pscf::Rpg::System< D >::readParameters().