PSCF: Pscf::Rpg Namespace Reference
Pscf::Rpg Namespace Reference
SCFT and PS-FTS with real periodic fields (GPU)
Namespaces
namespace VecOpFts
Element-wise vector operations performed on the GPU for FTS classes.
Classes
class AmCompressor
Rpg implementation of the Anderson Mixing compressor.
class AmIteratorBasis
Rpg implementation of the Anderson Mixing iterator.
class AmIteratorGrid
Rpg implementation of the Anderson Mixing iterator.
class Analyzer
Abstract base for periodic output and/or analysis actions.
class AnalyzerFactory
Factory for subclasses of Analyzer.
class AnalyzerManager
Manager for a list of Analyzer objects.
class AverageAnalyzer
Analyze averages and block averages of several real variables.
class AverageListAnalyzer
Analyze averages and block averages of several real variables.
class BasisFieldState
FieldState for fields in symmetry-adapted basis format.
class BdSimulator
Brownian dynamics simulator.
class BdStep
BdStep is an abstract base class for Brownian dynamics steps.
class BdStepFactory
Factory for subclasses of BdStep.
class BinaryStructureFactorGrid
BinaryStructureFactorGrid evaluates AB diblock structure factors in Fourier space.
class Block
Block within a branched polymer.
class CFieldContainer
A list of c fields stored in both basis and r-grid format.
class ChiDerivative
Evaluate the derivative of H with respect to chi.
class Compressor
Base class for iterators that impose incompressibility.
class CompressorFactory
Factory for subclasses of Compressor.
class ConcentrationDerivative
Evaluate the derivative of H with respect to concentration.
class ConcentrationWriter
Periodically write snapshots to a trajectory file.
class Domain
Spatial domain and spatial discretization for a periodic structure.
class EinsteinCrystalPerturbation
Perturbation for Einstein crystal thermodynamic integration method.
class ExplicitBdStep
BdStep is an abstract base class for Brownian dynamics steps.
class ExtGenFilm
External field generator for a thin film geometry.
class FieldIo
File input/output operations and format conversions for fields.
class FieldState
Record of a state of a System (fields + unit cell).
class ForceBiasMove
ForceBiasMove attempts a Brownian dynamics move.
class FourierMove
FourierMove is a Monte Carlo move in fourier space.
class FourthOrderParameter
FourthOrderParameter is used to detect an order-disorder transition.
class HamiltonianAnalyzer
Compute averages and output block averages of Hamiltonian components.
class HostDArrayComplex
HostDArray containing cudaComplex elements.
class ImposedFieldsGenerator
Class defining mask & external fields to impose on the calculation.
class IntraCorrelation
Base class for iterators that impose incompressibility.
class Iterator
Base class for iterative solvers for SCF equations.
class IteratorFactory
Factory for subclasses of Iterator.
class LinearRamp
Linear ramp - parameters vary linearly with step index.
class LinearSweep
Base class for a sweep in parameter space where parameters change linearly with the sweep variable.
class LMBdStep
Leimkuhler-Matthews Brownian dynamics stepper.
class LrAmCompressor
Anderson Mixing compressor with linear-response mixing step.
class LrAmPreCompressor
Anderson Mixing compressor with linear-response preconditioning.
class LrCompressor
Linear response compressor.
class Mask
A field to which the total monomer concentration is constrained.
class MaskGenFilm
Mask generator for a thin film geometry.
class MaxOrderParameter
MaxOrderParameter is used to detect an order-disorder transition.
class McMove
McMove is an abstract base class for Monte Carlo moves.
class McMoveFactory
Factory for subclasses of McMove.
class McMoveManager
Manager for a set of McMove objects.
class McSimulator
Monte-Carlo simulation coordinator.
class Mixture
Solver for a mixture of polymers and solvents.
class Perturbation
Base class for additive perturbations of standard FTS Hamiltonian.
class PerturbationDerivative
Evaluate the derivative of H w/ respect to perturbation parameter lambda.
class PerturbationFactory
Factory for subclasses of Perturbation.
class Polymer
Descriptor and solver for a branched polymer species.
class PredCorrBdStep
Predictor-corrector Brownian dynamics stepper.
class Propagator
MDE solver for one-direction of one block.
class Ramp
Class that varies parameters during a simulation (abstract).
class RampFactory
Factory for subclasses of Ramp.
class RampParameter
Class for storing data about an individual ramp parameter.
class RealMove
RealMove is a Monte Carlo move in real space.
class RGridTrajectoryReader
Trajectory file reader.
struct SimState
SimState stores the state used by an fts simulation.
class Simulator
Field theoretic simulator (base class).
class SimulatorFactory
Factory for subclasses of Simulator.
class Solvent
Solver and descriptor for a solvent species.
class StepLogger
Periodically write snapshots to a trajectory file.
class Sweep
Solve a sequence of problems along a line in parameter space.
class SweepFactory
Default Factory for subclasses of Sweep.
class SweepParameter
Class for storing data about an individual sweep parameter.
class System
Main class for calculations that represent one system.
class TrajectoryReader
Trajectory file reader.
class TrajectoryReaderFactory
Factory for subclasses of TrajectoryReader.
class TrajectoryWriter
Periodically write snapshots to a trajectory file.
class WaveList
Class to calculate and store properties of wavevectors.
class WFieldContainer
A list of fields stored in both basis and r-grid format.
Functions
template<int D>
std::istream & operator>> (std::istream &in, RampParameter< D > &param)
Inserter for reading a RampParameter from an istream.
template<int D>
std::ostream & operator<< (std::ostream &out, RampParameter< D > const &param)
Extractor for writing a RampParameter to ostream.
template<int D>
void run (int argc, char **argv)
Function template for main pscf_pg program.
template<int D>
std::istream & operator>> (std::istream &in, SweepParameter< D > &param)
Inserter for reading a SweepParameter from an istream.
template<int D>
std::ostream & operator<< (std::ostream &out, SweepParameter< D > const &param)
Extractor for writing a SweepParameter to ostream.
void realMulVConjVV (DeviceArray< cudaReal > &a, DeviceArray< cudaComplex > const &b, DeviceArray< cudaComplex > const &c, DeviceArray< cudaReal > const &d)
Element-wise calculation of a = real(b * conj(c) * d), kernel wrapper.
void richardsonEx (DeviceArray< cudaReal > &qNew, DeviceArray< cudaReal > const &qr, DeviceArray< cudaReal > const &qr2, DeviceArray< cudaReal > const &expW2)
Performs qNew = (4 * (qr2 * expW2) - qr) / 3 elementwise, kernel wrapper.
void addEqMulVVc (DeviceArray< cudaReal > &a, DeviceArray< cudaReal > const &b, DeviceArray< cudaReal > const &c, cudaReal const d)
Performs a[i] += b[i] * c[i] * d, kernel wrapper.
Detailed Description
SCFT and PS-FTS with real periodic fields (GPU)
Function Documentation
operator>>() [1/2]
template<int D> std::istream & Pscf::Rpg::operator>> (std::istream & in, RampParameter< D > & param)
Inserter for reading a RampParameter from an istream.
Parameters
in input stream
param RampParameter<D> object to read
Definition at line 263 of file rpg/fts/ramp/RampParameter.tpp.
operator<<() [1/2]
template<int D> std::ostream & Pscf::Rpg::operator<< (std::ostream & out, RampParameter< D > const & param)
Extractor for writing a RampParameter to ostream.
Parameters
out output stream
param RampParameter<D> object to write
Definition at line 286 of file rpg/fts/ramp/RampParameter.tpp.
References Pscf::Rpg::RampParameter< D >::id(), and Pscf::Rpg::RampParameter< D >::writeParamType().
operator>>() [2/2]
template<int D> std::istream & Pscf::Rpg::operator>> (std::istream & in, SweepParameter< D > & param)
Inserter for reading a SweepParameter from an istream.
Parameters
in input stream
param SweepParameter<D> object to read
Definition at line 277 of file rpg/scft/sweep/SweepParameter.tpp.
operator<<() [2/2]
template<int D> std::ostream & Pscf::Rpg::operator<< (std::ostream & out, SweepParameter< D > const & param)
Extractor for writing a SweepParameter to ostream.
Parameters
out output stream
param SweepParameter<D> object to write
Definition at line 299 of file rpg/scft/sweep/SweepParameter.tpp.
References Pscf::Rpg::SweepParameter< D >::id(), and Pscf::Rpg::SweepParameter< D >::writeParamType().
realMulVConjVV()
void Pscf::Rpg::realMulVConjVV (DeviceArray< cudaReal > & a, DeviceArray< cudaComplex > const & b, DeviceArray< cudaComplex > const & c, DeviceArray< cudaReal > const & d)
Element-wise calculation of a = real(b * conj(c) * d), kernel wrapper.
Parameters
a output array (real)
b input array 1 (complex)
c input array 2 (complex)
d input array 3 (real)
Definition at line 87 of file rpg/solvers/Block.tpp.
References Pscf::DeviceArray< Data >::capacity(), Pscf::DeviceArray< Data >::cArray(), Pscf::ThreadArray::setThreadsLogical(), and UTIL_CHECK.
Referenced by Pscf::Rpg::Block< D >::computeStress().
richardsonEx()
void Pscf::Rpg::richardsonEx (DeviceArray< cudaReal > & qNew, DeviceArray< cudaReal > const & qr, DeviceArray< cudaReal > const & qr2, DeviceArray< cudaReal > const & expW2)
Performs qNew = (4 * (qr2 * expW2) - qr) / 3 elementwise, kernel wrapper.
Parameters
qNew output array (a propagator slice)
qr input array 1 (a propagator slice)
qr2 input array 2 (a propagator slice)
expW2 input array 3 (exp(-W[i]*ds/4) array)
Definition at line 109 of file rpg/solvers/Block.tpp.
References Pscf::DeviceArray< Data >::capacity(), Pscf::DeviceArray< Data >::cArray(), Pscf::ThreadArray::setThreadsLogical(), and UTIL_CHECK.
Referenced by Pscf::Rpg::Block< D >::step().
addEqMulVVc()
void Pscf::Rpg::addEqMulVVc (DeviceArray< cudaReal > & a, DeviceArray< cudaReal > const & b, DeviceArray< cudaReal > const & c, cudaReal const d)
Performs a[i] += b[i] * c[i] * d, kernel wrapper.
Parameters
a output array
b input array 1
c input array 2
d input scalar
Definition at line 131 of file rpg/solvers/Block.tpp.
References Pscf::DeviceArray< Data >::capacity(), Pscf::DeviceArray< Data >::cArray(), Pscf::ThreadArray::setThreadsLogical(), and UTIL_CHECK.
Referenced by Pscf::Rpg::Block< D >::computeConcentration().