PSCF: pscfpp.make Namespace Reference
pscfpp.make Namespace Reference
Python scripts used by the PSCF makefile build system.
Classes
class MakeMaker
Class to construct makefile system for a set of source files.
Functions
def createDependencyFileCpp (processor, options, cfile, srcdir, blddir, extraDependencies='')
Create a *.d dependency file for a C/C++ source file.
def createDependencyFileCuda (processor, options, cfile, srcdir, blddir, extraDependencies='')
Create a *.d dependency file for a CUDA source file.
def editDepend (pfile, dfile, blddir, extraDependencies)
Edit the dependency file created for a C/C++ file by the compiler.
def editDependLocal (pfile, dfile, blddir, srcroot, extraDependencies)
Edit the dependency file created for a CUDA file by the compiler.
Detailed Description
Python scripts used by the PSCF makefile build system.
Function Documentation
createDependencyFileCpp()
def pscfpp.make.createDependencyFileCpp (processor, options, cfile, srcdir, blddir, extraDependencies = '')
Create a *.d dependency file for a C/C++ source file.
This command uses a compiler executable to analyze the dependencies of a C/C++ source file in the src directory tree and creates a dependency file with an appropriate format for make in the analogous location in the bld directory tree. The function first executes a compiler command to compute dependencies and then calls python function editDepend to edit the resulting file. The most important change made during editing is the replacement of relative paths output by the g++ compiler to the absolute paths used in the PSCF build system.
Parameters
processor compiler command to analyze dependencies (i.e., g++)
options string of options passed to processor
cfile path to source file
srcdir path to source directory tree (SRC_DIR in makefiles)
blddir path to bulkd directory tree (BLD_DIR in makefiles)
extraDependencies string of additional known dependencies
Definition at line 30 of file make.py.
References pscfpp.make.editDepend().
createDependencyFileCuda()
def pscfpp.make.createDependencyFileCuda (processor, options, cfile, srcdir, blddir, extraDependencies = '')
Create a *.d dependency file for a CUDA source file.
This command uses a compiler executable to analyze the dependencies of a CUDA source file in the src directory tree and creates a dependency file with an appropriate format for make in the analogous location in the bld directory tree. The function first executes a compiler command to compute dependencies and then calls python function editDependLocal to edit the resulting file. The most important change made during editing is the replacement of relative paths output by the nvcc compiler to the absolute paths used in the PSCF build system.
Parameters
processor compiler command to analyze dependencies (i.e., g++)
options string of options passed to processor
cfile path to source file
srcdir path to source directory tree (SRC_DIR in makefiles)
blddir path to build directory tree (BLD_DIR in makefiles)
extraDependencies string of additional known dependencies
Definition at line 84 of file make.py.
References pscfpp.make.editDependLocal().
editDepend()
def pscfpp.make.editDepend (pfile, dfile, blddir, extraDependencies)
Edit the dependency file created for a C/C++ file by the compiler.
This function edits the dependency file created by the g++ or compatible compiler so as to use absolute rather than relative paths, and so as to include the extraDependencies string.
Parameters
pfile input dependency file name
dfile output dependency file name
blddir path to build directory tree (BLD_DIR in makefiles)
extraDependencies string of additional known dependencies
Definition at line 134 of file make.py.
Referenced by pscfpp.make.createDependencyFileCpp().
editDependLocal()
def pscfpp.make.editDependLocal (pfile, dfile, blddir, srcroot, extraDependencies)
Edit the dependency file created for a CUDA file by the compiler.
This function edits the dependency file created by the nvcc compiler for a CUDA file so as to use absolute rather than relative paths, and so as to include the extraDependencies string.
Parameters
pfile input dependency file name
dfile output dependency file name
blddir path to build directory tree (BLD_DIR in makefiles)
srcroot path to source directory tree (SRC_DIR in makefiles)
extraDependencies string of additional known dependencies
Definition at line 188 of file make.py.
Referenced by pscfpp.make.createDependencyFileCuda().