PSCF: Pscf Namespace Reference
Pscf Namespace Reference
PSCF package top-level namespace.
Namespaces
namespace Debye
Functions used to compute intramolecular correlation functions.
namespace FloryHuggins
Flory-Huggins theory of spatially homogeneous mixtures.
namespace PolymerModel
Enumeration and functions to specify a model for polymer chains.
namespace Prdc
Periodic fields and crystallography.
namespace R1d
SCFT with real 1D fields.
namespace Rpc
Real periodic fields, SCFT and PS-FTS (CPU).
namespace Rpg
SCFT and PS-FTS with real periodic fields (GPU)
namespace ThreadArray
Global functions and variables to control GPU thread and block counts.
namespace ThreadMesh
Management of multidimensional GPU thread execution configurations.
Classes
class AmbdInteraction
Modified interaction to compute residual defn.
class AmIteratorTmpl
Template for Anderson mixing iterator algorithm.
class BlockTmpl
Class template for a block solver in a block copolymer.
class CudaRandom
Random number generator on GPU.
class DeviceArray
Dynamic array on the GPU device with aligned data.
class Edge
Descriptor for a block within a block polymer.
class EdgeIterator
Edge iterator for graph associated with a polymer.
class EnvironmentBase
Base class mask and external field generator.
class FieldComparison
Comparison of element-by-element differences between field arrays.
class FieldGeneratorBase
Base class for objects that generate fields for a MixAndMatchEnv.
class HostDArray
Template for dynamic array stored in host CPU memory.
class Interaction
Flory-Huggins excess free energy model.
class IntVec
An IntVec<D, T> is a D-component vector of elements of integer type T.
class LuSolver
Solve Ax=b by LU decomposition of A.
class Mesh
Description of a regular grid of points in a periodic domain.
class MeshIterator
Iterator over points in a Mesh<D>.
class MeshIteratorFortran
Iterator over points in a mesh in "Fortran" order.
class MixAndMatchEnvTmpl
Template class for Environments that mix and match field generators.
class MixtureBase
Abstract descriptor for a mixture of polymer and solvent species.
class MixtureTmpl
Solvers for a mixture of polymer and solvent species.
class Monomer
Descriptor for a monomer type.
class NanException
Exception thrown when not-a-number (NaN) is encountered.
class ParameterModifier
Base class allowing subclasses to define sweepable parameters.
struct ParameterType
Declaration of a specialized sweep parameter type.
class PolymerSpecies
Descriptor for a linear or acyclic branched block polymer.
class PolymerTmpl
Template for an MDE solver and descriptor for a block polymer.
struct PolymerType
Struct containing an enumeration of polymer structure types.
class PropagatorTmpl
Template for propagator classes.
class RealVec
A RealVec<D, T> is D-component vector with elements of floating type T.
class SolventSpecies
Descriptor for a solvent species.
class Species
Base class for a molecular species (polymer or solvent).
class SweepTmpl
Solve a sequence of problems along a path through parameter space.
class TridiagonalSolver
Solver for Ax=b with tridiagonal matrix A.
class Vec
A Vec<D, T><D,T> is a D-component vector with elements of type T.
class Vertex
A junction or chain end in a block polymer.
class VertexIterator
Vertex iterator for graph associated with a polymer.
Functions
std::istream & operator>> (std::istream &in, Edge &block)
Input stream extractor (>>) for a Edge.
std::ostream & operator<< (std::ostream &out, Edge const &block)
Output stream inserter (<<) for a Edge.
std::istream & operator>> (std::istream &in, Monomer &monomer)
Stream extractor (>>) for a Monomer.
std::ostream & operator<< (std::ostream &out, const Monomer &monomer)
Stream inserter (<<) for a Monomer.
std::istream & operator>> (std::istream &in, PolymerType::Enum &type)
Input stream extractor for a PolymerType::Enum enumeration.
std::ostream & operator<< (std::ostream &out, PolymerType::Enum const &type)
Output stream extractor for a PolymerType::Enum enumeration.
template<class Archive>
void serialize (Archive &ar, PolymerType::Enum &data, const unsigned int version)
Serialize a PolymerType::Enum enumeration.
std::istream & operator>> (std::istream &in, Species::Ensemble &policy)
istream extractor for a Species::Ensemble enumeration.
std::ostream & operator<< (std::ostream &out, Species::Ensemble policy)
ostream inserter for an Species::Ensemble enumeration.
template<class Archive>
void serialize (Archive &ar, Species::Ensemble &policy, const unsigned int version)
Serialize a Species::Ensemble.
void gpuAssert (cudaError_t err, const char *file, int line)
Check if CUDA API function returns cudaSuccess (used by cudaErrorCheck macro).
template<typename CT, typename RT>
RT real (CT const &a)
Return the real part of a complex number.
template<typename CT, typename RT>
RT imag (CT const &a)
Return the imaginary part of a complex number.
template<typename CT, typename RT>
RT abs (CT const &a)
Return absolute magnitude of a complex number.
template<typename CT, typename RT>
RT absSq (CT const &a)
Return square of absolute magnitude of a complex number.
template<typename CT>
void conj (CT &z, CT const &a)
Compute complex conjugate, z = a^*.
template<typename CT>
void conj (CT &a)
In-place complex conjugation of a complex number, a = a^* .
template<typename CT, typename RT>
void assign (CT &z, RT const &a, RT const &b)
Create a complex number from real and imaginary parts, z = a + ib.
template<typename CT, typename RT>
void assign (CT &z, RT const &a)
Assign a real input to a complex variable.
template<typename CT>
void assign (CT &z, CT const &a)
Assign a complex input to a complex variable, z=a.
template<typename CT, typename RT>
void assign (CT &z, std::complex< RT > const &a)
Assign a std::complex input to a complex variable, z=a.
template<typename CT, typename RT>
void assign (std::complex< RT > &z, CT const &a)
Assign a complex input to a std::complex variable, z=a.
template<typename CT>
void add (CT &z, CT const &a, CT const &b)
Addition of two complex numbers, z = a + b.
template<typename CT, typename RT>
void add (CT &z, CT const &a, RT const &b)
Addition of a complex and real number, z = a + b.
template<typename CT>
void addEq (CT &a, CT const &b)
In place addition of complex numbers, a += b.
template<typename CT, typename RT>
void addEq (CT &a, RT const &b)
In place addition of a complex and real number, a += b.
template<typename CT>
void sub (CT &z, CT const &a, CT const &b)
Subtraction of two complex numbers, z = a - b.
template<typename CT, typename RT>
void sub (CT &z, CT const &a, RT const &b)
Subtraction of a real number from a complex number, z = a - b.
template<typename CT>
void subEq (CT &a, CT const &b)
In place subtraction of two complex numbers, a -= b.
template<typename CT, typename RT>
void subEq (CT &a, RT const &b)
In place subtraction of real number from a complex number, a -= b.
template<typename CT, typename RT>
RT absSqDiff (CT const &a, CT const &b)
Return square of the absolute magnitude of a complex difference.
template<typename CT>
void mul (CT &z, CT const &a, CT const &b)
Multiplication of two complex numbers, z = a * b.
template<typename CT, typename RT>
void mul (CT &z, CT const &a, RT const &b)
Multiplication of complex and real numbers, z = a * b.
template<typename CT>
void mulEq (CT &a, CT const &b)
In place multiplication of two complex number, a *= b.
template<typename CT, typename RT>
void mulEq (CT &a, RT const &b)
In place multiplication of a complex and real number, a *= b.
template<typename CT>
void square (CT &z, CT const &a)
Compute complex square of a complex number, z = a * a.
template<typename CT>
void div (CT &z, CT const &a, CT const &b)
Division of two complex numbers, z = a / b .
template<typename CT, typename RT>
void div (CT &z, CT const &a, RT const &b)
Division of a complex number by a real number, z = a / b .
template<typename CT>
void divEq (CT &a, CT const &b)
In place division of two complex number, a /= b.
template<typename CT, typename RT>
void divEq (CT &a, RT const &b)
In place division of a complex number by a real number, a /= b.
template<int D, typename T>
std::istream & operator>> (std::istream &in, IntVec< D, T > &vector)
istream extractor for a IntVec<D, T>.
template<int D, typename T>
std::ostream & operator<< (std::ostream &out, const IntVec< D, T > &vector)
ostream inserter for a IntVec<D, T>.
template<int D, typename T>
bool operator== (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Equality of two IntVec<D> objects.
template<int D, typename T>
bool operator== (const IntVec< D, T > &v1, const Vec< D, T > &v2)
Equality of an IntVec<D> and a Vec<D, T>
template<int D, typename T>
bool operator== (const Vec< D, T > &v1, const IntVec< D, T > &v2)
Equality of an Vec<D, T> and an IntVec<D, T>
template<int D, typename T>
bool operator!= (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Inequality of two IntVec<D, T> objects.
template<int D, typename T>
bool operator!= (const IntVec< D, T > &v1, const Vec< D, T > &v2)
Inequality of an IntVec<D> and a Vec<D, T>
template<int D, typename T>
bool operator!= (const Vec< D, T > &v1, const IntVec< D, T > &v2)
Inequality of a Vec<D, T> and an IntVec<D, T>
template<int D, typename T>
bool operator< (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Less than comparison for two IntVec<D, T>s.
template<int D, typename T>
bool operator<= (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Less than or equal to comparison for two IntVec<D, T>s.
template<int D, typename T>
bool operator> (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Greater than comparison for two IntVec<D, T>s.
template<int D, typename T>
bool operator>= (const IntVec< D, T > &v1, const IntVec< D, T > &v2)
Greater than or equal to comparison for two IntVec<D, T>s.
template<int D, typename T>
std::istream & operator>> (std::istream &in, RealVec< D, T > &vector)
istream extractor for a RealVec<D, T>.
template<int D, typename T>
std::ostream & operator<< (std::ostream &out, const RealVec< D, T > &vector)
ostream inserter for a RealVec<D, T>.
template<int D, typename T>
T dot (Vec< D, T > const &v1, Vec< D, T > const &v2)
Return dot product of two vectors.
template<int D, typename T>
Vec< D, T > operator+ (Vec< D, T > const &v1, Vec< D, T > const &v2)
Return the sum of two vectors.
template<int D>
std::istream & operator>> (std::istream &in, Mesh< D > &mesh)
Input stream extractor for reading a Mesh<D> object.
template<int D>
std::ostream & operator<< (std::ostream &out, Mesh< D > const &mesh)
Output stream inserter for writing a Mesh<D> object.
template<>
double real< fftw_complex, double > (fftw_complex const &a)
Return the real part of a complex number.
template<>
double imag< fftw_complex, double > (fftw_complex const &a)
Return the imaginary part of a complex number.
template<>
double abs< fftw_complex, double > (fftw_complex const &a)
Return absolute magnitude of a complex number.
template<>
double absSq< fftw_complex, double > (fftw_complex const &a)
Return square of absolute magnitude of a complex number.
template<>
void conj (fftw_complex &z, fftw_complex const &a)
Compute complex conjugate, z = a^*.
template<>
void conj (fftw_complex &a)
In-place complex conjugation of a complex number, a = a^* .
template<>
void assign (fftw_complex &z, double const &a, double const &b)
Create a complex number from real and imaginary parts, z = a + ib.
template<>
void assign (fftw_complex &z, double const &a)
Assign a real input to a complex variable.
template<>
void assign (fftw_complex &z, fftw_complex const &a)
Assign a complex input to a complex variable.
template<>
void assign (fftw_complex &z, std::complex< double > const &a)
Assign a std::complex input to a complex variable.
template<>
void assign (std::complex< double > &z, fftw_complex const &a)
Assign a complex input to a std::complex variable.
template<>
void add (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Addition of two complex numbers, z = a + b.
template<>
void add (fftw_complex &z, fftw_complex const &a, double const &b)
Addition of a complex and real number, z = a + b.
template<>
void addEq (fftw_complex &a, fftw_complex const &b)
In place addition of complex numbers, a += b.
template<>
void addEq (fftw_complex &a, double const &b)
In place addition of a complex and real number, a += b.
template<>
void sub (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Subtraction of two complex numbers, z = a - b.
template<>
void sub (fftw_complex &z, fftw_complex const &a, double const &b)
Subtraction of a real number from a complex number, z = a - b.
template<>
void subEq (fftw_complex &a, fftw_complex const &b)
In place subtraction of two complex numbers, a -= b.
template<>
void subEq (fftw_complex &a, double const &b)
In place subtraction of real number from a complex number, a -= b.
template<>
double absSqDiff (fftw_complex const &a, fftw_complex const &b)
Return square of the absolute magnitude of a complex difference.
template<>
void mul (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Multiplication of two complex numbers, z = a * b.
template<>
void mul (fftw_complex &z, fftw_complex const &a, double const &b)
Multiplication of complex and real numbers, z = a * b.
template<>
void mulEq (fftw_complex &a, fftw_complex const &b)
In place multiplication of two complex number, a *= b.
template<>
void mulEq (fftw_complex &a, double const &b)
In place multiplication of a complex and real number, a *= b.
template<>
void square (fftw_complex &z, fftw_complex const &a)
Compute complex square of a complex number, z = a * a.
template<>
void div (fftw_complex &z, fftw_complex const &a, fftw_complex const &b)
Division of two complex numbers, z = a / b .
template<>
void div (fftw_complex &z, fftw_complex const &a, double const &b)
Division of a complex number by a real number, z = a / b .
template<>
void divEq (fftw_complex &a, fftw_complex const &b)
In place division of two complex number, a /= b.
template<>
void divEq (fftw_complex &a, double const &b)
In place division of a complex number by a real number, a /= b.
std::istream & operator>> (std::istream &is, fftw_complex &z)
Stream extraction operator for fftw_complex.
std::ostream & operator<< (std::ostream &os, fftw_complex const &z)
Stream insertion operator for fftw_complex.
template<>
Prdc::Cuda::cudaReal real (Prdc::Cuda::cudaComplex const &a)
Return the real part of a complex number.
template<>
Prdc::Cuda::cudaReal imag (Prdc::Cuda::cudaComplex const &a)
Return the imaginary part of a complex number.
template<>
Prdc::Cuda::cudaReal abs (Prdc::Cuda::cudaComplex const &a)
Return absolute magnitude of a complex number.
template<>
Prdc::Cuda::cudaReal absSq (Prdc::Cuda::cudaComplex const &a)
Return square of absolute magnitude of a complex number.
template<>
void conj (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a)
Compute complex conjugate, z = a^*.
template<>
void conj (Prdc::Cuda::cudaComplex &a)
In-place complex conjugation of a complex number, a = a^* .
template<>
void assign (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaReal const &a, Prdc::Cuda::cudaReal const &b)
Create a complex number from real and imaginary parts, z = a + ib.
template<>
void assign (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaReal const &a)
Assign a real input to a complex variable.
template<>
void assign (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a)
Assign a complex input to a complex variable.
template<>
void assign (Prdc::Cuda::cudaComplex &z, std::complex< Prdc::Cuda::cudaReal > const &a)
Assign a std::complex input to a complex variable.
template<>
void assign (std::complex< Prdc::Cuda::cudaReal > &z, Prdc::Cuda::cudaComplex const &a)
Assign a complex input to a std::complex variable.
template<>
void add (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaComplex const &b)
Addition of two complex numbers, z = a + b.
template<>
void add (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaReal const &b)
Addition of a complex and real number, z = a + b.
template<>
void addEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaComplex const &b)
In place addition of complex numbers, a += b.
template<>
void addEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaReal const &b)
In place addition of a complex and real number, a += b.
template<>
void sub (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaComplex const &b)
Subtraction of two complex numbers, z = a - b.
template<>
void sub (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaReal const &b)
Subtraction of a real number from a complex number, z = a - b.
template<>
void subEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaComplex const &b)
In place subtraction of two complex numbers, a -= b.
template<>
void subEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaReal const &b)
In place subtraction of real number from a complex number, a -= b.
template<>
Prdc::Cuda::cudaReal absSqDiff (Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaComplex const &b)
Return square of the absolute magnitude of a complex difference.
template<>
void mul (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaComplex const &b)
Multiplication of two complex numbers, z = a * b.
template<>
void mul (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaReal const &b)
Multiplication of complex and real numbers, z = a * b.
template<>
void mulEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaComplex const &b)
In place multiplication of two complex number, a *= b.
template<>
void mulEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaReal const &b)
In place multiplication of a complex and real number, a *= b.
template<>
void square (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a)
Compute complex square of a complex number, z = a * a.
template<>
void div (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaComplex const &b)
Division of two complex numbers, z = a / b .
template<>
void div (Prdc::Cuda::cudaComplex &z, Prdc::Cuda::cudaComplex const &a, Prdc::Cuda::cudaReal const &b)
Division of a complex number by a real number, z = a / b .
template<>
void divEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaComplex const &b)
In place division of two complex number, a /= b.
template<>
void divEq (Prdc::Cuda::cudaComplex &a, Prdc::Cuda::cudaReal const &b)
In place division of a complex number by a real number, a /= b.
Detailed Description
PSCF package top-level namespace.
Function Documentation
operator>>() [1/7]
std::istream & Pscf::operator>> (std::istream & in, Edge & block)
Input stream extractor (>>) for a Edge.
The polymerType must be set before an Edge can be read from a stream. The block id must be set explicitly by calling setId, and are not read from an istream. Vertex id values for blocks in a linear polymer must be set explicitly by calling setVertexIds with consecutive values, as done in the function Pscf::PolymerTmpl::readParameters.
Different text representations are used for bead and thread models, and for linear and branched polymers:
Thread model:
In the thread model, if PolymerModel::isThread(), the text representation of an Edge for a branched polymer is:
monomerId length vertexId(0) vertexid(1)
Here, length is a floating point number. For a linear polymer in the thread model, the vertex ids are omitted, because the vertex ids for block id of linear polymer must be equal to id and id + 1.
Bead model:
In the bead model, if PolymerModel::isBead(), the text representation for a branched polymer is:
monomerId nBead vertexId(0) vertexid(1)
where nBead is the integer number of beads in the chain. The corresponding text representation for a bead-spring linear chain omits the vertex ids, as for the thread model.
Parameters
in input stream
block Edge to be read from stream
Returns
modified input stream
Definition at line 83 of file Edge.cpp.
operator<<() [1/7]
std::ostream & Pscf::operator<< (std::ostream & out, Edge const & block)
Output stream inserter (<<) for a Edge.
Different text representations are used for linear and branched polymers, as discussed in documentation for the stream extractor (>>) operator. Vertex ids are output only for blocks of branched polymers.
Parameters
out output stream
block Edge to be written to stream
Returns
modified output stream
Definition at line 108 of file Edge.cpp.
operator>>() [2/7]
std::istream & Pscf::operator>> (std::istream & in, Monomer & monomer)
Stream extractor (>>) for a Monomer.
The text representation is given by the value of the kuhn data member (i.e., the monomer statistical segment length). The type id is thus not read from a stream, and so must be set explicitly with setId.
Parameters
in input stream
monomer Monomer to be read from stream
Returns
modified input stream
Definition at line 24 of file Monomer.cpp.
operator<<() [2/7]
std::ostream & Pscf::operator<< (std::ostream & out, const Monomer & monomer)
Stream inserter (<<) for a Monomer.
Parameters
out output stream
monomer Monomer to be written to stream
Returns
modified output stream
Definition at line 34 of file Monomer.cpp.
operator>>() [3/7]
std::istream & Pscf::operator>> (std::istream & in, Species::Ensemble & policy)
istream extractor for a Species::Ensemble enumeration.
Parameters
in input stream
policy Species::Ensemble to be read
Returns
modified input stream
Definition at line 77 of file Species.cpp.
References UTIL_THROW.
operator<<() [3/7]
std::ostream & Pscf::operator<< (std::ostream & out, Species::Ensemble policy)
ostream inserter for an Species::Ensemble enumeration.
Text representations of allowed values are "Open" and "Closed".
Parameters
out output stream
policy Species::Ensemble to be written
Returns
modified output stream
Definition at line 95 of file Species.cpp.
serialize()
template<class Archive> void Pscf::serialize (Archive & ar, Species::Ensemble & policy, const unsigned int version)
Serialize a Species::Ensemble.
Parameters
ar archive object
policy object to be serialized
version archive version id
Definition at line 198 of file Species.h.
References Util::serializeEnum().
gpuAssert()
void Pscf::gpuAssert (cudaError_t err, const char * file, int line) inline
Check if CUDA API function returns cudaSuccess (used by cudaErrorCheck macro).
Parameters
err cudaError_t object returned from CUDA API function
file filename where cudaErrorCheck was called
line line number where cudaErrorCheck was called
Definition at line 54 of file cudaErrorCheck.h.
operator>>() [4/7]
template<int D, typename T> std::istream & Pscf::operator>> (std::istream & in, IntVec< D, T > & vector)
istream extractor for a IntVec<D, T>.
Input elements of a vector from stream, without line breaks.
Parameters
in input stream
vector IntVec<D, T> to be read from stream
Returns
modified input stream
Definition at line 85 of file IntVec.h.
operator<<() [4/7]
template<int D, typename T> std::ostream & Pscf::operator<< (std::ostream & out, const IntVec< D, T > & vector)
ostream inserter for a IntVec<D, T>.
Output a IntVec<D, T> to an ostream, without line breaks.
Output elements of a vector to stream, without line breaks.
Parameters
out output stream
vector IntVec<D, T> to be written to stream
Returns
modified output stream
Definition at line 104 of file IntVec.h.
References Pscf::IntVec< D, T >::Width.
operator==() [1/3]
template<int D, typename T> bool Pscf::operator== (const IntVec< D, T > & v1, const IntVec< D, T > & v2) inline
Equality of two IntVec<D> objects.
Returns
true if v1 == v2, false otherwise.
Definition at line 120 of file IntVec.h.
operator==() [2/3]
template<int D, typename T> bool Pscf::operator== (const IntVec< D, T > & v1, const Vec< D, T > & v2) inline
Equality of an IntVec<D> and a Vec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 137 of file IntVec.h.
operator==() [3/3]
template<int D, typename T> bool Pscf::operator== (const Vec< D, T > & v1, const IntVec< D, T > & v2) inline
Equality of an Vec<D, T> and an IntVec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 154 of file IntVec.h.
operator!=() [1/3]
template<int D, typename T> bool Pscf::operator!= (const IntVec< D, T > & v1, const IntVec< D, T > & v2) inline
Inequality of two IntVec<D, T> objects.
Returns
true if v1 != v2, false if v1 == v2.
Definition at line 164 of file IntVec.h.
operator!=() [2/3]
template<int D, typename T> bool Pscf::operator!= (const IntVec< D, T > & v1, const Vec< D, T > & v2) inline
Inequality of an IntVec<D> and a Vec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 174 of file IntVec.h.
operator!=() [3/3]
template<int D, typename T> bool Pscf::operator!= (const Vec< D, T > & v1, const IntVec< D, T > & v2) inline
Inequality of a Vec<D, T> and an IntVec<D, T>
Returns
true if v1 == v2, false otherwise.
Definition at line 184 of file IntVec.h.
operator<()
template<int D, typename T> bool Pscf::operator< (const IntVec< D, T > & v1, const IntVec< D, T > & v2) inline
Less than comparison for two IntVec<D, T>s.
Elements with lower array indices are treated as more signficant.
Returns
true if v1 < v2, false otherwise.
Definition at line 196 of file IntVec.h.
operator<=()
template<int D, typename T> bool Pscf::operator<= (const IntVec< D, T > & v1, const IntVec< D, T > & v2) inline
Less than or equal to comparison for two IntVec<D, T>s.
Elements with lower array indices are more signficant digits.
Returns
true if v1 < v2, false otherwise.
Definition at line 220 of file IntVec.h.
operator>()
template<int D, typename T> bool Pscf::operator> (const IntVec< D, T > & v1, const IntVec< D, T > & v2) inline
Greater than comparison for two IntVec<D, T>s.
Returns
true if v1 > v2, false otherwise.
Definition at line 242 of file IntVec.h.
operator>=()
template<int D, typename T> bool Pscf::operator>= (const IntVec< D, T > & v1, const IntVec< D, T > & v2) inline
Greater than or equal to comparison for two IntVec<D, T>s.
Returns
true if v1 >= v2, false otherwise.
Definition at line 252 of file IntVec.h.
operator>>() [5/7]
template<int D, typename T> std::istream & Pscf::operator>> (std::istream & in, RealVec< D, T > & vector)
istream extractor for a RealVec<D, T>.
Input elements of a vector from stream, without line breaks.
Parameters
in input stream
vector RealVec<D, T> to be read from stream
Returns
modified input stream
Definition at line 89 of file RealVec.h.
operator<<() [5/7]
template<int D, typename T> std::ostream & Pscf::operator<< (std::ostream & out, const RealVec< D, T > & vector)
ostream inserter for a RealVec<D, T>.
Output a RealVec<D, T> to an ostream, without line breaks.
Output elements of a vector to stream, without line breaks.
Parameters
out output stream
vector RealVec<D, T> to be written to stream
Returns
modified output stream
Definition at line 108 of file RealVec.h.
References Pscf::RealVec< D, T >::Precision, and Pscf::RealVec< D, T >::Width.
dot()
template<int D, typename T> T Pscf::dot (Vec< D, T > const & v1, Vec< D, T > const & v2) inline
Return dot product of two vectors.
Parameters
v1 first input vector
v2 second input vector
Returns
dot product v1.v2
Definition at line 285 of file Vec.h.
References Util::setToZero().
operator+()
template<int D, typename T> Vec< D, T > Pscf::operator+ (Vec< D, T > const & v1, Vec< D, T > const & v2) inline
Return the sum of two vectors.
Parameters
v1 first input vector
v2 second input vector
Returns
sum v1 + v2
Definition at line 304 of file Vec.h.
References Pscf::Vec< D, T >::add().
operator>>() [6/7]
template<int D> std::istream & Pscf::operator>> (std::istream & in, Mesh< D > & mesh)
Input stream extractor for reading a Mesh<D> object.
Parameters
in input stream
mesh Mesh<D> object to be read
Returns
modified input stream
Definition at line 245 of file Mesh.h.
operator<<() [6/7]
template<int D> std::ostream & Pscf::operator<< (std::ostream & out, Mesh< D > const & mesh)
Output stream inserter for writing a Mesh<D> object.
Parameters
out output stream
mesh Mesh<D> to be written
Returns
modified output stream
Definition at line 257 of file Mesh.h.
operator>>() [7/7]
std::istream & Pscf::operator>> (std::istream & is, fftw_complex & z)
Stream extraction operator for fftw_complex.
Parameters
is input stream
z complex number
operator<<() [7/7]
std::ostream & Pscf::operator<< (std::ostream & os, fftw_complex const & z)
Stream insertion operator for fftw_complex.
Parameters
os output stream
z complex number
Returns
modified output stream