PSCF: Pscf::Rpc Namespace Reference
Pscf::Rpc Namespace Reference
Real periodic fields, SCFT and PS-FTS (CPU).
Classes
class AmCompressor
Anderson Mixing compressor.
class AmIteratorBasis
Rpc implementation of the Anderson Mixing iterator with symmetry.
class Analyzer
Abstract base for periodic output and/or analysis actions.
class AnalyzerFactory
Factory for subclasses of Analyzer.
class AnalyzerManager
Manager for a list of Analyzer objects.
class AverageAnalyzer
Analyze averages and block averages of several real variables.
class AverageListAnalyzer
Analyze averages and block averages of several real variables.
class BasisFieldState
FieldState for fields in symmetry-adapted basis format.
class BdSimulator
Brownian dynamics simulator for PS-FTS.
class BdStep
BdStep is an abstract base class for Brownian dynamics steps.
class BdStepFactory
Factory for subclasses of BdStep.
class BFieldComparison
Comparator for fields in symmetry-adapted basis format.
class BinaryStructureFactorGrid
BinaryStructureFactorGrid evaluates AB copolymer structure factors.
class Block
Block within a linear or branched block polymer.
class CFields
A list of c fields stored in both basis and r-grid format.
class ChiDerivative
Evaluate the derivative of H with respect to chi.
class Compressor
Base class for iterators that impose incompressibility.
class CompressorFactory
Factory for subclasses of Compressor.
class ConcentrationDerivative
Evaluate the derivative of H with respect to concentration.
class ConcentrationWriter
Periodically write snapshots to a trajectory file.
class Domain
Spatial domain for a periodic structure with real fields, on a CPU.
class EinsteinCrystalPerturbation
Perturbation for Einstein crystal thermodynamic integration method.
class EnvironmentFactory
Factory for subclasses of Environment.
class ExplicitBdStep
BdStep is an abstract base class for Brownian dynamics steps.
class FieldIo
File input/output operations and format conversions for fields.
class FieldState
Record of a state of a System (fields + unit cell).
class FilmEnvironment
Class defining mask & external fields for thin-film systems.
class FilmFieldGenExt
Field Generator for external fields in thin-film systems.
class FilmFieldGenMask
Field Generator for thin-film masks.
class ForceBiasMove
ForceBiasMove attempts a Brownian dynamics move.
class FourthOrderParameter
FourthOrderParameter is used to detect an order-disorder transition.
class HamiltonianAnalyzer
Compute averages and output block averages of Hamiltonian components.
class IntraCorrelation
Intramolecular correlation analysis for LR compressors.
class Iterator
Base class for iterative solvers for SCF equations.
class IteratorFactory
Factory for subclasses of Iterator.
class LinearRamp
Linear ramp - parameters vary linearly with step index.
class LinearSweep
Sweep in which parameters vary linearly with sweep variable s.
class LMBdStep
Leimkuhler-Matthews Brownian dynamics stepper.
class LrAmCompressor
Anderson Mixing compressor with linear-response mixing step.
class LrCompressor
Linear response compressor.
class Mask
A field to which the total density is constrained.
class MaxOrderParameter
MaxOrderParameter is used to detect an order-disorder transition.
class McMove
McMove is an abstract base class for Monte Carlo moves.
class McMoveFactory
Factory for subclasses of McMove.
class McMoveManager
Manager for a set of McMove objects.
class McSimulator
Monte-Carlo simulation coordinator.
class Mixture
Solver and descriptor for a mixture of polymers and solvents.
class MixtureModifier
Parameter modifier for an associated Mixture.
class Perturbation
Base class for additive perturbations of standard FTS Hamiltonian.
class PerturbationDerivative
Evaluate the derivative of H w/ respect to perturbation parameter lambda.
class PerturbationFactory
Factory for subclasses of Perturbation.
class Polymer
Descriptor and solver for one polymer species.
class PredCorrBdStep
Predictor-corrector Brownian dynamics stepper.
class Propagator
MDE solver for one direction of one block.
class Ramp
Class that varies parameters during a simulation (abstract).
class RampFactory
Factory for subclasses of Ramp.
class RampParameter
Class for storing data about an individual ramp parameter.
class RealMove
RealMove generates spatially uncorrelated random field changes.
class RGridTrajectoryReader
Trajectory file reader.
class ScftThermo
Computes SCFT free energies.
struct SimState
SimState stores the state used by an FTS simulation.
class Simulator
Field theoretic simulator (base class).
class SimulatorFactory
Factory for subclasses of Simulator.
class Solvent
Solver and descriptor for a solvent species.
class StepLogger
Periodically write snapshots to a trajectory file.
class Sweep
Solve a sequence of SCFT problems along a line in parameter space.
class SweepFactory
Default Factory for subclasses of Sweep.
class SweepParameter
Class for storing data about an individual sweep parameter.
class System
Main class, representing a complete physical system.
class SystemConstRef
Const access to a System<D>.
class TrajectoryReader
Trajectory file reader (base class).
class TrajectoryReaderFactory
Factory for subclasses of TrajectoryReader.
class TrajectoryWriter
Periodically write snapshots to a trajectory file.
class Types
List of aliases for types used the in Rpc namespace.
class WFields
A container of fields stored in both basis and r-grid format.
Functions
template<int D>
std::istream & operator>> (std::istream &in, RampParameter< D > &param)
Inserter for reading a RampParameter from an istream.
template<int D>
std::ostream & operator<< (std::ostream &out, RampParameter< D > const &param)
Extractor for writing a RampParameter to ostream.
template<int D>
void run (int argc, char **argv)
Function template for main pscf_pc program.
template<int D>
std::istream & operator>> (std::istream &in, SweepParameter< D > &param)
Inserter for reading a SweepParameter from an istream.
template<int D>
std::ostream & operator<< (std::ostream &out, SweepParameter< D > const &param)
Extractor for writing a SweepParameter to ostream.
Detailed Description
Real periodic fields, SCFT and PS-FTS (CPU).
All field theoretic simulation (FTS) methods implemented in this namespace rely on a partial saddle point approximation (PSA), which allows the use of real chemical potential fields.
Function Documentation
operator>>() [1/2]
template<int D> std::istream & Pscf::Rpc::operator>> (std::istream & in, RampParameter< D > & param)
Inserter for reading a RampParameter from an istream.
Parameters
in input stream
param RampParameter<D> object to read
Definition at line 278 of file rpc/fts/ramp/RampParameter.tpp.
operator<<() [1/2]
template<int D> std::ostream & Pscf::Rpc::operator<< (std::ostream & out, RampParameter< D > const & param)
Extractor for writing a RampParameter to ostream.
Parameters
out output stream
param RampParameter<D> object to write
Definition at line 301 of file rpc/fts/ramp/RampParameter.tpp.
References Pscf::Rpc::RampParameter< D >::id(), and Pscf::Rpc::RampParameter< D >::writeParamType().
operator>>() [2/2]
template<int D> std::istream & Pscf::Rpc::operator>> (std::istream & in, SweepParameter< D > & param)
Inserter for reading a SweepParameter from an istream.
Parameters
in input stream
param SweepParameter<D> object to read
Definition at line 279 of file rpc/scft/sweep/SweepParameter.tpp.
operator<<() [2/2]
template<int D> std::ostream & Pscf::Rpc::operator<< (std::ostream & out, SweepParameter< D > const & param)
Extractor for writing a SweepParameter to ostream.
Parameters
out output stream
param SweepParameter<D> object to write
Definition at line 299 of file rpc/scft/sweep/SweepParameter.tpp.
References Pscf::Rpc::SweepParameter< D >::id(), and Pscf::Rpc::SweepParameter< D >::writeParamType().